package dev.mineagent.runtime.core.objects;
import org.junit.jupiter.api.Test;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
class BasicMeshesTest {
    private static String model(String primitive){return "{\"version\":2,\"primitives\":["+primitive+"],\"collision\":[-2,0,-2,2,4,2]}";}
    private static String primitive(String type,String args,String axis){return "{\"type\":\""+type+"\",\"center\":[0,1,0],\"axis\":\""+axis+"\",\"color\":\"#ffffff\",\"smooth\":true,"+args+"}";}
    static Map<String,String> shapes(){return Map.ofEntries(Map.entry("box","\"size\":[.4,.6,.8]"),Map.entry("plane","\"size\":[.4,.8]"),Map.entry("disc","\"radius\":.3"),Map.entry("annulus","\"innerRadius\":.1,\"outerRadius\":.3"),Map.entry("cylinder","\"radius\":.3,\"height\":.6"),Map.entry("cone","\"radius\":.3,\"height\":.6"),Map.entry("frustum","\"radiusBottom\":.3,\"radiusTop\":.1,\"height\":.6"),Map.entry("prism","\"radius\":.3,\"height\":.6,\"sides\":3"),Map.entry("pyramid","\"radius\":.3,\"height\":.6,\"sides\":4"),Map.entry("ellipsoid","\"radii\":[.2,.3,.4]"),Map.entry("capsule","\"radius\":.2,\"height\":.8"));}
    @Test void allShapesHaveFiniteUnitNormalsCorrectWindingAndAllAxes(){for(var e:shapes().entrySet())for(String axis:List.of("x","y","z")){var mesh=RuntimeMesh.parse(model(primitive(e.getKey(),e.getValue().replace(":.",":0.").replace("[.","[0.").replace(",.",",0."),axis)));for(var v:mesh.vertices())assertEquals(1,Math.sqrt(v.nx()*v.nx()+v.ny()*v.ny()+v.nz()*v.nz()),1e-6,e.getKey());for(var t:mesh.triangles()){var a=mesh.vertices().get(t.a());var b=mesh.vertices().get(t.b());var c=mesh.vertices().get(t.c());double x=(b.y()-a.y())*(c.z()-a.z())-(b.z()-a.z())*(c.y()-a.y()),y=(b.z()-a.z())*(c.x()-a.x())-(b.x()-a.x())*(c.z()-a.z()),z=(b.x()-a.x())*(c.y()-a.y())-(b.y()-a.y())*(c.x()-a.x());assertTrue(x*(a.nx()+b.nx()+c.nx())+y*(a.ny()+b.ny()+c.ny())+z*(a.nz()+b.nz()+c.nz())>0,e.getKey()+axis);}}}
    @Test void discoverableExampleIsActuallyValidAndBadRootsReturnRepairableFieldHints()throws Exception{var json=new com.fasterxml.jackson.databind.ObjectMapper();String source=json.writeValueAsString(ModelGeometryTools.capabilities().get("minimalModel"));assertEquals("GEOMETRY_VALIDATED_NOT_EXECUTED",ModelGeometryTools.inspect(source,"world").get("status"));assertEquals("GEOMETRY_VALIDATED_NOT_EXECUTED",ModelGeometryTools.inspect(source,"item").get("status"));var failure=ModelGeometryTools.rejection("{\"primitives\":[{\"type\":\"box\",\"color\":[1,1,1]}]}",new IllegalArgumentException("RUNTIME_MESH_INVALID"));String hints=failure.get("details").toString();assertTrue(hints.contains("/version"));assertTrue(hints.contains("/collision"));assertTrue(hints.contains("/size"));assertTrue(hints.contains("/color"));}
    @Test void capsulesAtSphereLimitAndReverseConesRemainValid(){RuntimeMesh.parse(model(primitive("capsule","\"radius\":0.2,\"height\":0.4","y")));RuntimeMesh.parse(model(primitive("frustum","\"radiusBottom\":0,\"radiusTop\":0.2,\"height\":0.4","z")));}
    @Test void sharedBudgetAndMalformedValuesAreRejected(){String big=primitive("ellipsoid","\"radii\":[1,1,1],\"segments\":96,\"rings\":48","y");assertThrows(IllegalArgumentException.class,()->RuntimeMesh.parse(model(big)));for(String bad:List.of(primitive("capsule","\"radius\":1,\"height\":1","y"),primitive("box","\"size\":[1,-1,1]","y"),primitive("cone","\"radius\":1,\"height\":1,\"segments\":2147483648","y"),primitive("annulus","\"innerRadius\":1,\"outerRadius\":1","y")))assertThrows(IllegalArgumentException.class,()->RuntimeMesh.parse(model(bad)));}
}
