package dev.mineagent.runtime.neoforge.task;
import com.fasterxml.jackson.databind.*;
import dev.mineagent.runtime.api.directory.ObjectRef;
import dev.mineagent.runtime.api.permission.PermissionAction;
import dev.mineagent.runtime.api.task.*;
import dev.mineagent.runtime.core.directory.*;
import dev.mineagent.runtime.core.task.*;
import dev.mineagent.runtime.neoforge.*;
import dev.mineagent.runtime.neoforge.body.MineAgentPlayer;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.tick.ServerTickEvent;
import java.nio.file.*;
import java.util.*;

/** Two actual JVMs and one real viewer. Fixed Native tool requests; not model selection or multiplayer delivery. */
@EventBusSubscriber(modid="mineagent_runtime")
public final class AudienceSmokeServer {
    private static final ObjectMapper JSON=new ObjectMapper();public static volatile boolean ready,finished;public static volatile String failure;
    private static int phase,ticks;private static UUID agent,task,batch,snapAudience,liveAudience,pending,latestLive;
    private static AudienceStore.Snapshot snapFirst,liveFirst;private static String red,blue,previousTeam;private static Set<PermissionAction> grants;
    public static boolean enabled(){return Boolean.getBoolean("mineagent.audienceSmoke");}
    public static String stage(){return System.getProperty("mineagent.audienceStage","prepare");}
    private static Path root(MinecraftServer server)throws Exception{var root=server.getServerDirectory().resolve("audience-evidence");Files.createDirectories(root);return root;}
    private static void save(MinecraftServer server,String name,Object value)throws Exception{Files.writeString(root(server).resolve(stage()+"-"+name+".json"),JSON.writeValueAsString(value));}
    private static void require(boolean value,String code){if(!value)throw new IllegalStateException(code);}
    private static ManagedTask task(MinecraftServer server){return MineAgentRuntimeServices.tasks(server).get(task).orElseThrow();}
    private static AudienceStore.Create create(String mode,String team){return new AudienceStore.Create(mode,new ObjectQuery(ObjectRef.Kind.PLAYER,"","EXACT",List.of(),team,"",null,null,32,""),7200);}
    private static String createArgs(String mode,String team)throws Exception{var c=create(mode,team);return JSON.writeValueAsString(Map.of("mode",mode,"query",JSON.readTree(c.query().canonical()),"ttl_seconds",7200));}
    private static void submit(MinecraftServer server,String tool,Map<String,Object> args)throws Exception{submit(server,tool,JSON.writeValueAsString(args));}
    private static void submit(MinecraftServer server,String tool,String args)throws Exception{batch=MineAgentRuntimeServices.taskExecutor(server).worldActions().submit(task(server),List.of(Map.of("id","audience-"+UUID.randomUUID(),"name",tool,"arguments",args))).batchId();}
    private static WorldActionJournal.Batch batch(MinecraftServer server){return MineAgentRuntimeServices.taskExecutor(server).worldActions().list(task(server).ownerPlayerId()).stream().filter(b->b.batchId().equals(batch)).findFirst().orElseThrow();}
    private static void grant(MinecraftServer server,UUID owner,Set<PermissionAction> set)throws Exception{
        var config=MineAgentRuntimeServices.config(server);String value=set.stream().map(Enum::name).sorted().collect(java.util.stream.Collectors.joining(","));require(config.apply(new dev.mineagent.runtime.api.config.ConfigPatch(config.snapshot().revision(),Map.of("runtime.initialized","true","voice.output.enabled","false","permission.player."+owner,value)),true).accepted(),"AUDIENCE_PERMISSION_PERSIST_FAILED");MineAgentRuntimeServices.permissions(server).setTrustedActions(owner,set);
    }
    private static void journal(MinecraftServer server)throws Exception{Files.writeString(root(server).resolve("journal.json"),JSON.writeValueAsString(Map.of("agent",agent,"task",task,"snap",snapAudience,"live",liveAudience,"pending",pending,"red",red,"blue",blue,"previousTeam",previousTeam,"grants",grants)));}
    @SubscribeEvent public static void tick(ServerTickEvent.Post event)throws Exception{
        if(!enabled()||finished||failure!=null)return;var server=event.getServer();var viewer=server.getPlayerList().getPlayers().stream().filter(p->!(p instanceof MineAgentPlayer)).findFirst().orElse(null);if(viewer==null)return;ticks++;
        try{
            require(ticks<1600,"AUDIENCE_NATIVE_TIMEOUT");var actions=MineAgentRuntimeServices.taskExecutor(server).worldActions();var runtime=actions.audiences();var store=runtime.store();
            if(phase==0){
                if(stage().equals("prepare")){
                    grants=MineAgentRuntimeServices.permissions(server).trustedActions(viewer.getUUID());var allowed=new HashSet<>(grants);allowed.add(PermissionAction.DISCOVER_OBJECTS);grant(server,viewer.getUUID(),allowed);
                    previousTeam=viewer.getTeam()==null?"":viewer.getTeam().getName();red="aud_r_"+UUID.randomUUID().toString().substring(0,6);blue="aud_b_"+UUID.randomUUID().toString().substring(0,6);server.getScoreboard().addPlayerTeam(red);server.getScoreboard().addPlayerTeam(blue);server.getScoreboard().addPlayerToTeam(viewer.getScoreboardName(),server.getScoreboard().getPlayerTeam(red));
                    agent=MineAgentRuntimeServices.bodies(server).createPersistentAt("持久受众 Actor",viewer.getUUID(),server.overworld(),viewer.position().add(2,0,0)).agentId();var tasks=MineAgentRuntimeServices.tasks(server);var t=tasks.create(agent,viewer.getUUID(),"持久受众固定工具验收；不是发送或显示",20,List.of(new TaskStepSpec("fixture_plan",Set.of()),new TaskStepSpec("execute",Set.of("fixture_plan"))));task=tasks.completeStep(t.taskId(),t.revision(),"fixture_plan").task().taskId();
                    ready=true;submit(server,"create_audience",createArgs("SNAPSHOT",red));phase=1;
                }else{
                    require(stage().equals("resume"),"AUDIENCE_STAGE_INVALID");var saved=JSON.readTree(Files.readString(root(server).resolve("journal.json")));agent=UUID.fromString(saved.path("agent").asText());task=UUID.fromString(saved.path("task").asText());snapAudience=UUID.fromString(saved.path("snap").asText());liveAudience=UUID.fromString(saved.path("live").asText());pending=UUID.fromString(saved.path("pending").asText());red=saved.path("red").asText();blue=saved.path("blue").asText();previousTeam=saved.path("previousTeam").asText();var restored=new HashSet<PermissionAction>();saved.path("grants").forEach(n->restored.add(PermissionAction.valueOf(n.asText())));grants=Set.copyOf(restored);
                    if(MineAgentRuntimeServices.bodies(server).body(agent).isEmpty())return;require(task(server).status()==TaskStatus.RUNNING,"AUDIENCE_TASK_NOT_RESTORED");
                    snapFirst=JSON.readValue(Files.readString(root(server).resolve("prepare-first-snapshot.json")),AudienceStore.Snapshot.class);liveFirst=JSON.readValue(Files.readString(root(server).resolve("prepare-first-live.json")),AudienceStore.Snapshot.class);
                    var c=runtime.context(task(server),UUID.randomUUID());require(store.inspect(c,snapAudience).members().equals(List.of(viewer.getUUID())),"AUDIENCE_FIXED_MEMBERS_LOST");
                    require(store.resolve(runtime.context(task(server),snapFirst.context().operationId()),snapAudience,1,snapFirst.triggerId()).equals(snapFirst),"AUDIENCE_RESTART_SNAPSHOT_REPLAY_CHANGED");require(store.resolve(runtime.context(task(server),liveFirst.context().operationId()),liveAudience,1,liveFirst.triggerId()).equals(liveFirst),"AUDIENCE_RESTART_LIVE_REPLAY_CHANGED");
                    var unknown=store.operation(c,pending);require(unknown.state().equals("INTERRUPTED"),"AUDIENCE_PENDING_RESTART_NOT_FENCED");boolean refused=false;try{store.create(runtime.context(task(server),pending),create("SNAPSHOT",red));}catch(IllegalStateException expected){refused=expected.getMessage().equals("AUDIENCE_OPERATION_INTERRUPTED");}require(refused&&runtime.selectionCalls()==0,"AUDIENCE_UNKNOWN_RESELECTED");save(server,"restart",Map.of("fixed",store.inspect(c,snapAudience),"firstSnapshot",snapFirst,"firstLive",liveFirst,"pending",unknown,"selections",runtime.selectionCalls()));
                    server.getScoreboard().addPlayerToTeam(viewer.getScoreboardName(),server.getScoreboard().getPlayerTeam(red));ready=true;submit(server,"resolve_audience",Map.of("audience_id",snapAudience,"expected_revision",1));phase=21;
                }return;
            }
            var b=batch(server);if(ticks%20==0)save(server,"progress",Map.of("phase",phase,"batch",b.state(),"ticks",ticks));if(!b.state().equals("COMPLETED")){require(!Set.of("FAILED","INTERRUPTED").contains(b.state()),"AUDIENCE_NATIVE_ACTION_FAILED_"+phase+"_"+b.error());return;}
            save(server,"phase-"+phase,b);var result=b.receipts().getLast().after().get("result");
            switch(phase){
                case 1->{snapAudience=JSON.readValue(result,AudienceStore.Definition.class).audienceId();submit(server,"create_audience",createArgs("LIVE_AT_TRIGGER",blue));phase=2;}
                case 2->{liveAudience=JSON.readValue(result,AudienceStore.Definition.class).audienceId();require(runtime.selectionCalls()==1,"AUDIENCE_LIVE_CREATED_WITH_SELECTION");submit(server,"resolve_audience",Map.of("audience_id",snapAudience,"expected_revision",1));phase=3;}
                case 3->{snapFirst=JSON.readValue(result,AudienceStore.Snapshot.class);require(snapFirst.recipients().size()==1&&snapFirst.recipients().getFirst().status().equals("ELIGIBLE"),"AUDIENCE_INITIAL_FIXED_TARGET");save(server,"first-snapshot",snapFirst);submit(server,"resolve_audience",Map.of("audience_id",liveAudience,"expected_revision",1));phase=4;}
                case 4->{liveFirst=JSON.readValue(result,AudienceStore.Snapshot.class);require(liveFirst.recipients().isEmpty(),"AUDIENCE_INITIAL_BLUE_NOT_EMPTY");save(server,"first-live",liveFirst);server.getScoreboard().addPlayerToTeam(viewer.getScoreboardName(),server.getScoreboard().getPlayerTeam(blue));
                    var a=store.resolve(runtime.context(task(server),snapFirst.context().operationId()),snapAudience,1,snapFirst.triggerId());var l=store.resolve(runtime.context(task(server),liveFirst.context().operationId()),liveAudience,1,liveFirst.triggerId());var linked=store.resolve(runtime.context(task(server),UUID.randomUUID()),liveAudience,1,liveFirst.triggerId());require(a.equals(snapFirst)&&l.equals(liveFirst)&&linked.equals(liveFirst)&&runtime.selectionCalls()==2,"AUDIENCE_RETRY_EXPANDED_MEMBERS");save(server,"duplicate-trigger",Map.of("fixed",a,"live",l,"linked",linked,"selections",runtime.selectionCalls()));submit(server,"resolve_audience",Map.of("audience_id",snapAudience,"expected_revision",1));phase=5;}
                case 5->{var s=JSON.readValue(result,AudienceStore.Snapshot.class);require(s.recipients().size()==1&&s.recipients().getFirst().status().equals("FILTER_CHANGED"),"AUDIENCE_FIXED_GROUP_REEXPANDED");save(server,"fixed-after-team-change",s);submit(server,"resolve_audience",Map.of("audience_id",liveAudience,"expected_revision",1));phase=6;}
                case 6->{var s=JSON.readValue(result,AudienceStore.Snapshot.class);require(s.recipients().size()==1&&s.recipients().getFirst().status().equals("ELIGIBLE"),"AUDIENCE_LIVE_DID_NOT_EXPAND");save(server,"live-after-team-change",s);latestLive=s.snapshotId();submit(server,"inspect_audience",Map.of("kind","DEFINITION","id",snapAudience));phase=7;}
                case 7->{require(JSON.readTree(result).path("members").size()==1,"AUDIENCE_INSPECT_DEFINITION");submit(server,"inspect_audience",Map.of("kind","SNAPSHOT","id",latestLive));phase=8;}
                case 8->{require(JSON.readTree(result).path("state").asText().equals("RESOLVED"),"AUDIENCE_INSPECT_SNAPSHOT");pending=UUID.randomUUID();var prepared=store.beginCreate(runtime.context(task(server),pending),create("SNAPSHOT",red));require(prepared.dispatch(),"AUDIENCE_PENDING_ALREADY_EXISTS");save(server,"pending-intent",prepared);journal(server);submit(server,"inspect_audience",Map.of("kind","OPERATION","id",pending));phase=9;}
                case 9->{require(JSON.readTree(result).path("state").asText().equals("PENDING")&&runtime.selectionCalls()==3,"AUDIENCE_PENDING_INSPECTION");save(server,"result",Map.of("status","AUDIENCE_PREPARE_VERIFIED","selections",runtime.selectionCalls(),"modelCalls",0,"systemInputInjected",false,"fullV1",false));finished=true;}
                case 21->{var s=JSON.readValue(result,AudienceStore.Snapshot.class);require(s.recipients().size()==1&&s.recipients().getFirst().status().equals("ELIGIBLE")&&!s.recipients().getFirst().ref().generation().equals(snapFirst.recipients().getFirst().ref().generation()),"AUDIENCE_NEW_CONNECTION_NOT_REVALIDATED");save(server,"new-connection-snapshot",s);submit(server,"resolve_audience",Map.of("audience_id",liveAudience,"expected_revision",1));phase=22;}
                case 22->{var s=JSON.readValue(result,AudienceStore.Snapshot.class);require(s.recipients().isEmpty(),"AUDIENCE_RESTART_LIVE_FILTER");latestLive=s.snapshotId();save(server,"new-trigger-live",s);var t=MineAgentRuntimeServices.tasks(server).create(agent,viewer.getUUID(),"不同任务trigger上下文负向",1,List.of(new TaskStepSpec("independent_wait",Set.of())));boolean rejected=false;try{store.resolve(runtime.context(t,UUID.randomUUID()),liveAudience,1,liveFirst.triggerId());}catch(IllegalArgumentException expected){rejected=expected.getMessage().equals("AUDIENCE_TRIGGER_CONTEXT_REUSED");}require(rejected,"AUDIENCE_TRIGGER_REBOUND_TO_OTHER_TASK");save(server,"other-task-denied",Map.of("rejected",true));submit(server,"revoke_audience",Map.of("audience_id",snapAudience,"expected_revision",1));phase=23;}
                case 23->{require(JSON.readTree(result).path("state").asText().equals("REVOKED"),"AUDIENCE_REVOKE_FAILED");boolean rejected=false;try{store.resolve(runtime.context(task(server),snapFirst.context().operationId()),snapAudience,1,snapFirst.triggerId());}catch(IllegalStateException expected){rejected=true;}require(rejected,"AUDIENCE_REVOKED_REPLAY_ALLOWED");
                    var old=runtime.context(task(server),liveFirst.context().operationId());var allowed=new HashSet<>(MineAgentRuntimeServices.permissions(server).trustedActions(viewer.getUUID()));var denied=new HashSet<>(allowed);denied.remove(PermissionAction.DISCOVER_OBJECTS);grant(server,viewer.getUUID(),denied);grant(server,viewer.getUUID(),allowed);boolean stale=false;try{store.resolve(old,liveAudience,1,liveFirst.triggerId());}catch(SecurityException expected){stale=true;}require(stale,"AUDIENCE_OLD_GRANT_REVIVED");save(server,"revoke-and-regrant",Map.of("revokedReplayRejected",true,"oldAttemptRejected",true,"selections",runtime.selectionCalls()));submit(server,"resolve_audience",Map.of("audience_id",liveAudience,"expected_revision",1));phase=24;}
                case 24->{var s=JSON.readValue(result,AudienceStore.Snapshot.class);require(s.recipients().isEmpty()&&runtime.selectionCalls()==2,"AUDIENCE_CURRENT_GRANT_RESOLVE");latestLive=s.snapshotId();actions.finishTask(task(server),JSON.writeValueAsString(Map.of("checks",List.of(Map.of("kind","audience_definition","audience_id",snapAudience,"revision",2,"state","REVOKED"),Map.of("kind","audience_snapshot","snapshot_id",latestLive,"minimum_eligible",0)))));require(task(server).status()==TaskStatus.COMPLETED,"AUDIENCE_GOAL_NOT_COMPLETED");save(server,"result",Map.of("status","AUDIENCE_RESTART_AND_LIFECYCLE_VERIFIED","task",task(server),"snapshot",s,"selections",runtime.selectionCalls(),"modelCalls",0,"systemInputInjected",false,"deliveryVerified",false,"fullV1",false));cleanup(server,viewer);finished=true;}
                default->throw new IllegalStateException("AUDIENCE_PHASE_INVALID");
            }
        }catch(Exception e){failure=e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();save(server,"failure",Map.of("phase",phase,"error",e.toString()));}
    }
    private static void cleanup(MinecraftServer server,ServerPlayer viewer)throws Exception{grant(server,viewer.getUUID(),grants);server.getScoreboard().removePlayerFromTeam(viewer.getScoreboardName());if(!previousTeam.isEmpty()&&server.getScoreboard().getPlayerTeam(previousTeam)!=null)server.getScoreboard().addPlayerToTeam(viewer.getScoreboardName(),server.getScoreboard().getPlayerTeam(previousTeam));for(String name:List.of(red,blue)){var t=server.getScoreboard().getPlayerTeam(name);if(t!=null)server.getScoreboard().removePlayerTeam(t);}}
}
