package dev.mineagent.runtime.neoforge.task;
import com.fasterxml.jackson.databind.ObjectMapper;
import dev.mineagent.runtime.core.task.*;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;
import dev.mineagent.runtime.neoforge.network.AutonomyPayloads;
import net.minecraft.core.BlockPos;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.phys.*;
import net.minecraft.core.registries.BuiltInRegistries;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.network.PacketDistributor;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicBoolean;

/** One locally consented session, repeated observed objectives, live path finding and native player input. */
@EventBusSubscriber(modid="mineagent_runtime")
public final class AutonomousPlayerAgent {
    private static final ObjectMapper JSON=new ObjectMapper();private static final UUID NONE=new UUID(0,0);
    private static final Map<MinecraftServer,Map<UUID,Session>> SESSIONS=new IdentityHashMap<>();
    private static final ExecutorService IO=Executors.newSingleThreadExecutor(r->{var t=new Thread(r,"mineagent-autonomy-journal");t.setDaemon(true);return t;});
    private static final class Session {
        final UUID id,agent,world;final ServerPlayer player;final String dimension,name;final AtomicBoolean live=new AtomicBoolean(true);UUID consent=NONE;
        String goal,state="REVIEW",summary="等待本机确认",last="",mode="WAIT";long goalRevision=1,sequence,actionRevision,round,journalRevision,heartbeat=System.currentTimeMillis(),reviewExpires=System.currentTimeMillis()+180000;
        boolean clientPaused,manualPaused,planning;int actionAt,lastPlanAt,stuck,reroutes;Vec3 lastPosition,pausePosition;String pauseSummary="";AutonomyPlan plan;List<ObservedPathfinder.Cell> route=List.of();AtomicBoolean callPermit=new AtomicBoolean();CompletableFuture<Void> saved=CompletableFuture.completedFuture(null);volatile boolean journalFailed;
        Session(ServerPlayer p,UUID a,UUID id,String goal){player=p;agent=a;this.id=id;this.goal=goal;world=MineAgentRuntimeServices.worldId(p.level().getServer());dimension=p.level().dimension().identifier().toString();name=MineAgentRuntimeServices.bodies(p.level().getServer()).definitions().stream().filter(d->d.agentId().equals(a)).findFirst().orElseThrow().displayName();lastPosition=p.position();}
    }
    private AutonomousPlayerAgent(){}
    private static Map<UUID,Session> sessions(MinecraftServer s){return SESSIONS.computeIfAbsent(s,k->new HashMap<>());}
    private static boolean valid(Session j){var s=j.player.level().getServer();return j.live.get()&&!j.journalFailed&&s.getPlayerList().getPlayer(j.player.getUUID())==j.player&&j.player.isAlive()&&!j.player.isSpectator()&&j.world.equals(MineAgentRuntimeServices.worldId(s))&&j.dimension.equals(j.player.level().dimension().identifier().toString())&&ServerTaskStart.allowed(j.player,j.agent);}
    public static boolean active(ServerPlayer p){var j=sessions(p.level().getServer()).get(p.getUUID());return j!=null&&j.live.get();}
    public static Map<String,Object> inspect(ServerPlayer p){var j=sessions(p.level().getServer()).get(p.getUUID());if(j==null)return Map.of("active",false);return Map.of("active",j.live.get(),"session",j.id,"agent",j.agent,"state",j.state,"goal",j.goal,"summary",j.summary,"rounds",j.round,"reroutes",j.reroutes,"lastResult",j.last,"localApprovalCount",j.consent.equals(NONE)?0:1);}
    public static Map<String,Object> submit(ServerPlayer p,UUID agent,UUID operation,String goal)throws Exception{
        if(!p.level().getServer().isSameThread()||!ServerTaskStart.allowed(p,agent)||!p.isAlive()||p.isSpectator()||p.isPassenger()||goal==null||goal.isBlank()||goal.length()>4096||goal.codePoints().anyMatch(c->Character.isISOControl(c)&&c!=10&&c!=13&&c!=9))throw new IllegalArgumentException("AUTONOMY_REQUEST");
        var prior=sessions(p.level().getServer()).get(p.getUUID());if(prior!=null&&prior.live.get()){if(!prior.agent.equals(agent))throw new SecurityException("AUTONOMY_ANOTHER_AGENT_ACTIVE");if(prior.consent.equals(NONE))throw new IllegalStateException("AUTONOMY_START_APPROVAL_PENDING");update(prior,goal);return Map.of("status","GOAL_UPDATED_IN_EXISTING_SESSION","observed",inspect(p));}
        if(Set.of("REVIEW","ARMING","RUNNING","PLANNING","PREPARING").contains(PlayerBodyAgent.observe(p).get("state")))throw new IllegalStateException("AUTONOMY_LEGACY_BUSY");
        var j=new Session(p,agent,operation,goal);sessions(p.level().getServer()).put(p.getUUID(),j);save(j);PacketDistributor.sendToPlayer(p,new AutonomyPayloads.Offer(j.id,p.getUUID(),j.world,j.dimension,j.name,goal));return Map.of("status","AWAITING_LOCAL_START","observed",inspect(p),"continuous",true);
    }
    public static Map<String,Object> control(ServerPlayer p,UUID agent,String action,String goal)throws Exception{var j=sessions(p.level().getServer()).get(p.getUUID());if(j==null||!j.live.get())return Map.of("status","NO_ACTIVE_SESSION");if(!action.equals("stop")&&!j.agent.equals(agent))throw new SecurityException("AUTONOMY_AGENT_MISMATCH");if(!action.equals("stop")&&j.consent.equals(NONE))throw new IllegalStateException("AUTONOMY_START_APPROVAL_PENDING");switch(action){case "stop"->stop(j,"USER_STOP");case "goal"->{if(goal==null||goal.isBlank()||goal.length()>4096||goal.codePoints().anyMatch(c->Character.isISOControl(c)&&c!=10&&c!=13&&c!=9))throw new IllegalArgumentException("AUTONOMY_GOAL");update(j,goal);}case "pause"->{j.manualPaused=true;j.mode="WAIT";j.state="PAUSED";j.summary="按你的要求暂停，接管会话保留";j.callPermit.set(false);j.goalRevision++;j.planning=false;save(j);}case "resume"->{j.manualPaused=false;update(j,j.goal);}default->throw new IllegalArgumentException("AUTONOMY_ACTION");}return Map.of("status","APPLIED","observed",inspect(p));}
    private static void update(Session j,String goal){j.callPermit.set(false);j.goal=goal;j.goalRevision++;j.plan=null;j.route=List.of();j.mode="WAIT";j.planning=false;j.state=j.consent.equals(NONE)?"REVIEW":"OBSERVING";j.summary="目标已更新，重新观察";j.manualPaused=false;save(j);frame(j);}
    public static boolean stopForPlayer(ServerPlayer p){var j=sessions(p.level().getServer()).get(p.getUUID());if(j==null||!j.live.get())return false;stop(j,"USER_STOP");return true;}
    public static void input(ServerPlayer p,AutonomyPayloads.Input message){var j=sessions(p.level().getServer()).get(p.getUUID());if(j==null||j.player!=p||!j.id.equals(message.session())||!j.live.get())return;if(message.kind().equals("STOP")){if(j.consent.equals(NONE)||j.consent.equals(message.consent()))stop(j,"USER_STOP");return;}
        if(message.kind().equals("START")){if(!j.consent.equals(NONE))return;if(!valid(j)||System.currentTimeMillis()>j.reviewExpires||message.consent().equals(NONE)){stop(j,"CONTEXT_CHANGED");return;}j.consent=message.consent();j.state="OBSERVING";j.summary="已开始持续接管";j.heartbeat=System.currentTimeMillis();save(j);frame(j);return;}
        if(!j.consent.equals(message.consent())||j.consent.equals(NONE))return;j.heartbeat=System.currentTimeMillis();if(j.clientPaused!=message.paused()){j.clientPaused=message.paused();j.mode="WAIT";if(j.clientPaused){j.pausePosition=p.position();j.pauseSummary=j.summary;j.summary="界面/失焦暂停，接管会话保留";}else if(!j.manualPaused&&!j.planning){if(!AutonomySessionPolicy.reobserveOnResume(j.state,j.pausePosition==null?Double.POSITIVE_INFINITY:p.position().distanceToSqr(j.pausePosition))){j.mode=j.state.equals("IDLE")?"IDLE":"WAIT";j.summary=j.pauseSummary;}else{j.state="OBSERVING";j.plan=null;j.summary="恢复后重新观察";}}frame(j);}
    }
    private static void save(Session j){try{String value=JSON.writeValueAsString(Map.of("session",j.id,"owner",j.player.getUUID(),"agent",j.agent,"goal",j.goal,"goalRevision",j.goalRevision,"state",j.state,"summary",j.summary,"rounds",j.round,"reroutes",j.reroutes,"position",List.of(j.player.getX(),j.player.getY(),j.player.getZ())));var s=j.player.level().getServer();var db=s.getServerDirectory().resolve("mineagent-runtime-data/runtime.db");j.saved=j.saved.thenRunAsync(()->{try{j.journalRevision=PlayerControlJournal.append(db,j.world,j.id,j.journalRevision,value,System.currentTimeMillis());}catch(Exception e){j.journalFailed=true;throw new CompletionException(e);}},IO);}catch(Exception e){j.journalFailed=true;}}
    private static void frame(Session j){try{if(j.player.level().getServer().getPlayerList().getPlayer(j.player.getUUID())!=j.player)return;var value=new LinkedHashMap<String,Object>();value.put("state",j.state);value.put("goal",j.goal);value.put("summary",j.summary);value.put("mode",j.clientPaused||j.manualPaused||j.planning?"WAIT":j.mode);value.put("route",j.route.stream().limit(16).map(c->List.of(c.x()+.5,(double)c.y(),c.z()+.5)).toList());value.put("target",j.plan==null?List.of(0,0,0):j.plan.target());value.put("slot",j.plan==null?0:j.plan.slot());value.put("actionRevision",j.actionRevision);value.put("round",j.round);value.put("reroutes",j.reroutes);PacketDistributor.sendToPlayer(j.player,new AutonomyPayloads.Frame(j.id,j.consent,++j.sequence,JSON.writeValueAsString(value)));}catch(Exception e){j.live.set(false);}}
    private static void stop(Session j,String reason){if(!j.live.getAndSet(false))return;j.callPermit.set(false);j.mode="WAIT";j.state="STOPPED";j.last=reason;j.summary="已停止："+reason;save(j);frame(j);}
    private static ObservedPathfinder.Cell cell(Vec3 p){return new ObservedPathfinder.Cell(net.minecraft.util.Mth.floor(p.x),net.minecraft.util.Mth.floor(p.y+.1),net.minecraft.util.Mth.floor(p.z));}
    private static boolean hazard(net.minecraft.world.level.block.state.BlockState state){String id=BuiltInRegistries.BLOCK.getKey(state.getBlock()).toString();return !state.getFluidState().isEmpty()||id.contains("fire")||id.contains("lava")||id.contains("cactus")||id.contains("magma")||id.contains("berry_bush")||id.contains("powder_snow");}
    private static ObservedPathfinder.Grid grid(ServerPlayer p){return new ObservedPathfinder.Grid(){final Map<ObservedPathfinder.Cell,Boolean> cache=new HashMap<>();public boolean standable(ObservedPathfinder.Cell c){return cache.computeIfAbsent(c,k->{var pos=new BlockPos(c.x(),c.y(),c.z());var l=p.level();if(!l.isInWorldBounds(pos)||!l.getWorldBorder().isWithinBounds(pos)||!l.getChunkSource().hasChunk(c.x()>>4,c.z()>>4))return false;var floor=l.getBlockState(pos.below());if(hazard(floor)||floor.getCollisionShape(l,pos.below()).isEmpty()||hazard(l.getBlockState(pos))||hazard(l.getBlockState(pos.above())))return false;double w=p.getBbWidth()/2.0;return l.noCollision(p,new AABB(c.x()+.5-w+.001,c.y()+.001,c.z()+.5-w+.001,c.x()+.5+w-.001,c.y()+p.getBbHeight()-.001,c.z()+.5+w-.001));});}public boolean transition(ObservedPathfinder.Cell a,ObservedPathfinder.Cell b){if(b.y()<=a.y())return true;double w=p.getBbWidth()/2.0;return p.level().noCollision(p,new AABB(a.x()+.5-w,a.y()+1.001,a.z()+.5-w,a.x()+.5+w,a.y()+1+p.getBbHeight(),a.z()+.5+w));}};}
    private static void route(Session j){var p=j.player;var target=j.plan.target();j.route=ObservedPathfinder.find(cell(p.position()),cell(new Vec3(target.get(0),target.get(1),target.get(2))),grid(p));j.reroutes++;j.stuck=0;j.lastPosition=p.position();}
    private static String context(Session j)throws Exception{var p=j.player;var landmarks=new ArrayList<Object>();var floor=p.blockPosition();var counts=new TreeMap<String,Integer>();for(var pos:BlockPos.betweenClosed(floor.offset(-10,-2,-10),floor.offset(10,3,10))){if(!p.level().getChunkSource().hasChunk(pos.getX()>>4,pos.getZ()>>4))continue;var block=p.level().getBlockState(pos);if(block.isAir())continue;String id=BuiltInRegistries.BLOCK.getKey(block.getBlock()).toString();counts.merge(id,1,Integer::sum);if(landmarks.size()<48&&!Set.of("minecraft:stone","minecraft:dirt","minecraft:grass_block","minecraft:bedrock").contains(id))landmarks.add(Map.of("block",id,"at",List.of(pos.getX(),pos.getY(),pos.getZ()),"standAbove",List.of(pos.getX()+.5,pos.getY()+1.0,pos.getZ()+.5)));}
        var observations=Map.of("position",List.of(p.getX(),p.getY(),p.getZ()),"yaw",p.getYRot(),"pitch",p.getXRot(),"health",p.getHealth(),"mainHand",p.getMainHandItem().toString(),"landmarks",landmarks,"nearbyBlockCounts",counts,"lastResult",j.last,"reach",p.blockInteractionRange());var def=MineAgentRuntimeServices.bodies(p.level().getServer()).definitions().stream().filter(a->a.agentId().equals(j.agent)).findFirst().orElseThrow();return AutonomyPlan.instructions()+dev.mineagent.runtime.core.agent.PersonaPrompt.section(def,MineAgentRuntimeServices.personas(p.level().getServer()).forModel(def))+"\n原始持续目标："+j.goal+"\n最新真实观察："+JSON.writeValueAsString(observations);}
    private static void plan(Session j){var server=j.player.level().getServer();if(j.planning||!j.saved.isDone())return;try{String prompt=context(j);long revision=j.goalRevision;UUID request=UUID.nameUUIDFromBytes((j.id+"|observe-plan|"+(++j.round)).getBytes(java.nio.charset.StandardCharsets.UTF_8));j.callPermit=new AtomicBoolean(true);var permit=j.callPermit;j.planning=true;j.state="PLANNING";j.mode="WAIT";j.summary="读取当前环境，等待下一步决策";j.lastPlanAt=server.getTickCount();save(j);frame(j);
        MineAgentRuntimeServices.worker(server).streamComplete(MineAgentRuntimeServices.config(server),"PLANNING",prompt,delta->{},()->j.live.get()&&permit.get(),null,request).whenComplete((response,error)->server.execute(()->{if(!j.live.get()||revision!=j.goalRevision||j.callPermit!=permit)return;j.planning=false;if(!valid(j)){stop(j,"CONTEXT_CHANGED");return;}try{if(error!=null||response==null||!response.type().equals("model.stream.result"))throw new IllegalStateException("MODEL_REQUEST_FAILED_OR_UNKNOWN");String raw=String.valueOf(response.payload().get("text"));MineAgentRuntimeServices.audit(server).record(j.player.getUUID().toString(),"AUTONOMY_MODEL_RESPONSE",j.id.toString(),JSON.writeValueAsString(Map.of("request",request,"round",j.round,"goalRevision",revision,"text",raw.substring(0,Math.min(8192,raw.length())),"truncated",raw.length()>8192)));j.plan=AutonomyPlan.parse(raw);var t=j.plan.target();if(!j.plan.action().equals("IDLE")&&!j.plan.action().equals("WAIT")&&new Vec3(t.get(0),t.get(1),t.get(2)).distanceToSqr(j.player.position())>32*32)throw new IllegalArgumentException("TARGET_OUT_OF_OBSERVED_RANGE");j.summary=j.plan.summary();j.mode=j.plan.action();j.state=j.mode.equals("IDLE")?"IDLE":"ACTING";j.actionRevision++;j.actionAt=server.getTickCount();j.lastPosition=j.player.position();j.stuck=0;j.route=List.of();if(j.mode.equals("MOVE")){route(j);if(j.route.isEmpty()&&j.player.position().distanceToSqr(new Vec3(t.get(0),t.get(1),t.get(2)))>1){j.state="IDLE";j.mode="WAIT";j.summary="当前未找到安全可达路线，等待新指令";j.last="NO_LOADED_SAFE_ROUTE";}}save(j);frame(j);}catch(Exception invalid){j.state="WAITING_FOR_INSTRUCTION";j.mode="WAIT";j.summary="本次决策失败，接管会话保留；请给新指令或Esc停止";j.last=invalid.getMessage();save(j);frame(j);}}));
        }catch(Exception failure){j.state="WAITING_FOR_INSTRUCTION";j.mode="WAIT";j.summary="规划不可用，等待新指令";j.last="PLANNING_UNAVAILABLE";save(j);}}
    private static void observedDone(Session j,String result){j.state="OBSERVING";j.mode="WAIT";j.last=result;j.plan=null;j.route=List.of();save(j);frame(j);}
    @SubscribeEvent public static void tick(net.neoforged.neoforge.event.tick.ServerTickEvent.Post event){var all=SESSIONS.get(event.getServer());if(all==null)return;for(var j:List.copyOf(all.values())){if(!j.live.get())continue;if(!valid(j)){stop(j,"CONTEXT_CHANGED");continue;}long now=System.currentTimeMillis();if(j.consent.equals(NONE)){if(now>j.reviewExpires)stop(j,"APPROVAL_EXPIRED");continue;}if(!j.clientPaused&&now-j.heartbeat>5000){stop(j,"CLIENT_CONNECTION_LOST");continue;}int tick=event.getServer().getTickCount();if(tick%5==0)frame(j);if(j.clientPaused||j.manualPaused||j.planning)continue;
        if(j.state.equals("OBSERVING")&&tick-j.lastPlanAt>=60){plan(j);continue;}if(!j.state.equals("ACTING"))continue;
        if(j.mode.equals("MOVE")){var t=j.plan.target();if(j.player.position().distanceToSqr(new Vec3(t.get(0),t.get(1),t.get(2)))<.36){observedDone(j,"MOVE_REACHED_NATIVE_POSITION");continue;}while(!j.route.isEmpty()){var n=j.route.getFirst();if(j.player.position().distanceToSqr(new Vec3(n.x()+.5,n.y(),n.z()+.5))>.32)break;j.route=j.route.subList(1,j.route.size());}
            if(tick%10==0){if(j.player.position().distanceToSqr(j.lastPosition)<.04)j.stuck+=10;else j.stuck=0;j.lastPosition=j.player.position();if(j.route.isEmpty()||!grid(j.player).standable(j.route.getFirst())||j.stuck>=30){route(j);j.actionRevision++;frame(j);if(j.route.isEmpty()){observedDone(j,"ROUTE_BLOCKED_REOBSERVE");}}}if(tick-j.actionAt>600)observedDone(j,"MOVE_PROGRESS_REOBSERVE");
        }else if(tick-j.actionAt>=j.plan.ticks()){observedDone(j,"ACTION_ENDED_OBSERVE_ACTUAL_WORLD");}
    }}
    @SubscribeEvent public static void logout(net.neoforged.neoforge.event.entity.player.PlayerEvent.PlayerLoggedOutEvent event){if(event.getEntity() instanceof ServerPlayer p){var all=SESSIONS.get(p.level().getServer());var j=all==null?null:all.get(p.getUUID());if(j!=null)stop(j,"DISCONNECTED");}}
    @SubscribeEvent public static void stopped(net.neoforged.neoforge.event.server.ServerStoppedEvent event){var all=SESSIONS.remove(event.getServer());if(all!=null)all.values().forEach(j->stop(j,"SERVER_STOPPED"));}
}
