package dev.mineagent.runtime.neoforge.task;
import dev.mineagent.runtime.neoforge.*;
import dev.mineagent.runtime.neoforge.body.MineAgentPlayer;
import dev.mineagent.runtime.core.task.*;
import dev.mineagent.runtime.api.task.*;
import net.minecraft.core.BlockPos;
import net.minecraft.world.item.*;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.tick.ServerTickEvent;
import java.util.*;
import java.nio.file.*;
@EventBusSubscriber(modid="mineagent_runtime")
public final class CraftingUseSmokeServer {
    public static final String RUN=UUID.randomUUID().toString();
    public static final String PROMPT="使用自己背包里的2个橡木原木先制作8块橡木木板，再制作一次木棍，使用已在身旁可触及的工作台(404,170,1)制作一把木镐，然后吃掉自己的1个苹果。先 find_recipes 核对每个配方，不需要移动，不借观察玩家物品。最终自己背包应有木镐1、木棍2、木板3、苹果0，饥饿值至少16；用 finish_task 实际检查。";
    private static final com.fasterxml.jackson.databind.ObjectMapper JSON=new com.fasterxml.jackson.databind.ObjectMapper();private static final long STARTED=System.currentTimeMillis();
    public static volatile String agentId,cancelTaskId,failure;public static volatile boolean finished,liveVerified;private static UUID agent,taskId;private static int phase,at;private static boolean setup;private static ItemStack viewerSlot;private static Map<String,Integer> beforeNegative;
    private static boolean noopUseChecked;
    public static String directory(){return "crafting-use-evidence/"+RUN;}
    private static Map<String,Object> craft(String id,int count,boolean table){var args=new LinkedHashMap<String,Object>();args.put("recipe",id);args.put("count",count);if(table){args.put("x",404);args.put("y",170);args.put("z",1);}try{return Map.of("id",UUID.randomUUID().toString(),"name","craft_recipe","arguments",JSON.writeValueAsString(args));}catch(Exception e){throw new IllegalStateException(e);}}
    private static Map<String,Object> use(){return Map.of("id",UUID.randomUUID().toString(),"name","use_item","arguments","{\"item\":\"minecraft:apple\"}");}
    @SubscribeEvent public static void tick(ServerTickEvent.Post event)throws Exception{
        if(!Boolean.getBoolean("mineagent.craftingUseSmoke")||finished||failure!=null)return;var server=event.getServer();var viewer=server.getPlayerList().getPlayers().stream().filter(p->!(p instanceof MineAgentPlayer)).findFirst().orElse(null);if(viewer==null)return;
        var root=server.getServerDirectory().resolve(directory());Files.createDirectories(root);var tasks=MineAgentRuntimeServices.tasks(server);var actions=MineAgentRuntimeServices.taskExecutor(server).worldActions();var bodies=MineAgentRuntimeServices.bodies(server);
        try{
            if(!setup){
                viewer.setGameMode(net.minecraft.world.level.GameType.CREATIVE);viewer.teleportTo(server.overworld(),402.5,172,4.5,Set.of(),180,25,true);viewerSlot=viewer.getInventory().getItem(8).copy();viewer.getInventory().setItem(8,new ItemStack(Items.DIAMOND,7));
                for(int x=399;x<=412;x++)for(int z=-2;z<=5;z++){server.overworld().setBlockAndUpdate(new BlockPos(x,169,z),Blocks.STONE.defaultBlockState());for(int y=170;y<=173;y++)server.overworld().setBlockAndUpdate(new BlockPos(x,y,z),Blocks.AIR.defaultBlockState());}server.overworld().setBlockAndUpdate(new BlockPos(404,170,1),Blocks.CRAFTING_TABLE.defaultBlockState());
                var def=bodies.createAt("Craft Fixture "+RUN.substring(0,6),viewer.getUUID(),dev.mineagent.runtime.api.agent.AgentMode.SURVIVAL,server.overworld(),new net.minecraft.world.phys.Vec3(402.5,170,1.5));agent=def.agentId();agentId=agent.toString();var body=bodies.body(agent).orElseThrow();reset(body);body.getInventory().setItem(0,new ItemStack(Items.OAK_LOG,2));body.getInventory().setItem(1,new ItemStack(Items.APPLE));body.getFoodData().setFoodLevel(12);body.getFoodData().setSaturation(0);setup=true;
                Files.writeString(root.resolve("fixture.json"),JSON.writeValueAsString(Map.of("agentId",agent,"actorId",body.getUUID(),"viewerId",viewer.getUUID(),"prompt",PROMPT,"driver",System.getProperty("mineagent.craftingUseReplay","").isBlank()?"LIVE_MODEL":"FIXED_NATIVE_REGRESSION")));
                if(!System.getProperty("mineagent.craftingUseReplay","").isBlank())newTask(tasks,actions,viewer.getUUID(),PROMPT,List.of(craft("minecraft:oak_planks",2,false),craft("minecraft:stick",1,false),craft("minecraft:wooden_pickaxe",1,true),use()));
            }
            var body=bodies.body(agent).orElseThrow();if(taskId==null){var task=tasks.all().stream().filter(t->t.agentId().equals(agent)&&t.title().equals(PROMPT)&&t.updatedAtEpochMillis()>=STARTED).findFirst().orElse(null);if(task==null)return;taskId=task.taskId();}
            var task=tasks.get(taskId).orElseThrow();var history=actions.list(viewer.getUUID()).stream().filter(b->b.taskId().equals(taskId)).toList();var batch=history.stream().max(Comparator.comparingInt(WorldActionJournal.Batch::round)).orElse(null);if(batch==null){if(task.status()==TaskStatus.PAUSED)throw new IllegalStateException("PLANNING_FAILED");return;}
            if(phase==0){
                Files.writeString(root.resolve("model-rounds.json"),JSON.writeValueAsString(history));
                if(Set.of("FAILED","INTERRUPTED").contains(batch.state()))throw new IllegalStateException("LIVE_"+batch.error());if(task.status()==TaskStatus.PAUSED)throw new IllegalStateException("LIVE_PLANNING_PAUSED");
                if(batch.state().equals("COMPLETED")&&task.status()==TaskStatus.RUNNING&&!System.getProperty("mineagent.craftingUseReplay","").isBlank()){actions.finishTask(task,"{\"checks\":[{\"kind\":\"inventory\",\"item\":\"minecraft:oak_planks\",\"count\":3},{\"kind\":\"inventory\",\"item\":\"minecraft:stick\",\"count\":2},{\"kind\":\"inventory\",\"item\":\"minecraft:wooden_pickaxe\",\"count\":1},{\"kind\":\"inventory\",\"item\":\"minecraft:apple\",\"count\":0},{\"kind\":\"food\",\"minimum\":16}]}");return;}
                if(task.status()!=TaskStatus.COMPLETED)return;
                if(count(body,Items.OAK_PLANKS)!=3||count(body,Items.STICK)!=2||count(body,Items.WOODEN_PICKAXE)!=1||count(body,Items.APPLE)!=0||body.getFoodData().getFoodLevel()<16||viewer.getInventory().getItem(8).getCount()!=7||body.containerMenu!=body.inventoryMenu)throw new IllegalStateException("LIVE_CRAFT_USE_MISMATCH");
                Files.writeString(root.resolve("live-verified.json"),JSON.writeValueAsString(Map.of("task",task,"batches",history,"inventory",NativeCraftingAction.inventory(body),"food",body.getFoodData().getFoodLevel(),"viewerDiamonds",7,"planningAttempts",actions.planningAttempts(task))));liveVerified=true;phase=1;at=server.getTickCount();return;
            }
            if(phase==1&&server.getTickCount()-at>30){reset(body);body.getInventory().setItem(0,new ItemStack(Items.DIRT,64));beforeNegative=NativeCraftingAction.inventory(body);newTask(tasks,actions,viewer.getUUID(),"无材料不能制作",List.of(craft("minecraft:diamond_pickaxe",1,true)));phase=2;return;}
            if(phase==2){if(!terminal(batch))return;if(!NativeCraftingAction.inventory(body).equals(beforeNegative)||body.containerMenu!=body.inventoryMenu)throw new IllegalStateException("MISSING_INGREDIENT_MUTATION");Files.writeString(root.resolve("missing-verified.json"),JSON.writeValueAsString(batch));reset(body);body.getInventory().setItem(0,new ItemStack(Items.OAK_PLANKS,3));body.getInventory().setItem(1,new ItemStack(Items.STICK,2));beforeNegative=NativeCraftingAction.inventory(body);newTask(tasks,actions,viewer.getUUID(),"三乘三不可放二乘二",List.of(craft("minecraft:wooden_pickaxe",1,false)));phase=3;return;}
            if(phase==3){if(!terminal(batch))return;if(!batch.error().equals("CRAFT_GRID_TOO_SMALL")||!NativeCraftingAction.inventory(body).equals(beforeNegative))throw new IllegalStateException("GRID_LIMIT_BYPASSED");Files.writeString(root.resolve("grid-verified.json"),JSON.writeValueAsString(batch));reset(body);for(int i=0;i<36;i++)body.getInventory().setItem(i,new ItemStack(Items.COBBLESTONE,64));body.getInventory().setItem(0,new ItemStack(Items.OAK_LOG,64));beforeNegative=NativeCraftingAction.inventory(body);newTask(tasks,actions,viewer.getUUID(),"背包满不能假领结果",List.of(craft("minecraft:oak_planks",1,false)));phase=4;return;}
            if(phase==4){if(!terminal(batch))return;if(!NativeCraftingAction.inventory(body).equals(beforeNegative)||count(body,Items.OAK_PLANKS)!=0)throw new IllegalStateException("FULL_INVENTORY_LOSS");if(bodies.craft(agent,net.minecraft.resources.ResourceKey.create(net.minecraft.core.registries.Registries.RECIPE,net.minecraft.resources.Identifier.parse("minecraft:oak_planks"))).isPresent())throw new IllegalStateException("LEGACY_CRAFT_FALSE_SUCCESS");Files.writeString(root.resolve("full-verified.json"),JSON.writeValueAsString(batch));reset(body);body.getInventory().setItem(0,new ItemStack(Items.APPLE));body.getFoodData().setFoodLevel(5);body.getFoodData().setSaturation(0);newTask(tasks,actions,viewer.getUUID(),"取消进食",List.of(use()));phase=5;return;}
            if(phase==5){if(body.isUsingItem()&&body.getTicksUsingItem()>=3&&!noopUseChecked){body.startUsingItem(net.minecraft.world.InteractionHand.MAIN_HAND);if(!body.ownsItemUse(batch.operationId()))throw new IllegalStateException("NOOP_USE_LOST_OWNER");noopUseChecked=true;}if(body.isUsingItem()&&body.getTicksUsingItem()>=5)cancelTaskId=taskId.toString();if(task.status()!=TaskStatus.CANCELLED)return;if(body.isUsingItem()||count(body,Items.APPLE)!=1||body.getFoodData().getFoodLevel()!=5)throw new IllegalStateException("CANCELLED_USE_CONSUMED");Files.writeString(root.resolve("cancel-verified.json"),JSON.writeValueAsString(Map.of("task",task,"batch",batch,"food",5,"apples",1,"noopStartOwnerPreserved",noopUseChecked)));cancelTaskId=null;reset(body);body.getInventory().setItem(0,new ItemStack(Items.APPLE));body.getFoodData().setFoodLevel(20);newTask(tasks,actions,viewer.getUUID(),"饱腹原生拒绝",List.of(use()));phase=6;return;}
            if(phase==6){if(!terminal(batch))return;if(!batch.error().equals("USE_REJECTED")||count(body,Items.APPLE)!=1)throw new IllegalStateException("USE_DENIAL_BYPASSED");Files.writeString(root.resolve("full-food-verified.json"),JSON.writeValueAsString(batch));reset(body);for(int i=0;i<3;i++)body.getInventory().setItem(i,new ItemStack(Items.MILK_BUCKET));body.getInventory().setItem(3,new ItemStack(Items.SUGAR,2));body.getInventory().setItem(4,new ItemStack(Items.EGG));body.getInventory().setItem(5,new ItemStack(Items.WHEAT,3));newTask(tasks,actions,viewer.getUUID(),"真实制作余料",List.of(craft("minecraft:cake",1,true)));phase=7;return;}
            if(phase==7){if(terminal(batch))throw new IllegalStateException("REMAINDER_CRAFT_FAILED_"+batch.error());if(!batch.state().equals("COMPLETED"))return;if(count(body,Items.CAKE)!=1||count(body,Items.BUCKET)!=3||count(body,Items.MILK_BUCKET)!=0||body.containerMenu!=body.inventoryMenu)throw new IllegalStateException("REMAINDER_NOT_RETURNED");Files.writeString(root.resolve("remainders-verified.json"),JSON.writeValueAsString(Map.of("batch",batch,"inventory",NativeCraftingAction.inventory(body),"cake",1,"buckets",3)));reset(body);body.getInventory().setItem(0,new ItemStack(Items.OAK_LOG));body.inventoryMenu.getInputGridSlots().getFirst().set(new ItemStack(Items.DIAMOND));beforeNegative=NativeCraftingAction.inventory(body);newTask(tasks,actions,viewer.getUUID(),"保留已有制作草稿",List.of(craft("minecraft:oak_planks",1,false)));phase=8;return;}
            if(phase==8){if(!terminal(batch))return;if(!batch.error().equals("CRAFT_GRID_BUSY")||!body.inventoryMenu.getInputGridSlots().getFirst().getItem().is(Items.DIAMOND)||!NativeCraftingAction.inventory(body).equals(beforeNegative))throw new IllegalStateException("CRAFT_DRAFT_LOST");Files.writeString(root.resolve("busy-grid-verified.json"),JSON.writeValueAsString(batch));reset(body);body.getInventory().setItem(0,new ItemStack(Items.APPLE));body.getFoodData().setFoodLevel(5);newTask(tasks,actions,viewer.getUUID(),"使用目标改变",List.of(use()));phase=9;return;}
            if(phase==9){if(body.isUsingItem()&&body.getTicksUsingItem()>=5){body.getInventory().setItem(1,body.getMainHandItem().copy());body.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,new ItemStack(Items.BREAD));}if(!terminal(batch))return;if(body.isUsingItem()||count(body,Items.APPLE)!=1||count(body,Items.BREAD)!=1||body.getFoodData().getFoodLevel()!=5)throw new IllegalStateException("REPLACED_USE_CONSUMED");Files.writeString(root.resolve("use-replaced-verified.json"),JSON.writeValueAsString(batch));viewer.getInventory().setItem(8,viewerSlot);bodies.remove(agent,viewer.getUUID(),true);finished=true;}
        }catch(Exception e){failure=e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();Files.writeString(root.resolve("failure.json"),JSON.writeValueAsString(Map.of("phase",phase,"error",failure)));if(agent!=null){bodies.body(agent).ifPresent(b->{if(b.isUsingItem())b.stopUsingItem();if(b.containerMenu!=b.inventoryMenu)b.doCloseContainer();});bodies.remove(agent,viewer.getUUID(),true);}if(viewerSlot!=null)viewer.getInventory().setItem(8,viewerSlot);}
    }
    private static boolean terminal(WorldActionJournal.Batch b){return Set.of("FAILED","INTERRUPTED").contains(b.state());}
    private static int count(MineAgentPlayer p,Item item){int n=0;for(int i=0;i<p.getInventory().getContainerSize();i++)if(p.getInventory().getItem(i).is(item))n+=p.getInventory().getItem(i).getCount();return n;}
    private static void reset(MineAgentPlayer p){if(p.isUsingItem())p.stopUsingItem();if(p.containerMenu!=p.inventoryMenu)p.doCloseContainer();p.inventoryMenu.removed(p);p.getInventory().clearContent();p.getInventory().setSelectedSlot(0);}
    private static void newTask(TaskManager tasks,WorldActionService actions,UUID owner,String title,List<Map<String,Object>> calls)throws Exception{var task=tasks.create(agent,owner,title,50,List.of(new TaskStepSpec("fixture_plan",Set.of()),new TaskStepSpec("execute",Set.of("fixture_plan"))));taskId=task.taskId();task=tasks.completeStep(taskId,task.revision(),"fixture_plan").task();actions.submit(task,calls);}
}
