package dev.mineagent.runtime.neoforge.task;
import com.fasterxml.jackson.databind.ObjectMapper;
import dev.mineagent.runtime.api.permission.PermissionAction;
import dev.mineagent.runtime.api.task.*;
import dev.mineagent.runtime.core.directory.ObjectDirectory;
import dev.mineagent.runtime.core.scheduling.*;
import dev.mineagent.runtime.core.task.TaskStepSpec;
import dev.mineagent.runtime.neoforge.*;
import dev.mineagent.runtime.neoforge.body.MineAgentPlayer;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import java.time.Instant;
import java.util.*;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.BooleanSupplier;

/** Uses the existing Agent/Worker path. Clock waiting itself never asks a model or fabricates a player event. */
public final class NativeScheduleRuntime implements AutoCloseable {
    private final MinecraftServer server;private final UUID epoch=UUID.randomUUID();private final PersistentScheduleStore store;private final ObjectMapper json=new ObjectMapper();private volatile boolean closed;private String diagnostic="READY";
    private record Lease(UUID owner,long scheduleEpoch,long directoryEpoch,long eventEpoch,boolean condition,BooleanSupplier conditionPermit,AtomicBoolean valid){}
    private final Map<UUID,Lease> leases=new ConcurrentHashMap<>();
    private PersistentScheduleStore.ManagementContext managementContext;private ServerPlayer managementPlayer;
    private record ScriptCompletion(UUID occurrence,UUID schedule,String result,String error){}
    private ScriptCompletion scriptCompletion;private boolean scriptInvoking;
    private record DeliveryCompletion(UUID occurrence,UUID schedule,PersistentScheduleStore.DeliveryResult result,String error){}
    private DeliveryCompletion deliveryCompletion;private boolean deliveryInvoking;
    public NativeScheduleRuntime(MinecraftServer server){this.server=server;try{store=PersistentScheduleStore.open(server.getServerDirectory().resolve("mineagent-runtime-data/runtime.db"),MineAgentRuntimeServices.worldId(server),System::currentTimeMillis,()->server.overworld().getGameTime(),new PersistentScheduleStore.Port(){
        public void authorize(PersistentScheduleStore.Context c){authorizeCommand(c);}
        public void authorizeManagement(PersistentScheduleStore.ManagementContext context,PersistentScheduleStore.Definition d,boolean activate){
            if(closed||!server.isSameThread()||context!=managementContext||managementPlayer==null||managementPlayer instanceof MineAgentPlayer||server.getPlayerList().getPlayer(context.owner())!=managementPlayer||!context.world().equals(MineAgentRuntimeServices.worldId(server)))throw new SecurityException("SCHEDULE_MANAGEMENT_IDENTITY_REQUIRED");
            if(activate&&(d==null||token(d)==null))throw new SecurityException("SCHEDULE_RESUME_AUTHORITY_REQUIRED");
        }
        public String authority(PersistentScheduleStore.Definition d){return token(d);}
        public boolean waitingForTarget(PersistentScheduleStore.Definition d){return waiting(d);}
        public PersistentScheduleStore.Signal signal(PersistentScheduleStore.Definition d){if(conditionToken(d)==null)throw new IllegalStateException("SCHEDULE_CONDITION_UNAVAILABLE");try{var signal=MineAgentRuntimeServices.events(server).store().latestRecorded(d.spec().conditionSubscription());return new PersistentScheduleStore.Signal(signal.sequence(),signal.eventId());}catch(Exception failure){throw new IllegalStateException("SCHEDULE_CONDITION_UNAVAILABLE",failure);}}
    });for(var o:store.bindings())leases.put(o.taskId(),new Lease(store.definitionForRuntime(o.scheduleId()).creator().scope().ownerId(),-1,-1,-1,false,()->false,new AtomicBoolean(false)));}catch(Exception e){throw new IllegalStateException("SCHEDULE_RUNTIME_STORE",e);}}
    private long permission(UUID owner,PermissionAction action){return MineAgentRuntimeServices.permissions(server).actionRevision(owner,action);}
    private boolean granted(UUID owner){return MineAgentRuntimeServices.permissions(server).trustedActions(owner).contains(PermissionAction.SCHEDULE_TASKS);}
    private dev.mineagent.runtime.api.agent.AgentDefinition definition(UUID id){return MineAgentRuntimeServices.bodies(server).definitions().stream().filter(d->d.agentId().equals(id)).findFirst().orElse(null);}
    private void authorizeCommand(PersistentScheduleStore.Context c){
        if(closed||!server.isSameThread()||!epoch.equals(c.serverEpoch())||!MineAgentRuntimeServices.worldId(server).equals(c.scope().worldId())||!granted(c.scope().ownerId())||permission(c.scope().ownerId(),PermissionAction.SCHEDULE_TASKS)!=c.scope().authorityRevision())throw new SecurityException("SCHEDULE_PERMISSION_REQUIRED");
        var task=MineAgentRuntimeServices.tasks(server).get(c.scope().taskId()).orElse(null);var d=definition(c.scope().agentId());if(task==null||task.status()!=TaskStatus.RUNNING||task.intentRevision()!=c.scope().intentRevision()||!task.agentId().equals(c.scope().agentId())||!task.ownerPlayerId().equals(c.scope().ownerId())||d==null||!MineAgentRuntimeServices.permissions(server).canMutateAgent(d,c.scope().ownerId(),false)||!MineAgentRuntimeServices.taskExecutor(server).authorized(task))throw new SecurityException("SCHEDULE_TASK_AUTHORITY");
    }
    private String conditionToken(PersistentScheduleStore.Definition d){return MineAgentRuntimeServices.events(server).conditionAuthority(d.creator().scope().ownerId(),d.creator().scope().agentId(),d.spec().conditionSubscription(),d.spec().conditionRevision());}
    private boolean baseAuthority(PersistentScheduleStore.Definition d){var owner=d.creator().scope().ownerId();var actor=definition(d.creator().scope().agentId());return !closed&&granted(owner)&&actor!=null&&MineAgentRuntimeServices.permissions(server).canMutateAgent(actor,owner,false);}
    private String token(PersistentScheduleStore.Definition d){var owner=d.creator().scope().ownerId();var actor=definition(d.creator().scope().agentId());if(!baseAuthority(d))return null;String condition="";if(d.spec().kind().equals("EVENT_CONDITION")){condition=conditionToken(d);if(condition==null)return null;}String result=epoch+"|"+permission(owner,PermissionAction.SCHEDULE_TASKS)+"|"+actor.ownerPlayerId()+"|"+actor.collaboratorPlayerIds().stream().map(UUID::toString).sorted().toList()+"|"+condition;if(d.spec().delivery()!=null){var target=deliveryToken(d);return target==null?null:result+"|delivery|"+target;}if(d.spec().push()!=null){var target=pushToken(owner,d.spec().push());return target==null||!pushConditionMatches(d)?null:result+"|push|"+target;}if(d.spec().script()!=null){var target=scriptToken(owner,d.spec().script());return target==null?null:result+"|script|"+target;}return result;}
    private boolean scriptPermission(UUID owner){var actions=MineAgentRuntimeServices.permissions(server).trustedActions(owner);return actions.contains(PermissionAction.RUN_CODE)&&actions.contains(PermissionAction.MANAGE_PACKAGES);}
    private dev.mineagent.runtime.core.directory.AudienceStore.Definition deliveryAudience(PersistentScheduleStore.Definition d){try{
        var target=d.spec().delivery();if(target==null)return null;var audience=MineAgentRuntimeServices.taskExecutor(server).worldActions().audiences().store().definitionForRuntime(target.audienceId());
        return audience!=null&&audience.worldId().equals(d.creator().scope().worldId())&&audience.ownerId().equals(d.creator().scope().ownerId())&&audience.agentId().equals(d.creator().scope().agentId())&&audience.revision()==target.audienceRevision()&&audience.state().equals("ACTIVE")&&System.currentTimeMillis()<audience.expiresAt()?audience:null;
    }catch(Exception unavailable){return null;}}
    private String deliveryToken(PersistentScheduleStore.Definition d){
        var audience=deliveryAudience(d);if(audience==null)return null;String target=dev.mineagent.runtime.neoforge.ui.ServerUiRuntime.get(server).deliveries().scheduleAuthority(d.creator().scope().ownerId(),d.creator().scope().agentId(),d.spec().delivery());return target==null?null:audience.audienceId()+"|"+audience.revision()+"|"+target;
    }
    private void runDelivery()throws Exception{
        if(deliveryInvoking)return;if(deliveryCompletion!=null){if(server.getTickCount()%20!=0)return;store.finishDelivery(deliveryCompletion.occurrence(),deliveryCompletion.result(),deliveryCompletion.error());deliveryCompletion=null;return;}
        var next=store.claimDelivery();if(next.isEmpty())return;var o=next.get();PersistentScheduleStore.DeliveryResult outcome=null;String error="DELIVERY_DISPATCH_UNCERTAIN";ManagedTask child=null;
        try{deliveryInvoking=true;var d=store.definitionForRuntime(o.scheduleId());var target=Objects.requireNonNull(d.spec().delivery());
            child=MineAgentRuntimeServices.tasks(server).createIdempotent(o.id(),d.creator().scope().agentId(),d.creator().scope().ownerId(),"定时内容邀请（不代表已显示）",20,List.of(new TaskStepSpec("scheduled_delivery",Set.of())),new dev.mineagent.runtime.core.persistence.TaskBudgetLineage.Parent(d.creator().scope().taskId(),d.creator().scope().intentRevision(),"SCHEDULE"));
            if(!child.taskId().equals(o.taskId())||child.status()!=TaskStatus.RUNNING||child.intentRevision()!=1||!child.runnableStepIds().equals(List.of("scheduled_delivery"))||!permitTask(child))throw new SecurityException("SCHEDULE_DELIVERY_TASK_STALE");
            var audience=MineAgentRuntimeServices.taskExecutor(server).worldActions().audiences();UUID resolve=UUID.nameUUIDFromBytes((o.id()+"|scheduled-audience").getBytes(java.nio.charset.StandardCharsets.UTF_8));var context=audience.context(child,resolve);
            var snapshot=audience.store().resolve(context,target.audienceId(),target.audienceRevision(),o.id());if(!snapshot.state().equals("RESOLVED"))throw new IllegalStateException("SCHEDULE_AUDIENCE_NOT_RESOLVED");
            UUID batch=null;if(!snapshot.recipients().isEmpty()){UUID operation=UUID.nameUUIDFromBytes((o.id()+"|scheduled-offer").getBytes(java.nio.charset.StandardCharsets.UTF_8));var result=dev.mineagent.runtime.neoforge.ui.ServerUiRuntime.get(server).deliveries().execute(child,operation,"offer_content",target.offerRequest(snapshot.snapshotId()));batch=UUID.fromString(json.readTree(result.get("result")).path("id").asText());}
            outcome=new PersistentScheduleStore.DeliveryResult(snapshot.snapshotId(),batch,snapshot.recipients().size(),(int)snapshot.recipients().stream().filter(r->r.status().equals("ELIGIBLE")).count());
            var current=MineAgentRuntimeServices.tasks(server).get(child.taskId()).orElseThrow();if(current.intentRevision()!=child.intentRevision()||!MineAgentRuntimeServices.tasks(server).completeStep(current.taskId(),current.revision(),"scheduled_delivery").accepted())throw new IllegalStateException("SCHEDULE_DELIVERY_TASK_RECEIPT_UNCERTAIN");error="";
        }catch(Exception|LinkageError failure){String code=failure.getMessage();error=code!=null&&code.matches("[A-Z0-9_]{1,80}")?code:"DELIVERY_DISPATCH_UNCERTAIN";if(child!=null)try{var live=MineAgentRuntimeServices.tasks(server).get(child.taskId()).orElse(null);if(live!=null&&live.status()!=TaskStatus.COMPLETED&&live.status()!=TaskStatus.CANCELLED)MineAgentRuntimeServices.tasks(server).transition(live.taskId(),live.revision(),true,TaskStatus.CANCELLED);}catch(Exception ignored){/* Durable occurrence remains interrupted; no resend. */}}
        finally{deliveryInvoking=false;}
        deliveryCompletion=new DeliveryCompletion(o.id(),o.scheduleId(),outcome,error);store.finishDelivery(o.id(),outcome,error);deliveryCompletion=null;
    }
    public List<UUID> causalChain(ManagedTask task){try{var o=store.forTask(task.taskId()).orElse(null);if(o==null||o.conditionEvent()==null)return List.of();var event=MineAgentRuntimeServices.events(server).store().event(o.conditionEvent()).orElseThrow();var result=new ArrayList<>(event.subscriptionChain());var d=store.definitionForRuntime(o.scheduleId());if(d.spec().conditionSubscription()!=null&&!result.contains(d.spec().conditionSubscription()))result.add(d.spec().conditionSubscription());if(result.size()>8)throw new IllegalStateException("SCHEDULE_CAUSAL_DEPTH");return List.copyOf(result);}catch(Exception unavailable){throw new IllegalStateException("SCHEDULE_CAUSAL_CONTEXT_UNAVAILABLE",unavailable);}}
    private boolean pushConditionMatches(PersistentScheduleStore.Definition d){try{
        if(d.spec().push()==null||!d.spec().kind().equals("EVENT_CONDITION"))return true;var sub=MineAgentRuntimeServices.events(server).store().subscriptionForRuntime(d.spec().conditionSubscription());if(sub==null)return false;
        var shared=sub.request().shared();if(shared==null)return true;var source=shared.target();var push=d.spec().push();return source.packageId().equals(push.packageId())&&source.instanceId().equals(push.instanceId())&&source.packageRevision()==push.packageRevision()&&source.canonicalSha256().equals(push.canonicalSha256());
    }catch(Exception unavailable){return false;}}
    private String pushToken(UUID owner,SchedulePushConsumer push){try{
        if(closed||!server.isSameThread()||!scriptPermission(owner))return null;var target=dev.mineagent.runtime.neoforge.content.WorldContentRuntime.get(server).scriptEventTarget(owner,push.instanceId());var pack=dev.mineagent.runtime.neoforge.ui.ServerPackageRuntime.get(server).worldLibrary().get(push.packageId()).orElse(null);
        if(!target.active()||!target.packageId().equals(push.packageId())||target.packageRevision()!=push.packageRevision()||!target.canonicalSha256().equals(push.canonicalSha256())||pack==null||pack.entrypoints().values().stream().noneMatch(e->e.side()==dev.mineagent.runtime.api.packages.RuntimeResourceSide.CLIENT&&e.path().equals(push.entryPath())))return null;
        return target.executionEpoch()+"|"+target.activationId()+"|"+push.entryPath()+"|"+permission(owner,PermissionAction.RUN_CODE)+"|"+permission(owner,PermissionAction.MANAGE_PACKAGES);
    }catch(RuntimeException unavailable){return null;}}
    private Map<String,Object> inspectPushTargets(UUID owner,UUID instance,int offset){
        if(!scriptPermission(owner))throw new SecurityException("SCHEDULE_PUSH_PERMISSION_REQUIRED");var target=dev.mineagent.runtime.neoforge.content.WorldContentRuntime.get(server).scriptEventTarget(owner,instance);var pack=dev.mineagent.runtime.neoforge.ui.ServerPackageRuntime.get(server).worldLibrary().get(target.packageId()).orElseThrow();
        var paths=pack.entrypoints().values().stream().filter(e->e.side()==dev.mineagent.runtime.api.packages.RuntimeResourceSide.CLIENT&&e.path().startsWith("ui/")&&e.path().endsWith(".html")).map(dev.mineagent.runtime.api.packages.RuntimeEntrypoint::path).distinct().sorted().toList();var result=new LinkedHashMap<String,Object>();var entries=paths.stream().skip(offset).limit(16).toList();
        result.put("package_id",target.packageId());result.put("instance_id",instance);result.put("package_revision",target.packageRevision());result.put("canonical_sha256",target.canonicalSha256());result.put("active",target.active());result.put("executionEpoch",target.executionEpoch());result.put("entries",entries);result.put("offset",offset);result.put("nextOffset",offset+entries.size());result.put("more",paths.size()>offset+entries.size());result.put("runCodeRevision",permission(owner,PermissionAction.RUN_CODE));result.put("managePackagesRevision",permission(owner,PermissionAction.MANAGE_PACKAGES));return result;
    }
    private void runPush()throws Exception{
        var next=store.claimPush();if(next.isPresent()){var o=next.get();try{var d=store.definitionForRuntime(o.scheduleId());if(d==null||d.spec().push()==null)throw new IllegalStateException("SCHEDULE_PUSH_TARGET_MISSING");
            dev.mineagent.runtime.core.events.RuntimeEventStore.Event condition=null;if(d.spec().kind().equals("EVENT_CONDITION")){if(o.conditionEvent()==null)throw new IllegalStateException("SCHEDULE_PUSH_CONDITION_MISSING");condition=MineAgentRuntimeServices.events(server).store().event(o.conditionEvent()).orElseThrow();}
            var targets=dev.mineagent.runtime.neoforge.ui.ServerUiRuntime.get(server).worldUi().schedulePushTargets(d.spec().push(),condition);store.preparePush(o.id(),targets);
        }catch(Exception unavailable){store.failPush(o.id());}}
        for(var row:store.pushCandidates(8)){try{var sent=store.markPushSent(row.id());if(!dev.mineagent.runtime.neoforge.ui.ServerUiRuntime.get(server).worldUi().notifySchedulePush(sent))store.rejectPush(row.id());}catch(Exception unavailable){/* Retry only this immutable read hint within its stored bounds, never open a view. */}}
    }
    private String scriptToken(UUID owner,ScriptScheduleConsumer script){try{
        if(closed||!server.isSameThread()||!scriptPermission(owner))return null;var world=dev.mineagent.runtime.neoforge.content.WorldContentRuntime.get(server);var target=world.scriptScheduleTarget(owner,script.instanceId());
        if(!target.active()||!target.packageId().equals(script.packageId())||target.packageRevision()!=script.packageRevision()||!target.canonicalSha256().equals(script.canonicalSha256())||!target.handlers().contains(script.handler()))return null;
        return target.executionEpoch()+"|"+target.activationId()+"|"+script.handler()+"|"+world.scriptEventHandlerRevision(owner,script.instanceId(),script.handler())+"|"+permission(owner,PermissionAction.RUN_CODE)+"|"+permission(owner,PermissionAction.MANAGE_PACKAGES);
    }catch(RuntimeException unavailable){return null;}}
    private boolean waiting(PersistentScheduleStore.Definition d){try{
        if(d.spec().delivery()!=null){if(!baseAuthority(d)||deliveryAudience(d)==null)return false;if(d.spec().kind().equals("EVENT_CONDITION")&&conditionToken(d)==null&&!MineAgentRuntimeServices.events(server).conditionWaiting(d.creator().scope().ownerId(),d.creator().scope().agentId(),d.spec().conditionSubscription(),d.spec().conditionRevision()))return false;return deliveryToken(d)!=null||dev.mineagent.runtime.neoforge.ui.ServerUiRuntime.get(server).deliveries().scheduleWaiting(d.creator().scope().ownerId(),d.creator().scope().agentId(),d.spec().delivery());}
        var script=d.spec().script();var push=d.spec().push();var owner=d.creator().scope().ownerId();if(script==null&&push==null||!baseAuthority(d)||!scriptPermission(owner)||!pushConditionMatches(d))return false;
        if(d.spec().kind().equals("EVENT_CONDITION")&&conditionToken(d)==null&&!MineAgentRuntimeServices.events(server).conditionWaiting(owner,d.creator().scope().agentId(),d.spec().conditionSubscription(),d.spec().conditionRevision()))return false;
        if(push!=null)return pushToken(owner,push)!=null||dev.mineagent.runtime.neoforge.content.WorldContentRuntime.get(server).instanceEventWaiting(owner,push.packageId(),push.instanceId(),push.packageRevision(),push.canonicalSha256());
        return scriptToken(owner,script)!=null||dev.mineagent.runtime.neoforge.content.WorldContentRuntime.get(server).instanceEventWaiting(owner,script.packageId(),script.instanceId(),script.packageRevision(),script.canonicalSha256());
    }catch(RuntimeException unavailable){return false;}}
    private Map<String,Object> inspectHandlers(UUID owner,UUID instance,int offset){
        if(!scriptPermission(owner))throw new SecurityException("SCHEDULE_SCRIPT_PERMISSION_REQUIRED");var world=dev.mineagent.runtime.neoforge.content.WorldContentRuntime.get(server);var target=world.scriptScheduleTarget(owner,instance);
        var handlers=target.handlers().stream().skip(offset).limit(16).map(name->Map.of("handler",name,"handlerRevision",world.scriptEventHandlerRevision(owner,instance,name))).toList();var result=new LinkedHashMap<String,Object>();result.put("package_id",target.packageId());result.put("instance_id",instance);result.put("package_revision",target.packageRevision());result.put("canonical_sha256",target.canonicalSha256());result.put("active",target.active());result.put("executionEpoch",target.executionEpoch());result.put("handlers",handlers);result.put("offset",offset);result.put("nextOffset",offset+handlers.size());result.put("more",target.handlers().size()>offset+handlers.size());result.put("runCodeRevision",permission(owner,PermissionAction.RUN_CODE));result.put("managePackagesRevision",permission(owner,PermissionAction.MANAGE_PACKAGES));return result;
    }
    private void runScript()throws Exception{
        if(scriptInvoking)return;if(scriptCompletion!=null){if(server.getTickCount()%20!=0)return;store.finishScript(scriptCompletion.occurrence(),scriptCompletion.result(),scriptCompletion.error());scriptCompletion=null;return;}
        var next=store.claimScript();if(next.isEmpty())return;var o=next.get();String result="",error="SCHEDULE_SCRIPT_DISPATCH_UNCERTAIN";
        try{scriptInvoking=true;var d=store.definitionForRuntime(o.scheduleId());var spec=d.spec();var chain=new ArrayList<UUID>();
            if(o.conditionEvent()!=null){var source=MineAgentRuntimeServices.events(server).store().event(o.conditionEvent()).orElseThrow();chain.addAll(source.subscriptionChain());if(!chain.contains(spec.conditionSubscription()))chain.add(spec.conditionSubscription());}
            var origin=dev.mineagent.runtime.core.shared.SharedStateStore.Provenance.schedule(o.id(),d.id(),chain);var data=new LinkedHashMap<String,Object>();data.put("scheduleId",d.id());data.put("occurrenceId",o.id());data.put("slot",o.index());data.put("definitionRevision",o.definitionRevision());data.put("kind",spec.kind());data.put("due",o.due());data.put("recordedAt",o.recordedAt());data.put("timezone",spec.zone());data.put("conditionEventId",o.conditionEvent());data.put("currentUtc",Instant.now().toString());data.put("gameTicks",server.overworld().getGameTime());
            var outcome=dev.mineagent.runtime.neoforge.content.WorldContentRuntime.get(server).dispatchScriptSchedule(d.creator().scope().ownerId(),spec.script(),o.id(),d.id(),json.writeValueAsString(data),origin,()->{try{return !closed&&store.permitScript(o.id());}catch(Exception unavailable){return false;}});
            if(!outcome.returned())MineAgentRuntimeServices.events(server).invalidateObjectInstance(spec.script().instanceId());error=!outcome.returned()?"SCHEDULE_SCRIPT_HANDLER_FAILED":!outcome.completed()?"SCHEDULE_SCRIPT_COMPLETION_REQUIRED":"";result=outcome.result();
        }catch(Exception|LinkageError failure){error="SCHEDULE_SCRIPT_DISPATCH_UNCERTAIN";}finally{scriptInvoking=false;}
        scriptCompletion=new ScriptCompletion(o.id(),o.scheduleId(),result,error);store.finishScript(o.id(),result,error);scriptCompletion=null;
    }
    public PersistentScheduleStore store(){return store;}
    public PersistentScheduleStore.Context context(ManagedTask task,UUID operation){return new PersistentScheduleStore.Context(new ObjectDirectory.Scope(task.worldId(),task.agentId(),task.ownerPlayerId(),task.taskId(),task.intentRevision(),permission(task.ownerPlayerId(),PermissionAction.SCHEDULE_TASKS)),epoch,operation);}
    public void tick(){if(closed)return;try{store.poll();runScript();runPush();runDelivery();refresh();for(int i=0;i<4;i++){var found=store.claim();if(found.isEmpty())break;var o=found.get();var d=store.definitionForRuntime(o.scheduleId());var owner=d.creator().scope().ownerId();var lease=new Lease(owner,permission(owner,PermissionAction.SCHEDULE_TASKS),permission(owner,PermissionAction.DISCOVER_OBJECTS),permission(owner,PermissionAction.SUBSCRIBE_EVENTS),d.spec().kind().equals("EVENT_CONDITION"),d.spec().kind().equals("EVENT_CONDITION")?MineAgentRuntimeServices.events(server).conditionWorkerPermit(d.spec().conditionSubscription()):()->true,new AtomicBoolean(false));leases.put(o.taskId(),lease);
            try{var task=MineAgentRuntimeServices.tasks(server).createIdempotent(o.id(),d.creator().scope().agentId(),owner,d.spec().goal(),20,List.of(new TaskStepSpec("plan",Set.of()),new TaskStepSpec("execute",Set.of("plan"))),new dev.mineagent.runtime.core.persistence.TaskBudgetLineage.Parent(d.creator().scope().taskId(),d.creator().scope().intentRevision(),"SCHEDULE"));if(!task.taskId().equals(o.taskId()))throw new IllegalStateException("SCHEDULE_TASK_ID_MISMATCH");store.dispatched(o.id());lease.valid().set(true);}catch(Exception failure){store.failed(o.id(),"SCHEDULE_TASK_DISPATCH_UNCERTAIN");lease.valid().set(false);}}
            for(var entry:List.copyOf(leases.entrySet())){var task=MineAgentRuntimeServices.tasks(server).get(entry.getKey()).orElse(null);if(task!=null&&Set.of(TaskStatus.COMPLETED,TaskStatus.CANCELLED,TaskStatus.FAILED).contains(task.status())){store.taskFinished(entry.getKey(),task.status().name());entry.getValue().valid().set(false);leases.remove(entry.getKey(),entry.getValue());}}
        }catch(Exception failure){diagnostic="SCHEDULE_TICK_FAILED";leases.values().forEach(l->l.valid().set(false));MineAgentRuntimeMod.LOGGER.warn("Schedule runtime tick failed code={}",failure.getClass().getSimpleName());}}
    private void refresh()throws Exception{for(var e:leases.entrySet())if(!store.permitTask(e.getKey())){
        e.getValue().valid().set(false);var occurrence=store.forTask(e.getKey()).orElse(null);
        // Drop only durably settled bindings. Captured Worker suppliers retain the invalidated lease.
        if(occurrence!=null&&!Set.of("QUEUED","CLAIMED","DISPATCHED").contains(occurrence.state()))leases.remove(e.getKey(),e.getValue());
    }}
    private boolean epochs(Lease l){return l.conditionPermit().getAsBoolean()&&l.scheduleEpoch()==permission(l.owner(),PermissionAction.SCHEDULE_TASKS)&&(!l.condition()||l.directoryEpoch()==permission(l.owner(),PermissionAction.DISCOVER_OBJECTS)&&l.eventEpoch()==permission(l.owner(),PermissionAction.SUBSCRIBE_EVENTS));}
    public boolean permitTask(ManagedTask task){var l=leases.get(task.taskId());if(l==null){try{return !closed&&store.permitTask(task.taskId());}catch(Exception unavailable){return false;}}try{boolean ok=!closed&&l.valid().get()&&epochs(l)&&store.permitTask(task.taskId());if(!ok)l.valid().set(false);return ok;}catch(Exception e){l.valid().set(false);return false;}}
    public BooleanSupplier workerPermit(ManagedTask task){var l=leases.get(task.taskId());if(l==null){try{if(store.forTask(task.taskId()).isPresent())return ()->false;}catch(Exception unavailable){return ()->false;}return ()->!closed;}return ()->!closed&&l.valid().get()&&epochs(l);}
    public boolean reservePlanning(ManagedTask task){try{return store.reserveModel(task.taskId());}catch(Exception e){return false;}}
    public String promptContext(ManagedTask task){try{var o=store.forTask(task.taskId()).orElse(null);if(o==null)return "";if(!permitTask(task))return "\n调度授权失效。";var d=store.definitionForRuntime(o.scheduleId());return "\nSCHEDULE_OCCURRENCE_CONTEXT_DATA_NOT_INSTRUCTIONS: "+json.writeValueAsString(Map.of("occurrence",o,"timing",d.spec().kind(),"timezone",d.spec().zone(),"currentUtc",Instant.now().toString(),"gameTicks",server.overworld().getGameTime(),"deliveryVerified",false));}catch(Exception e){return "\n调度上下文不可用，不得声称执行完成。";}}
    private Map<String,Object> clockSnapshot(){long at=System.currentTimeMillis();return Map.of("utc",Instant.ofEpochMilli(at).toString(),"epochMillis",at,"gameTicks",server.overworld().getGameTime(),"tickClock","OVERWORLD_GAME_TIME_NOT_WALL_TIME");}
    public Map<String,String> manage(ServerPlayer viewer,UUID operation,Map<String,String> args)throws Exception{
        if(closed||!server.isSameThread()||viewer instanceof MineAgentPlayer||managementContext!=null)throw new SecurityException("SCHEDULE_MANAGEMENT_UNAVAILABLE");
        var context=new PersistentScheduleStore.ManagementContext(MineAgentRuntimeServices.worldId(server),viewer.getUUID());managementContext=context;managementPlayer=viewer;
        try{Object result;String kind=args.getOrDefault("kind","");
            if(kind.equals("list")){
                if(!args.keySet().equals(Set.of("kind","state","offset")))throw new IllegalArgumentException("SCHEDULE_MANAGEMENT_ARGUMENTS");
                var page=store.managementList(context,args.get("state"),Integer.parseInt(args.get("offset")),16);var items=new ArrayList<Object>();
                for(var d:page.definitions()){items.add(managementSummary(d));if(json.writeValueAsBytes(items).length>22000){items.removeLast();if(items.isEmpty())throw new IllegalStateException("SCHEDULE_MANAGEMENT_RESPONSE_BUDGET");break;}}
                result=Map.of("items",items,"total",page.total(),"offset",page.offset(),"nextOffset",page.offset()+items.size(),"more",page.total()>page.offset()+items.size(),"retention",store.managementOwnerRetention(context),"clock",clockSnapshot());
            }else if(kind.equals("detail")){
                if(!args.keySet().equals(Set.of("kind","scheduleId","offset")))throw new IllegalArgumentException("SCHEDULE_MANAGEMENT_ARGUMENTS");UUID id=UUID.fromString(args.get("scheduleId"));int offset=Integer.parseInt(args.get("offset"));var d=store.managementInspect(context,id);var items=new ArrayList<Object>();
                for(var o:store.managementHistory(context,id,offset,8)){items.add(occurrenceView(d,o));if(json.writeValueAsBytes(items).length>18000){items.removeLast();if(items.isEmpty())throw new IllegalStateException("SCHEDULE_MANAGEMENT_RESPONSE_BUDGET");break;}}
                var retention=store.managementRetention(context,id);var count=(PersistentScheduleStore.RetentionCount)retention.get("occurrences");
                result=Map.of("definition",managementSummary(d),"spec",d.spec(),"occurrences",items,"offset",offset,"nextOffset",offset+items.size(),"more",count.total()>offset+items.size(),"retention",retention,"clock",clockSnapshot(),"diagnostic",diagnostic);
            }else if(kind.equals("write")){
                if(!args.keySet().equals(Set.of("kind","scheduleId","expectedRevision","action","confirmed"))||!"true".equals(args.get("confirmed")))throw new IllegalArgumentException("SCHEDULE_MANAGEMENT_CONFIRM");
                result=store.managementWrite(context,operation,UUID.fromString(args.get("scheduleId")),Long.parseLong(args.get("expectedRevision")),args.get("action"),true);refresh();
            }else if(kind.equals("deliveries")){
                if(!args.keySet().equals(Set.of("kind","scheduleId","occurrenceId","offset")))throw new IllegalArgumentException("SCHEDULE_MANAGEMENT_ARGUMENTS");var id=UUID.fromString(args.get("scheduleId"));var d=store.managementInspect(context,id);var o=store.managementOccurrence(context,id,UUID.fromString(args.get("occurrenceId")));if(d.spec().delivery()==null||o.taskId()==null)throw new IllegalArgumentException("SCHEDULE_DELIVERY_OCCURRENCE_REQUIRED");
                result=dev.mineagent.runtime.neoforge.ui.ServerUiRuntime.get(server).deliveries().scheduleHistory(context.owner(),d.creator().scope().agentId(),o.taskId(),Integer.parseInt(args.get("offset")));
            }else throw new IllegalArgumentException("SCHEDULE_MANAGEMENT_KIND");
            if(server.getPlayerList().getPlayer(viewer.getUUID())!=viewer)throw new SecurityException("SCHEDULE_MANAGEMENT_DISCONNECTED");String encoded=json.writeValueAsString(result);if(encoded.getBytes(java.nio.charset.StandardCharsets.UTF_8).length>24000)throw new IllegalStateException("SCHEDULE_MANAGEMENT_RESPONSE_BUDGET");
            return Map.of("state",encoded,"executionMode","OWNER_SCHEDULE_MANAGEMENT_NO_MODEL");
        }finally{managementContext=null;managementPlayer=null;}
    }
    private Map<String,Object> managementSummary(PersistentScheduleStore.Definition d)throws Exception{
        var spec=d.spec();boolean expired=System.currentTimeMillis()>=d.expires(),exhausted=d.cursor()>=spec.maxOccurrences()-1,current=token(d)!=null,archived=store.archivedDefinition(d.id());var agent=definition(d.creator().scope().agentId());
        var value=new LinkedHashMap<String,Object>();value.put("id",d.id());value.put("agentId",d.creator().scope().agentId());value.put("agentName",agent==null?d.creator().scope().agentId().toString():agent.displayName());value.put("kind",spec.kind());value.put("mode",spec.mode());value.put("goal",spec.goal());value.put("zone",spec.zone());value.put("missedPolicy",spec.missedPolicy());value.put("state",d.state());value.put("revision",d.revision());value.put("start",d.start());value.put("expires",d.expires());value.put("consumedSlots",d.cursor()+1);value.put("maximumSlots",spec.maxOccurrences());value.put("skipped",d.skipped());value.put("maxModelCalls",spec.maxModelCalls());value.put("archived",archived);value.put("error",d.error());value.put("authorityReady",current);
        value.put("canPause",d.state().equals("ACTIVE")&&!expired&&!archived);value.put("canCancel",Set.of("ACTIVE","PAUSED").contains(d.state())&&!archived);value.put("canResume",d.state().equals("PAUSED")&&!expired&&!exhausted&&!archived&&current);value.put("resumeReason",expired?"EXPIRED":exhausted?"SLOTS_EXHAUSTED":!current?"CURRENT_AUTHORITY_OR_CONDITION_REQUIRED":"");
        value.put("sourceState",current?"READY":waiting(d)?"WAITING_RESOURCE":"AUTHORITY_OR_TARGET_UNAVAILABLE");value.put("scriptReceiptPending",scriptCompletion!=null&&scriptCompletion.schedule().equals(d.id()));
        value.put("deliveryReceiptPending",deliveryCompletion!=null&&deliveryCompletion.schedule().equals(d.id()));if(d.spec().delivery()!=null){var offer=d.spec().delivery().template();value.put("deliveryMode",offer.mode());value.put("feedbackEnabled",offer.feedbackEnabled());}
        if(!spec.kind().equals("EVENT_CONDITION")&&!exhausted&&!expired&&Set.of("ACTIVE","PAUSED").contains(d.state()))value.put("nextPlannedSlot",Math.addExact(d.start(),Math.multiplyExact(d.cursor()+1,spec.period())));
        return value;
    }
    public Map<String,Object> occurrenceView(PersistentScheduleStore.Definition d,PersistentScheduleStore.Occurrence o)throws Exception{
        var item=new LinkedHashMap<String,Object>();item.put("id",o.id());item.put("scheduleId",o.scheduleId());item.put("index",o.index());item.put("slot",o.index());item.put("definitionRevision",o.definitionRevision());item.put("state",o.state());item.put("taskId",o.taskId());item.put("modelAttempts",o.modelAttempts());item.put("maxModelCalls",o.maxModelCalls());item.put("due",o.due());item.put("recordedAt",o.recordedAt());item.put("conditionEvent",o.conditionEvent());item.put("error",o.error());
        if(o.deliveryResult()!=null)item.put("deliveryResult",o.deliveryResult());if(d.spec().delivery()!=null)item.put("canInspectDeliveries",o.taskId()!=null);
        if(d.spec().push()!=null)item.put("pushDeliveries",store.pushDeliveries(o.id()).stream().map(row->Map.of("viewId",row.session().binding().viewId(),"state",row.state(),"attempts",row.attempts(),"readRevision",row.readRevision(),"error",row.error(),"paintVerified",false)).toList());
        if(!o.scriptResult().isEmpty()){if(token(d)!=null)item.put("scriptResult",json.readTree(o.scriptResult()));else item.put("scriptResultRedacted",true);}return item;
    }
    public Map<String,String> execute(ManagedTask task,UUID operation,String tool,String arguments)throws Exception{var request=ScheduleToolRequest.parse(tool,arguments);var c=context(task,operation);Object value;String scriptAuthority="";
        if(tool.equals("inspect_schedule_push_targets")){authorizeCommand(c);value=inspectPushTargets(task.ownerPlayerId(),request.id(),request.offset());}
        else if(tool.equals("inspect_schedule_handlers")){authorizeCommand(c);value=inspectHandlers(task.ownerPlayerId(),request.id(),request.offset());}
        else if(tool.equals("create_schedule"))value=store.create(c,request.spec());else if(tool.equals("set_schedule_state")){value=store.state(c,request.id(),request.revision(),request.state());refresh();}
        else if(tool.equals("inspect_clock")){authorizeCommand(c);value=Map.of("utc",Instant.now().toString(),"epochMillis",System.currentTimeMillis(),"gameTicks",server.overworld().getGameTime(),"tickClock","OVERWORLD_GAME_TIME_NOT_WALL_TIME");}
        else{var d=store.inspect(c,request.id());var occurrences=new ArrayList<Object>();for(var o:store.history(c,request.id(),request.offset(),d.spec().script()==null&&d.spec().push()==null&&d.spec().delivery()==null?16:8)){occurrences.add(d.spec().script()==null&&d.spec().push()==null&&d.spec().delivery()==null?o:occurrenceView(d,o));if((d.spec().script()!=null||d.spec().push()!=null||d.spec().delivery()!=null)&&json.writeValueAsBytes(occurrences).length>16000){occurrences.removeLast();if(occurrences.isEmpty())throw new IllegalStateException("SCHEDULE_HISTORY_ITEM_BUDGET");break;}}value=Map.of("definition",d,"offset",request.offset(),"nextOffset",request.offset()+occurrences.size(),"occurrences",occurrences,"more",store.historyCount(c,request.id())>request.offset()+occurrences.size(),"diagnostic",diagnostic);scriptAuthority=Objects.toString(token(d),"");}
        if(value instanceof PersistentScheduleStore.Definition d)scriptAuthority=Objects.toString(token(d),"");
        return Map.of("executionMode","NATIVE_SCHEDULE_CONFIGURATION_OR_OCCURRENCE","result",json.writeValueAsString(value),"request",request.canonical(),"serverEpoch",epoch.toString(),"scheduleAuthority",Long.toString(permission(task.ownerPlayerId(),PermissionAction.SCHEDULE_TASKS)),"scriptAuthority",scriptAuthority,"deliveryVerified","false");
    }
    public Map<String,String> forModel(ManagedTask task,String tool,Map<String,String> after){if(!ScheduleToolRequest.TOOLS.contains(tool))return after;try{if(!epoch.toString().equals(after.get("serverEpoch"))||!Long.toString(permission(task.ownerPlayerId(),PermissionAction.SCHEDULE_TASKS)).equals(after.get("scheduleAuthority")))throw new IllegalStateException();var c=context(task,UUID.randomUUID());authorizeCommand(c);var request=ScheduleToolRequest.parse(tool,after.get("request"));if(tool.equals("inspect_schedule_push_targets")){if(!json.readTree(after.get("result")).equals(json.readTree(json.writeValueAsBytes(inspectPushTargets(task.ownerPlayerId(),request.id(),request.offset())))))throw new IllegalStateException();return after;}if(tool.equals("inspect_schedule_handlers")){if(!json.readTree(after.get("result")).equals(json.readTree(json.writeValueAsBytes(inspectHandlers(task.ownerPlayerId(),request.id(),request.offset())))))throw new IllegalStateException();return after;}if(!tool.equals("inspect_clock")){var node=json.readTree(after.get("result"));var old=tool.equals("inspect_schedule")?node.path("definition"):node;var current=store.inspect(c,request.id()==null?UUID.fromString(old.path("id").asText()):request.id());if(old.path("revision").asLong()!=current.revision()||!old.path("state").asText().equals(current.state())||(current.spec().script()!=null||current.spec().push()!=null||current.spec().delivery()!=null)&&(token(current)==null||!token(current).equals(after.get("scriptAuthority"))))throw new IllegalStateException();}return after;}catch(Exception e){return Map.of("executionMode","SCHEDULE_OBSERVATION_REDACTED","reason","CURRENT_SCHEDULE_AUTHORITY_REQUIRED");}}
    public BooleanSupplier observationPermit(ManagedTask task,String tool,Map<String,String> after){try{
        if(!after.equals(forModel(task,tool,after)))return ()->false;var request=ScheduleToolRequest.parse(tool,after.get("request"));long schedule=permission(task.ownerPlayerId(),PermissionAction.SCHEDULE_TASKS),run=permission(task.ownerPlayerId(),PermissionAction.RUN_CODE),manage=permission(task.ownerPlayerId(),PermissionAction.MANAGE_PACKAGES);BooleanSupplier source=()->true;
        ScriptScheduleConsumer pinned=null;SchedulePushConsumer pushed=null;UUID instance=null;String handler="catalog";if(tool.equals("inspect_schedule_handlers")||tool.equals("inspect_schedule_push_targets"))instance=request.id();else if(!tool.equals("inspect_clock")){var node=json.readTree(after.get("result"));var d=store.definitionForRuntime(request.id()==null?UUID.fromString(node.path("id").asText()):request.id());if(d.spec().delivery()!=null)return deliveryObservationPermit(task,tool,after);if(d.spec().script()!=null){pinned=d.spec().script();instance=pinned.instanceId();handler=pinned.handler();}if(d.spec().push()!=null){pushed=d.spec().push();instance=pushed.instanceId();handler="push:"+pushed.entryPath();}if(d.spec().kind().equals("EVENT_CONDITION"))source=MineAgentRuntimeServices.events(server).conditionWorkerPermit(d.spec().conditionSubscription());}
        boolean script=instance!=null;var resource=script?MineAgentRuntimeServices.events(server).scriptResourcePermit(instance,handler):(BooleanSupplier)()->true;var bound=source;var target=pinned;var pushTarget=pushed;var library=dev.mineagent.runtime.neoforge.ui.ServerPackageRuntime.get(server).worldLibrary();
        return ()->!closed&&permission(task.ownerPlayerId(),PermissionAction.SCHEDULE_TASKS)==schedule&&(!script||permission(task.ownerPlayerId(),PermissionAction.RUN_CODE)==run&&permission(task.ownerPlayerId(),PermissionAction.MANAGE_PACKAGES)==manage)&&resource.getAsBoolean()&&bound.getAsBoolean()&&(target==null||library.get(target.packageId()).filter(p->p.enabled()&&p.revision()==target.packageRevision()&&p.canonicalSha256().equals(target.canonicalSha256())).isPresent())&&(pushTarget==null||library.get(pushTarget.packageId()).filter(p->p.enabled()&&p.revision()==pushTarget.packageRevision()&&p.canonicalSha256().equals(pushTarget.canonicalSha256())).isPresent());
    }catch(Exception unavailable){return ()->false;}}
    private BooleanSupplier deliveryObservationPermit(ManagedTask task,String tool,Map<String,String> after){var valid=new AtomicBoolean(true);return ()->{if(!valid.get())return false;try{
        boolean current=server.isSameThread()?after.equals(forModel(task,tool,after)):server.submit(()->after.equals(forModel(task,tool,after))).get(3,java.util.concurrent.TimeUnit.SECONDS);if(!current)valid.set(false);return current;
    }catch(Exception unavailable){valid.set(false);return false;}};}
    @Override public void close()throws Exception{closed=true;leases.values().forEach(l->l.valid().set(false));store.close();}
}
