package dev.mineagent.runtime.neoforge.task;

import com.fasterxml.jackson.databind.ObjectMapper;
import dev.mineagent.runtime.api.task.*;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;
import dev.mineagent.runtime.neoforge.body.MineAgentPlayer;
import net.minecraft.server.level.ServerPlayer;
import java.util.*;

/** Owner-only retained Task metadata. Reading history never resumes work or grants Agent control. */
public final class ServerTaskHistory {
    private static final ObjectMapper JSON=new ObjectMapper();
    private ServerTaskHistory(){}
    public static Map<String,String> read(ServerPlayer viewer,Map<String,String> args)throws Exception{
        var server=viewer.level().getServer();if(!server.isSameThread()||viewer instanceof MineAgentPlayer||server.getPlayerList().getPlayer(viewer.getUUID())!=viewer)throw new SecurityException("TASK_HISTORY_IDENTITY");var tasks=MineAgentRuntimeServices.tasks(server);Object result;
        if(Set.of("creatures","creaturePreview","modelPreview","models","packages","package","versions","version","versionText","versionFile","operation","compatibility").contains(args.get("kind")))return ServerPackageCatalog.read(viewer,args);
        if(Set.of("jobs","job","jobPrompt","jobRaw").contains(args.get("kind")))return ServerGenerationHistory.read(viewer,args);
        if("list".equals(args.get("kind"))){
            if(!args.keySet().equals(Set.of("kind","state","archive","offset")))throw new IllegalArgumentException("TASK_HISTORY_ARGUMENTS");var page=tasks.history(viewer.getUUID(),args.get("state"),args.get("archive"),Integer.parseInt(args.get("offset")),16);var items=new ArrayList<Object>();
            for(var task:page.tasks()){items.add(summary(task));if(JSON.writeValueAsBytes(items).length>20000){items.removeLast();if(items.isEmpty())throw new IllegalStateException("TASK_HISTORY_ITEM_BUDGET");break;}}
            result=Map.of("items",items,"total",page.total(),"offset",page.offset(),"nextOffset",page.offset()+items.size(),"more",page.total()>page.offset()+items.size(),"usage",tasks.usage(viewer.getUUID()));
        }else if("budget".equals(args.get("kind"))){
            if(!args.keySet().equals(Set.of("kind","taskId","offset")))throw new IllegalArgumentException("TASK_HISTORY_ARGUMENTS");
            var task=tasks.get(UUID.fromString(args.get("taskId"))).filter(t->t.ownerPlayerId().equals(viewer.getUUID())).orElseThrow(()->new SecurityException("TASK_HISTORY_NOT_OWNED"));
            result=dev.mineagent.runtime.core.persistence.ServiceCallLedger.taskSnapshot(server.getServerDirectory().resolve("mineagent-runtime-data/runtime.db"),java.time.Clock.systemUTC(),task.worldId(),viewer.getUUID(),task.taskId(),Integer.parseInt(args.get("offset")));
        }else if("detail".equals(args.get("kind"))){
            if(!args.keySet().equals(Set.of("kind","taskId","offset")))throw new IllegalArgumentException("TASK_HISTORY_ARGUMENTS");var task=tasks.get(UUID.fromString(args.get("taskId"))).filter(t->t.ownerPlayerId().equals(viewer.getUUID())).orElseThrow(()->new SecurityException("TASK_HISTORY_NOT_OWNED"));int offset=Integer.parseInt(args.get("offset"));if(offset<0||offset>1000)throw new IllegalArgumentException("TASK_HISTORY_PAGE");var steps=new ArrayList<Object>();
            for(var step:task.steps().stream().skip(offset).limit(8).toList())steps.add(Map.of("id",step.stepId(),"status",step.status(),"dependencyCount",step.dependencies().size(),"dependencies",step.dependencies().stream().sorted().limit(16).toList(),"dependenciesTruncated",step.dependencies().size()>16));
            result=Map.of("task",summary(task),"steps",steps,"offset",offset,"nextOffset",offset+steps.size(),"more",task.steps().size()>offset+steps.size(),"readOnly",true);
        }else if("dependencies".equals(args.get("kind"))){
            if(!args.keySet().equals(Set.of("kind","taskId","stepId","revision","offset")))throw new IllegalArgumentException("TASK_HISTORY_ARGUMENTS");var task=tasks.get(UUID.fromString(args.get("taskId"))).filter(t->t.ownerPlayerId().equals(viewer.getUUID())).orElseThrow(()->new SecurityException("TASK_HISTORY_NOT_OWNED"));if(task.revision()!=Long.parseLong(args.get("revision")))throw new IllegalStateException("TASK_HISTORY_STALE");var step=task.steps().stream().filter(s->s.stepId().equals(args.get("stepId"))).findFirst().orElseThrow(()->new IllegalArgumentException("TASK_HISTORY_STEP_MISSING"));int offset=Integer.parseInt(args.get("offset"));if(offset<0||offset>1000)throw new IllegalArgumentException("TASK_HISTORY_PAGE");var values=step.dependencies().stream().sorted().skip(offset).limit(64).toList();result=Map.of("step",step.stepId(),"dependencies",values,"nextOffset",offset+values.size(),"more",step.dependencies().size()>offset+values.size());
        }else if("reason".equals(args.get("kind"))){
            if(!args.keySet().equals(Set.of("kind","taskId","revision","offset")))throw new IllegalArgumentException("TASK_HISTORY_ARGUMENTS");var task=tasks.get(UUID.fromString(args.get("taskId"))).filter(t->t.ownerPlayerId().equals(viewer.getUUID())).orElseThrow(()->new SecurityException("TASK_HISTORY_NOT_OWNED"));if(task.revision()!=Long.parseLong(args.get("revision")))throw new IllegalStateException("TASK_HISTORY_STALE");int offset=Integer.parseInt(args.get("offset")),length=task.lastChangeReason().codePointCount(0,task.lastChangeReason().length());if(offset<0||offset>length)throw new IllegalArgumentException("TASK_HISTORY_PAGE");int next=Math.min(length,offset+1024);result=Map.of("text",task.lastChangeReason().substring(task.lastChangeReason().offsetByCodePoints(0,offset),task.lastChangeReason().offsetByCodePoints(0,next)),"nextOffset",next,"more",next<length);
        }else if("world".equals(args.get("kind"))){
            if(!args.keySet().equals(Set.of("kind","taskId","offset")))throw new IllegalArgumentException("TASK_HISTORY_ARGUMENTS");var task=tasks.get(UUID.fromString(args.get("taskId"))).filter(t->t.ownerPlayerId().equals(viewer.getUUID())).orElseThrow(()->new SecurityException("TASK_HISTORY_NOT_OWNED"));int offset=Integer.parseInt(args.get("offset"));var batches=MineAgentRuntimeServices.taskExecutor(server).worldActions().historyPage(viewer.getUUID(),task.taskId(),offset,9);var rows=new ArrayList<Object>();
            for(var b:batches.stream().limit(8).toList())rows.add(Map.of("id",b.batchId(),"revision",b.revision(),"intent",b.intent(),"round",b.round(),"state",b.state(),"cursor",b.cursor(),"total",b.actions().size(),"receiptCount",b.receipts().size(),"error",b.error(),"resumableReadOnlyWait",dev.mineagent.runtime.core.task.WorldActionJournal.resumableWorldWait(b)));
            result=Map.of("batches",rows,"offset",offset,"nextOffset",offset+rows.size(),"more",batches.size()>8,"readOnly",true);
        }else if("worldBatch".equals(args.get("kind"))){
            if(!args.keySet().equals(Set.of("kind","taskId","batchId","offset")))throw new IllegalArgumentException("TASK_HISTORY_ARGUMENTS");var task=tasks.get(UUID.fromString(args.get("taskId"))).filter(t->t.ownerPlayerId().equals(viewer.getUUID())).orElseThrow(()->new SecurityException("TASK_HISTORY_NOT_OWNED"));var b=MineAgentRuntimeServices.taskExecutor(server).worldActions().historyBatch(viewer.getUUID(),task.taskId(),UUID.fromString(args.get("batchId")));int offset=Integer.parseInt(args.get("offset"));if(offset<0||offset>256)throw new IllegalArgumentException("TASK_HISTORY_PAGE");var rows=new ArrayList<Object>();
            for(int i=offset;i<Math.min(offset+8,b.receipts().size());i++){var r=b.receipts().get(i);rows.add(Map.of("receipt",i,"operationId",r.operationId(),"index",r.index(),"tool",r.tool(),"verified",r.verified(),"code",r.code()));}
            var planned=b.actions().stream().skip(offset).limit(8).map(a->Map.of("tool",a.tool(),"callId",a.callId())).toList();int next=offset+Math.max(rows.size(),planned.size());result=Map.of("id",b.batchId(),"revision",b.revision(),"state",b.state(),"round",b.round(),"intent",b.intent(),"receipts",rows,"nextOffset",next,"more",Math.max(b.receipts().size(),b.actions().size())>next,"plannedActions",planned);
        }else if("worldReceipt".equals(args.get("kind"))){
            if(!args.keySet().equals(Set.of("kind","taskId","batchId","revision","receipt","offset","expectedHash")))throw new IllegalArgumentException("TASK_HISTORY_ARGUMENTS");var task=tasks.get(UUID.fromString(args.get("taskId"))).filter(t->t.ownerPlayerId().equals(viewer.getUUID())).orElseThrow(()->new SecurityException("TASK_HISTORY_NOT_OWNED"));var actions=MineAgentRuntimeServices.taskExecutor(server).worldActions();var b=actions.historyBatch(viewer.getUUID(),task.taskId(),UUID.fromString(args.get("batchId")));if(b.revision()!=Long.parseLong(args.get("revision")))throw new IllegalStateException("WORLD_ACTION_HISTORY_STALE");String text=JSON.writeValueAsString(actions.historyReceipt(task,b,Integer.parseInt(args.get("receipt"))));String hash=dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer.sha256(text.getBytes(java.nio.charset.StandardCharsets.UTF_8));int offset=Integer.parseInt(args.get("offset")),length=text.codePointCount(0,text.length());if(offset<0||offset>length||offset>0&&!hash.equals(args.get("expectedHash")))throw new IllegalStateException("WORLD_ACTION_PROJECTION_CHANGED");int next=Math.min(offset+4096,length);
            result=Map.of("text",text.substring(text.offsetByCodePoints(0,offset),text.offsetByCodePoints(0,next)),"nextOffset",next,"more",next<length,"hash",hash,"projection","CURRENT_SOURCE_AUTHORITY_NO_TASK_IMPERSONATION");
        }else throw new IllegalArgumentException("TASK_HISTORY_KIND");
        String encoded=JSON.writeValueAsString(result);if(encoded.getBytes(java.nio.charset.StandardCharsets.UTF_8).length>24000)throw new IllegalStateException("TASK_HISTORY_RESPONSE_BUDGET");return Map.of("state",encoded,"executionMode","OWNER_TASK_HISTORY_READ_ONLY_NO_MODEL");
    }
    private static Map<String,Object> summary(ManagedTask task){
        return Map.ofEntries(Map.entry("id",task.taskId()),Map.entry("agentId",task.agentId()),Map.entry("title",task.title()),Map.entry("status",task.status()),Map.entry("revision",task.revision()),Map.entry("intentRevision",task.intentRevision()),Map.entry("updatedAt",task.updatedAtEpochMillis()),Map.entry("archived",task.status()==TaskStatus.COMPLETED||task.status()==TaskStatus.CANCELLED),Map.entry("stepCount",task.steps().size()),Map.entry("completedSteps",task.steps().stream().filter(s->s.status()==TaskNodeStatus.COMPLETED).count()),Map.entry("reason",prefix(task.lastChangeReason(),256)),Map.entry("reasonTruncated",task.lastChangeReason().codePointCount(0,task.lastChangeReason().length())>256));
    }
    private static String prefix(String text,int count){return text.substring(0,text.offsetByCodePoints(0,Math.min(count,text.codePointCount(0,text.length()))));}
}
