package dev.mineagent.runtime.neoforge.ui;
import com.fasterxml.jackson.databind.*;import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;import net.minecraft.server.MinecraftServer;import net.minecraft.core.BlockPos;import net.minecraft.world.level.block.Blocks;import java.util.*;import java.nio.file.*;
public final class BuildingImportSmokeServer {
 public static volatile boolean ready,clientReady,complete,waiting;public static volatile UUID agent;public static volatile String failure="";private static final ObjectMapper JSON=new ObjectMapper();private static final List<Object> evidence=new ArrayList<>();private static boolean searched,inspected,applied,zeroStarted;private static Map<String,Object> receipt=Map.of();
 public static boolean active(){return Boolean.getBoolean("mineagent.conversationAgentReal")&&Boolean.getBoolean("mineagent.conversationAgentSmoke")&&Set.of("building_files","building_search","building_files_zero").contains(System.getProperty("mineagent.conversationAgentScenario",""));}
 public static boolean zero(){return active()&&System.getProperty("mineagent.conversationAgentScenario","").equals("building_files_zero");}
 public static boolean searchOnly(){return System.getProperty("mineagent.conversationAgentScenario","").equals("building_search");}
 public static void observe(String tool,JsonNode args,Map<String,Object> result){if(!active())return;evidence.add(Map.of("tool",tool,"arguments",args,"result",result));if(tool.equals("inspect_building_file")&&"LITEMATICA".equals(result.get("format")))inspected=true;if(tool.equals("apply_world_geometry")){receipt=result;applied="APPLIED".equals(result.get("status"));}}
 public static void web(String tool,Map<String,Object> result){if(!active())return;evidence.add(Map.of("tool",tool,"result",result));if(tool.equals("web_search")){searched=true;}}
 public static void save(MinecraftServer s,String name,Object data)throws Exception{Files.writeString(Files.createDirectories(s.getServerDirectory().resolve("building-import-smoke")).resolve(name+".json"),JSON.writeValueAsString(data));}
 public static void tick(MinecraftServer s){if(complete||!failure.isEmpty())return;var p=s.getPlayerList().getPlayers().stream().filter(v->!(v instanceof dev.mineagent.runtime.neoforge.body.MineAgentPlayer)).findFirst().orElse(null);if(p==null)return;try{
  if(!ready){s.getPlayerList().op(p.nameAndId());p.setGameMode(net.minecraft.world.level.GameType.CREATIVE);for(int x=-1;x<=4;x++)for(int z=-1;z<=4;z++)p.level().getChunk(x,z);for(var pos:BlockPos.betweenClosed(new BlockPos(-8,110,-8),new BlockPos(63,156,63)))p.level().setBlock(pos,pos.getY()==110?Blocks.SMOOTH_STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),2);p.teleportTo(p.level(),-4.5,111,4.5,Set.of(),-80,-5,true);agent=MineAgentRuntimeServices.bodies(s).createPersistentAt("建筑助手",p.getUUID(),p.level(),p.position().add(0,0,3)).agentId();ready=true;return;}
  if(s.getTickCount()%100==0)save(s,"progress",Map.of("searched",searched,"waiting",waiting,"inspected",inspected,"applied",applied,"tools",evidence));if(!clientReady)return;if(zero()){if(!zeroStarted){zeroStarted=true;ConversationAgentTools.execute(p,agent,UUID.randomUUID(),"inspect_building_files","{}",()->true).whenComplete((r,e)->s.execute(()->{try{var files=JSON.valueToTree(r.get("files"));if(files.isEmpty()){zeroStarted=false;return;}UUID file=UUID.fromString(files.get(0).path("id").asText());var args=JSON.createObjectNode().put("file_id",file.toString()).put("data_policy","blocks_only").put("rotation",90).put("mirror","x");args.putArray("anchor").add(4).add(111).add(4);ConversationAgentTools.execute(p,agent,UUID.randomUUID(),"plan_building_import",args.toString(),()->true).thenCompose(plan->{if(!"PLANNED".equals(plan.get("status")))throw new IllegalStateException("ZERO_PLAN_"+plan);return ConversationAgentTools.execute(p,agent,UUID.randomUUID(),"apply_world_geometry","{\"plan_id\":\""+plan.get("planId")+"\"}",()->true);}).whenComplete((value,failed)->s.execute(()->{try{if(failed!=null||!"APPLIED".equals(value.get("status"))||((Number)value.get("matchedAfterPhysics")).longValue()!=177)throw new IllegalStateException("ZERO_ROTATION_"+value,failed);save(s,"server",Map.of("status","ROTATED_MIRRORED_IMPORT_ZERO_MODEL_VERIFIED","receipt",value));complete=true;}catch(Exception ex){failure=ex.toString();}}));}catch(Exception ex){failure=ex.toString();}}));}return;}var store=ServerConversations.get(s).store();var cs=store.list(p.getUUID(),agent,"ALL","",0,20).conversations();if(cs.isEmpty())return;var c=cs.getFirst();if(c.messageCount()<2||!c.activeOperation().isEmpty())return;var ctx=store.context(p.getUUID(),agent,c.conversationId(),null).orElseThrow();save(s,"conversation",ctx);save(s,"tools",evidence);if(!ctx.requestState().equals("COMPLETE")||ctx.modelReceipt()==null||!ctx.modelReceipt().requestedModel().equals("deepseek-flash"))throw new IllegalStateException("BUILDING_REAL_CHAT_"+ctx.errorCode());if(searchOnly()){if(!searched||evidence.stream().noneMatch(v->((Map<?,?>)v).get("tool").equals("read_web_page")))throw new IllegalStateException("BUILDING_SEARCH_NOT_READ");save(s,"server",Map.of("status","REAL_BUILDING_SEARCH_AND_SOURCE_READ","tools",evidence));complete=true;return;}if(!searched||!inspected||!applied)throw new IllegalStateException("BUILDING_REAL_CHAIN_INCOMPLETE_"+receipt);
  var bounds=JSON.valueToTree(receipt.get("bounds"));BlockPos lo=new BlockPos(bounds.path("min").get(0).asInt(),bounds.path("min").get(1).asInt(),bounds.path("min").get(2).asInt()),hi=new BlockPos(bounds.path("max").get(0).asInt(),bounds.path("max").get(1).asInt(),bounds.path("max").get(2).asInt());long actual=0;var states=new TreeMap<String,Long>();for(var pos:BlockPos.betweenClosed(lo,hi)){var b=p.level().getBlockState(pos);if(!b.isAir()){actual++;states.merge(net.minecraft.commands.arguments.blocks.BlockStateParser.serialize(b),1L,Long::sum);}}if(actual!=((Number)receipt.get("selected")).longValue())throw new IllegalStateException("BUILDING_ACTUAL_COUNT_MISMATCH_"+actual);save(s,"server",Map.of("status","REAL_SEARCH_UPLOAD_PARSE_PLACE_NATIVE_VERIFIED","actualNonAir",actual,"states",states,"receipt",receipt,"fixturePlacesBuilding",false));complete=true;
 }catch(Exception e){failure=e.toString();try{save(s,"failure",Map.of("error",failure,"tools",evidence));}catch(Exception ignored){}}}
 private BuildingImportSmokeServer(){}
}
