package dev.mineagent.runtime.neoforge.ui;
import com.fasterxml.jackson.databind.*;import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;import dev.mineagent.runtime.neoforge.body.*;import net.minecraft.core.*;import net.minecraft.server.*;import net.minecraft.server.level.*;import net.minecraft.world.level.block.*;import net.minecraft.world.phys.*;import net.minecraft.world.item.*;import net.minecraft.world.InteractionHand;import java.util.*;import java.util.concurrent.*;import java.nio.file.*;
public final class ClearancePathSmokeServer {
 public static volatile boolean ready,clientReady,complete;public static volatile String failure="";public static volatile UUID agent;public static volatile int stage;public static final List<Object> evidence=new ArrayList<>();private static final ObjectMapper JSON=new ObjectMapper();private static int at,crouchTicks,standTicks;private static CompletableFuture<Map<String,Object>> pending;private static boolean paid;private static MineAgentPlayer follower;public static volatile int playerReuse;private static java.util.concurrent.atomic.AtomicBoolean permit;
 public static boolean active(){return Boolean.getBoolean("mineagent.conversationAgentSmoke")&&Set.of("clearance_path_zero","clearance_path","interaction_schema").contains(System.getProperty("mineagent.conversationAgentScenario",""));}public static boolean schema(){return System.getProperty("mineagent.conversationAgentScenario","").equals("interaction_schema");}public static boolean real(){return schema()||System.getProperty("mineagent.conversationAgentScenario","").equals("clearance_path");}
 private static void require(boolean value,String message){if(!value)throw new IllegalStateException(message);}
 private static void save(MinecraftServer s,String name,Object value)throws Exception{var root=Files.createDirectories(s.getServerDirectory().resolve("clearance-path-smoke"));Files.writeString(root.resolve(name+".json"),JSON.writeValueAsString(value));}
 private static CompletableFuture<Map<String,Object>> path(ServerPlayer p,int x,int y,int z){var a=JSON.createObjectNode();a.putArray("to").add(x).add(y).add(z);return ConversationAgentTools.execute(p,agent,UUID.randomUUID(),"build_agent_path",a.toString(),()->true);}
 private static void rule(ServerPlayer p,BlockPos pos,String event)throws Exception{var source=JSON.createObjectNode();source.putArray("position").add(pos.getX()).add(pos.getY()).add(pos.getZ());source.putArray("events").add(event);ServerInteractionRules.set(p,UUID.randomUUID(),JSON.createObjectNode().put("source",source.toString()),false);}
 private static void use(ServerPlayer p,BlockPos pos,InteractionHand hand){p.gameMode.useItemOn(p,p.level(),p.getItemInHand(hand),hand,new BlockHitResult(Vec3.atCenterOf(pos).add(0,.5,0),Direction.UP,pos,false));}
 public static void tick(MinecraftServer s){if(complete||!failure.isEmpty())return;var p=s.getPlayerList().getPlayers().stream().filter(v->!(v instanceof MineAgentPlayer)).findFirst().orElse(null);if(p==null)return;try{
  if(!ready){s.getPlayerList().op(p.nameAndId());p.setGameMode(net.minecraft.world.level.GameType.CREATIVE);for(var pos:BlockPos.betweenClosed(new BlockPos(-6,107,-3),new BlockPos(27,120,9)))p.level().setBlock(pos,pos.getY()==110?Blocks.SMOOTH_STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),2);for(var pos:BlockPos.betweenClosed(new BlockPos(-5,111,-1),new BlockPos(8,114,1)))if(pos.getZ()!=0||pos.getX()==-5)p.level().setBlock(pos,Blocks.STONE.defaultBlockState(),2);for(int x=-1;x<=3;x++)p.level().setBlock(new BlockPos(x,112,0),Blocks.STONE_SLAB.defaultBlockState().setValue(SlabBlock.TYPE,net.minecraft.world.level.block.state.properties.SlabType.TOP),2);for(int x=12;x<=21;x++)for(int y=107;y<=110;y++)p.level().setBlock(new BlockPos(x,y,4),Blocks.AIR.defaultBlockState(),2);p.teleportTo(p.level(),0.5,111,5.5,Set.of(),180,0,true);agent=MineAgentRuntimeServices.bodies(s).createPersistentAt("搭路助手",p.getUUID(),p.level(),new Vec3(-3.5,111,.5)).agentId();ready=true;at=s.getTickCount();return;}
  var b=MineAgentRuntimeServices.bodies(s).body(agent).orElseThrow();if(b.isCrouching())crouchTicks++;else standTicks++;if(!clientReady)return;if(s.getTickCount()%100==0)save(s,"progress",Map.of("stage",stage,"body",ConversationBodyTools.execute(p,agent,JSON.createObjectNode(),true),"evidence",evidence));
  if(real()){if(!paid){paid=true;ServerConversations.get(s).submitNative(p,agent,schema()?"请给(2,111,6)添加仅禁止放置的规则，不影响该点的破坏和使用；读回核对后结束，不进行其他动作。":"测试新能力：先用工具开启你自己的潜行再关闭，亲自走过低矮通道到(6,111,0)。然后从(11,111,4)到(18,111,4)搭一条玩家能跟着走、永久保留的圆石桥，再从(18,111,4)搭台阶到(21,113,4)，最后从(23,111,4)垂直跳跃垫高到(23,114,4)且留下梯子供我爬。不用传送或命令代替搭路。给(2,111,6)单独禁止放置，不禁破坏和使用；读取规则核对。不要执行电脑命令。",true);return;}var cs=ServerConversations.get(s).store().list(p.getUUID(),agent,"ACTIVE","",0,20).conversations();if(cs.isEmpty()||cs.getFirst().messageCount()<2||!cs.getFirst().activeOperation().isEmpty())return;var c=cs.getFirst();var ctx=ServerConversations.get(s).store().context(p.getUUID(),agent,c.conversationId(),null).orElseThrow();save(s,"real-context",ctx);require(ctx.requestState().equals("COMPLETE"),"REAL_CHAT_"+ctx.errorCode());if(!schema()){for(int x=12;x<=18;x++)require(p.level().getBlockState(new BlockPos(x,110,4)).is(Blocks.COBBLESTONE),"REAL_BRIDGE_MISSING");require(p.level().getBlockState(new BlockPos(21,112,4)).is(Blocks.COBBLESTONE),"REAL_STAIRS_MISSING");for(int y=111;y<=113;y++)require(p.level().getBlockState(new BlockPos(23,y,4)).is(Blocks.COBBLESTONE)&&p.level().getBlockState(new BlockPos(24,y,4)).is(Blocks.LADDER),"REAL_PILLAR_MISSING");}require(ServerInteractionRules.denied(p,new BlockPos(2,111,6),null,"block_place",false)&&!ServerInteractionRules.denied(p,new BlockPos(2,111,6),null,"block_break",false),"REAL_RULE_MISSING");save(s,"server",Map.of("status",schema()?"REAL_DEEPSEEK_RULE_SCHEMA_COMPLETE":"REAL_DEEPSEEK_PATH_COMPLETE","crouchTicks",crouchTicks));complete=true;return;}
  if(s.getTickCount()-at>5000)throw new IllegalStateException("NATIVE_SCENE_TIMEOUT");
  if(pending!=null){if(!pending.isDone()){if(stage==20&&p.level().getBlockState(new BlockPos(12,110,7)).is(Blocks.COBBLESTONE))ConversationBodyTools.execute(p,agent,JSON.createObjectNode().put("action","stop"),false);return;}var r=pending.join();evidence.add(r);pending=null;if(stage==17){require(r.get("status").equals("REJECTED")&&p.level().getBlockState(new BlockPos(15,110,8)).isAir()&&b.getMainHandItem().getCount()==1,"LOCK_NOT_ATOMIC");stage=19;}else if(stage==20){require(r.get("status").equals("CANCELLED")&&!b.taskControlOwned()&&p.level().getBlockState(new BlockPos(12,110,7)).is(Blocks.COBBLESTONE)&&p.level().getBlockState(new BlockPos(21,110,7)).isAir(),"PATH_STOP_NOT_PRESERVED");stage=21;}else{require(r.get("status").equals("APPLIED"),"PATH_RECEIPT:"+r);stage++;}}
  switch(stage){
   case 0->{require(!NativeSurfaceNavigation.clearPose(b,.5,111,.5,net.minecraft.world.entity.Pose.STANDING)&&NativeSurfaceNavigation.clearPose(b,.5,111,.5,net.minecraft.world.entity.Pose.CROUCHING),"POSE_CLEARANCE");ConversationBodyTools.execute(p,agent,JSON.createObjectNode().put("action","sneak").put("enabled",true),false);require(b.isCrouching()&&b.isShiftKeyDown(),"MANUAL_SNEAK");stage=1;at=s.getTickCount();}
   case 1->{if(s.getTickCount()-at<20)return;ConversationBodyTools.execute(p,agent,JSON.createObjectNode().put("action","sneak").put("enabled",false),false);require(!b.isCrouching(),"MANUAL_STAND");b.movementController().movePreciselyTo(new Vec3(6.5,111,.5));stage=2;}
   case 2->{if(b.movementController().target().isPresent())return;require(b.movementController().outcome().equals("ARRIVED"),"CROUCH_ROUTE:"+b.movementController().outcome());require(crouchTicks>20&&!b.isCrouching(),"AUTO_POSE_LIFECYCLE");evidence.add(Map.of("clearance",b.movementController().evidence(),"crouchTicks",crouchTicks,"restoredStanding",!b.isCrouching()));for(int x=-1;x<=3;x++)p.level().setBlock(new BlockPos(x,112,0),Blocks.STONE_SLAB.defaultBlockState(),2);require(NativeSurfaceNavigation.find(b,new Vec3(-3.5,111,.5),2048).isEmpty(),"TOO_LOW_ROUTE_ACCEPTED");interaction(p);b.teleportTo(p.level(),11.5,111,4.5,Set.of(),-90,0,true);at=s.getTickCount();stage=3;}
   case 3->{if(s.getTickCount()-at<10)return;pending=path(p,18,111,4);stage=4;}
   case 5->{pending=path(p,21,113,4);stage=6;}
   case 7->{b.teleportTo(p.level(),23.5,111,4.5,Set.of(),0,0,true);at=s.getTickCount();stage=8;}
   case 8->{if(s.getTickCount()-at<10)return;pending=path(p,23,114,4);stage=9;}
   case 10->{for(int x=12;x<=18;x++)require(p.level().getBlockState(new BlockPos(x,110,4)).is(Blocks.COBBLESTONE),"PERMANENT_BRIDGE");for(int y=111;y<=113;y++)require(p.level().getBlockState(new BlockPos(24,y,4)).is(Blocks.LADDER),"PERMANENT_LADDER");var id=MineAgentRuntimeServices.bodies(s).createPersistentAt("复用路线验证",p.getUUID(),p.level(),new Vec3(11.5,111,4.5)).agentId();follower=MineAgentRuntimeServices.bodies(s).body(id).orElseThrow();follower.movementController().movePreciselyTo(new Vec3(21.5,113,4.5));stage=11;}
   case 11->{if(follower.movementController().target().isPresent())return;require(follower.movementController().outcome().equals("ARRIVED"),"REUSE_STAIR_PATH");evidence.add(Map.of("secondBodyReusedBridgeAndStairs",true,"navigation",follower.movementController().evidence()));b.teleportTo(p.level(),26.5,111,8.5,Set.of(),0,0,true);p.teleportTo(p.level(),24.5,111,4.5,Set.of(),90,0,true);playerReuse=1;at=s.getTickCount();stage=12;}
   case 12->{if(p.getY()<113.9){require(s.getTickCount()-at<240,"PLAYER_LADDER_REUSE_FAILED");return;}playerReuse=0;evidence.add(Map.of("realPlayerClimbedLadder",true,"y",p.getY()));p.teleportTo(p.level(),11.5,111,4.5,Set.of(),-90,0,true);playerReuse=2;at=s.getTickCount();stage=13;}
   case 13->{if(p.getX()<18.15){require(s.getTickCount()-at<240,"PLAYER_BRIDGE_REUSE_FAILED");return;}playerReuse=0;evidence.add(Map.of("realPlayerWalkedPermanentBridge",true,"x",p.getX()));b.teleportTo(p.level(),11.5,111,8.5,Set.of(),-90,0,true);b.setGameMode(net.minecraft.world.level.GameType.SURVIVAL);b.getInventory().clearContent();b.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(Items.COBBLESTONE,4));for(int x=12;x<=21;x++)for(int y=107;y<=110;y++)p.level().setBlock(new BlockPos(x,y,8),Blocks.AIR.defaultBlockState(),2);at=s.getTickCount();stage=14;}
   case 14->{if(s.getTickCount()-at<10)return;pending=path(p,14,111,8);stage=15;}
   case 16->{require(b.getMainHandItem().getCount()==1,"SURVIVAL_MATERIAL_NOT_CONSUMED");evidence.add(Map.of("survivalPlaced",3,"remaining",1));var lock=new BlockPos(15,110,8);rule(p,lock,"block_place");var r=NativeAgentPathBuilder.start(p,agent,UUID.randomUUID(),JSON.createObjectNode().set("to",JSON.createArrayNode().add(15).add(111).add(8)),()->true);pending=r;stage=17;}
   case 17->{}
   case 18->{throw new IllegalStateException("UNEXPECTED_LOCK_SUCCESS");}
   case 19->{b.setGameMode(net.minecraft.world.level.GameType.CREATIVE);b.teleportTo(p.level(),11.5,111,7.5,Set.of(),-90,0,true);for(int x=12;x<=21;x++)for(int y=107;y<=110;y++)p.level().setBlock(new BlockPos(x,y,7),Blocks.AIR.defaultBlockState(),2);permit=new java.util.concurrent.atomic.AtomicBoolean(true);pending=NativeAgentPathBuilder.start(p,agent,UUID.randomUUID(),JSON.createObjectNode().set("to",JSON.createArrayNode().add(21).add(111).add(7)),permit::get);stage=20;}
   case 20->{if(p.level().getBlockState(new BlockPos(12,110,7)).is(Blocks.COBBLESTONE)){ConversationBodyTools.execute(p,agent,JSON.createObjectNode().put("action","stop"),false);}}
   case 21->{save(s,"server",Map.of("status","NATIVE_CLEARANCE_RULES_BRIDGE_STAIRS_PILLAR_VERIFIED","evidence",evidence));complete=true;}

  }
 }catch(Exception e){failure=e.toString();try{save(s,"failure",Map.of("stage",stage,"error",failure,"evidence",evidence));}catch(Exception ignored){}}}
 private static void interaction(ServerPlayer p)throws Exception{var l=p.level();var q=new BlockPos(2,111,6);l.setBlock(q,Blocks.CRAFTING_TABLE.defaultBlockState(),2);rule(p,q,"block_use");p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(Items.COBBLESTONE,5));use(p,q,InteractionHand.MAIN_HAND);require(l.getBlockState(q.above()).is(Blocks.COBBLESTONE)&&p.containerMenu==p.inventoryMenu,"USE_LOCK_BLOCKED_PLACEMENT");p.setItemInHand(InteractionHand.OFF_HAND,ItemStack.EMPTY);use(p,q,InteractionHand.OFF_HAND);require(p.containerMenu==p.inventoryMenu,"OFFHAND_BYPASSED_USE_LOCK");require(p.gameMode.destroyBlock(q),"USE_LOCK_BLOCKED_BREAK");
  q=new BlockPos(4,111,6);l.setBlock(q,Blocks.CRAFTING_TABLE.defaultBlockState(),2);rule(p,q.above(),"block_place");p.setShiftKeyDown(true);p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(Items.COBBLESTONE,5));use(p,q,InteractionHand.MAIN_HAND);p.setShiftKeyDown(false);require(l.getBlockState(q.above()).isAir(),"PLACE_LOCK_IGNORED");p.setItemInHand(InteractionHand.MAIN_HAND,ItemStack.EMPTY);use(p,q,InteractionHand.MAIN_HAND);require(p.containerMenu!=p.inventoryMenu,"PLACE_LOCK_BLOCKED_USE");p.closeContainer();require(p.gameMode.destroyBlock(q),"PLACE_LOCK_BLOCKED_BREAK");
  q=new BlockPos(6,111,6);l.setBlock(q,Blocks.CRAFTING_TABLE.defaultBlockState(),2);rule(p,q,"block_break");require(!p.gameMode.destroyBlock(q),"BREAK_LOCK_IGNORED");p.setItemInHand(InteractionHand.MAIN_HAND,ItemStack.EMPTY);use(p,q,InteractionHand.MAIN_HAND);require(p.containerMenu!=p.inventoryMenu,"BREAK_LOCK_BLOCKED_USE");p.closeContainer();p.setShiftKeyDown(true);p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(Items.COBBLESTONE));use(p,q,InteractionHand.MAIN_HAND);p.setShiftKeyDown(false);require(l.getBlockState(q.above()).is(Blocks.COBBLESTONE),"BREAK_LOCK_BLOCKED_PLACE");
  q=new BlockPos(8,111,6);rule(p,q.above(),"block_place");p.setGameMode(net.minecraft.world.level.GameType.SURVIVAL);p.setItemInHand(InteractionHand.MAIN_HAND,new ItemStack(Items.OAK_DOOR,3));use(p,q.below(),InteractionHand.MAIN_HAND);require(l.getBlockState(q).isAir()&&l.getBlockState(q.above()).isAir()&&p.getMainHandItem().getCount()==3,"MULTIPLACE_NOT_ATOMIC");p.setGameMode(net.minecraft.world.level.GameType.CREATIVE);evidence.add(Map.of("independentEvents",true,"offhandDenied",true,"multiPlaceRolledBack",true,"rules",ServerInteractionRules.inspect(p,0)));}
 private ClearancePathSmokeServer(){}
}
