package dev.mineagent.runtime.neoforge.ui;

import com.fasterxml.jackson.databind.*;
import dev.mineagent.runtime.api.packages.*;
import dev.mineagent.runtime.api.permission.PermissionAction;
import dev.mineagent.runtime.core.task.TaskStepSpec;
import dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer;
import dev.mineagent.runtime.neoforge.*;
import dev.mineagent.runtime.neoforge.network.UiPayloads;
import dev.mineagent.runtime.worker.generation.*;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.neoforged.neoforge.network.PacketDistributor;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;

/** Two actual recipients independently download/approve/reject signed CLIENT code. Provider and OS input remain unused. */
public final class ClientCodeDeliverySmokeServer {
    private static final ObjectMapper JSON=new ObjectMapper();private static final String RUN=UUID.randomUUID().toString();private static final Map<String,UUID> players=new LinkedHashMap<>(),rhinoRows=new LinkedHashMap<>(),javaRows=new LinkedHashMap<>();private static final Set<String> done=new HashSet<>(),seen=new HashSet<>();private static UUID task,agent,rhinoBatch,javaBatch;private static RuntimePackage rhinoPkg,javaPkg;private static int phase,ticks,after;private static boolean finished,failed;
    private ClientCodeDeliverySmokeServer(){}public static boolean enabled(){return Boolean.getBoolean("mineagent.clientCodeDeliverySmoke");}private static String role(ServerPlayer p){return p.nameAndId().name().equals("DeliveryA")?"A":p.nameAndId().name().equals("DeliveryB")?"B":"";}private static Path root(MinecraftServer s){return s.getServerDirectory().resolve("client-code-delivery-evidence").resolve(RUN);}private static void write(MinecraftServer s,String name,Object value)throws Exception{Files.createDirectories(root(s));Files.writeString(root(s).resolve(name),JSON.writeValueAsString(value));}private static void require(boolean value,String code){if(!value)throw new IllegalStateException(code);}private static Map<String,String> execute(MinecraftServer s,String tool,Object arguments)throws Exception{return ServerUiRuntime.get(s).deliveries().execute(MineAgentRuntimeServices.tasks(s).get(task).orElseThrow(),UUID.randomUUID(),tool,JSON.writeValueAsString(arguments));}private static JsonNode rows(MinecraftServer s,UUID batch)throws Exception{return JSON.readTree(execute(s,"query_deliveries",Map.of("batch_id",batch)).get("result")).path("deliveries");}private static JsonNode row(MinecraftServer s,UUID batch,String who)throws Exception{for(var row:rows(s,batch))if(row.path("recipient").asText().equals(players.get(who).toString()))return row;throw new IllegalStateException("CLIENT_CODE_DELIVERY_ROW");}
    private static NativeCompatibility compatibility(){return new NativeCompatibility(1,Map.of("CLIENT",new NativeCompatibility.Target("26.1.2","neoforge","26.1.2.106","official",25,Map.of())));}
    private static GeneratedFile file(String path,String source)throws Exception{byte[] bytes=source.getBytes(StandardCharsets.UTF_8);return new GeneratedFile(path,RuntimeResourceSide.CLIENT,path.endsWith(".java")?"text/x-java-source":"application/javascript",RuntimePackageCanonicalizer.sha256(bytes),bytes);}
    private static RuntimePackage install(MinecraftServer s,ServerPlayer owner,String name,String entryId,GeneratedFile file)throws Exception{return ServerPackageRuntime.get(s).importOwned(owner,UUID.randomUUID(),new ParsedRuntimePackage(name,"1.0",RuntimePackageType.EXTENSION,ActivationMode.HOT_RUNTIME,Map.of(),Set.of(),Map.of(entryId,new RuntimeEntrypoint(file.path(),file.side(),file.sha256())),List.of(),List.of(file),compatibility()));}
    private static UUID offer(MinecraftServer s,RuntimePackage pkg,String entry,String mode,UUID snapshot)throws Exception{var args=new LinkedHashMap<String,Object>();args.put("package_id",pkg.packageId());args.put("package_revision",pkg.revision());args.put("canonical_sha256",pkg.canonicalSha256());args.put("entry_id",entry);args.put("mode",mode);args.put("audience_snapshot_id",snapshot);args.put("data",Map.of());args.put("ttl_seconds",600);args.put("feedback_enabled",false);return UUID.fromString(JSON.readTree(execute(s,"offer_content",args).get("result")).path("id").asText());}
    public static void tick(MinecraftServer s)throws Exception{if(!enabled()||finished||failed)return;ticks++;try{for(var player:s.getPlayerList().getPlayers()){String role=role(player);if(!role.isEmpty())players.put(role,player.getUUID());}if(phase==0&&players.size()==2){var owner=s.getPlayerList().getPlayer(players.get("A"));var grants=new HashSet<>(MineAgentRuntimeServices.permissions(s).trustedActions(owner.getUUID()));grants.addAll(Set.of(PermissionAction.MANAGE_PACKAGES,PermissionAction.DISCOVER_OBJECTS,PermissionAction.OFFER_CONTENT));var config=MineAgentRuntimeServices.config(s);require(config.apply(new dev.mineagent.runtime.api.config.ConfigPatch(config.snapshot().revision(),Map.of("runtime.initialized","true","voice.output.enabled","false","permission.player."+owner.getUUID(),grants.stream().map(Enum::name).sorted().collect(java.util.stream.Collectors.joining(",")))),true).accepted(),"CLIENT_CODE_DELIVERY_CONFIG");MineAgentRuntimeServices.permissions(s).setTrustedActions(owner.getUUID(),grants);agent=MineAgentRuntimeServices.bodies(s).createPersistentAt("Client code delivery Actor",owner.getUUID(),s.overworld(),owner.position().add(2,0,0)).agentId();task=MineAgentRuntimeServices.tasks(s).create(agent,owner.getUUID(),"Explicit CLIENT code delivery fixture",1,List.of(new TaskStepSpec("execute",Set.of()))).taskId();rhinoPkg=install(s,owner,"CLIENT Rhino recipient fixture","client",file("client/delivered.js","client.status('DELIVERED_RHINO_RUNNING');track(client.cleanupStatus('DELIVERED_RHINO_CLEANED'));'RHINO';"));String java="""
                    package dev.mineagent.delivery; import java.util.Map; import dev.mineagent.runtime.api.packages.ClientRuntimeHost; import dev.mineagent.runtime.scripting.javaext.ClientRuntimeExtension;
                    public final class DeliveredExtension implements ClientRuntimeExtension { public Object start(Map<String,Object> bindings){var client=(ClientRuntimeHost)bindings.get("client");client.status("DELIVERED_JAVA_RUNNING");client.cleanupStatus("DELIVERED_JAVA_CLEANED");return "JAVA";} }
                    """;javaPkg=install(s,owner,"CLIENT Java recipient fixture","client_java",file("client/dev/mineagent/delivery/DeliveredExtension.java",java));var audiences=MineAgentRuntimeServices.taskExecutor(s).worldActions().audiences();var current=MineAgentRuntimeServices.tasks(s).get(task).orElseThrow();var definition=JSON.readTree(audiences.execute(current,UUID.randomUUID(),"create_audience","{\"mode\":\"SNAPSHOT\",\"query\":{\"kind\":\"PLAYER\"}}").get("result"));var snapshot=JSON.readTree(audiences.execute(current,UUID.randomUUID(),"resolve_audience",JSON.writeValueAsString(Map.of("audience_id",definition.path("audienceId").asText(),"expected_revision",1))).get("result"));UUID snap=UUID.fromString(snapshot.path("snapshotId").asText());rhinoBatch=offer(s,rhinoPkg,"client","CLIENT_RHINO",snap);javaBatch=offer(s,javaPkg,"client_java","CLIENT_JAVA",snap);for(String who:List.of("A","B")){rhinoRows.put(who,UUID.fromString(row(s,rhinoBatch,who).path("deliveryId").asText()));javaRows.put(who,UUID.fromString(row(s,javaBatch,who).path("deliveryId").asText()));}write(s,"fixture.json",Map.of("run",RUN,"players",players,"task",task,"agent",agent,"rhinoPackage",rhinoPkg,"javaPackage",javaPkg,"rhinoRows",rhinoRows,"javaRows",javaRows,"providerCalls",0,"systemInputInjected",false));phase=1;}
        if(phase==1){for(String who:List.of("A","B")){String rhino=row(s,rhinoBatch,who).path("status").asText(),java=row(s,javaBatch,who).path("status").asText();seen.add(who+"|RHINO|"+rhino);seen.add(who+"|JAVA|"+java);}if(done.size()==2){require(seen.containsAll(Set.of("A|RHINO|CODE_DOWNLOADED","A|RHINO|CODE_RUNNING","A|RHINO|CODE_STOPPED","A|JAVA|REJECTED","B|RHINO|REJECTED","B|JAVA|CODE_DOWNLOADED","B|JAVA|CODE_RUNNING","B|JAVA|CODE_STOPPED")),"CLIENT_CODE_DELIVERY_PHASES_MISSING");phase=2;after=ticks+40;}}
        if(phase==2&&ticks>=after&&s.getPlayerList().getPlayers().stream().noneMatch(p->!role(p).isEmpty())){String ar=row(s,rhinoBatch,"A").path("status").asText(),aj=row(s,javaBatch,"A").path("status").asText(),br=row(s,rhinoBatch,"B").path("status").asText(),bj=row(s,javaBatch,"B").path("status").asText();require(ar.equals("CODE_SUSPENDED")&&bj.equals("CODE_SUSPENDED")&&aj.equals("REJECTED")&&br.equals("REJECTED"),"CLIENT_CODE_DELIVERY_DISCONNECT_STATE");write(s,"result.json",Map.of("status","REAL_TWO_CLIENT_CODE_INVITE_APPROVE_REJECT_READINESS_VERIFIED","final",Map.of("aRhino",ar,"aJava",aj,"bRhino",br,"bJava",bj),"seen",seen.stream().sorted().toList(),"providerCalls",0,"systemInputInjected",false,"fullV1",false));finished=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_DELIVERY_SERVER_OK clientCode=true");s.halt(false);}}
        catch(Exception failure){failed=true;write(s,"failure.json",Map.of("phase",phase,"ticks",ticks,"error",failure.toString(),"seen",seen));s.halt(false);throw failure;}}
    public static void handle(ServerPlayer player,UiPayloads.Command packet)throws Exception{var s=player.level().getServer();var request=JSON.readTree(packet.json());String action=request.path("action").asText(),who=role(player);if(who.isEmpty())throw new SecurityException("CLIENT_CODE_DELIVERY_ROLE");if(action.equals("done"))done.add(who);else if(!action.equals("info"))throw new IllegalArgumentException("CLIENT_CODE_DELIVERY_ACTION");var result=new LinkedHashMap<String,Object>();result.put("run",RUN);result.put("ready",phase>0);result.put("phase",phase);result.put("rhinoPackage",rhinoPkg);result.put("javaPackage",javaPkg);if(phase>0){result.put("rhino",row(s,rhinoBatch,who));result.put("java",row(s,javaBatch,who));result.put("seen",seen);}PacketDistributor.sendToPlayer(player,new UiPayloads.Event(packet.requestId(),"clientCodeDeliveryFixture",JSON.writeValueAsString(result)));}
}
