package dev.mineagent.runtime.neoforge.ui;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.tick.ServerTickEvent;
import java.util.*;
import java.nio.file.*;
import net.minecraft.world.item.*;
@EventBusSubscriber(modid="mineagent_runtime")
public final class ConversationAgentSmokeServer {
    public static volatile boolean ready,pending,negative;public static volatile int verified;public static volatile String failure="";public static volatile UUID agent,conversation;
    @SubscribeEvent public static void tick(ServerTickEvent.Post e)throws Exception{if(!Boolean.getBoolean("mineagent.conversationAgentSmoke")||!failure.isEmpty())return;var s=e.getServer();if(AgentModelSmokeServer.active()){AgentModelSmokeServer.tick(s);return;}if(PythonHostSmokeServer.active()){PythonHostSmokeServer.tick(s);return;}if(ConversationRecoverySmokeServer.active()){ConversationRecoverySmokeServer.tick(e.getServer());return;}if(CreatureEventsSmokeServer.active()){CreatureEventsSmokeServer.tick(s);return;}if(ConversationWatchSmokeServer.active()){ConversationWatchSmokeServer.tick(s);return;}if(ConversationCreatureSmokeServer.active()){ConversationCreatureSmokeServer.tick(s);return;}if(ConversationThinkingSmokeServer.active()){ConversationThinkingSmokeServer.tick(s);return;}if(ProviderModelsSmokeServer.active()){ProviderModelsSmokeServer.tick(s);return;}if(ConversationFeedbackSmokeServer.active()){ConversationFeedbackSmokeServer.tick(s);return;}if(ConversationManagementSmokeServer.active()){ConversationManagementSmokeServer.tick(s);return;}if(ConversationAutonomySmokeServer.active()){ConversationAutonomySmokeServer.tick(s);return;}if(ConversationHostSmokeServer.active()){ConversationHostSmokeServer.tick(s);return;}if(ConversationDiamondSmokeServer.active()){ConversationDiamondSmokeServer.tick(s);return;}if(ConversationRuntimeItemSmokeServer.active()){ConversationRuntimeItemSmokeServer.tick(s);return;}if(ConversationInteractionSmokeServer.active()){ConversationInteractionSmokeServer.tick(s);return;}if(ConversationBuildSmokeServer.active()){ConversationBuildSmokeServer.tick(s);return;}var p=s.getPlayerList().getPlayers().stream().filter(x->!(x instanceof dev.mineagent.runtime.neoforge.body.MineAgentPlayer)).findFirst().orElse(null);if(p==null)return;
        try{if(!ready){s.getPlayerList().op(p.nameAndId());s.getCommands().performPrefixedCommand(p.createCommandSourceStack(),"gamerule keep_inventory false");s.getCommands().performPrefixedCommand(p.createCommandSourceStack(),"gamerule pvp true");p.getInventory().clearContent();var sword=new ItemStack(Items.IRON_SWORD);var custom=new net.minecraft.nbt.CompoundTag();custom.putString("preserve","original");sword.set(net.minecraft.core.component.DataComponents.CUSTOM_DATA,net.minecraft.world.item.component.CustomData.of(custom));p.getInventory().setItem(0,sword);p.getInventory().setSelectedSlot(0);p.inventoryMenu.broadcastChanges();agent=MineAgentRuntimeServices.bodies(s).createPersistentAt("工具助手",p.getUUID(),s.overworld(),p.position().add(3,0,0)).agentId();s.overworld().setBlockAndUpdate(p.blockPosition().offset(20,-8,0),net.minecraft.world.level.block.Blocks.DIAMOND_ORE.defaultBlockState());ready=true;return;}
            var store=ServerConversations.get(s).store();var list=store.list(p.getUUID(),agent,"ALL","",0,20).conversations();if(list.isEmpty())return;var c=list.getFirst();conversation=c.conversationId();pending=!c.activeOperation().isEmpty();if(pending||c.messageCount()<2||c.messageCount()%2!=0)return;var context=store.context(p.getUUID(),agent,conversation,null).orElseThrow();if(!context.requestState().equals("COMPLETE"))throw new IllegalStateException("CHAT_AGENT_CONVERSATION:"+context.errorCode());int stage=(int)c.messageCount()/2+(Boolean.getBoolean("mineagent.conversationAgentReal")&&System.getProperty("mineagent.conversationAgentScenario","").equals("rules")?2:0);if(stage<=verified)return;
            if(Boolean.getBoolean("mineagent.conversationAgentReal")&&(context.modelReceipt()==null||!context.modelReceipt().requestedModel().equals("deepseek-flash")||!context.modelReceipt().streamMode().equals("PROVIDER_STREAM")))throw new IllegalStateException("CHAT_AGENT_REAL_MODEL_RECEIPT");
            var sharp=p.registryAccess().lookupOrThrow(net.minecraft.core.registries.Registries.ENCHANTMENT).getOrThrow(net.minecraft.world.item.enchantment.Enchantments.SHARPNESS);
            if(stage==1){if(!p.getMainHandItem().is(Items.IRON_SWORD)||net.minecraft.world.item.enchantment.EnchantmentHelper.getTagEnchantmentLevel(sharp,p.getMainHandItem())!=3||!p.getMainHandItem().getHoverName().getString().equals("晨光")||!p.getMainHandItem().get(net.minecraft.core.component.DataComponents.CUSTOM_DATA).copyTag().getStringOr("preserve","").equals("original"))throw new IllegalStateException("CHAT_AGENT_HELD_ITEM_READBACK");ConversationAgentTools.execute(p,agent,UUID.randomUUID(),"modify_item","{\"slot\":0,\"expected_hash\":\""+"0".repeat(64)+"\",\"name\":\"BAD\"}",()->true).whenComplete((result,error)->{if(error!=null||!"REJECTED".equals(result.get("status"))||!p.getMainHandItem().getHoverName().getString().equals("晨光"))failure="CHAT_AGENT_STALE_HASH";else negative=true;});}
            if(stage==2){int count=0;for(int i=0;i<p.getInventory().getContainerSize();i++){var item=p.getInventory().getItem(i);if(item.is(Items.DIAMOND_SWORD)&&net.minecraft.world.item.enchantment.EnchantmentHelper.getTagEnchantmentLevel(sharp,item)==5)count+=item.getCount();}if(count!=1)throw new IllegalStateException("CHAT_AGENT_GIVE_READBACK");}
            if(stage==3&&(!p.level().getGameRules().get(net.minecraft.world.level.gamerules.GameRules.KEEP_INVENTORY)||p.level().getGameRules().get(net.minecraft.world.level.gamerules.GameRules.PVP)))throw new IllegalStateException("CHAT_AGENT_RULE_READBACK");
            var root=Files.createDirectories(s.getServerDirectory().resolve("conversation-agent-smoke"));Files.writeString(root.resolve("turn-"+stage+".json"),new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(Map.of("conversation",c,"context",context,"mainHand",p.getMainHandItem().toString(),"rules",Map.of("keep_inventory",p.level().getGameRules().get(net.minecraft.world.level.gamerules.GameRules.KEEP_INVENTORY),"pvp",p.level().getGameRules().get(net.minecraft.world.level.gamerules.GameRules.PVP)))));verified=stage;
        }catch(Exception error){failure=error.toString();}
    }
}
