package dev.mineagent.runtime.neoforge.ui;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;
import net.minecraft.server.MinecraftServer;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import net.minecraft.world.effect.MobEffectInstance;
import java.util.*;
import java.nio.file.*;
public final class ConversationManagementSmokeServer {
    public static volatile boolean ready;public static volatile int verified;public static volatile UUID agent;public static volatile String failure="",ysmModel="";
    public static boolean ysm(){return System.getProperty("mineagent.conversationAgentScenario","").startsWith("management_ysm");}
    public static boolean active(){return Boolean.getBoolean("mineagent.conversationAgentReal")&&Set.of("management","management_ysm","management_ysm_saved").contains(System.getProperty("mineagent.conversationAgentScenario",""));}
    private static boolean replaySubmitted;
    public static boolean saved(){return System.getProperty("mineagent.conversationAgentScenario","").equals("management_ysm_saved");}
    private static void save(MinecraftServer s,String name,Object value)throws Exception{Files.writeString(Files.createDirectories(s.getServerDirectory().resolve("management-smoke")).resolve(name+".json"),new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(value));}
    public static void tick(MinecraftServer s){if(!failure.isEmpty())return;var p=s.getPlayerList().getPlayers().stream().filter(v->!(v instanceof dev.mineagent.runtime.neoforge.body.MineAgentPlayer)).findFirst().orElse(null);if(p==null)return;try{
        if(!ready){s.getPlayerList().op(p.nameAndId());if(agent==null){var c=p.blockPosition();for(var pos:net.minecraft.core.BlockPos.betweenClosed(c.offset(-6,-1,-6),c.offset(6,5,6)))p.level().setBlockAndUpdate(pos,pos.getY()<c.getY()?net.minecraft.world.level.block.Blocks.STONE.defaultBlockState():net.minecraft.world.level.block.Blocks.AIR.defaultBlockState());p.addEffect(new MobEffectInstance(BuiltInRegistries.MOB_EFFECT.wrapAsHolder(BuiltInRegistries.MOB_EFFECT.getValue(Identifier.parse("minecraft:fire_resistance"))),24000,0));agent=MineAgentRuntimeServices.bodies(s).createPersistentAt("工具助手",p.getUUID(),p.level(),p.position().add(0,0,4)).agentId();}if(MineAgentRuntimeServices.bodies(s).body(agent).isEmpty())return;if(ysm()){var bridge=new dev.mineagent.runtime.neoforge.integration.NeoForgeYsmRuntimeBridge(s);if(!bridge.runtimeAvailable()||bridge.availableModels().isEmpty())return;save(s,"ysm-catalog",bridge.availableModels());}ready=true;return;}
        if(saved()){if(!replaySubmitted){replaySubmitted=true;String raw=Files.readString(s.getServerDirectory().resolve("runtime-item-source.json"));save(s,"source",Map.of("sha256",dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer.sha256(raw),"realModelCalls",0,"argumentsUnchanged",true));ConversationAgentTools.execute(p,agent,UUID.randomUUID(),"set_appearance",raw,()->true).whenComplete((result,error)->s.execute(()->{try{if(error!=null||!"APPLIED".equals(result.get("status")))throw new IllegalStateException("YSM_SAVED_APPLY_FAILED");var a=ConversationIdentityTools.appearance(p,agent);var selected=(Map<?,?>)((Map<?,?>)a.get("ysm")).get("nativeSelection");ysmModel=selected.get("model").toString();save(s,"ysm-result",a);verified=1;}catch(Exception e){failure=e.toString();}}));}return;}
        var store=ServerConversations.get(s).store();var list=store.list(p.getUUID(),agent,"ALL","",0,20).conversations();if(list.isEmpty())return;var c=list.getFirst();if(!c.activeOperation().isEmpty()||c.messageCount()<2||c.messageCount()/2<=verified)return;var context=store.context(p.getUUID(),agent,c.conversationId(),null).orElseThrow();save(s,"context-"+c.messageCount()/2,context);if(!context.requestState().equals("COMPLETE")||context.modelReceipt()==null||!context.modelReceipt().requestedModel().equals("deepseek-flash"))throw new IllegalStateException("MANAGEMENT_REAL_CHAT_FAILED");
        if(ysm()){var a=ConversationIdentityTools.appearance(p,agent);var nativeState=(Map<?,?>)((Map<?,?>)a.get("ysm")).get("nativeSelection");if(nativeState.isEmpty()||!a.get("vanillaSkin").equals(""))throw new IllegalStateException("YSM_NATIVE_SELECTION_MISSING");ysmModel=String.valueOf(nativeState.get("model"));save(s,"ysm-result",a);verified=1;return;}
        int stage=(int)c.messageCount()/2;var def=MineAgentRuntimeServices.bodies(s).definitions().stream().filter(a->a.agentId().equals(agent)).findFirst().orElseThrow();var persona=MineAgentRuntimeServices.personas(s).forModel(def);var speed=BuiltInRegistries.MOB_EFFECT.wrapAsHolder(BuiltInRegistries.MOB_EFFECT.getValue(Identifier.parse("minecraft:speed")));var fire=BuiltInRegistries.MOB_EFFECT.wrapAsHolder(BuiltInRegistries.MOB_EFFECT.getValue(Identifier.parse("minecraft:fire_resistance")));if(!p.hasEffect(fire))throw new IllegalStateException("UNRELATED_BUFF_LOST");
        if(stage==1){if(!persona.text().contains("星际向导")||!persona.text().contains("银河")||p.getEffect(speed)==null||p.getEffect(speed).getAmplifier()!=1||p.getEffect(speed).isVisible()||!ConversationIdentityTools.appearance(p,agent).get("vanillaSkin").equals("alex:wide"))throw new IllegalStateException("MANAGEMENT_NATIVE_READBACK");save(s,"persona",persona);save(s,"effects-given",ConversationEffectTools.inspect(p));save(s,"appearance",ConversationIdentityTools.appearance(p,agent));}
        if(stage==2){var msg=store.messages(p.getUUID(),agent,c.conversationId(),0,20).messages().stream().filter(m->m.role().equals("ASSISTANT")).reduce((a,b)->b).orElseThrow();var reply=store.chunk(p.getUUID(),agent,c.conversationId(),msg.messageId(),msg.revision(),0,4096).text();if(!reply.contains("银河")||!reply.contains("星际向导"))throw new IllegalStateException("PERSONA_NOT_CONSUMED_BY_REAL_MODEL");save(s,"persona-reply",Map.of("text",reply,"personaRevision",persona.revision()));}
        if(stage==3){if(p.getEffect(speed)==null||p.getEffect(speed).getAmplifier()!=0||p.getEffect(speed).getDuration()>600)throw new IllegalStateException("BUFF_MODIFICATION_FAILED");save(s,"effects-modified",ConversationEffectTools.inspect(p));}
        if(stage==4){if(p.hasEffect(speed))throw new IllegalStateException("BUFF_REMOVE_FAILED");save(s,"result",Map.of("status","REAL_PERSONA_APPEARANCE_EFFECTS_VERIFIED","personaRevision",persona.revision(),"effects",ConversationEffectTools.inspect(p),"unrelatedEffectPreserved",true));}verified=stage;
    }catch(Exception e){failure=e.toString();try{save(s,"failure",Map.of("error",failure));}catch(Exception ignored){}}}
}
