package dev.mineagent.runtime.neoforge.ui;
import dev.mineagent.runtime.neoforge.*;
import dev.mineagent.runtime.neoforge.task.ServerTaskStart;
import dev.mineagent.runtime.neoforge.content.*;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.item.*;
import net.minecraft.world.*;
import net.minecraft.world.phys.Vec3;
import java.util.*;
import java.nio.file.*;

/** Fixture actions are test-player interactions, never substituted model output or navigation. */
public final class ConversationCreatureSmokeServer {
 public static volatile boolean ready,complete,clientReady;public static volatile int stage;public static volatile UUID agent,mainEntity;public static volatile String failure="";
 private static final com.fasterxml.jackson.databind.ObjectMapper JSON=new com.fasterxml.jackson.databind.ObjectMapper();
 private static final List<Map<String,Object>> receipts=new ArrayList<>();private static boolean loaded;private static int started;private static Vec3 start;private static RuntimeCreatureEntity main,partner,enemy,neutral;private static net.minecraft.world.entity.monster.zombie.Zombie dummy;private static float initialHealth;private static double patrolDisplacement;
 public static boolean active(){return Boolean.getBoolean("mineagent.conversationAgentSmoke")&&Boolean.getBoolean("mineagent.conversationAgentReal")&&Set.of("creatures","creatures_saved").contains(System.getProperty("mineagent.conversationAgentScenario",""));}
 public static boolean saved(){return System.getProperty("mineagent.conversationAgentScenario","").equals("creatures_saved");}
 public static void observe(String tool,com.fasterxml.jackson.databind.JsonNode args,Map<String,Object> result){if(active())receipts.add(Map.of("tool",tool,"arguments",args,"result",result));}
 private static void save(MinecraftServer s,String name,Object data)throws Exception{Files.writeString(Files.createDirectories(s.getServerDirectory().resolve("creature-smoke")).resolve(name+".json"),JSON.writeValueAsString(data));}
 private static long event(RuntimeCreatureEntity e,String k){return ((Number)((Map<?,?>)e.observation().get("events")).get(k)).longValue();}
 private static void require(boolean v,String code){if(!v)throw new IllegalStateException(code);}
 public static void tick(MinecraftServer s){if(complete||!failure.isEmpty())return;if(ready&&CinematicSmokeTiming.pause("creature-interactions",stage,stage==0||stage>=9?0:4000))return;var p=s.getPlayerList().getPlayers().stream().filter(x->!(x instanceof dev.mineagent.runtime.neoforge.body.MineAgentPlayer)).findFirst().orElse(null);if(p==null)return;try{
  if(!ready){s.getPlayerList().op(p.nameAndId());p.setGameMode(net.minecraft.world.level.GameType.CREATIVE);var b=p.blockPosition();for(var pos:net.minecraft.core.BlockPos.betweenClosed(b.offset(-20,-1,-20),b.offset(20,7,20)))p.level().setBlockAndUpdate(pos,pos.getY()<b.getY()?net.minecraft.world.level.block.Blocks.STONE.defaultBlockState():net.minecraft.world.level.block.Blocks.AIR.defaultBlockState());agent=MineAgentRuntimeServices.bodies(s).createPersistentAt("生物助手",p.getUUID(),p.level(),p.position().add(-5,0,-5)).agentId();ready=true;return;}
  if(!loaded){if(!clientReady)return;if(!ServerTaskStart.allowed(p,agent))return;
   if(saved()){var data=JSON.readTree(Files.readString(s.getServerDirectory().resolve("runtime-item-source.json")));for(var row:data.path("species")){var args=JSON.createObjectNode().put("source",row.path("source").asText());var r=RuntimeCreatures.define(p,UUID.randomUUID(),args);var id=((dev.mineagent.runtime.core.creature.CreatureStore.Species)r.get("species")).id();RuntimeCreatures.control(p,JSON.createObjectNode().put("action","spawn").put("species_id",id.toString()).set("position",JSON.valueToTree(List.of(p.getX()+4,p.getY(),p.getZ()+receipts.size()*3))));receipts.add(Map.of("savedSource",row));}}
   else{var store=ServerConversations.get(s).store();var list=store.list(p.getUUID(),agent,"ALL","",0,20).conversations();if(list.isEmpty())return;var c=list.getFirst();if(!c.activeOperation().isEmpty()||c.messageCount()<2)return;var context=store.context(p.getUUID(),agent,c.conversationId(),null).orElseThrow();save(s,"conversation",Map.of("context",context,"receipts",receipts));require(context.requestState().equals("COMPLETE")&&context.modelReceipt()!=null&&context.modelReceipt().requestedModel().equals("deepseek-flash"),"CREATURE_REAL_CONVERSATION_FAILED");}
   var inspect=RuntimeCreatures.inspect(p,JSON.createObjectNode());save(s,"source",inspect);var creatures=new ArrayList<RuntimeCreatureEntity>();for(var e:p.level().getAllEntities())if(e instanceof RuntimeCreatureEntity c&&p.getUUID().equals(c.owner()))creatures.add(c);main=creatures.stream().filter(e->e.definition().disposition().equals("friendly")).findFirst().orElseThrow();enemy=creatures.stream().filter(e->e.definition().disposition().equals("hostile")).findFirst().orElseThrow();neutral=creatures.stream().filter(e->e.definition().disposition().equals("neutral")).findFirst().orElseThrow();var d=main.definition();require(d.rideable()&&d.companion()&&!d.food().isEmpty()&&!d.trades().isEmpty()&&d.barter()!=null&&d.proximityRadius()>0,"CREATURE_MODEL_MISSING_BEHAVIOURS");require(JSON.readTree(d.model()).has("primitives"),"CREATURE_CUSTOM_GEOMETRY_MISSING");mainEntity=main.getUUID();main.setPos(p.position().add(0,0,3));enemy.setPos(p.position().add(14,0,0));neutral.setPos(p.position().add(14,0,4));loaded=true;stage=1;started=s.getTickCount();return;
  }
  int elapsed=s.getTickCount()-started;if(stage==6)patrolDisplacement=Math.max(patrolDisplacement,main.distanceToSqr(start));if(elapsed>1000)throw new IllegalStateException("CREATURE_NATIVE_TIMEOUT_STAGE_"+stage);
  if(stage==1&&elapsed>40){require(event(main,"proximity")>0,"CREATURE_PROXIMITY_NOT_FIRED");p.setShiftKeyDown(true);main.mobInteract(p,InteractionHand.MAIN_HAND);p.setShiftKeyDown(false);require(p.containerMenu instanceof net.minecraft.world.inventory.MerchantMenu,"CREATURE_NATIVE_MERCHANT_MENU");stage=2;started=s.getTickCount();return;}
  if(stage==2&&elapsed>40){var menu=(net.minecraft.world.inventory.MerchantMenu)p.containerMenu;var offer=main.getOffers().getFirst();menu.getSlot(0).set(offer.getCostA().copy());menu.slotsChanged(menu.getSlot(0).container);require(!menu.getSlot(2).getItem().isEmpty(),"CREATURE_TRADE_OUTPUT_EMPTY");menu.clicked(2,0,net.minecraft.world.inventory.ContainerInput.PICKUP,p);require(event(main,"trade")==1&&ItemStack.isSameItem(menu.getCarried(),offer.getResult()),"CREATURE_TRADE_NOT_COMMITTED");p.closeContainer();main.setPos(p.position().add(5,0,0));var t=main.definition().barter();p.level().addFreshEntity(new ItemEntity(p.level(),main.getX(),main.getY(),main.getZ(),new ItemStack(RuntimeCreatureEntity.item(t.input()),t.inputCount())));stage=3;started=s.getTickCount();return;}
  if(stage==3&&event(main,"barter")>0){require(p.level().getEntitiesOfClass(ItemEntity.class,main.getBoundingBox().inflate(4)).stream().anyMatch(i->i.getItem().is(RuntimeCreatureEntity.item(main.definition().barter().output()))),"CREATURE_BARTER_OUTPUT_ABSENT");var spawn=RuntimeCreatures.control(p,JSON.createObjectNode().put("action","spawn").put("species_id",main.species().toString()).set("position",JSON.valueToTree(List.of(main.getX()+2,main.getY(),main.getZ()))));partner=(RuntimeCreatureEntity)p.level().getEntity(UUID.fromString(((Map<?,?>)spawn.get("entity")).get("entity_id").toString()));p.getInventory().setItem(0,new ItemStack(RuntimeCreatureEntity.item(main.definition().food()),2));p.getInventory().setSelectedSlot(0);main.mobInteract(p,InteractionHand.MAIN_HAND);partner.mobInteract(p,InteractionHand.MAIN_HAND);require(main.isInLove()&&partner.isInLove(),"CREATURE_FEED_NOT_LOVE");stage=4;started=s.getTickCount();return;}
  if(stage==4&&event(main,"breeding")+event(partner,"breeding")>0){require(p.level().getEntitiesOfClass(RuntimeCreatureEntity.class,main.getBoundingBox().inflate(8)).stream().anyMatch(c->c.isBaby()&&main.species().equals(c.species())),"CREATURE_CHILD_MISSING");partner.setPos(p.position().add(15,0,-10));main.setPos(p.position().add(6,0,0));start=main.position();main.command("follow",List.of(),null);stage=5;started=s.getTickCount();return;}
  if(stage==5&&elapsed>100){require(main.distanceToSqr(start)>4&&main.distanceToSqr(p)<10,"CREATURE_FOLLOW_NOT_MOVED");main.command("stay",List.of(),null);var base=p.position().add(4,0,4);main.command("patrol",List.of(base,base.add(-8,0,0)),null);start=main.position();stage=6;started=s.getTickCount();return;}
  if(stage==6&&elapsed>100){require(patrolDisplacement>4,"CREATURE_PATROL_NOT_MOVED");main.command("stay",List.of(),null);dummy=new net.minecraft.world.entity.monster.zombie.Zombie(EntityType.ZOMBIE,p.level());dummy.setNoAi(true);dummy.setPos(main.position().add(1,0,0));dummy.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.IRON_HELMET));p.level().addFreshEntity(dummy);initialHealth=dummy.getHealth();main.command("attack",List.of(),dummy);stage=7;started=s.getTickCount();return;}
  if(stage==7&&dummy.getHealth()<initialHealth){require(event(main,"attack")>0,"CREATURE_ATTACK_EVENT");main.command("stay",List.of(),null);dummy.discard();p.getInventory().setItem(0,ItemStack.EMPTY);p.inventoryMenu.broadcastChanges();main.setPos(p.position().add(0,0,1));p.setShiftKeyDown(false);main.mobInteract(p,InteractionHand.MAIN_HAND);p.setShiftKeyDown(false);require(p.getVehicle()==main,"CREATURE_MOUNT_NOT_NATIVE");start=main.position();stage=8;started=s.getTickCount();return;}
  if(stage==8&&elapsed>60){require(main.distanceToSqr(start)>.5,"CREATURE_RIDING_INPUT_DID_NOT_MOVE");p.stopRiding();main.command("stay",List.of(),null);enemy.setPos(p.position().add(2,0,0));p.setGameMode(net.minecraft.world.level.GameType.SURVIVAL);p.setHealth(p.getMaxHealth());initialHealth=p.getHealth();stage=9;started=s.getTickCount();return;}
  if(stage==9&&event(enemy,"attack")>0&&p.getHealth()<initialHealth){require(event(enemy,"attack")>0,"CREATURE_HOSTILE_NOT_ATTACKING");p.setGameMode(net.minecraft.world.level.GameType.CREATIVE);enemy.discard();dummy=new net.minecraft.world.entity.monster.zombie.Zombie(EntityType.ZOMBIE,p.level());dummy.setNoAi(true);dummy.setPos(neutral.position().add(1,0,0));dummy.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.IRON_HELMET));p.level().addFreshEntity(dummy);neutral.hurtServer(p.level(),p.level().damageSources().mobAttack(dummy),1);initialHealth=dummy.getHealth();stage=10;started=s.getTickCount();return;}
  if(stage==10&&dummy.getHealth()<initialHealth){require(event(neutral,"attack")>0,"CREATURE_NEUTRAL_RETALIATION");dummy.discard();var output=net.minecraft.world.level.storage.TagValueOutput.createWithContext(net.minecraft.util.ProblemReporter.DISCARDING,p.registryAccess());main.saveWithoutId(output);var restored=new RuntimeCreatureEntity(MineAgentRegistries.RUNTIME_CREATURE.get(),p.level());restored.load(net.minecraft.world.level.storage.TagValueInput.create(net.minecraft.util.ProblemReporter.DISCARDING,p.registryAccess(),output.buildResult()));require(main.species().equals(restored.species())&&main.definition().equals(restored.definition())&&main.observation().get("events").equals(restored.observation().get("events")),"CREATURE_NBT_RESTORE");save(s,"result",Map.of("status","CREATURE_SEVEN_INTERACTIONS_NATIVE_VERIFIED","main",main.observation(),"neutral",neutral.observation(),"fixtureActions","Explicit test player inputs and scene staging; model definitions unchanged","savedRealArtifact",saved(),"nativeNbtRoundTrip",true));stage=11;complete=true;}
 }catch(Exception e){failure=e.toString();try{save(s,"failure",Map.of("stage",stage,"error",failure,"receipts",receipts,"main",main==null?Map.of():main.observation(),"patrolDisplacement",patrolDisplacement,"enemy",enemy==null?Map.of():enemy.observation(),"player",Map.of("health",p.getHealth(),"position",List.of(p.getX(),p.getY(),p.getZ()))));}catch(Exception ignored){}}}
}
