package dev.mineagent.runtime.neoforge.ui;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;
import dev.mineagent.runtime.neoforge.content.*;
import net.minecraft.server.MinecraftServer;
import java.util.*;import java.nio.file.*;
public final class ConversationWatchSmokeServer {
 public static volatile boolean ready,generated,change,changed,historyStarted,historyVerified;public static volatile UUID agent,object;public static volatile String failure="";public static volatile double expectedX;public static volatile int expectedStone;private static UUID pack;private static final com.fasterxml.jackson.databind.ObjectMapper JSON=new com.fasterxml.jackson.databind.ObjectMapper();
 public static boolean active(){return Boolean.getBoolean("mineagent.conversationAgentSmoke")&&Boolean.getBoolean("mineagent.conversationAgentReal")&&Set.of("watch_ui","watch_ui_saved").contains(System.getProperty("mineagent.conversationAgentScenario",""));}
 public static boolean saved(){return System.getProperty("mineagent.conversationAgentScenario","").equals("watch_ui_saved");}
 public static void observe(String tool,Map<String,Object> result){if(active()&&tool.equals("generate_content_package")&&result.containsKey("packageId"))pack=UUID.fromString(result.get("packageId").toString());}
 public static void tick(MinecraftServer s){if(!failure.isEmpty())return;var p=s.getPlayerList().getPlayers().stream().filter(e->!(e instanceof dev.mineagent.runtime.neoforge.body.MineAgentPlayer)).findFirst().orElse(null);if(p==null)return;try{var root=Files.createDirectories(s.getServerDirectory().resolve("watch-smoke"));
  if(!ready){s.getPlayerList().op(p.nameAndId());p.setGameMode(net.minecraft.world.level.GameType.CREATIVE);var base=p.blockPosition();for(var b:net.minecraft.core.BlockPos.betweenClosed(base.offset(-8,-1,-8),base.offset(8,5,8)))p.level().setBlockAndUpdate(b,b.getY()<base.getY()?net.minecraft.world.level.block.Blocks.STONE.defaultBlockState():net.minecraft.world.level.block.Blocks.AIR.defaultBlockState());agent=MineAgentRuntimeServices.bodies(s).createPersistentAt("读数助手",p.getUUID(),p.level(),p.position().add(-3,0,0)).agentId();ready=true;return;}
  var runtime=ServerPackageRuntime.get(s);var world=WorldContentRuntime.get(s);
  if(!generated){if(!dev.mineagent.runtime.neoforge.task.ServerTaskStart.allowed(p,agent))return;if(saved()){String raw=Files.readString(s.getServerDirectory().resolve("runtime-item-source.json"));var parsed=new dev.mineagent.runtime.worker.generation.RuntimePackageOutputParser().parse(dev.mineagent.runtime.worker.generation.GeneratedMetadata.complete(raw));var pkg=runtime.importOwned(p,UUID.randomUUID(),parsed);pack=pkg.packageId();for(var d:pkg.definitions().values())world.activate(p,UUID.randomUUID(),pack,runtime.worldLibrary().get(pack).orElseThrow().revision(),d.definitionId(),new dev.mineagent.runtime.api.packages.RuntimeInstanceLocation(p.level().dimension().identifier().toString(),p.getX()+2,p.getY(),p.getZ(),0,0),true,false);}
   else{var store=ServerConversations.get(s).store();var list=store.list(p.getUUID(),agent,"ALL","",0,20).conversations();if(list.isEmpty())return;var c=list.getFirst();if(c.messageCount()<2||!c.activeOperation().isEmpty())return;var context=store.context(p.getUUID(),agent,c.conversationId(),null).orElseThrow();Files.writeString(root.resolve("conversation.json"),JSON.writeValueAsString(context));for(var j:runtime.list(p.getUUID()))if(!j.rawOutputSha256().isBlank())Files.write(root.resolve("raw-"+j.operationId()+".json"),runtime.worldContent().read(j.rawOutputSha256()));if(!context.requestState().equals("COMPLETE")||pack==null)throw new IllegalStateException("WATCH_REAL_GENERATION_FAILED:"+context.errorCode());}
   var pkg=runtime.worldLibrary().get(pack).orElseThrow();if(ServerPackageRuntime.uiEntry(pkg).isEmpty())throw new IllegalStateException("WATCH_HTML_MISSING");var live=world.list(p.getUUID()).stream().filter(a->a.packageId().equals(pack)&&a.state().equals("ACTIVE")).findFirst().orElseThrow();for(var e:p.level().getAllEntities())if(e instanceof RuntimeObjectEntity o&&o.header()!=null&&o.header().instance().equals(live.instanceId())){object=e.getUUID();break;}if(object==null)throw new IllegalStateException("WATCH_NATIVE_OBJECT_MISSING");Files.writeString(root.resolve("generated.json"),JSON.writeValueAsString(Map.of("package",pkg,"activation",live,"object",object)));generated=true;
  }
  if(change&&!changed){p.teleportTo(p.getX()+1,p.getY(),p.getZ());var b=p.blockPosition().offset(1,0,0);p.level().setBlockAndUpdate(b,net.minecraft.world.level.block.Blocks.STONE.defaultBlockState());changed=true;}
  if(historyStarted&&!historyVerified){var copies=runtime.ownedHeads(p.getUUID(),0,32).items().stream().filter(v->!v.packageId().equals(pack)&&v.origin()==dev.mineagent.runtime.api.packages.PackageOrigin.REUSED).toList();for(var copy:copies){var live=world.list(p.getUUID());if(live.stream().anyMatch(a->a.packageId().equals(copy.packageId())&&a.state().equals("ACTIVE"))){if(live.stream().noneMatch(a->a.packageId().equals(pack)&&a.state().equals("ACTIVE")))throw new IllegalStateException("HISTORY_ORIGINAL_INSTANCE_LOST");Files.writeString(root.resolve("history.json"),JSON.writeValueAsString(Map.of("status","NATIVE_HISTORICAL_COPY_ACTIVATION_VERIFIED","original",pack,"copy",copy,"activations",live)));historyVerified=true;}}}
  expectedX=p.getX();int count=0;for(var b:net.minecraft.core.BlockPos.betweenClosed(p.blockPosition().offset(-2,-2,-2),p.blockPosition().offset(2,2,2)))if(p.level().getBlockState(b).is(net.minecraft.world.level.block.Blocks.STONE))count++;expectedStone=count;
 }catch(Exception e){failure=e.toString();}}
}
