package dev.mineagent.runtime.neoforge.ui;
import dev.mineagent.runtime.neoforge.*;
import dev.mineagent.runtime.neoforge.content.*;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.*;
import net.minecraft.world.item.*;
import java.util.*;import java.nio.file.*;
/** Actual provider definitions; fixture stages explicit player proximity, not model output or effects. */
public final class CreatureEventsSmokeServer {
 public static volatile boolean ready,clientReady,complete;public static volatile UUID agent;public static volatile String failure="";public static volatile int stage;
 private static int since;private static RuntimeCreatureEntity helper,bomb;private static net.minecraft.world.entity.monster.zombie.Zombie target;private static float health;private static net.minecraft.core.BlockPos block;private static net.minecraft.world.phys.Vec3 origin;private static final com.fasterxml.jackson.databind.ObjectMapper JSON=new com.fasterxml.jackson.databind.ObjectMapper();
 public static boolean active(){return Boolean.getBoolean("mineagent.conversationAgentSmoke")&&Boolean.getBoolean("mineagent.conversationAgentReal")&&Set.of("creature_events","creature_events_saved").contains(System.getProperty("mineagent.conversationAgentScenario",""));}
 public static boolean saved(){return System.getProperty("mineagent.conversationAgentScenario","").endsWith("_saved");}
 private static void save(MinecraftServer s,String name,Object v)throws Exception{Files.writeString(Files.createDirectories(s.getServerDirectory().resolve("creature-events-smoke")).resolve(name+".json"),JSON.writeValueAsString(v));}
 private static void require(boolean v,String message){if(!v)throw new IllegalStateException(message);}
 private static long event(RuntimeCreatureEntity e,String name){return ((Number)((Map<?,?>)e.observation().get("events")).get(name)).longValue();}
 private static int apples(ServerPlayer p){int n=0;for(var i:p.getInventory().getNonEquipmentItems())if(i.is(Items.APPLE))n+=i.getCount();return n;}
 private static RuntimeCreatureEntity spawn(ServerPlayer p,UUID id,double dx)throws Exception{var args=JSON.createObjectNode().put("action","spawn").put("species_id",id.toString());args.set("position",JSON.valueToTree(List.of(p.getX()+dx,p.getY(),p.getZ())));var r=RuntimeCreatures.control(p,args);return (RuntimeCreatureEntity)p.level().getEntity(UUID.fromString(((Map<?,?>)r.get("entity")).get("entity_id").toString()));}
 private static int fuse(RuntimeCreatureEntity e){return ((Number)e.observation().get("fuseTicks")).intValue();}
 public static void tick(MinecraftServer s){if(complete||!failure.isEmpty())return;var p=s.getPlayerList().getPlayers().stream().filter(x->!(x instanceof dev.mineagent.runtime.neoforge.body.MineAgentPlayer)).findFirst().orElse(null);if(p==null)return;try{
  if(!ready){s.getPlayerList().op(p.nameAndId());p.setGameMode(net.minecraft.world.level.GameType.CREATIVE);p.getInventory().clearContent();var b=p.blockPosition();for(var pos:net.minecraft.core.BlockPos.betweenClosed(b.offset(-16,-1,-16),b.offset(16,6,16)))p.level().setBlockAndUpdate(pos,pos.getY()<b.getY()?net.minecraft.world.level.block.Blocks.STONE.defaultBlockState():net.minecraft.world.level.block.Blocks.AIR.defaultBlockState());agent=MineAgentRuntimeServices.bodies(s).createPersistentAt("事件助手",p.getUUID(),p.level(),p.position().add(12,0,12)).agentId();origin=p.position();ready=true;return;}
  if(stage==0){if(!clientReady||!dev.mineagent.runtime.neoforge.task.ServerTaskStart.allowed(p,agent))return;
   if(saved()){var source=JSON.readTree(Files.readString(s.getServerDirectory().resolve("runtime-item-source.json")));for(var v:source.path("species"))RuntimeCreatures.define(p,UUID.randomUUID(),JSON.createObjectNode().put("source",v.path("source").asText()));}
   else {var store=ServerConversations.get(s).store();var list=store.list(p.getUUID(),agent,"ALL","",0,20).conversations();if(list.isEmpty())return;var c=list.getFirst();if(c.messageCount()<2||!c.activeOperation().isEmpty())return;var ctx=store.context(p.getUUID(),agent,c.conversationId(),null).orElseThrow();save(s,"conversation",ctx);require(ctx.requestState().equals("COMPLETE")&&ctx.modelReceipt()!=null&&ctx.modelReceipt().requestedModel().equals("deepseek-flash"),"EVENTS_REAL_CHAT_FAILED");}
   var data=RuntimeCreatures.inspect(p,JSON.createObjectNode());save(s,"source",data);var species=(List<dev.mineagent.runtime.core.creature.CreatureStore.Species>)data.get("species");var h=species.stream().filter(v->v.definition().proximityActions().stream().anyMatch(a->a.type().equals("give_item"))).findFirst().orElseThrow();var b=species.stream().filter(v->v.definition().proximityActions().stream().anyMatch(a->a.type().equals("explosion"))).findFirst().orElseThrow();require(h.definition().proximityActions().stream().anyMatch(a->a.type().equals("effect")&&a.id().equals("minecraft:speed")&&a.level()==2),"EVENTS_MODEL_EFFECT_MISSING");require(h.definition().proximityActions().stream().anyMatch(a->a.type().equals("sound")),"EVENTS_MODEL_SOUND_MISSING");require(b.definition().proximityActions().stream().filter(a->a.type().equals("explosion")).allMatch(a->!a.breakBlocks()&&a.fuseTicks()>=30),"EVENTS_MODEL_EXPLOSION_CONTRACT");helper=spawn(p,h.id(),6);bomb=spawn(p,b.id(),-8);helper.setPos(origin.add(2,0,0));stage=1;since=s.getTickCount();return;
  }
  int elapsed=s.getTickCount()-since;if(elapsed>600)throw new IllegalStateException("EVENTS_TIMEOUT_"+stage);
  if(stage==1&&event(helper,"give_item")>0){require(apples(p)==2&&event(helper,"effect")==1&&event(helper,"sound")==1,"EVENTS_NATIVE_ENTRY_ACTIONS");var effect=p.getEffect(net.minecraft.world.effect.MobEffects.SPEED);require(effect!=null&&effect.getAmplifier()==1&&effect.getDuration()>0,"EVENTS_NATIVE_BUFF");stage=2;since=s.getTickCount();return;}
  if(stage==2&&elapsed>40){require(apples(p)==2&&event(helper,"give_item")==1,"EVENTS_REPEATED_WHILE_INSIDE");helper.setPos(origin.add(8,0,0));stage=3;since=s.getTickCount();return;}
  if(stage==3&&elapsed>helper.definition().proximityCooldown()+20){helper.setPos(origin.add(2,0,0));stage=4;since=s.getTickCount();return;}
  if(stage==4&&event(helper,"give_item")==2){require(apples(p)==4,"EVENTS_REENTRY_GIFT");helper.setPos(origin.add(12,0,8));bomb.setPos(origin.add(-2,0,0));stage=5;since=s.getTickCount();return;}
  if(stage==5&&fuse(bomb)>0){save(s,"armed",bomb.observation());bomb.setPos(origin.add(-8,0,0));stage=6;since=s.getTickCount();return;}
  if(stage==6&&elapsed>bomb.definition().proximityCooldown()+50){require(!bomb.isRemoved()&&fuse(bomb)==0,"EVENTS_FUSE_NOT_CANCELLED");bomb.setPos(origin.add(-2,0,0));target=new net.minecraft.world.entity.monster.zombie.Zombie(EntityType.ZOMBIE,p.level());target.setNoAi(true);target.setPos(bomb.position().add(0,0,1.1));target.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.IRON_HELMET));p.level().addFreshEntity(target);health=target.getHealth();block=bomb.blockPosition().below();require(p.level().getBlockState(block).is(net.minecraft.world.level.block.Blocks.STONE),"EVENTS_TEST_FLOOR");stage=7;since=s.getTickCount();return;}
  if(stage==7&&bomb.isRemoved()){require(target.getHealth()<health,"EVENTS_EXPLOSION_DAMAGE_MISSING");require(p.level().getBlockState(block).is(net.minecraft.world.level.block.Blocks.STONE),"EVENTS_EXPLOSION_BROKE_BLOCKS");save(s,"result",Map.of("status","REAL_NATIVE_PROXIMITY_ACTIONS_VERIFIED","savedRealArtifact",saved(),"helper",helper.observation(),"apples",apples(p),"fuseCancelledOnExit",true,"explosionVictimHealthBefore",health,"explosionVictimHealthAfter",target.getHealth(),"floorPreserved",true));complete=true;stage=8;}
 }catch(Exception e){failure=e.toString();try{save(s,"failure",Map.of("stage",stage,"error",failure,"helper",helper==null?Map.of():helper.observation(),"bomb",bomb==null?Map.of():bomb.observation()));}catch(Exception ignored){}}}
}
