package dev.mineagent.runtime.neoforge.ui;

import com.fasterxml.jackson.databind.*;
import dev.mineagent.runtime.api.packages.*;
import dev.mineagent.runtime.api.permission.PermissionAction;
import dev.mineagent.runtime.core.task.TaskStepSpec;
import dev.mineagent.runtime.neoforge.*;
import dev.mineagent.runtime.neoforge.network.UiPayloads;
import dev.mineagent.runtime.worker.generation.*;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.tick.ServerTickEvent;
import net.neoforged.neoforge.network.PacketDistributor;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.util.*;

/** Explicit two-client delivery fixture. Only the normal package/audience/delivery APIs perform effects. */
@EventBusSubscriber(modid="mineagent_runtime")
public final class DeliverySmokeServer {
    private static final String RUN=UUID.randomUUID().toString();private static final ObjectMapper JSON=new ObjectMapper();private static UUID agent,task,batch,secondBatch;
    private static final Map<String,UUID> players=new LinkedHashMap<>(),deliveries=new LinkedHashMap<>(),rejects=new LinkedHashMap<>();private static final Set<String> ready=new HashSet<>(),updated=new HashSet<>(),done=new HashSet<>(),goalDrafts=new HashSet<>();private static int phase,ticks,after;private static boolean failed;
    private static String role(ServerPlayer p){return p.nameAndId().name().equals("DeliveryA")?"A":p.nameAndId().name().equals("DeliveryB")?"B":"";}
    public static boolean enabled(){return Boolean.getBoolean("mineagent.deliverySmokeServer");}
    public static boolean feedbackMode(){return Boolean.getBoolean("mineagent.feedbackSmoke");}
    public static boolean dataMode(){return Boolean.getBoolean("mineagent.feedbackData");}
    private static RuntimeDefinition dataDefinition;private static UUID dataInstance;
    public static boolean wakeMode(){return Boolean.getBoolean("mineagent.feedbackWakeSmoke");}
    public static boolean cancelWake(){return Boolean.getBoolean("mineagent.feedbackWakeCancel");}
    private static dev.mineagent.runtime.worker.smoke.FeedbackControlledProvider provider;private static int wakeAfter;private static UUID wakeSubscription;private static boolean idleVerified,replySeen;
    private static List<dev.mineagent.runtime.core.feedback.UiFeedbackStore.Item> feedbackRows(MinecraftServer s)throws Exception{return ServerUiRuntime.get(s).deliveries().feedback().store().rows();}
    private static Path root(MinecraftServer s){return s.getServerDirectory().resolve("delivery-evidence").resolve(RUN);}
    private static void write(MinecraftServer s,String name,Object value)throws Exception{Files.createDirectories(root(s));Files.writeString(root(s).resolve(name),JSON.writeValueAsString(value));}
    private static Map<String,String> execute(MinecraftServer s,String name,Object arguments)throws Exception{return ServerUiRuntime.get(s).deliveries().execute(MineAgentRuntimeServices.tasks(s).get(task).orElseThrow(),UUID.randomUUID(),name,JSON.writeValueAsString(arguments));}
    private static JsonNode rows(MinecraftServer s,UUID id)throws Exception{return JSON.readTree(execute(s,"query_deliveries",Map.of("batch_id",id)).get("result")).path("deliveries");}
    private static JsonNode row(MinecraftServer s,String who)throws Exception{for(var r:rows(s,batch))if(r.path("recipient").asText().equals(players.get(who).toString()))return r;throw new IllegalStateException("DELIVERY_FIXTURE_ROW");}
    private static void require(boolean b,String error){if(!b)throw new IllegalStateException(error);}
    public static final String PAGE="""
        <!doctype html><html lang="zh-CN"><meta charset="utf-8"><title>独立投递页面</title>
        <style>body{font:16px/1.6 'Microsoft YaHei',sans-serif;padding:22px;background:#1b241f;color:#eef4eb}h1{font-size:25px}input{font:inherit;padding:12px;width:80%;border-radius:9px;border:1px solid #829382;background:#18271e;color:inherit}#value{padding:16px;border:1px solid #829382;border-radius:12px}#proof{font-size:9px}</style>
        <h1>签名内容 · 独立接收</h1><p id="value">等待投递数据…</p><p id="revision"></p><label for="draft">人工草稿（数据更新不得覆盖）</label><input id="draft" value="尚未编辑"><pre id="proof"></pre>
        <script>let state=null;function show(next){state=next;document.querySelector('#value').textContent=state.data.text;document.querySelector('#revision').textContent='数据版本 '+state.revision;}async function start(){try{show(await mineagentDelivery.read());}catch(e){document.querySelector('#value').textContent=e.message;}}if(window.mineagentDelivery)start();else addEventListener('mineagent:delivery-ready',start,{once:true});addEventListener('mineagent:delivery-data',e=>show(e.detail));window.deliveryProbe=()=>document.querySelector('#proof').textContent='DELIVERY_PROOF:'+JSON.stringify({state,draft:document.querySelector('#draft').value});</script></html>
        """;
    private static final String DATA_SCRIPT="""
        on('instance.create',function(){
          content.sharedDefine('state','schema',0,JSON.stringify({version:1,fields:{count:{type:'INTEGER',scope:'SHARED',minimum:0,maximum:1},entry:{type:'STRING'},ownerSecret:{type:'STRING',scope:'SHARED',read:'OWNER',write:'OWNER'}}}));
          content.sharedTransact('state','initial',JSON.stringify({schema_version:1,conditions:[],writes:[{key:'count',op:'PUT',value:0},{key:'ownerSecret',op:'PUT',value:'OWNER_FEEDBACK_NOT_VISIBLE'}]}));
          content.placeBlock('marker',0,0,0,'minecraft:stone');
        });
        on('instance.restore',function(){content.placeBlock('marker',0,0,0,'minecraft:stone');content.sharedRead('state');});
        on('feedback.plan',function(e){
          var input=JSON.parse(String(e.payload())),snapshot=JSON.parse(String(e.snapshot()));
          if(snapshot.values.ownerSecret!==undefined)throw new Error('FEEDBACK_OWNER_FIELD_LEAK');
          var denied=false;try{content.state('owner-private');}catch(error){denied=true;}if(!denied)throw new Error('FEEDBACK_PLAN_BORROWED_OWNER_STATE');
          e.plan(JSON.stringify({transaction:{schema_version:1,conditions:[{key:'count',test:'LT',value:1},{key:'entry',test:'ABSENT'}],writes:[{key:'count',op:'ADD',value:1},{key:'entry',op:'PUT_IF_ABSENT',value:input.question}]}}));
        });
        """;
    private static String feedbackPage(){String page=PAGE.replace("<pre id=\"proof\"></pre>","<form id=\"feedback-form\"><label for=\"question\">向该 Agent 记录问题（不调用模型）</label><input id=\"question\"><input type=\"hidden\" id=\"not-sent\" value=\"FEEDBACK_HIDDEN_NOT_SENT\"><button id=\"feedback-submit\">提交反馈</button></form><p id=\"feedback-status\">尚未提交反馈</p><p id=\"feedback-answer\"></p><pre id=\"proof\"></pre>").replace("</html>", """
        <script>let feedbackRecord=null,feedbackOperation=null,feedbackAttempts=0,feedbackError='',feedbackPending=false,feedbackReply='',feedbackShared=null,feedbackBusiness='';addEventListener('mineagent:feedback-data',async e=>{if(e.detail.result?.receipt){try{feedbackBusiness=e.detail.result.receipt.status;feedbackShared=await mineagentFeedback.readShared(e.detail.feedbackId);document.querySelector('#feedback-answer').textContent='事务 '+feedbackBusiness+' · count='+feedbackShared.values.count+' · 我的记录='+(feedbackShared.values.entry||'未写入');}catch(error){feedbackError=error.message;}}});addEventListener('mineagent:feedback-data',e=>{if(e.detail.result?.reply){feedbackReply=e.detail.result.reply;document.querySelector('#feedback-answer').textContent=feedbackReply;}});
        document.querySelector('#feedback-form').addEventListener('submit',async e=>{e.preventDefault();if(feedbackPending)return;feedbackPending=true;feedbackAttempts++;feedbackOperation??=crypto.randomUUID();try{feedbackRecord=await mineagentFeedback.submit('help',{question:document.querySelector('#question').value},feedbackOperation);document.querySelector('#feedback-status').textContent='反馈 '+feedbackRecord.state+' · '+feedbackRecord.feedbackId;}catch(error){feedbackError=error.message;document.querySelector('#feedback-status').textContent=feedbackError;}finally{feedbackPending=false;}});
        window.deliveryProbe=()=>document.querySelector('#proof').textContent='DELIVERY_PROOF:'+JSON.stringify({state,draft:document.querySelector('#draft').value,feedback:feedbackRecord,feedbackOperation,feedbackAttempts,feedbackError,feedbackPending,feedbackReply,feedbackShared,feedbackBusiness});</script></html>
        """);return dataMode()?page.replace("记录问题（不调用模型）","提交共享事务（无模型）"):wakeMode()?page.replace("不调用模型","已授权AI回复"):page;}
    private static List<GeneratedFile> files(byte[] page)throws Exception{
        var files=new ArrayList<GeneratedFile>();files.add(new GeneratedFile("ui/index.html",RuntimeResourceSide.CLIENT,"text/html",dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer.sha256(page),page));
        if(feedbackMode())for(var entry:Map.of("ui/feedback.json","{\"schema\":1,\"entries\":{\"ui/index.html\":{\"events\":{\"help\":{\"mode\":\"RECORD_ONLY\",\"lifecycle\":\"INDEPENDENT\",\"max_events\":8,\"cooldown_ms\":1000,\"fields\":{\"question\":{\"type\":\"string\",\"max_length\":100}},\"required\":[\"question\"]}}}}}","ui/view-settings.json","{\"schema\":1,\"entries\":{\"ui/index.html\":{\"anchor\":\"TOP_RIGHT\",\"width\":600,\"height\":540,\"offsetX\":-12,\"offsetY\":0}}}").entrySet()){byte[] bytes=(dataMode()?entry.getValue().replace("RECORD_ONLY","DETERMINISTIC"):wakeMode()?entry.getValue().replace("RECORD_ONLY","AGENT_WAKE"):entry.getValue()).getBytes(StandardCharsets.UTF_8);files.add(new GeneratedFile(entry.getKey(),RuntimeResourceSide.CLIENT,"application/json",dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer.sha256(bytes),bytes));}
        if(dataMode()){String source=DATA_SCRIPT;if(FeedbackRestartSmokeServer.enabled())source=source.replace("on('instance.create',function(){","on('instance.create',function(){feedbackTrace.record('create',String(instance.instanceId()));").replace("on('instance.restore',function(){","on('instance.restore',function(){feedbackTrace.record('restore',String(instance.instanceId()));").replace("on('feedback.plan',function(e){","on('feedback.plan',function(e){feedbackTrace.record('plan',String(e.feedbackId()));");byte[] script=source.getBytes(StandardCharsets.UTF_8);files.add(new GeneratedFile("server/main.js",RuntimeResourceSide.SERVER,"application/javascript",dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer.sha256(script),script));dataDefinition=new RuntimeDefinition(UUID.randomUUID(),"Feedback data instance",RuntimeDefinitionKind.ENTITY,"server",Set.of(),Map.of(),1);}
        return files;
    }
    @SubscribeEvent public static void tick(ServerTickEvent.Post event)throws Exception{
        if(!enabled()||failed)return;var s=event.getServer();if(ClientCodeDeliverySmokeServer.enabled()){ClientCodeDeliverySmokeServer.tick(s);return;}ticks++;if(GenerationRepairSmokeServer.enabled()){GenerationRepairSmokeServer.tick(s);return;}WorkerHealthSmokeServer.tick(s);if(FeedbackApplicationSmokeServer.enabled()){FeedbackApplicationSmokeServer.tick(s);return;}if(FeedbackRestartSmokeServer.resume()){FeedbackRestartSmokeServer.tick(s);return;}try{
            for(var p:s.getPlayerList().getPlayers())if(!role(p).isEmpty())players.put(role(p),p.getUUID());
            if(phase==0&&players.size()==2){var owner=s.getPlayerList().getPlayer(players.get("A"));var grants=new HashSet<>(MineAgentRuntimeServices.permissions(s).trustedActions(owner.getUUID()));grants.addAll(Set.of(PermissionAction.MANAGE_PACKAGES,PermissionAction.DISCOVER_OBJECTS,PermissionAction.OFFER_CONTENT));if(feedbackMode())grants.add(PermissionAction.RECEIVE_UI_FEEDBACK);if(wakeMode())grants.add(PermissionAction.SUBSCRIBE_EVENTS);if(dataMode())grants.addAll(Set.of(PermissionAction.RUN_CODE,PermissionAction.ACCESS_SHARED_STATE));var cfg=MineAgentRuntimeServices.config(s);require(cfg.apply(new dev.mineagent.runtime.api.config.ConfigPatch(cfg.snapshot().revision(),Map.of("runtime.initialized","true","voice.output.enabled","false","permission.player."+owner.getUUID(),grants.stream().map(Enum::name).sorted().collect(java.util.stream.Collectors.joining(",")))),true).accepted(),"DELIVERY_FIXTURE_CONFIG");MineAgentRuntimeServices.permissions(s).setTrustedActions(owner.getUUID(),grants);
                if(wakeMode()){provider=new dev.mineagent.runtime.worker.smoke.FeedbackControlledProvider(s.getServerDirectory());require(cfg.apply(new dev.mineagent.runtime.api.config.ConfigPatch(cfg.snapshot().revision(),Map.of("provider.openai.baseUrl",provider.baseUrl(),"provider.openai.model","controlled-feedback-wake","provider.openai.apiKey","fixture-only")),true).accepted(),"FEEDBACK_WAKE_CONFIG");}

                agent=MineAgentRuntimeServices.bodies(s).createPersistentAt("Delivery test Actor",owner.getUUID(),s.overworld(),owner.position().add(2,0,0)).agentId();task=MineAgentRuntimeServices.tasks(s).create(agent,owner.getUUID(),"Explicit delivery integration fixture",1,List.of(new TaskStepSpec("execute",Set.of()))).taskId();byte[] page=(feedbackMode()?feedbackPage():PAGE).getBytes(StandardCharsets.UTF_8);var files=files(page);var file=files.getFirst();var entries=new LinkedHashMap<String,RuntimeEntrypoint>();entries.put("ui",new RuntimeEntrypoint(file.path(),file.side(),file.sha256()));if(dataMode()){var script=files.stream().filter(f->f.path().equals("server/main.js")).findFirst().orElseThrow();var entry=new RuntimeEntrypoint(script.path(),script.side(),script.sha256());entries.put("server",entry);entries.put("server.restore",entry);}
                var pkg=ServerPackageRuntime.get(s).importOwned(owner,UUID.randomUUID(),new ParsedRuntimePackage("独立投递 · 本地验收包","1",RuntimePackageType.CONTENT,ActivationMode.HOT_RUNTIME,Map.of(),dataMode()?Set.of("RUN_CODE","state.shared"):Set.of(),entries,dataMode()?List.of(dataDefinition):List.of(),files));
                if(dataMode()){var activation=dev.mineagent.runtime.neoforge.content.WorldContentRuntime.get(s).activate(owner,UUID.randomUUID(),pkg.packageId(),pkg.revision(),dataDefinition.definitionId(),new RuntimeInstanceLocation("minecraft:overworld",owner.getX()+8,owner.getY(),owner.getZ()+8,0,0),true,FeedbackRestartSmokeServer.enabled());require(activation.state().equals("ACTIVE"),"FEEDBACK_DATA_ACTIVATION");dataInstance=activation.instanceId();pkg=ServerPackageRuntime.get(s).worldLibrary().get(pkg.packageId()).orElseThrow();write(s,"feedback-data-instance.json",Map.of("activation",activation,"package",pkg));}
                var contractArgs=Map.<String,Object>of("package_id",pkg.packageId(),"package_revision",pkg.revision(),"canonical_sha256",pkg.canonicalSha256(),"entry_id","ui");
                var contract=execute(s,"inspect_content_contract",contractArgs);var description=JSON.readTree(contract.get("result"));require(description.path("entryPath").asText().equals("ui/index.html")&&!description.path("grantsAuthority").asBoolean(),"CONTENT_CONTRACT_NATIVE_SCOPE");if(feedbackMode())require(description.path("feedbackDeclared").asBoolean()&&description.path("events").has("help")&&description.path("feedbackPolicySha256").asText().equals(pkg.resources().get("ui/feedback.json").sha256()),"CONTENT_CONTRACT_FEEDBACK_SCHEMA");write(s,"content-contract.json",contract);
                var deniedArgs=new LinkedHashMap<String,Object>(contractArgs);deniedArgs.put("canonical_sha256","0".repeat(64));boolean denied=false;try{execute(s,"inspect_content_contract",deniedArgs);}catch(SecurityException expected){denied=true;}require(denied,"CONTENT_CONTRACT_STALE_HASH_ACCEPTED");
                deniedArgs=new LinkedHashMap<String,Object>(contractArgs);deniedArgs.put("entry_id","server");denied=false;try{execute(s,"inspect_content_contract",deniedArgs);}catch(IllegalArgumentException expected){denied=true;}require(denied,"CONTENT_CONTRACT_SERVER_SOURCE_EXPOSED");write(s,"content-contract-denials.json",Map.of("staleHash",true,"serverEntry",true));
                var audiences=MineAgentRuntimeServices.taskExecutor(s).worldActions().audiences();var current=MineAgentRuntimeServices.tasks(s).get(task).orElseThrow();var definition=JSON.readTree(audiences.execute(current,UUID.randomUUID(),"create_audience","{\"mode\":\"SNAPSHOT\",\"query\":{\"kind\":\"PLAYER\"}}").get("result"));var snap=JSON.readTree(audiences.execute(current,UUID.randomUUID(),"resolve_audience",JSON.writeValueAsString(Map.of("audience_id",definition.path("audienceId").asText(),"expected_revision",1))).get("result"));
                if(wakeMode()){
                    var filter=new dev.mineagent.runtime.core.feedback.FeedbackSubscriptionFilter(pkg.packageId(),pkg.revision(),pkg.canonicalSha256(),"ui/index.html",pkg.resources().get("ui/feedback.json").sha256(),Set.of("help"),0);var subscriptionArgs=new LinkedHashMap<String,Object>(filter.wire());subscriptionArgs.put("mode","AGENT_WAKE");subscriptionArgs.put("goal","FEEDBACK_WAKE_GOAL：解释收到的教学问题，只回复真实反馈作者，不操作世界或授权卡。");subscriptionArgs.put("max_wakes",4);subscriptionArgs.put("max_model_calls",3);subscriptionArgs.put("pending_limit",4);subscriptionArgs.put("cooldown_ms",0);subscriptionArgs.put("ttl_seconds",600);var subscription=MineAgentRuntimeServices.events(s).execute(current,UUID.randomUUID(),"subscribe_ui_feedback",JSON.writeValueAsString(subscriptionArgs));write(s,"feedback-subscription.json",subscription);wakeSubscription=UUID.fromString(JSON.readTree(subscription.get("result")).path("id").asText());
                }
                var args=new LinkedHashMap<String,Object>();args.put("package_id",pkg.packageId());args.put("package_revision",pkg.revision());args.put("canonical_sha256",pkg.canonicalSha256());args.put("entry_id","ui");args.put("audience_snapshot_id",snap.path("snapshotId").asText());args.put("data",Map.of("text","INITIAL_DELIVERY"));args.put("ttl_seconds",600);args.put("feedback_enabled",feedbackMode());if(dataMode())args.put("feedback_binding",new dev.mineagent.runtime.core.feedback.FeedbackDataBinding(dataInstance,"state",1,Set.of("count","entry"),Set.of("count","entry")).wire());batch=UUID.fromString(JSON.readTree(execute(s,"offer_content",args).get("result")).path("id").asText());args.put("data",Map.of("text","SECOND_OFFER_NOT_OPENED"));args.put("feedback_enabled",false);args.remove("feedback_binding");secondBatch=UUID.fromString(JSON.readTree(execute(s,"offer_content",args).get("result")).path("id").asText());
                for(String who:List.of("A","B")){for(var r:rows(s,batch))if(r.path("recipient").asText().equals(players.get(who).toString()))deliveries.put(who,UUID.fromString(r.path("deliveryId").asText()));for(var r:rows(s,secondBatch))if(r.path("recipient").asText().equals(players.get(who).toString()))rejects.put(who,UUID.fromString(r.path("deliveryId").asText()));}
                write(s,"fixture.json",Map.of("run",RUN,"players",players,"agent",agent,"task",task,"batch",batch,"secondBatch",secondBatch,"deliveries",deliveries,"package",pkg,"source","EXPLICIT_IMPORT_NOT_MODEL_GENERATED"));phase=1;wakeAfter=ticks+60;
            }
            if(FeedbackRestartSmokeServer.prepareTick(s))return;
            if(phase>0&&WorldRuleSmokeServer.enabled()&&!WorldRuleSmokeServer.finished){var ruleOwner=s.getPlayerList().getPlayer(players.get("A"));if(ruleOwner!=null)WorldRuleSmokeServer.tick(s,ruleOwner);}
            if(phase==1&&DeliveryGoalSmokeServer.enabled())task=DeliveryGoalSmokeServer.tickOrigin(s,task,agent,batch,secondBatch,players.get("A"),goalDrafts.size()==2);
            if(wakeMode()&&!idleVerified&&phase==1&&ticks>=wakeAfter){require(provider.calls()==0,"FEEDBACK_IDLE_MODEL_CALL");idleVerified=true;write(s,"feedback-idle.json",Map.of("calls",0,"ticks",60));}
            if(phase==1&&ready.size()==2&&(!cancelWake()||provider.calls()==2)){require(row(s,"A").path("status").asText().equals(feedbackMode()?"INTERACTED":"RENDERED")&&row(s,"B").path("status").asText().equals(feedbackMode()?"INTERACTED":"RENDERED"),"DELIVERY_ACTUAL_PAINT_REQUIRED");if(feedbackMode()){var f=feedbackRows(s);require(f.size()==2&&f.stream().allMatch(i->dataMode()?Set.of("COMPLETED","REJECTED").contains(i.state()):i.state().equals(wakeMode()?"PROCESSING":"RECORDED"))&&f.stream().map(i->i.scope().conversationId()).distinct().count()==2,"FEEDBACK_NATIVE_RECORDS");write(s,"feedback-recorded.json",f);if(dataMode()){require(f.stream().filter(i->i.state().equals("COMPLETED")).count()==1&&f.stream().filter(i->i.state().equals("REJECTED")).count()==1,"FEEDBACK_DATA_ATOMIC_LIMIT");write(s,"feedback-data-results.json",f);}}if(cancelWake()){MineAgentRuntimeServices.events(s).execute(MineAgentRuntimeServices.tasks(s).get(task).orElseThrow(),UUID.randomUUID(),"set_subscription_state",JSON.writeValueAsString(Map.of("subscription_id",wakeSubscription,"expected_revision",1,"state","CANCELLED")));provider.releaseReplies();phase=70;after=ticks+100;write(s,"feedback-cancel-start.json",Map.of("calls",provider.calls(),"tick",ticks));}else{if(!DeliveryGoalSmokeServer.enabled())execute(s,"update_view",Map.of("delivery_id",deliveries.get("A"),"expected_data_revision",1,"data",Map.of("text","ONLY_A_UPDATED")));phase=2;write(s,"updated.json",rows(s,batch));}}
            if(phase==70&&ticks>=after){provider.verifyCancelled();var feedback=feedbackRows(s);require(feedback.size()==2&&feedback.stream().allMatch(i->i.state().equals("CANCELLED")&&i.reply()==null&&i.completion()==null&&MineAgentRuntimeServices.tasks(s).get(i.consumerOperationId()).orElseThrow().status()==dev.mineagent.runtime.api.task.TaskStatus.PAUSED),"FEEDBACK_LATE_REPLY_NOT_CANCELLED");write(s,"feedback-cancel-verification.json",Map.of("items",feedback,"calls",provider.calls(),"ticksAfterCancel",100));execute(s,"close_view",Map.of("delivery_id",deliveries.get("A")));execute(s,"close_view",Map.of("delivery_id",deliveries.get("B")));phase=71;}
            if(phase==71&&done.size()==2){provider.verifyCancelled();write(s,"feedback-wake-cancel-result.json",Map.of("status","IN_FLIGHT_AND_QUEUED_FEEDBACK_CANCELLED","items",feedbackRows(s),"providerCalls",provider.calls(),"paidCalls",0,"fullV1",false));MineAgentRuntimeMod.LOGGER.info("MINEAGENT_DELIVERY_SERVER_OK run={}",RUN);phase=6;after=ticks+80;}
            if(phase==2&&updated.size()==2){execute(s,"close_view",Map.of("delivery_id",deliveries.get("A")));phase=3;}
            if(phase==3&&row(s,"A").path("closeConfirmed").asBoolean()){require(row(s,"A").path("status").asText().equals("CLOSED"),"DELIVERY_CLOSE_NOT_ACKED");execute(s,"update_view",Map.of("delivery_id",deliveries.get("A"),"expected_data_revision",2,"data",Map.of("text","CLOSED_MUST_NOT_REOPEN")));if(wakeMode()){write(s,"feedback-replies-released.json",Map.of("sourceAClosed",true,"tick",ticks,"calls",provider.calls()));provider.releaseReplies();}after=ticks+80;phase=4;}
            if(phase==4&&ticks>=after&&(!wakeMode()||replySeen&&feedbackRows(s).stream().allMatch(i->i.state().equals("COMPLETED")&&i.consumerOperationId()!=null&&MineAgentRuntimeServices.tasks(s).get(i.consumerOperationId()).orElseThrow().status()==dev.mineagent.runtime.api.task.TaskStatus.COMPLETED))){require(row(s,"A").path("status").asText().equals("CLOSED")&&row(s,"A").path("dataRevision").asInt()==3,"DELIVERY_CLOSED_UPDATE_REOPENED");execute(s,"revoke_content",Map.of("delivery_id",deliveries.get("B")));phase=5;}
            if(phase==5&&done.size()==2){var a=row(s,"A");var b=row(s,"B");require(a.path("closeConfirmed").asBoolean()&&a.path("status").asText().equals("CLOSED")&&b.path("closeConfirmed").asBoolean()&&b.path("status").asText().equals("REVOKED"),"DELIVERY_FINAL_STATES");write(s,"result.json",Map.of("status","TWO_REAL_CLIENT_DELIVERY_LIFECYCLE_VERIFIED","main",rows(s,batch),"secondary",rows(s,secondBatch),"players",players,"providerCalls",0,"systemInputInjected",false,"fullV1",false));if(feedbackMode()){var feedback=feedbackRows(s);require(feedback.size()==2&&feedback.stream().allMatch(i->dataMode()?Set.of("COMPLETED","REJECTED").contains(i.state()):i.state().equals(wakeMode()?"COMPLETED":"RECORDED")),"FEEDBACK_REPLAY_DUPLICATED");if(wakeMode()){provider.verify();write(s,"feedback-wake-result.json",Map.of("status","TWO_CLIENT_BOUND_FEEDBACK_REPLY_VERIFIED","items",feedback,"providerCalls",provider.calls(),"paidCalls",0,"fullV1",false));}write(s,"feedback-result.json",Map.of("status",dataMode()?"TWO_CLIENT_FEEDBACK_SHARED_TRANSACTION_VERIFIED":wakeMode()?"TWO_CLIENT_FEEDBACK_REPLIED":"TWO_CLIENT_FEEDBACK_INGRESS_RECORDED","items",feedback,"providerCalls",wakeMode()?provider.calls():0,"fullV1",false));}if(feedbackMode()){var permissions=MineAgentRuntimeServices.permissions(s);var original=permissions.trustedActions(players.get("A"));var reduced=new HashSet<>(original);reduced.remove(PermissionAction.RECEIVE_UI_FEEDBACK);permissions.setTrustedActions(players.get("A"),reduced);permissions.setTrustedActions(players.get("A"),original);phase=50;after=ticks+40;}else{MineAgentRuntimeMod.LOGGER.info("MINEAGENT_DELIVERY_SERVER_OK run={}",RUN);phase=6;after=ticks+80;}}
            if(phase==50&&ticks>=after&&(!WorldRuleSmokeServer.enabled()||WorldRuleSmokeServer.finished)){var secondary=rows(s,secondBatch);if(!DeliveryGoalSmokeServer.finishFollowup(s,task,batch,secondBatch,players.get("A"),players.get("B")))return;for(var row:secondary)if(row.path("recipient").asText().equals(players.get("A").toString()))require(row.path("status").asText().equals("OFFERED"),"FEEDBACK_EPOCH_REVOKED_READONLY_OFFER");write(s,"feedback-epoch-isolation.json",Map.of("status","READONLY_OFFER_SURVIVED_FEEDBACK_REVOKE_REGRANT","secondary",secondary));if(DeliveryGoalSmokeServer.enabled())task=DeliveryGoalSmokeServer.resourceProbe(s,batch,players.get("A"),agent);MineAgentRuntimeMod.LOGGER.info("MINEAGENT_DELIVERY_SERVER_OK run={}",RUN);phase=6;after=ticks+80;}
            if(phase==6&&ticks>=after){DeliveryGoalSmokeServer.closeProbe(s);if(provider!=null){provider.close();provider=null;}s.halt(false);}if(ticks>14000)throw new IllegalStateException("DELIVERY_FIXTURE_TIMEOUT_"+phase);
        }catch(Exception e){failed=true;write(s,"failure.json",Map.of("phase",phase,"error",e.toString()));s.halt(false);throw e;}
    }
    public static void handle(ServerPlayer p,UiPayloads.Command packet)throws Exception{if(!enabled()||role(p).isEmpty())throw new SecurityException("DELIVERY_FIXTURE_SOURCE");var s=p.level().getServer();if(ClientCodeDeliverySmokeServer.enabled()){ClientCodeDeliverySmokeServer.handle(p,packet);return;}if(GenerationRepairSmokeServer.enabled()){GenerationRepairSmokeServer.handle(p,packet);return;}if(FeedbackApplicationSmokeServer.enabled()){FeedbackApplicationSmokeServer.handle(p,packet);return;}if(FeedbackRestartSmokeServer.resume()){FeedbackRestartSmokeServer.handle(p,packet);return;}try{var args=JSON.readTree(packet.json());String action=args.path("action").asText();if(!args.isObject()||args.size()!=1||!Set.of("info","ready","updated","done","reply-seen","draft-ready").contains(action))throw new IllegalArgumentException("DELIVERY_FIXTURE_ACTION");String who=role(p);if(action.equals("draft-ready")){if(!DeliveryGoalSmokeServer.enabled())throw new IllegalArgumentException("GOAL_FIXTURE_DISABLED");goalDrafts.add(who);}if(action.equals("ready"))ready.add(who);if(action.equals("updated"))updated.add(who);if(action.equals("done"))done.add(who);if(action.equals("reply-seen")&&who.equals("B"))replySeen=true;var result=new LinkedHashMap<String,Object>();result.put("run",RUN);result.put("ready",phase>0);result.put("phase",phase);result.put("originFinished",DeliveryGoalSmokeServer.originFinished());result.put("wakeReady",!wakeMode()||idleVerified);if(phase>0){result.put("own",row(s,who));result.put("otherDelivery",deliveries.get(who.equals("A")?"B":"A"));result.put("rejectId",rejects.get(who));if(feedbackMode()){for(var f:feedbackRows(s)){if(f.scope().authorId().equals(p.getUUID()))result.put("feedback",Map.of("feedbackId",f.id(),"state",f.state(),"conversationId",f.scope().conversationId()));else result.put("otherFeedbackId",f.id());}}}PacketDistributor.sendToPlayer(p,new UiPayloads.Event(packet.requestId(),"deliveryFixture",JSON.writeValueAsString(result)));}catch(Exception e){write(s,"coordination-failure.json",Map.of("error",e.toString()));s.halt(false);throw e;}}
}
