package dev.mineagent.runtime.neoforge.ui;
import com.fasterxml.jackson.databind.*;import dev.mineagent.runtime.neoforge.mixin.EntityGoalsAccess;import dev.mineagent.runtime.neoforge.integration.TwilightNagaInterop;
import net.minecraft.server.level.ServerPlayer;import net.minecraft.server.permissions.Permissions;import net.minecraft.world.entity.*;import net.minecraft.world.entity.ai.attributes.*;import net.minecraft.world.entity.animal.Animal;
import net.minecraft.world.item.*;import net.minecraft.core.registries.BuiltInRegistries;import net.minecraft.resources.Identifier;import java.util.*;
public final class EntityLogicTools {
 private static final ObjectMapper JSON=new ObjectMapper();
 public static Map<String,Object> inspect(ServerPlayer p,JsonNode args){
  if(!args.has("entity_id")){int offset=args.path("offset").asInt(0);if(offset<0)throw new IllegalArgumentException("ENTITY_OFFSET");var all=new ArrayList<Entity>();for(var e:p.level().getAllEntities())if(!(e instanceof net.minecraft.world.entity.player.Player)&&e.isAlive()&&(args.path("query").asText().isEmpty()||e.getName().getString().toLowerCase(Locale.ROOT).contains(args.path("query").asText().toLowerCase(Locale.ROOT))||BuiltInRegistries.ENTITY_TYPE.getKey(e.getType()).toString().contains(args.path("query").asText())))all.add(e);all.sort(Comparator.comparingDouble(p::distanceToSqr));return Map.of("entities",all.stream().skip(offset).limit(24).map(EntityLogicTools::brief).toList(),"nextOffset",offset+24<all.size()?offset+24:-1,"scope","CURRENT_DIMENSION_LOADED","contract",ServerEntityInterop.CONTRACT);}
  Entity e=ServerEntityInterop.target(p,args.path("entity_id").asText());var out=new LinkedHashMap<String,Object>(brief(e));out.put("contract",ServerEntityInterop.CONTRACT);out.put("adapter",TwilightNagaInterop.inspect(e));out.put("class",e.getClass().getName());
  if(e instanceof Mob mob){out.put("noAI",mob.isNoAi());out.put("target",mob.getTarget()==null?"":mob.getTarget().getUUID());out.put("goals",goals(((EntityGoalsAccess)mob).mineagent$goals()));out.put("targetGoals",goals(((EntityGoalsAccess)mob).mineagent$targets()));out.put("brainBehaviors",mob.getBrain().getRunningBehaviors().stream().map(v->v.getClass().getName()).toList());out.put("logicScope","Observed runtime goals/brain behaviours and native event adapters, not a decompiled copy of private Mod Java logic.");}
  if(e instanceof LivingEntity living){var attributes=new ArrayList<Object>();for(var attribute:BuiltInRegistries.ATTRIBUTE.listElements().toList()){var instance=living.getAttribute(attribute);if(instance!=null)attributes.add(Map.of("id",attribute.key().identifier().toString(),"base",instance.getBaseValue(),"effective",instance.getValue()));}out.put("attributes",attributes);out.put("health",living.getHealth());out.put("maxHealth",living.getMaxHealth());}
  var parts=new ArrayList<Object>();var children=e.getParts();if(children!=null)for(int i=0;i<children.length;i++){var part=children[i];var row=new LinkedHashMap<String,Object>(brief(part));row.put("part_index",i);row.put("parent",e.getUUID());row.put("invisible",part.isInvisible());parts.add(row);}out.put("parts",parts);out.put("canEdit",p.permissions().hasPermission(Permissions.COMMANDS_GAMEMASTER)&&!(e instanceof net.minecraft.world.entity.player.Player));out.put("reuse",Map.of("templateTool","derive_creature_template","nativeVisualReference",BuiltInRegistries.ENTITY_TYPE.getKey(e.getType()).toString(),"doesNotCopyPrivateJava",true));return out;
 }
 private static List<Object> goals(net.minecraft.world.entity.ai.goal.GoalSelector selector){return selector.getAvailableGoals().stream().sorted(Comparator.comparingInt(net.minecraft.world.entity.ai.goal.WrappedGoal::getPriority)).map(g->(Object)Map.of("goalClass",g.getGoal().getClass().getName(),"priority",g.getPriority(),"running",g.isRunning(),"flags",g.getFlags().stream().map(Enum::name).toList())).toList();}
 private static Map<String,Object> brief(Entity e){return Map.of("entity_id",e.getUUID(),"type",BuiltInRegistries.ENTITY_TYPE.getKey(ServerEntityInterop.root(e).getType()).toString(),"name",e.getName().getString(),"position",List.of(e.getX(),e.getY(),e.getZ()),"velocity",List.of(e.getDeltaMovement().x,e.getDeltaMovement().y,e.getDeltaMovement().z),"yaw",e.getYRot(),"pitch",e.getXRot(),"size",List.of(e.getBbWidth(),e.getBbHeight()));}
 public static Map<String,Object> state(ServerPlayer p,JsonNode a){if(!p.permissions().hasPermission(Permissions.COMMANDS_GAMEMASTER))throw new SecurityException("ENTITY_GAMEMASTER_REQUIRED");Entity e=ServerEntityInterop.target(p,a.path("entity_id").asText());if(e instanceof net.minecraft.world.entity.player.Player)throw new SecurityException("ENTITY_PLAYER_RULE_UNSUPPORTED");
  if(a.has("no_ai")&&(!(e instanceof Mob)||!a.get("no_ai").isBoolean()))throw new IllegalArgumentException("ENTITY_NO_AI");if(a.has("native_action")&&(!TwilightNagaInterop.supports(e)||!Set.of("naga.daze","naga.circle","naga.crumble").contains(a.get("native_action").asText())))throw new IllegalArgumentException("NAGA_ADAPTER_ACTION");
  if(a.has("attributes")){if(!(e instanceof LivingEntity living)||!a.get("attributes").isObject())throw new IllegalArgumentException("ENTITY_ATTRIBUTES");var patches=new LinkedHashMap<AttributeInstance,Double>();for(var field:a.get("attributes").properties()){var id=Identifier.tryParse(field.getKey());if(id==null||!BuiltInRegistries.ATTRIBUTE.containsKey(id)||!field.getValue().isNumber()||!Double.isFinite(field.getValue().asDouble()))throw new IllegalArgumentException("ENTITY_ATTRIBUTE_INVALID");var holder=BuiltInRegistries.ATTRIBUTE.wrapAsHolder(BuiltInRegistries.ATTRIBUTE.getValue(id));var instance=living.getAttribute(holder);if(instance==null||holder.value().sanitizeValue(field.getValue().asDouble())!=field.getValue().asDouble())throw new IllegalArgumentException("ENTITY_ATTRIBUTE_RANGE");patches.put(instance,field.getValue().asDouble());}patches.forEach(AttributeInstance::setBaseValue);}
  if(a.has("no_ai")){if(!(e instanceof Mob mob)||!a.get("no_ai").isBoolean())throw new IllegalArgumentException("ENTITY_NO_AI");mob.setNoAi(a.get("no_ai").asBoolean());}
  if(a.has("native_action"))try{TwilightNagaInterop.action(e,a.get("native_action").asText());}catch(ReflectiveOperationException ex){return Map.of("status","UNKNOWN","error","NAGA_NATIVE_ACTION_OUTCOME_UNKNOWN","replayAllowed",false);}
  return Map.of("status","APPLIED","entity",inspect(p,JSON.createObjectNode().put("entity_id",e.getUUID().toString())),"persists","Attributes and no_ai follow native entity saving; native action is a live state transition.");
 }
 public static Map<String,Object> template(ServerPlayer p,JsonNode a){Entity e=ServerEntityInterop.target(p,a.path("entity_id").asText());if(!(e instanceof LivingEntity living)||e instanceof net.minecraft.world.entity.player.Player)throw new IllegalArgumentException("ENTITY_TEMPLATE_LIVING_REQUIRED");var source=JSON.createObjectNode();source.put("name",a.path("name").asText("自建"+e.getName().getString()));source.put("native_visual",BuiltInRegistries.ENTITY_TYPE.getKey(e.getType()).toString());source.put("health",Math.min(1024,Math.max(1,living.getMaxHealth())));source.put("speed",Math.min(1,Math.max(.05,living.getAttributes().hasAttribute(Attributes.MOVEMENT_SPEED)?living.getAttributeValue(Attributes.MOVEMENT_SPEED):.25)));source.put("damage",Math.min(100,Math.max(0,living.getAttributes().hasAttribute(Attributes.ATTACK_DAMAGE)?living.getAttributeValue(Attributes.ATTACK_DAMAGE):3)));source.put("disposition",e.getType().getCategory()==MobCategory.MONSTER?"hostile":"friendly");source.put("companion",true);source.put("rideable",e instanceof net.minecraft.world.entity.animal.equine.AbstractHorse);
  if(e instanceof Animal animal)for(String item:List.of("wheat","carrot","wheat_seeds","beetroot","sweet_berries","cod","salmon","bamboo","golden_carrot")){var food=BuiltInRegistries.ITEM.getValue(Identifier.withDefaultNamespace(item));if(animal.isFood(new ItemStack(food))){source.put("food","minecraft:"+item);break;}}
  var dimensions=source.putObject("model");dimensions.put("version",1);var box=dimensions.putArray("boxes").addObject();double w=Math.max(.1,Math.min(4,e.getBbWidth())),h=Math.max(.1,Math.min(6,e.getBbHeight()));box.putArray("from").add(-w/2).add(0).add(-w/2);box.putArray("to").add(w/2).add(h).add(w/2);box.put("color","#72bcd4");dimensions.putArray("collision").add(-w/2).add(0).add(-w/2).add(w/2).add(h).add(w/2);
  return Map.of("source",source.toString(),"observedSource",brief(e),"copied",List.of("native visual reference","health/speed/damage baseline","supported food predicate","disposition","companion/riding flags"),"notCopied",List.of("private Java Goal/Brain state machines","boss progression and loot tables","multipart server hitboxes","third-party constructor state"),"next","Review/modify source, define_creature, control_creature spawn; use set_entity_rule/set_entity_animation on the new entity or species. Naga visual reference currently reuses its head renderer, not a cloned multipart boss.");
 }
 private EntityLogicTools(){}
}
