package dev.mineagent.runtime.neoforge.ui;
import com.fasterxml.jackson.databind.*;import dev.mineagent.runtime.neoforge.network.UiPayloads;import net.minecraft.server.level.ServerPlayer;import java.util.*;import java.util.concurrent.*;
/** Replies must come from the exact client connection asked to observe an actually rendered entity. */
public final class EntityAnimationProbe {
 private static final ObjectMapper JSON=new ObjectMapper();private record Pending(ServerPlayer player,net.minecraft.server.level.ServerLevel level,UUID entity,int part,CompletableFuture<Map<String,Object>> result){}private static final Map<UUID,Pending> PENDING=new ConcurrentHashMap<>();
 public static CompletableFuture<Map<String,Object>> request(ServerPlayer p,JsonNode args){var entity=ServerEntityInterop.target(p,args.path("entity_id").asText());int part=args.path("part_index").asInt(-1),offset=args.path("offset").asInt(0);if(offset<0||part< -1||part>=0&&(entity.getParts()==null||part>=entity.getParts().length))throw new IllegalArgumentException("ENTITY_ANIMATION_TARGET");UUID id=UUID.randomUUID();var result=new CompletableFuture<Map<String,Object>>();var pending=new Pending(p,p.level(),entity.getUUID(),part,result);PENDING.put(id,pending);result.orTimeout(8,TimeUnit.SECONDS).whenComplete((v,e)->PENDING.remove(id,pending));try{net.neoforged.neoforge.network.PacketDistributor.sendToPlayer(p,new UiPayloads.Event(id,"entityAnimationInspect",JSON.writeValueAsString(Map.of("entity",entity.getUUID(),"part",part,"offset",offset))));}catch(Exception e){PENDING.remove(id);result.completeExceptionally(e);}return result.exceptionally(e->Map.of("status","UNAVAILABLE","error","ENTITY_ANIMATION_CLIENT_NOT_OBSERVED","worldModified",false));}
 public static void reply(ServerPlayer p,UiPayloads.Command packet){var pending=PENDING.get(packet.requestId());if(pending==null||pending.player()!=p||pending.level()!=p.level())return;try{var value=JSON.readValue(packet.json(),new com.fasterxml.jackson.core.type.TypeReference<Map<String,Object>>(){});if("OBSERVED_NATIVE_DRAW".equals(value.get("status"))&&(!pending.entity().toString().equals(value.get("entity"))||!Integer.valueOf(pending.part()).equals(value.get("part_index"))))throw new IllegalArgumentException("ENTITY_ANIMATION_REPLY_SCOPE");pending.result().complete(value);}catch(Exception e){pending.result().complete(Map.of("status","UNAVAILABLE","error","ENTITY_ANIMATION_BAD_REPLY"));}PENDING.remove(packet.requestId(),pending);}
 private EntityAnimationProbe(){}
}
