package dev.mineagent.runtime.neoforge.ui;
import com.fasterxml.jackson.databind.*;import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;import dev.mineagent.runtime.neoforge.body.MineAgentPlayer;import net.minecraft.server.MinecraftServer;import net.minecraft.server.level.ServerPlayer;import net.minecraft.core.*;import net.minecraft.world.level.block.*;import net.minecraft.world.phys.Vec3;import java.util.*;import java.util.concurrent.*;import java.nio.file.*;
public final class FeedbackNineSmokeServer {
 public static volatile boolean ready,clientReady,complete,uiReady,uiDone;public static volatile UUID agent,guestAgent,creature,pack,approval;public static volatile String approvalChoice="",failure="";public static volatile int stage,lockStep,lockSent,grants;public static final List<Object> evidence=new ArrayList<>();private static final ObjectMapper JSON=new ObjectMapper();private static CompletableFuture<Map<String,Object>> pending;private static MineAgentPlayer guest;private static int since;private static UUID oldConversation;private static boolean paidStarted;public static volatile boolean entityLocked,entityUnlocked,lockedInputSent,unlockedInputSent;private static UUID entityRule;private static float entityHealth;
 public static boolean active(){return Boolean.getBoolean("mineagent.conversationAgentSmoke")&&Set.of("feedback_nine_zero","feedback_nine").contains(System.getProperty("mineagent.conversationAgentScenario",""));}public static boolean real(){return System.getProperty("mineagent.conversationAgentScenario","").equals("feedback_nine");}
 public static void observe(String tool,JsonNode args,Map<String,Object> receipt){if(active())evidence.add(Map.of("tool",tool,"arguments",args,"receipt",receipt));}
 private static void require(boolean b,String code){if(!b)throw new IllegalStateException(code);}
 private static Path root(MinecraftServer s)throws Exception{return Files.createDirectories(s.getServerDirectory().resolve("nine-feedback-smoke"));}
 private static void save(MinecraftServer s,String name,Object value)throws Exception{Files.writeString(root(s).resolve(name+".json"),JSON.writeValueAsString(value));}
 private static CompletableFuture<Map<String,Object>> call(ServerPlayer p,String tool,JsonNode args){return ConversationAgentTools.execute(p,agent,UUID.randomUUID(),tool,args.toString(),()->true);}
 public static void tick(MinecraftServer s){if(complete||!failure.isEmpty())return;var p=s.getPlayerList().getPlayers().stream().filter(v->!(v instanceof MineAgentPlayer)).findFirst().orElse(null);if(p==null)return;try{
  if(!ready){s.getPlayerList().op(p.nameAndId());p.setGameMode(net.minecraft.world.level.GameType.CREATIVE);for(var pos:BlockPos.betweenClosed(new BlockPos(-12,110,-8),new BlockPos(15,119,10)))p.level().setBlock(pos,pos.getY()==110?Blocks.SMOOTH_STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),2);for(int x=-9;x<=10;x++)for(int y=111;y<=114;y++)for(int z:List.of(-1,1))p.level().setBlock(new BlockPos(x,y,z),Blocks.STONE.defaultBlockState(),2);var door=Blocks.OAK_DOOR.defaultBlockState().setValue(DoorBlock.FACING,Direction.EAST);p.level().setBlock(new BlockPos(0,111,0),door,2);p.level().setBlock(new BlockPos(0,112,0),door.setValue(DoorBlock.HALF,net.minecraft.world.level.block.state.properties.DoubleBlockHalf.UPPER),2);p.level().setBlock(new BlockPos(1,111,0),Blocks.OAK_FENCE_GATE.defaultBlockState().setValue(FenceGateBlock.FACING,Direction.EAST),2);p.level().setBlock(new BlockPos(2,111,0),Blocks.STONE_SLAB.defaultBlockState(),2);p.level().setBlock(new BlockPos(3,111,0),Blocks.RED_CARPET.defaultBlockState(),2);p.level().setBlock(new BlockPos(4,111,0),Blocks.STONE_STAIRS.defaultBlockState().setValue(StairBlock.FACING,Direction.WEST),2);for(int x=5;x<=9;x++)p.level().setBlock(new BlockPos(x,111,0),Blocks.STONE.defaultBlockState(),2);for(int y=112;y<=114;y++)p.level().setBlock(new BlockPos(8,y,0),Blocks.OAK_LOG.defaultBlockState(),2);p.teleportTo(p.level(),-6.5,111,4.5,Set.of(),-90,10,true);agent=MineAgentRuntimeServices.bodies(s).createPersistentAt("改进助手",p.getUUID(),p.level(),new Vec3(-7.5,111,.5)).agentId();guestAgent=MineAgentRuntimeServices.bodies(s).createPersistentAt("原生测试访客",UUID.randomUUID(),p.level(),new Vec3(-9.5,111,7.5)).agentId();guest=MineAgentRuntimeServices.bodies(s).body(guestAgent).orElseThrow();ready=true;return;}
  if(!clientReady)return;if(approval!=null){var field=ServerChatAccess.class.getDeclaredField("PENDING");field.setAccessible(true);var all=(Map<?,?>)field.get(null);var map=(Map<?,?>)all.get(s);if(map==null||!map.containsKey(approval))approval=null;}if(s.getTickCount()%100==0)save(s,"progress",Map.of("stage",stage,"lockStep",lockStep,"evidence",evidence,"body",ConversationBodyTools.execute(p,agent,JSON.createObjectNode(),true)));
  if(real()){realTick(s,p);return;}
  if(pending!=null){if(!pending.isDone())return;var r=pending.join();require(Set.of("APPLIED","OBSERVED","PREVIEW_OPENED").contains(r.get("status")),"NATIVE_TOOL_"+r);pending=null;stage++;}
  switch(stage){
   case 0->{ServerChatSettings.defaultReply(p,agent.toString());var own=MineAgentRuntimeServices.bodies(s).createPersistentAt("访客专属",guest.getUUID(),p.level(),new Vec3(-10.5,111,8.5)).agentId();ServerChatSettings.defaultReply(guest,own.toString());require(ServerChatSettings.defaultAgent(p).equals(agent)&&ServerChatSettings.defaultAgent(guest).equals(own),"DEFAULT_NOT_PLAYER_SCOPED");require(!ServerChatAccess.allowed(guest,agent),"OTHER_CALLER_ALLOWED_BY_DEFAULT");ask(p,"once_allow");stage=1;}
   case 1->{if(approval!=null)return;require(grants==1&&!ServerChatAccess.allowed(guest,agent),"ONCE_ALLOW_PERSISTED");ask(p,"once_deny");stage=2;}
   case 2->{if(approval!=null)return;require(grants==1,"ONCE_DENY_DISPATCHED");ask(p,"always_allow");stage=3;}
   case 3->{if(approval!=null)return;require(grants==2&&ServerChatAccess.allowed(guest,agent),"ALWAYS_ALLOW_NOT_SAVED");var policy=ServerChatAccess.policy(s,agent);ServerChatAccess.edit(p,agent,Map.of("policyRevision",Long.toString(policy.revision()),"mode","ASK","playerId",guest.getUUID().toString(),"entry","remove"));ask(p,"always_deny");stage=4;}
   case 4->{if(approval!=null)return;require(grants==2&&!ServerChatAccess.allowed(guest,agent),"ALWAYS_DENY_NOT_SAVED");save(s,"access",Map.of("status","FOUR_OWNER_DECISIONS_AND_PLAYER_SCOPE_VERIFIED","visitorType","NATIVE_SERVER_PLAYER_TEST_ACTOR_NOT_SECOND_CLIENT","grants",grants));var a=JSON.createObjectNode().put("action","break").put("item","minecraft:iron_axe");a.putArray("position").add(8).add(114).add(0);pending=call(p,"agent_block_action",a);stage=5;}
   case 5->{}
   case 6->{require(p.level().getBlockState(new BlockPos(8,114,0)).isAir(),"LOG_NOT_BROKEN");require(p.level().getBlockState(new BlockPos(0,111,0)).getValue(DoorBlock.OPEN),"DOOR_NOT_OPENED_BY_BODY");var a=JSON.createObjectNode().put("action","place").put("item","minecraft:crafting_table");a.putArray("position").add(7).add(112).add(0);pending=call(p,"agent_block_action",a);stage=7;}
   case 7->{}
   case 8->{require(p.level().getBlockState(new BlockPos(7,112,0)).is(Blocks.CRAFTING_TABLE),"BODY_PLACE_FAILED");p.teleportTo(p.level(),-2.5,111,.5,Set.of(),-90,0,true);p.getInventory().clearContent();p.inventoryMenu.broadcastChanges();for(var target:List.of(new BlockPos(0,111,0),new BlockPos(-3,111,2),new BlockPos(-2,111,2),new BlockPos(-1,111,2))){if(target.getZ()==2)p.level().setBlock(target,(target.getX()==-3?Blocks.CHEST:target.getX()==-2?Blocks.CRAFTING_TABLE:Blocks.STONE_BUTTON).defaultBlockState(),2);var source=JSON.createObjectNode().put("name","原生交互锁").put("key_item","minecraft:stick");source.putArray("position").add(target.getX()).add(target.getY()+(target.getZ()==0?1:0)).add(target.getZ());source.putArray("events").add("block_use");ServerInteractionRules.set(p,UUID.randomUUID(),JSON.createObjectNode().put("source",source.toString()),false);}var door=p.level().getBlockState(new BlockPos(0,111,0));p.level().setBlock(new BlockPos(0,111,0),door.setValue(DoorBlock.OPEN,false),2);p.level().setBlock(new BlockPos(0,112,0),p.level().getBlockState(new BlockPos(0,112,0)).setValue(DoorBlock.OPEN,false),2);lockStep=1;since=s.getTickCount();stage=9;}
   case 9->{if(lockSent<lockStep||s.getTickCount()-since<20)return;require(!p.level().getBlockState(new BlockPos(0,111,0)).getValue(DoorBlock.OPEN)&&p.containerMenu==p.inventoryMenu&&!p.level().getBlockState(new BlockPos(-1,111,2)).getValue(net.minecraft.world.level.block.ButtonBlock.POWERED),"NATIVE_LOCK_DID_NOT_CANCEL");if(lockStep<4){lockStep++;since=s.getTickCount();return;}p.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,new net.minecraft.world.item.ItemStack(net.minecraft.world.item.Items.STICK));p.inventoryMenu.broadcastChanges();lockStep=5;since=s.getTickCount();stage=10;}
   case 10->{if(lockSent<5||s.getTickCount()-since<20)return;require(p.level().getBlockState(new BlockPos(0,111,0)).getValue(DoorBlock.OPEN),"KEY_DID_NOT_ALLOW_NATIVE_DOOR");save(s,"locks",ServerInteractionRules.inspect(p,0));var source=JSON.createObjectNode().put("name","动画测试体").put("disposition","friendly").put("rideable",true);var anim=source.putObject("animations");anim.set("idle",JSON.readTree("{\"duration_ticks\":40,\"keyframes\":[{\"tick\":0},{\"tick\":20,\"translation\":[0,0.2,0]},{\"tick\":40}]}"));anim.set("hurt",JSON.readTree("{\"duration_ticks\":10,\"keyframes\":[{\"tick\":0,\"rotation\":[0,0,25]},{\"tick\":10}]}"));anim.set("random",JSON.readTree("{\"duration_ticks\":20,\"interval_ticks\":60,\"keyframes\":[{\"tick\":0},{\"tick\":10,\"rotation\":[0,60,0]},{\"tick\":20}]}"));var r=dev.mineagent.runtime.neoforge.content.RuntimeCreatures.define(p,UUID.randomUUID(),JSON.createObjectNode().put("source",source.toString()));var species=(dev.mineagent.runtime.core.creature.CreatureStore.Species)r.get("species");var spawn=JSON.createObjectNode().put("action","spawn").put("species_id",species.id().toString());spawn.putArray("position").add(-1.5).add(111).add(4.5);var entity=JSON.valueToTree(dev.mineagent.runtime.neoforge.content.RuntimeCreatures.control(p,spawn).get("entity"));creature=UUID.fromString(entity.path("entity_id").asText());p.teleportTo(p.level(),-6.5,111,4.5,Set.of(),-90,10,true);importPreviewPack(p);uiReady=true;stage=11;}
   case 11->{if(!uiDone)return;p.teleportTo(p.level(),-3.5,111,4.5,Set.of(),-90,10,true);p.setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,net.minecraft.world.item.ItemStack.EMPTY);p.inventoryMenu.broadcastChanges();var c=(net.minecraft.world.entity.LivingEntity)p.level().getEntity(creature);entityHealth=c.getHealth();var source=JSON.createObjectNode().put("name","实体交互锁").put("entity_id",creature.toString());source.putArray("events").add("entity_use").add("entity_attack");entityRule=UUID.randomUUID();ServerInteractionRules.set(p,entityRule,JSON.createObjectNode().put("source",source.toString()),false);entityLocked=true;since=s.getTickCount();stage=12;}
   case 12->{if(!lockedInputSent||s.getTickCount()-since<40)return;var c=(net.minecraft.world.entity.LivingEntity)p.level().getEntity(creature);require(c.getHealth()==entityHealth&&!p.isPassenger(),"ENTITY_LOCK_NOT_ENFORCED");save(s,"entity-lock",Map.of("healthUnchanged",true,"mountBlocked",true,"rules",ServerInteractionRules.inspect(p,0)));ServerInteractionRules.set(p,UUID.randomUUID(),JSON.createObjectNode().put("rule_id",entityRule.toString()).put("expected_revision",1),true);entityUnlocked=true;since=s.getTickCount();stage=13;}
   case 13->{if(!unlockedInputSent||s.getTickCount()-since<40)return;require(p.getVehicle()!=null&&p.getVehicle().getUUID().equals(creature),"ENTITY_UNLOCK_MOUNT_FAILED");p.stopRiding();save(s,"entity-unlock",Map.of("nativeMountRestored",true));save(s,"server",Map.of("status","NATIVE_NINE_FEATURES_IMPLEMENTATION_REGRESSION_VERIFIED","evidence",evidence,"defaultAgent",ServerChatSettings.defaultAgent(p),"access",ServerChatAccess.policy(s,agent)));complete=true;}
  }
 }catch(Exception e){failure=e.toString();try{save(s,"failure",Map.of("error",failure,"stage",stage,"evidence",evidence));}catch(Exception ignored){}}}
 @SuppressWarnings("unchecked") private static void ask(ServerPlayer owner,String choice)throws Exception{boolean admitted=ServerChatAccess.admitOrAsk(guest,agent,"访问测试"+choice,()->grants++);require(!admitted,"GUEST_BYPASSED_APPROVAL");var f=ServerChatAccess.class.getDeclaredField("PENDING");f.setAccessible(true);var map=((Map<MinecraftServer,Map<UUID,?>>)f.get(null)).get(owner.level().getServer());approval=map.keySet().iterator().next();approvalChoice=choice;try{ServerChatAccess.decide(guest,approval,choice);throw new IllegalStateException("NON_OWNER_DECIDED");}catch(SecurityException expected){}}
 private static void importPreviewPack(ServerPlayer p)throws Exception{var runtime=ServerPackageRuntime.get(p.level().getServer());byte[] js="on('instance.create',function(){});".getBytes(java.nio.charset.StandardCharsets.UTF_8),mesh="{\"version\":1,\"boxes\":[{\"from\":[-0.3,0,-0.3],\"to\":[0.3,0.6,0.3],\"color\":\"#E6B85C\"}],\"collision\":[-0.3,0,-0.3,0.3,0.6,0.3]}".getBytes(java.nio.charset.StandardCharsets.UTF_8);var script=new dev.mineagent.runtime.worker.generation.GeneratedFile("server/main.js",dev.mineagent.runtime.api.packages.RuntimeResourceSide.SERVER,"application/javascript",dev.mineagent.runtime.core.objects.RuntimeModelBundle.hash(js),js);var model=new dev.mineagent.runtime.worker.generation.GeneratedFile("models/item.json",dev.mineagent.runtime.api.packages.RuntimeResourceSide.COMMON,"application/json",dev.mineagent.runtime.core.objects.RuntimeModelBundle.hash(mesh),mesh);var entry=new dev.mineagent.runtime.api.packages.RuntimeEntrypoint(script.path(),script.side(),script.sha256());var definition=new dev.mineagent.runtime.api.packages.RuntimeDefinition(UUID.randomUUID(),"预览测试物品",dev.mineagent.runtime.api.packages.RuntimeDefinitionKind.ITEM,"server",Set.of(model.path()),Map.of(),1);var parsed=new dev.mineagent.runtime.worker.generation.ParsedRuntimePackage("预览测试包","1.0",dev.mineagent.runtime.api.packages.RuntimePackageType.CONTENT,dev.mineagent.runtime.api.packages.ActivationMode.HOT_RUNTIME,Map.of(),Set.of("RUN_CODE"),Map.of("server",entry,"server.restore",entry),List.of(definition),List.of(script,model));pack=runtime.importOwned(p,UUID.randomUUID(),parsed).packageId();}
 private static void realTick(MinecraftServer s,ServerPlayer p)throws Exception{if(!paidStarted){paidStarted=true;ServerConversations.get(s).submitNative(p,agent,"请通过对话工具完成：把你的原生聊天思考隐藏，深度保持high，设置只对我生效的默认无@响应且明确绑定你；你亲自走过门、栅栏门、半砖、地毯和台阶，用铁斧破坏(8,114,0)的木头，然后拿出工作台放在(7,112,0)。必须走过去、持物、调整视角，不用指令或传送代替。给(0,111,0)的门增加原生交互锁，只有手持minecraft:stick能右键。再创建一个友好蓝色生物，设置idle上下浮动、random转动、hurt倾斜动画，生成到(-1,111,4)，打开生物预览。不要执行电脑命令。",true);return;}var store=ServerConversations.get(s).store();var cs=store.list(p.getUUID(),agent,"ACTIVE","",0,20).conversations();if(cs.isEmpty())return;var c=cs.getFirst();if(c.messageCount()<2||!c.activeOperation().isEmpty())return;var ctx=store.context(p.getUUID(),agent,c.conversationId(),null).orElseThrow();save(s,"real-context",ctx);require(ctx.requestState().equals("COMPLETE"),"REAL_CHAT_"+ctx.errorCode());require(p.level().getBlockState(new BlockPos(8,114,0)).isAir()&&p.level().getBlockState(new BlockPos(7,112,0)).is(Blocks.CRAFTING_TABLE),"REAL_BODY_NOT_DONE");require(agent.equals(ServerChatSettings.defaultAgent(p)),"REAL_DEFAULT_NOT_SET");save(s,"real",Map.of("status","REAL_DEEPSEEK_NINE_SCENARIO_COMPLETE","evidence",evidence,"settings",ServerChatSettings.inspect(p,agent),"rules",ServerInteractionRules.inspect(p,0),"creatures",dev.mineagent.runtime.neoforge.content.RuntimeCreatures.catalog(p,0)));complete=true;}
 private FeedbackNineSmokeServer(){}
}
