package dev.mineagent.runtime.neoforge.ui;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;import dev.mineagent.runtime.core.conversation.ConversationStore;import net.minecraft.server.MinecraftServer;import net.minecraft.server.level.ServerPlayer;import java.util.*;import java.nio.file.*;import com.fasterxml.jackson.databind.ObjectMapper;
public final class FeedbackChatSmokeServer {
 public static volatile boolean ready,clientReady,complete;public static volatile UUID agent,cancelId,firstOperation,oldConversation;public static volatile int stage;public static volatile String failure="";private static final Map<UUID,List<String>> PROMPTS=new LinkedHashMap<>();private static final ObjectMapper JSON=new ObjectMapper();
 public static boolean active(){return Boolean.getBoolean("mineagent.conversationAgentSmoke")&&System.getProperty("mineagent.conversationAgentScenario","").equals("feedback_chat");}
 public static void capture(UUID conversation,String prompt){if(active())PROMPTS.computeIfAbsent(conversation,k->new ArrayList<>()).add(prompt);}
 private static void require(boolean test,String code){if(!test)throw new IllegalStateException(code);}
 public static void tick(MinecraftServer server){if(complete||!failure.isEmpty())return;var p=server.getPlayerList().getPlayers().stream().filter(v->!(v instanceof dev.mineagent.runtime.neoforge.body.MineAgentPlayer)).findFirst().orElse(null);if(p==null)return;try{var root=Files.createDirectories(server.getServerDirectory().resolve("chat-lifecycle-smoke"));if(!ready){server.getPlayerList().op(p.nameAndId());agent=MineAgentRuntimeServices.bodies(server).createPersistentAt("对话验收",p.getUUID(),p.level(),p.position().add(2,0,0)).agentId();ready=true;return;}if(!clientReady)return;var conversations=ServerConversations.get(server);var store=conversations.store();if(server.getTickCount()%60==0)Files.writeString(root.resolve("progress.json"),JSON.writeValueAsString(Map.of("stage",stage,"cancel",cancelId==null?"":cancelId,"conversations",store.list(p.getUUID(),agent,"ALL","",0,20).conversations())));
  if(stage==0){var list=store.list(p.getUUID(),agent,"ACTIVE","",0,20).conversations();if(list.isEmpty())return;var c=list.getFirst();oldConversation=c.conversationId();if(firstOperation==null&&!c.activeOperation().isEmpty())firstOperation=UUID.fromString(c.activeOperation());var f=ServerConversations.class.getDeclaredField("pendingNative");f.setAccessible(true);var map=(Map<?,?>)f.get(conversations);for(var entry:map.entrySet()){var method=entry.getValue().getClass().getDeclaredMethod("text");method.setAccessible(true);if(method.invoke(entry.getValue()).toString().contains("CANCELLED_QUEUE_MARKER"))cancelId=(UUID)entry.getKey();}if(cancelId!=null)stage=1;}
  if(stage==1){var c=store.get(p.getUUID(),agent,oldConversation);if(c.messageCount()<4)return;stage=2;}
  if(stage==2){var c=store.get(p.getUUID(),agent,oldConversation);if(!c.activeOperation().isEmpty())return;require(c.messageCount()==4,"QUEUE_CANCEL_WRONG_COUNT");var context=store.context(p.getUUID(),agent,c.conversationId(),null).orElseThrow();require(context.requestState().equals("COMPLETE"),"QUEUE_MESSAGE_CANCELLED_OR_FAILED");String prompts=String.join("\n",PROMPTS.getOrDefault(oldConversation,List.of()));require(!prompts.contains("CANCELLED_QUEUE_MARKER")&&prompts.contains("QUEUED_SENT_MARKER"),"QUEUE_PROMPT_CONTENT");stage=3;}
  if(stage==3){if(!store.get(p.getUUID(),agent,oldConversation).state().equals("DELETED"))return;stage=4;}
  if(stage==4){var list=store.list(p.getUUID(),agent,"ACTIVE","",0,20).conversations();if(list.isEmpty())return;var c=list.getFirst();if(c.messageCount()<2||!c.activeOperation().isEmpty())return;require(!c.conversationId().equals(oldConversation),"DELETED_NATIVE_CONVERSATION_REUSED");require(store.context(p.getUUID(),agent,c.conversationId(),null).orElseThrow().requestState().equals("COMPLETE"),"FRESH_CHAT_NOT_COMPLETE");String prompts=String.join("\n",PROMPTS.getOrDefault(c.conversationId(),List.of()));require(prompts.contains("NEW_CONTEXT_OK")&&!prompts.contains("FIRST_OLD_CONTEXT")&&!prompts.contains("QUEUED_SENT_MARKER")&&!prompts.contains("CANCELLED_QUEUE_MARKER"),"DELETED_CONTEXT_RESUBMITTED");Files.writeString(root.resolve("server.json"),JSON.writeValueAsString(Map.of("status","REAL_QUEUE_CANCEL_DELETE_CONTEXT_ISOLATION_VERIFIED","oldConversation",oldConversation,"newConversation",c.conversationId(),"oldMessageCount",4,"newMessageCount",2,"cancelledTextNotSubmitted",true,"freshPromptExcludesOldContext",true,"defaultAgent",ServerChatSettings.defaultAgent(p),"depth",ServerChatSettings.inspect(p,agent))));complete=true;}
 }catch(Exception e){failure=e.toString();try{Files.writeString(server.getServerDirectory().resolve("chat-lifecycle-smoke/failure.json"),JSON.writeValueAsString(Map.of("stage",stage,"error",failure)));}catch(Exception ignored){}}}
 private FeedbackChatSmokeServer(){}
}
