package dev.mineagent.runtime.neoforge.ui;
import com.fasterxml.jackson.databind.*;import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;import dev.mineagent.runtime.core.building.BuildingNbt;import net.minecraft.core.BlockPos;import net.minecraft.world.level.block.Blocks;import java.util.*;import java.nio.file.*;
public final class FullImportSmokeServer {
 public static volatile boolean ready,clientReady,complete;public static volatile String failure="";public static volatile UUID agent;private static boolean started;private static final ObjectMapper JSON=new ObjectMapper();
 public static boolean active(){return Boolean.getBoolean("mineagent.conversationAgentReal")&&Boolean.getBoolean("mineagent.conversationAgentSmoke")&&System.getProperty("mineagent.conversationAgentScenario","").equals("full_import_zero");}
 public static void tick(net.minecraft.server.MinecraftServer s){if(complete||!failure.isEmpty())return;var p=s.getPlayerList().getPlayers().stream().filter(v->!(v instanceof dev.mineagent.runtime.neoforge.body.MineAgentPlayer)).findFirst().orElse(null);if(p==null)return;try{Path root=Files.createDirectories(s.getServerDirectory().resolve("full-import-smoke"));if(!ready){s.getPlayerList().op(p.nameAndId());p.setGameMode(net.minecraft.world.level.GameType.CREATIVE);for(var pos:BlockPos.betweenClosed(new BlockPos(-5,110,-5),new BlockPos(15,120,15)))p.level().setBlock(pos,pos.getY()==110?Blocks.SMOOTH_STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),2);p.teleportTo(p.level(),-3.5,111,3.5,Set.of(),-90,0,true);agent=MineAgentRuntimeServices.bodies(s).createPersistentAt("内容助手",p.getUUID(),p.level(),p.position().add(0,0,3)).agentId();ready=true;return;}if(!clientReady||started)return;started=true;
  var chest=new LinkedHashMap<String,Object>();chest.put("id","minecraft:chest");chest.put("Items",List.of(Map.of("Slot",(byte)0,"id","minecraft:diamond","Count",(byte)7)));var entity=new LinkedHashMap<String,Object>();entity.put("id","minecraft:armor_stand");entity.put("NoGravity",(byte)1);entity.put("CustomName","{\"text\":\"内容保留\"}");entity.put("Rotation",List.of(0f,0f));entity.put("Pos",List.of(2.5,1.0,.5));
  var blocks=new ArrayList<Object>();for(int x=0;x<3;x++)blocks.add(Map.of("pos",List.of(x,0,0),"state",0));blocks.add(Map.of("pos",List.of(0,1,0),"state",1,"nbt",chest));chest.put("x",0);chest.put("y",1);chest.put("z",0);var nbt=Map.<String,Object>of("Version",6,"MinecraftDataVersion",3465,"Regions",Map.of("contents",Map.of("Position",Map.of("x",0,"y",0,"z",0),"Size",Map.of("x",3,"y",2,"z",1),"BlockStatePalette",List.of(Map.of("Name","minecraft:stone"),Map.of("Name","minecraft:chest","Properties",Map.of("facing","south","type","single","waterlogged","false")),Map.of("Name","minecraft:air")),"BlockStates",new long[]{2624},"TileEntities",List.of(chest),"Entities",List.of(entity),"PendingBlockTicks",List.of(Map.of("Block","minecraft:stone","x",0,"y",0,"z",0,"Time",6000L,"Priority",-1)))));Path file=root.resolve("contents.litematic");try(var out=new java.util.zip.GZIPOutputStream(Files.newOutputStream(file))){out.write(BuildingNbt.encode(nbt));}
  ServerBuildingFiles.library(p,agent).thenApplyAsync(l->{try{return l.importFile(p.getUUID(),file,"NATIVE_CONTENT_FIXTURE");}catch(Exception e){throw new java.util.concurrent.CompletionException(e);}}).whenComplete((asset,error)->s.execute(()->{if(error!=null){failure=error.toString();return;}var args=JSON.createObjectNode().put("file_id",asset.id().toString()).put("source_facing","south").put("target_facing","north");args.putArray("anchor").add(4).add(111).add(4);ConversationAgentTools.execute(p,agent,UUID.randomUUID(),"plan_building_import",args.toString(),()->true).thenCompose(plan->{if(!"PLANNED".equals(plan.get("status")))throw new IllegalStateException("FULL_PLAN_"+plan);return ConversationAgentTools.execute(p,agent,UUID.randomUUID(),"apply_world_geometry","{\"plan_id\":\""+plan.get("planId")+"\"}",()->true);}).whenComplete((receipt,failed)->s.execute(()->{try{if(failed!=null||!"APPLIED".equals(receipt.get("status")))throw new IllegalStateException("FULL_APPLY_"+receipt,failed);var block=p.level().getBlockState(new BlockPos(6,112,4));var be=p.level().getBlockEntity(new BlockPos(6,112,4));if(!(be instanceof net.minecraft.world.level.block.entity.ChestBlockEntity box)||!box.getItem(0).is(net.minecraft.world.item.Items.DIAMOND)||box.getItem(0).getCount()!=7||block.getValue(net.minecraft.world.level.block.ChestBlock.FACING)!=net.minecraft.core.Direction.NORTH)throw new IllegalStateException("FULL_CHEST_OR_DIRECTION");var entities=p.level().getEntitiesOfClass(net.minecraft.world.entity.decoration.ArmorStand.class,new net.minecraft.world.phys.AABB(4,111,4,7,115,6));if(entities.size()!=1||!entities.getFirst().getName().getString().equals("内容保留")||Math.abs(entities.getFirst().getX()-4.5)>.01)throw new IllegalStateException("FULL_ENTITY_DATA_OR_POSITION");if(!p.level().getBlockTicks().hasScheduledTick(new BlockPos(6,111,4),Blocks.STONE)||((Number)receipt.get("scheduledTicks")).longValue()!=1)throw new IllegalStateException("SCHEDULED_TICK_NOT_RESTORED");Files.writeString(root.resolve("server.json"),JSON.writeValueAsString(Map.of("status","DEFAULT_FULL_CONTENTS_DIRECTION_NATIVE_VERIFIED","diamonds",7,"facing","north","armorStand",entities.getFirst().getUUID(),"receipt",receipt)));complete=true;}catch(Exception e){failure=e.toString();}}));}));
 }catch(Exception e){failure=e.toString();}}
 private FullImportSmokeServer(){}
}
