package dev.mineagent.runtime.neoforge.ui;
import com.fasterxml.jackson.databind.*;import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;import dev.mineagent.runtime.neoforge.body.MineAgentPlayer;import net.minecraft.server.MinecraftServer;import net.minecraft.core.BlockPos;import net.minecraft.world.level.block.Blocks;import java.nio.file.*;import java.util.*;
public final class MediaToolsSmokeServer {
 public static volatile boolean ready,clientReady,complete;public static volatile String failure="";public static volatile UUID agent;public static volatile int skinApplications;public static volatile String thinking="";private static MineAgentPlayer original;private static String profileName,displayName;private static int entityId;private static long ticksBefore;private static boolean replaying;private static int replayIndex;private static final Map<String,String> remapped=new HashMap<>();private static boolean followStarted,preview,fileWritten,offered,exported;private static final ObjectMapper JSON=new ObjectMapper();private static final List<Object> evidence=new ArrayList<>();
 public static boolean active(){return Boolean.getBoolean("mineagent.conversationAgentReal")&&Boolean.getBoolean("mineagent.conversationAgentSmoke")&&Set.of("media_tools","media_tools_saved").contains(System.getProperty("mineagent.conversationAgentScenario",""));}
 public static boolean saved(){return System.getProperty("mineagent.conversationAgentScenario","").equals("media_tools_saved");}
 public static void observe(String tool,Map<String,Object> receipt){if(!active())return;evidence.add(Map.of("tool",tool,"receipt",receipt));if(tool.equals("set_skin_png")&&"APPLIED".equals(receipt.get("status")))skinApplications++;preview|=tool.equals("open_preview")&&"PREVIEW_OPENED".equals(receipt.get("status"));fileWritten|=tool.equals("write_file")&&"CREATED".equals(receipt.get("status"));offered|=tool.equals("offer_file_download")&&"DOWNLOAD_ENTRY_SENT".equals(receipt.get("status"));exported|=tool.equals("export_current_skin")&&"CURRENT_SKIN_EXPORTED".equals(receipt.get("status"));}
 public static void tick(MinecraftServer s){if(complete||!failure.isEmpty())return;var p=s.getPlayerList().getPlayers().stream().filter(v->!(v instanceof MineAgentPlayer)).findFirst().orElse(null);if(p==null)return;try{Path root=Files.createDirectories(s.getServerDirectory().resolve("media-tools-smoke"));if(!ready){s.getPlayerList().op(p.nameAndId());p.setGameMode(net.minecraft.world.level.GameType.CREATIVE);for(var pos:BlockPos.betweenClosed(new BlockPos(-12,110,-12),new BlockPos(12,120,12)))p.level().setBlock(pos,pos.getY()==110?Blocks.SMOOTH_STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),2);p.teleportTo(p.level(),3.5,111,3.5,Set.of(),90,0,true);agent=MineAgentRuntimeServices.bodies(s).createPersistentAt("造物助手",p.getUUID(),p.level(),p.position().add(-8,0,0)).agentId();original=MineAgentRuntimeServices.bodies(s).body(agent).orElseThrow();profileName=original.getGameProfile().name();displayName=original.getDisplayName().getString();entityId=original.getId();ticksBefore=original.nativeTicks();ready=true;return;}if(!clientReady)return;if(!followStarted){ConversationBodyTools.execute(p,agent,JSON.createObjectNode().put("action","follow"),false);followStarted=true;}
 if(s.getTickCount()%100==0)Files.writeString(root.resolve("progress.json"),JSON.writeValueAsString(Map.of("skinApplications",skinApplications,"preview",preview,"fileWritten",fileWritten,"offered",offered,"exported",exported,"evidence",evidence)));
 if(saved()){var operations=JSON.readTree(Files.readString(s.getServerDirectory().resolve("runtime-item-source.json")));if(replayIndex<operations.size()){if(replaying)return;var source=operations.get(replayIndex);String arguments=source.path("arguments").asText();for(var pair:remapped.entrySet())arguments=arguments.replace(pair.getKey(),pair.getValue());replaying=true;ConversationAgentTools.execute(p,agent,UUID.randomUUID(),source.path("tool").asText(),arguments,()->true).whenComplete((value,error)->s.execute(()->{try{if(error!=null||value.containsKey("error")&&!String.valueOf(value.get("error")).isEmpty()||Set.of("REJECTED","PARTIAL","UNKNOWN").contains(value.get("status")))throw new IllegalStateException("SAVED_MEDIA_TOOL_"+value,error);var before=source.path("result").path("file").path("id");if(before.isTextual()){var file=JSON.valueToTree(value.get("file"));remapped.put(before.asText(),file.path("id").asText());}replayIndex++;}catch(Exception e){failure=e.toString();}finally{replaying=false;}}));return;}var body=MineAgentRuntimeServices.bodies(s).body(agent).orElseThrow();if(body!=original||!body.getGameProfile().name().equals(profileName)||body.getId()!=entityId)throw new IllegalStateException("SAVED_SKIN_IDENTITY");thinking="REAL_HISTORY_NOT_REPLAYED";Files.writeString(root.resolve("server.json"),JSON.writeValueAsString(Map.of("status","SAVED_REAL_MEDIA_OPS_NATIVE_VERIFIED","sameInstance",true,"operations",replayIndex,"evidence",evidence)));complete=true;return;}
 var store=ServerConversations.get(s).store();var cs=store.list(p.getUUID(),agent,"ALL","",0,20).conversations();if(cs.isEmpty())return;var c=cs.getFirst();if(c.messageCount()<2||!c.activeOperation().isEmpty())return;var ctx=store.context(p.getUUID(),agent,c.conversationId(),null).orElseThrow();Files.writeString(root.resolve("context.json"),JSON.writeValueAsString(ctx));if(!ctx.requestState().equals("COMPLETE"))throw new IllegalStateException("MEDIA_CHAT_"+ctx.errorCode());var body=MineAgentRuntimeServices.bodies(s).body(agent).orElseThrow();if(body!=original||body.getId()!=entityId||!body.getUUID().equals(agent)||!body.getGameProfile().name().equals(profileName)||!body.getDisplayName().getString().equals(displayName)||body.nativeTicks()<=ticksBefore||!Boolean.parseBoolean(MineAgentRuntimeServices.config(s).snapshot().values().getOrDefault("agent."+agent+".follow","false")))throw new IllegalStateException("SKIN_IDENTITY_OR_TASK_CHANGED");if(skinApplications<2||!preview||!fileWritten||!offered||!exported)throw new IllegalStateException("MEDIA_TOOLS_INCOMPLETE");var meta=store.thinking(p.getUUID(),agent,c.conversationId(),ctx.assistantMessageId());StringBuilder full=new StringBuilder();for(int offset=0;offset<meta.textLength();){var chunk=store.thinkingChunk(p.getUUID(),agent,c.conversationId(),ctx.assistantMessageId(),meta.revision(),offset,4096);full.append(chunk.text());offset+=chunk.text().length();}thinking=full.toString();if(thinking.isBlank())throw new IllegalStateException("THINKING_NOT_STORED");Files.writeString(root.resolve("server.json"),JSON.writeValueAsString(Map.of("status","REAL_FILES_PREVIEW_HOT_SKIN_IDENTITY_VERIFIED","skinApplications",skinApplications,"sameServerInstance",true,"sameUuidAndName",true,"sameEntityId",true,"followingRetained",true,"ticksBefore",ticksBefore,"ticksAfter",body.nativeTicks(),"thinkingStoredChars",thinking.length(),"evidence",evidence)));complete=true;
 }catch(Exception e){failure=e.toString();try{Files.writeString(Files.createDirectories(s.getServerDirectory().resolve("media-tools-smoke")).resolve("failure.json"),JSON.writeValueAsString(Map.of("error",failure,"evidence",evidence)));}catch(Exception ignored){}}}
 public static void verifyIdentity(MinecraftServer server,boolean png){var body=MineAgentRuntimeServices.bodies(server).body(agent).orElseThrow();if(body!=original||body.getId()!=entityId||body.hasVisualProfile()!=png||!body.getGameProfile().name().equals(profileName)||!body.getUUID().equals(agent)||!Boolean.parseBoolean(MineAgentRuntimeServices.config(server).snapshot().values().getOrDefault("agent."+agent+".follow","false")))throw new IllegalStateException("SKIN_SWITCH_IDENTITY_OR_TASK_CHANGED");}
 private MediaToolsSmokeServer(){}
}
