package dev.mineagent.runtime.neoforge.ui;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.tick.ServerTickEvent;
import java.util.*;
import java.nio.file.*;
@EventBusSubscriber(modid="mineagent_runtime")
public final class NativeMentionSmokeServer {
    public static volatile boolean ready,verified,reviewObserved,commandsVerified;public static volatile String failure="";private static UUID agent;private static int ticks;
    @SubscribeEvent public static void tick(ServerTickEvent.Post event)throws Exception{if(!Boolean.getBoolean("mineagent.nativeMentionSmoke")||commandsVerified||!failure.isEmpty())return;var s=event.getServer();var p=s.getPlayerList().getPlayers().stream().filter(v->!(v instanceof dev.mineagent.runtime.neoforge.body.MineAgentPlayer)).findFirst().orElse(null);if(p==null)return;
        try{if(++ticks>1800)throw new IllegalStateException("NATIVE_MENTION_TIMEOUT");if(!ready){s.getPlayerList().op(p.nameAndId());var bodies=MineAgentRuntimeServices.bodies(s);agent=bodies.createPersistentAt("小明",p.getUUID(),s.overworld(),p.position().add(2,0,0)).agentId();bodies.createPersistentAt("AI Helper",p.getUUID(),s.overworld(),p.position().add(4,0,0));ready=true;return;}if(verified){var observation=dev.mineagent.runtime.neoforge.task.PlayerCommandAgent.observe(p);String state=String.valueOf(observation.get("state"));if(state.equals("REVIEW")){if(s.getScoreboard().getObjective("mention_score")!=null)throw new IllegalStateException("COMMAND_BEFORE_CONFIRM");reviewObserved=true;}if(Set.of("FAILED","OUTCOME_UNKNOWN","CANCELLED").contains(state))throw new IllegalStateException(observation.toString());if(state.equals("COMPLETED")){var objective=s.getScoreboard().getObjective("mention_score");var score=s.getScoreboard().getPlayerScoreInfo(p,objective);var sharp=s.registryAccess().lookupOrThrow(net.minecraft.core.registries.Registries.ENCHANTMENT).getOrThrow(net.minecraft.world.item.enchantment.Enchantments.SHARPNESS);if(!reviewObserved||score==null||score.value()!=11||!s.overworld().getGameRules().get(net.minecraft.world.level.gamerules.GameRules.KEEP_INVENTORY)||!p.getMainHandItem().is(net.minecraft.world.item.Items.DIAMOND_SWORD)||net.minecraft.world.item.enchantment.EnchantmentHelper.getTagEnchantmentLevel(sharp,p.getMainHandItem())!=3)throw new IllegalStateException("COMMAND_NATIVE_READBACK");var dir=Files.createDirectories(s.getServerDirectory().resolve("native-mention-smoke"));Files.writeString(dir.resolve("commands.json"),new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(observation));commandsVerified=true;}return;}var store=ServerConversations.get(s).store();var list=store.list(p.getUUID(),agent,"ALL","",0,20).conversations();if(list.isEmpty())return;if(list.size()!=1)throw new IllegalStateException("MENTION_MULTIPLE_CONVERSATIONS");var c=list.getFirst();if(c.messageCount()!=2||!c.activeOperation().isEmpty())return;var context=store.context(p.getUUID(),agent,c.conversationId(),null).orElseThrow();if(!context.requestState().equals("COMPLETE")||!context.inputSource().equals("CHAT"))throw new IllegalStateException("MENTION_CONTEXT");var messages=store.messages(p.getUUID(),agent,c.conversationId(),0,20);var dir=Files.createDirectories(s.getServerDirectory().resolve("native-mention-smoke"));Files.writeString(dir.resolve("server.json"),new com.fasterxml.jackson.databind.ObjectMapper().writeValueAsString(Map.of("conversation",c,"context",context,"messages",messages,"webFocusChanged",ServerConversations.get(s).focused(p).isPresent(),"provider","CONTROLLED_LOCAL_SSE")));verified=true;
        }catch(Exception e){failure=e.toString();}
    }
}
