package dev.mineagent.runtime.neoforge.ui;
import com.fasterxml.jackson.databind.JsonNode;import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;import dev.mineagent.runtime.neoforge.body.*;import net.minecraft.server.MinecraftServer;import net.minecraft.server.level.ServerPlayer;import net.minecraft.core.*;import net.minecraft.resources.Identifier;import net.minecraft.world.InteractionHand;import net.minecraft.world.item.*;import net.minecraft.world.level.block.state.BlockState;import net.minecraft.world.phys.*;import net.neoforged.bus.api.SubscribeEvent;import net.neoforged.fml.common.EventBusSubscriber;import java.util.*;import java.util.concurrent.*;import java.util.function.BooleanSupplier;
/** One physical action: approach -> equip -> face -> native use/mining -> observe. */
@EventBusSubscriber(modid="mineagent_runtime")
public final class NativeAgentBlockActions {
 private static final Map<MinecraftServer,List<Job>> JOBS=new IdentityHashMap<>();
 public static CompletableFuture<Map<String,Object>> start(ServerPlayer owner,UUID agent,UUID operation,JsonNode a,BooleanSupplier permit){var b=MineAgentRuntimeServices.bodies(owner.level().getServer()).body(agent).orElseThrow(()->new IllegalArgumentException("AGENT_BODY_UNAVAILABLE"));if(b.level()!=owner.level()||!b.canAct()||b.taskControlOwned())throw new IllegalStateException("AGENT_BODY_BUSY_OR_DIMENSION");String action=a.path("action").asText();if(!Set.of("break","place","use").contains(action))throw new IllegalArgumentException("AGENT_BLOCK_ACTION");var n=a.path("position");if(!n.isArray()||n.size()!=3)throw new IllegalArgumentException("AGENT_BLOCK_POSITION");for(var v:n)if(!v.isIntegralNumber()||!v.canConvertToInt())throw new IllegalArgumentException("AGENT_BLOCK_POSITION");var pos=new BlockPos(n.get(0).intValue(),n.get(1).intValue(),n.get(2).intValue());if(!b.level().hasChunkAt(pos)||b.level().isOutsideBuildHeight(pos)||!b.level().getWorldBorder().isWithinBounds(pos))throw new IllegalArgumentException("AGENT_BLOCK_UNLOADED");var job=new Job(owner,b,operation,pos,action,a.path("item").asText(""),a.path("approach").asText("walk"),permit);if(!b.claimTaskControl(operation,job::valid,()->job.finish("CANCELLED","AGENT_CONTROL_REVOKED")))throw new IllegalStateException("AGENT_BODY_BUSY");JOBS.computeIfAbsent(owner.level().getServer(),k->new ArrayList<>()).add(job);return job.result;}
 public static boolean stop(ServerPlayer owner,UUID agent){for(var job:List.copyOf(JOBS.getOrDefault(owner.level().getServer(),List.of())))if(job.body.agentId().equals(agent)&&job.owner==owner){job.finish("CANCELLED","USER_STOPPED");return true;}return false;}
 private static final class Job {
  final ServerPlayer owner;final MineAgentPlayer body;final UUID operation;final BlockPos pos;final String action,item,approach;final BooleanSupplier permit;final net.minecraft.server.level.ServerLevel level;final BlockState before;final CompletableFuture<Map<String,Object>> result=new CompletableFuture<>();final int started;int phase,at,cracks,held;long navigation;boolean done,committed;Vec3 destination;
  Job(ServerPlayer p,MineAgentPlayer b,UUID op,BlockPos pos,String action,String item,String approach,BooleanSupplier permit){owner=p;body=b;operation=op;this.pos=pos;this.action=action;this.item=item;this.approach=approach;this.permit=permit;level=b.level();before=level.getBlockState(pos);started=level.getServer().getTickCount();}
  boolean valid(){return !done&&permit.getAsBoolean()&&body.canAct()&&body.level()==level&&owner.level()==level&&level.getServer().getPlayerList().getPlayer(owner.getUUID())==owner&&MineAgentRuntimeServices.bodies(level.getServer()).body(body.agentId()).orElse(null)==body&&dev.mineagent.runtime.neoforge.task.ServerTaskStart.allowed(owner,body.agentId());}
  void tick(){if(done)return;try{if(!valid())throw new IllegalStateException("AGENT_BLOCK_CONTEXT_CHANGED");if(level.getServer().getTickCount()-started>2400)throw new IllegalStateException("AGENT_BLOCK_TIMEOUT");if(!level.hasChunkAt(pos))throw new IllegalStateException("AGENT_BLOCK_UNLOADED");
   if(phase==0){body.movementController().stop();if(body.getEyePosition().distanceToSqr(Vec3.atCenterOf(pos))>12.25||!visible(body.getEyePosition())){destination=approachPoint();if(approach.equals("teleport")){if(!owner.permissions().hasPermission(net.minecraft.server.permissions.Permissions.COMMANDS_GAMEMASTER))throw new SecurityException("AGENT_TELEPORT_PERMISSION");body.teleportTo(level,destination.x,destination.y,destination.z,Set.of(),body.getYRot(),body.getXRot(),true);}else if(approach.equals("walk")){body.movementController().movePreciselyTo(destination);navigation=body.movementController().commandRevision();}else throw new IllegalArgumentException("AGENT_BLOCK_APPROACH");}phase=1;return;}
   if(phase==1){if(body.getEyePosition().distanceToSqr(Vec3.atCenterOf(pos))>16||!visible(body.getEyePosition())){if(!body.movementController().target().isPresent())throw new IllegalStateException("AGENT_BLOCK_PATH_"+body.movementController().outcome());return;}body.movementController().stop();equip();body.lookAt(net.minecraft.commands.arguments.EntityAnchorArgument.Anchor.EYES,aimPoint(body.getEyePosition()));body.inventoryMenu.broadcastChanges();at=level.getServer().getTickCount();phase=2;return;}
   if(phase==2){body.lookAt(net.minecraft.commands.arguments.EntityAnchorArgument.Anchor.EYES,aimPoint(body.getEyePosition()));held++;if(level.getServer().getTickCount()-at<6)return;if(level.getBlockState(pos)!=before)throw new IllegalStateException("AGENT_BLOCK_TARGET_CHANGED");if(action.equals("place")){var block=net.minecraft.core.registries.BuiltInRegistries.BLOCK.getValue(Identifier.parse(item));if(block==null||block.asItem()==Items.AIR)throw new IllegalArgumentException("AGENT_PLACE_BLOCK_ID");committed=MineAgentRuntimeServices.bodies(level.getServer()).placeBlock(body.agentId(),pos,block);if(!committed)throw new IllegalStateException("AGENT_NATIVE_PLACE_REJECTED");finish("APPLIED","");return;}
    if(action.equals("use")){var hit=level.clip(new net.minecraft.world.level.ClipContext(body.getEyePosition(),aimPoint(body.getEyePosition()),net.minecraft.world.level.ClipContext.Block.OUTLINE,net.minecraft.world.level.ClipContext.Fluid.NONE,body));if(hit.getType()!=HitResult.Type.BLOCK||!hit.getBlockPos().equals(pos))throw new IllegalStateException("AGENT_BLOCK_NOT_VISIBLE");body.lookAt(net.minecraft.commands.arguments.EntityAnchorArgument.Anchor.EYES,hit.getLocation());var used=body.gameMode.useItemOn(body,level,body.getMainHandItem(),InteractionHand.MAIN_HAND,hit);body.swing(InteractionHand.MAIN_HAND,true);committed=used.consumesAction();finish(committed?"APPLIED":"REJECTED",committed?"":"AGENT_NATIVE_USE_REJECTED");return;}
    if(before.isAir()||before.getDestroySpeed(level,pos)<0)throw new IllegalStateException("AGENT_BLOCK_UNBREAKABLE");if(body.hasInfiniteMaterials()){at=level.getServer().getTickCount();phase=3;}else{if(!body.beginMining(pos,operation))throw new IllegalStateException("AGENT_NATIVE_MINE_REJECTED");phase=4;}return;
   }
   if(phase==3){if(level.getBlockState(pos)!=before)throw new IllegalStateException("AGENT_BLOCK_TARGET_CHANGED");int age=level.getServer().getTickCount()-at;body.lookAt(net.minecraft.commands.arguments.EntityAnchorArgument.Anchor.EYES,aimPoint(body.getEyePosition()));if(age%3==0){body.swing(InteractionHand.MAIN_HAND,true);level.destroyBlockProgress(body.getId(),pos,Math.min(9,age/2));cracks++;}if(age>=20){body.beginMining(pos,operation);phase=4;}return;}
   if(phase==4){if(level.getBlockState(pos)!=before){committed=level.getBlockState(pos).isAir();finish(committed?"APPLIED":"PARTIAL",committed?"":"AGENT_BLOCK_CHANGED");return;}var receipt=body.miningReceipt(operation);if(receipt.isPresent())throw new IllegalStateException("AGENT_NATIVE_MINE_"+receipt.get().state());}
  }catch(Exception e){finish(committed?"PARTIAL":"REJECTED",Objects.toString(e.getMessage(),"AGENT_BLOCK_FAILED"));}}
  Vec3 aimPoint(Vec3 eye){if(action.equals("place"))return Vec3.atCenterOf(pos);return level.getBlockState(pos).getShape(level,pos,net.minecraft.world.phys.shapes.CollisionContext.of(body)).toAabbs().stream().map(b->b.move(pos).getCenter()).min(Comparator.comparingDouble(eye::distanceToSqr)).orElse(Vec3.atCenterOf(pos));}
  boolean visible(Vec3 eye){var hit=level.clip(new net.minecraft.world.level.ClipContext(eye,aimPoint(eye),net.minecraft.world.level.ClipContext.Block.OUTLINE,net.minecraft.world.level.ClipContext.Fluid.NONE,body));return hit.getType()==HitResult.Type.MISS||hit.getBlockPos().equals(pos);}
  Vec3 approachPoint(){var choices=new ArrayList<Vec3>();for(int dx=-3;dx<=3;dx++)for(int dz=-3;dz<=3;dz++)for(Vec3 v:NativeSurfaceNavigation.standingPositions(body,pos.getX()+dx,pos.getZ()+dz,body.getY()))if(v.add(0,body.getEyeHeight(),0).distanceToSqr(Vec3.atCenterOf(pos))<=12.25&&visible(v.add(0,body.getEyeHeight(),0)))choices.add(v);return choices.stream().min(Comparator.comparingDouble(body::distanceToSqr)).orElseThrow(()->new IllegalStateException("AGENT_BLOCK_NO_APPROACH"));}
  void equip(){if(item.isBlank()){if(action.equals("place"))throw new IllegalArgumentException("AGENT_PLACE_ITEM_REQUIRED");return;}var id=Identifier.tryParse(item);if(id==null||!net.minecraft.core.registries.BuiltInRegistries.ITEM.containsKey(id))throw new IllegalArgumentException("AGENT_ITEM_UNKNOWN");var wanted=new ItemStack(net.minecraft.core.registries.BuiltInRegistries.ITEM.getValue(id));int slot=body.getInventory().findSlotMatchingItem(wanted);if(slot<0){if(!body.hasInfiniteMaterials())throw new IllegalStateException("AGENT_ITEM_MISSING");body.setItemInHand(InteractionHand.MAIN_HAND,wanted);}else if(slot<9)body.getInventory().setSelectedSlot(slot);else body.getInventory().pickSlot(slot);}
  void finish(String status,String error){if(done)return;done=true;body.abortMiningIfCurrent(operation);level.destroyBlockProgress(body.getId(),pos,-1);if(navigation>0)body.movementController().stopIfCurrent(navigation);body.releaseTaskControl(operation);var out=new LinkedHashMap<String,Object>();out.put("status",status);out.put("error",error);out.put("actor",body.getUUID());out.put("position",List.of(body.getX(),body.getY(),body.getZ()));out.put("pitch",body.getXRot());out.put("mainHand",body.getMainHandItem().toString());out.put("heldTicks",held);out.put("navigation",navigation>0?body.movementController().evidence():Map.of("steps",0));out.put("approachExplanation","Native pathfinding opens traversable wooden doors/gates as it walks. Do not click an already-open door merely to prove traversal; use navigation evidence and observed positions.");out.put("crackFrames",cracks);out.put("before",net.minecraft.commands.arguments.blocks.BlockStateParser.serialize(before));out.put("after",level.hasChunkAt(pos)?net.minecraft.commands.arguments.blocks.BlockStateParser.serialize(level.getBlockState(pos)):"UNLOADED");out.put("elapsedTicks",level.getServer().getTickCount()-started);result.complete(out);}
 }
 @SubscribeEvent public static void tick(net.neoforged.neoforge.event.tick.ServerTickEvent.Post e){var list=JOBS.get(e.getServer());if(list==null)return;for(var job:List.copyOf(list)){job.tick();if(job.done)list.remove(job);}}
 @SubscribeEvent public static void stop(net.neoforged.neoforge.event.server.ServerStoppedEvent e){var list=JOBS.remove(e.getServer());if(list!=null)for(var job:list)job.finish("CANCELLED","SERVER_STOPPED");}
 private NativeAgentBlockActions(){}
}
