package dev.mineagent.runtime.neoforge.ui;

import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.databind.node.*;
import dev.mineagent.runtime.neoforge.*;import dev.mineagent.runtime.neoforge.body.*;import dev.mineagent.runtime.neoforge.content.*;
import net.minecraft.server.MinecraftServer;import net.minecraft.server.level.ServerPlayer;import net.minecraft.core.*;import net.minecraft.world.phys.Vec3;import net.minecraft.world.level.block.*;import net.minecraft.world.level.block.state.properties.*;import net.minecraft.world.level.GameType;
import net.neoforged.bus.api.*;import net.neoforged.fml.common.EventBusSubscriber;import net.neoforged.neoforge.event.tick.ServerTickEvent;
import java.util.*;import java.util.concurrent.*;import java.nio.file.*;

/** Opt-in isolated production-client acceptance. Fixture actions are never claimed as model decisions. */
@EventBusSubscriber(modid="mineagent_runtime")
public final class NativeAcceptanceSmoke {
 public static volatile String phase="BOOT",failure="",visualFailure="";public static volatile boolean done,rigVisualDone,crowdSeen;public static volatile UUID realRig,fixtureRig;public static volatile List<UUID> crowdIds=List.of(),terrainIds=List.of();
 private static final ObjectMapper JSON=new ObjectMapper();private static final List<Object> evidence=new ArrayList<>();private static final List<String> failures=new ArrayList<>();private static final Map<UUID,List<Object>> observed=new LinkedHashMap<>();private static final Map<String,List<Double>> timings=new LinkedHashMap<>();
 private static MinecraftServer server;private static ServerPlayer viewer;private static int started,at,rigStart,created;private static long tickStart;private static UUID rigAgent;private static boolean rigRequested,cancelledMove,cancelledModel,placementsStarted,modelsStarted,plansStarted;private static final List<MineAgentPlayer> crowd=new ArrayList<>();private static final List<Terrain> terrain=new ArrayList<>();private static final List<CompletableFuture<Map<String,Object>>> placements=new ArrayList<>(),plans=new ArrayList<>(),applies=new ArrayList<>();private static final List<UUID> modelAgents=new ArrayList<>();private static final Map<UUID,UUID> conversations=new LinkedHashMap<>();private static final Map<UUID,String> markers=new LinkedHashMap<>();
 public static boolean crowdOnly(){return "crowd".equals(System.getProperty("mineagent.nativeAcceptanceScope"));}
 private static int placeJournalBefore;
 private static final String[] MATERIALS={"cyan_wool","orange_wool","lime_wool","red_wool","yellow_wool","blue_wool","white_wool","purple_wool"};
 private static final class Terrain {final String name;final MineAgentPlayer body;final Vec3 start,target;final boolean pass,sneak;boolean finished,returning;int crouch,backCrouch;final int startTick;Terrain(String n,MineAgentPlayer b,Vec3 a,Vec3 z,boolean pass,boolean sneak){name=n;body=b;start=a;target=z;this.pass=pass;this.sneak=sneak;startTick=server.getTickCount();}}
 public static boolean enabled(){return Boolean.getBoolean("mineagent.nativeAcceptanceSmoke");}
 public static void observe(UUID agent,UUID operation,String tool,Map<String,Object> receipt){if(enabled()&&phase.equals("MODELS"))observed.computeIfAbsent(agent,k->new ArrayList<>()).add(Map.of("operation",operation,"tool",tool,"receipt",receipt));}
 private static void check(boolean ok,String code){if(!ok)failures.add(code);}
 private static void save(String name,Object data)throws Exception{var root=Files.createDirectories(server.getServerDirectory().resolve("native-acceptance"));Files.writeString(root.resolve(name+".json"),JSON.writeValueAsString(data));}
 @SubscribeEvent public static void pre(ServerTickEvent.Pre e){if(enabled())tickStart=System.nanoTime();}
 @SubscribeEvent(priority=EventPriority.LOWEST) public static void post(ServerTickEvent.Post e){if(!enabled()||done)return;server=e.getServer();if(tickStart!=0&&!phase.equals("BOOT"))timings.computeIfAbsent(phase,k->new ArrayList<>()).add((System.nanoTime()-tickStart)/1e6);viewer=server.getPlayerList().getPlayers().stream().filter(p->!(p instanceof MineAgentPlayer)).findFirst().orElse(null);if(viewer==null)return;try{
  if(started==0)started=server.getTickCount();if(server.getTickCount()-started>30000)throw new IllegalStateException("ACCEPTANCE_TIMEOUT_"+phase);
  if(phase.equals("BOOT")){setup();phase=crowdOnly()?"CROWD_CREATE":"RIG_GENERATE";at=server.getTickCount();}
  if(server.getTickCount()%100==0)save("progress",Map.of("phase",phase,"tick",server.getTickCount(),"crowd",crowd.size(),"failures",failures));
  switch(phase){case "RIG_GENERATE"->rig();case "RIG_VIEW"->{if(rigVisualDone||server.getTickCount()-rigStart>500){check(rigVisualDone,"RIG_CLIENT_VISUAL_TIMEOUT");check(visualFailure.isEmpty(),"RIG_VISUAL_"+visualFailure);startTerrain();}}case "TERRAIN"->terrain();case "CROWD_CREATE"->createCrowd();case "CROWD_MOVE"->moveCrowd();case "CROWD_PLACE"->placeCrowd();case "PLANS"->plans();case "MODELS"->models();}
 }catch(Exception error){failure=error.toString();failures.add(failure);try{finish();}catch(Exception ignored){done=true;}}}
 private static void arena(int x0,int z0,int x1,int z1,int height){var level=viewer.level();for(int x=x0;x<=x1;x++)for(int z=z0;z<=z1;z++)for(int y=170;y<=height;y++)level.setBlock(new BlockPos(x,y,z),y==170?Blocks.SMOOTH_STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),2);}
 private static MineAgentPlayer body(String name,Vec3 at)throws Exception{var service=MineAgentRuntimeServices.bodies(server);var id=service.createPersistentAt(name,viewer.getUUID(),viewer.level(),at).agentId();var b=service.body(id).orElseThrow();b.setGameMode(GameType.CREATIVE);b.getAbilities().flying=false;return b;}
 private static void setup()throws Exception{
  if(!WorldIdentityRuntime.ready(server))throw new IllegalStateException("TEST_WORLD_IDENTITY_NOT_READY");server.getPlayerList().op(viewer.nameAndId());viewer.setGameMode(GameType.CREATIVE);server.getCommands().performPrefixedCommand(viewer.createCommandSourceStack(),"ai accept");server.getCommands().performPrefixedCommand(viewer.createCommandSourceStack(),"time set noon");
  for(int cx=-2;cx<=5;cx++)for(int cz=-2;cz<=4;cz++)viewer.level().getChunk(cx,cz);
  arena(-12,-10,14,12,179);arena(-12,17,23,45,177);arena(-2,48,36,68,176);arena(40,46,76,69,174);
  viewer.teleportTo(viewer.level(),.5,171,9.5,Set.of(),180,0,true);viewer.setNoGravity(true);if(crowdOnly()){viewer.teleportTo(viewer.level(),16,182,77,Set.of(),180,36,true);return;}rigAgent=body("骨骼验收",new Vec3(-8.5,171,7.5)).agentId();
  String source;try(var input=NativeAcceptanceSmoke.class.getResourceAsStream("/mineagent/smoke/rig-fixture.json")){if(input==null)throw new IllegalStateException("RIG_FIXTURE_MISSING");source=new String(input.readAllBytes(),java.nio.charset.StandardCharsets.UTF_8);}var species=UUID.randomUUID();RuntimeCreatures.define(viewer,species,JSON.createObjectNode().put("source",source));var spawned=RuntimeCreatures.control(viewer,JSON.createObjectNode().put("action","spawn").put("species_id",species.toString()).set("position",JSON.valueToTree(List.of(3.0,171.0,0.0))));fixtureRig=UUID.fromString(((Map<?,?>)spawned.get("entity")).get("entity_id").toString());((RuntimeCreatureEntity)viewer.level().getEntity(fixtureRig)).setNoAi(true);
 }
 private static void rig()throws Exception{
  if(!rigRequested){rigRequested=true;ServerConversations.get(server).submitNative(viewer,rigAgent,"请实际创建并召唤一个彩色骨骼机器人到(-3,171,0)，供真实画面验收。先读取生物契约，必须使用bones父子骨骼：body、head、arm、forearm，forearm的parent是arm，arm/head的parent是body；父先子后。body不动，idle循环让手臂和头部各自活动。model字段严格按RuntimeMesh契约，不添加type字段；每部分局部坐标，颜色要不同、轮廓容易识别，整体在2x3x2内。只造一个物种和一个实体，不创建网页，不改游戏规则，不执行电脑命令。完成后简短说明。",true);return;}
  var store=ServerConversations.get(server).store();var c=store.list(viewer.getUUID(),rigAgent,"ACTIVE","",0,20).conversations();if(c.isEmpty()||c.getFirst().messageCount()<2||!c.getFirst().activeOperation().isEmpty())return;
  var context=store.context(viewer.getUUID(),rigAgent,c.getFirst().conversationId(),null).orElseThrow();check(context.requestState().equals("COMPLETE"),"RIG_MODEL_"+context.errorCode());save("rig-model-context",context);
  var candidates=new ArrayList<RuntimeCreatureEntity>();for(var entity:viewer.level().getAllEntities())if(entity instanceof RuntimeCreatureEntity creature&&viewer.getUUID().equals(creature.owner())&&!creature.getUUID().equals(fixtureRig))candidates.add(creature);
  check(candidates.size()==1,"RIG_MODEL_ENTITY_COUNT_"+candidates.size());if(!candidates.isEmpty()){var entity=candidates.getFirst();realRig=entity.getUUID();entity.setNoAi(true);var d=entity.definition();check(d.bones().size()>=4,"RIG_MODEL_BONES_MISSING");var parents=new HashMap<String,String>();d.bones().forEach(b->parents.put(b.name(),b.parent()));check(d.bones().stream().anyMatch(b->!b.parent().isEmpty()&&!parents.getOrDefault(b.parent(),"").isEmpty()),"RIG_MODEL_HIERARCHY_MISSING");check(d.animations().containsKey("idle")&&!d.animations().get("idle").bones().isEmpty(),"RIG_MODEL_TRACK_MISSING");save("rig-model-definition",Map.of("source",d.source(),"entity",entity.observation()));}
  phase="RIG_VIEW";rigStart=server.getTickCount();
 }
 private static void startTerrain()throws Exception{
  viewer.teleportTo(viewer.level(),1.5,181,14.5,Set.of(),0,42,true);String[] names={"open_height_difference","slab_stair_carpet","door_gate","low_clearance","impassable_clearance"};
  for(int i=0;i<5;i++){int z=20+i*5;for(int x=-11;x<=22;x++)for(int y=171;y<=176;y++){viewer.level().setBlock(new BlockPos(x,y,z-1),Blocks.GLASS.defaultBlockState(),2);viewer.level().setBlock(new BlockPos(x,y,z+1),Blocks.GLASS.defaultBlockState(),2);if(x==-11||x==22)viewer.level().setBlock(new BlockPos(x,y,z),Blocks.STONE.defaultBlockState(),2);}
   if(i==0){for(int x=0;x<=5;x++)viewer.level().setBlock(new BlockPos(x,171,z),Blocks.STONE.defaultBlockState(),2);}
   if(i==1){viewer.level().setBlock(new BlockPos(-1,171,z),Blocks.STONE_SLAB.defaultBlockState(),2);viewer.level().setBlock(new BlockPos(0,171,z),Blocks.RED_CARPET.defaultBlockState(),2);viewer.level().setBlock(new BlockPos(2,171,z),Blocks.STONE_STAIRS.defaultBlockState().setValue(StairBlock.FACING,Direction.WEST),2);for(int x=3;x<=6;x++)viewer.level().setBlock(new BlockPos(x,171,z),Blocks.STONE.defaultBlockState(),2);viewer.level().setBlock(new BlockPos(7,171,z),Blocks.STONE_SLAB.defaultBlockState(),2);}
   if(i==2){var door=Blocks.OAK_DOOR.defaultBlockState().setValue(DoorBlock.FACING,Direction.EAST);viewer.level().setBlock(new BlockPos(0,171,z),door,2);viewer.level().setBlock(new BlockPos(0,172,z),door.setValue(DoorBlock.HALF,DoubleBlockHalf.UPPER),2);viewer.level().setBlock(new BlockPos(3,171,z),Blocks.OAK_FENCE_GATE.defaultBlockState().setValue(FenceGateBlock.FACING,Direction.EAST),2);}
   if(i>=3)for(int x=-1;x<=4;x++)viewer.level().setBlock(new BlockPos(x,172,z),Blocks.STONE_SLAB.defaultBlockState().setValue(SlabBlock.TYPE,i==3?SlabType.TOP:SlabType.BOTTOM),2);
   var start=new Vec3(-8.5,171,z+.5);var target=new Vec3(12.5,171,z+.5);var b=body("地形"+i,start);terrain.add(new Terrain(names[i],b,start,target,i!=4,i==3));b.movementController().movePreciselyTo(target);
  }terrainIds=terrain.stream().map(t->t.body.agentId()).toList();phase="TERRAIN";at=server.getTickCount();
 }
 private static void terrain()throws Exception{
  for(var t:terrain){if(t.finished)continue;if(t.body.isCrouching()){if(t.returning)t.backCrouch++;else t.crouch++;}
   var movement=t.body.movementController();if(movement.target().isPresent()&&server.getTickCount()-t.startTick<2200)continue;
   if(movement.target().isPresent())movement.stop();boolean reached=movement.outcome().equals("ARRIVED");check(reached==t.pass,"TERRAIN_"+t.name+"_"+(t.returning?"RETURN_":"")+movement.outcome());
   if(t.name.equals("door_gate")&&!t.returning&&reached){check(((Number)movement.evidence().get("openedDoors")).intValue()>0&&((Number)movement.evidence().get("openedGates")).intValue()>0,"DOOR_GATE_NOT_OPENED");}
   if(!t.sneak)check(t.crouch==0&&t.backCrouch==0,"UNNEEDED_CROUCH_"+t.name);else if(reached)check((t.returning?t.backCrouch:t.crouch)>0,"LOW_TUNNEL_NO_CROUCH");
   evidence.add(Map.of("case",t.name,"returning",t.returning,"outcome",movement.outcome(),"position",List.of(t.body.getX(),t.body.getY(),t.body.getZ()),"crouchTicks",t.returning?t.backCrouch:t.crouch,"movement",movement.evidence()));
   if(t.pass&&reached&&!t.returning){t.returning=true;movement.movePreciselyTo(t.start);}else t.finished=true;
  }
  if(terrain.stream().allMatch(t->t.finished)){save("terrain",Map.of("cases",evidence,"failures",failures));phase="CROWD_CREATE";at=server.getTickCount();viewer.teleportTo(viewer.level(),16,180,71,Set.of(),180,30,true);}
 }
 private static void createCrowd()throws Exception{for(int n=0;n<4&&created<64;n++,created++){int i=created;crowd.add(body("并发"+String.format(java.util.Locale.ROOT,"%02d",i),new Vec3((i%8)*2+.5,171,50+(i/8)*2+.5)));}if(created<64)return;crowdIds=crowd.stream().map(MineAgentPlayer::agentId).toList();for(var b:crowd)b.movementController().movePreciselyTo(b.position().add(18,0,0));phase="CROWD_MOVE";at=server.getTickCount();}
 private static void moveCrowd()throws Exception{
  if(!cancelledMove&&server.getTickCount()-at>=60){crowd.getFirst().movementController().stop();cancelledMove=true;}
  if(crowd.stream().skip(1).anyMatch(b->b.movementController().target().isPresent())&&server.getTickCount()-at<1800)return;
  for(int i=0;i<crowd.size();i++){var b=crowd.get(i);check(b.movementController().outcome().equals(i==0?"CANCELLED":"ARRIVED"),"CROWD_MOVE_"+i+"_"+b.movementController().outcome());if(b.movementController().target().isPresent())b.movementController().stop();}
  save("crowd-navigation",crowd.stream().map(b->Map.of("agent",b.agentId(),"name",b.getName().getString(),"position",List.of(b.getX(),b.getY(),b.getZ()),"outcome",b.movementController().outcome(),"evidence",b.movementController().evidence())).toList());phase="CROWD_PLACE";at=server.getTickCount();
 }
 private static void placeCrowd()throws Exception{
  if(!placementsStarted){placementsStarted=true;placeJournalBefore=MineAgentRuntimeServices.changeJournal(server).all().size();for(int i=1;i<64;i++){int x=(i%8)*2+18,z=51+(i/8)*2;var args=JSON.createObjectNode().put("action","place").put("item","minecraft:"+MATERIALS[i%8]).put("approach","walk");args.putArray("position").add(x).add(171).add(z);placements.add(ConversationAgentTools.execute(viewer,crowd.get(i).agentId(),UUID.randomUUID(),"agent_block_action",args.toString(),()->true));}return;}
  if(placements.stream().anyMatch(f->!f.isDone())&&server.getTickCount()-at<2500)return;var results=new ArrayList<Object>();for(int i=1;i<64;i++){var f=placements.get(i-1);Map<String,Object> r=f.isDone()?f.handle((v,e)->e==null?v:Map.<String,Object>of("error",e.toString())).join():Map.of("error","TIMEOUT");boolean placed=net.minecraft.core.registries.BuiltInRegistries.BLOCK.getKey(viewer.level().getBlockState(new BlockPos((i%8)*2+18,171,51+(i/8)*2)).getBlock()).toString().equals("minecraft:"+MATERIALS[i%8]);check(placed&&"APPLIED".equals(r.get("status")),"CROWD_PLACE_"+i);results.add(Map.of("agent",crowd.get(i).agentId(),"receipt",r,"blockVerified",placed));}int recorded=MineAgentRuntimeServices.changeJournal(server).all().size()-placeJournalBefore;check(recorded==63,"CROWD_JOURNAL_COUNT_"+recorded);save("crowd-journal",Map.of("expected",63,"persisted",recorded));save("crowd-placement",results);phase="PLANS";at=server.getTickCount();}
 private static void plans()throws Exception{
  if(!plansStarted){plansStarted=true;for(int i=0;i<16;i++){String source="{\"origin\":["+(42+(i%8)*4)+",171,"+(50+(i/8)*6)+"],\"parts\":[{\"kind\":\"box\",\"min\":[0,0,0],\"max\":[1,1,1],\"material\":\"minecraft:gold_block\"}]}";plans.add(ConversationWorldGeometry.plan(viewer,crowd.get(i).agentId(),JSON.createObjectNode().put("source",source),()->true));}return;}
  if(plans.stream().anyMatch(f->!f.isDone())&&server.getTickCount()-at<1200)return;
  if(applies.isEmpty()){var receipts=new ArrayList<Object>();var unique=new HashSet<String>();for(int i=0;i<16;i++){var f=plans.get(i);var r=f.isDone()?f.handle((v,e)->e==null?v:Map.<String,Object>of("error",e.toString())).join():Map.<String,Object>of("error","TIMEOUT");receipts.add(r);if(r.containsKey("planId")){String id=r.get("planId").toString();check(unique.add(id),"PLAN_ID_COLLISION");applies.add(ConversationAgentTools.execute(viewer,crowd.get(i).agentId(),UUID.randomUUID(),"apply_world_geometry",JSON.createObjectNode().put("plan_id",id).toString(),()->true));}else{failures.add("PARALLEL_PLAN_"+i);applies.add(CompletableFuture.completedFuture(r));}}save("parallel-plans",receipts);return;}
  if(applies.stream().anyMatch(f->!f.isDone())&&server.getTickCount()-at<2400)return;var results=new ArrayList<Object>();for(int i=0;i<16;i++){var f=applies.get(i);var r=f.isDone()?f.handle((v,e)->e==null?v:Map.<String,Object>of("error",e.toString())).join():Map.<String,Object>of("error","TIMEOUT");int gold=0;for(var pos:BlockPos.betweenClosed(new BlockPos(42+(i%8)*4,171,50+(i/8)*6),new BlockPos(43+(i%8)*4,172,51+(i/8)*6)))if(viewer.level().getBlockState(pos).is(Blocks.GOLD_BLOCK))gold++;check(gold==8&&"APPLIED".equals(r.get("status")),"PARALLEL_APPLY_"+i);results.add(Map.of("index",i,"goldBlocks",gold,"receipt",r));}save("parallel-applies",results);if(crowdOnly()){check(crowdSeen,"CLIENT_DID_NOT_OBSERVE_64_AGENTS");finish();return;}phase="MODELS";at=server.getTickCount();}
 private static void models()throws Exception{
  var runtime=ServerConversations.get(server);var store=runtime.store();
  if(!modelsStarted){modelsStarted=true;for(int i=0;i<8;i++){UUID agent=crowd.get(i+8).agentId();modelAgents.add(agent);String marker="CASE_"+String.format(java.util.Locale.ROOT,"%02d",i);markers.put(agent,marker);runtime.submitNative(viewer,agent,i==1?"先读取你自己的身体信息，然后逐行列出从1到500的数字，最后加标记 "+marker+"。不要进行世界写入或电脑命令。":"只调用一次工具读取你自己这个AI的身体位置和主手物品（不是玩家，也不是其它AI），然后用一段简短中文报告结果并附上专用标记 "+marker+"。不改变世界，不移动，不做电脑操作。",true);if(i==0)runtime.submitNative(viewer,agent,"排队的第二条：仅回复QUEUE_SECOND，不调用工具，不改变世界。",true);}return;}
  int active=0;for(UUID id:modelAgents){var list=store.list(viewer.getUUID(),id,"ACTIVE","",0,20).conversations();if(list.isEmpty())continue;var c=list.getFirst();conversations.put(id,c.conversationId());if(!c.activeOperation().isEmpty())active++;}
  if(!cancelledModel&&conversations.containsKey(modelAgents.get(1))){UUID id=modelAgents.get(1);var c=store.get(viewer.getUUID(),id,conversations.get(id));var ctx=store.context(viewer.getUUID(),id,c.conversationId(),null);if(!c.activeOperation().isEmpty()&&ctx.isPresent()&&(store.thinking(viewer.getUUID(),id,c.conversationId(),ctx.get().assistantMessageId()).textLength()>0||server.getTickCount()-at>100)){runtime.interruptNative(viewer,id,"active:"+c.activeOperation());cancelledModel=true;}}
  if((active>0||conversations.size()<8||store.get(viewer.getUUID(),modelAgents.getFirst(),conversations.get(modelAgents.getFirst())).messageCount()<4)&&server.getTickCount()-at<12000)return;
  var results=new ArrayList<Object>();for(int i=0;i<modelAgents.size();i++){UUID id=modelAgents.get(i);if(!conversations.containsKey(id)){failures.add("MODEL_NO_CONVERSATION_"+i);continue;}UUID conversation=conversations.get(id);var messages=store.messages(viewer.getUUID(),id,conversation,0,20).messages();var assistant=messages.stream().filter(m->m.role().equals("ASSISTANT")).toList();var rows=new ArrayList<Object>();for(var m:assistant){var value=new StringBuilder();for(int offset=0;offset<m.textLength();){var chunk=store.chunk(viewer.getUUID(),id,conversation,m.messageId(),m.revision(),offset,4096);value.append(chunk.text());if(chunk.text().isEmpty())throw new IllegalStateException("EMPTY_MESSAGE_CHUNK");offset+=chunk.text().length();}var ctx=store.context(viewer.getUUID(),id,conversation,m.messageId()).orElseThrow();rows.add(Map.of("message",m,"context",ctx,"text",value.toString()));if(i!=1){check(m.status().equals("COMPLETE"),"MODEL_NOT_COMPLETE_"+i);check(ctx.modelReceipt()!=null&&ctx.modelReceipt().requestedModel().equals("deepseek-flash"),"MODEL_RECEIPT_"+i);}if(i!=1&&m==assistant.getFirst())check(value.toString().contains(markers.get(id)),"MODEL_RESULT_ROUTING_"+i);}
   if(i==0){check(assistant.size()==2,"SAME_SESSION_QUEUE_COUNT");if(rows.size()==2)check(((Map<?,?>)rows.get(1)).get("text").toString().contains("QUEUE_SECOND"),"SAME_SESSION_QUEUE_ORDER");}if(i==1)check(cancelledModel&&assistant.stream().anyMatch(m->m.status().equals("CANCELLED")),"SINGLE_REQUEST_CANCEL_NOT_OBSERVED");else check(observed.getOrDefault(id,List.of()).stream().anyMatch(v->((Map<?,?>)v).get("tool").equals("inspect_agent_body")),"OWN_BODY_NOT_READ_"+i);
   results.add(Map.of("agent",id,"expectedMarker",markers.get(id),"conversation",conversation,"responses",rows,"tools",observed.getOrDefault(id,List.of())));
  }save("real-conversations",results);check(crowdSeen,"CLIENT_DID_NOT_OBSERVE_64_AGENTS");finish();
 }
 private static Map<String,Object> stats(List<Double> values){var sorted=new ArrayList<>(values);Collections.sort(sorted);if(sorted.isEmpty())return Map.of();return Map.of("samples",sorted.size(),"medianMs",sorted.get(sorted.size()/2),"p95Ms",sorted.get(Math.min(sorted.size()-1,(int)(sorted.size()*.95))),"maxMs",sorted.getLast());}
 private static void finish()throws Exception{var perf=new LinkedHashMap<String,Object>();timings.forEach((k,v)->perf.put(k,stats(v)));save("server-final",Map.of("status",failures.isEmpty()?"NATIVE_ACCEPTANCE_PASSED":"NATIVE_ACCEPTANCE_FAILED","failures",failures,"crowdAgents",crowd.size(),"modelAgents",modelAgents.size(),"cancelledOneNavigation",cancelledMove,"cancelledOneModel",cancelledModel,"timings",perf));phase="DONE";done=true;}
 private NativeAcceptanceSmoke(){}
}
