package dev.mineagent.runtime.neoforge.ui;
import com.fasterxml.jackson.databind.*;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;
import dev.mineagent.runtime.api.config.ConfigPatch;
import dev.mineagent.runtime.core.config.AgentThinkingSettings;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.network.chat.*;
import java.util.*;
public final class ServerChatSettings {
 private static final ObjectMapper JSON=new ObjectMapper();
 private static String defaultKey(ServerPlayer p){return "chat.default."+MineAgentRuntimeServices.worldId(p.level().getServer())+"."+p.getUUID();}
 public static UUID defaultAgent(ServerPlayer p){String id=MineAgentRuntimeServices.config(p.level().getServer()).snapshot().values().getOrDefault(defaultKey(p),"");if(id.isEmpty())return null;try{UUID agent=UUID.fromString(id);return ServerChatAccess.allowed(p,agent)?agent:null;}catch(Exception e){return null;}}
 public static UUID select(ServerPlayer p,String name){var defs=MineAgentRuntimeServices.bodies(p.level().getServer()).definitions().stream().filter(a->ServerChatAccess.allowed(p,a.agentId())).toList();if(name!=null&&!name.isBlank())return defs.stream().filter(a->a.displayName().equals(name)||a.agentId().toString().equals(name)).findFirst().orElseThrow(()->new IllegalArgumentException("CHAT_AGENT_NOT_FOUND")).agentId();var focus=ServerConversations.get(p.level().getServer()).focused(p).filter(dev.mineagent.runtime.core.conversation.ConversationFocusRegistry.Focus::nativeInput);if(focus.isPresent())return focus.get().agentId();UUID id=defaultAgent(p);if(id!=null)return id;if(defs.size()==1)return defs.getFirst().agentId();throw new IllegalArgumentException("CHAT_SELECT_AGENT_REQUIRED");}
 public static Map<String,Object> inspect(ServerPlayer p,UUID agent){if(MineAgentRuntimeServices.bodies(p.level().getServer()).definitions().stream().noneMatch(a->a.agentId().equals(agent)))throw new SecurityException("CHAT_AGENT_PERMISSION");var server=p.level().getServer();var config=MineAgentRuntimeServices.config(server);var snap=config.snapshot();UUID fallback=defaultAgent(p);return Map.of("agentId",agent,"thinkingDepth",AgentThinkingSettings.read(snap.values(),MineAgentRuntimeServices.worldId(server),agent),"thinkingLevels",List.of("off","low","high","max"),"depthScope","current Agent; currently sent to official DeepSeek, other Providers manage their own parameters","defaultAgent",fallback==null?"":fallback.toString(),"defaultReplyEnabled",fallback!=null,"nativeThinkingDisplay","client local setting; F2 history unaffected","revision",snap.revision());}
 public static Map<String,Object> set(ServerPlayer p,UUID agent,JsonNode args)throws Exception{inspect(p,agent);if(args.has("show_thinking")&&!args.get("show_thinking").isBoolean()||args.has("default_reply")&&!args.get("default_reply").isBoolean())throw new IllegalArgumentException("CHAT_SETTING_BOOLEAN");if(args.path("default_reply").asBoolean()&&(!args.path("response_agent").isTextual()||args.path("response_agent").asText().isBlank()))throw new IllegalArgumentException("CHAT_RESPONSE_AGENT_REQUIRED");var server=p.level().getServer();if(args.has("thinking_depth")&&MineAgentRuntimeServices.bodies(server).definitions().stream().noneMatch(a->a.agentId().equals(agent)&&a.ownerPlayerId().equals(p.getUUID())))throw new SecurityException("THINKING_OWNER_REQUIRED");var config=MineAgentRuntimeServices.config(server);var patch=new LinkedHashMap<String,String>();if(args.has("thinking_depth")){String level=args.path("thinking_depth").asText();if(level.equals("medium"))level="high";if(!AgentThinkingSettings.LEVELS.contains(level))throw new IllegalArgumentException("THINKING_LEVEL_INVALID");patch.put(AgentThinkingSettings.key(MineAgentRuntimeServices.worldId(server),agent),level);}if(args.has("default_reply")){if(!args.get("default_reply").isBoolean())throw new IllegalArgumentException("CHAT_SETTING_BOOLEAN");UUID target=args.path("default_reply").asBoolean()?select(p,args.path("response_agent").asText(agent.toString())):null;patch.put(defaultKey(p),target==null?"":target.toString());}if(!patch.isEmpty()){var r=config.apply(new ConfigPatch(config.snapshot().revision(),patch),true);if(!r.accepted())throw new IllegalStateException(r.errorCode());}if(args.has("default_reply")){UUID target=defaultAgent(p);var focus=ServerConversations.get(server).focused(p);if(target==null||focus.isPresent()&&!focus.get().agentId().equals(target))ServerConversations.get(server).disableNativeRoute(p);}if(args.has("show_thinking")){if(!args.get("show_thinking").isBoolean())throw new IllegalArgumentException("CHAT_SETTING_BOOLEAN");sendDisplay(p,args.path("show_thinking").asBoolean()?"on":"off");}return Map.of("status","APPLIED","settings",inspect(p,agent),"displayChangeSent",args.has("show_thinking"),"takesEffect","next request; never replay an in-flight request");}
 public static void sendDisplay(ServerPlayer p,String mode){if(!Set.of("on","off","toggle").contains(mode))throw new IllegalArgumentException("THINKING_DISPLAY_MODE");net.neoforged.neoforge.network.PacketDistributor.sendToPlayer(p,new dev.mineagent.runtime.neoforge.network.UiPayloads.Event(UUID.randomUUID(),"nativeThinkingSetting","{\"mode\":\""+mode+"\"}"));}
 public static int depth(ServerPlayer p,String level,String name){try{UUID agent=select(p,name);set(p,agent,JSON.createObjectNode().put("thinking_depth",level));p.sendSystemMessage(Component.literal("思考深度已设置："+level+"（下次请求生效）"));return 1;}catch(Exception e){p.sendSystemMessage(Component.literal("未设置："+e.getMessage()));return 0;}}
 public static int defaultReply(ServerPlayer p,String name){try{UUID target=name.equals("off")?null:select(p,name);var cfg=MineAgentRuntimeServices.config(p.level().getServer());var r=cfg.apply(new ConfigPatch(cfg.snapshot().revision(),Map.of(defaultKey(p),target==null?"":target.toString())),true);if(!r.accepted())throw new IllegalStateException(r.errorCode());var focus=ServerConversations.get(p.level().getServer()).focused(p);if(target==null||focus.isPresent()&&!focus.get().agentId().equals(target))ServerConversations.get(p.level().getServer()).disableNativeRoute(p);p.sendSystemMessage(Component.literal(target==null?"默认对话已关闭":"默认对话已启用："+MineAgentRuntimeServices.bodies(p.level().getServer()).definitions().stream().filter(a->a.agentId().equals(target)).findFirst().orElseThrow().displayName()));return 1;}catch(Exception e){p.sendSystemMessage(Component.literal("未设置："+e.getMessage()));return 0;}}
 public static int menu(ServerPlayer p,String kind){var text=Component.literal(kind.equals("deep")?"思考深度： ":"默认响应 AI： ");if(kind.equals("deep")){for(String level:List.of("off","low","high","max"))text.append(Component.literal("["+level+"] ").withStyle(s->s.withColor(net.minecraft.ChatFormatting.AQUA).withClickEvent(new ClickEvent.RunCommand("/ai thinking deep "+level))));}else{for(var a:MineAgentRuntimeServices.bodies(p.level().getServer()).definitions())if(ServerChatAccess.allowed(p,a.agentId()))text.append(Component.literal("["+a.displayName()+"] ").withStyle(s->s.withColor(net.minecraft.ChatFormatting.AQUA).withClickEvent(new ClickEvent.RunCommand("/ai default "+a.agentId()))));text.append(Component.literal("[关闭]").withStyle(s->s.withClickEvent(new ClickEvent.RunCommand("/ai default off"))));}p.sendSystemMessage(text);return 1;}
 private ServerChatSettings(){}
}
