package dev.mineagent.runtime.neoforge.ui;
import com.fasterxml.jackson.databind.JsonNode;import dev.mineagent.runtime.core.files.FileLibrary;import net.minecraft.server.level.ServerPlayer;import java.nio.file.*;import java.nio.charset.*;import java.io.*;import java.util.*;import java.util.concurrent.*;import java.util.function.BooleanSupplier;
/** Generic attachment library. Building, skin and preview adapters consume the same immutable files. */
public final class ServerFileTools {
 private static final ExecutorService IO=java.util.concurrent.Executors.newVirtualThreadPerTaskExecutor();
 private static String text(JsonNode a,String k,int max){if(!a.path(k).isTextual()||a.get(k).asText().length()>max)throw new IllegalArgumentException("FILES_ARGUMENTS");return a.get(k).asText();}
 private static UUID id(JsonNode a){return UUID.fromString(text(a,"file_id",36));}
 private static long offset(JsonNode a){if(!a.has("offset"))return 0;if(!a.get("offset").isIntegralNumber()||!a.get("offset").canConvertToLong()||a.get("offset").longValue()<0)throw new IllegalArgumentException("FILES_OFFSET");return a.get("offset").longValue();}
 private static Map<String,Object> summary(FileLibrary.Asset a){return Map.of("id",a.id(),"name",a.name(),"kind",a.kind(),"bytes",a.bytes(),"sha256",a.sha256(),"created",a.created());}
 public static CompletableFuture<Map<String,Object>> read(ServerPlayer p,UUID agent,String tool,JsonNode a){UUID owner=p.getUUID();return ServerBuildingFiles.library(p,agent).thenApplyAsync(library->{try{
  if(tool.equals("inspect_files")&&!a.has("file_id")){var page=library.list(owner,a.path("query").asText(""),Math.toIntExact(offset(a)));var out=new LinkedHashMap<String,Object>(page);@SuppressWarnings("unchecked") var files=(List<FileLibrary.Asset>)page.get("files");out.put("files",files.stream().map(ServerFileTools::summary).toList());out.put("capabilities",List.of("request_files opens shared F2 file upload/download","read_file: UTF-8 text or base64 byte pages","write_file: generated data only, no execution","offer_file_download: clickable native-chat download entry","building/skin/preview adapters use file_id"));return out;}
  UUID id=id(a);var asset=library.asset(owner,id);String entry=a.path("entry").asText("");if(tool.equals("inspect_files")){var out=new LinkedHashMap<String,Object>(summary(asset));out.put("source",asset.source());if(!asset.kind().equals("FILE")){Path root=library.data(owner,id);List<Path> entries;try(var walk=Files.walk(root)){entries=walk.filter(f->Files.isRegularFile(f,LinkOption.NOFOLLOW_LINKS)&&!Files.isSymbolicLink(f)).sorted().toList();}int off=Math.toIntExact(offset(a));if(off>entries.size())throw new IllegalArgumentException("FILES_OFFSET");var rows=new ArrayList<Object>();for(var file:entries.subList(off,Math.min(off+32,entries.size())))rows.add(Map.of("entry",root.relativize(file).toString().replace('\\','/'),"bytes",Files.size(file)));out.put("entries",rows);out.put("totalEntries",entries.size());out.put("nextOffset",off+32<entries.size()?off+32:-1);}out.put("untrustedContent",true);return out;}
  Path file=library.file(owner,id,entry);long start=offset(a);String encoding=a.path("encoding").asText("utf-8");String content;long next;
  if(encoding.equals("base64")){try(var f=new RandomAccessFile(file.toFile(),"r")){if(start>f.length())throw new IllegalArgumentException("FILES_OFFSET");f.seek(start);byte[] b=new byte[(int)Math.min(6000,f.length()-start)];f.readFully(b);content=Base64.getEncoder().encodeToString(b);next=start+b.length<f.length()?start+b.length:-1;}}
  else if(encoding.equals("utf-8")){try(var r=Files.newBufferedReader(file,StandardCharsets.UTF_8)){long remaining=start;while(remaining>0){long n=r.skip(remaining);if(n==0){if(r.read()<0)throw new IllegalArgumentException("FILES_OFFSET");n=1;}remaining-=n;}char[] b=new char[8001];int n=0;while(n<b.length){int got=r.read(b,n,b.length-n);if(got<0)break;n+=got;}int length=Math.min(n,8000);if(length>0&&Character.isHighSurrogate(b[length-1]))length--;content=new String(b,0,length);if(content.indexOf('\0')>=0)throw new IllegalArgumentException("FILES_BINARY_USE_BASE64");next=n>length?start+length:-1;}}
  else throw new IllegalArgumentException("FILES_ENCODING");return Map.of("file",summary(asset),"entry",entry,"encoding",encoding,"offset",start,"nextOffset",next,"content",content,"untrustedContent",true);
 }catch(Exception e){throw new CompletionException(e);}},IO).exceptionally(e->Map.of("status","REJECTED","error",code(e)));}
 public static CompletableFuture<Map<String,Object>> write(ServerPlayer p,UUID agent,UUID operation,JsonNode a,BooleanSupplier permit){UUID owner=p.getUUID();return ServerBuildingFiles.library(p,agent).thenApplyAsync(library->{UUID upload=null;try{if(!permit.getAsBoolean())throw new IllegalStateException("FILES_CONTEXT_CHANGED");String name=text(a,"name",240),encoding=a.path("encoding").asText("utf-8"),content=text(a,"content",12000);FileLibrary.safeRelative(name);if(name.contains("/"))throw new IllegalArgumentException("FILES_NAME");byte[] bytes=encoding.equals("utf-8")?content.getBytes(StandardCharsets.UTF_8):encoding.equals("base64")?Base64.getDecoder().decode(content):null;if(bytes==null)throw new IllegalArgumentException("FILES_ENCODING");upload=library.begin(owner,name,"FILE");var part=library.beginFile(owner,upload,name,bytes.length);if(bytes.length>0)library.chunk(owner,upload,part,0,bytes);if(!permit.getAsBoolean())throw new IllegalStateException("FILES_CONTEXT_CHANGED");var result=library.finish(owner,upload,"AI_GENERATED:"+agent+":"+operation);return Map.<String,Object>of("status","CREATED","file",summary(result),"executed",false);}catch(Exception e){if(upload!=null)try{library.cancel(owner,upload);}catch(Exception ignored){}return Map.<String,Object>of("status","REJECTED","error",code(e));}},IO);}
 public static CompletableFuture<Map<String,Object>> offer(ServerPlayer p,UUID agent,JsonNode a,BooleanSupplier permit){UUID owner=p.getUUID();return ServerBuildingFiles.library(p,agent).thenApplyAsync(library->{try{return library.asset(owner,id(a));}catch(Exception e){throw new CompletionException(e);}},IO).thenCompose(file->{var result=new CompletableFuture<Map<String,Object>>();p.level().getServer().execute(()->{if(!permit.getAsBoolean()||p.level().getServer().getPlayerList().getPlayer(owner)!=p){result.complete(Map.of("status","REJECTED","error","FILES_CONTEXT_CHANGED"));return;}p.sendSystemMessage(net.minecraft.network.chat.Component.literal("[下载 "+file.name()+"]").withStyle(s->s.withColor(net.minecraft.ChatFormatting.AQUA).withUnderlined(true).withClickEvent(new net.minecraft.network.chat.ClickEvent.RunCommand("/ai files "+agent+" "+file.id()))));result.complete(Map.of("status","DOWNLOAD_ENTRY_SENT","file",summary(file)));});return result;});}
 private static String code(Throwable e){String result="FILES_FAILED";for(Throwable c=e;c!=null;c=c.getCause())if(c.getMessage()!=null&&c.getMessage().matches("(?:FILES|BUILDING)_[A-Z_0-9]+"))result=c.getMessage();return result;}
 private ServerFileTools(){}
}
