package dev.mineagent.runtime.neoforge.ui;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;
import dev.mineagent.runtime.core.config.*;
import dev.mineagent.runtime.api.permission.PermissionAction;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.server.permissions.Permissions;
import java.util.*;
public final class ServerAgentModels {
 private ServerAgentModels(){}
 public static boolean permitted(ServerPlayer p,UUID agent){var s=p.level().getServer();boolean op=p.permissions().hasPermission(Permissions.COMMANDS_GAMEMASTER);return !(p instanceof dev.mineagent.runtime.neoforge.body.MineAgentPlayer)&&MineAgentRuntimeServices.bodies(s).definitions().stream().anyMatch(a->a.agentId().equals(agent)&&(a.ownerPlayerId().equals(p.getUUID())||op))&&MineAgentRuntimeServices.permissions(s).allowed(p.getUUID(),op,PermissionAction.MANAGE_PROVIDERS);}
 public static void authorize(ServerPlayer p,Map<String,String> args){if(!p.level().getServer().isSameThread()||!permitted(p,UUID.fromString(args.get("agentId"))))throw new SecurityException("AGENT_MODEL_FORBIDDEN");}
 public static Map<String,Object> read(ServerPlayer p,UUID agent){authorize(p,Map.of("agentId",agent.toString()));var s=p.level().getServer();var values=MineAgentRuntimeServices.config(s).snapshot();var c=AgentModelSettings.read(values.values(),MineAgentRuntimeServices.worldId(s),agent);var a=MineAgentRuntimeServices.bodies(s).definitions().stream().filter(v->v.agentId().equals(agent)).findFirst().orElseThrow();String url=values.values().getOrDefault("provider.openai.baseUrl","");String global=String.valueOf(WebSettingsCatalog.routing(values).get("textModel"));boolean configured=WebSettingsCatalog.safeUrl(url)&&Boolean.parseBoolean(values.values().getOrDefault("provider.openai.enabled","true"));var result=new LinkedHashMap<String,Object>();result.put("agentId",agent);result.put("name",a.displayName());result.put("mode",c.mode());result.put("model",c.model());result.put("revision",c.revision());result.put("defaultModel",global);result.put("effectiveModel",c.mode().equals("DEFAULT")?global:c.model());result.put("baseUrl",configured?AgentModelSettings.origin(url):"");result.put("apiConfigured",configured);result.put("bindingValid",c.mode().equals("DEFAULT")||configured&&c.baseUrl().equals(AgentModelSettings.origin(url)));result.put("provider",c.mode().equals("DEFAULT")?WebSettingsCatalog.routing(values).get("textProvider"):"openai-compatible");return result;}
 public static Map<String,Object> save(ServerPlayer p,Map<String,String> args)throws Exception{authorize(p,args);if(!args.keySet().equals(Set.of("agentId","expectedRevision","mode","model","baseUrl")))throw new IllegalArgumentException("AGENT_MODEL_ARGUMENTS");var s=p.level().getServer();AgentModelSettings.save(MineAgentRuntimeServices.config(s),MineAgentRuntimeServices.worldId(s),UUID.fromString(args.get("agentId")),Long.parseLong(args.get("expectedRevision")),args.get("mode"),args.get("model"),args.get("baseUrl"));return read(p,UUID.fromString(args.get("agentId")));}
}
