package dev.mineagent.runtime.neoforge.ui;
import com.fasterxml.jackson.databind.*;import com.mojang.authlib.*;import com.mojang.authlib.properties.*;import com.google.common.collect.ImmutableMultimap;
import dev.mineagent.runtime.core.agent.SkinImage;import dev.mineagent.runtime.core.files.FileLibrary;import dev.mineagent.runtime.api.config.ConfigPatch;import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;import dev.mineagent.runtime.neoforge.body.MineAgentPlayer;import dev.mineagent.runtime.neoforge.network.*;
import net.minecraft.server.MinecraftServer;import net.minecraft.server.level.ServerPlayer;import net.minecraft.network.protocol.game.*;import net.neoforged.bus.api.SubscribeEvent;import net.neoforged.fml.common.EventBusSubscriber;import net.neoforged.neoforge.network.PacketDistributor;
import java.nio.file.*;import java.util.*;import java.util.concurrent.*;import java.util.function.BooleanSupplier;
@EventBusSubscriber(modid="mineagent_runtime")
public final class ServerAgentSkins {
 private static final ObjectMapper JSON=new ObjectMapper();private static final ExecutorService IO=Executors.newFixedThreadPool(2,r->{var t=new Thread(r,"mineagent-png-skins");t.setDaemon(true);return t;});
 private record Skin(UUID file,UUID owner,String model,String hash,long revision,byte[] png){}
 private static final Map<MinecraftServer,Map<UUID,Skin>> CACHE=new WeakHashMap<>();private static final Map<ServerPlayer,Map<UUID,String>> SENT=new IdentityHashMap<>();private record LoadKey(MinecraftServer server,UUID agent){}private static final Set<LoadKey> LOADING=new HashSet<>();private static final Set<MinecraftServer> STOPPED=Collections.newSetFromMap(new WeakHashMap<>());
 private static String pre(UUID agent){return "agent."+agent+".";}
 private static void authorize(ServerPlayer p,UUID id){var def=MineAgentRuntimeServices.bodies(p.level().getServer()).definitions().stream().filter(a->a.agentId().equals(id)).findFirst().orElseThrow();if(!dev.mineagent.runtime.core.agent.AgentPersonaService.mayEdit(def,p.getUUID(),false))throw new IllegalArgumentException("SKIN_OWNER_REQUIRED");}
 private static byte[] png(FileLibrary files,UUID owner,UUID file)throws Exception{Path path=files.file(owner,file,"");if(!Files.isRegularFile(path)||Files.size(path)>262144)throw new IllegalArgumentException("SKIN_FILE_SIZE");try(var in=Files.newInputStream(path)){return SkinImage.normalize(in.readNBytes(262145));}}
 public static Map<String,Object> inspect(ServerPlayer p,UUID agent){authorize(p,agent);var s=p.level().getServer();var v=MineAgentRuntimeServices.config(s).snapshot().values();String k=pre(agent);return Map.of("agentId",agent,"revision",Long.parseLong(v.getOrDefault(k+"skinRevision","0")),"selection",v.getOrDefault(k+"vanillaSkin",""),"fileId",v.getOrDefault(k+"skinPngFile",""),"models",List.of("wide","slim"),"format","PNG 64x64 or classic64x32; classic is expanded to64x64; standard base layers stay opaque","regions",SkinImage.regions(v.getOrDefault(k+"skinPngModel","wide")),"generator","create_skin_png writes pixel-art PNG using named part rects; base_file_id edits a selected PNG, otherwise a new skin. Model=wide/slim, rect color=#RRGGBB or #AARRGGBB; x/y/width/height relative to part, omit to fill whole part.","identity","Hot appearance only: preserve server AI instance, UUID/name, task/goal state; no logout/recreate.");}
 public static CompletableFuture<Map<String,Object>> uiRead(ServerPlayer p,UUID agent,String query,int offset){var view=inspect(p,agent);UUID owner=p.getUUID();return ServerBuildingFiles.library(p,agent).thenApplyAsync(files->{try{var out=new LinkedHashMap<String,Object>(view);out.put("files",files.list(owner,query,offset));out.put("presets",dev.mineagent.runtime.core.agent.BuiltinAgentSkins.catalog());return out;}catch(Exception e){throw new CompletionException(e);}},IO);}
 public static Map<String,Object> openUi(ServerPlayer p,UUID agent){authorize(p,agent);PacketDistributor.sendToPlayer(p,new UiPayloads.Event(UUID.randomUUID(),"skinUiOpen","{\"agentId\":\""+agent+"\"}"));return Map.of("status","SKIN_UI_OPENED","agentId",agent);}
 public static CompletableFuture<Map<String,Object>> exportCurrent(ServerPlayer p,UUID agent,UUID operation,BooleanSupplier permit){authorize(p,agent);UUID owner=p.getUUID();return ServerBuildingFiles.library(p,agent).thenCompose(files->dev.mineagent.runtime.neoforge.client.AgentSkinSource.capture(agent).thenApplyAsync(image->{UUID upload=null;try{if(!permit.getAsBoolean())throw new IllegalStateException("SKIN_CONTEXT_CHANGED");byte[] bytes=image.png();upload=files.begin(owner,"current-ai-skin.png","FILE");UUID part=files.beginFile(owner,upload,"current-ai-skin.png",bytes.length);files.chunk(owner,upload,part,0,bytes);var asset=files.finish(owner,upload,"CURRENT_AI_SKIN:"+agent+":"+operation);return Map.<String,Object>of("status","CURRENT_SKIN_EXPORTED","file",asset,"model",image.model(),"identityChanged",false);}catch(Exception e){if(upload!=null)try{files.cancel(owner,upload);}catch(Exception ignored){}throw new CompletionException(e);}},IO));}
 public static CompletableFuture<Map<String,Object>> create(ServerPlayer p,UUID agent,UUID operation,JsonNode a,BooleanSupplier permit){authorize(p,agent);UUID owner=p.getUUID();String model=a.path("model").asText("wide");return ServerBuildingFiles.library(p,agent).thenApplyAsync(files->{UUID upload=null;try{byte[] base=a.has("base_file_id")?png(files,owner,UUID.fromString(a.path("base_file_id").asText())):null;byte[] image=SkinImage.paint(base,model,a);if(!permit.getAsBoolean())throw new IllegalStateException("SKIN_CONTEXT_CHANGED");String name=a.path("name").asText("ai-skin.png");if(!name.toLowerCase(Locale.ROOT).endsWith(".png"))throw new IllegalArgumentException("SKIN_PNG_NAME");upload=files.begin(owner,name,"FILE");UUID part=files.beginFile(owner,upload,name,image.length);files.chunk(owner,upload,part,0,image);var file=files.finish(owner,upload,"AI_SKIN:"+agent+":"+operation);return Map.<String,Object>of("status","PNG_CREATED","file",file,"model",model,"size",List.of(64,64),"applied",false);}catch(Exception e){if(upload!=null)try{files.cancel(owner,upload);}catch(Exception ignored){}throw new CompletionException(e);}},IO);}
 public static CompletableFuture<Map<String,Object>> apply(ServerPlayer p,UUID agent,UUID operation,JsonNode a,BooleanSupplier permit){authorize(p,agent);UUID owner=p.getUUID(),file=UUID.fromString(a.path("file_id").asText());String model=a.path("model").asText("wide");if(!Set.of("wide","slim").contains(model)||!a.path("expected_revision").isIntegralNumber())throw new IllegalArgumentException("SKIN_ARGUMENTS");long expected=a.path("expected_revision").asLong();var server=p.level().getServer();var level=p.level();return ServerBuildingFiles.library(p,agent).thenApplyAsync(files->{try{return png(files,owner,file);}catch(Exception e){throw new CompletionException(e);}},IO).thenCompose(bytes->{var result=new CompletableFuture<Map<String,Object>>();server.execute(()->{try{
  if(!permit.getAsBoolean()||p.level()!=level||server.getPlayerList().getPlayer(owner)!=p)throw new IllegalStateException("SKIN_CONTEXT_CHANGED");authorize(p,agent);var config=MineAgentRuntimeServices.config(server);String prefix=pre(agent);if(Long.parseLong(config.snapshot().values().getOrDefault(prefix+"skinRevision","0"))!=expected)throw new IllegalStateException("SKIN_REVISION_CHANGED");
  var bridge=new dev.mineagent.runtime.neoforge.integration.NeoForgeYsmRuntimeBridge(server);if(bridge.runtimeAvailable()){var ysm=MineAgentNetwork.readAppearanceFromUi(p,agent);if(!bridge.availableModels().contains("default"))throw new IllegalStateException("SKIN_YSM_DEFAULT_UNAVAILABLE");var restored=MineAgentNetwork.applyAppearanceFromUi(new MineAgentPayloads.AppearanceCommand(agent.toString(),"default","","",((Number)ysm.get("revision")).longValue(),operation.toString()),p);if(!restored.accepted())throw new IllegalStateException("SKIN_YSM_RESET_FAILED");}
  String hash=dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer.sha256(bytes);long revision=Math.addExact(expected,1);var current=config.snapshot();var patch=Map.of(prefix+"vanillaSkin","png:"+model,prefix+"skinPngFile",file.toString(),prefix+"skinPngOwner",owner.toString(),prefix+"skinPngModel",model,prefix+"skinPngHash",hash,prefix+"skinPlayer",owner.toString(),prefix+"skinWorld",MineAgentRuntimeServices.worldId(server).toString(),prefix+"skinRevision",Long.toString(revision));if(!config.apply(new ConfigPatch(current.revision(),patch),true).accepted())throw new IllegalStateException("SKIN_CONFIG_CHANGED");var skin=new Skin(file,owner,model,hash,revision,bytes);CACHE.computeIfAbsent(server,k->new HashMap<>()).put(agent,skin);var body=MineAgentRuntimeServices.bodies(server).body(agent).orElse(null);String name=body==null?"":body.getGameProfile().name();int entityId=body==null?-1:body.getId();long ticks=body==null?-1:body.nativeTicks();broadcast(server,agent,skin);if(body!=null)refresh(server,body,skin);ConversationIdentityTools.broadcast(server);
  result.complete(Map.of("status",body==null?"CONFIGURED_BODY_NOT_LOADED":"APPLIED","fileId",file,"sha256",hash,"revision",revision,"identity",Map.of("uuid",agent,"profileName",name,"entityId",entityId,"nativeTicks",ticks,"sameServerInstance",body==null||MineAgentRuntimeServices.bodies(server).body(agent).orElse(null)==body),"renderConfirmation","CLIENT_NATIVE_TEXTURE_PENDING"));
 }catch(Exception e){result.completeExceptionally(e);}});return result;});}
 private static void broadcast(MinecraftServer server,UUID agent,Skin skin){for(var viewer:server.getPlayerList().getPlayers())if(!(viewer instanceof MineAgentPlayer)){var sent=SENT.computeIfAbsent(viewer,k->new HashMap<>());String stamp=skin.hash+":"+skin.revision;if(!stamp.equals(sent.get(agent))){PacketDistributor.sendToPlayer(viewer,new AgentPngSkinPayload(agent,skin.hash,skin.model,skin.revision,skin.png));sent.put(agent,stamp);}}}
 private static void refresh(MinecraftServer server,MineAgentPlayer body,Skin skin)throws Exception{
  GameProfile old=body.getGameProfile();var props=ImmutableMultimap.<String,Property>builder();for(var entry:old.properties().entries())if(!entry.getKey().equals("textures"))props.put(entry.getKey(),entry.getValue());String data=JSON.writeValueAsString(Map.of("profileId",old.id().toString().replace("-",""),"profileName",old.name(),"textures",Map.of("SKIN",Map.of("url","mineagent:skin/"+skin.hash,"metadata",Map.of("model",skin.model.equals("slim")?"slim":"default")))));props.put("textures",new Property("textures",Base64.getEncoder().encodeToString(data.getBytes(java.nio.charset.StandardCharsets.UTF_8))));body.updateVisualProfile(new GameProfile(old.id(),old.name(),new PropertyMap(props.build())));
  refreshObservers(server,body);
 }
 private static void refreshObservers(MinecraftServer server,MineAgentPlayer body){
  var remove=new ClientboundPlayerInfoRemovePacket(List.of(body.getUUID()));var info=ClientboundPlayerInfoUpdatePacket.createPlayerInitializing(List.of(body));for(var viewer:server.getPlayerList().getPlayers())if(!(viewer instanceof MineAgentPlayer)){viewer.connection.send(remove);viewer.connection.send(info);}
  var chunkMap=body.level().getChunkSource().chunkMap;Object tracked=((dev.mineagent.runtime.neoforge.mixin.AgentEntityTrackerAccess)chunkMap).mineagent$entityMap().get(body.getId());if(tracked!=null){var tracker=((dev.mineagent.runtime.neoforge.mixin.AgentTrackedEntityAccess)tracked).mineagent$serverEntity();for(var viewer:chunkMap.getPlayersWatching(body)){tracker.removePairing(viewer);tracker.addPairing(viewer);}}
 }
 @SubscribeEvent public static void tick(net.neoforged.neoforge.event.tick.ServerTickEvent.Post e){var server=e.getServer();if(server.getTickCount()%40!=0||!dev.mineagent.runtime.neoforge.WorldIdentityRuntime.ready(server))return;SENT.keySet().removeIf(p->p.level().getServer()==server&&server.getPlayerList().getPlayer(p.getUUID())!=p);var cfg=MineAgentRuntimeServices.config(server).snapshot().values();for(var def:MineAgentRuntimeServices.bodies(server).definitions()){String prefix=pre(def.agentId());if(!cfg.getOrDefault(prefix+"vanillaSkin","").startsWith("png:")||!MineAgentRuntimeServices.worldId(server).toString().equals(cfg.get(prefix+"skinWorld")))continue;Skin cached=CACHE.computeIfAbsent(server,k->new HashMap<>()).get(def.agentId());if(cached!=null&&cached.revision!=Long.parseLong(cfg.getOrDefault(prefix+"skinRevision","0"))){CACHE.get(server).remove(def.agentId());cached=null;}if(cached!=null){broadcast(server,def.agentId(),cached);var body=MineAgentRuntimeServices.bodies(server).body(def.agentId()).orElse(null);if(body!=null&&!body.hasVisualProfile())try{refresh(server,body,cached);}catch(Exception ignored){}continue;}
  var key=new LoadKey(server,def.agentId());if(!LOADING.add(key))continue;try{UUID owner=UUID.fromString(cfg.get(prefix+"skinPngOwner")),file=UUID.fromString(cfg.get(prefix+"skinPngFile"));var player=server.getPlayerList().getPlayer(owner);if(player==null){LOADING.remove(key);continue;}ServerBuildingFiles.library(player,def.agentId()).thenApplyAsync(files->{try{byte[] image=png(files,owner,file);return new Skin(file,owner,cfg.getOrDefault(prefix+"skinPngModel","wide"),dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer.sha256(image),Long.parseLong(cfg.getOrDefault(prefix+"skinRevision","0")),image);}catch(Exception ex){throw new CompletionException(ex);}},IO).whenComplete((skin,error)->server.execute(()->{LOADING.remove(key);if(error==null&&!STOPPED.contains(server)&&dev.mineagent.runtime.neoforge.WorldIdentityRuntime.ready(server)){var latest=MineAgentRuntimeServices.config(server).snapshot().values();if(latest.getOrDefault(prefix+"vanillaSkin","").startsWith("png:")&&latest.getOrDefault(prefix+"skinPngFile","").equals(file.toString())&&Long.parseLong(latest.getOrDefault(prefix+"skinRevision","0"))==skin.revision)CACHE.computeIfAbsent(server,k->new HashMap<>()).put(def.agentId(),skin);}}));}catch(Exception invalid){LOADING.remove(key);}}
 }
 @SubscribeEvent public static void stop(net.neoforged.neoforge.event.server.ServerStoppedEvent e){STOPPED.add(e.getServer());LOADING.removeIf(k->k.server==e.getServer());CACHE.remove(e.getServer());SENT.keySet().removeIf(p->p.level().getServer()==e.getServer());}
 public static void reconcileProfiles(MinecraftServer server){
  var values=MineAgentRuntimeServices.config(server).snapshot().values();String world=MineAgentRuntimeServices.worldId(server).toString();
  for(var def:MineAgentRuntimeServices.bodies(server).definitions()){String prefix=pre(def.agentId());if(values.getOrDefault(prefix+"vanillaSkin","").startsWith("png:")&&world.equals(values.get(prefix+"skinWorld")))continue;var body=MineAgentRuntimeServices.bodies(server).body(def.agentId()).orElse(null);if(body!=null&&body.hasVisualProfile()){body.resetVisualProfile();refreshObservers(server,body);}var cache=CACHE.get(server);if(cache!=null)cache.remove(def.agentId());}
 }
 private ServerAgentSkins(){}
}
