package dev.mineagent.runtime.neoforge.ui;
import com.fasterxml.jackson.databind.ObjectMapper;import dev.mineagent.runtime.core.conversation.AgentChatPolicy;import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;import dev.mineagent.runtime.api.agent.AgentDefinition;import dev.mineagent.runtime.api.config.ConfigPatch;import net.minecraft.server.level.ServerPlayer;import net.minecraft.server.MinecraftServer;import net.minecraft.network.chat.*;import java.util.*;
@net.neoforged.fml.common.EventBusSubscriber(modid="mineagent_runtime")
public final class ServerChatAccess {
 @FunctionalInterface public interface Resume{void run()throws Exception;}
 private record Pending(UUID id,UUID owner,ServerPlayer caller,UUID agent,String text,long revision,long expires,Resume resume){}
 private record Permit(ServerPlayer caller,UUID agent,String text){}
 private static final ObjectMapper JSON=new ObjectMapper();private static final Map<MinecraftServer,Map<UUID,Pending>> PENDING=new WeakHashMap<>();private static final ThreadLocal<Permit> ONCE=new ThreadLocal<>();
 private static AgentDefinition definition(ServerPlayer p,UUID id){return MineAgentRuntimeServices.bodies(p.level().getServer()).definitions().stream().filter(a->a.agentId().equals(id)).findFirst().orElseThrow(()->new IllegalArgumentException("CHAT_AGENT_NOT_FOUND"));}
 private static String key(MinecraftServer s,UUID agent){return "chat.access."+MineAgentRuntimeServices.worldId(s)+"."+agent;}
 public static AgentChatPolicy policy(MinecraftServer s,UUID agent){String raw=MineAgentRuntimeServices.config(s).snapshot().values().get(key(s,agent));if(raw==null)return AgentChatPolicy.defaults();try{return JSON.readValue(raw,AgentChatPolicy.class);}catch(Exception e){throw new IllegalStateException("CHAT_POLICY_INVALID",e);}}
 public static boolean canContinue(ServerPlayer p,UUID agent){try{var d=definition(p,agent);return d.ownerPlayerId().equals(p.getUUID())||policy(p.level().getServer(),agent).decision(d.ownerPlayerId(),p.getUUID())!=AgentChatPolicy.Decision.DENY;}catch(Exception missing){return false;}}
 public static boolean allowed(ServerPlayer p,UUID agent){return policy(p.level().getServer(),agent).decision(definition(p,agent).ownerPlayerId(),p.getUUID())==AgentChatPolicy.Decision.ALLOW;}
 public static boolean admitOrAsk(ServerPlayer p,UUID agent,String text,Resume resume){var d=definition(p,agent);var permit=ONCE.get();if(permit!=null&&permit.caller==p&&permit.agent.equals(agent)&&permit.text.equals(text))return true;var s=p.level().getServer();var policy=policy(s,agent);var decision=policy.decision(d.ownerPlayerId(),p.getUUID());if(decision==AgentChatPolicy.Decision.ALLOW)return true;if(decision==AgentChatPolicy.Decision.DENY){p.sendSystemMessage(Component.literal("["+d.displayName()+"] 创建者未允许响应你的请求。"));return false;}
  var owner=s.getPlayerList().getPlayer(d.ownerPlayerId());if(owner==null){p.sendSystemMessage(Component.literal("["+d.displayName()+"] 创建者不在线，暂不能请求响应许可。"));return false;}var map=PENDING.computeIfAbsent(s,k->new LinkedHashMap<>());map.values().removeIf(v->v.expires<System.currentTimeMillis()||s.getPlayerList().getPlayer(v.caller.getUUID())!=v.caller);if(map.values().stream().anyMatch(v->v.caller==p&&v.agent.equals(agent))){p.sendSystemMessage(Component.literal("该 AI 的响应许可正在等待创建者处理。"));return false;}if(map.size()>=128)throw new IllegalStateException("CHAT_APPROVAL_BUSY");UUID id=UUID.randomUUID();map.put(id,new Pending(id,d.ownerPlayerId(),p,agent,text,policy.revision(),System.currentTimeMillis()+600000,resume));var message=Component.literal("["+d.displayName()+"] 是否允许响应玩家 "+p.getGameProfile().name()+" 的请求？ ");String[][] choices={{"once_allow","响应一次TA"},{"always_allow","始终允许响应TA"},{"once_deny","拒绝一次TA"},{"always_deny","始终拒绝TA"}};for(var c:choices)message.append(Component.literal("["+c[1]+"] ").withStyle(style->style.withColor(c[0].endsWith("allow")?net.minecraft.ChatFormatting.GREEN:net.minecraft.ChatFormatting.RED).withClickEvent(new ClickEvent.RunCommand("/ai access_reply "+id+" "+c[0]))));owner.sendSystemMessage(message);p.sendSystemMessage(Component.literal("["+d.displayName()+"] 已向创建者请求响应许可，暂未提交给模型。"));return false;
 }
 public static int decide(ServerPlayer owner,UUID id,String choice)throws Exception{if(!Set.of("once_allow","always_allow","once_deny","always_deny").contains(choice))throw new IllegalArgumentException("CHAT_APPROVAL_CHOICE");var s=owner.level().getServer();var map=PENDING.getOrDefault(s,Map.of());var pending=map.get(id);if(pending==null||!pending.owner.equals(owner.getUUID())||pending.expires<System.currentTimeMillis()||!definition(owner,pending.agent).ownerPlayerId().equals(owner.getUUID()))throw new SecurityException("CHAT_APPROVAL_EXPIRED_OR_OWNER");if(policy(s,pending.agent).revision()!=pending.revision)throw new IllegalStateException("CHAT_POLICY_CHANGED");map.remove(id);boolean yes=choice.endsWith("allow");if(choice.startsWith("always"))save(owner,pending.agent,policy(s,pending.agent).remember(pending.caller.getUUID(),yes),pending.revision);owner.sendSystemMessage(Component.literal(yes?"已允许该请求响应。":"已拒绝该请求响应。"));if(s.getPlayerList().getPlayer(pending.caller.getUUID())!=pending.caller)return 1;if(!yes){pending.caller.sendSystemMessage(Component.literal("AI 创建者拒绝了本次响应请求。"));return 1;}ONCE.set(new Permit(pending.caller,pending.agent,pending.text));try{pending.resume.run();}finally{ONCE.remove();}return 1;}
 private static void save(ServerPlayer owner,UUID agent,AgentChatPolicy next,long expected)throws Exception{if(!definition(owner,agent).ownerPlayerId().equals(owner.getUUID()))throw new SecurityException("CHAT_POLICY_OWNER_REQUIRED");var s=owner.level().getServer();if(policy(s,agent).revision()!=expected)throw new IllegalStateException("CHAT_POLICY_CHANGED");var config=MineAgentRuntimeServices.config(s);var r=config.apply(new ConfigPatch(config.snapshot().revision(),Map.of(key(s,agent),JSON.writeValueAsString(next))),true);if(!r.accepted())throw new IllegalStateException(r.errorCode());ServerConversations.accessChanged(s,agent);}
 public static Map<String,String> edit(ServerPlayer owner,UUID agent,Map<String,String> args)throws Exception{var old=policy(owner.level().getServer(),agent);long expected=Long.parseLong(args.get("policyRevision"));var allow=new HashSet<>(old.allow());var deny=new HashSet<>(old.deny());String mode=args.getOrDefault("mode",old.mode()),player=args.getOrDefault("playerId",""),action=args.getOrDefault("entry","");if(!player.isEmpty()){UUID id=UUID.fromString(player);allow.remove(id);deny.remove(id);if(action.equals("allow"))allow.add(id);else if(action.equals("deny"))deny.add(id);else if(!action.equals("remove"))throw new IllegalArgumentException("CHAT_POLICY_ENTRY");}var next=new AgentChatPolicy(mode,allow,deny,expected+1);save(owner,agent,next,expected);return Map.of("revision",Long.toString(next.revision()),"mode",mode);}
 public static void accepted(ServerPlayer caller,UUID agent,String text,Resume resume)throws Exception{ONCE.set(new Permit(caller,agent,text));try{resume.run();}finally{ONCE.remove();}}
 public static void disconnect(ServerPlayer player){var map=PENDING.get(player.level().getServer());if(map!=null)map.values().removeIf(p->p.caller==player||p.owner.equals(player.getUUID()));}
 @net.neoforged.bus.api.SubscribeEvent public static void logout(net.neoforged.neoforge.event.entity.player.PlayerEvent.PlayerLoggedOutEvent e){if(e.getEntity() instanceof ServerPlayer p)disconnect(p);}
 @net.neoforged.bus.api.SubscribeEvent public static void stopped(net.neoforged.neoforge.event.server.ServerStoppedEvent e){PENDING.remove(e.getServer());}
 private ServerChatAccess(){}
}
