package dev.mineagent.runtime.neoforge.ui;

import com.fasterxml.jackson.databind.ObjectMapper;
import dev.mineagent.runtime.api.packages.*;
import dev.mineagent.runtime.api.permission.PermissionAction;
import dev.mineagent.runtime.api.task.*;
import dev.mineagent.runtime.api.ui.*;
import dev.mineagent.runtime.api.ui.UiProtocol.*;
import dev.mineagent.runtime.core.delivery.*;
import dev.mineagent.runtime.core.packages.*;
import dev.mineagent.runtime.core.ui.UiSessionService;
import dev.mineagent.runtime.neoforge.*;
import dev.mineagent.runtime.neoforge.network.UiPayloads;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.neoforged.neoforge.network.PacketDistributor;
import java.util.*;
import java.util.concurrent.*;

/** Sender-owned offers and recipient-owned display Sessions. No world/score/package editing rights are inherited. */
public final class ServerContentDeliveries implements AutoCloseable {
    private final MinecraftServer server;private final UiSessionService sessions;private final ContentDeliveryStore store;private final ObjectMapper json=new ObjectMapper();
    private final ServerUiFeedback feedback;
    private final PackageTransferLeases transfers=new PackageTransferLeases(java.time.Clock.systemUTC());private final Map<UUID,Open> opened=new HashMap<>();private final Map<UUID,UUID> transferOwners=new HashMap<>(),codeTransferOwners=new HashMap<>();private final Map<UUID,String> codeBundleHashes=new HashMap<>();
    private final Map<UUID,String> senderEpochs=new HashMap<>();private final Set<UUID> dirtyDeliveries=new LinkedHashSet<>();private ContentDeliveryStore.ManagementContext managementContext;private ServerPlayer managementViewer;private final Map<UUID,Long> sentRevision=new HashMap<>();private boolean closed;
    private final ExecutorService io=new ThreadPoolExecutor(1,1,0,TimeUnit.SECONDS,new ArrayBlockingQueue<>(4),r->{var t=new Thread(r,"mineagent-delivery-bundle");t.setDaemon(true);return t;},new ThreadPoolExecutor.AbortPolicy());
    private static final class Open{final DeliveryProtocol.Launch launch;final Binding binding;final ServerPlayer player;Session session;boolean visible=true;long visibilityRevision;Open(DeliveryProtocol.Launch launch,Binding binding,ServerPlayer player){this.launch=launch;this.binding=binding;this.player=player;}}
    ServerContentDeliveries(MinecraftServer server,UiSessionService sessions){
        this.server=server;this.sessions=sessions;
        try{store=ContentDeliveryStore.open(server.getServerDirectory().resolve("mineagent-runtime-data/runtime.db"),MineAgentRuntimeServices.worldId(server),System::currentTimeMillis,new ContentDeliveryStore.Port(){public void authorize(ContentDeliveryStore.Context c){authorizeSender(c);}public String authority(ContentDeliveryStore.Delivery d){return senderAuthority(d);}public void authorizeManagement(ContentDeliveryStore.ManagementContext c){requireThread();if(c!=managementContext||managementViewer==null||managementViewer instanceof dev.mineagent.runtime.neoforge.body.MineAgentPlayer||server.getPlayerList().getPlayer(c.owner())!=managementViewer)throw new SecurityException("DELIVERY_MANAGEMENT_IDENTITY");}public boolean mayArchive(ContentDeliveryStore.Delivery d){return (d.leaseId()==null||!opened.containsKey(d.leaseId()))&&(d.sessionId()==null||sessions.get(d.recipient(),d.sessionId()).isEmpty());}public boolean waitingForAuthority(ContentDeliveryStore.Delivery d){return waitingSender(d);}public void changed(UUID id){if(dirtyDeliveries.size()<4096)dirtyDeliveries.add(id);}});}catch(Exception e){throw new IllegalStateException("DELIVERY_STORE",e);}
        try{feedback=new ServerUiFeedback(server,sessions,this);}catch(Exception e){try{store.close();}catch(Exception x){e.addSuppressed(x);}throw new IllegalStateException("FEEDBACK_STORE",e);}
    }
    public long epoch(UUID owner){return MineAgentRuntimeServices.permissions(server).actionRevision(owner,PermissionAction.OFFER_CONTENT);}
    public boolean sameEpoch(UUID owner,long expected){return !closed&&epoch(owner)==expected;}
    private String epochs(UUID owner){return epoch(owner)+"|"+MineAgentRuntimeServices.permissions(server).actionRevision(owner,PermissionAction.DISCOVER_OBJECTS)+"|"+MineAgentRuntimeServices.permissions(server).actionRevision(owner,PermissionAction.RECEIVE_UI_FEEDBACK);}
    static String leaseEpochs(ContentDeliveryStore.Asset asset,long offer,long directory,long feedback){return offer+"|"+directory+(asset.feedbackPolicySha256().isEmpty()?"":"|"+feedback);}
    private boolean granted(UUID owner){var p=MineAgentRuntimeServices.permissions(server).trustedActions(owner);return p.contains(PermissionAction.OFFER_CONTENT)&&p.contains(PermissionAction.DISCOVER_OBJECTS);}
    private dev.mineagent.runtime.api.agent.AgentDefinition agent(UUID id){return MineAgentRuntimeServices.bodies(server).definitions().stream().filter(a->a.agentId().equals(id)).findFirst().orElse(null);}
    private RuntimePackage packageFor(UUID owner,ContentDeliveryStore.Asset a){var p=ServerPackageRuntime.get(server).ownedPackage(owner,a.packageId(),a.revision()).orElseThrow(()->new SecurityException("DELIVERY_PACKAGE_UNOWNED"));if(p.revision()!=a.revision()||!p.canonicalSha256().equals(a.canonical())||p.entrypoints().values().stream().noneMatch(e->e.path().equals(a.entry())&&e.side()!=RuntimeResourceSide.SERVER))throw new SecurityException("DELIVERY_PACKAGE_CHANGED");return p;}
    private void authorizeSender(ContentDeliveryStore.Context c){requireThread();var d=agent(c.agent());var task=MineAgentRuntimeServices.tasks(server).get(c.task()).orElse(null);if(!granted(c.owner())||!MineAgentRuntimeServices.permissions(server).canMutateAgent(d,c.owner(),false)||task==null||task.status()!=TaskStatus.RUNNING||task.intentRevision()!=c.intent()||!task.ownerPlayerId().equals(c.owner())||!task.agentId().equals(c.agent())||!MineAgentRuntimeServices.taskExecutor(server).authorized(task))throw new SecurityException("DELIVERY_SENDER_AUTHORITY");}
    private String stableAuthority(UUID owner,UUID agent,ContentDeliveryStore.Asset asset){var d=agent(agent);if(!granted(owner)||d==null||!MineAgentRuntimeServices.permissions(server).canMutateAgent(d,owner,false))return null;packageFor(owner,asset);String extra="";if(!asset.feedbackPolicySha256().isEmpty()){if(!MineAgentRuntimeServices.permissions(server).trustedActions(owner).contains(PermissionAction.RECEIVE_UI_FEEDBACK))return null;extra="|feedback|"+asset.feedbackPolicySha256()+"|"+MineAgentRuntimeServices.permissions(server).actionRevision(owner,PermissionAction.RECEIVE_UI_FEEDBACK);}if(asset.feedbackData()!=null){String dataToken=feedback.dataToken(owner,agent,asset);if(dataToken==null)return null;extra+="|data|"+dataToken;}return owner+"|"+agent+"|"+d.ownerPlayerId()+"|"+d.collaboratorPlayerIds().stream().map(UUID::toString).sorted().toList()+"|"+asset.packageId()+"|"+asset.revision()+"|"+asset.canonical()+extra;}
    private String senderAuthority(ContentDeliveryStore.Delivery d){try{if(closed||!server.isSameThread()||!Objects.toString(d.issuedAuthority(),"").startsWith("DELIVERY_V2|"))return null;var p=MineAgentRuntimeServices.permissions(server);String current=leaseEpochs(d.asset(),epoch(d.owner()),p.actionRevision(d.owner(),PermissionAction.DISCOVER_OBJECTS),p.actionRevision(d.owner(),PermissionAction.RECEIVE_UI_FEEDBACK));if(!senderEpochs.computeIfAbsent(d.id(),k->current).equals(current))return null;return issuedAuthority(d.owner(),d.agent(),d.asset());}catch(Exception denied){return null;}}
    private String issuedAuthority(UUID owner,UUID agent,ContentDeliveryStore.Asset asset){
        // Check live resources, but never persist process-local script/permission epochs in a restartable grant.
        if(stableAuthority(owner,agent,asset)==null)return null;return durableAuthority(owner,agent,asset);
    }
    private String durableAuthority(UUID owner,UUID agent,ContentDeliveryStore.Asset asset){long membership=MineAgentRuntimeServices.bodies(server).authorityGeneration(agent);if(membership<0)return null;var config=MineAgentRuntimeServices.config(server);
        String value="DELIVERY_V2|"+membership+"|"+owner+"|"+agent+"|"+asset.packageId()+"|"+asset.revision()+"|"+asset.canonical()+"|"+asset.entry()+"|"+asset.mode()+"|"+config.permissionGeneration(owner,PermissionAction.OFFER_CONTENT)+"|"+config.permissionGeneration(owner,PermissionAction.DISCOVER_OBJECTS);
        if(!asset.feedbackPolicySha256().isEmpty())value+="|"+asset.feedbackPolicySha256()+"|"+config.permissionGeneration(owner,PermissionAction.RECEIVE_UI_FEEDBACK);
        if(asset.feedbackData()!=null){var data=asset.feedbackData();value+="|"+data.instanceId()+"|"+data.namespace()+"|"+data.schemaVersion()+"|"+data.readKeys().stream().sorted().toList()+"|"+data.writeKeys().stream().sorted().toList()+"|"+config.permissionGeneration(owner,PermissionAction.ACCESS_SHARED_STATE)+"|"+config.permissionGeneration(owner,PermissionAction.RUN_CODE)+"|"+config.permissionGeneration(owner,PermissionAction.MANAGE_PACKAGES);}
        return value;
    }
    private boolean waitingSender(ContentDeliveryStore.Delivery d){try{
        if(closed||!Objects.toString(d.issuedAuthority(),"").startsWith("DELIVERY_V2|")||d.asset().feedbackData()==null||!granted(d.owner())||!MineAgentRuntimeServices.permissions(server).canMutateAgent(agent(d.agent()),d.owner(),false)||!Objects.equals(d.issuedAuthority(),durableAuthority(d.owner(),d.agent(),d.asset())))return false;packageFor(d.owner(),d.asset());
        if(!MineAgentRuntimeServices.permissions(server).trustedActions(d.owner()).contains(PermissionAction.RECEIVE_UI_FEEDBACK))return false;
        return dev.mineagent.runtime.neoforge.content.WorldContentRuntime.get(server).instanceEventWaiting(d.owner(),d.asset().packageId(),d.asset().feedbackData().instanceId(),d.asset().revision(),d.asset().canonical());
    }catch(Exception unavailable){return false;}}
    private ContentDeliveryStore.Context context(ManagedTask task,UUID operation){return new ContentDeliveryStore.Context(task.worldId(),task.ownerPlayerId(),task.agentId(),task.taskId(),task.intentRevision(),operation);}
    public void requireGoalCoverage(ManagedTask task,List<dev.mineagent.runtime.core.task.WorldGoalCheck> checks,List<dev.mineagent.runtime.core.task.WorldActionJournal.Batch> history)throws Exception{
        var goals=new ArrayList<DeliveryGoal>();for(var c:checks)if(c.kind().equals("content_delivery"))goals.add(DeliveryGoal.parse(json.readTree(c.details().get("request"))));
        var effects=new ArrayList<DeliveryGoalCoverage.Effect>();for(var b:history)for(var a:b.actions())if(Set.of("update_view","close_view","revoke_content").contains(a.tool())){var r=DeliveryToolRequest.parse(a.tool(),a.options().get("request"));effects.add(new DeliveryGoalCoverage.Effect(a.tool(),r.id(),r.tool().equals("update_view")?Math.addExact(r.expectedDataRevision(),1):0,r.tool().equals("update_view")?ContentDeliveryStore.dataSha256(r.data()):""));}
        var ids=new HashSet<UUID>();goals.forEach(g->ids.add(g.deliveryId()));effects.forEach(e->ids.add(e.deliveryId()));var rows=store.coverageRows(context(task,UUID.randomUUID()),ids);
        if(!goals.isEmpty()||!effects.isEmpty()||rows.stream().anyMatch(d->d.origin()!=null&&d.origin().task().equals(task.taskId())&&d.origin().intent()==task.intentRevision())){var c=context(task,UUID.randomUUID());authorizeSender(c);DeliveryGoalCoverage.require(c,rows,goals,effects);}
    }
    public Map<String,Object> verifyGoal(ManagedTask task,dev.mineagent.runtime.core.task.WorldGoalCheck check)throws Exception{
        var goal=DeliveryGoal.parse(json.readTree(check.details().get("request")));var d=store.inspect(context(task,UUID.randomUUID()),goal.deliveryId());packageFor(d.owner(),d.asset());
        var open=opened.get(d.leaseId());boolean live=open!=null&&open.visible&&open.session!=null&&open.session.sessionId().equals(d.sessionId())&&authorize(open.session)==Code.OK;
        return Map.of("matched",goal.matches(d,live),"evidence",goal.evidence(),"row",summary(d),"liveVisible",live,"humanReadVerified",false,"applicationSemanticsVerified",false);
    }
    private void receiptResource(ContentDeliveryStore.Delivery d){packageFor(d.owner(),d.asset());if(!Set.of("CLOSED","REVOKED","REJECTED","EXPIRED","FAILED","UNAVAILABLE").contains(d.status())&&!Objects.equals(senderAuthority(d),d.issuedAuthority()))throw new SecurityException("DELIVERY_RESOURCE_AUTHORITY_CHANGED");}
    public Map<String,String> execute(ManagedTask task,UUID operation,String tool,String arguments)throws Exception{
        requireThread();var r=DeliveryToolRequest.parse(tool,arguments);var c=context(task,operation);authorizeSender(c);Object result;
        if(tool.equals("inspect_content_contract")){
            var pkg=contractPackage(c.owner(),r);result=ContentContractView.inspect(pkg,r.entryId(),r.offset(),ServerPackageRuntime.get(server).worldContent()::read);authorizeSender(c);contractPackage(c.owner(),r);
        }else if(tool.equals("offer_content")){
            var asset=offerAsset(c.owner(),c.agent(),r);var audience=MineAgentRuntimeServices.taskExecutor(server).worldActions().audiences();var ac=audience.context(task,operation);var snapshot=audience.store().inspectSnapshot(ac,r.audienceSnapshot());var definition=audience.store().inspect(ac,snapshot.audienceId());
            if(!snapshot.state().equals("RESOLVED")||!definition.state().equals("ACTIVE")||definition.revision()!=snapshot.definitionRevision()||System.currentTimeMillis()>=snapshot.expiresAt()||!snapshot.context().serverEpoch().equals(ac.serverEpoch())||snapshot.context().scope().authorityRevision()!=ac.scope().authorityRevision())throw new SecurityException("DELIVERY_AUDIENCE_STALE");
            var people=new ArrayList<ContentDeliveryStore.Recipient>();var directory=MineAgentRuntimeServices.taskExecutor(server).worldActions().directory();for(var p:snapshot.recipients()){String status=p.status();if(status.equals("ELIGIBLE")){var check=directory.core().revalidate(ac.scope(),p.ref(),definition.query());if(!check.status().equals("CURRENT"))status=check.status().equals("FILTER_CHANGED")?"FILTER_CHANGED":"UNAVAILABLE";}people.add(new ContentDeliveryStore.Recipient(p.playerId(),status));}
            result=store.offer(c,asset,snapshot.snapshotId(),people,r.data(),r.ttlMillis(),issuedAuthority(c.owner(),c.agent(),asset));
        }else if(tool.equals("query_deliveries")){var rows=store.query(c,r.id());result=Map.of("deliveries",rows.stream().skip(r.offset()).limit(16).map(this::summary).toList(),"offset",r.offset(),"more",rows.size()>r.offset()+16);}
        else{var value=switch(tool){case "update_view"->store.update(c,r.id(),r.expectedDataRevision(),r.data());case "close_view"->store.requestClose(c,r.id());case "revoke_content"->store.revoke(c,r.id());default->throw new IllegalArgumentException("DELIVERY_TOOL");};result=summary(value);}
        return Map.of("executionMode","CONTENT_DELIVERY_LIFECYCLE_NOT_BUSINESS_COMPLETION","result",json.writeValueAsString(result),"request",r.canonicalRequest(),"authorityEpoch",epochs(c.owner()),"deliveryVerified","false");
    }
    private ContentDeliveryStore.Asset offerAsset(UUID owner,UUID agent,DeliveryToolRequest r)throws Exception{return offerAsset(owner,agent,r,true);}
    private ContentDeliveryStore.Asset offerAsset(UUID owner,UUID agent,DeliveryToolRequest r,boolean requireData)throws Exception{
            var pkg=ServerPackageRuntime.get(server).ownedPackage(owner,r.packageId(),r.packageRevision()).orElseThrow(()->new SecurityException("DELIVERY_PACKAGE_UNOWNED"));var entry=pkg.entrypoints().get(r.entryId());if(entry==null||entry.side()==RuntimeResourceSide.SERVER||!pkg.canonicalSha256().equals(r.canonical())||pkg.revision()!=r.packageRevision())throw new IllegalArgumentException("DELIVERY_ENTRY");boolean code=r.mode().startsWith("CLIENT_");if(code){if(r.mode().equals("CLIENT_JAVA")){if(!ClientJavaPlan.inspect(pkg).entrypoint().equals(entry.path()))throw new IllegalArgumentException("DELIVERY_CLIENT_JAVA_ENTRY");}else if(r.mode().equals("CLIENT_RHINO")){if(!ClientScriptPlan.inspect(pkg).entrypoint().equals(entry.path()))throw new IllegalArgumentException("DELIVERY_CLIENT_RHINO_ENTRY");}else throw new IllegalArgumentException("DELIVERY_CODE_MODE");if(r.feedbackEnabled()||r.feedbackData()!=null)throw new IllegalArgumentException("DELIVERY_CODE_FEEDBACK");}else if(entry.side()!=RuntimeResourceSide.CLIENT||!entry.path().startsWith("ui/")||!entry.path().endsWith(".html"))throw new IllegalArgumentException("DELIVERY_ENTRY");
            if(r.mode().equals("HUD")&&!PackageUiEntrypoints.select(pkg.entrypoints(),true).filter(entry.path()::equals).isPresent())throw new IllegalArgumentException("DELIVERY_HUD_ENTRY");
            String feedbackHash="";
            if(r.feedbackEnabled()){
                if(!r.mode().equals("CONTENT")||!MineAgentRuntimeServices.permissions(server).trustedActions(owner).contains(PermissionAction.RECEIVE_UI_FEEDBACK))throw new SecurityException("FEEDBACK_EXPLICIT_GRANT_REQUIRED");
                var policy=dev.mineagent.runtime.core.feedback.UiFeedbackPolicy.fromPackage(pkg,entry.path(),ServerPackageRuntime.get(server).worldContent()::read);
                if(policy.events().values().stream().anyMatch(e->!Set.of("RECORD_ONLY","AGENT_WAKE","DETERMINISTIC").contains(e.mode())))throw new IllegalStateException("FEEDBACK_CONSUMER_NOT_AVAILABLE");for(var event:policy.events().entrySet())if(event.getValue().mode().equals("AGENT_WAKE")&&MineAgentRuntimeServices.events(server).feedbackConsumer(owner,agent,pkg.packageId(),pkg.revision(),pkg.canonicalSha256(),entry.path(),policy.sha256(),event.getKey())==null)throw new IllegalStateException("FEEDBACK_CONSUMER_NOT_AVAILABLE");if(policy.events().values().stream().anyMatch(e->e.mode().equals("DETERMINISTIC"))!=(r.feedbackData()!=null))throw new IllegalArgumentException("FEEDBACK_DATA_BINDING_REQUIRED");feedbackHash=policy.sha256();
            }
            var asset=new ContentDeliveryStore.Asset(pkg.packageId(),pkg.revision(),pkg.canonicalSha256(),entry.path(),r.mode(),pkg.name(),feedbackHash,r.feedbackData());if(requireData&&r.feedbackData()!=null&&feedback.dataToken(owner,agent,asset)==null)throw new SecurityException("FEEDBACK_DATA_GRANT_REQUIRED");return asset;
    }
    /** Standing validation only; no Task identity or audience snapshot is fabricated. */
    public String scheduleAuthority(UUID owner,UUID agent,dev.mineagent.runtime.core.scheduling.ScheduleDeliveryConsumer delivery){try{requireThread();if(closed||!granted(owner))return null;var asset=offerAsset(owner,agent,delivery.template());String value=stableAuthority(owner,agent,asset);if(value==null)return null;var p=MineAgentRuntimeServices.permissions(server);return value+"|"+leaseEpochs(asset,epoch(owner),p.actionRevision(owner,PermissionAction.DISCOVER_OBJECTS),p.actionRevision(owner,PermissionAction.RECEIVE_UI_FEEDBACK));}catch(Exception unavailable){return null;}}
    public Map<String,Object> scheduleHistory(UUID owner,UUID agent,UUID originTask,int offset)throws Exception{
        requireThread();if(closed||!granted(owner)||!MineAgentRuntimeServices.permissions(server).canMutateAgent(agent(agent),owner,false))throw new SecurityException("SCHEDULE_DELIVERY_AUTHORITY_REQUIRED");if(offset<0||offset>64)throw new IllegalArgumentException("SCHEDULE_DELIVERY_PAGE");
        var rows=store.originHistory(owner,agent,originTask,offset,16);long total=store.originCount(owner,agent,originTask);var page=new ArrayList<Object>();
        for(var d:rows){receiptResource(d);page.add(summary(d));if(json.writeValueAsBytes(page).length>20000){page.removeLast();if(page.isEmpty())throw new IllegalStateException("SCHEDULE_DELIVERY_PAGE_BUDGET");break;}}
        return Map.of("deliveries",page,"total",total,"offset",offset,"nextOffset",offset+page.size(),"more",total>offset+page.size(),"historyOnly",true,"humanReadVerified",false);
    }
    public boolean scheduleWaiting(UUID owner,UUID agent,dev.mineagent.runtime.core.scheduling.ScheduleDeliveryConsumer delivery){try{
        requireThread();if(closed||!granted(owner)||!MineAgentRuntimeServices.permissions(server).canMutateAgent(agent(agent),owner,false))return false;var r=delivery.template();var asset=offerAsset(owner,agent,r,false);if(asset.feedbackData()==null)return false;
        return dev.mineagent.runtime.neoforge.content.WorldContentRuntime.get(server).instanceEventWaiting(owner,asset.packageId(),asset.feedbackData().instanceId(),asset.revision(),asset.canonical());
    }catch(Exception unavailable){return false;}}
    private Map<String,Object> summary(ContentDeliveryStore.Delivery d){var value=new LinkedHashMap<String,Object>();boolean code=d.asset().mode().startsWith("CLIENT_");value.put("deliveryId",d.id());value.put("batchId",d.batchId());value.put("recipient",d.recipient());value.put("title",d.asset().title());value.put("packageId",d.asset().packageId());value.put("packageRevision",d.asset().revision());value.put("canonicalSha256",d.asset().canonical());value.put("entry",d.asset().entry());value.put("mode",d.asset().mode());value.put("clientCode",code);value.put("readiness",code?(d.status().startsWith("CODE_")?d.status().substring(5):d.status().equals("OFFERED")?"PENDING":d.status()):"");value.put("feedbackEnabled",!d.asset().feedbackPolicySha256().isEmpty());if(!d.asset().feedbackPolicySha256().isEmpty())try{value.put("feedbackModes",feedbackPolicy(d).events().values().stream().map(dev.mineagent.runtime.core.feedback.UiFeedbackPolicy.Event::mode).distinct().toList());}catch(Exception missing){value.put("feedbackModes",List.of("UNAVAILABLE"));}value.put("status",d.status());value.put("revision",d.revision());value.put("dataRevision",d.dataRevision());value.put("dataSha256",ContentDeliveryStore.dataSha256(d.data()));value.put("receivedDataRevision",d.dataReceipt()==null?0:d.dataReceipt().revision());value.put("receivedDataSha256",d.dataReceipt()==null?"":d.dataReceipt().sha256());value.put("dataPaintedAt",d.dataReceipt()==null?0:d.dataReceipt().receivedAndPaintedAt());value.put("dataPaintMatchesLatest",!code&&new DeliveryGoal(d.id(),d.revision(),d.dataRevision(),ContentDeliveryStore.dataSha256(d.data()),d.status(),"DATA_PAINT").matches(d,true));value.put("expiresAt",d.expiresAt());value.put("closeConfirmed",d.closeConfirmed());value.put("paintedAt",d.paintedAt());value.put("error",d.error());return value;}
    public Map<String,String> inbox(ServerPlayer viewer,int offset)throws Exception{var rows=store.inbox(viewer.getUUID(),offset);return Map.of("deliveries",json.writeValueAsString(rows.stream().map(this::summary).toList()),"offset",Integer.toString(offset),"more",Boolean.toString(store.inboxCount(viewer.getUUID())>offset+rows.size()),"nextOffset",Integer.toString(offset+rows.size()));}
    public Map<String,String> manage(ServerPlayer viewer,UUID operation,Map<String,String> args)throws Exception{
        requireThread();if(managementContext!=null||viewer instanceof dev.mineagent.runtime.neoforge.body.MineAgentPlayer||server.getPlayerList().getPlayer(viewer.getUUID())!=viewer)throw new SecurityException("DELIVERY_MANAGEMENT_IDENTITY");
        var c=new ContentDeliveryStore.ManagementContext(MineAgentRuntimeServices.worldId(server),viewer.getUUID());managementContext=c;managementViewer=viewer;
        try{Object result;String kind=args.getOrDefault("kind","");
            if(kind.equals("list")){if(!args.keySet().equals(Set.of("kind","status","archive","offset")))throw new IllegalArgumentException("DELIVERY_MANAGEMENT_ARGUMENTS");var page=store.managementList(c,args.get("status"),args.get("archive"),Integer.parseInt(args.get("offset")),16);var rows=new ArrayList<Object>();
                for(var d:page.rows()){rows.add(managementSummary(d));if(json.writeValueAsBytes(rows).length>20000){rows.removeLast();if(rows.isEmpty())throw new IllegalStateException("DELIVERY_MANAGEMENT_RESPONSE_BUDGET");break;}}
                result=Map.of("items",rows,"total",page.total(),"offset",page.offset(),"nextOffset",page.offset()+rows.size(),"more",page.total()>page.offset()+rows.size(),"usage",store.managementUsage(c));
            }else if(kind.equals("detail")){if(!args.keySet().equals(Set.of("kind","deliveryId")))throw new IllegalArgumentException("DELIVERY_MANAGEMENT_ARGUMENTS");var d=store.managementInspect(c,UUID.fromString(args.get("deliveryId")));result=Map.of("delivery",managementSummary(d),"data",json.readTree(d.data()),"canonicalSha256",d.asset().canonical(),"entry",d.asset().entry(),"originTask",d.origin()==null?"":d.origin().task().toString());
            }else if(kind.equals("write")){if(!args.keySet().equals(Set.of("kind","deliveryId","expectedRevision","action","confirmed"))||!"true".equals(args.get("confirmed")))throw new IllegalArgumentException("DELIVERY_MANAGEMENT_CONFIRM");result=store.managementWrite(c,operation,UUID.fromString(args.get("deliveryId")),Long.parseLong(args.get("expectedRevision")),args.get("action"),true);
            }else throw new IllegalArgumentException("DELIVERY_MANAGEMENT_KIND");String value=json.writeValueAsString(result);if(value.getBytes(java.nio.charset.StandardCharsets.UTF_8).length>24000)throw new IllegalStateException("DELIVERY_MANAGEMENT_RESPONSE_BUDGET");return Map.of("state",value,"executionMode","OWNER_SENT_CONTENT_NO_MODEL");
        }finally{managementContext=null;managementViewer=null;}
    }
    private Map<String,Object> managementSummary(ContentDeliveryStore.Delivery d)throws Exception{var value=new LinkedHashMap<>(summary(d));value.put("agentId",d.agent());value.put("archived",store.archived(d.id()));value.put("canArchive",store.mayArchive(d)&&!store.archived(d.id()));value.put("canClose",!Set.of("CLOSED","REVOKED","REJECTED","EXPIRED","FAILED","UNAVAILABLE","CLOSE_REQUESTED").contains(d.status()));value.put("canRevoke",!Set.of("REVOKED","REJECTED","EXPIRED","FAILED","UNAVAILABLE").contains(d.status()));value.put("legacyAuthority",!Objects.toString(d.issuedAuthority(),"").startsWith("DELIVERY_V2|"));return value;}
    public void accept(ServerPlayer viewer,Request request){
        requireThread();UUID delivery=UUID.fromString(request.arguments().get("deliveryId"));ContentDeliveryStore.Lease lease=null;Open candidate=null;
        try{
            lease=store.accept(viewer.getUUID(),delivery,request.operationId());var row=store.recipient(viewer.getUUID(),delivery);var pkg=packageFor(row.owner(),row.asset());
            var launch=new DeliveryProtocol.Launch(row.id(),lease.leaseId(),lease.viewId(),pkg.packageId(),pkg.revision(),pkg.canonicalSha256(),row.asset().entry(),row.asset().mode(),viewer.getUUID(),Math.min(row.expiresAt(),System.currentTimeMillis()+1_800_000),row.asset().feedbackPolicySha256());
            if(opened.containsKey(lease.leaseId()))throw new IllegalStateException("DELIVERY_ALREADY_OPENING");candidate=new Open(launch,launch.binding(MineAgentRuntimeServices.worldId(server),pkg.version()),viewer);opened.put(lease.leaseId(),candidate);candidate.session=sessions.openUntil(candidate.binding,true,true,launch.expiresAt());store.attach(viewer.getUUID(),delivery,lease.leaseId(),candidate.session.sessionId());
            var current=candidate;var content=ServerPackageRuntime.get(server).worldContent();CompletableFuture.supplyAsync(()->{try{return PackagePreviewBundle.encode(pkg,launch.entryPath(),content);}catch(Exception e){throw new CompletionException(e);}},io).whenComplete((bytes,error)->server.execute(()->{
                try{if(error!=null||authorize(current.session)!=Code.OK||sessions.checkRead(viewer.getUUID(),request,"delivery.transfer")!=Code.OK)throw new IllegalStateException("DELIVERY_OPEN_CHANGED");var offer=transfers.offer(viewer.getUUID(),request.sessionId(),pkg.packageId(),pkg.revision(),bytes);transferOwners.put(offer.transferId(),launch.leaseId());send(viewer,request.operationId(),"receipt",sessions.complete(request,Code.ACCEPTED,Map.of("launch",json.writeValueAsString(launch),"contentSession",json.writeValueAsString(current.session),"packageId",pkg.packageId().toString(),"packageRevision",Long.toString(pkg.revision()),"transferId",offer.transferId().toString(),"size",Integer.toString(offer.size()),"sha256",offer.sha256())));}
                catch(Exception failed){failOpen(current);send(viewer,request.operationId(),"receipt",sessions.complete(request,Code.FAILED,Map.of("errorCode","DELIVERY_OPEN_FAILED")));}
            }));
        }catch(Exception e){if(candidate!=null)failOpen(candidate);send(viewer,request.operationId(),"receipt",sessions.complete(request,Code.FAILED,Map.of("errorCode","DELIVERY_ACCEPT_FAILED")));}
    }
    public void acceptCode(ServerPlayer viewer,Request request){requireThread();UUID delivery=UUID.fromString(request.arguments().get("deliveryId"));try{store.acceptCode(viewer.getUUID(),delivery,request.operationId());var row=store.recipient(viewer.getUUID(),delivery);var pkg=packageFor(row.owner(),row.asset());boolean java=row.asset().mode().equals("CLIENT_JAVA");if(java!=ClientJavaPlan.path(row.asset().entry())||!java&&!ClientScriptPlan.path(row.asset().entry()))throw new IllegalStateException("DELIVERY_CODE_ENTRY");var content=ServerPackageRuntime.get(server).worldContent();CompletableFuture.supplyAsync(()->{try{return java?ClientJavaPlan.inspect(pkg).bundle(content):ClientScriptPlan.inspect(pkg).bundle(content);}catch(Exception failure){throw new CompletionException(failure);}},io).whenComplete((body,error)->server.execute(()->{try{if(error!=null||sessions.checkRead(viewer.getUUID(),request,"delivery.transfer")!=Code.OK)throw new IllegalStateException("DELIVERY_CODE_DOWNLOAD_CHANGED");var current=store.recipient(viewer.getUUID(),delivery);if(!current.status().equals("CODE_DOWNLOADING")||!Objects.equals(senderAuthority(current),current.issuedAuthority()))throw new IllegalStateException("DELIVERY_CODE_DOWNLOAD_CHANGED");var offer=transfers.offer(viewer.getUUID(),request.sessionId(),pkg.packageId(),pkg.revision(),body);codeTransferOwners.put(offer.transferId(),delivery);codeBundleHashes.put(delivery,offer.sha256());send(viewer,request.operationId(),"receipt",sessions.complete(request,Code.ACCEPTED,Map.of("deliveryId",delivery.toString(),"packageId",pkg.packageId().toString(),"packageRevision",Long.toString(pkg.revision()),"canonicalSha256",pkg.canonicalSha256(),"language",java?"JAVA":"RHINO","transferId",offer.transferId().toString(),"size",Integer.toString(offer.size()),"sha256",offer.sha256())));}catch(Exception failed){try{store.codeState(viewer.getUUID(),delivery,UUID.randomUUID(),"FAILED","DELIVERY_CODE_DOWNLOAD_FAILED");}catch(Exception ignored){}send(viewer,request.operationId(),"receipt",sessions.complete(request,Code.FAILED,Map.of("errorCode","DELIVERY_CODE_DOWNLOAD_FAILED")));}}));}catch(Exception failure){try{store.codeState(viewer.getUUID(),delivery,UUID.randomUUID(),"FAILED","DELIVERY_CODE_ACCEPT_FAILED");}catch(Exception ignored){}send(viewer,request.operationId(),"receipt",sessions.complete(request,Code.FAILED,Map.of("errorCode","DELIVERY_CODE_ACCEPT_FAILED")));}}
    private void failOpen(Open open){if(open.session!=null)sessions.close(open.launch.viewer(),open.session.sessionId());try{store.fail(open.launch.viewer(),open.launch.deliveryId(),open.launch.leaseId(),"DELIVERY_OPEN_FAILED");}catch(Exception ignored){}opened.remove(open.launch.leaseId());}
    public Code authorize(Session session){if(session==null||closed)return Code.STALE_VIEW;try{var id=DeliveryProtocol.deliveryId(session.binding());var lease=DeliveryProtocol.leaseId(session.binding());var open=opened.get(lease);if(open==null||!open.binding.equals(session.binding())||server.getPlayerList().getPlayer(open.launch.viewer())!=open.player)return Code.STALE_VIEW;return store.permits(open.launch.viewer(),id,lease,open.session==null?null:session.sessionId())?Code.OK:Code.STALE_VIEW;}catch(Exception e){return Code.PERMISSION_DENIED;}}
    public Map<String,String> chunk(ServerPlayer viewer,UUID shell,UUID transfer,int offset){byte[] bytes=transfers.chunk(viewer.getUUID(),shell,transfer,offset,offer->{var open=opened.get(transferOwners.get(transfer));return open!=null&&authorize(open.session)==Code.OK;});return Map.of("offset",Integer.toString(offset),"bytes",Base64.getEncoder().encodeToString(bytes));}
    public Map<String,String> codeChunk(ServerPlayer viewer,UUID shell,UUID transfer,int offset){byte[] bytes=transfers.chunk(viewer.getUUID(),shell,transfer,offset,offer->{try{UUID id=codeTransferOwners.get(transfer);var row=id==null?null:store.recipient(viewer.getUUID(),id);return row!=null&&row.status().equals("CODE_DOWNLOADING")&&Objects.equals(senderAuthority(row),row.issuedAuthority())&&row.asset().packageId().equals(offer.packageId())&&row.asset().revision()==offer.packageRevision();}catch(Exception denied){return false;}});return Map.of("offset",Integer.toString(offset),"bytes",Base64.getEncoder().encodeToString(bytes));}
    public void release(ServerPlayer viewer){transfers.release(viewer.getUUID());transferOwners.entrySet().removeIf(e->{var o=opened.get(e.getValue());return o==null||o.player==viewer;});codeTransferOwners.entrySet().removeIf(e->{try{return store.recipient(viewer.getUUID(),e.getValue())!=null;}catch(Exception denied){return false;}});}
    public Map<String,String> read(ServerPlayer viewer,Session session)throws Exception{if(authorize(session)!=Code.OK)throw new SecurityException("DELIVERY_READ_DENIED");var row=store.recipient(viewer.getUUID(),DeliveryProtocol.deliveryId(session.binding()));var value=new LinkedHashMap<String,Object>();value.put("deliveryId",row.id());value.put("revision",row.dataRevision());value.put("dataSha256",ContentDeliveryStore.dataSha256(row.data()));value.put("data",json.readTree(row.data()));value.put("assetOnly",true);if(DeliveryProtocol.feedbackEnabled(session.binding()))value.put("feedback",feedbackPolicy(row));return Map.of("state",json.writeValueAsString(value));}
    public Map<String,String> receipt(ServerPlayer viewer,String action,Map<String,String> a)throws Exception{
        UUID id=UUID.fromString(a.get("deliveryId"));if(action.equals("delivery.reject")){store.reject(viewer.getUUID(),id,UUID.fromString(a.get("operationId")));return Map.of("status","REJECTED");}
        UUID lease=UUID.fromString(a.get("leaseId")),session=UUID.fromString(a.get("sessionId"));
        if(action.equals("delivery.closed")){store.closed(viewer.getUUID(),id,lease,session);var old=opened.remove(lease);if(old!=null)sessions.retire(viewer.getUUID(),session,old.launch.viewId());return Map.of("status","CLOSED_ACKNOWLEDGED");}
        var current=sessions.get(viewer.getUUID(),session).orElseThrow();if(authorize(current)!=Code.OK||current.pageGeneration()!=Long.parseLong(a.get("pageGeneration")))throw new SecurityException("DELIVERY_RECEIPT_CONTEXT");
        if(action.equals("delivery.visibility")){
            var open=opened.get(lease);long revision=Long.parseLong(a.get("visibilityRevision"));if(open==null||!open.launch.deliveryId().equals(id)||!open.session.sessionId().equals(session)||open.player!=viewer||revision<1||!Set.of("true","false").contains(a.get("visible")))throw new IllegalArgumentException("DELIVERY_VISIBILITY");
            if(revision>open.visibilityRevision){open.visibilityRevision=revision;open.visible=Boolean.parseBoolean(a.get("visible"));feedback.visibilityChanged();}return Map.of("visible",Boolean.toString(open.visible));
        }
        if(action.equals("delivery.painted")&&current.status()!=Status.RENDERED)throw new IllegalStateException("DELIVERY_NOT_ADMITTED");
        if(action.equals("delivery.received"))store.received(viewer.getUUID(),id,lease,session);
        else if(action.equals("delivery.painted")){if(a.containsKey("dataRevision")){var open=opened.get(lease);if(open==null||!open.visible)throw new SecurityException("DELIVERY_DATA_PAINT_HIDDEN");store.painted(viewer.getUUID(),id,lease,session,a.get("documentId"),Long.parseLong(a.get("paintSequence")),a.get("layoutHash"),Long.parseLong(a.get("dataRevision")),a.get("dataSha256"));}else store.painted(viewer.getUUID(),id,lease,session,a.get("documentId"),Long.parseLong(a.get("paintSequence")),a.get("layoutHash"));}else throw new IllegalArgumentException("DELIVERY_RECEIPT_ACTION");return Map.of("status",store.recipient(viewer.getUUID(),id).status());
    }
    public Map<String,String> codeState(ServerPlayer viewer,Request request)throws Exception{var a=request.arguments();if(!a.keySet().equals(Set.of("deliveryId","packageId","packageRevision","canonicalSha256","language","localState","assetRevision","bundleHash"))||!Set.of("RHINO","JAVA").contains(a.get("language")))throw new IllegalArgumentException("DELIVERY_CODE_STATE_ARGUMENTS");UUID id=UUID.fromString(a.get("deliveryId"));var row=store.recipient(viewer.getUUID(),id);boolean java=row.asset().mode().equals("CLIENT_JAVA");if(!row.asset().packageId().toString().equals(a.get("packageId"))||row.asset().revision()!=Long.parseLong(a.get("packageRevision"))||!row.asset().canonical().equals(a.get("canonicalSha256"))||java!=a.get("language").equals("JAVA")||!Objects.equals(codeBundleHashes.get(id),a.get("bundleHash"))||Long.parseLong(a.get("assetRevision"))<1)throw new SecurityException("DELIVERY_CODE_STATE_IDENTITY");var changed=store.codeState(viewer.getUUID(),id,request.operationId(),a.get("localState"),a.get("localState").equals("FAILED")?"CLIENT_CODE_LOCAL_FAILED":"");return Map.of("status",changed.status(),"revision",Long.toString(changed.revision()));}
    public void navigated(UUID viewer,Session session)throws Exception{store.navigated(viewer,DeliveryProtocol.deliveryId(session.binding()),DeliveryProtocol.leaseId(session.binding()),session.sessionId());}
    public void closedSession(UUID viewer,Session session)throws Exception{if(DeliveryProtocol.bound(session.binding())){sessions.retire(viewer,session.sessionId(),session.binding().viewId());store.closed(viewer,DeliveryProtocol.deliveryId(session.binding()),DeliveryProtocol.leaseId(session.binding()),session.sessionId());opened.remove(DeliveryProtocol.leaseId(session.binding()));}}
    public void disconnect(UUID viewer){try{store.disconnect(viewer);}catch(Exception e){MineAgentRuntimeMod.LOGGER.warn("Delivery disconnect persistence failed");}transfers.release(viewer);opened.values().removeIf(o->o.launch.viewer().equals(viewer));transferOwners.entrySet().removeIf(e->!opened.containsKey(e.getValue()));codeTransferOwners.entrySet().removeIf(e->{try{return store.recipient(viewer,e.getValue())!=null;}catch(Exception denied){return false;}});codeBundleHashes.keySet().removeIf(id->{try{return store.recipient(viewer,id)!=null;}catch(Exception denied){return false;}});sentRevision.entrySet().removeIf(e->{try{return store.recipient(viewer,e.getKey())!=null;}catch(Exception denied){return false;}});}
    public void tick(){if(closed||server.getTickCount()%20!=0)return;try{store.reconcile();feedback.tick();var rows=new LinkedHashMap<UUID,ContentDeliveryStore.Delivery>();for(var d:store.runtimeHotRows())rows.put(d.id(),d);var hot=new HashSet<>(rows.keySet());for(var id:List.copyOf(dirtyDeliveries))store.runtimeRow(id).ifPresent(d->rows.put(id,d));dirtyDeliveries.clear();
        sentRevision.keySet().retainAll(hot);senderEpochs.keySet().retainAll(hot);codeBundleHashes.keySet().removeIf(id->!rows.containsKey(id)||!rows.get(id).status().startsWith("CODE_"));
        for(var d:rows.values()){var player=server.getPlayerList().getPlayer(d.recipient());if(player==null||Objects.equals(sentRevision.get(d.id()),d.revision()))continue;if(hot.contains(d.id()))sentRevision.put(d.id(),d.revision());if(Set.of("REVOKED","EXPIRED","CLOSE_REQUESTED").contains(d.status())&&d.sessionId()!=null)sessions.retire(d.recipient(),d.sessionId(),d.viewId());String channel=Set.of("REVOKED","EXPIRED","CLOSE_REQUESTED").contains(d.status())?"deliveryRetired":d.status().equals("OFFERED")||d.status().equals("SUSPENDED")?"deliveryNotice":"deliveryUpdated";send(player,UUID.randomUUID(),channel,summary(d));}
    }catch(Exception e){MineAgentRuntimeMod.LOGGER.warn("Delivery reconciliation failed code={}",e.getClass().getSimpleName());}}
    public ServerUiFeedback feedback(){return feedback;}
    String feedbackSubscriptionToken(UUID owner,UUID agent,dev.mineagent.runtime.core.feedback.FeedbackSubscriptionFilter filter,String mode)throws Exception{
        requireThread();var asset=new ContentDeliveryStore.Asset(filter.packageId(),filter.packageRevision(),filter.canonicalSha256(),filter.entry(),"CONTENT","Feedback subscription",filter.policySha256());
        var policy=dev.mineagent.runtime.core.feedback.UiFeedbackPolicy.fromPackage(packageFor(owner,asset),filter.entry(),ServerPackageRuntime.get(server).worldContent()::read);
        if(!policy.sha256().equals(filter.policySha256()))return null;for(String event:filter.events())if(mode.equals("AGENT_WAKE")&&!policy.event(event).mode().equals("AGENT_WAKE"))return null;
        String token=stableAuthority(owner,agent,asset);return token==null?null:token+"|"+epochs(owner);
    }

    ContentDeliveryStore.Delivery feedbackRow(UUID viewer,UUID id)throws Exception{return store.recipient(viewer,id);}
    String feedbackToken(ContentDeliveryStore.Delivery row){if(row.origin()==null||row.asset().feedbackPolicySha256().isEmpty()||System.currentTimeMillis()>=row.expiresAt()||Set.of("REVOKED","EXPIRED","FAILED","REJECTED","UNAVAILABLE").contains(row.status()))return null;String token=senderAuthority(row);return Objects.equals(token,row.issuedAuthority())?token:null;}
    dev.mineagent.runtime.core.feedback.UiFeedbackPolicy feedbackPolicy(ContentDeliveryStore.Delivery row)throws Exception{
        var pkg=packageFor(row.owner(),row.asset());var policy=dev.mineagent.runtime.core.feedback.UiFeedbackPolicy.fromPackage(pkg,row.asset().entry(),ServerPackageRuntime.get(server).worldContent()::read);
        if(!policy.sha256().equals(row.asset().feedbackPolicySha256()))throw new SecurityException("FEEDBACK_POLICY_CHANGED");return policy;
    }
    boolean feedbackVisible(Session session){var open=opened.get(DeliveryProtocol.leaseId(session.binding()));return open!=null&&open.visible&&Objects.equals(open.player,server.getPlayerList().getPlayer(session.binding().viewerPlayerId()))&&authorize(session)==Code.OK;}
    void interacted(ContentDeliveryStore.Delivery row,Session session,String document)throws Exception{store.interacted(row.recipient(),row.id(),row.leaseId(),session.sessionId(),document);}
    public Map<String,String> forModel(ManagedTask task,String tool,Map<String,String> after){if(!DeliveryToolRequest.TOOLS.contains(tool))return after;try{authorizeSender(context(task,UUID.randomUUID()));if(!epochs(task.ownerPlayerId()).equals(after.get("authorityEpoch")))throw new SecurityException();var request=DeliveryToolRequest.parse(tool,after.get("request"));if(tool.equals("inspect_content_contract"))contractPackage(task.ownerPlayerId(),request);else if(tool.equals("offer_content")||tool.equals("query_deliveries")){UUID batch=tool.equals("query_deliveries")?request.id():UUID.fromString(json.readTree(after.get("result")).path("id").asText());var rows=store.query(context(task,UUID.randomUUID()),batch);if(rows.isEmpty())throw new SecurityException("DELIVERY_BATCH_MISSING");for(var row:rows)receiptResource(row);}else receiptResource(store.inspect(context(task,UUID.randomUUID()),request.id()));return after;}catch(Exception denied){return Map.of("executionMode","DELIVERY_OBSERVATION_REDACTED","reason","CURRENT_DELIVERY_AUTHORITY_REQUIRED");}}
    private void send(ServerPlayer viewer,UUID id,String channel,Object value){try{PacketDistributor.sendToPlayer(viewer,new UiPayloads.Event(id,channel,json.writeValueAsString(value)));}catch(Exception e){throw new IllegalStateException("DELIVERY_SEND_FAILED",e);}}
    private RuntimePackage contractPackage(UUID owner,DeliveryToolRequest r){var pkg=ServerPackageRuntime.get(server).ownedPackage(owner,r.packageId(),r.packageRevision()).orElseThrow(()->new SecurityException("CONTENT_CONTRACT_NOT_OWNED"));if(!pkg.canonicalSha256().equals(r.canonical()))throw new SecurityException("CONTENT_CONTRACT_CHANGED");return pkg;}
    public java.util.function.BooleanSupplier contractWorkerPermit(ManagedTask task,Map<String,String> after){return workerPermit(task,"inspect_content_contract",after);}
    public java.util.function.BooleanSupplier workerPermit(ManagedTask task,String tool,Map<String,String> after){var valid=new java.util.concurrent.atomic.AtomicBoolean(true);return ()->{if(!valid.get())return false;try{boolean current=server.isSameThread()?after.equals(forModel(task,tool,after)):server.submit(()->after.equals(forModel(task,tool,after))).get(3,java.util.concurrent.TimeUnit.SECONDS);if(!current)valid.set(false);return current;}catch(Exception failure){valid.set(false);return false;}};}
    private void requireThread(){if(closed||!server.isSameThread())throw new IllegalStateException("DELIVERY_THREAD");}
    @Override public void close(){closed=true;io.shutdownNow();transfers.clear();opened.clear();transferOwners.clear();codeTransferOwners.clear();codeBundleHashes.clear();try{try{feedback.close();}finally{store.close();}}catch(Exception e){throw new IllegalStateException("DELIVERY_CLOSE",e);}}
}
