package dev.mineagent.runtime.neoforge.ui;
import com.fasterxml.jackson.databind.*;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;
import net.minecraft.server.MinecraftServer;
import net.minecraft.core.BlockPos;
import net.minecraft.world.level.block.Blocks;
import java.nio.file.*;
import java.util.*;

/** Real ordinary-chat build acceptance. Fixture only clears/floors an isolated test plot. */
public final class WorldGeometrySmokeServer {
    public static volatile boolean ready,clientReady,complete;
    public static volatile String failure="";
    public static volatile UUID agent;
    public static volatile long rounds,calls;
    private static final ObjectMapper JSON=new ObjectMapper();
    private static final List<Map<String,Object>> evidence=new ArrayList<>();
    private static final Map<String,String> sources=new LinkedHashMap<>();
    private static final Set<String> applied=new LinkedHashSet<>();
    private static int stage,step;private static boolean busy;private static String testPlan;private static final List<String> negatives=new ArrayList<>();
    public static boolean active(){return Boolean.getBoolean("mineagent.conversationAgentSmoke")&&Boolean.getBoolean("mineagent.conversationAgentReal")&&Set.of("world_geometry","world_geometry_zero").contains(System.getProperty("mineagent.conversationAgentScenario",""));}
    public static boolean zero(){return System.getProperty("mineagent.conversationAgentScenario","").equals("world_geometry_zero");}
    public static void progress(long r,long c){if(active()){rounds=r;calls=c;}}
    public static void observe(String tool,JsonNode args,Map<String,Object> value){if(!active()||stage!=1)return;evidence.add(Map.of("tool",tool,"arguments",args,"receipt",value));if(tool.equals("plan_world_geometry")&&value.containsKey("planId"))sources.put(value.get("planId").toString(),args.path("source").asText());if(tool.equals("apply_world_geometry")&&"APPLIED".equals(value.get("status")))applied.add(args.path("plan_id").asText());}
    private static void save(MinecraftServer s,String name,Object value)throws Exception{Files.writeString(Files.createDirectories(s.getServerDirectory().resolve("world-geometry-smoke")).resolve(name+".json"),JSON.writeValueAsString(value));}
    private static void require(boolean v,String reason){if(!v)throw new IllegalStateException(reason);}
    public static void tick(MinecraftServer s){if(complete||!failure.isEmpty())return;var p=s.getPlayerList().getPlayers().stream().filter(v->!(v instanceof dev.mineagent.runtime.neoforge.body.MineAgentPlayer)).findFirst().orElse(null);if(p==null)return;try{
        if(!ready){s.getPlayerList().op(p.nameAndId());p.setGameMode(net.minecraft.world.level.GameType.CREATIVE);for(int x=-1;x<=5;x++)for(int z=-1;z<=2;z++)p.level().getChunk(x,z);
            for(var pos:BlockPos.betweenClosed(new BlockPos(-8,110,-8),new BlockPos(79,121,30)))p.level().setBlock(pos,pos.getY()==110?Blocks.SMOOTH_STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),2);
            p.teleportTo(p.level(),-4.5,111,5.5,Set.of(),-90,10,true);agent=MineAgentRuntimeServices.bodies(s).createPersistentAt("建筑师",p.getUUID(),p.level(),p.position().add(0,0,3)).agentId();ready=true;return;}
        if(!clientReady||busy)return;
        if(stage==0){ // actual Native safety/state tests, no model and no duplicate side effects
            var a=JSON.createObjectNode();String source="{\"origin\":[0,111,25],\"parts\":[{\"kind\":\"box\",\"min\":[0,0,0],\"max\":[2,0,0],\"material\":\"minecraft:stone\"}]}";
            if(step==0||step==2||step==5){a.put("source",source);busy=true;int at=step;ConversationWorldGeometry.plan(p,agent,a,()->true).whenComplete((r,e)->s.execute(()->{try{require(e==null&&"PLANNED".equals(r.get("status")),"NEGATIVE_PLAN_"+r);testPlan=r.get("planId").toString();step=at+1;}catch(Exception ex){failure=ex.toString();}finally{busy=false;}}));return;}
            if(step==1||step==3||step==6){a.put("plan_id",testPlan);int at=step;if(at==1)p.level().setBlockAndUpdate(new BlockPos(0,111,25),Blocks.GOLD_BLOCK.defaultBlockState());busy=true;var permit=new java.util.concurrent.atomic.AtomicBoolean(true);var pending=ConversationWorldGeometry.apply(p,agent,a,permit::get);if(at==6)permit.set(false);pending.whenComplete((r,e)->s.execute(()->{try{require(e==null,"NEGATIVE_APPLY_EXCEPTION");if(at==1){require("REJECTED".equals(r.get("status"))&&"GEOMETRY_STATE_CHANGED".equals(r.get("error"))&&((Number)r.get("written")).intValue()==0,"STALE_PLAN_WROTE");negatives.add("stale_before_write_rejected");}else if(at==3){require("APPLIED".equals(r.get("status")),"NATIVE_APPLY_FAILED_"+r);negatives.add("native_write_readback");}else if(at==6){require("REJECTED".equals(r.get("status"))&&((Number)r.get("written")).intValue()==0,"CANCEL_WROTE");negatives.add("cancel_before_write_releases");}step=at+1;}catch(Exception ex){failure=ex.toString();}finally{busy=false;}}));return;}
            if(step==4){try{ConversationWorldGeometry.apply(p,agent,JSON.createObjectNode().put("plan_id",testPlan),()->true);throw new IllegalStateException("REPLAY_ALLOWED");}catch(IllegalStateException expected){require("GEOMETRY_PLAN_ALREADY_CONSUMED".equals(expected.getMessage()),"REPLAY_WRONG_REJECTION");}negatives.add("consumed_plan_replay_rejected");step=5;return;}
            if(step==7){save(s,"native-preflight",negatives);if(zero()){busy=true;extraChecks(p).whenComplete((v,e)->s.execute(()->{try{if(e!=null)throw new IllegalStateException(e);complete=true;save(s,"server",Map.of("status","GEOMETRY_NATIVE_ZERO_VERIFIED","checks",negatives));}catch(Exception ex){failure=ex.toString();}finally{busy=false;}}));step=8;}else stage=1;return;}
        }
        if(stage==1&&!zero()){
            if(s.getTickCount()%100==0)save(s,"progress",Map.of("rounds",rounds,"calls",calls,"applied",applied.size(),"evidence",evidence));
            var store=ServerConversations.get(s).store();var cs=store.list(p.getUUID(),agent,"ALL","",0,20).conversations();if(cs.isEmpty())return;var c=cs.getFirst();if(c.messageCount()<2||!c.activeOperation().isEmpty())return;var ctx=store.context(p.getUUID(),agent,c.conversationId(),null).orElseThrow();save(s,"conversation",ctx);save(s,"tools",evidence);save(s,"sources",sources);
            require(ctx.requestState().equals("COMPLETE"),"MODEL_GEOMETRY_"+ctx.errorCode());require(ctx.modelReceipt()!=null&&ctx.modelReceipt().requestedModel().equals("deepseek-flash"),"REAL_MODEL_RECEIPT");require(rounds>12&&calls>32,"OLD_LIMITS_NOT_CROSSED_"+rounds+"_"+calls);require(applied.size()>=14,"GEOMETRY_EXHIBITS_MISSING_"+applied.size());
            var kinds=new TreeSet<String>();var transforms=new TreeSet<String>();var materialModes=new TreeSet<String>();boolean replacement=false,fullState=false;var finalCells=new LinkedHashMap<dev.mineagent.runtime.core.geometry.WorldGeometry.Pos,dev.mineagent.runtime.core.geometry.WorldGeometry.Cell>();
            for(String id:applied){JsonNode n=JSON.readTree(sources.get(id));replacement|=n.has("replace");for(var part:n.path("parts")){kinds.add(part.path("kind").asText());if(part.path("material").isObject())materialModes.add(part.path("material").path("mode").asText());fullState|=part.path("material").toString().contains("facing=");for(var t:part.path("transforms"))transforms.add(t.path("op").asText());}var g=dev.mineagent.runtime.core.geometry.WorldGeometry.parse(sources.get(id));for(var cell:g.cells())finalCells.put(cell.pos(),cell);}
            require(kinds.containsAll(Set.of("line","plane","box","polygon","slope","curve","surface","cylinder","dome")),"MISSING_SHAPES_"+kinds);require(transforms.containsAll(Set.of("mirror","rotate","array","path")),"MISSING_TRANSFORMS_"+transforms);require(replacement&&fullState&&!materialModes.isEmpty(),"MISSING_MATERIAL_STATE_REPLACEMENT");
            int actual=0;var states=new TreeMap<String,Integer>();for(var pos:finalCells.keySet()){var b=p.level().getBlockState(new BlockPos(pos.x(),pos.y(),pos.z()));if(!b.isAir())actual++;states.merge(net.minecraft.commands.arguments.blocks.BlockStateParser.serialize(b),1,Integer::sum);}require(actual>100,"NO_ACTUAL_BUILD");
            save(s,"server",Map.of("status","REAL_GEOMETRY_AND_UNLIMITED_LOOP_NATIVE_VERIFIED","rounds",rounds,"calls",calls,"appliedPlans",applied.size(),"actualNonAir",actual,"states",states,"kinds",kinds,"transforms",transforms,"nativeChecks",negatives));complete=true;
        }
    }catch(Exception e){failure=e.toString();try{save(s,"failure",Map.of("error",failure,"stage",stage,"step",step,"rounds",rounds,"calls",calls,"evidence",evidence));}catch(Exception ignored){}}}
    private static java.util.concurrent.CompletableFuture<Void> extraChecks(net.minecraft.server.level.ServerPlayer p){
        var s=p.level().getServer();String stairs="{\"origin\":[0,111,25],\"parts\":[{\"kind\":\"box\",\"min\":[0,0,0],\"max\":[0,0,0],\"material\":\"minecraft:oak_stairs[facing=north,half=top,shape=straight,waterlogged=false]\",\"transforms\":[{\"op\":\"rotate\",\"turns\":1},{\"op\":\"mirror\",\"axis\":\"x\"}]}]}";
        return ConversationWorldGeometry.plan(p,agent,JSON.createObjectNode().put("source",stairs),()->true).thenCompose(r->{require("PLANNED".equals(r.get("status")),"ORIENTATION_PLAN_"+r);testPlan=r.get("planId").toString();try{ConversationWorldGeometry.apply(p,UUID.randomUUID(),JSON.createObjectNode().put("plan_id",testPlan),()->true);throw new IllegalStateException("WRONG_AGENT_ALLOWED");}catch(IllegalStateException expected){require("GEOMETRY_PLAN_SCOPE".equals(expected.getMessage()),"SCOPE_ERROR");}negatives.add("other_agent_rejected");return ConversationWorldGeometry.apply(p,agent,JSON.createObjectNode().put("plan_id",testPlan),()->true);})
        .thenCompose(r->{require("APPLIED".equals(r.get("status")),"ORIENTATION_APPLY_"+r);String got=net.minecraft.commands.arguments.blocks.BlockStateParser.serialize(p.level().getBlockState(new BlockPos(0,111,25)));require(got.contains("facing=west")&&got.contains("half=top"),"ORIENTATION_ACTUAL_"+got);negatives.add("native_rotation_mirror_full_state");String mask="{\"origin\":[0,111,25],\"replace\":[\"minecraft:stone\"],\"parts\":[{\"kind\":\"box\",\"min\":[0,0,0],\"max\":[4,0,0],\"material\":\"minecraft:gold_block\"}]}";return ConversationWorldGeometry.plan(p,agent,JSON.createObjectNode().put("source",mask),()->true);})
        .thenCompose(r->{require(((Number)r.get("selected")).intValue()==2&&((Number)r.get("maskSkipped")).intValue()==3,"MASK_SAMPLING_"+r);return ConversationWorldGeometry.apply(p,agent,JSON.createObjectNode().put("plan_id",r.get("planId").toString()),()->true);})
        .thenCompose(r->{require("APPLIED".equals(r.get("status"))&&p.level().getBlockState(new BlockPos(0,111,25)).is(Blocks.OAK_STAIRS)&&p.level().getBlockState(new BlockPos(1,111,25)).is(Blocks.GOLD_BLOCK)&&p.level().getBlockState(new BlockPos(3,111,25)).isAir(),"MASK_ACTUAL");negatives.add("local_replace_preserves_other_states_and_air");p.level().setBlockAndUpdate(new BlockPos(0,111,28),Blocks.CHEST.defaultBlockState());String source="{\"origin\":[0,111,28],\"parts\":[{\"kind\":\"box\",\"min\":[0,0,0],\"max\":[0,0,0],\"material\":\"minecraft:stone\"}]}";return ConversationWorldGeometry.plan(p,agent,JSON.createObjectNode().put("source",source),()->true);})
        .thenAccept(r->{require("REJECTED".equals(r.get("status"))&&"GEOMETRY_EXISTING_BLOCK_ENTITY".equals(r.get("error"))&&p.level().getBlockState(new BlockPos(0,111,28)).is(Blocks.CHEST),"BLOCK_ENTITY_NOT_PRESERVED");negatives.add("block_entity_rejected_and_preserved");s.getPlayerList().deop(p.nameAndId());try{ConversationWorldGeometry.plan(p,agent,JSON.createObjectNode().put("source",stairs),()->true);throw new IllegalStateException("UNPRIVILEGED_PLAN_ALLOWED");}catch(IllegalStateException expected){require("GEOMETRY_PERMISSION".equals(expected.getMessage()),"PERMISSION_ERROR");}finally{s.getPlayerList().op(p.nameAndId());}negatives.add("actual_op_required");});
    }
    public static boolean preflightDone(){return stage==1;}
}
