package dev.mineagent.runtime.neoforge.skill;
import com.fasterxml.jackson.databind.ObjectMapper;import com.fasterxml.jackson.databind.node.ObjectNode;
import dev.mineagent.runtime.agent.body.BodyControlCoordinator;
import dev.mineagent.runtime.neoforge.body.*;
import dev.mineagent.runtime.neoforge.task.AutonomousPlayerAgent;
import net.minecraft.core.BlockPos;import net.minecraft.server.level.ServerPlayer;import net.minecraft.world.entity.Entity;import net.minecraft.world.phys.Vec3;
import java.util.*;

/** Frames drive the authenticated local input controller; no server-side real-player movement/attack. */
public final class PlayerSkillActor implements SkillActor {
    private static final ObjectMapper JSON=new ObjectMapper();private final ServerPlayer player;private final UUID skill;private final boolean emergency;private final Object level;private final net.minecraft.world.level.GameType mode;
    private final BodyControlCoordinator controls=new BodyControlCoordinator();private final NativeNavigationIntent navigation=new NativeNavigationIntent();private Vec3 destination,aim;private UUID navOperation=UUID.randomUUID(),selectionOperation;private int selectionSlot=-1;private net.minecraft.world.item.Item selectionWanted;private String lastAction="";
    private boolean sprinting,crouching;private ObjectNode motion;private String hand="";private UUID offhandOperation;private int offhandSlot=-1;private net.minecraft.world.item.ItemStack offhandWanted=net.minecraft.world.item.ItemStack.EMPTY;
    private List<dev.mineagent.runtime.core.task.SurfacePathfinder.PathStep> checkedRoute;
    public String moveTactically(UUID session,List<dev.mineagent.runtime.core.task.SurfacePathfinder.PathStep> route){if(!inputReady())return "PAUSED_INPUT";if(route!=checkedRoute){if(!navigation.followCheckedRoute(player,route))return "ROUTE_CHANGED";checkedRoute=route;destination=null;navOperation=UUID.randomUUID();}var step=terrain(session,navigation.tick(player));if(step!=null)send(session,"MOVE",navOperation,(navigation.recovery().active()?NativeTraversalEvaluator.point(step.to()):navigation.waypoint(step)),0,-1,step.action().name());else if(!navigation.recovery().active())send(session,"HALT_MOTION",navOperation,player.position(),0,-1,"");return navigation.status();}
    public PlayerSkillActor(ServerPlayer player,UUID agent,UUID skill,String label)throws Exception{this.player=player;this.skill=skill;this.emergency=false;this.level=player.level();this.mode=player.gameMode.getGameModeForPlayer();AutonomousPlayerAgent.beginLocalSkill(player,agent,skill,label);}
    private PlayerSkillActor(ServerPlayer player,UUID session){this.player=player;this.skill=session;this.emergency=true;this.level=player.level();this.mode=player.gameMode.getGameModeForPlayer();}
    static PlayerSkillActor emergency(ServerPlayer player){UUID id=AutonomousPlayerAgent.emergencySession(player);return id==null?null:new PlayerSkillActor(player,id);}
    public ServerPlayer player(){return player;}public BodyControlCoordinator controls(){return controls;}
    public boolean current(){return player.level()==level&&player.gameMode.getGameModeForPlayer()==mode&&(emergency?AutonomousPlayerAgent.emergencyCurrent(player,skill):AutonomousPlayerAgent.localSkillActive(player,skill));}
    public boolean inputReady(){return current()&&!player.isPassenger()&&(player.containerMenu==player.inventoryMenu||player.containerMenu instanceof dev.mineagent.runtime.neoforge.ui.AgentInventoryMenu)&&(emergency?AutonomousPlayerAgent.emergencyCurrent(player,skill):AutonomousPlayerAgent.localSkillReady(player,skill));}
    private void send(UUID session,String action,UUID operation,Vec3 target,int slot,int entity,String pathAction){
        if(!current()||!controls.owns(session,dev.mineagent.runtime.api.agent.BodyDomain.MOVEMENT))throw new IllegalStateException("PLAYER_SKILL_CONTROL_CHANGED");
        if(!action.equals("HOTBAR")&&selectionOperation!=null&&player.getMainHandItem().is(selectionWanted))selectionOperation=null;lastAction=action;ObjectNode frame=JSON.createObjectNode().put("action",action).put("operation",operation.toString()).put("slot",slot).put("entity",entity).put("pathAction",pathAction).put("sprinting",sprinting).put("sneaking",crouching);if(action.equals("ATTACK_ENTITY")){var boost=ActorEnhancements.forBody(player);boolean enabled=ActorEnhancements.boost(player);frame.put("boostCritical",enabled&&boost.enhancedCritical()).put("boostMicroHop",enabled&&boost.microHop());}frame.putArray("target").add(target.x).add(target.y).add(target.z);if(!hand.isEmpty())frame.put("hand",hand);if(!action.equals("MOVE")&&!action.equals("HALT")&&motion!=null)frame.set("motion",motion.deepCopy().put("sneaking",crouching));if(aim!=null)frame.putArray("aim").add(aim.x).add(aim.y).add(aim.z);if(action.equals("MOVE"))motion=frame.deepCopy();if(emergency){AutonomousPlayerAgent.emergencyFrame(player,skill,frame);return;}AutonomousPlayerAgent.localSkillFrame(player,skill,frame,switch(action){case "MOVE"->"前往操作位置";case "BREAK"->"挖掘目标方块";case "PLACE_BLOCK"->"搭建通行支点";case "USE_BLOCK"->"操作目标方块";case "HOLD"->"使用手中装备";case "RELEASE"->"释放蓄力";case "ATTACK_ENTITY"->"攻击选定目标";case "HOTBAR"->"选择装备";case "USE_ONCE"->"使用手中物品";default->"等待下一步";});
    }
    public String move(UUID session,Vec3 target){checkedRoute=null;if(destination==null){navigation.start(target,.2);destination=target;navOperation=UUID.randomUUID();}else if(destination.distanceToSqr(target)>.09){navigation.update(target);destination=target;}
        if(!inputReady())return "PAUSED_INPUT";var step=terrain(session,navigation.tick(player));if(step!=null)send(session,"MOVE",navOperation,(navigation.recovery().active()?NativeTraversalEvaluator.point(step.to()):navigation.waypoint(step)),0,-1,step.action().name());else if(!navigation.recovery().active())send(session,"HALT",navOperation,player.position(),0,-1,"");return navigation.status();}
    private dev.mineagent.runtime.core.task.SurfacePathfinder.PathStep terrain(UUID session,dev.mineagent.runtime.core.task.SurfacePathfinder.PathStep step){
        if(!navigation.recovery().active())return step;motion=null;sprinting=crouching=false;
        var result=navigation.recovery().tick(new NativeTerrainRecovery.Actions(){
            public boolean current(){return PlayerSkillActor.this.current()&&controls.owns(session,dev.mineagent.runtime.api.agent.BodyDomain.MOVEMENT);}
            public boolean select(int slot){return PlayerSkillActor.this.select(session,slot);}
            public void aim(Vec3 point){aimImmediately(session,point);}
            public void jump(UUID operation){send(session,"JUMP",operation,player.position(),0,-1,"");}
            public void mine(UUID operation,BlockPos at){var visible=NativeTerrainRecovery.visibleMiningPoint(player,at);if(visible!=null)send(session,"BREAK",operation,visible,0,-1,"");}
            public void place(UUID operation,net.minecraft.world.phys.BlockHitResult hit){var face=hit.getDirection();send(session,"PLACE_BLOCK",operation,hit.getLocation().subtract(new Vec3(face.getStepX(),face.getStepY(),face.getStepZ()).scale(.001)),0,face.get3DDataValue(),"");}
            public void cancel(UUID operation){motion=null;aim=null;send(session,"HALT",UUID.randomUUID(),player.position(),0,-1,"");}
        });
        if(result.changed())navigation.recheckAfterTerrain();return result.move();
    }
    public boolean recovering(){return navigation.recovery().active();}
    public boolean recover(UUID session,Vec3 target){
        if(!inputReady())return false;if(!navigation.recovery().active()&&!navigation.recovery().request(player,target,"TACTICAL_ROUTE_EXHAUSTED"))return false;
        var step=terrain(session,null);if(step!=null)send(session,"MOVE",navOperation,NativeTraversalEvaluator.point(step.to()),0,-1,step.action().name());return true;
    }
    public void aim(UUID session,Vec3 target){aim=target;}
    public void crouch(UUID session,boolean enabled){crouching=enabled;if(enabled)sprinting=false;send(session,"SNEAK",navOperation,player.position(),0,-1,"");}
    public void sprint(UUID session,boolean enabled){sprinting=enabled;}
    public void jump(UUID session){if(motion==null&&inputReady()){send(session,"JUMP",navOperation,player.position(),0,-1,"");return;}if(motion!=null&&inputReady()){navigation.tacticalJump(player);motion.put("jump",true);AutonomousPlayerAgent.localSkillFrame(player,skill,motion.deepCopy(),"短跳调整走位");}}
    public void haltMotion(UUID session){checkedRoute=null;motion=null;sprinting=crouching=false;navigation.stop("HOLD_POSITION");destination=null;send(session,"HALT_MOTION",navOperation,aim==null?player.getEyePosition().add(player.getLookAngle()):aim,0,-1,"");}
    public boolean select(UUID session,int slot){if(!inputReady())return false;if(selectionOperation==null||selectionSlot!=slot){selectionSlot=slot;selectionWanted=player.getInventory().getItem(slot).getItem();selectionOperation=UUID.randomUUID();}send(session,"HOTBAR",selectionOperation,player.position(),slot,-1,"");return slot<9&&player.getInventory().getSelectedSlot()==slot;}
    public boolean equipOffhand(UUID session,int slot){if(!inputReady())return false;if(offhandOperation==null||offhandSlot!=slot){offhandOperation=UUID.randomUUID();offhandSlot=slot;offhandWanted=player.getInventory().getItem(slot).copy();}send(session,"OFFHAND",offhandOperation,player.position(),slot,-1,"");boolean applied=net.minecraft.world.item.ItemStack.isSameItemSameComponents(player.getOffhandItem(),offhandWanted);if(applied)offhandOperation=null;return applied;}
    public void useHand(UUID session,UUID op,net.minecraft.world.InteractionHand value){if(player.isUsingItem()&&player.getUsedItemHand()!=value)player.stopUsingItem();hand=value.name();try{useItem(session,op,true);}finally{hand="";}}
    public void aimImmediately(UUID session,Vec3 target){aim=target;send(session,"LOOK",navOperation,target,0,-1,"");}
    public void useOnce(UUID session,UUID op,net.minecraft.world.InteractionHand value){hand=value.name();try{useItem(session,op,false);}finally{hand="";}}
    public void breakBlock(UUID session,UUID op,BlockPos target){send(session,"BREAK",op,Vec3.atCenterOf(target),0,-1,"");}
    public void useBlock(UUID session,UUID op,BlockPos target){send(session,"USE_BLOCK",op,InteractionTargetResolver.topHit(player,target),0,-1,"");}
    public void useItem(UUID session,UUID op,boolean hold){send(session,hold?"HOLD":"USE_ONCE",op,aim==null?player.getEyePosition().add(player.getLookAngle().scale(4)):aim,0,-1,"");}
    public void releaseItem(UUID session,UUID op){send(session,"RELEASE",op,aim==null?player.getEyePosition():aim,0,-1,"");}
    public void attack(UUID session,UUID op,Entity entity){if(entity instanceof net.minecraft.world.entity.LivingEntity living)BoostRuntime.arm(player,living,op);send(session,"ATTACK_ENTITY",op,dev.mineagent.runtime.neoforge.body.NativeTargetGeometry.point(player,entity).orElse(entity.getEyePosition()),0,entity.getId(),"");}
    public void stop(UUID session){BoostRuntime.cancel(player);if(emergency){AutonomousPlayerAgent.emergencyFrame(player,skill,null);return;}checkedRoute=null;motion=null;sprinting=crouching=false;if(selectionOperation!=null&&player.getMainHandItem().is(selectionWanted))selectionOperation=null;lastAction="HALT";navigation.stop("CANCELLED");destination=null;aim=null;player.stopUsingItem();if(current()){var frame=JSON.createObjectNode().put("action","HALT").put("operation",UUID.randomUUID().toString());frame.putArray("target").add(player.getX()).add(player.getY()).add(player.getZ());AutonomousPlayerAgent.localSkillFrame(player,skill,frame,"等待下一步");}}
    public Map<String,Object> observation(){return Map.of("adapter","REAL_PLAYER_INPUT","entityId",player.getId(),"ready",inputReady(),"navigation",navigation.status(),"search",navigation.evidence(),"position",List.of(player.getX(),player.getY(),player.getZ()),"mainHand",player.getMainHandItem().toString(),"selectedSlot",player.getInventory().getSelectedSlot(),"frameAction",lastAction);}
    public void report(String reason,boolean complete){if(current())AutonomousPlayerAgent.localSkillSummary(player,skill,complete?"本次任务已完成，等待新指令":switch(reason){case "TERRAIN_ESCAPE"->"检查出口，逐步脱困";case "NORMAL_CRITICAL_WINDOW"->"利用真实下落时机出手";case "REACQUIRE_THREAT"->"检查上次发现敌人的位置";case "JUMP_TAP"->"短跳调整攻击节奏，检查落点";case "AD_LEFT"->"向左变向，避开攻击区域";case "AD_RIGHT"->"向右变向，避开攻击区域";case "RANGED_BAIT"->"移出远程火力，再寻找接近机会";case "COUNTER_APPROACH"->"把握攻击间隔，疾跑反击";case "STAP_SPACE"->"短退控距，等待下一次出手";case "COMBO_PRESSURE"->"跟进实际击退，衔接下一击";case "COMBO_SPACING"->"保持攻击边缘，等待冷却";case "BREAKTHROUGH"->"攻击阻挡者，争取突围";case "CONTACT_ESCAPE"->"摆脱持续近身攻击";case "MELEE_EXIT"->"攻击后脱离";case "MELEE_APPROACH"->"寻找出手位置";case "LURE"->"牵引敌群，调整退路";case "RETREAT"->"脱离交战";case "RECOVER"->"寻找安全恢复位置";case "BOW_DRAW"->"保持距离并蓄力";case "BOW_RELEASE"->"释放弓箭并检查命中";case "WAITING_FOR_TACTICAL_PATH"->"计算安全退路";case "NO_SAFE_EXIT"->"暂未找到安全退路，防御中";case "EATING_IN_SAFE_SPACE"->"在安全位置进食";case "COOLDOWN_GUARD"->"等待攻击冷却，保持防御";case "WAITING_FOR_CROP_GROWTH"->"等待作物成熟";case "WAITING_FOR_REAL_BITE"->"等待鱼咬钩";case "SEED_REQUIRED_FOR_REPLANT","SEED_NOT_READY"->"等待补种种子";case "INVENTORY_FULL"->"背包已满，等待整理";case "FOLLOW_DISTANCE_SATISFIED","FOLLOW_HYSTERESIS"->"保持跟随距离";case "WAYPOINT_DWELL"->"在路标处停留";case "WAITING_CHUNKS"->"等待区块加载";case "NEXT_CAST"->"准备下一次抛竿";default->"等待下一步";},complete);}
}
