org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.106
moddev_version=2.0.146

mod_id=mineagent_runtime
mod_name=MineAgent Runtime
mod_license=Apache-2.0
mod_version=0.1.0-SNAPSHOT
mod_group_id=dev.mineagent.runtime

junit_version=6.1.3
jackson_version=2.22.2
sqlite_jdbc_version=3.53.4.0
rhino_version=2101.2.8-build.91
