package dev.mineagent.runtime.core.interaction;
import com.fasterxml.jackson.databind.*;import java.util.*;
/** Data-defined native event policy. No reflection instructions or arbitrary host code. */
public record EntityLogicSpec(String name,EntitySelector selector,Set<String> block,double taken,double dealt,double knockback,List<Double> movement,Set<String> blockedGoals,Map<String,List<Action>> callbacks,int cooldown,String source){
 public static final Set<String> EVENTS=Set.of("interact","attack","attacked","hurt","knockback","target","move","tick");
 public record Action(String type,String value,int ticks,int amplifier){}
 public static EntityLogicSpec parse(String source){try{
  if(source==null||source.length()>14000)throw new IllegalArgumentException("ENTITY_RULE_SIZE");var j=new ObjectMapper(com.fasterxml.jackson.core.JsonFactory.builder().enable(com.fasterxml.jackson.core.StreamReadFeature.STRICT_DUPLICATE_DETECTION).build()).enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS).readTree(source);keys(j,"name","dimension","entity_id","entity_type","species_id","block","damage_taken_multiplier","damage_dealt_multiplier","knockback_multiplier","movement_scale","blocked_goals","callbacks","cooldown_ticks");var selector=EntitySelector.parse(j);String name=j.path("name").asText("实体规则");if(name.isBlank()||name.length()>80)throw new IllegalArgumentException("ENTITY_RULE_NAME");
  var block=strings(j.path("block"));if(!EVENTS.containsAll(block))throw new IllegalArgumentException("ENTITY_RULE_EVENT");var goals=strings(j.path("blocked_goals"));for(String g:goals)if(!g.matches("[A-Za-z_$][A-Za-z0-9_.$]{0,239}"))throw new IllegalArgumentException("ENTITY_RULE_GOAL");
  var movement=vector(j.path("movement_scale"),1,0,8);var callbacks=new LinkedHashMap<String,List<Action>>();if(j.has("callbacks")){if(!j.get("callbacks").isObject())throw new IllegalArgumentException("ENTITY_RULE_CALLBACKS");for(var entry:j.get("callbacks").properties()){if(!EVENTS.contains(entry.getKey())||!entry.getValue().isArray()||entry.getValue().size()>16)throw new IllegalArgumentException("ENTITY_RULE_CALLBACKS");var actions=new ArrayList<Action>();for(var a:entry.getValue()){keys(a,"type","value","ticks","amplifier");String type=a.path("type").asText(),value=a.path("value").asText();if(!Set.of("message","sound","effect","command").contains(type)||value.isBlank()||value.length()>512||Set.of("sound","effect").contains(type)&&!EntitySelector.id(value))throw new IllegalArgumentException("ENTITY_RULE_ACTION");int ticks=integer(a,"ticks",100,1,1728000),amp=integer(a,"amplifier",0,0,255);actions.add(new Action(type,value,ticks,amp));}callbacks.put(entry.getKey(),List.copyOf(actions));}}
  return new EntityLogicSpec(name,selector,block,num(j,"damage_taken_multiplier",1,0,100),num(j,"damage_dealt_multiplier",1,0,100),num(j,"knockback_multiplier",1,0,10),movement,goals,Map.copyOf(callbacks),integer(j,"cooldown_ticks",20,1,72000),new ObjectMapper().writeValueAsString(j));
 }catch(IllegalArgumentException e){throw e;}catch(Exception e){throw new IllegalArgumentException("ENTITY_RULE_INVALID",e);}}
 public static void keys(JsonNode n,String...keys){if(!n.isObject()||!Set.of(keys).containsAll(n.properties().stream().map(Map.Entry::getKey).toList()))throw new IllegalArgumentException("ENTITY_RULE_FIELDS");}
 public static double num(JsonNode n,String k,double fallback,double min,double max){if(!n.has(k))return fallback;var v=n.get(k);double d=v.asDouble();if(!v.isNumber()||!Double.isFinite(d)||d<min||d>max)throw new IllegalArgumentException("ENTITY_RULE_NUMBER");return d;}
 public static int integer(JsonNode n,String k,int fallback,int min,int max){if(!n.has(k))return fallback;if(!n.get(k).isIntegralNumber())throw new IllegalArgumentException("ENTITY_RULE_INTEGER");return (int)num(n,k,fallback,min,max);}
 public static List<Double> vector(JsonNode n,double fallback,double min,double max){if(n.isMissingNode())return List.of(fallback,fallback,fallback);if(!n.isArray()||n.size()!=3)throw new IllegalArgumentException("ENTITY_RULE_VECTOR");var values=new ArrayList<Double>();for(var v:n){double d=v.asDouble();if(!v.isNumber()||!Double.isFinite(d)||d<min||d>max)throw new IllegalArgumentException("ENTITY_RULE_VECTOR");values.add(d);}return List.copyOf(values);}
 private static Set<String> strings(JsonNode n){if(n.isMissingNode())return Set.of();if(!n.isArray()||n.size()>128)throw new IllegalArgumentException("ENTITY_RULE_ARRAY");var out=new LinkedHashSet<String>();for(var v:n){if(!v.isTextual())throw new IllegalArgumentException("ENTITY_RULE_STRING");out.add(v.asText());}return Set.copyOf(out);}
}
