// Generated by legacy189/tools/port_navigation.py from the existing 26.1.2 shared algorithm.
// Upstream SHA-256: 14a93c705d914bce55a2b42a875388d51f5d2fc2753223f5b0156e7a7a976a32
package dev.mineagent.runtime.legacy189.navigation;

/** Retry timing belongs to the intent, not to the presence of a route. */
public final class NavigationRetry {
    private long next;private int failures;
    public boolean ready(long tick){return tick>=next;}
    public void reset(long tick){next=tick;failures=0;}
    public void failed(long tick){next=tick+Math.min(160,20L<<Math.min(failures++,3));}
    public void failed(long tick,int initial,int maximum){if(initial<1||maximum<initial)throw new IllegalArgumentException("RETRY_INTERVAL");next=tick+Math.min(maximum,(long)initial<<Math.min(failures++,3));}
    public void waitUntil(long tick){next=Math.max(next,tick);}
    public void succeeded(long tick){failures=0;next=tick+20;}
    public int failures(){return failures;}
    public long next(){return next;}
}
