// Generated by legacy189/tools/port_navigation.py from the existing 26.1.2 shared algorithm.
// Upstream SHA-256: 6d63bece1b8250239e2f5b4f2e65ef9757287684657770fc26bf20b1ad68ea21
package dev.mineagent.runtime.legacy189.navigation;

/** Retry timing belongs to the intent, not to the presence of a route. */
public final class NavigationRetry {
    private long next;private int failures;
    public boolean ready(long tick){return tick>=next;}
    public void reset(long tick){next=tick;failures=0;}
    public void failed(long tick){next=tick+Math.min(160,20L<<Math.min(failures++,3));}
    public void waitUntil(long tick){next=Math.max(next,tick);}
    public void succeeded(long tick){failures=0;next=tick+20;}
    public int failures(){return failures;}
    public long next(){return next;}
}
