// Generated by legacy189/tools/port_navigation.py from the existing 26.1.2 shared algorithm.
// Upstream SHA-256: eab36c8a2b5a95803c4372737519dfea56a9f2a8252c9e5f463a215c73d87038
package dev.mineagent.runtime.legacy189.navigation;
import java.util.*;import java.util.function.*;
/** Resumable search over a shared traversal graph. A slice ending is never proof of no route. */
public final class SurfacePathfinder {
    public static final class Node{public final int x;public final int y16;public final int z;public Node(int x,int y16,int z){this.x=x;this.y16=y16;this.z=z;}public int x(){return x;}public int y16(){return y16;}public int z(){return z;}public double y(){return y16/16.0;}@Override public boolean equals(Object value){if(this==value)return true;if(!(value instanceof Node))return false;Node other=(Node)value;return x==other.x&&y16==other.y16&&z==other.z;}@Override public int hashCode(){return Objects.hash(x,y16,z);}}
    public enum Action { WALK, STEP_UP, JUMP, DROP, CROUCH, OPEN_DOOR, CLIMB, ENTER_WATER, SWIM, LEAVE_WATER }
    public enum Posture { STANDING, CROUCHING, SWIMMING }
    public enum Status { FOUND, BUDGET_EXHAUSTED, WAITING_CHUNKS, NO_PATH, INVALID_TARGET, SEARCH_LIMIT }
    public static final class PathStep{public final Node from;public final Node to;public final Action action;public final Posture posture;public final double cost;public PathStep(Node from,Node to,Action action,Posture posture,double cost){Objects.requireNonNull(from);Objects.requireNonNull(to);Objects.requireNonNull(action);Objects.requireNonNull(posture);if(!Double.isFinite(cost)||cost<=0)throw new IllegalArgumentException("PATH_COST");this.from=from;this.to=to;this.action=action;this.posture=posture;this.cost=cost;}public Node from(){return from;}public Node to(){return to;}public Action action(){return action;}public Posture posture(){return posture;}public double cost(){return cost;}@Override public boolean equals(Object value){if(this==value)return true;if(!(value instanceof PathStep))return false;PathStep other=(PathStep)value;return Objects.equals(from,other.from)&&Objects.equals(to,other.to)&&Objects.equals(action,other.action)&&Objects.equals(posture,other.posture)&&Double.compare(cost,other.cost)==0;}@Override public int hashCode(){return Objects.hash(from,to,action,posture,cost);}}
    public static final class Result{public final Status status;public final List<PathStep> steps;public final int expanded;public Result(Status status,List<PathStep> steps,int expanded){steps=copyList(steps);this.status=status;this.steps=steps;this.expanded=expanded;}public Status status(){return status;}public List<PathStep> steps(){return steps;}public int expanded(){return expanded;}@Override public boolean equals(Object value){if(this==value)return true;if(!(value instanceof Result))return false;Result other=(Result)value;return Objects.equals(status,other.status)&&Objects.equals(steps,other.steps)&&expanded==other.expanded;}@Override public int hashCode(){return Objects.hash(status,steps,expanded);}}
    public interface TraversalEvaluator {
        List<PathStep> neighbors(Node from);
        default boolean encounteredUnloaded(){return false;}
    }
    public static final class Search {
        private static final class Entry{public final Node node;public final double cost;public final double score;public Entry(Node node,double cost,double score){this.node=node;this.cost=cost;this.score=score;}public Node node(){return node;}public double cost(){return cost;}public double score(){return score;}@Override public boolean equals(Object value){if(this==value)return true;if(!(value instanceof Entry))return false;Entry other=(Entry)value;return Objects.equals(node,other.node)&&Double.compare(cost,other.cost)==0&&Double.compare(score,other.score)==0;}@Override public int hashCode(){return Objects.hash(node,cost,score);}}
        private final Node start;private final Predicate<Node> goal;private final ToDoubleFunction<Node> heuristic;private final TraversalEvaluator evaluator;
        private final PriorityQueue<Entry> open=new PriorityQueue<>(Comparator.comparingDouble(Entry::score));
        private final Map<Node,Double> costs=new HashMap<>();private final Map<Node,PathStep> parent=new HashMap<>();private final Set<Node> closed=new HashSet<>();
        private Result terminal;
        public Search(Node start,Node goal,TraversalEvaluator evaluator){this(start,goal::equals,n->distance(n,goal),evaluator);}
        public Search(Node start,Predicate<Node> goal,ToDoubleFunction<Node> heuristic,TraversalEvaluator evaluator){this.start=Objects.requireNonNull(start);this.goal=goal;this.heuristic=heuristic;this.evaluator=evaluator;costs.put(start,0.0);open.add(new Entry(start,0,heuristic.applyAsDouble(start)));}
        public Result advance(int budget,BooleanSupplier timeAvailable){
            if(budget<1)throw new IllegalArgumentException("PATH_SLICE_BUDGET");if(terminal!=null)return terminal;int remaining=budget;
            while(!open.isEmpty()&&remaining>0&&timeAvailable.getAsBoolean()){
                Entry entry=open.remove();Node n=entry.node;if(entry.cost>costs.getOrDefault(n,Double.POSITIVE_INFINITY)||!closed.add(n))continue;
                remaining--;if(goal.test(n)){ArrayList<PathStep> route=new ArrayList<PathStep>();for(Node at=n;!at.equals(start);){PathStep edge=parent.get(at);route.add(edge);at=edge.from;}Collections.reverse(route);return terminal=new Result(Status.FOUND,route,closed.size());}
                for(PathStep step:evaluator.neighbors(n)){if(!step.from.equals(n))throw new IllegalArgumentException("PATH_EDGE_ORIGIN");Node next=step.to;if(closed.contains(next))continue;double cost=entry.cost+step.cost;
                    if(cost<costs.getOrDefault(next,Double.POSITIVE_INFINITY)){costs.put(next,cost);parent.put(next,step);open.add(new Entry(next,cost,cost+heuristic.applyAsDouble(next)));}}
                if(costs.size()>131072)return terminal=new Result(Status.SEARCH_LIMIT,Collections.emptyList(),closed.size());
            }
            if(open.isEmpty())return terminal=new Result(evaluator.encounteredUnloaded()?Status.WAITING_CHUNKS:Status.NO_PATH,Collections.emptyList(),closed.size());
            return new Result(Status.BUDGET_EXHAUSTED,Collections.emptyList(),closed.size());
        }
        public Result advance(int budget){return advance(budget,()->true);}
    }
    /** Compatibility for callers that intentionally use a bounded, one-shot ground query. */
    public static List<Node> find(Node start,Node goal,int budget,Function<Node,List<Node>> neighbors){
        Search search=new Search(start,goal,n->{ArrayList<PathStep> edges=new ArrayList<PathStep>();for(Node next:neighbors.apply(n)){if(Math.abs(next.x-n.x)+Math.abs(next.z-n.z)!=1||next.y16-n.y16>20||n.y16-next.y16>48)continue;edges.add(new PathStep(n,next,Action.WALK,Posture.STANDING,1+Math.abs(next.y()-n.y())*.8));}return edges;});
        Result result=search.advance(budget);if(result.status!=Status.FOUND)return Collections.emptyList();ArrayList<Node> nodes=new ArrayList<Node>();nodes.add(start);result.steps.forEach(step->nodes.add(step.to));return copyList(nodes);
    }
    private static double distance(Node a,Node b){return Math.abs(a.x-b.x)+Math.abs(a.z-b.z)+Math.abs(a.y()-b.y())*.8;}
    private SurfacePathfinder(){}
private static <T> List<T> copyList(Collection<T> values){return Collections.unmodifiableList(new ArrayList<T>(values));}
}
