// Generated by legacy189/tools/port_navigation.py from the existing 26.1.2 shared algorithm.
// Upstream SHA-256: 7632317bd5032d17a178785e8b51f587192d96123033608318b7f49e8c90a68d
package dev.mineagent.runtime.legacy189.navigation;

import java.util.*;

/** Bounded search over ordinary movement and virtual block edits. Nothing here writes a world. */
public final class TerrainPathSearch {
    public static final class Cell{public final int x;public final int y;public final int z;public Cell(int x,int y,int z){this.x=x;this.y=y;this.z=z;}public int x(){return x;}public int y(){return y;}public int z(){return z;}public Cell add(int x,int y,int z){return new Cell(this.x+x,this.y+y,this.z+z);}public int distance(Cell b){return Math.abs(x-b.x)+Math.abs(y-b.y)+Math.abs(z-b.z);}@Override public boolean equals(Object value){if(this==value)return true;if(!(value instanceof Cell))return false;Cell other=(Cell)value;return x==other.x&&y==other.y&&z==other.z;}@Override public int hashCode(){return Objects.hash(x,y,z);}}
    public enum Kind { BREAK, PLACE }
    /** A denied edit stays denied until its observed execution context changes, never merely with time. */
    public static final class Rejections<C> {
        private static final class Key{public final Cell cell;public final Kind kind;public Key(Cell cell,Kind kind){this.cell=cell;this.kind=kind;}public Cell cell(){return cell;}public Kind kind(){return kind;}@Override public boolean equals(Object value){if(this==value)return true;if(!(value instanceof Key))return false;Key other=(Key)value;return Objects.equals(cell,other.cell)&&Objects.equals(kind,other.kind);}@Override public int hashCode(){return Objects.hash(cell,kind);}}
        private final Map<Key,C> contexts=new HashMap<>();
        public void clear(){contexts.clear();}
        public void reject(Cell cell,Kind kind,C context){contexts.put(new Key(cell,kind),Objects.requireNonNull(context));}
        public boolean contains(Cell cell,Kind kind,java.util.function.Supplier<C> current){
            Key key=new Key(cell,kind);C previous=contexts.get(key);if(previous==null)return false;
            if(previous.equals(current.get()))return true;
            contexts.remove(key);return false;
        }
    }
    public static final class Edit{public final Cell cell;public final Kind kind;public final String expected;public final int ticks;public Edit(Cell cell,Kind kind,String expected,int ticks){this.cell=cell;this.kind=kind;this.expected=expected;this.ticks=ticks;}public Cell cell(){return cell;}public Kind kind(){return kind;}public String expected(){return expected;}public int ticks(){return ticks;}@Override public boolean equals(Object value){if(this==value)return true;if(!(value instanceof Edit))return false;Edit other=(Edit)value;return Objects.equals(cell,other.cell)&&Objects.equals(kind,other.kind)&&Objects.equals(expected,other.expected)&&ticks==other.ticks;}@Override public int hashCode(){return Objects.hash(cell,kind,expected,ticks);}}
    public static final class Step{public final Cell from;public final Cell to;public final List<Edit> edits;public final boolean jumpPlace;public final double cost;public Step(Cell from,Cell to,List<Edit> edits,boolean jumpPlace,double cost){edits=copyList(edits);this.from=from;this.to=to;this.edits=edits;this.jumpPlace=jumpPlace;this.cost=cost;}public Cell from(){return from;}public Cell to(){return to;}public List<Edit> edits(){return edits;}public boolean jumpPlace(){return jumpPlace;}public double cost(){return cost;}@Override public boolean equals(Object value){if(this==value)return true;if(!(value instanceof Step))return false;Step other=(Step)value;return Objects.equals(from,other.from)&&Objects.equals(to,other.to)&&Objects.equals(edits,other.edits)&&jumpPlace==other.jumpPlace&&Double.compare(cost,other.cost)==0;}@Override public int hashCode(){return Objects.hash(from,to,edits,jumpPlace,cost);}}
    public static final class Block{public final boolean loaded;public final boolean clear;public final boolean supports;public final boolean breakable;public final int breakTicks;public final String state;public Block(boolean loaded,boolean clear,boolean supports,boolean breakable,int breakTicks,String state){this.loaded=loaded;this.clear=clear;this.supports=supports;this.breakable=breakable;this.breakTicks=breakTicks;this.state=state;}public boolean loaded(){return loaded;}public boolean clear(){return clear;}public boolean supports(){return supports;}public boolean breakable(){return breakable;}public int breakTicks(){return breakTicks;}public String state(){return state;}@Override public boolean equals(Object value){if(this==value)return true;if(!(value instanceof Block))return false;Block other=(Block)value;return loaded==other.loaded&&clear==other.clear&&supports==other.supports&&breakable==other.breakable&&breakTicks==other.breakTicks&&Objects.equals(state,other.state);}@Override public int hashCode(){return Objects.hash(loaded,clear,supports,breakable,breakTicks,state);}}
    public interface World {
        Block block(Cell at);
        boolean canPlace(Cell at);
        /** True only if this location can continue the original intent or a checked escape route. */
        boolean exit(Cell feet,Map<Cell,Kind> changes);
        double risk(Cell feet);
        default double learnedCost(Step step,double risk){return 0;}
    }
    public static final class Result{public final String state;public final List<Step> steps;public final int expanded;public final double cost;public Result(String state,List<Step> steps,int expanded,double cost){steps=copyList(steps);this.state=state;this.steps=steps;this.expanded=expanded;this.cost=cost;}public String state(){return state;}public List<Step> steps(){return steps;}public int expanded(){return expanded;}public double cost(){return cost;}@Override public boolean equals(Object value){if(this==value)return true;if(!(value instanceof Result))return false;Result other=(Result)value;return Objects.equals(state,other.state)&&Objects.equals(steps,other.steps)&&expanded==other.expanded&&Double.compare(cost,other.cost)==0;}@Override public int hashCode(){return Objects.hash(state,steps,expanded,cost);}}
    private static final class State{public final Cell feet;public final Map<Cell,Kind> changes;public final int materials;public State(Cell feet,Map<Cell,Kind> changes,int materials){this.feet=feet;this.changes=changes;this.materials=materials;}public Cell feet(){return feet;}public Map<Cell,Kind> changes(){return changes;}public int materials(){return materials;}@Override public boolean equals(Object value){if(this==value)return true;if(!(value instanceof State))return false;State other=(State)value;return Objects.equals(feet,other.feet)&&Objects.equals(changes,other.changes)&&materials==other.materials;}@Override public int hashCode(){return Objects.hash(feet,changes,materials);}}
    private static final class Entry{public final State state;public final List<Step> path;public final double cost;public Entry(State state,List<Step> path,double cost){this.state=state;this.path=path;this.cost=cost;}public State state(){return state;}public List<Step> path(){return path;}public double cost(){return cost;}@Override public boolean equals(Object value){if(this==value)return true;if(!(value instanceof Entry))return false;Entry other=(Entry)value;return Objects.equals(state,other.state)&&Objects.equals(path,other.path)&&Double.compare(cost,other.cost)==0;}@Override public int hashCode(){return Objects.hash(state,path,cost);}}
    private final World world;
    private final Cell origin;
    private final int materials,radius;
    private final PriorityQueue<Entry> open=new PriorityQueue<>(Comparator.comparingDouble(Entry::cost));
    private final Map<State,Double> best=new HashMap<>();
    private int expanded;
    private boolean unloaded;
    private Result terminal;
    public TerrainPathSearch(World world,Cell origin,int materials,int radius){
        this.world=Objects.requireNonNull(world);this.origin=origin;this.materials=Math.max(0,materials);this.radius=Math.max(1,Math.min(8,radius));
        State start=new State(origin,Collections.emptyMap(),0);open.add(new Entry(start,Collections.emptyList(),0));best.put(start,0d);
    }
    public Result advance(int budget,java.util.function.BooleanSupplier timeAvailable){
        if(terminal!=null)return terminal;
        while(budget-->0&&!open.isEmpty()&&timeAvailable.getAsBoolean()){
            Entry current=open.remove();if(current.cost>best.getOrDefault(current.state,Double.POSITIVE_INFINITY))continue;
            expanded++;
            if(!current.path.isEmpty()&&world.exit(current.state.feet,current.state.changes))return terminal=new Result("FOUND",current.path,expanded,current.cost);
            if(current.path.size()>=10)continue;
            for(int[] d:new int[][]{{1,0},{-1,0},{0,1},{0,-1},{0,0}}){
                for(int dy=-1;dy<=1;dy++){
                    boolean column=d[0]==0&&d[1]==0;if(column&&dy!=1)continue;
                    Cell destination=current.state.feet.add(d[0],dy,d[1]);
                    if(Math.abs(destination.x-origin.x)>radius||Math.abs(destination.z-origin.z)>radius||destination.y<origin.y-1||destination.y>origin.y+radius)continue;
                    LinkedHashMap<Cell,Kind> changes=new LinkedHashMap<>(current.state.changes);ArrayList<Edit> edits=new ArrayList<Edit>();double cost=8+Math.abs(dy)*5;int used=current.state.materials;
                    // Rising needs head clearance along the whole motion, including the old column.
                    LinkedHashSet<Cell> clearance=new LinkedHashSet<Cell>();clearance.add(destination.add(0,1,0));clearance.add(destination);
                    if(dy>0)clearance.add(current.state.feet.add(0,2,0));
                    boolean valid=true;
                    for(Cell at:clearance){Block block=read(at,changes);if(!block.loaded){valid=false;break;}if(!block.clear){
                        if(column||!block.breakable||block.breakTicks<=0||block.breakTicks>240){valid=false;break;}
                        edits.add(new Edit(at,Kind.BREAK,block.state,block.breakTicks));changes.put(at,Kind.BREAK);cost+=block.breakTicks+4;
                    }}
                    if(!valid)continue;
                    Cell floor=destination.add(0,-1,0);Block support=read(floor,changes);if(!support.loaded)continue;
                    if(!support.supports){
                        if(!support.clear||!world.canPlace(floor)||used>=materials||dy<0)continue;
                        edits.add(new Edit(floor,Kind.PLACE,support.state,12));changes.put(floor,Kind.PLACE);used++;cost+=22;
                    } else if(column)continue;
                    if(changes.size()>10)continue;
                    double risk=world.risk(destination);if(!Double.isFinite(risk)||risk<0)continue;
                    // Price exposure for the complete edit-and-move interval, not just the endpoint.
                    cost+=Math.max(risk,world.risk(current.state.feet))*Math.max(1,cost/10);
                    Step step=new Step(current.state.feet,destination,edits,column,cost);
                    double learned=world.learnedCost(step,risk);if(Double.isFinite(learned))cost+=Math.max(0,Math.min(10,learned));
                    step=new Step(step.from,step.to,step.edits,step.jumpPlace,cost);
                    State next=new State(destination,Collections.unmodifiableMap(new LinkedHashMap<Cell,Kind>(changes)),used);double total=current.cost+cost;
                    if(total>=best.getOrDefault(next,Double.POSITIVE_INFINITY))continue;
                    best.put(next,total);ArrayList<Step> path=new ArrayList<>(current.path);path.add(step);open.add(new Entry(next,copyList(path),total));
                }
            }
            if(expanded>=4096||best.size()>16384)return terminal=new Result("SEARCH_LIMIT",Collections.emptyList(),expanded,0);
        }
        if(open.isEmpty())return terminal=new Result(unloaded?"WAITING_CHUNKS":"NO_SAFE_ESCAPE",Collections.emptyList(),expanded,0);
        return new Result("SEARCHING",Collections.emptyList(),expanded,0);
    }
    private Block read(Cell cell,Map<Cell,Kind> changes){
        Block value=world.block(cell);if(!value.loaded)unloaded=true;
        Kind change=changes.get(cell);if(change==Kind.BREAK)return new Block(value.loaded,true,false,false,0,value.state);if(change==Kind.PLACE)return new Block(value.loaded,false,true,false,0,value.state);return value;
    }
private static <T> List<T> copyList(Collection<T> values){return Collections.unmodifiableList(new ArrayList<T>(values));}
}
