package dev.mineagent.runtime.core.objects;

import com.fasterxml.jackson.databind.JsonNode;
import java.util.*;
import dev.mineagent.runtime.core.objects.RuntimeMesh.*;

/** Bounded mathematical primitives. Local Y is the symmetry axis; transforms preserve handedness. */
final class BasicMeshes {
    static final Set<String> TYPES=Set.of("box","plane","disc","annulus","cylinder","cone","frustum","prism","pyramid","ellipsoid","capsule");
    private BasicMeshes(){}
    static void append(JsonNode p,List<Vertex> output,List<Triangle> faces){
        String type=p.path("type").asText();if(!TYPES.contains(type))throw new IllegalArgumentException("MESH_PRIMITIVE_TYPE");
        var allowed=new HashSet<>(Set.of("type","center","color","axis","smooth"));
        allowed.addAll(switch(type){case "box","plane"->Set.of("size","doubleSided");case "disc"->Set.of("radius","segments","doubleSided");case "annulus"->Set.of("innerRadius","outerRadius","segments","doubleSided");case "ellipsoid"->Set.of("radii","segments","rings");case "capsule"->Set.of("radius","height","segments","hemisphereRings");case "frustum"->Set.of("radiusTop","radiusBottom","height","segments","capped");case "prism","pyramid"->Set.of("radius","height","sides","capped");default->Set.of("radius","height","segments","capped");});
        RuntimeMesh.keys(p,allowed);double[] center=vector(p,"center",3,-32,32);String axis=p.path("axis").asText("y");if(p.has("axis")&&!p.path("axis").isTextual()||!Set.of("x","y","z").contains(axis))throw new IllegalArgumentException("MESH_AXIS");
        boolean smooth=bool(p,"smooth",!Set.of("box","plane","prism","pyramid").contains(type));int color=RuntimeMesh.color(p.path("color"));var v=new ArrayList<Vertex>();var t=new ArrayList<Triangle>();
        switch(type){
            case "box"->{if(p.has("doubleSided"))throw new IllegalArgumentException("BOX_DOUBLE_SIDED");double[] size=vector(p,"size",3,.001,32);ParametricMeshes.budget(output,faces,24,12);box(v,t,size,color);}
            case "plane"->{double[] size=vector(p,"size",2,.001,32);boolean two=bool(p,"doubleSided",true);ParametricMeshes.budget(output,faces,two?8:4,two?4:2);quad(v,t,new double[][]{{-size[0]/2,0,-size[1]/2},{-size[0]/2,0,size[1]/2},{size[0]/2,0,size[1]/2},{size[0]/2,0,-size[1]/2}},new double[]{0,1,0},color);if(two)quad(v,t,new double[][]{{-size[0]/2,0,-size[1]/2},{size[0]/2,0,-size[1]/2},{size[0]/2,0,size[1]/2},{-size[0]/2,0,size[1]/2}},new double[]{0,-1,0},color);}
            case "disc","annulus"->{int n=integer(p,"segments",48,3,96);double outer=num(p,type.equals("disc")?"radius":"outerRadius",.001,16),inner=type.equals("disc")?0:num(p,"innerRadius",.0001,16);if(inner>=outer)throw new IllegalArgumentException("MESH_ANNULUS_RADII");boolean two=bool(p,"doubleSided",true);ParametricMeshes.budget(output,faces,(two?2:1)*(inner==0?n+2:2*(n+1)),(two?2:1)*(inner==0?n:2*n));cap(v,t,outer,inner,0,n,1,color);if(two)cap(v,t,outer,inner,0,n,-1,color);}
            case "ellipsoid"->{double[] radii=vector(p,"radii",3,.001,16);int n=integer(p,"segments",64,8,96),r=integer(p,"rings",32,4,48);ParametricMeshes.budget(output,faces,2+(r-1)*(n+1),2*n*(r-1));var rows=new ArrayList<double[]>();for(int i=1;i<r;i++){double a=Math.PI*i/r;rows.add(new double[]{radii[1]*Math.cos(a),Math.sin(a),Math.cos(a)});}rounded(v,t,rows,radii[1],-radii[1],radii[0],radii[2],radii[1],n,color,false);}
            case "capsule"->{double radius=num(p,"radius",.001,16),height=num(p,"height",.002,32);if(height<2*radius)throw new IllegalArgumentException("MESH_CAPSULE_HEIGHT");int n=integer(p,"segments",48,8,96),h=integer(p,"hemisphereRings",8,2,24);boolean cylinder=height>2*radius;int rowCount=cylinder?2*h:2*h-1;ParametricMeshes.budget(output,faces,2+rowCount*(n+1),2*n*rowCount);var rows=new ArrayList<double[]>();double half=height/2-radius;for(int i=1;i<=h;i++){double a=Math.PI*i/(2*h);rows.add(new double[]{half+radius*Math.cos(a),Math.sin(a),Math.cos(a)});}for(int i=cylinder?0:1;i<h;i++){double a=Math.PI/2+Math.PI*i/(2*h);rows.add(new double[]{-half+radius*Math.cos(a),Math.sin(a),Math.cos(a)});}rounded(v,t,rows,height/2,-height/2,radius,radius,radius,n,color,true);}
            default->{boolean polygon=type.equals("prism")||type.equals("pyramid");int n=integer(p,polygon?"sides":"segments",polygon?6:48,3,96);double height=num(p,"height",.001,32),bottom=type.equals("frustum")?num(p,"radiusBottom",0,16):num(p,"radius",.001,16),top=type.equals("frustum")?num(p,"radiusTop",0,16):Set.of("cone","pyramid").contains(type)?0:bottom;if(top==0&&bottom==0)throw new IllegalArgumentException("MESH_FRUSTUM_RADII");boolean capped=bool(p,"capped",true);int caps=capped?((top>0?1:0)+(bottom>0?1:0)):0;ParametricMeshes.budget(output,faces,n*(top==0||bottom==0?3:4)+caps*(n+2),n*(top==0||bottom==0?1:2)+caps*n);frustum(v,t,bottom,top,height,n,capped,color);}
        }
        int base=output.size();for(var a:v){double[] xyz=rotate(axis,a.x(),a.y(),a.z()),normal=rotate(axis,a.nx(),a.ny(),a.nz());double x=center[0]+xyz[0],y=center[1]+xyz[1],z=center[2]+xyz[2];if(Math.abs(x)>32||Math.abs(y)>32||Math.abs(z)>32)throw new IllegalArgumentException("MESH_PRIMITIVE_BOUNDS");output.add(new Vertex((float)x,(float)y,(float)z,a.u(),a.v(),smooth?(float)normal[0]:0,smooth?(float)normal[1]:0,smooth?(float)normal[2]:0));}for(var a:t)faces.add(new Triangle(base+a.a(),base+a.b(),base+a.c(),a.color()));
    }
    private static double num(JsonNode p,String k,double min,double max){return RuntimeMesh.number(p.path(k),min,max);}
    private static double[] vector(JsonNode p,String k,int length,double min,double max){var node=p.path(k);RuntimeMesh.arraySize(node,length);double[] out=new double[length];for(int i=0;i<length;i++)out[i]=RuntimeMesh.number(node.get(i),min,max);return out;}
    private static int integer(JsonNode p,String k,int fallback,int min,int max){if(!p.has(k))return fallback;var v=p.path(k);if(!v.isIntegralNumber()||!v.canConvertToInt()||v.intValue()<min||v.intValue()>max)throw new IllegalArgumentException("MESH_SEGMENT_RANGE");return v.intValue();}
    private static boolean bool(JsonNode p,String k,boolean fallback){if(p.has(k)&&!p.path(k).isBoolean())throw new IllegalArgumentException("MESH_BOOLEAN");return p.path(k).asBoolean(fallback);}
    private static double[] rotate(String axis,double x,double y,double z){return switch(axis){case "x"->new double[]{y,-x,z};case "z"->new double[]{x,-z,y};default->new double[]{x,y,z};};}
    private static int vertex(List<Vertex> v,double x,double y,double z,double u,double w,double nx,double ny,double nz){double length=Math.sqrt(nx*nx+ny*ny+nz*nz);int i=v.size();v.add(new Vertex((float)x,(float)y,(float)z,(float)u,(float)w,(float)(nx/length),(float)(ny/length),(float)(nz/length)));return i;}
    private static void tri(List<Vertex> v,List<Triangle> t,int a,int b,int c,int color){var A=v.get(a);var B=v.get(b);var C=v.get(c);double nx=(B.y()-A.y())*(C.z()-A.z())-(B.z()-A.z())*(C.y()-A.y()),ny=(B.z()-A.z())*(C.x()-A.x())-(B.x()-A.x())*(C.z()-A.z()),nz=(B.x()-A.x())*(C.y()-A.y())-(B.y()-A.y())*(C.x()-A.x());double dot=nx*(A.nx()+B.nx()+C.nx())+ny*(A.ny()+B.ny()+C.ny())+nz*(A.nz()+B.nz()+C.nz());t.add(dot>=0?new Triangle(a,b,c,color):new Triangle(a,c,b,color));}
    private static void quad(List<Vertex> v,List<Triangle> t,double[][] points,double[] normal,int color){int start=v.size();for(int i=0;i<4;i++)vertex(v,points[i][0],points[i][1],points[i][2],i==0||i==3?0:1,i<2?0:1,normal[0],normal[1],normal[2]);tri(v,t,start,start+1,start+2,color);tri(v,t,start,start+2,start+3,color);}
    private static void box(List<Vertex> v,List<Triangle> t,double[] size,int color){double x=size[0]/2,y=size[1]/2,z=size[2]/2;quad(v,t,new double[][]{{-x,-y,-z},{-x,-y,z},{-x,y,z},{-x,y,-z}},new double[]{-1,0,0},color);quad(v,t,new double[][]{{x,-y,-z},{x,y,-z},{x,y,z},{x,-y,z}},new double[]{1,0,0},color);quad(v,t,new double[][]{{-x,-y,-z},{x,-y,-z},{x,-y,z},{-x,-y,z}},new double[]{0,-1,0},color);quad(v,t,new double[][]{{-x,y,-z},{-x,y,z},{x,y,z},{x,y,-z}},new double[]{0,1,0},color);quad(v,t,new double[][]{{-x,-y,-z},{-x,y,-z},{x,y,-z},{x,-y,-z}},new double[]{0,0,-1},color);quad(v,t,new double[][]{{-x,-y,z},{x,-y,z},{x,y,z},{-x,y,z}},new double[]{0,0,1},color);}
    private static void cap(List<Vertex> v,List<Triangle> t,double outer,double inner,double y,int n,int direction,int color){int base=v.size();if(inner==0){vertex(v,0,y,0,.5,.5,0,direction,0);for(int i=0;i<=n;i++){double a=i==n?0:2*Math.PI*i/n,x=Math.cos(a),z=Math.sin(a);vertex(v,outer*x,y,outer*z,.5+x/2,.5+z/2,0,direction,0);}for(int i=0;i<n;i++)tri(v,t,base,base+1+i,base+2+i,color);}else{for(int i=0;i<=n;i++){double a=i==n?0:2*Math.PI*i/n,x=Math.cos(a),z=Math.sin(a);vertex(v,inner*x,y,inner*z,.5+x*inner/(2*outer),.5+z*inner/(2*outer),0,direction,0);vertex(v,outer*x,y,outer*z,.5+x/2,.5+z/2,0,direction,0);}for(int i=0;i<n;i++){int a=base+2*i;tri(v,t,a,a+1,a+2,color);tri(v,t,a+1,a+3,a+2,color);}}}
    private static void frustum(List<Vertex> v,List<Triangle> t,double bottom,double top,double height,int n,boolean capped,int color){double y=height/2;for(int i=0;i<n;i++){double a=2*Math.PI*i/n,b=i+1==n?0:2*Math.PI*(i+1)/n,ca=Math.cos(a),sa=Math.sin(a),cb=Math.cos(b),sb=Math.sin(b),mid=2*Math.PI*(i+.5)/n;int start=v.size();if(bottom==0){vertex(v,0,-y,0,(i+.5)/n,1,height*Math.cos(mid),bottom-top,height*Math.sin(mid));vertex(v,top*ca,y,top*sa,(double)i/n,0,height*ca,bottom-top,height*sa);vertex(v,top*cb,y,top*sb,(double)(i+1)/n,0,height*cb,bottom-top,height*sb);tri(v,t,start,start+1,start+2,color);}else if(top==0){vertex(v,bottom*ca,-y,bottom*sa,(double)i/n,1,height*ca,bottom-top,height*sa);vertex(v,0,y,0,(i+.5)/n,0,height*Math.cos(mid),bottom-top,height*Math.sin(mid));vertex(v,bottom*cb,-y,bottom*sb,(double)(i+1)/n,1,height*cb,bottom-top,height*sb);tri(v,t,start,start+1,start+2,color);}else{vertex(v,bottom*ca,-y,bottom*sa,(double)i/n,1,height*ca,bottom-top,height*sa);vertex(v,top*ca,y,top*sa,(double)i/n,0,height*ca,bottom-top,height*sa);vertex(v,top*cb,y,top*sb,(double)(i+1)/n,0,height*cb,bottom-top,height*sb);vertex(v,bottom*cb,-y,bottom*sb,(double)(i+1)/n,1,height*cb,bottom-top,height*sb);tri(v,t,start,start+1,start+2,color);tri(v,t,start,start+2,start+3,color);}}if(capped&&bottom>0)cap(v,t,bottom,0,-y,n,-1,color);if(capped&&top>0)cap(v,t,top,0,y,n,1,color);}
    private static void rounded(List<Vertex> v,List<Triangle> t,List<double[]> rows,double top,double bottom,double rx,double rz,double ry,int n,int color,boolean capsule){int base=v.size();vertex(v,0,top,0,.5,0,0,1,0);for(int row=0;row<rows.size();row++){double[] r=rows.get(row);for(int i=0;i<=n;i++){double a=i==n?0:2*Math.PI*i/n,c=Math.cos(a),s=Math.sin(a);vertex(v,rx*r[1]*c,r[0],rz*r[1]*s,(double)i/n,(double)(row+1)/(rows.size()+1),r[1]*c/rx,r[2]/ry,r[1]*s/rz);}}int end=v.size();vertex(v,0,bottom,0,.5,1,0,-1,0);for(int i=0;i<n;i++)tri(v,t,base,base+1+i,base+2+i,color);for(int row=0;row<rows.size()-1;row++)for(int i=0;i<n;i++){int a=base+1+row*(n+1)+i,b=a+n+1;tri(v,t,a,a+1,b,color);tri(v,t,a+1,b+1,b,color);}int last=base+1+(rows.size()-1)*(n+1);for(int i=0;i<n;i++)tri(v,t,end,last+i,last+i+1,color);}
}
