package dev.mineagent.runtime.neoforge.compile;

import com.fasterxml.jackson.databind.ObjectMapper;
import dev.mineagent.runtime.core.compile.*;
import dev.mineagent.runtime.core.content.ContentAddressedStore;
import dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;
import dev.mineagent.runtime.neoforge.ui.ServerPackageRuntime;
import dev.mineagent.runtime.api.permission.PermissionAction;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.permissions.Permissions;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.BooleanSupplier;

/** Trusted, bounded Native API inspection. No Worker RPC is made while the server thread or a database monitor waits. */
public final class NativeApiCatalog {
    private static final ObjectMapper JSON=new ObjectMapper();
    private static final ExecutorService IO=new ThreadPoolExecutor(1,1,0,TimeUnit.SECONDS,new ArrayBlockingQueue<>(4),r->{var t=new Thread(r,"mineagent-native-api");t.setDaemon(true);return t;},new ThreadPoolExecutor.AbortPolicy());
    private record Scope(UUID world,UUID owner){}
    private record Refresh(UUID operation,String phase,String snapshot,String error){}
    private static final Map<Scope,Refresh> REFRESH=new ConcurrentHashMap<>();
    private NativeApiCatalog(){}
    private record AgentQuery(String snapshot,int count,Object value,String mode){}
    public static void authorize(ServerPlayer viewer){var server=viewer.level().getServer();if(!server.isSameThread()||viewer instanceof dev.mineagent.runtime.neoforge.body.MineAgentPlayer||server.getPlayerList().getPlayer(viewer.getUUID())!=viewer)throw new SecurityException("NATIVE_API_IDENTITY");var permissions=MineAgentRuntimeServices.permissions(server);boolean op=viewer.permissions().hasPermission(Permissions.COMMANDS_GAMEMASTER);if(!permissions.allowed(viewer.getUUID(),op,PermissionAction.RUN_CODE)||!permissions.allowed(viewer.getUUID(),op,PermissionAction.MANAGE_PACKAGES))throw new SecurityException("NATIVE_API_PERMISSION");}
    public static CompletableFuture<Map<String,String>> read(ServerPlayer viewer,Map<String,String> args,BooleanSupplier permit,UUID operation){
        authorize(viewer);String kind=args.get("kind");var expected=switch(Objects.toString(kind,"")){case "state","refresh"->Set.of("kind");case "modules"->Set.of("kind","snapshot","offset");case "classes"->Set.of("kind","snapshot","module","search","offset");case "members"->Set.of("kind","snapshot","module","class","search","offset","textOffset");case "method_body"->Set.of("kind","snapshot","module","class","method","descriptor","offset","textOffset");case "source"->{var value=new HashSet<>(Set.of("kind","snapshot","module","class","lineOffset","textOffset"));if(args.containsKey("method")||args.containsKey("descriptor")){value.add("method");value.add("descriptor");}yield Set.copyOf(value);}default->throw new IllegalArgumentException("NATIVE_API_QUERY");};if(!args.keySet().equals(expected))throw new IllegalArgumentException("NATIVE_API_QUERY");
        var content=ServerPackageRuntime.get(viewer.level().getServer()).worldContent();
        var scope=new Scope(MineAgentRuntimeServices.worldId(viewer.level().getServer()),viewer.getUUID());
        if(kind.equals("state")){try{return CompletableFuture.completedFuture(Map.of("state",JSON.writeValueAsString(Map.of("environment",NativeCompilationEnvironment.state(),"refresh",REFRESH.containsKey(scope)?REFRESH.get(scope):Map.of())),"executionMode","CACHED_CAPTURE_STATE_NO_WORKER_RPC"));}catch(Exception failure){return CompletableFuture.failedFuture(failure);}}
        if(kind.equals("refresh")){
            if(REFRESH.size()>=128&&!REFRESH.containsKey(scope))throw new IllegalStateException("NATIVE_API_REQUEST_BUDGET");var queued=new Refresh(operation,"QUEUED","","");var prior=REFRESH.get(scope);if(prior!=null&&Set.of("QUEUED","CAPTURING").contains(prior.phase()))throw new IllegalStateException("NATIVE_API_BUSY");REFRESH.put(scope,queued);
            try{IO.execute(()->{
                REFRESH.put(scope,new Refresh(operation,"CAPTURING","",""));
                try{var result=NativeCompilationEnvironment.capture(content,permit);REFRESH.put(scope,new Refresh(operation,"READY",result.hash(),""));}
                catch(Exception failure){String code=Objects.toString(failure.getMessage(),"");REFRESH.put(scope,new Refresh(operation,"FAILED","",code.matches("NATIVE_CLASSPATH_[A-Z_]{1,80}")?code:"NATIVE_API_CAPTURE_FAILED"));}
            });}catch(RejectedExecutionException rejected){REFRESH.put(scope,new Refresh(operation,"FAILED","","NATIVE_API_BUSY"));throw new IllegalStateException("NATIVE_API_BUSY");}
            return CompletableFuture.completedFuture(Map.of("state","{\"status\":\"REFRESH_QUEUED\"}","operation",operation.toString(),"executionMode","METADATA_CAPTURE_NO_CLASS_INITIALIZATION"));
        }
        return CompletableFuture.supplyAsync(()->{
            try{if(!permit.getAsBoolean())throw new SecurityException("NATIVE_API_PERMISSION_CHANGED");Object value;
                {
                    var current=NativeCompilationEnvironment.latest();if(!current.hash().equals(args.get("snapshot")))throw new IllegalStateException("NATIVE_API_SNAPSHOT_CHANGED");var snapshot=NativeCompilationSnapshot.read(content,current.hash());if(!snapshot.environment().fingerprint().equals(dev.mineagent.runtime.neoforge.content.NativePackageCompatibility.observe().fingerprint()))throw new IllegalStateException("NATIVE_API_ENVIRONMENT_CHANGED");int offset=integer(args,kind.equals("source")?"lineOffset":"offset");
                    if(kind.equals("modules")){var all=snapshot.modules();if(offset>all.size())throw new IllegalArgumentException("NATIVE_API_OFFSET");var page=all.stream().skip(offset).limit(16).toList();value=Map.of("snapshot",current.hash(),"namespace",snapshot.namespace(),"physicalSide",snapshot.physicalSide(),"mappingStatus",snapshot.mappingStatus(),"modules",page,"nextOffset",offset+page.size(),"more",offset+page.size()<all.size());}
                    else if(kind.equals("classes")){var page=snapshot.classPage(content,args.get("module"),args.get("search"),offset,17);var visible=page.stream().limit(16).toList();value=Map.of("module",args.get("module"),"classes",visible,"offset",offset,"nextOffset",offset+visible.size(),"more",page.size()>16,"moduleHash",snapshot.module(args.get("module")).sha256());}
                    else if(kind.equals("members")){byte[] bytes=snapshot.classBytes(content,args.get("module"),args.get("class"));var symbols=ClassFileSymbols.inspect(bytes,args.get("search"),offset);String full=JSON.writerWithDefaultPrettyPrinter().writeValueAsString(symbols);int start=integer(args,"textOffset"),length=full.codePointCount(0,full.length());if(length>4000000)throw new IllegalStateException("NATIVE_API_SYMBOL_LIMIT");if(start>length)throw new IllegalArgumentException("NATIVE_API_TEXT_OFFSET");int end=Math.min(length,start+4096);var memberValue=new LinkedHashMap<String,Object>();memberValue.put("module",args.get("module"));memberValue.put("class",args.get("class"));memberValue.put("classHash",RuntimePackageCanonicalizer.sha256(bytes));memberValue.put("textHash",RuntimePackageCanonicalizer.sha256(full));memberValue.put("text",full.substring(full.offsetByCodePoints(0,start),full.offsetByCodePoints(0,end)));memberValue.put("nextTextOffset",end);memberValue.put("textMore",end<length);memberValue.put("nextOffset",symbols.nextOffset());memberValue.put("more",symbols.more());memberValue.put("mappingStatus",snapshot.mappingStatus());memberValue.put("methods",methodSelectors(symbols));var module=snapshot.module(args.get("module"));memberValue.put("sourceAvailable",!module.sourceSha256().isEmpty());memberValue.put("sourceKind",module.sourceKind());value=Map.copyOf(memberValue);}
                    else if(kind.equals("method_body"))value=methodBody(snapshot,content,args,offset);else value=sourceView(snapshot,content,args,offset);
                    if(!current.hash().equals(NativeCompilationEnvironment.latest().hash()))throw new IllegalStateException("NATIVE_API_SNAPSHOT_CHANGED");
                }
                if(!permit.getAsBoolean())throw new SecurityException("NATIVE_API_PERMISSION_CHANGED");String encoded=JSON.writeValueAsString(value);if(encoded.getBytes(java.nio.charset.StandardCharsets.UTF_8).length>24000)throw new IllegalStateException("NATIVE_API_RESPONSE_LIMIT");return Map.of("state",encoded,"executionMode",kind.equals("source")?"ATTACHED_SOURCE_NO_COMPILATION_OR_EXECUTION":kind.equals("method_body")?"RAW_CLASS_METHOD_BYTECODE_NO_INITIALIZATION":"RAW_CLASS_METADATA_NO_INITIALIZATION");
            }catch(Exception failure){String code=Objects.toString(failure.getMessage(),"");if(!code.matches("(?:NATIVE_API|NATIVE_CLASSPATH)_[A-Z_]{1,80}"))code="NATIVE_API_FAILED";return Map.of("errorCode",code);}
        },IO);
    }
    /** Planner-facing read/capture. The model supplies no actor/owner identity and each call is a persisted WorldAction. */
    public static CompletableFuture<Map<String,String>> readTask(MinecraftServer server,dev.mineagent.runtime.api.task.ManagedTask task,Map<String,String> args,BooleanSupplier permit,UUID operation){
        requireTask(server,task);String kind=args.get("kind");var expected=switch(Objects.toString(kind,"")){case "state","refresh"->Set.of("kind");case "modules"->Set.of("kind","snapshot","offset");case "classes"->Set.of("kind","snapshot","module","search","offset");case "members"->Set.of("kind","snapshot","module","class","search","offset","textOffset");case "method_body"->Set.of("kind","snapshot","module","class","method","descriptor","offset","textOffset");case "source"->{var value=new HashSet<>(Set.of("kind","snapshot","module","class","lineOffset","textOffset"));if(args.containsKey("method")||args.containsKey("descriptor")){value.add("method");value.add("descriptor");}yield Set.copyOf(value);}default->throw new IllegalArgumentException("NATIVE_API_QUERY");};if(!args.keySet().equals(expected))throw new IllegalArgumentException("NATIVE_API_QUERY");
        var content=ServerPackageRuntime.get(server).worldContent();
        if(kind.equals("state")){var s=NativeCompilationEnvironment.state();return completed(agent(new AgentQuery(s.snapshot(),s.modules(),Map.of("environment",s,"operation",operation), "CACHED_CAPTURE_STATE_NO_WORKER_RPC")));}
        if(kind.equals("refresh")){
            try{return CompletableFuture.supplyAsync(()->{try{if(!permit.getAsBoolean())throw new SecurityException("NATIVE_API_PERMISSION_CHANGED");var value=NativeCompilationEnvironment.capture(content,permit);return agent(new AgentQuery(value.hash(),value.snapshot().modules().size(),Map.of("snapshot",value.hash(),"environment",value.snapshot().environment().wire(),"physicalSide",value.snapshot().physicalSide(),"mappingStatus",value.snapshot().mappingStatus(),"modules",value.snapshot().modules().size(),"classes",value.snapshot().classCount()),"TASK_AUTHORIZED_METADATA_CAPTURE_NO_CLASS_INITIALIZATION"));}catch(Exception failure){throw new java.util.concurrent.CompletionException(failure);}},IO);}catch(RejectedExecutionException rejected){return CompletableFuture.failedFuture(new IllegalStateException("NATIVE_API_BUSY"));}
        }
        try{return CompletableFuture.supplyAsync(()->{try{return agent(query(content,args,permit));}catch(Exception failure){throw new java.util.concurrent.CompletionException(failure);}},IO);}catch(RejectedExecutionException rejected){return CompletableFuture.failedFuture(new IllegalStateException("NATIVE_API_BUSY"));}
    }
    /** Durable knowledge lifecycle. Remember receives a selection rebuilt from a verified current-task receipt on the server thread. */
    public static CompletableFuture<Map<String,String>> knowledgeTask(MinecraftServer server,dev.mineagent.runtime.api.task.ManagedTask task,NativeKnowledgeToolRequest request,NativeCoderContext remembered,BooleanSupplier permit,UUID operation){
        requireTask(server,task);var runtime=ServerPackageRuntime.get(server);var content=runtime.worldContent();var store=runtime.nativeKnowledge();
        try{return CompletableFuture.supplyAsync(()->{try{
            if(!permit.getAsBoolean())throw new SecurityException("NATIVE_API_PERMISSION_CHANGED");Object value;String snapshot=NativeCompilationEnvironment.state().snapshot();int count;
            switch(request.tool()){
                case "remember_native_api"->{if(remembered==null)throw new IllegalArgumentException("NATIVE_KNOWLEDGE_OBSERVATION_REQUIRED");var source=NativeCompilationSnapshot.read(content,remembered.snapshot());var reference=remembered.capture(source,content,permit);String encoded=remembered.read(reference,content),semantic=NativeKnowledgeArtifact.semanticHash(encoded);if(!permit.getAsBoolean())throw new SecurityException("NATIVE_API_PERMISSION_CHANGED");var result=store.remember(operation,task.ownerPlayerId(),task.agentId(),task.taskId(),request.observation(),request.label(),remembered,reference,semantic);value=knowledgeDetail(result.entry(),result.duplicate());snapshot=result.entry().selection().snapshot();count=1;}
                case "search_native_knowledge"->{var page=store.search(task.ownerPlayerId(),task.agentId(),request.query(),request.offset());value=Map.of("entries",page.entries().stream().map(NativeApiCatalog::knowledgeSummary).toList(),"offset",page.offset(),"nextOffset",page.nextOffset(),"more",page.more(),"total",page.total());count=page.entries().size();}
                case "inspect_native_knowledge"->{var entry=store.get(task.ownerPlayerId(),task.agentId(),request.knowledge());value=knowledgeDetail(entry,false);snapshot=entry.selection().snapshot();count=1;}
                case "revalidate_native_knowledge"->{var entry=store.get(task.ownerPlayerId(),task.agentId(),request.knowledge());NativeKnowledgeStore.Mutation result;try{var current=NativeCompilationEnvironment.latest();var source=NativeCompilationSnapshot.read(content,current.hash());var oldType=entry.selection().types().getFirst();var types=List.of(Map.of("module",oldType.module(),"class",oldType.className()));var methods=entry.selection().methods().isEmpty()?List.<Map<String,String>>of():entry.selection().methods().stream().map(m->Map.of("module",m.module(),"class",m.className(),"method",m.name(),"descriptor",m.descriptor())).toList();var sources=entry.selection().sources().stream().map(s->Map.of("module",s.module(),"class",s.className(),"method",s.method(),"descriptor",s.descriptor())).toList();var selection=NativeCoderContext.resolve(source,current.hash(),dev.mineagent.runtime.neoforge.content.NativePackageCompatibility.observe().fingerprint(),types,methods,sources,permit);var reference=selection.capture(source,content,permit);String semantic=NativeKnowledgeArtifact.semanticHash(selection.read(reference,content));if(!permit.getAsBoolean())throw new SecurityException("NATIVE_API_PERMISSION_CHANGED");result=store.revalidate(operation,task.ownerPlayerId(),task.agentId(),entry.knowledgeId(),selection,reference,semantic);}catch(Exception missing){String code=Objects.toString(missing.getMessage(),"");if(!code.matches("(?:NATIVE_CLASSPATH_MODULE_UNKNOWN|NATIVE_API_CLASS_MISSING|NATIVE_API_METHOD_NOT_FOUND|NATIVE_SOURCE_UNAVAILABLE|NATIVE_SOURCE_FILE_MISSING)"))throw missing;if(!permit.getAsBoolean())throw new SecurityException("NATIVE_API_PERMISSION_CHANGED");result=store.markMissing(operation,task.ownerPlayerId(),task.agentId(),entry.knowledgeId(),code);}value=knowledgeDetail(result.entry(),result.duplicate());snapshot=result.entry().state().equals("CURRENT")?result.entry().selection().snapshot():NativeCompilationEnvironment.state().snapshot();count=1;}
                case "forget_native_knowledge"->{if(!permit.getAsBoolean())throw new SecurityException("NATIVE_API_PERMISSION_CHANGED");var result=store.forget(operation,task.ownerPlayerId(),task.agentId(),request.knowledge());value=knowledgeDetail(result.entry(),result.duplicate());snapshot=result.entry().selection().snapshot();count=1;}
                default->throw new IllegalArgumentException("NATIVE_KNOWLEDGE_TOOL");
            }
            if(!permit.getAsBoolean())throw new SecurityException("NATIVE_API_PERMISSION_CHANGED");return agent(new AgentQuery(snapshot,count,value,"PERSISTED_NATIVE_KNOWLEDGE_NO_PROVIDER"));
        }catch(Exception failure){throw new CompletionException(failure);}},IO);}catch(RejectedExecutionException rejected){return CompletableFuture.failedFuture(new IllegalStateException("NATIVE_API_BUSY"));}
    }
    /** Explicit transformed/live inspection. Captured bytes are CAS evidence, not yet a compiler selection. */
    public static CompletableFuture<Map<String,String>> liveTask(MinecraftServer server,dev.mineagent.runtime.api.task.ManagedTask task,NativeLiveToolRequest request,BooleanSupplier permit,UUID operation){
        requireTask(server,task);var content=ServerPackageRuntime.get(server).worldContent();try{return CompletableFuture.supplyAsync(()->{try{return agent(liveQuery(content,request,permit,operation));}catch(Exception failure){throw new CompletionException(failure);}},IO);}catch(RejectedExecutionException rejected){return CompletableFuture.failedFuture(new IllegalStateException("NATIVE_API_BUSY"));}
    }
    public static CompletableFuture<Map<String,String>> readLive(ServerPlayer viewer,NativeLiveToolRequest request,BooleanSupplier permit,UUID operation){authorize(viewer);var server=viewer.level().getServer();var content=ServerPackageRuntime.get(server).worldContent();UUID world=MineAgentRuntimeServices.worldId(server),owner=viewer.getUUID();try{return CompletableFuture.supplyAsync(()->{try{var result=liveQuery(content,request,permit,operation);if(!(result.value() instanceof Map<?,?> raw))throw new IllegalStateException("NATIVE_LIVE_RESULT");var value=new LinkedHashMap<String,Object>();for(var entry:raw.entrySet()){if(!(entry.getKey() instanceof String key))throw new IllegalStateException("NATIVE_LIVE_RESULT");value.put(key,entry.getValue());}value.put("snapshot",result.snapshot());if(value.containsKey("classRef")&&result.snapshot().matches("[a-f0-9]{64}"))try{value.put("selectionId",NativeLiveClassAccess.register(world,owner,result.snapshot(),value));}catch(RuntimeException unavailable){String code=Objects.toString(unavailable.getMessage(),"");value.put("selectionUnavailable",code.matches("NATIVE_(?:LIVE|CODER)_[A-Z0-9_]{1,80}")?code:"NATIVE_LIVE_SELECTION_UNAVAILABLE");}String encoded=JSON.writeValueAsString(value);if(encoded.getBytes(java.nio.charset.StandardCharsets.UTF_8).length>24000)throw new IllegalStateException("NATIVE_API_RESPONSE_LIMIT");return Map.of("state",encoded,"executionMode",result.mode(),"snapshot",result.snapshot());}catch(Exception failure){String code=Objects.toString(failure.getMessage(),"");return Map.of("errorCode",code.matches("NATIVE_[A-Z0-9_]{1,80}")?code:"NATIVE_LIVE_FAILED");}},IO);}catch(RejectedExecutionException rejected){return CompletableFuture.failedFuture(new IllegalStateException("NATIVE_API_BUSY"));}}
    private static AgentQuery liveQuery(ContentAddressedStore content,NativeLiveToolRequest request,BooleanSupplier permit,UUID operation)throws Exception{if(!permit.getAsBoolean())throw new SecurityException("NATIVE_API_PERMISSION_CHANGED");String snapshot=NativeCompilationEnvironment.state().snapshot();AgentQuery result;switch(request.kind()){case "live_state"->{var state=NativeLiveClassAccess.state();result=new AgentQuery(snapshot,0,Map.of("state",state,"operation",operation),"LIVE_CAPABILITY_STATE_NO_CLASS_CAPTURE");}case "loaded"->{var page=NativeLiveClassAccess.loaded(request.query(),request.offset());result=new AgentQuery(snapshot,page.classes().size(),Map.of("classes",page.classes(),"offset",page.offset(),"nextOffset",page.nextOffset(),"more",page.more(),"total",page.total(),"processEpoch",NativeLiveClassAccess.state().processEpoch()),"JVM_LOADED_CLASS_DIRECTORY_NO_CAPTURE");}case "live_members"->{var captured=NativeLiveClassAccess.live(request.classToken());result=liveSymbols(content,captured,request.query(),request.offset(),request.textOffset(),"");}case "live_method_body"->{var captured=NativeLiveClassAccess.live(request.classToken());result=liveMethod(content,captured,request.method(),request.descriptor(),request.offset(),request.textOffset(),"");}case "transformed_members","transformed_method_body"->{var current=NativeCompilationEnvironment.latest();if(!current.hash().equals(request.snapshot()))throw new IllegalStateException("NATIVE_API_SNAPSHOT_CHANGED");var rawSnapshot=NativeCompilationSnapshot.read(content,current.hash());byte[] raw=rawSnapshot.classBytes(content,request.module(),request.className());String rawHash=RuntimePackageCanonicalizer.sha256(raw);var observed=NativeLiveClassAccess.transformed(request.className());var captured=new NativeLiveClassAccess.Captured(observed.bytes(),observed.className(),request.module(),observed.loaderKind(),observed.provenance(),observed.audit());if(!current.hash().equals(NativeCompilationEnvironment.latest().hash()))throw new IllegalStateException("NATIVE_API_SNAPSHOT_CHANGED");result=request.kind().equals("transformed_members")?liveSymbols(content,captured,request.query(),request.offset(),request.textOffset(),rawHash):liveMethod(content,captured,request.method(),request.descriptor(),request.offset(),request.textOffset(),rawHash);snapshot=current.hash();}default->throw new IllegalArgumentException("NATIVE_LIVE_TOOL");}if(!permit.getAsBoolean())throw new SecurityException("NATIVE_API_PERMISSION_CHANGED");return new AgentQuery(snapshot,result.count(),result.value(),result.mode());}
    private static void requireTask(MinecraftServer server,dev.mineagent.runtime.api.task.ManagedTask task){
        if(!server.isSameThread()||task==null||!task.worldId().equals(MineAgentRuntimeServices.worldId(server))||task.status()!=dev.mineagent.runtime.api.task.TaskStatus.RUNNING||dev.mineagent.runtime.core.task.TaskAuthorityFence.revoked(task))throw new SecurityException("NATIVE_API_TASK_CONTEXT");
        var definition=MineAgentRuntimeServices.bodies(server).definitions().stream().filter(d->d.agentId().equals(task.agentId())).findFirst().orElseThrow(()->new SecurityException("NATIVE_API_AGENT"));
        var owner=server.getPlayerList().getPlayer(task.ownerPlayerId());boolean op=owner!=null&&owner.permissions().hasPermission(Permissions.COMMANDS_GAMEMASTER);
        var permissions=MineAgentRuntimeServices.permissions(server);if(!dev.mineagent.runtime.core.task.TaskAuthorityFence.allowed(task,definition,op)||!permissions.canMutateAgent(definition,task.ownerPlayerId(),op)||!permissions.allowed(task.ownerPlayerId(),op,PermissionAction.RUN_CODE)||!permissions.allowed(task.ownerPlayerId(),op,PermissionAction.MANAGE_PACKAGES))throw new SecurityException("NATIVE_API_PERMISSION");
    }
    private static CompletableFuture<Map<String,String>> completed(Map<String,String> value){return CompletableFuture.completedFuture(value);}
    private static Map<String,String> agent(AgentQuery query){try{String result=JSON.writeValueAsString(query.value());if(result.getBytes(java.nio.charset.StandardCharsets.UTF_8).length>24000)throw new IllegalStateException("NATIVE_API_RESPONSE_LIMIT");return Map.of("snapshot",query.snapshot()==null?"":query.snapshot(),"count",Integer.toString(query.count()),"result",result,"executionMode",query.mode());}catch(Exception failure){String code=Objects.toString(failure.getMessage(),"");throw new IllegalStateException(code.matches("NATIVE_API_[A-Z_]{1,80}")?code:"NATIVE_API_FAILED",failure);}}
    private static AgentQuery query(ContentAddressedStore content,Map<String,String> args,BooleanSupplier permit)throws Exception {
        if(!permit.getAsBoolean())throw new SecurityException("NATIVE_API_PERMISSION_CHANGED");var current=NativeCompilationEnvironment.latest();if(!current.hash().equals(args.get("snapshot")))throw new IllegalStateException("NATIVE_API_SNAPSHOT_CHANGED");var snapshot=NativeCompilationSnapshot.read(content,current.hash());if(!snapshot.environment().fingerprint().equals(dev.mineagent.runtime.neoforge.content.NativePackageCompatibility.observe().fingerprint()))throw new IllegalStateException("NATIVE_API_ENVIRONMENT_CHANGED");int offset=integer(args,args.get("kind").equals("source")?"lineOffset":"offset");AgentQuery result;
        if(args.get("kind").equals("modules")){var all=snapshot.modules();if(offset>all.size())throw new IllegalArgumentException("NATIVE_API_OFFSET");var page=all.stream().skip(offset).limit(16).toList();result=new AgentQuery(current.hash(),page.size(),Map.of("snapshot",current.hash(),"namespace",snapshot.namespace(),"physicalSide",snapshot.physicalSide(),"mappingStatus",snapshot.mappingStatus(),"modules",page,"nextOffset",offset+page.size(),"more",offset+page.size()<all.size()),"RAW_CLASS_METADATA_NO_INITIALIZATION");}
        else if(args.get("kind").equals("classes")){var page=snapshot.classPage(content,args.get("module"),args.get("search"),offset,17);var visible=page.stream().limit(16).toList();result=new AgentQuery(current.hash(),visible.size(),Map.of("snapshot",current.hash(),"module",args.get("module"),"classes",visible,"offset",offset,"nextOffset",offset+visible.size(),"more",page.size()>16,"moduleHash",snapshot.module(args.get("module")).sha256()),"RAW_CLASS_METADATA_NO_INITIALIZATION");}
        else if(args.get("kind").equals("members")){byte[] bytes=snapshot.classBytes(content,args.get("module"),args.get("class"));var symbols=ClassFileSymbols.inspect(bytes,args.get("search"),offset);String full=JSON.writerWithDefaultPrettyPrinter().writeValueAsString(symbols);int start=integer(args,"textOffset"),length=full.codePointCount(0,full.length());if(length>4000000||start>length)throw new IllegalStateException("NATIVE_API_SYMBOL_LIMIT");int end=Math.min(length,start+4096);var value=new LinkedHashMap<String,Object>();value.put("snapshot",current.hash());value.put("module",args.get("module"));value.put("class",args.get("class"));value.put("classHash",RuntimePackageCanonicalizer.sha256(bytes));value.put("textHash",RuntimePackageCanonicalizer.sha256(full));value.put("text",full.substring(full.offsetByCodePoints(0,start),full.offsetByCodePoints(0,end)));value.put("nextTextOffset",end);value.put("textMore",end<length);value.put("nextOffset",symbols.nextOffset());value.put("more",symbols.more());value.put("totalMembers",symbols.total());value.put("mappingStatus",snapshot.mappingStatus());value.put("methods",methodSelectors(symbols));var module=snapshot.module(args.get("module"));value.put("sourceAvailable",!module.sourceSha256().isEmpty());value.put("sourceKind",module.sourceKind());result=new AgentQuery(current.hash(),symbols.members().size(),Map.copyOf(value),"RAW_CLASS_METADATA_NO_INITIALIZATION");}
        else if(args.get("kind").equals("method_body")){var body=methodBody(snapshot,content,args,offset);result=new AgentQuery(current.hash(),((Number)body.get("visibleInstructions")).intValue(),body,"RAW_CLASS_METHOD_BYTECODE_NO_INITIALIZATION");}
        else{var source=sourceView(snapshot,content,args,offset);result=new AgentQuery(current.hash(),((Number)source.get("visibleLines")).intValue(),source,"ATTACHED_SOURCE_NO_COMPILATION_OR_EXECUTION");}
        if(!current.hash().equals(NativeCompilationEnvironment.latest().hash())||!permit.getAsBoolean())throw new IllegalStateException("NATIVE_API_SNAPSHOT_CHANGED");return result;
    }
    private static int integer(Map<String,String> args,String key){int n=Integer.parseInt(args.get(key));int maximum=key.equals("textOffset")?4000000:key.equals("lineOffset")?200000:300000;if(n<0||n>maximum)throw new IllegalArgumentException("NATIVE_API_OFFSET");return n;}
    private static List<Map<String,Object>> methodSelectors(ClassFileSymbols.Summary symbols){return symbols.members().stream().filter(m->m.kind().equals("METHOD")).map(m->Map.<String,Object>of("name",m.name(),"descriptor",m.descriptor(),"flags",m.flags())).toList();}
    private static Map<String,Object> methodBody(NativeCompilationSnapshot snapshot,ContentAddressedStore content,Map<String,String> args,int offset)throws Exception{
        byte[] bytes=snapshot.classBytes(content,args.get("module"),args.get("class"));var body=ClassFileMethodBody.inspect(bytes,args.get("method"),args.get("descriptor"),offset);String full=JSON.writerWithDefaultPrettyPrinter().writeValueAsString(body);int start=integer(args,"textOffset"),length=full.codePointCount(0,full.length());if(length>4000000||start>length)throw new IllegalStateException("NATIVE_API_METHOD_TEXT_LIMIT");int end=Math.min(length,start+4096);var value=new LinkedHashMap<String,Object>();value.put("snapshot",args.get("snapshot"));value.put("module",args.get("module"));value.put("class",args.get("class"));value.put("method",args.get("method"));value.put("descriptor",args.get("descriptor"));value.put("classHash",RuntimePackageCanonicalizer.sha256(bytes));value.put("textHash",RuntimePackageCanonicalizer.sha256(full));value.put("text",full.substring(full.offsetByCodePoints(0,start),full.offsetByCodePoints(0,end)));value.put("nextTextOffset",end);value.put("textMore",end<length);value.put("nextOffset",body.nextOffset());value.put("more",body.more());value.put("totalInstructions",body.total());value.put("visibleInstructions",body.instructions().size());value.put("implementationKind",body.implementationKind());value.put("mappingStatus",snapshot.mappingStatus());var module=snapshot.module(args.get("module"));value.put("sourceAvailable",!module.sourceSha256().isEmpty());value.put("sourceKind",module.sourceKind());return Map.copyOf(value);
    }
    private static Map<String,Object> sourceView(NativeCompilationSnapshot snapshot,ContentAddressedStore content,Map<String,String> args,int offset)throws Exception{var view=NativeSourceView.inspect(snapshot,content,args.get("module"),args.get("class"),args.getOrDefault("method",""),args.getOrDefault("descriptor",""),offset);String full=view.text();int start=integer(args,"textOffset"),length=full.codePointCount(0,full.length());if(start>length)throw new IllegalArgumentException("NATIVE_API_TEXT_OFFSET");int end=Math.min(length,start+4096);var value=new LinkedHashMap<String,Object>();value.put("snapshot",args.get("snapshot"));value.put("module",view.module());value.put("class",view.className());value.put("method",view.method());value.put("descriptor",view.descriptor());value.put("sourcePath",view.sourcePath());value.put("sourceHash",view.sourceHash());value.put("sourceArchiveHash",view.sourceArchiveHash());value.put("namespace",view.namespace());value.put("mappingConfidence",view.mappingConfidence());value.put("mappedStartLine",view.mappedStartLine());value.put("mappedEndLine",view.mappedEndLine());value.put("pageStartLine",view.pageStartLine());value.put("pageEndLine",view.pageEndLine());value.put("totalLines",view.totalLines());value.put("textHash",RuntimePackageCanonicalizer.sha256(full));value.put("text",full.substring(full.offsetByCodePoints(0,start),full.offsetByCodePoints(0,end)));value.put("nextTextOffset",end);value.put("textMore",end<length);value.put("nextOffset",view.nextOffset());value.put("more",view.more());value.put("visibleLines",view.pageEndLine()==0?0:view.pageEndLine()-view.pageStartLine()+1);return Map.copyOf(value);}
    private static AgentQuery liveSymbols(ContentAddressedStore content,NativeLiveClassAccess.Captured captured,String search,int offset,int textOffset,String rawHash)throws Exception{var symbols=ClassFileSymbols.inspect(captured.bytes(),search,offset);String full=JSON.writerWithDefaultPrettyPrinter().writeValueAsString(symbols);var text=text(full,textOffset);var stored=content.put(captured.bytes());var value=new LinkedHashMap<String,Object>();value.put("class",captured.className());value.put("module",captured.moduleName());value.put("loader",captured.loaderKind());value.put("processEpoch",NativeLiveClassAccess.state().processEpoch());value.put("provenance",captured.provenance());value.put("audit",captured.audit());value.put("classHash",stored.sha256());value.put("classRef",stored.sha256());value.put("rawClassHash",rawHash);value.put("rawComparison",rawHash.isEmpty()?"NOT_COMPARED":rawHash.equals(stored.sha256())?"SAME":"DIFFERENT");value.put("textHash",RuntimePackageCanonicalizer.sha256(full));value.putAll(text);value.put("nextOffset",symbols.nextOffset());value.put("more",symbols.more());value.put("totalMembers",symbols.total());value.put("methods",methodSelectors(symbols));return new AgentQuery(NativeCompilationEnvironment.state().snapshot(),symbols.members().size(),Map.copyOf(value),captured.provenance());}
    private static AgentQuery liveMethod(ContentAddressedStore content,NativeLiveClassAccess.Captured captured,String method,String descriptor,int offset,int textOffset,String rawHash)throws Exception{var body=ClassFileMethodBody.inspect(captured.bytes(),method,descriptor,offset);String full=JSON.writerWithDefaultPrettyPrinter().writeValueAsString(body);var text=text(full,textOffset);var stored=content.put(captured.bytes());var value=new LinkedHashMap<String,Object>();value.put("class",captured.className());value.put("module",captured.moduleName());value.put("loader",captured.loaderKind());value.put("processEpoch",NativeLiveClassAccess.state().processEpoch());value.put("provenance",captured.provenance());value.put("audit",captured.audit());value.put("method",method);value.put("descriptor",descriptor);value.put("classHash",stored.sha256());value.put("classRef",stored.sha256());value.put("rawClassHash",rawHash);value.put("rawComparison",rawHash.isEmpty()?"NOT_COMPARED":rawHash.equals(stored.sha256())?"SAME":"DIFFERENT");value.put("textHash",RuntimePackageCanonicalizer.sha256(full));value.putAll(text);value.put("nextOffset",body.nextOffset());value.put("more",body.more());value.put("totalInstructions",body.total());value.put("implementationKind",body.implementationKind());return new AgentQuery(NativeCompilationEnvironment.state().snapshot(),body.instructions().size(),Map.copyOf(value),captured.provenance());}
    private static Map<String,Object> text(String full,int start)throws Exception{int length=full.codePointCount(0,full.length());if(length>4000000||start<0||start>length)throw new IllegalArgumentException("NATIVE_API_TEXT_OFFSET");int end=Math.min(length,start+4096);return Map.of("text",full.substring(full.offsetByCodePoints(0,start),full.offsetByCodePoints(0,end)),"nextTextOffset",end,"textMore",end<length);}
    private static Map<String,Object> knowledgeSummary(NativeKnowledgeStore.Entry entry){var type=entry.selection().types().getFirst();var method=entry.selection().methods().isEmpty()?null:entry.selection().methods().getFirst();String liveSnapshot=NativeCompilationEnvironment.state().snapshot(),liveEnvironment="";try{liveEnvironment=dev.mineagent.runtime.neoforge.content.NativePackageCompatibility.observe().fingerprint();}catch(Exception unavailable){/* effective state remains stale */}String effective=entry.state();if(effective.equals("CURRENT")&&(!entry.selection().snapshot().equals(liveSnapshot)||!entry.selection().environment().equals(liveEnvironment)))effective="STALE_REVALIDATION_REQUIRED";var value=new LinkedHashMap<String,Object>();value.put("knowledgeId",entry.knowledgeId());value.put("label",entry.label());value.put("state",effective);value.put("storedState",entry.state());value.put("diagnostic",entry.diagnostic());value.put("module",type.module());value.put("class",type.className());value.put("method",method==null?"":method.name());value.put("descriptor",method==null?"":method.descriptor());value.put("snapshot",entry.selection().snapshot());value.put("semanticHash",entry.semanticHash());value.put("updatedAt",entry.updatedAt());return Map.copyOf(value);}
    private static Map<String,Object> knowledgeDetail(NativeKnowledgeStore.Entry entry,boolean duplicate){var value=new LinkedHashMap<String,Object>(knowledgeSummary(entry));value.put("duplicate",duplicate);value.put("selection",entry.selection());value.put("context",entry.context());value.put("sourceTask",entry.sourceTask());value.put("sourceOperation",entry.sourceOperation());value.put("revision",entry.revision());if(entry.candidateSelection()!=null){value.put("candidateSelection",entry.candidateSelection());value.put("candidateContext",entry.candidateContext());value.put("candidateSemanticHash",entry.candidateSemanticHash());}return Map.copyOf(value);}
}
