package dev.mineagent.runtime.neoforge.compile;

import dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer;
import dev.mineagent.runtime.core.compile.NativeCoderContext;
import net.neoforged.fml.classloading.transformation.TransformingClassLoader;
import net.neoforged.fml.loading.FMLLoader;
import net.neoforged.neoforgespi.transformation.ProcessorName;
import java.lang.classfile.ClassFile;
import java.lang.instrument.*;
import java.lang.ref.WeakReference;
import java.lang.reflect.*;
import java.nio.charset.StandardCharsets;
import java.security.ProtectionDomain;
import java.util.*;
import java.util.concurrent.atomic.AtomicReference;

/** Capability-detected access to FML transformed bytes and loaded JVM definitions. Reflection failure is explicit, never a raw fallback. */
public final class NativeLiveClassAccess {
    static final long SELECTION_TTL_MILLIS=10*60*1000L;
    public record State(boolean instrumentationAvailable,boolean retransformSupported,boolean transformingLoaderAvailable,boolean transformAccessAvailable,String processEpoch,String error){}
    public record Loaded(UUID token,String className,String moduleName,boolean namedModule,String loaderKind,String codeSourceHash,boolean modifiable){}
    public record Page(List<Loaded> classes,int offset,int nextOffset,boolean more,int total){public Page{classes=List.copyOf(classes);}}
    public record Captured(byte[] bytes,String className,String moduleName,String loaderKind,String provenance,String audit){public Captured{bytes=bytes.clone();}public byte[] bytes(){return bytes.clone();}}
    private static final UUID EPOCH=UUID.randomUUID();private static final Object LOCK=new Object();private static final IdentityHashMap<Class<?>,UUID> IDS=new IdentityHashMap<>();private static final Map<UUID,WeakReference<Class<?>>> TOKENS=new LinkedHashMap<>();private static volatile Instrumentation instrumentation;private static volatile String instrumentationError="";
    private record Frozen(UUID id,UUID world,UUID viewer,String snapshot,NativeCoderContext.Overlay overlay,long expires){}
    private static final Map<UUID,Frozen> FROZEN=new LinkedHashMap<>();
    private NativeLiveClassAccess(){}
    public static State state(){Instrumentation value=instrumentation();ClassLoader loader=null;try{loader=FMLLoader.getCurrent().getCurrentClassLoader();}catch(Exception unavailable){}return new State(value!=null,value!=null&&value.isRetransformClassesSupported(),loader instanceof TransformingClassLoader,transformAccess(loader),EPOCH.toString(),instrumentationError);}
    public static Page loaded(String query,int offset)throws Exception{if(query==null||query.length()>128||offset<0||offset>300000)throw new IllegalArgumentException("NATIVE_LIVE_QUERY");var value=requireInstrumentation();Class<?>[] all=value.getAllLoadedClasses();if(all.length>300000)throw new IllegalStateException("NATIVE_LIVE_CLASS_LIMIT");String wanted=query.toLowerCase(Locale.ROOT);var matches=Arrays.stream(all).filter(c->!c.isArray()&&!c.isPrimitive()&&c.getName().toLowerCase(Locale.ROOT).contains(wanted)).sorted(Comparator.comparing((Class<?> c)->c.getName()).thenComparing(NativeLiveClassAccess::moduleName).thenComparing(NativeLiveClassAccess::loaderKind)).toList();if(offset>matches.size())throw new IllegalArgumentException("NATIVE_LIVE_OFFSET");var page=matches.stream().skip(offset).limit(16).map(c->describe(value,c)).toList();return new Page(page,offset,offset+page.size(),offset+page.size()<matches.size(),matches.size());}
    public static Captured live(UUID token)throws Exception{Instrumentation value=requireInstrumentation();Class<?> target; synchronized(LOCK){var ref=TOKENS.get(token);target=ref==null?null:ref.get();}if(target==null)throw new IllegalStateException("NATIVE_LIVE_TOKEN_STALE");if(!value.isRetransformClassesSupported()||!value.isModifiableClass(target))throw new IllegalStateException("NATIVE_LIVE_CLASS_NOT_MODIFIABLE");var captured=new AtomicReference<byte[]>();ClassFileTransformer transformer=new ClassFileTransformer(){@Override public byte[] transform(Module module,ClassLoader loader,String name,Class<?> redefined,ProtectionDomain domain,byte[] bytes){if(redefined==target)captured.compareAndSet(null,bytes.clone());return null;}};synchronized(LOCK){value.addTransformer(transformer,true);try{value.retransformClasses(target);}finally{value.removeTransformer(transformer);}}byte[] bytes=captured.get();if(bytes==null)throw new IllegalStateException("NATIVE_LIVE_CAPTURE_MISSING");verify(bytes,target.getName());return new Captured(bytes,target.getName(),moduleName(target),loaderKind(target),"JVM_RETRANSFORM_LIVE_DEFINITION",audit(target.getName()));}
    public static Captured transformed(String className)throws Exception{if(className==null||className.isBlank()||className.length()>512||className.contains("/")||className.contains("\\")||className.contains(".."))throw new IllegalArgumentException("NATIVE_LIVE_CLASS");var loader=FMLLoader.getCurrent().getCurrentClassLoader();if(!(loader instanceof TransformingClassLoader transforming))throw new IllegalStateException("NATIVE_TRANSFORM_LOADER_UNAVAILABLE");byte[] bytes;try{Method method=TransformingClassLoader.class.getDeclaredMethod("buildTransformedClassNodeFor",String.class,ProcessorName.class);if(!method.trySetAccessible())throw new IllegalAccessException("not open");synchronized(LOCK){bytes=(byte[])method.invoke(transforming,className,new ProcessorName("mineagent","inspection"));}}catch(InvocationTargetException failure){Throwable cause=failure.getCause();if(cause instanceof Exception exception)throw exception;throw new IllegalStateException("NATIVE_TRANSFORM_CAPTURE_FAILED",cause);}catch(ReflectiveOperationException failure){throw new IllegalStateException("NATIVE_TRANSFORM_ACCESS_UNAVAILABLE",failure);}verify(bytes,className);return new Captured(bytes,className,"","TransformingClassLoader","FML_TRANSFORM_PIPELINE_PREDEFINE",audit(className));}
    public static UUID register(UUID world,UUID viewer,String snapshot,Map<String,?> value){return register(world,viewer,snapshot,value,System.currentTimeMillis());}
    static UUID register(UUID world,UUID viewer,String snapshot,Map<String,?> value,long now){String className=Objects.toString(value.get("class"),""),classRef=Objects.toString(value.get("classRef"),""),classHash=Objects.toString(value.get("classHash"),""),rawHash=Objects.toString(value.get("rawClassHash"),""),provenance=Objects.toString(value.get("provenance"),""),epoch=Objects.toString(value.get("processEpoch"),""),module=Objects.toString(value.get("module"),""),loader=Objects.toString(value.get("loader"),""),method=Objects.toString(value.get("method"),""),descriptor=Objects.toString(value.get("descriptor"),""),audit=Objects.toString(value.get("audit"),"");if(world==null||viewer==null||snapshot==null||!snapshot.matches("[a-f0-9]{64}")||!epoch.equals(EPOCH.toString())||now<0)throw new IllegalArgumentException("NATIVE_LIVE_SELECTION");var overlay=new NativeCoderContext.Overlay(module,className,classRef,classHash,rawHash,provenance,epoch,loader,method,descriptor,audit);synchronized(LOCK){prune(now);for(var entry:FROZEN.entrySet()){var frozen=entry.getValue();if(frozen.world().equals(world)&&frozen.viewer().equals(viewer)&&frozen.snapshot().equals(snapshot)&&frozen.overlay().equals(overlay)){FROZEN.put(entry.getKey(),new Frozen(entry.getKey(),world,viewer,snapshot,overlay,now+SELECTION_TTL_MILLIS));return entry.getKey();}}if(FROZEN.size()>=4096)throw new IllegalStateException("NATIVE_LIVE_SELECTION_BUDGET");UUID id=UUID.randomUUID();FROZEN.put(id,new Frozen(id,world,viewer,snapshot,overlay,now+SELECTION_TTL_MILLIS));return id;}}
    public static List<NativeCoderContext.Overlay> resolve(UUID world,UUID viewer,String snapshot,List<UUID> ids){return resolve(world,viewer,snapshot,ids,System.currentTimeMillis());}
    static List<NativeCoderContext.Overlay> resolve(UUID world,UUID viewer,String snapshot,List<UUID> ids,long now){if(world==null||viewer==null||snapshot==null||!snapshot.matches("[a-f0-9]{64}")||ids==null||ids.isEmpty()||ids.size()>16||ids.stream().anyMatch(Objects::isNull)||ids.stream().distinct().count()!=ids.size()||now<0)throw new IllegalArgumentException("NATIVE_LIVE_SELECTION");synchronized(LOCK){prune(now);var result=new ArrayList<NativeCoderContext.Overlay>();for(var id:ids){var value=FROZEN.get(id);if(value==null||!value.world().equals(world)||!value.viewer().equals(viewer)||!value.snapshot().equals(snapshot)||!value.overlay().processEpoch().equals(EPOCH.toString()))throw new IllegalStateException("NATIVE_LIVE_SELECTION_STALE");result.add(value.overlay());}return List.copyOf(result);}}
    public static void clear(UUID viewer){synchronized(LOCK){FROZEN.values().removeIf(v->v.viewer().equals(viewer));}}
    private static void prune(long now){FROZEN.values().removeIf(v->v.expires()<now);}
    private static Loaded describe(Instrumentation value,Class<?> type){UUID token; synchronized(LOCK){token=IDS.computeIfAbsent(type,key->{UUID id=UUID.nameUUIDFromBytes((EPOCH+"|"+System.identityHashCode(key)+"|"+key.getName()).getBytes(StandardCharsets.UTF_8));while(TOKENS.containsKey(id))id=UUID.randomUUID();TOKENS.put(id,new WeakReference<>(key));while(TOKENS.size()>4096){var first=TOKENS.entrySet().iterator();var removed=first.next();first.remove();var current=removed.getValue().get();if(current!=null)IDS.remove(current);}return id;});}return new Loaded(token,type.getName(),moduleName(type),type.getModule()!=null&&type.getModule().isNamed(),loaderKind(type),codeSource(type),value.isModifiableClass(type));}
    private static Instrumentation requireInstrumentation(){var value=instrumentation();if(value==null)throw new IllegalStateException("NATIVE_INSTRUMENTATION_UNAVAILABLE");return value;}
    private static Instrumentation instrumentation(){var value=instrumentation;if(value!=null)return value;synchronized(LOCK){if(instrumentation!=null)return instrumentation;if(!instrumentationError.isEmpty())return null;try{var loader=FMLLoader.getCurrent();Field resources=FMLLoader.class.getDeclaredField("ownedResources");if(!resources.trySetAccessible())throw new IllegalAccessException("ownedResources");for(Object resource:(List<?>)resources.get(loader))if(resource!=null&&resource.getClass().getName().equals("net.neoforged.fml.loading.ClassLoadingGuardian")){Field field=resource.getClass().getDeclaredField("instrumentation");if(!field.trySetAccessible())throw new IllegalAccessException("instrumentation");if(field.get(resource) instanceof Instrumentation found){instrumentation=found;return found;}}instrumentationError="NATIVE_INSTRUMENTATION_NOT_RETAINED";}catch(Exception failure){instrumentationError="NATIVE_INSTRUMENTATION_ACCESS_UNAVAILABLE";}return null;}}
    private static void verify(byte[] bytes,String name)throws Exception{if(bytes==null||bytes.length<1||bytes.length>8*1024*1024||!ClassFile.of().parse(bytes).thisClass().asInternalName().replace('/','.').equals(name))throw new IllegalStateException("NATIVE_LIVE_CLASS_BYTES_INVALID");}
    private static String audit(String name){try{String value=FMLLoader.getCurrent().getClassTransformerAuditLog().getAuditString(name);return value==null?"":value.length()>8192?value.substring(0,8192):value;}catch(Exception unavailable){return "";}}
    private static boolean transformAccess(ClassLoader loader){if(!(loader instanceof TransformingClassLoader))return false;try{return TransformingClassLoader.class.getDeclaredMethod("buildTransformedClassNodeFor",String.class,ProcessorName.class).trySetAccessible();}catch(Exception unavailable){return false;}}
    private static String moduleName(Class<?> value){var module=value.getModule();return module==null||!module.isNamed()?"":Objects.toString(module.getName(),"");}
    private static String loaderKind(Class<?> value){var loader=value.getClassLoader();return loader==null?"BOOTSTRAP":loader.getClass().getName();}
    private static String codeSource(Class<?> value){try{var source=value.getProtectionDomain()==null?null:value.getProtectionDomain().getCodeSource();return source==null||source.getLocation()==null?"":RuntimePackageCanonicalizer.sha256(source.getLocation().toExternalForm());}catch(Exception unavailable){return "";}}
}
