package dev.mineagent.runtime.neoforge.client.body;

import com.fasterxml.jackson.databind.*;import com.fasterxml.jackson.databind.node.ObjectNode;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;import dev.mineagent.runtime.neoforge.WorldActivationRuntime;
import dev.mineagent.runtime.neoforge.body.MineAgentPlayer;import dev.mineagent.runtime.neoforge.ui.ConversationAgentTools;
import net.minecraft.client.Minecraft;import net.minecraft.core.*;import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.entity.*;import net.minecraft.world.item.*;import net.minecraft.world.level.GameType;import net.minecraft.world.level.block.*;import net.minecraft.world.level.block.state.properties.*;import net.minecraft.world.phys.Vec3;
import net.neoforged.api.distmarker.Dist;import net.neoforged.bus.api.SubscribeEvent;import net.neoforged.fml.common.EventBusSubscriber;import net.neoforged.neoforge.client.event.ClientTickEvent;
import java.nio.file.*;import java.util.*;import java.util.concurrent.*;import java.util.function.*;

/** Isolated world acceptance through the real public tool path; never enabled in a normal installation. */
@EventBusSubscriber(modid="mineagent_runtime",value=Dist.CLIENT)
public final class PersistentSkillSmokeClient {
    private static final ObjectMapper JSON=new ObjectMapper();private record Step(String name,int timeout,Supplier<CompletableFuture<Boolean>> run){}
    private static final Deque<Step> STEPS=new ArrayDeque<>();private static final List<Object> EVIDENCE=new ArrayList<>();
    private static UUID agent,second,zombie;private static int ticks,stageAt;private static boolean initialized,busy,done;private static Vec3 stoppedAt;private static long baseline;
    private static JsonNode lastObservation;
    private static final List<UUID> manyAgents=new ArrayList<>();
    private static final List<UUID> combatants=new ArrayList<>();private static UUID oldBehaviorRequest;private static boolean sawRunningCooldown,sawHurtWithoutStun;
    private static String uiSkillId="";
    private static UUID raceOperation,localConversation,localOperation;
    private static void tacticalSurvival(){
        action("native-skeleton-and-normal-equipment",()->server(p->{var b=controlled(p);b.teleportTo(p.level(),.5,101,6.5,Set.of(),-90,0,true);b.getInventory().setItem(12,new ItemStack(Items.SHIELD));b.getInventory().setItem(13,new ItemStack(Items.BREAD,8));b.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.DIAMOND_HELMET));b.setItemSlot(EquipmentSlot.CHEST,new ItemStack(Items.DIAMOND_CHESTPLATE));b.setItemSlot(EquipmentSlot.LEGS,new ItemStack(Items.DIAMOND_LEGGINGS));b.setItemSlot(EquipmentSlot.FEET,new ItemStack(Items.DIAMOND_BOOTS));b.inventoryMenu.broadcastChanges();var skeleton=EntityType.SKELETON.create(p.level(),EntitySpawnReason.COMMAND);skeleton.setPos(12.5,101,6.5);skeleton.setItemSlot(EquipmentSlot.MAINHAND,new ItemStack(Items.BOW));skeleton.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.IRON_HELMET));skeleton.setTarget(b);p.level().addFreshEntity(skeleton);zombie=skeleton.getUUID();return Map.of("enemy",zombie,"health",skeleton.getHealth(),"nativeAi",!skeleton.isNoAi());}));
        action("hold-position-with-native-shield",()->{var n=start("ranged_threat","ai").put("target",zombie.toString());n.putObject("combat").put("strategy","hold_position");return tool("combat_entity",n);});
        waitFor("actual-arrow-blocked-by-shield",1800,()->state("ranged_threat",s->s.path("counters").path("nativeShieldBlocks").asInt()>0));
        action("switch-to-ranged-without-replacing-intent",()->{var n=JSON.createObjectNode().put("id","ranged_threat").put("expected_revision",1);n.putObject("combat").put("strategy","ranged_kite");return tool("set_combat_policy",n);});
        waitFor("moving-ranged-enemy-native-gravity-hits",2200,()->state("ranged_threat",s->s.path("state").asText().equals("COMPLETED")&&s.path("counters").path("nativeGravityHits").asInt()>0&&s.path("counters").path("arrowsReleased").asInt()>0));
        action("injured-and-hungry-recovery-scenario",()->server(p->{var b=controlled(p);b.teleportTo(p.level(),.5,101,6.5,Set.of(),-90,0,true);b.setHealth(5);b.getFoodData().setFoodLevel(8);b.getFoodData().setSaturation(0);var mob=EntityType.ZOMBIE.create(p.level(),EntitySpawnReason.COMMAND);mob.setPos(14.5,101,6.5);mob.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.IRON_HELMET));mob.setTarget(b);p.level().addFreshEntity(mob);zombie=mob.getUUID();baseline=b.getInventory().countItem(Items.BREAD);return Map.of("initialHealth",b.getHealth(),"initialFood",b.getFoodData().getFoodLevel(),"initialBread",baseline);}));
        action("disengage-and-use-real-food",()->{var n=start("recover","ai").put("kind","idle");n.putObject("combat").put("strategy","disengage").put("engagement","self_defense");return tool("set_behavior_mode",n);});
        waitFor("food-finished-and-consumed-natively",1600,()->state("recover",s->s.path("counters").path("nativeFoodConsumptions").asInt()>0));
        action("no-granted-food-or-direct-healing",()->server(p->{var b=controlled(p);require(b.getInventory().countItem(Items.BREAD)<baseline&&b.getFoodData().getFoodLevel()>8,"NATIVE_FOOD_NOT_CONSUMED");EVIDENCE.add(Map.of("health",b.getHealth(),"food",b.getFoodData().getFoodLevel(),"bread",b.getInventory().countItem(Items.BREAD)));dev.mineagent.runtime.neoforge.skill.SkillRuntime.get(p.level().getServer()).stopAll(p,agent);return null;}));
    }
    private static CompletableFuture<Map<String,Object>> raceStart;
    private static void tacticalRules(){
        action("load-durable-skill-state",()->tool("inspect_behavior",JSON.createObjectNode()));
        action("start-and-stop-before-save-callback",()->server(p->{var runtime=dev.mineagent.runtime.neoforge.skill.SkillRuntime.get(p.level().getServer());raceOperation=UUID.randomUUID();raceStart=runtime.start(p,agent,raceOperation,null,start("race_stop","ai").put("kind","idle"),null,()->true);runtime.stopAll(p,agent);return null;}));
        waitFor("cancelled-start-future-finishes",300,()->CompletableFuture.completedFuture(raceStart.isDone()));
        action("cancelled-start-stays-terminal",()->{require(raceStart.join().get("status").equals("CANCELLED"),"STOP_DURING_START_REVIVED");return CompletableFuture.completedFuture(raceStart.join());});
        action("prepare-temporary-work-chain",()->server(p->{crops(p,3,3,6);return null;}));
        action("persistent-farm-before-temporary-work",()->tool("farm_area",area("resume_farm","ai",3,101,6,3,101,6).put("defend",true)));
        waitFor("original-farm-makes-real-progress",1000,()->state("resume_farm",s->s.path("counters").path("planted").asInt()>0));
        action("temporary-patrol-keeps-parent",()->{var n=start("temporary_route","ai").put("repeat",false).put("resume_previous",true).put("dwell_ticks",100);n.putArray("route").addArray().add(10.5).add(101).add(6.5);return tool("patrol_route",n);});
        action("edit-only-combat-during-temporary-work",()->{var n=JSON.createObjectNode().put("id","temporary_route").put("expected_revision",1);n.putObject("combat").put("strategy","hit_and_run");return tool("set_combat_policy",n);});
        action("parent-stays-paused-with-new-combat-policy",()->tool("inspect_behavior",JSON.createObjectNode()).thenApply(data->{var parent=session(data,"resume_farm");require(parent.path("state").asText().equals("PAUSED")&&parent.path("reason").asText().equals("TEMPORARY_WORK"),"POLICY_UNPAUSED_PARENT");require(parent.path("spec").path("combat").path("strategy").asText().equals("HIT_AND_RUN"),"PARENT_POLICY_NOT_UPDATED");return data;}));
        waitFor("temporary-work-completes",1600,()->state("temporary_route",s->s.path("state").asText().equals("COMPLETED")));
        action("mature-after-temporary-work",()->server(p->{crops(p,3,3,6);return null;}));
        waitFor("same-parent-resumes-with-progress",1200,()->state("resume_farm",s->s.path("counters").path("planted").asInt()>1&&s.path("spec").path("combat").path("strategy").asText().equals("HIT_AND_RUN")));
        action("finite-work-with-independent-self-defense",()->{var n=start("finite_route","ai").put("defend",true).put("repeat",false).put("dwell_ticks",0);n.putArray("route").addArray().add(8.5).add(101).add(6.5);return tool("patrol_route",n);});
        waitFor("finite-work-remains-completed",1000,()->state("finite_route",s->s.path("state").asText().equals("COMPLETED")));
        waitFor("standby-preserves-self-defense",300,()->tool("inspect_behavior",JSON.createObjectNode()).thenApply(data->{for(var row:data.path("skills")){var s=row.path("session");if(s.path("spec").path("kind").asText().equals("IDLE")&&s.path("receipt").has("completedWork")&&s.path("spec").path("combat").path("engagement").asText().equals("SELF_DEFENSE")){EVIDENCE.add(data);return true;}}return false;}));
        action("local-chat-stop-with-no-model-provider",()->server(p->{try{var conversations=dev.mineagent.runtime.neoforge.ui.ServerConversations.get(p.level().getServer());var c=conversations.store().create(p.getUUID(),agent,UUID.randomUUID(),"本地指令验收",false);localConversation=c.conversationId();localOperation=UUID.randomUUID();return conversations.write(p,localOperation,Map.of("kind","send","agentId",agent.toString(),"conversationId",localConversation.toString(),"expectedRevision",Long.toString(c.revision()),"text","停下，什么也别做"));}catch(Exception e){throw new CompletionException(e);}}));
        waitFor("local-chat-receipt-is-complete",300,()->server(p->{try{var c=dev.mineagent.runtime.neoforge.ui.ServerConversations.get(p.level().getServer()).store().context(p.getUUID(),agent,localConversation,null).orElseThrow();if(c.requestState().equals("COMPLETE")){EVIDENCE.add(c);return true;}require(!c.requestState().equals("FAILED"),"LOCAL_RECEIPT_FAILED_"+c.errorCode());return false;}catch(Exception e){throw new CompletionException(e);}}));
        action("stop-removes-standby",()->tool("inspect_behavior",JSON.createObjectNode()).thenApply(data->{for(var row:data.path("skills"))require(Set.of("COMPLETED","CANCELLED","FAILED").contains(row.path("session").path("state").asText()),"STANDBY_RESTARTED_AFTER_STOP");return data;}));
    }
    private static boolean playerActor(){return System.getProperty("mineagent.skillSmokeActor","ai").equals("player");}
    private static ServerPlayer controlled(ServerPlayer p){return playerActor()?p:body(p);}
    private static Minecraft mc(){return Minecraft.getInstance();}private static Path root()throws Exception{return Files.createDirectories(mc().gameDirectory.toPath().resolve(Boolean.getBoolean("mineagent.skillSmokeResume")?"persistent-skill-resume":"persistent-skill-smoke"));}
    private static Path identityFile(){return mc().gameDirectory.toPath().resolve("persistent-skill-smoke/identity.json");}
    private static void require(boolean value,String reason){if(!value)throw new IllegalStateException(reason);}
    private static <T> CompletableFuture<T> server(Function<ServerPlayer,T> work){var out=new CompletableFuture<T>();var s=mc().getSingleplayerServer();UUID player=mc().player.getUUID();s.submit(()->work.apply(s.getPlayerList().getPlayer(player))).whenComplete((value,error)->mc().execute(()->{if(error!=null)out.completeExceptionally(error);else out.complete(value);}));return out;}
    private static MineAgentPlayer body(ServerPlayer p){return MineAgentRuntimeServices.bodies(p.level().getServer()).body(agent).orElseThrow();}
    private static CompletableFuture<JsonNode> tool(UUID ai,String name,ObjectNode args){return server(p->ConversationAgentTools.execute(p,ai,UUID.randomUUID(),name,args.toString(),()->true)).thenCompose(Function.identity()).thenApply(value->{var n=JSON.valueToTree(value);if(n.path("status").asText().equals("REJECTED"))throw new IllegalStateException(name+":"+n);return n;});}
    private static CompletableFuture<JsonNode> tool(String name,ObjectNode args){return tool(agent,name,args);}
    private static JsonNode session(JsonNode result,String id){for(var value:result.path("skills"))if(value.path("session").path("spec").path("id").asText().equals(id))return value.path("session");throw new IllegalStateException("SKILL_NOT_LISTED_"+id);}
    private static CompletableFuture<Boolean> state(String id,Predicate<JsonNode> ready){return tool("inspect_skills",JSON.createObjectNode()).thenApply(value->{lastObservation=value;var s=session(value,id);if(Set.of("FAILED","PAUSED").contains(s.path("state").asText()))throw new IllegalStateException("SKILL_RUNTIME_"+s);if(ready.test(s)){EVIDENCE.add(value);return true;}if(Set.of("COMPLETED","CANCELLED").contains(s.path("state").asText()))throw new IllegalStateException("SKILL_ENDED_WITHOUT_EXPECTED_PROOF_"+s);return false;});}
    private static void action(String name,Supplier<CompletableFuture<?>> action){STEPS.add(new Step(name,800,()->action.get().thenApply(value->{if(value!=null)EVIDENCE.add(Map.of("step",name,"result",value));return true;})));}
    private static void waitFor(String name,int timeout,Supplier<CompletableFuture<Boolean>> predicate){STEPS.add(new Step(name,timeout,predicate));}
    private static ObjectNode start(String id,String actor){return JSON.createObjectNode().put("id",id).put("actor",playerActor()?"player":actor).put("dimension","minecraft:overworld").put("expected_revision",0).put("defend",false);}
    private static ObjectNode area(String id,String actor,int x1,int y1,int z1,int x2,int y2,int z2){var n=start(id,actor);n.putArray("min").add(x1).add(y1).add(z1);n.putArray("max").add(x2).add(y2).add(z2);return n;}
    private static CompletableFuture<JsonNode> stop(String id){return tool("control_skill",JSON.createObjectNode().put("id",id).put("expected_revision",1).put("action","stop"));}
    private static void screen(String name){try{net.minecraft.client.Screenshot.takeScreenshot(mc().getMainRenderTarget(),image->{try(image){image.writeToFile(root().resolve(name+".png"));}catch(Exception failure){fail(failure);}});}catch(Exception e){fail(e);}}
    private static void prepare(){
        if(Boolean.getBoolean("mineagent.skillSmokeResume")){restoreLifecycle();return;}
        action("world-and-real-survival-bodies",()->server(p->{
            var s=p.level().getServer();s.getPlayerList().op(p.nameAndId());p.setGameMode(GameType.CREATIVE);WorldActivationRuntime.decide(p.createCommandSourceStack(),true,null);p.teleportTo(p.level(),.5,101,-3.5,Set.of(),0,0,true);
            for(int x=-12;x<=31;x++)for(int z=-7;z<=26;z++)for(int y=98;y<=109;y++)p.level().setBlock(new BlockPos(x,y,z),y<=100?Blocks.STONE.defaultBlockState():Blocks.AIR.defaultBlockState(),2);
            agent=MineAgentRuntimeServices.bodies(s).createPersistentAt("持续技能搭档",p.getUUID(),p.level(),new Vec3(.5,101,6.5)).agentId();var b=body(p);b.setGameMode(GameType.SURVIVAL);b.getInventory().clearContent();b.getInventory().setItem(0,new ItemStack(Items.DIAMOND_SWORD));b.getInventory().setItem(1,new ItemStack(Items.WHEAT_SEEDS,32));b.getInventory().setItem(2,new ItemStack(Items.IRON_HOE));b.getInventory().setItem(3,new ItemStack(Items.BOW));b.getInventory().setItem(4,new ItemStack(Items.ARROW,32));var rod=new ItemStack(Items.FISHING_ROD);var lure=p.registryAccess().lookupOrThrow(net.minecraft.core.registries.Registries.ENCHANTMENT).getOrThrow(net.minecraft.world.item.enchantment.Enchantments.LURE);net.minecraft.world.item.enchantment.EnchantmentHelper.updateEnchantments(rod,e->e.set(lure,3));b.getInventory().setItem(5,rod);return Map.of("agent",agent,"mode",b.gameMode.getGameModeForPlayer().name());
        }));
        String mode=System.getProperty("mineagent.skillSmokeMode","work");
        if(playerActor()){waitFor("signed-player-control-activation",300,()->{if(dev.mineagent.runtime.neoforge.client.MineAgentClientTrustPrompt.enabled())return CompletableFuture.completedFuture(true);dev.mineagent.runtime.neoforge.client.MineAgentClientTrustPrompt.smokeEnable();return CompletableFuture.completedFuture(false);});action("real-player-equipment-and-input",()->{org.lwjgl.glfw.GLFW.glfwFocusWindow(mc().getWindow().handle());return server(p->{var b=body(p);p.setGameMode(GameType.SURVIVAL);p.getInventory().clearContent();for(int i=0;i<36;i++)p.getInventory().setItem(i,b.getInventory().getItem(i).copy());p.inventoryMenu.broadcastChanges();b.teleportTo(p.level(),27.5,101,25.5,Set.of(),0,0,true);return null;});});}
        if(mode.equals("tactical_survival")){tacticalSurvival();return;}if(mode.equals("tactical_rules")){tacticalRules();return;}if(mode.equals("tactical_ui")){tacticalUi();return;}if(mode.equals("tactical")){tactical();return;}if(mode.equals("navigation")){navigation();return;}if(mode.equals("fishing")||mode.equals("fishing_defense")){fishing();return;}if(mode.equals("combat")){combat();return;}if(mode.equals("player")){player();return;}if(mode.equals("cooperation")){cooperation();return;}if(mode.equals("patrol")){patrol();return;}if(mode.equals("performance")){performance();return;}if(mode.equals("lifecycle")){lifecycle();return;}if(mode.equals("uncertain")){uncertain();return;}if(mode.equals("crops")){cropAdapters();return;}work();
    }
    private static void tacticalUi(){
        action("ui-area-context",()->server(p->{p.teleportTo(p.level(),.5,101,6.5,Set.of(),0,0,true);crops(p,3,3,6);return null;}));
        waitFor("enable-through-signed-client-choice",300,()->{if(dev.mineagent.runtime.neoforge.client.MineAgentClientTrustPrompt.enabled())return CompletableFuture.completedFuture(true);dev.mineagent.runtime.neoforge.client.MineAgentClientTrustPrompt.smokeEnable();return CompletableFuture.completedFuture(false);});
        action("open-f2-native-workspace",()->{dev.mineagent.runtime.neoforge.client.nativeui.NativeWorkspaceScreen.open();return CompletableFuture.completedFuture(null);});
        waitFor("f2-ready",400,()->CompletableFuture.completedFuture(dev.mineagent.runtime.neoforge.client.nativeui.NativeWorkspaceConnection.ready()&&mc().screen instanceof dev.mineagent.runtime.neoforge.client.nativeui.NativeWorkspaceScreen));
        action("f2-integrated-behavior-editor",()->{dev.mineagent.runtime.neoforge.client.nativeui.NativeBehaviorPanel.open((dev.mineagent.runtime.neoforge.client.nativeui.NativeWorkspaceScreen)mc().screen,agent.toString(),"持续技能搭档");return CompletableFuture.completedFuture(null);});
        waitFor("f2-mode-state-loaded",300,()->CompletableFuture.completedFuture(dev.mineagent.runtime.neoforge.client.nativeui.NativeBehaviorPanel.smokeReady(agent.toString())));
        action("choose-farming-from-player-position",()->{dev.mineagent.runtime.neoforge.client.nativeui.NativeBehaviorPanel.smokeSelect(agent.toString(),"mode","FARM");dev.mineagent.runtime.neoforge.client.nativeui.NativeBehaviorPanel.smokeSelect(agent.toString(),"region","CURRENT");dev.mineagent.runtime.neoforge.client.nativeui.NativeBehaviorPanel.smokeClick(agent.toString(),"切换主工作",false);baseline=ticks;return CompletableFuture.completedFuture(null);});
        waitFor("mouse-down-does-not-apply-mode",40,()->tool("inspect_behavior",JSON.createObjectNode()).thenApply(value->{require(value.path("skills").isEmpty(),"MODE_TRIGGERED_ON_PRESS");return ticks-baseline>=10;}));
        action("mouse-release-applies-mode",()->{dev.mineagent.runtime.neoforge.client.nativeui.NativeBehaviorPanel.smokeClick(agent.toString(),"切换主工作",true);return CompletableFuture.completedFuture(null);});
        waitFor("ui-farm-is-working",1500,()->tool("inspect_behavior",JSON.createObjectNode()).thenApply(value->{lastObservation=value;for(var row:value.path("skills")){var s=row.path("session");if(s.path("spec").path("kind").asText().equals("FARM")&&s.path("counters").path("planted").asInt()>0){uiSkillId=s.path("spec").path("id").asText();EVIDENCE.add(value);return true;}}return false;}));
        action("capture-f2-mode-panel",()->{screen("f2-behavior-panel");dev.mineagent.runtime.neoforge.client.nativeui.AgentProfileScreen.open(agent,"持续技能搭档");return CompletableFuture.completedFuture(null);});
        waitFor("profile-open",150,()->CompletableFuture.completedFuture(mc().screen instanceof dev.mineagent.runtime.neoforge.client.nativeui.AgentProfileScreen));
        action("open-profile-behavior-tab",()->{var s=(dev.mineagent.runtime.neoforge.client.nativeui.AgentProfileScreen)mc().screen;s.smokeBehaviorTab(false);s.smokeBehaviorTab(true);return CompletableFuture.completedFuture(null);});
        waitFor("profile-mode-state-loaded",300,()->CompletableFuture.completedFuture(dev.mineagent.runtime.neoforge.client.nativeui.NativeBehaviorPanel.smokeReady(agent.toString())));
        action("change-only-combat-style",()->{dev.mineagent.runtime.neoforge.client.nativeui.NativeBehaviorPanel.smokeSelect(agent.toString(),"strategy","HIT_AND_RUN");dev.mineagent.runtime.neoforge.client.nativeui.NativeBehaviorPanel.smokeClick(agent.toString(),"只改战斗规则",false);dev.mineagent.runtime.neoforge.client.nativeui.NativeBehaviorPanel.smokeClick(agent.toString(),"只改战斗规则",true);return CompletableFuture.completedFuture(null);});
        waitFor("profile-preserved-farm-id-and-progress",300,()->state(uiSkillId,s->s.path("revision").asInt()==2&&s.path("spec").path("kind").asText().equals("FARM")&&s.path("spec").path("combat").path("strategy").asText().equals("HIT_AND_RUN")&&s.path("counters").path("planted").asInt()>0));
        action("profile-stop-all-button",()->{screen("ai-profile-behavior-panel");dev.mineagent.runtime.neoforge.client.nativeui.NativeBehaviorPanel.smokeClick(agent.toString(),"全部停止",false);dev.mineagent.runtime.neoforge.client.nativeui.NativeBehaviorPanel.smokeClick(agent.toString(),"全部停止",true);return CompletableFuture.completedFuture(null);});
        waitFor("profile-stop-is-terminal",200,()->state(uiSkillId,s->s.path("state").asText().equals("CANCELLED")));
    }
    private static void tactical(){
        action("normal-survival-equipment",()->server(p->{var b=controlled(p);b.teleportTo(p.level(),.5,101,6.5,Set.of(),0,0,true);b.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.DIAMOND_HELMET));b.setItemSlot(EquipmentSlot.CHEST,new ItemStack(Items.DIAMOND_CHESTPLATE));b.setItemSlot(EquipmentSlot.LEGS,new ItemStack(Items.DIAMOND_LEGGINGS));b.setItemSlot(EquipmentSlot.FEET,new ItemStack(Items.DIAMOND_BOOTS));b.getInventory().setItem(3,ItemStack.EMPTY);b.getInventory().setItem(6,new ItemStack(Items.SHIELD));b.getInventory().setItem(7,new ItemStack(Items.BREAD,16));b.inventoryMenu.broadcastChanges();crops(p,3,3,6);oldBehaviorRequest=UUID.randomUUID();dev.mineagent.runtime.neoforge.skill.BehaviorAuthority.get(p.level().getServer()).accepted(p,agent,oldBehaviorRequest,"维护这片田，遇怪用跑打");return Map.of("maxHealth",b.getMaxHealth(),"attackReach",b.getAttackRangeWith(b.getMainHandItem()).effectiveMaxRange(b));}));
        action("start-tactical-farm",()->tool("farm_area",area("tactical_farm","ai",3,101,6,3,101,6).put("defend",true).put("crop","minecraft:wheat")));
        waitFor("farm-before-combat",1000,()->state("tactical_farm",s->s.path("counters").path("planted").asInt()>0));
        action("style-change-preserves-main-work",()->{var n=JSON.createObjectNode().put("id","tactical_farm").put("expected_revision",1);n.putObject("combat").put("strategy","HIT_AND_RUN");return tool("set_combat_policy",n).thenApply(value->{var s=value.path("skill").path("session");require(s.path("spec").path("kind").asText().equals("FARM")&&s.path("counters").path("planted").asInt()>0,"STYLE_REPLACED_WORK");return value;});});
        action("three-active-zombies-from-different-directions",()->server(p->{var b=controlled(p);for(double[] offset:new double[][]{{4.5,0},{-3.5,3.5},{-3.5,-3.5}}){var mob=EntityType.ZOMBIE.create(p.level(),EntitySpawnReason.COMMAND);mob.setPos(b.getX()+offset[0],101,b.getZ()+offset[1]);mob.setPersistenceRequired();mob.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.IRON_HELMET));mob.setTarget(b);p.level().addFreshEntity(mob);combatants.add(mob.getUUID());require(!mob.isNoAi(),"ENEMY_AI_WAS_DISABLED");}return Map.of("enemies",combatants,"modelCalls",0);}));
        waitFor("local-multi-threat-hit-and-run",6000,()->tool("inspect_behavior",JSON.createObjectNode()).thenCompose(value->server(p->{lastObservation=value;var s=session(value,"tactical_farm");require(!Set.of("PAUSED","FAILED","CANCELLED").contains(s.path("state").asText()),"TACTICAL_SESSION_STOPPED_"+s);require(controlled(p).isAlive(),"TACTICAL_BODY_DIED");for(var row:value.path("skills"))if(row.path("session").path("spec").path("id").asText().equals("tactical_farm"))for(var threat:row.path("combat").path("threats")){var actual=threat.path("actual");if(actual.path("hurtAnimationTicks").asInt()>0){require(actual.path("restrictions").isEmpty(),"HURT_ANIMATION_ASSUMED_STUN");sawHurtWithoutStun=true;}for(var attack:actual.path("attacks"))if(attack.path("running").asBoolean()&&attack.path("cooldownTicks").asInt(-1)>=0)sawRunningCooldown=true;}
            if(combatants.stream().anyMatch(id->{var e=p.level().getEntity(id);return e!=null&&e.isAlive();}))return false;
            require(s.path("counters").path("verifiedHits").asInt()>=3&&s.path("counters").path("tactic_LURE").asInt()>0&&s.path("counters").path("tactic_MELEE_EXIT").asInt()>0,"TACTICS_OR_NATIVE_DAMAGE_NOT_OBSERVED");require(sawRunningCooldown&&sawHurtWithoutStun,"REAL_COMBAT_TELEMETRY_NOT_OBSERVED");EVIDENCE.add(value);EVIDENCE.add(Map.of("actualHealth",controlled(p).getHealth(),"runningCooldownRead",sawRunningCooldown,"hurtNotStun",sawHurtWithoutStun));return true;})));
        action("farm-matures-after-defense",()->server(p->{crops(p,3,3,6);return null;}));
        waitFor("resume-original-farm",1600,()->state("tactical_farm",s->s.path("counters").path("planted").asInt()>1&&s.path("counters").path("workResumptions").asInt()>0));
        if(!playerActor()){
            action("immediate-follow-without-model",()->server(p->{dev.mineagent.runtime.neoforge.skill.BehaviorAuthority.get(p.level().getServer()).accepted(p,agent,UUID.randomUUID(),"跟着我");return null;}));
            waitFor("new-follow-intent-replaces-farm",300,()->tool("inspect_behavior",JSON.createObjectNode()).thenApply(data->{for(var row:data.path("skills"))if(row.path("session").path("spec").path("kind").asText().equals("FOLLOW")&&Set.of("RUNNING","WAITING").contains(row.path("session").path("state").asText()))return true;return false;}));
        }
        action("late-old-model-cannot-restore-work",()->server(p->{var a=dev.mineagent.runtime.neoforge.skill.BehaviorAuthority.get(p.level().getServer());if(playerActor())a.invalidate(p,agent);require(!a.current(p,agent,oldBehaviorRequest),"OLD_MODEL_REMAINS_AUTHORIZED");return null;}));
        action("explicit-stop-is-immediate",()->server(p->{dev.mineagent.runtime.neoforge.skill.BehaviorAuthority.get(p.level().getServer()).accepted(p,agent,UUID.randomUUID(),"停下，什么也别做");baseline=p.level().getServer().getTickCount();return null;}));
        waitFor("stop-does-not-auto-restart",150,()->tool("inspect_behavior",JSON.createObjectNode()).thenCompose(value->server(p->{if(p.level().getServer().getTickCount()-baseline<80)return false;for(var row:value.path("skills"))require(Set.of("COMPLETED","CANCELLED","FAILED").contains(row.path("session").path("state").asText()),"STOPPED_WORK_REVIVED");EVIDENCE.add(value);return true;})));
    }
    private static void corridor(ServerPlayer p,boolean openEntrance){
        for(int x=-1;x<=23;x++)for(int y=101;y<=107;y++){p.level().setBlock(new BlockPos(x,y,-1),Blocks.STONE.defaultBlockState(),2);p.level().setBlock(new BlockPos(x,y,1),Blocks.STONE.defaultBlockState(),2);}for(int y=101;y<=107;y++){p.level().setBlock(new BlockPos(-1,y,0),Blocks.STONE.defaultBlockState(),2);p.level().setBlock(new BlockPos(23,y,0),Blocks.STONE.defaultBlockState(),2);}
            var door=Blocks.OAK_DOOR.defaultBlockState().setValue(DoorBlock.FACING,Direction.WEST);p.level().setBlock(new BlockPos(4,101,0),door.setValue(DoorBlock.HALF,DoubleBlockHalf.LOWER),2);p.level().setBlock(new BlockPos(4,102,0),door.setValue(DoorBlock.HALF,DoubleBlockHalf.UPPER),2);p.level().setBlock(new BlockPos(5,102,0),Blocks.STONE_SLAB.defaultBlockState().setValue(SlabBlock.TYPE,SlabType.TOP),2);p.level().setBlock(new BlockPos(7,101,0),Blocks.STONE_SLAB.defaultBlockState(),2);
            for(int x=9;x<=12;x++){p.level().setBlock(new BlockPos(x,99,0),Blocks.WATER.defaultBlockState(),2);p.level().setBlock(new BlockPos(x,100,0),Blocks.WATER.defaultBlockState(),2);}for(int x=17;x<=22;x++)for(int y=101;y<=103;y++)p.level().setBlock(new BlockPos(x,y,0),Blocks.STONE.defaultBlockState(),2);for(int y=101;y<=103;y++)p.level().setBlock(new BlockPos(16,y,0),Blocks.LADDER.defaultBlockState().setValue(LadderBlock.FACING,Direction.WEST),2);

        if(openEntrance)for(int y=101;y<=107;y++)p.level().setBlock(new BlockPos(-1,y,0),Blocks.AIR.defaultBlockState(),2);
    }
    private static void navigation(){
        action("forced-door-slab-crouch-water-ladder-route",()->server(p->{var b=body(p);corridor(p,false);
            controlled(p).teleportTo(p.level(),.5,101,.5,Set.of(),-90,0,true);if(!playerActor())b.movementController().movePreciselyTo(new Vec3(21.5,104,.5));return null;}));
        if(playerActor()){
            action("real-player-terrain-patrol",()->{var n=start("terrain","player").put("repeat",false);n.putArray("route").addArray().add(21.5).add(104).add(.5);return tool("patrol_route",n);});
            waitFor("real-player-terrain-arrival",2200,()->state("terrain",s->s.path("state").asText().equals("COMPLETED")));
            action("real-player-terrain-motion-proof",()->{var proof=NativeSkillInput.motionEvidence();require(((Number)proof.get("climbingTicks")).intValue()>0&&((Number)proof.get("swimmingTicks")).intValue()>0&&((Number)proof.get("crouchingTicks")).intValue()>0,"REAL_PLAYER_TERRAIN_ACTIONS_MISSING "+proof);EVIDENCE.add(proof);return CompletableFuture.completedFuture(null);});return;
        }
        waitFor("native-route-arrival",1800,()->server(p->{var b=body(p);var nav=b.movementController();lastObservation=JSON.valueToTree(Map.of("navigation",nav.evidence(),"position",b.position().toString(),"outcome",nav.outcome()));if(!nav.outcome().equals("ARRIVED")){require(nav.outcome().equals("MOVING"),"NAVIGATION_"+nav.outcome()+" "+nav.evidence()+" "+b.position());return false;}var proof=nav.evidence();require(((Number)proof.get("openedDoors")).intValue()>0&&((Number)proof.get("crouchingSteps")).intValue()>0&&((Number)proof.get("swimmingSteps")).intValue()>0&&((Number)proof.get("climbingSteps")).intValue()>0,"NAVIGATION_ACTIONS_MISSING "+proof);EVIDENCE.add(proof);return true;}));
        action("sealed-unreachable-test",()->server(p->{var b=body(p);for(int x=-7;x<=-5;x++)for(int z=4;z<=6;z++)if(x!=-6||z!=5)for(int y=101;y<=105;y++)p.level().setBlock(new BlockPos(x,y,z),Blocks.STONE.defaultBlockState(),2);b.teleportTo(p.level(),-5.5,101,5.5,Set.of(),0,0,true);baseline=p.level().getServer().getTickCount();b.movementController().moveTo(new Vec3(-1.5,101,5.5));return null;}));
        waitFor("retry-backoff-is-real",300,()->server(p->{var b=body(p);if(!b.movementController().outcome().equals("UNREACHABLE"))return false;long elapsed=p.level().getServer().getTickCount()-baseline;require(elapsed>=60,"EMPTY_ROUTE_BYPASSED_BACKOFF");EVIDENCE.add(Map.of("retryElapsed",elapsed,"search",b.movementController().evidence()));return true;}));
    }
    private static void crops(ServerPlayer p,int from,int to,int z){for(int x=from;x<=to;x++){p.level().setBlock(new BlockPos(x,100,z),Blocks.FARMLAND.defaultBlockState().setValue(BlockStateProperties.MOISTURE,7),2);p.level().setBlock(new BlockPos(x,101,z),Blocks.WHEAT.defaultBlockState().setValue(CropBlock.AGE,7),2);}p.level().setBlock(new BlockPos(from,100,z+1),Blocks.WATER.defaultBlockState(),2);}
    private static void work(){
        action("farm-targets",()->server(p->{crops(p,3,5,6);return null;}));action("start-farm-through-tool",()->tool("farm_area",area("farm","ai",3,101,6,5,101,6).put("defend",true).put("crop","minecraft:wheat")));
        waitFor("real-harvest-and-replant",1400,()->state("farm",s->s.path("counters").path("planted").asInt()>=1));
        action("interrupt-farm-with-monster",()->server(p->{var b=body(p);var mob=EntityType.ZOMBIE.create(p.level(),EntitySpawnReason.COMMAND);mob.setPos(b.getX()+2,101,b.getZ());mob.setTarget(b);mob.setHealth(4);mob.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.IRON_HELMET));p.level().addFreshEntity(mob);zombie=mob.getUUID();return Map.of("zombie",zombie);}));
        waitFor("native-defense-damage",1000,()->state("farm",s->s.path("counters").path("verifiedHits").asInt()>0));
        waitFor("monster-defeated",1000,()->server(p->{var e=p.level().getEntity(zombie);return e==null||!e.isAlive();}));
        action("mature-after-defense",()->server(p->{crops(p,3,5,6);return null;}));
        action("save-resume-counter",()->tool("inspect_skills",JSON.createObjectNode()).thenAccept(v->baseline=session(v,"farm").path("counters").path("planted").asLong()));
        waitFor("farm-resumed-after-defense",1400,()->state("farm",s->s.path("counters").path("planted").asLong()>baseline));
        action("terrain-after-farm-and-defense",()->server(p->{corridor(p,true);return null;}));
        action("switch-to-follow",()->tool("follow_entity",start("follow","ai").put("target","$owner")));
        action("owner-moves-first",()->server(p->{p.teleportTo(p.level(),18.5,104,.5,Set.of(),0,0,true);return null;}));
        waitFor("follow-started",500,()->server(p->body(p).getX()>5));
        action("owner-moves-again",()->server(p->{p.teleportTo(p.level(),21.5,104,.5,Set.of(),0,0,true);return null;}));
        waitFor("follows-live-entity-position",1400,()->server(p->body(p).distanceTo(p)<3));
        action("integrated-follow-terrain-evidence",()->server(p->{var proof=body(p).movementController().evidence();require(((Number)proof.get("openedDoors")).intValue()>0&&((Number)proof.get("crouchingSteps")).intValue()>0&&((Number)proof.get("swimmingSteps")).intValue()>0&&((Number)proof.get("climbingSteps")).intValue()>0,"INTEGRATED_FOLLOW_TERRAIN_MISSING "+proof);return proof;}));
        action("cancel-follow",()->stop("follow"));action("remember-stop-position",()->server(p->{stoppedAt=body(p).position();baseline=p.level().getServer().getTickCount();return null;}));
        waitFor("cancel-is-terminal",100,()->server(p->{if(p.level().getServer().getTickCount()-baseline<40)return false;require(body(p).position().distanceToSqr(stoppedAt)<.1,"CANCELLED_SKILL_MOVED");return true;}));
    }
    private static void fishing(){
        boolean defense=System.getProperty("mineagent.skillSmokeMode","").equals("fishing_defense");
        action("native-fishing-water-and-shore",()->server(p->{for(int x=-6;x<=-1;x++)for(int z=12;z<=18;z++)for(int y=99;y<=100;y++)p.level().setBlock(new BlockPos(x,y,z),Blocks.WATER.defaultBlockState(),2);controlled(p).teleportTo(p.level(),.5,101,14.5,Set.of(),90,25,true);return null;}));
        if(defense)action("unenchanted-rod-for-interruption-window",()->server(p->{controlled(p).getInventory().setItem(5,new ItemStack(Items.FISHING_ROD));return null;}));
        action("start-fishing",()->tool("fish_at",area("fish","ai",-6,100,12,-1,100,18).put("limit",1).put("defend",defense)));
        if(defense){
            waitFor("owned-hook-waiting-before-threat",1500,()->state("fish",s->s.path("phase").asText().equals("FISH_WAIT_BITE")));
            action("threat-interrupts-owned-cast",()->server(p->{var b=controlled(p);var mob=EntityType.ZOMBIE.create(p.level(),EntitySpawnReason.COMMAND);mob.setPos(b.getX()+1.8,b.getY(),b.getZ());mob.setTarget(b);mob.setHealth(4);mob.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.IRON_HELMET));p.level().addFreshEntity(mob);return null;}));
            waitFor("fishing-session-keeps-progress-through-defense",1500,()->state("fish",s->s.path("counters").path("verifiedHits").asInt()>0&&s.path("counters").path("interruptedCasts").asInt()==1));
        }
        waitFor("actual-bite-reel-loot",7500,()->state("fish",s->s.path("state").asText().equals("COMPLETED")&&s.path("counters").path("fishingCatches").asInt()==1));
    }
    private static void combat(){
        action("ranged-target",()->server(p->{controlled(p).teleportTo(p.level(),.5,101,6.5,Set.of(),-90,0,true);var mob=EntityType.ZOMBIE.create(p.level(),EntitySpawnReason.COMMAND);mob.setPos(12.5,101,6.5);mob.setNoAi(true);mob.setHealth(4);mob.setItemSlot(EquipmentSlot.HEAD,new ItemStack(Items.IRON_HELMET));p.level().addFreshEntity(mob);zombie=mob.getUUID();return null;}));
        action("start-native-bow-combat",()->tool("combat_entity",start("bow","ai").put("target",zombie.toString())));
        waitFor("native-bow-hit-and-consumption",1800,()->state("bow",s->s.path("state").asText().equals("COMPLETED")&&s.path("counters").path("verifiedHits").asInt()>0&&s.path("counters").path("arrowsReleased").asInt()>0));
    }
    private static void cooperation(){
        action("two-survival-farmers-one-plot",()->server(p->{var manager=MineAgentRuntimeServices.bodies(p.level().getServer());second=manager.createPersistentAt("协作农务搭档",p.getUUID(),p.level(),new Vec3(.5,101,10.5)).agentId();var b=manager.body(second).orElseThrow();b.setGameMode(GameType.SURVIVAL);b.getInventory().clearContent();b.getInventory().setItem(0,new ItemStack(Items.WHEAT_SEEDS,16));body(p).teleportTo(p.level(),.5,101,8.5,Set.of(),0,0,true);crops(p,5,5,9);return null;}));
        action("simultaneous-farm-intents",()->CompletableFuture.allOf(tool("farm_area",area("coop_a","ai",5,101,9,5,101,9).put("crop","minecraft:wheat")),tool(second,"farm_area",area("coop_b","ai",5,101,9,5,101,9).put("crop","minecraft:wheat"))));
        waitFor("one-harvest-one-replant",1500,()->tool("inspect_skills",JSON.createObjectNode()).thenCombine(tool(second,"inspect_skills",JSON.createObjectNode()),(a,b)->{var sa=session(a,"coop_a");var sb=session(b,"coop_b");long harvested=sa.path("counters").path("harvested").asLong()+sb.path("counters").path("harvested").asLong(),planted=sa.path("counters").path("planted").asLong()+sb.path("counters").path("planted").asLong();require(harvested<=1&&planted<=1,"DUPLICATED_SHARED_PLOT");if(planted==1){require(sa.path("counters").path("reservationConflicts").asLong()+sb.path("counters").path("reservationConflicts").asLong()>0,"RESERVATION_CONTENTION_NOT_EXERCISED");require(harvested==1,"PLANT_WITHOUT_NATIVE_HARVEST");EVIDENCE.add(Map.of("first",a,"second",b));return true;}return false;}));
        action("stop-both-farmers",()->CompletableFuture.allOf(stop("coop_a"),tool(second,"control_skill",JSON.createObjectNode().put("id","coop_b").put("expected_revision",1).put("action","stop"))));
        action("start-paused-farm",()->tool("farm_area",area("paused_farm","ai",5,101,9,5,101,9).put("crop","minecraft:wheat")));
        waitFor("no-mature-crop-is-waiting",300,()->state("paused_farm",s->s.path("state").asText().equals("WAITING")));
        action("explicit-pause",()->tool("control_skill",JSON.createObjectNode().put("id","paused_farm").put("expected_revision",1).put("action","pause")));
        action("mature-paused-plot",()->server(p->{crops(p,5,5,9);baseline=p.level().getServer().getTickCount();return null;}));
        waitFor("pause-keeps-crop-untouched",350,()->server(p->{if(p.level().getServer().getTickCount()-baseline<140)return false;require(p.level().getBlockState(new BlockPos(5,101,9)).getValue(CropBlock.AGE)==7,"PAUSED_FARM_CHANGED_WORLD");return true;}));
        action("resume-same-session",()->tool("control_skill",JSON.createObjectNode().put("id","paused_farm").put("expected_revision",2).put("action","resume")));
        waitFor("resumed-native-result",1000,()->state("paused_farm",s->s.path("counters").path("planted").asLong()>=1));
        action("stop-resumed-session",()->tool("control_skill",JSON.createObjectNode().put("id","paused_farm").put("expected_revision",3).put("action","stop")));
    }
    private static void patrol(){
        action("start-patrol-route",()->{var n=start("patrol","ai").put("repeat",false).put("dwell_ticks",10);var r=n.putArray("route");r.addArray().add(6.5).add(101).add(6.5);r.addArray().add(6.5).add(101).add(11.5);r.addArray().add(.5).add(101).add(11.5);return tool("patrol_route",n);});
        waitFor("all-waypoints-reached",1600,()->state("patrol",s->s.path("state").asText().equals("COMPLETED")&&s.path("counters").path("waypointsReached").asInt()==3));
        action("start-reachable-idle",()->tool("wander_area",area("wander","ai",-3,100,4,9,102,15).put("limit",2).put("dwell_ticks",5)));
        waitFor("reachable-idle-visits",1600,()->state("wander",s->s.path("state").asText().equals("COMPLETED")&&s.path("counters").path("wanderVisits").asInt()==2));
    }
    private static void performance(){
        action("sixteen-isolated-navigation-intents",()->server(p->{var manager=MineAgentRuntimeServices.bodies(p.level().getServer());for(int i=0;i<16;i++){int x=-8+(i%4)*3,z=3+(i/4)*4;var id=manager.createPersistentAt("并发寻路"+i,p.getUUID(),p.level(),new Vec3(x+.5,101,z+.5)).agentId();manyAgents.add(id);var b=manager.body(id).orElseThrow();b.movementController().movePreciselyTo(new Vec3(x+14.5,101,z+.5));}baseline=p.level().getServer().getTickCount();return null;}));
        waitFor("all-searches-get-budget-and-move",1600,()->server(p->{var manager=MineAgentRuntimeServices.bodies(p.level().getServer());int moved=0;var values=new ArrayList<Object>();for(var id:manyAgents){var b=manager.body(id).orElseThrow();if(b.movementController().executedSteps()>0)moved++;values.add(Map.of("id",id,"position",b.position().toString(),"navigation",b.movementController().evidence()));}if(moved<16)return false;var budget=dev.mineagent.runtime.neoforge.body.NativeNavigationBudget.get(p.level().getServer()).observation();require(((Number)budget.get("maxReservedNodesPerTick")).intValue()<=1024,"SEARCH_BUDGET_EXCEEDED");EVIDENCE.add(Map.of("agents",16,"elapsedTicks",p.level().getServer().getTickCount()-baseline,"budget",budget,"navigation",values));return true;}));
    }
    private static void lifecycle(){
        action("restart-farm-plot",()->server(p->{crops(p,3,3,6);return null;}));
        action("start-restartable-intent",()->tool("farm_area",area("saved_farm","ai",3,101,6,3,101,6).put("crop","minecraft:wheat")));
        waitFor("durable-progress-before-restart",1200,()->state("saved_farm",s->s.path("counters").path("planted").asInt()>=1));
        action("pause-before-world-close",()->tool("control_skill",JSON.createObjectNode().put("id","saved_farm").put("expected_revision",1).put("action","pause")));
        action("persist-restart-identity",()->server(p->{try{crops(p,3,3,6);Files.writeString(root().resolve("identity.json"),JSON.writeValueAsString(Map.of("agent",agent,"seeds",body(p).getInventory().countItem(Items.WHEAT_SEEDS),"sourcePhase","PREPARED_FOR_REAL_RESTART")));return null;}catch(Exception e){throw new CompletionException(e);}}));
    }
    private static void cropAdapters(){
        action("six-native-crop-types",()->server(p->{var b=body(p);b.getInventory().setItem(6,new ItemStack(Items.CARROT,16));b.getInventory().setItem(7,new ItemStack(Items.POTATO,16));b.getInventory().setItem(8,new ItemStack(Items.BEETROOT_SEEDS,16));b.getInventory().setItem(9,new ItemStack(Items.NETHER_WART,16));b.getInventory().setItem(10,new ItemStack(Items.SWEET_BERRIES,16));Block[] types={Blocks.WHEAT,Blocks.CARROTS,Blocks.POTATOES,Blocks.BEETROOTS,Blocks.NETHER_WART,Blocks.SWEET_BERRY_BUSH};for(int i=0;i<types.length;i++){int x=3+i;p.level().setBlock(new BlockPos(x,100,6),i==4?Blocks.SOUL_SAND.defaultBlockState():i==5?Blocks.DIRT.defaultBlockState():Blocks.FARMLAND.defaultBlockState().setValue(BlockStateProperties.MOISTURE,7),2);var crop=types[i];var state=crop instanceof CropBlock growing?growing.getStateForAge(growing.getMaxAge()):crop==Blocks.NETHER_WART?crop.defaultBlockState().setValue(NetherWartBlock.AGE,3):crop.defaultBlockState().setValue(SweetBerryBushBlock.AGE,3);p.level().setBlock(new BlockPos(x,101,6),state,2);}p.level().setBlock(new BlockPos(4,100,7),Blocks.WATER.defaultBlockState(),2);return null;}));
        action("farm-through-crop-adapters",()->tool("farm_area",area("adapters","ai",3,101,6,8,101,6).put("repeat",false)));
        waitFor("crop-native-results",2200,()->state("adapters",s->s.path("state").asText().equals("COMPLETED")&&s.path("counters").path("harvested").asInt()==6&&s.path("counters").path("planted").asInt()==5));
        action("empty-hand-berry-use",()->server(p->{body(p).setItemInHand(net.minecraft.world.InteractionHand.MAIN_HAND,ItemStack.EMPTY);p.level().setBlock(new BlockPos(8,101,6),Blocks.SWEET_BERRY_BUSH.defaultBlockState().setValue(SweetBerryBushBlock.AGE,3),2);return null;}));
        action("native-empty-hand-adapter",()->tool("farm_area",area("empty_berry","ai",8,101,6,8,101,6).put("repeat",false).put("crop","minecraft:sweet_berry_bush")));
        waitFor("empty-hand-native-result",1200,()->state("empty_berry",s->s.path("state").asText().equals("COMPLETED")&&s.path("counters").path("harvested").asInt()==1));
        action("till-and-plant-target",()->server(p->{p.level().setBlock(new BlockPos(3,100,12),Blocks.DIRT.defaultBlockState(),2);p.level().setBlock(new BlockPos(3,101,12),Blocks.AIR.defaultBlockState(),2);p.level().setBlock(new BlockPos(3,100,13),Blocks.WATER.defaultBlockState(),2);return null;}));
        action("native-till-and-replant",()->tool("farm_area",area("till","ai",3,101,12,3,101,12).put("repeat",false).put("crop","minecraft:wheat").put("till",true)));
        waitFor("native-till-effect",1200,()->state("till",s->s.path("state").asText().equals("COMPLETED")&&s.path("counters").path("tilled").asInt()==1&&s.path("counters").path("planted").asInt()==1));
    }
    private static void restoreLifecycle(){
        action("read-same-world-identity",()->{try{agent=UUID.fromString(JSON.readTree(Files.readString(identityFile())).path("agent").asText());return CompletableFuture.completedFuture(null);}catch(Exception e){return CompletableFuture.failedFuture(e);}});
        waitFor("same-ai-restored",600,()->server(p->MineAgentRuntimeServices.bodies(p.level().getServer()).body(agent).isPresent()));
        action("observe-saved-session",()->tool("inspect_skills",JSON.createObjectNode()).thenAccept(value->{var s=session(value,"saved_farm");require(s.path("state").asText().equals("PAUSED")&&s.path("revision").asInt()==2&&s.path("counters").path("planted").asInt()==1,"RESTART_DID_NOT_PRESERVE_PAUSED_PROGRESS");EVIDENCE.add(value);}));
        action("restart-observation-start",()->server(p->{baseline=p.level().getServer().getTickCount();return null;}));
        waitFor("restart-does-not-replay",350,()->server(p->{if(p.level().getServer().getTickCount()-baseline<160)return false;try{var original=JSON.readTree(Files.readString(identityFile()));require(body(p).getInventory().countItem(Items.WHEAT_SEEDS)==original.path("seeds").asInt(),"RESTART_CONSUMED_INVENTORY");require(p.level().getBlockState(new BlockPos(3,101,6)).getValue(CropBlock.AGE)==7,"RESTART_CHANGED_PAUSED_CROP");return true;}catch(Exception e){throw new CompletionException(e);}}));
        action("explicit-resume-saved-session",()->tool("control_skill",JSON.createObjectNode().put("id","saved_farm").put("expected_revision",2).put("action","resume")));
        waitFor("saved-session-continues",1200,()->state("saved_farm",s->s.path("counters").path("planted").asInt()==2));
        action("cancel-resumed-session",()->tool("control_skill",JSON.createObjectNode().put("id","saved_farm").put("expected_revision",3).put("action","stop")));
    }
    private static void uncertain(){
        action("uncertain-effect-plot",()->server(p->{crops(p,3,3,6);return null;}));
        action("one-cycle-with-receipt-fault",()->tool("farm_area",area("uncertain_farm","ai",3,101,6,3,101,6).put("repeat",false).put("crop","minecraft:wheat")));
        waitFor("native-effect-retained-with-uncertain-receipt",1200,()->tool("inspect_skills",JSON.createObjectNode()).thenApply(value->{lastObservation=value;var s=session(value,"uncertain_farm");if(!s.path("state").asText().equals("PAUSED"))return false;require(s.path("receipt").path("state").asText().equals("PREPARED")&&s.path("reason").asText().contains("ACCEPTANCE_AFTER_NATIVE_PLANT"),"FAULT_NOT_AFTER_REAL_PLANT");EVIDENCE.add(value);return true;}));
        action("record-actual-effect",()->server(p->{require(p.level().getBlockState(new BlockPos(3,101,6)).is(Blocks.WHEAT),"UNKNOWN_WORLD_EFFECT_MISSING");baseline=body(p).getInventory().countItem(Items.WHEAT_SEEDS);return Map.of("seedCountAfterNativePlant",baseline);}));
        action("reject-blind-resume",()->server(p->ConversationAgentTools.execute(p,agent,UUID.randomUUID(),"control_skill",JSON.createObjectNode().put("id","uncertain_farm").put("expected_revision",1).put("action","resume").toString(),()->true)).thenCompose(Function.identity()).handle((value,error)->{require(error!=null||!"APPLIED".equals(value.get("status")),"UNCERTAIN_RESUMED_WITHOUT_RECONCILE");return Map.of("blindResumeRejected",true);}));
        action("observe-instead-of-replay",()->tool("control_skill",JSON.createObjectNode().put("id","uncertain_farm").put("expected_revision",1).put("action","reconcile")));
        action("new-explicit-resume-after-observation",()->tool("control_skill",JSON.createObjectNode().put("id","uncertain_farm").put("expected_revision",2).put("action","resume")));
        waitFor("reconciled-scan-complete",500,()->state("uncertain_farm",s->s.path("state").asText().equals("COMPLETED")));
        action("no-second-consumption",()->server(p->{require(body(p).getInventory().countItem(Items.WHEAT_SEEDS)==baseline,"UNCERTAIN_ACTION_REPLAYED");return null;}));
    }
    private static void hudClick(String name,String button){waitFor(name,200,()->{if(!mc().isWindowActive()){org.lwjgl.glfw.GLFW.glfwFocusWindow(mc().getWindow().handle());return CompletableFuture.completedFuture(false);}dev.mineagent.runtime.neoforge.client.nativeui.AutonomyControlPanel.smokeClick(button);return CompletableFuture.completedFuture(true);});}
    private static void player(){
        action("player-farm-setup",()->server(p->{body(p).teleportTo(p.level(),5.5,101,16.5,Set.of(),0,0,true);p.setGameMode(GameType.SURVIVAL);p.teleportTo(p.level(),.5,101,6.5,Set.of(),-90,0,true);p.getInventory().clearContent();p.getInventory().setItem(0,new ItemStack(Items.DIAMOND_SWORD));p.getInventory().setItem(12,new ItemStack(Items.WHEAT_SEEDS,12));p.inventoryMenu.broadcastChanges();crops(p,3,3,6);return null;}));
        action("focus-only-test-game",()->{mc().options.pauseOnLostFocus=true;org.lwjgl.glfw.GLFW.glfwFocusWindow(mc().getWindow().handle());return CompletableFuture.completedFuture(null);});
        action("start-real-player-farm",()->tool("farm_area",area("player_farm","player",3,101,6,3,101,6).put("crop","minecraft:wheat")));
        waitFor("native-player-input-harvest-replant",1800,()->state("player_farm",s->s.path("counters").path("planted").asInt()>=1));
        action("released-cursor-and-append-button",()->{require(!mc().mouseHandler.isMouseGrabbed(),"AUTONOMY_CURSOR_NOT_RELEASED");require(!mc().options.pauseOnLostFocus,"AUTONOMY_DID_NOT_OVERRIDE_FOCUS_PAUSE");dev.mineagent.runtime.neoforge.client.nativeui.AutonomyControlPanel.smokeClick("append");require(mc().screen instanceof net.minecraft.client.gui.screens.ChatScreen,"APPEND_DID_NOT_OPEN_CHAT");return CompletableFuture.completedFuture(null);});
        action("grow-while-chat-open",()->server(p->{crops(p,3,3,6);return null;}));
        waitFor("chat-does-not-pause-farming",1000,()->state("player_farm",s->s.path("counters").path("planted").asInt()>=2));
        action("open-native-f2-while-farming",()->{require(mc().screen instanceof net.minecraft.client.gui.screens.ChatScreen,"CHAT_WAS_CLOSED_BY_CONTROL");dev.mineagent.runtime.neoforge.client.nativeui.NativeWorkspaceScreen.open();return server(p->{crops(p,3,3,6);return null;});});
        waitFor("f2-does-not-pause-farming",1000,()->state("player_farm",s->s.path("counters").path("planted").asInt()>=3));
        action("background-test-game",()->{mc().setScreen(null);org.lwjgl.glfw.GLFW.glfwIconifyWindow(mc().getWindow().handle());return server(p->{crops(p,3,3,6);return null;});});
        waitFor("background-does-not-pause-farming",1400,()->state("player_farm",s->s.path("counters").path("planted").asInt()>=4));
        action("restore-test-game",()->{org.lwjgl.glfw.GLFW.glfwRestoreWindow(mc().getWindow().handle());org.lwjgl.glfw.GLFW.glfwFocusWindow(mc().getWindow().handle());return CompletableFuture.completedFuture(null);});
        waitFor("panel-ready-after-background",150,()->CompletableFuture.completedFuture(mc().isWindowActive()&&Boolean.TRUE.equals(dev.mineagent.runtime.neoforge.client.nativeui.AutonomyControlPanel.observation().get("visible"))));
        hudClick("pause-using-hud-button","pause");
        waitFor("manual-pause-acknowledged",150,()->CompletableFuture.completedFuture(AutonomousBodyClient.manuallyPaused()));
        action("grow-during-manual-pause",()->server(p->{crops(p,3,3,6);baseline=p.level().getServer().getTickCount();return null;}));
        waitFor("manual-pause-blocks-actions",350,()->server(p->{if(p.level().getServer().getTickCount()-baseline<140)return false;require(p.level().getBlockState(new BlockPos(3,101,6)).getValue(CropBlock.AGE)==7,"MANUAL_PAUSE_STILL_HARVESTED");return true;}));
        hudClick("continue-using-hud-button","pause");
        waitFor("resume-server-acknowledged",200,()->tool("inspect_behavior",JSON.createObjectNode()).thenApply(data->!session(data,"player_farm").path("state").asText().equals("PAUSED")));
        waitFor("manual-resume-continues-work",1000,()->state("player_farm",s->s.path("counters").path("planted").asInt()>=5));
        hudClick("exit-using-hud-button","exit");
        action("exit-restores-user-preference",()->{require(!AutonomousBodyClient.active(),"EXIT_BUTTON_FAILED");require(mc().options.pauseOnLostFocus,"FOCUS_PAUSE_PREFERENCE_NOT_RESTORED");return CompletableFuture.completedFuture(null);});
        waitFor("exit-button-cancels-skill",150,()->state("player_farm",s->s.path("state").asText().equals("CANCELLED")));
        action("remember-explicit-takeover-request",()->server(p->{oldBehaviorRequest=UUID.randomUUID();dev.mineagent.runtime.neoforge.skill.BehaviorAuthority.get(p.level().getServer()).accepted(p,agent,oldBehaviorRequest,"接管我的身体，照顾农田");return null;}));
        action("restart-to-check-escape",()->tool("farm_area",area("player_esc","player",3,101,6,3,101,6).put("crop","minecraft:wheat")));
        waitFor("escape-session-active",150,()->CompletableFuture.completedFuture(AutonomousBodyClient.active()&&!mc().mouseHandler.isMouseGrabbed()));
        action("real-player-escape",()->{screen("real-player-farm");require(AutonomousBodyClient.active(),"PLAYER_ADAPTER_NOT_ACTIVE");PlayerBodyControlClient.physicalKey(mc().getWindow().handle(),1,new net.minecraft.client.input.KeyEvent(256,0,0));require(!AutonomousBodyClient.active(),"ESC_DID_NOT_RELEASE");return CompletableFuture.completedFuture(null);});
        waitFor("escape-cancels-skill",150,()->state("player_esc",s->s.path("state").asText().equals("CANCELLED")));
        action("escape-invalidates-old-model-takeover",()->server(p->{var authority=dev.mineagent.runtime.neoforge.skill.BehaviorAuthority.get(p.level().getServer());require(!authority.current(p,agent,oldBehaviorRequest)&&!authority.playerRequested(p,agent,oldBehaviorRequest),"ESC_ALLOWED_OLD_MODEL_TO_RETAKE_BODY");return null;}));
    }
    @SubscribeEvent public static void tick(ClientTickEvent.Post event){if(!Boolean.getBoolean("mineagent.skillSmoke")||done)return;try{
        if(mc().player==null||mc().getSingleplayerServer()==null)return;ticks++;if(!initialized){initialized=true;prepare();stageAt=ticks;}if(ticks%100==0)Files.writeString(root().resolve("progress.json"),JSON.writeValueAsString(Map.of("stage",STEPS.isEmpty()?"DONE":STEPS.getFirst().name,"ticks",ticks,"busy",busy,"observed",lastObservation==null?Map.of():lastObservation,"input",NativeSkillInput.observation())));
        if(STEPS.isEmpty()){Files.writeString(root().resolve("result.json"),JSON.writeValueAsString(Map.of("status","PASS","mode",System.getProperty("mineagent.skillSmokeMode","work"),"modelCalls",0,"evidence",EVIDENCE)));done=true;mc().stop();return;}
        if(ticks-stageAt>STEPS.getFirst().timeout)throw new IllegalStateException("SKILL_SMOKE_TIMEOUT_"+STEPS.getFirst().name);if(busy||ticks%5!=0)return;busy=true;var step=STEPS.getFirst();step.run.get().whenComplete((finished,error)->mc().execute(()->{busy=false;if(error!=null){fail(error);return;}if(finished){EVIDENCE.add(Map.of("completedStep",step.name,"atTick",ticks));STEPS.removeFirst();stageAt=ticks;}}));
    }catch(Exception e){fail(e);}}
    private static void fail(Throwable failure){if(done)return;done=true;try{screen("failure");Files.writeString(root().resolve("failure.json"),JSON.writeValueAsString(Map.of("error",failure.toString(),"stage",STEPS.isEmpty()?"DONE":STEPS.getFirst().name,"evidence",EVIDENCE,"lastObservation",lastObservation==null?Map.of():lastObservation,"input",NativeSkillInput.observation(),"autonomy",AutonomousBodyClient.observe())));}catch(Exception ignored){}AutonomousBodyClient.stop("SMOKE_FAILURE");mc().stop();}
    private PersistentSkillSmokeClient(){}
}
