package dev.mineagent.runtime.core.delivery;

import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.ObjectNode;
import dev.mineagent.runtime.core.persistence.RetainedRows;
import dev.mineagent.runtime.core.packages.ClientJavaPlan;
import dev.mineagent.runtime.core.packages.ClientScriptPlan;
import java.nio.charset.StandardCharsets;
import java.nio.channels.*;
import java.nio.file.*;
import java.sql.*;
import java.util.*;
import java.util.function.*;

/** Persistent offers and receipts, not proof of human reading or arbitrary application success. */
public final class ContentDeliveryStore implements AutoCloseable {
    public record Context(UUID world,UUID owner,UUID agent,UUID task,long intent,UUID operation){public Context{Objects.requireNonNull(world);Objects.requireNonNull(owner);Objects.requireNonNull(agent);Objects.requireNonNull(task);Objects.requireNonNull(operation);if(intent<1)throw new IllegalArgumentException("DELIVERY_CONTEXT");}}
    public record Asset(UUID packageId,long revision,String canonical,String entry,String mode,String title,String feedbackPolicySha256,dev.mineagent.runtime.core.feedback.FeedbackDataBinding feedbackData){public Asset(UUID id,long revision,String canonical,String entry,String mode,String title,String policy){this(id,revision,canonical,entry,mode,title,policy,null);}public Asset(UUID id,long revision,String canonical,String entry,String mode,String title){this(id,revision,canonical,entry,mode,title,"");}public Asset{if(feedbackData!=null&&(feedbackPolicySha256==null||feedbackPolicySha256.isEmpty()))throw new IllegalArgumentException("FEEDBACK_DATA_WITHOUT_GRANT");feedbackPolicySha256=feedbackPolicySha256==null?"":feedbackPolicySha256;if(!feedbackPolicySha256.isEmpty()&&(!feedbackPolicySha256.matches("[a-f0-9]{64}")||!mode.equals("CONTENT")))throw new IllegalArgumentException("DELIVERY_FEEDBACK_ASSET");Objects.requireNonNull(packageId);boolean html=Set.of("CONTENT","HUD").contains(mode)&&entry!=null&&entry.startsWith("ui/")&&entry.endsWith(".html"),rhino=mode!=null&&mode.equals("CLIENT_RHINO")&&ClientScriptPlan.path(entry),java=mode!=null&&mode.equals("CLIENT_JAVA")&&ClientJavaPlan.path(entry);if(revision<1||canonical==null||!canonical.matches("[a-f0-9]{64}")||entry==null||entry.length()>256||entry.contains("..")||entry.contains("\\")||!(html||rhino||java)||title==null||title.isBlank()||title.length()>128||mode.startsWith("CLIENT_")&&(!feedbackPolicySha256.isEmpty()||feedbackData!=null))throw new IllegalArgumentException("DELIVERY_ASSET");}}
    public record Recipient(UUID playerId,String eligibility){public Recipient{Objects.requireNonNull(playerId);if(!Set.of("ELIGIBLE","UNAVAILABLE","FILTER_CHANGED","GENERATION_CHANGED").contains(eligibility))throw new IllegalArgumentException("DELIVERY_RECIPIENT");}}
    public record Batch(UUID id,UUID audienceSnapshot,List<UUID> deliveries){public Batch{deliveries=List.copyOf(deliveries);}}
    public record DataReceipt(long revision,String sha256,String documentId,long paintSequence,String layoutHash,long receivedAndPaintedAt){
        public DataReceipt{if(revision<1||sha256==null||!sha256.matches("[a-f0-9]{64}")||documentId==null||documentId.isBlank()||documentId.length()>128||paintSequence<1||layoutHash==null||!layoutHash.matches("[a-f0-9]{64}")||receivedAndPaintedAt<1)throw new IllegalArgumentException("DELIVERY_DATA_RECEIPT");}
    }
    public record Delivery(UUID id,UUID batchId,UUID owner,UUID agent,Asset asset,UUID recipient,String status,long revision,long dataRevision,String data,long expiresAt,String issuedAuthority,UUID leaseId,String viewId,UUID sessionId,long attempt,long paintedAt,String documentId,String layoutHash,long paintSequence,boolean closeConfirmed,String error,Context origin,DataReceipt dataReceipt){}
    public record Lease(UUID deliveryId,UUID leaseId,String viewId,long attempt){}
    public record CodeAcceptance(UUID deliveryId,long attempt){}
    private record Operation(String fingerprint,String kind,String result){}
    public record ManagementContext(UUID world,UUID owner){public ManagementContext{Objects.requireNonNull(world);Objects.requireNonNull(owner);}}
    public record ManagementReceipt(UUID operation,UUID delivery,String action,String status,long revision,boolean archived){}
    public record ManagementResult(ManagementReceipt receipt,boolean duplicate,String currentStatus,long currentRevision,boolean closeConfirmed){}
    public record ManagementPage(long total,int offset,int nextOffset,boolean more,List<Delivery> rows){public ManagementPage{rows=List.copyOf(rows);}}
    private record ManagementOperation(UUID owner,String fingerprint,ManagementReceipt receipt){}
    public interface Port{void authorize(Context context);String authority(Delivery delivery);
        default void authorizeManagement(ManagementContext context){throw new SecurityException("DELIVERY_MANAGEMENT_UNAVAILABLE");}
        default boolean mayArchive(Delivery delivery){return false;}
        default boolean waitingForAuthority(Delivery delivery){return false;}
        default void changed(UUID id){}
    }
    private static final Set<String> OPEN=Set.of("OPENING","CLIENT_RECEIVED","RENDERED","INTERACTED");
    private static final Set<String> CODE=Set.of("CODE_DOWNLOADING","CODE_DOWNLOADED","CODE_RUNNING","CODE_STOPPED","CODE_SUSPENDED","CODE_FAILED");
    private static final Set<String> TERMINAL=Set.of("REJECTED","CLOSED","REVOKED","EXPIRED","FAILED","UNAVAILABLE");
    private static final String TERMINAL_SQL="'REJECTED','CLOSED','REVOKED','EXPIRED','FAILED','UNAVAILABLE'";
    private final Connection db;private final UUID world;private final LongSupplier now;private final Port port;private final FileChannel channel;private final FileLock lock;private final ObjectMapper json=new ObjectMapper();private boolean closed;
    private ContentDeliveryStore(Connection db,UUID world,LongSupplier now,Port port,FileChannel channel,FileLock lock)throws Exception{
        this.db=db;this.world=world;this.now=now;this.port=port;this.channel=channel;this.lock=lock;try(var s=db.createStatement()){s.execute("PRAGMA journal_mode=WAL");s.execute("PRAGMA busy_timeout=5000");s.execute("CREATE TABLE IF NOT EXISTS mineagent_deliveries_v1(world TEXT NOT NULL,id TEXT NOT NULL,batch TEXT NOT NULL,owner TEXT NOT NULL,recipient TEXT NOT NULL,status TEXT NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(world,id))");s.execute("CREATE INDEX IF NOT EXISTS mineagent_deliveries_recipient_v1 ON mineagent_deliveries_v1(world,recipient)");s.execute("CREATE TABLE IF NOT EXISTS mineagent_delivery_operations_v1(world TEXT NOT NULL,id TEXT NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(world,id))");}
        tx(()->{try(var statement=db.createStatement()){statement.execute("CREATE TABLE IF NOT EXISTS mineagent_delivery_management_v1(world TEXT NOT NULL,id TEXT NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(world,id))");}
            RetainedRows.initialize(db,world,List.of("mineagent_deliveries_v1","mineagent_delivery_operations_v1","mineagent_delivery_management_v1"));var columns=new HashSet<String>();try(var query=db.createStatement();var rows=query.executeQuery("PRAGMA table_info(mineagent_deliveries_v1)")){while(rows.next())columns.add(rows.getString("name"));}
            try(var statement=db.createStatement()){for(var column:List.of("agent","origin_task"))if(!columns.contains(column))statement.execute("ALTER TABLE mineagent_deliveries_v1 ADD COLUMN "+column+" TEXT NOT NULL DEFAULT ''");if(!columns.contains("origin_intent"))statement.execute("ALTER TABLE mineagent_deliveries_v1 ADD COLUMN origin_intent INTEGER NOT NULL DEFAULT 0");}
            var old=new ArrayList<Delivery>();try(var query=db.prepareStatement("SELECT payload FROM mineagent_deliveries_v1 WHERE world=? AND agent=''")){query.setString(1,world.toString());try(var rows=query.executeQuery()){while(rows.next())old.add(json.readValue(rows.getString(1),Delivery.class));}}
            try(var update=db.prepareStatement("UPDATE mineagent_deliveries_v1 SET agent=?,origin_task=?,origin_intent=? WHERE world=? AND id=?")){for(var d:old){update.setString(1,d.agent().toString());update.setString(2,d.origin()==null?"":d.origin().task().toString());update.setLong(3,d.origin()==null?0:d.origin().intent());update.setString(4,world.toString());update.setString(5,d.id().toString());update.executeUpdate();}}
            try(var statement=db.createStatement()){statement.execute("CREATE INDEX IF NOT EXISTS mineagent_delivery_owner_v1 ON mineagent_deliveries_v1(world,owner,agent,status)");statement.execute("CREATE INDEX IF NOT EXISTS mineagent_delivery_origin_v1 ON mineagent_deliveries_v1(world,owner,agent,origin_task,origin_intent)");statement.execute("CREATE INDEX IF NOT EXISTS mineagent_delivery_batch_v1 ON mineagent_deliveries_v1(world,batch)");}return null;
        });
        tx(()->{for(var d:hotRows())if(OPEN.contains(d.status())||d.status().equals("CLOSE_REQUESTED")||CODE.contains(d.status()))save(change(d,n->{n.put("status",d.status().equals("CLOSE_REQUESTED")?"CLOSED":d.status().startsWith("CODE_")?"CODE_SUSPENDED":"SUSPENDED");n.put("error","SERVER_RESTART_REQUIRES_NEW_ACCEPTANCE");}));return null;});
    }
    public static ContentDeliveryStore open(Path path,UUID world,LongSupplier now,Port port)throws Exception{
        Objects.requireNonNull(world);Objects.requireNonNull(now);Objects.requireNonNull(port);
        Path p=path.toAbsolutePath().normalize();Files.createDirectories(p.getParent());
        var channel=FileChannel.open(p.resolveSibling(p.getFileName()+".delivery-"+world+".lock"),StandardOpenOption.CREATE,StandardOpenOption.WRITE);
        FileLock lock=null;Connection db=null;
        try{
            try{lock=channel.tryLock();}catch(OverlappingFileLockException busy){throw new IllegalStateException("DELIVERY_STORE_ALREADY_OPEN",busy);}
            if(lock==null)throw new IllegalStateException("DELIVERY_STORE_ALREADY_OPEN");
            db=DriverManager.getConnection("jdbc:sqlite:"+p);return new ContentDeliveryStore(db,world,now,port,channel,lock);
        }catch(Exception e){
            if(db!=null)try{db.close();}catch(Exception x){e.addSuppressed(x);}
            if(lock!=null)try{lock.close();}catch(Exception x){e.addSuppressed(x);}
            try{channel.close();}catch(Exception x){e.addSuppressed(x);}throw e;
        }
    }
    private void authorize(Context c){if(closed||!world.equals(c.world()))throw new SecurityException("DELIVERY_WORLD");port.authorize(c);}
    private boolean authority(Delivery d){String token=port.authority(d);return token!=null&&token.equals(d.issuedAuthority());}
    private void current(Delivery d){if(closed||now.getAsLong()>=d.expiresAt()||!authority(d))throw new SecurityException("DELIVERY_AUTHORITY_REVOKED");}
    private Delivery owned(Context c,UUID id)throws Exception{authorize(c);var d=load(id);if(d==null||!d.owner().equals(c.owner())||!d.agent().equals(c.agent()))throw new SecurityException("DELIVERY_NOT_OWNED");return d;}
    private Delivery recipientRow(UUID recipient,UUID id)throws Exception{var d=load(id);if(closed||d==null||!d.recipient().equals(recipient))throw new SecurityException("DELIVERY_RECIPIENT_DENIED");return d;}
    public synchronized Batch offer(Context c,Asset asset,UUID audience,List<Recipient> recipients,String data,long ttl,String authority)throws Exception{
        authorize(c);Objects.requireNonNull(audience);data=normalize(data);if(recipients==null||recipients.isEmpty()||recipients.size()>64||recipients.stream().map(Recipient::playerId).distinct().count()!=recipients.size()||ttl<1000||ttl>604800000||authority==null||authority.isBlank())throw new IllegalArgumentException("DELIVERY_OFFER_ARGUMENTS");
        String payload=data;var people=List.copyOf(recipients);return tx(()->{authorize(c);String fp=hash(List.of(c.world(),c.owner(),c.agent(),c.task(),c.intent(),"OFFER",asset,audience,people,payload,ttl));var old=operation(c.operation(),fp);if(old!=null)return json.readValue(old.result(),Batch.class);budgetOperations();
            if(RetainedRows.usage(db,world,"mineagent_deliveries_v1").hot()+people.size()>4096)archiveCompleted(null,256);
            if(RetainedRows.usage(db,world,"mineagent_deliveries_v1").hot()+people.size()>4096||ownerLive(c.owner())+people.stream().filter(p->p.eligibility().equals("ELIGIBLE")).count()>128)throw new IllegalStateException("DELIVERY_OFFER_BUDGET");
            UUID batch=stable("batch",c.operation().toString());var ids=new ArrayList<UUID>();for(var p:people){UUID id=stable("recipient",batch+"|"+p.playerId());ids.add(id);var d=new Delivery(id,batch,c.owner(),c.agent(),asset,p.playerId(),p.eligibility().equals("ELIGIBLE")?"OFFERED":"UNAVAILABLE",1,1,payload,Math.addExact(now.getAsLong(),ttl),authority,null,"",null,0,0,"","",0,false,p.eligibility().equals("ELIGIBLE")?"":p.eligibility(),c,null);if(!authority(d))throw new SecurityException("DELIVERY_OFFER_AUTHORITY_CHANGED");save(d);}
            var result=new Batch(batch,audience,ids);writeOperation(c.operation(),fp,"OFFER",result);authorize(c);return result;
        });
    }
    public synchronized List<Delivery> query(Context c,UUID batch)throws Exception{authorize(c);return queryRows(" AND batch=? AND owner=? AND agent=?",List.of(batch.toString(),c.owner().toString(),c.agent().toString()),0,64,false);}
    public synchronized Delivery inspect(Context c,UUID id)throws Exception{return owned(c,id);}
    public synchronized List<Delivery> inbox(UUID recipient,int offset)throws Exception{if(offset<0||offset>RetainedRows.MAX_RETAINED_ROWS||closed)throw new IllegalArgumentException("DELIVERY_PAGE");return queryRows(" AND recipient=?",List.of(recipient.toString()),offset,16,true);}
    public synchronized long inboxCount(UUID recipient)throws Exception{return countRows(" AND recipient=?",List.of(recipient.toString()));}
    public synchronized Delivery recipient(UUID recipient,UUID id)throws Exception{return recipientRow(recipient,id);}
    public synchronized Lease accept(UUID recipient,UUID id,UUID operation)throws Exception{
        return tx(()->{var d=recipientRow(recipient,id);current(d);String fp=hash(List.of("ACCEPT",recipient,id));var previous=operation(operation,fp);if(previous!=null){var result=json.readValue(previous.result(),Lease.class);if(!OPEN.contains(d.status())||!result.leaseId().equals(d.leaseId()))throw new IllegalStateException("DELIVERY_OLD_ACCEPTANCE");return result;}
            if(!Set.of("OFFERED","SUSPENDED").contains(d.status()))throw new IllegalStateException("DELIVERY_ACCEPT_STATE");budgetOperations();UUID lease=UUID.randomUUID();String view="delivery-"+lease;var next=change(d,n->{n.put("status","OPENING");n.put("leaseId",lease.toString());n.put("viewId",view);n.putNull("sessionId");n.put("attempt",d.attempt()+1);n.put("paintedAt",0);n.put("documentId","");n.put("layoutHash","");n.put("paintSequence",0);n.putNull("dataReceipt");n.put("closeConfirmed",false);n.put("error","");});save(next);var result=new Lease(id,lease,view,next.attempt());writeOperation(operation,fp,"ACCEPT",result);current(next);return result;
        });
    }
    public synchronized CodeAcceptance acceptCode(UUID recipient,UUID id,UUID operation)throws Exception{return tx(()->{var d=recipientRow(recipient,id);current(d);if(!d.asset().mode().startsWith("CLIENT_"))throw new IllegalStateException("DELIVERY_CODE_MODE");String fp=hash(List.of("CODE_ACCEPT",recipient,id));var previous=operation(operation,fp);if(previous!=null){var result=json.readValue(previous.result(),CodeAcceptance.class);if(!d.status().equals("CODE_DOWNLOADING")||d.attempt()!=result.attempt())throw new IllegalStateException("DELIVERY_OLD_ACCEPTANCE");return result;}if(!Set.of("OFFERED","CODE_SUSPENDED","CODE_FAILED").contains(d.status()))throw new IllegalStateException("DELIVERY_CODE_ACCEPT_STATE");budgetOperations();var next=change(d,n->{n.put("status","CODE_DOWNLOADING");n.put("attempt",d.attempt()+1);n.put("error","");});save(next);var result=new CodeAcceptance(id,next.attempt());writeOperation(operation,fp,"CODE_ACCEPT",result);current(next);return result;});}
    public synchronized Delivery codeState(UUID recipient,UUID id,UUID operation,String localState,String error)throws Exception{return tx(()->{var d=recipientRow(recipient,id);if(!d.asset().mode().startsWith("CLIENT_"))throw new IllegalStateException("DELIVERY_CODE_MODE");if(!Set.of("DOWNLOADED","RUNNING","STOPPED","FAILED").contains(localState))throw new IllegalArgumentException("DELIVERY_CODE_STATE");String fp=hash(List.of("CODE_STATE",recipient,id,localState,Objects.toString(error,"")));var previous=operation(operation,fp);if(previous!=null)return d;if(TERMINAL.contains(d.status())){budgetOperations();writeOperation(operation,fp,"CODE_STATE_TERMINAL",id);return d;}String next="CODE_"+localState;if(!switch(d.status()){case "CODE_DOWNLOADING"->Set.of("CODE_DOWNLOADED","CODE_FAILED").contains(next);case "CODE_DOWNLOADED"->Set.of("CODE_DOWNLOADED","CODE_RUNNING","CODE_STOPPED","CODE_FAILED").contains(next);case "CODE_RUNNING"->Set.of("CODE_RUNNING","CODE_STOPPED","CODE_FAILED").contains(next);case "CODE_STOPPED"->Set.of("CODE_STOPPED","CODE_RUNNING","CODE_FAILED").contains(next);case "CODE_SUSPENDED"->Set.of("CODE_STOPPED","CODE_FAILED").contains(next);case "CODE_FAILED"->next.equals("CODE_FAILED");default->false;})throw new IllegalStateException("DELIVERY_CODE_STATE_ORDER");budgetOperations();var changed=change(d,n->{n.put("status",next);n.put("error",next.equals("CODE_FAILED")&&error!=null&&error.matches("[A-Z0-9_]{1,80}")?error:"");});save(changed);writeOperation(operation,fp,"CODE_STATE",id);return changed;});}
    public synchronized void reject(UUID recipient,UUID id,UUID operation)throws Exception{tx(()->{var d=recipientRow(recipient,id);String fp=hash(List.of("REJECT",recipient,id));if(operation(operation,fp)!=null)return null;if(!Set.of("OFFERED","SUSPENDED","CODE_SUSPENDED","CODE_FAILED").contains(d.status()))throw new IllegalStateException("DELIVERY_REJECT_STATE");budgetOperations();save(change(d,n->n.put("status","REJECTED")));writeOperation(operation,fp,"REJECT",id);return null;});}
    public synchronized void attach(UUID recipient,UUID id,UUID lease,UUID session)throws Exception{Objects.requireNonNull(session);tx(()->{var d=lease(recipient,id,lease,null);if(!d.status().equals("OPENING")||d.sessionId()!=null&&!d.sessionId().equals(session))throw new IllegalStateException("DELIVERY_SESSION_BINDING");save(change(d,n->n.put("sessionId",session.toString())));return null;});}
    public synchronized void received(UUID recipient,UUID id,UUID lease,UUID session)throws Exception{Objects.requireNonNull(session);tx(()->{var d=lease(recipient,id,lease,session);if(Set.of("CLIENT_RECEIVED","RENDERED","INTERACTED").contains(d.status()))return null;if(!d.status().equals("OPENING"))throw new IllegalStateException("DELIVERY_RECEIPT_ORDER");save(change(d,n->n.put("status","CLIENT_RECEIVED")));return null;});}
    public synchronized void painted(UUID recipient,UUID id,UUID lease,UUID session,String document,long sequence,String layoutHash)throws Exception{
        painted(recipient,id,lease,session,document,sequence,layoutHash,0,"");
    }
    public synchronized void painted(UUID recipient,UUID id,UUID lease,UUID session,String document,long sequence,String layoutHash,long dataRevision,String dataHash)throws Exception{
        Objects.requireNonNull(session);if(document==null||document.isBlank()||document.length()>128||sequence<1||layoutHash==null||!layoutHash.matches("[a-f0-9]{64}"))throw new IllegalArgumentException("DELIVERY_PAINT_PROOF");
        if(dataRevision<0||dataHash==null||dataRevision==0&&!dataHash.isEmpty()||dataRevision>0&&!dataHash.matches("[a-f0-9]{64}"))throw new IllegalArgumentException("DELIVERY_DATA_PAINT_PROOF");
        tx(()->{var d=lease(recipient,id,lease,session);if(!Set.of("CLIENT_RECEIVED","RENDERED","INTERACTED").contains(d.status()))throw new IllegalStateException("DELIVERY_PAINT_ORDER");
            if(dataRevision>0&&(dataRevision!=d.dataRevision()||!dataHash.equals(dataSha256(d.data()))))throw new IllegalStateException("DELIVERY_DATA_CHANGED");
            if(sequence<d.paintSequence())throw new IllegalStateException("DELIVERY_OLD_PAINT");if(sequence==d.paintSequence()){if(!document.equals(d.documentId())||!layoutHash.equals(d.layoutHash())||dataRevision>0&&(d.dataReceipt()==null||d.dataReceipt().revision()!=dataRevision||!d.dataReceipt().sha256().equals(dataHash)))throw new IllegalStateException("DELIVERY_PAINT_REUSED");return null;}
            save(change(d,n->{if(!d.status().equals("INTERACTED")||!d.documentId().equals(document))n.put("status","RENDERED");n.put("paintedAt",now.getAsLong());n.put("documentId",document);n.put("paintSequence",sequence);n.put("layoutHash",layoutHash);
                if(dataRevision>0)n.set("dataReceipt",json.valueToTree(new DataReceipt(dataRevision,dataHash,document,sequence,layoutHash,now.getAsLong())));else if(!d.documentId().equals(document))n.putNull("dataReceipt");
            }));return null;
        });
    }
    private Delivery lease(UUID recipient,UUID id,UUID lease,UUID session)throws Exception{Objects.requireNonNull(lease);var d=recipientRow(recipient,id);current(d);if(!OPEN.contains(d.status())||!Objects.equals(d.leaseId(),lease)||session!=null&&!session.equals(d.sessionId()))throw new SecurityException("DELIVERY_LEASE_REVOKED");return d;}
    public synchronized void navigated(UUID recipient,UUID id,UUID lease,UUID session)throws Exception{Objects.requireNonNull(session);tx(()->{var d=lease(recipient,id,lease,session);save(change(d,n->{n.put("status","CLIENT_RECEIVED");n.put("paintedAt",0);n.put("documentId","");n.put("layoutHash","");n.putNull("dataReceipt");}));return null;});}
    public synchronized boolean permits(UUID recipient,UUID id,UUID lease,UUID session){try{lease(recipient,id,lease,session);return true;}catch(Exception e){return false;}}
    public synchronized void interacted(UUID recipient,UUID id,UUID lease,UUID session,String document)throws Exception{
        tx(()->{var d=lease(recipient,id,lease,session);if(!Set.of("RENDERED","INTERACTED").contains(d.status())||!d.documentId().equals(document)||d.paintedAt()<1)throw new SecurityException("DELIVERY_INTERACTION_DOCUMENT");if(!d.status().equals("INTERACTED"))save(change(d,n->n.put("status","INTERACTED")));return null;});
    }
    public synchronized Delivery update(Context c,UUID id,long expectedDataRevision,String data)throws Exception{
        String value=normalize(data);return tx(()->{var d=owned(c,id);if(d.asset().mode().startsWith("CLIENT_"))throw new IllegalStateException("DELIVERY_CODE_DATA_UNSUPPORTED");current(d);String fp=hash(List.of(c.owner(),c.agent(),"UPDATE",id,expectedDataRevision,value));var old=operation(c.operation(),fp);if(old!=null)return load(id);if(d.dataRevision()!=expectedDataRevision||Set.of("REVOKED","EXPIRED","REJECTED","FAILED","UNAVAILABLE").contains(d.status()))throw new IllegalStateException("DELIVERY_DATA_CONFLICT");budgetOperations();var next=change(d,n->{n.put("data",value);n.put("dataRevision",d.dataRevision()+1);});save(next);writeOperation(c.operation(),fp,"UPDATE",id);authorize(c);current(next);return next;});
    }
    public synchronized Delivery revoke(Context c,UUID id)throws Exception{return stop(c,id,true);}
    public synchronized Delivery requestClose(Context c,UUID id)throws Exception{return stop(c,id,false);}
    private Delivery stop(Context c,UUID id,boolean revoke)throws Exception{return tx(()->{
        var d=owned(c,id);String fp=hash(List.of(c.owner(),c.agent(),revoke?"REVOKE":"CLOSE",id));
        if(operation(c.operation(),fp)!=null)return d;budgetOperations();
        // A later close is not a new outcome. Explicit revoke may strengthen CLOSED,
        // but neither command can erase a rejection, failure, expiry or revocation.
        var next=stopValue(d,revoke);
        writeOperation(c.operation(),fp,"STOP",id);authorize(c);return next;
    });}
    private Delivery stopValue(Delivery d,boolean revoke)throws Exception{
        boolean preserve=TERMINAL.contains(d.status())&&!(revoke&&d.status().equals("CLOSED"));if(preserve)return d;String status=revoke?"REVOKED":d.leaseId()==null?"CLOSED":"CLOSE_REQUESTED";
        var next=change(d,n->{n.put("status",status);n.put("error",revoke?"SENDER_REVOKED":"SENDER_CLOSE_REQUESTED");});save(next);return next;
    }
    public synchronized void closed(UUID recipient,UUID id,UUID lease,UUID session)throws Exception{Objects.requireNonNull(lease);Objects.requireNonNull(session);tx(()->{var d=recipientRow(recipient,id);if(!Objects.equals(lease,d.leaseId())||!Objects.equals(session,d.sessionId()))throw new SecurityException("DELIVERY_CLOSE_IDENTITY");if(d.closeConfirmed())return null;save(change(d,n->{if(!TERMINAL.contains(d.status()))n.put("status","CLOSED");n.put("closeConfirmed",true);}));return null;});}
    public synchronized void fail(UUID recipient,UUID id,UUID lease,String error)throws Exception{tx(()->{var d=recipientRow(recipient,id);if(!Objects.equals(d.leaseId(),lease)||!OPEN.contains(d.status()))return null;save(change(d,n->{n.put("status","FAILED");n.put("error",error!=null&&error.matches("[A-Z0-9_]{1,80}")?error:"DELIVERY_OPEN_FAILED");}));return null;});}
    public synchronized void disconnect(UUID recipient)throws Exception{tx(()->{for(var d:queryRows(" AND archived=0 AND recipient=?",List.of(recipient.toString()),0,4096,false)){if(OPEN.contains(d.status()))save(change(d,n->{n.put("status","SUSPENDED");n.put("error","CONNECTION_LOST_NEW_ACCEPTANCE_REQUIRED");}));else if(CODE.contains(d.status()))save(change(d,n->{n.put("status","CODE_SUSPENDED");n.put("error","CONNECTION_LOST_NEW_ACCEPTANCE_REQUIRED");}));}return null;});}
    public synchronized void reconcile()throws Exception{tx(()->{for(var d:hotRows())if(!TERMINAL.contains(d.status())){if(now.getAsLong()>=d.expiresAt())save(change(d,n->n.put("status","EXPIRED")));else if(!authority(d)){if(port.waitingForAuthority(d)){if(!d.error().equals("SENDER_RESOURCE_WAITING"))save(change(d,n->n.put("error","SENDER_RESOURCE_WAITING")));}else save(change(d,n->{n.put("status","REVOKED");n.put("error","SENDER_AUTHORITY_CHANGED");}));}else if(d.error().equals("SENDER_RESOURCE_WAITING"))save(change(d,n->n.put("error","")));}return null;});}
    public synchronized List<Delivery> runtimeRows()throws Exception{return List.copyOf(all());}
    public synchronized List<Delivery> runtimeHotRows()throws Exception{return List.copyOf(hotRows());}
    public synchronized Optional<Delivery> runtimeRow(UUID id)throws Exception{return Optional.ofNullable(load(id));}
    public synchronized List<Delivery> coverageRows(Context c,Set<UUID> ids)throws Exception{
        if(closed||!world.equals(c.world()))throw new SecurityException("DELIVERY_WORLD");if(ids.size()>256)throw new IllegalArgumentException("DELIVERY_GOAL_BUDGET");String selected=json.writeValueAsString(ids.stream().map(UUID::toString).sorted().toList());var result=queryRows(" AND owner=? AND agent=? AND ((origin_task=? AND origin_intent=?) OR id IN (SELECT value FROM json_each(?)))",List.of(c.owner().toString(),c.agent().toString(),c.task().toString(),Long.toString(c.intent()),selected),0,(int)RetainedRows.MAX_RETAINED_ROWS,false);if(!result.isEmpty()||!ids.isEmpty())authorize(c);return result;
    }
    public synchronized List<Delivery> originHistory(UUID owner,UUID agent,UUID task,int offset,int limit)throws Exception{return queryRows(" AND owner=? AND agent=? AND origin_task=?",List.of(owner.toString(),agent.toString(),task.toString()),offset,limit,false);}
    public synchronized long originCount(UUID owner,UUID agent,UUID task)throws Exception{return countRows(" AND owner=? AND agent=? AND origin_task=?",List.of(owner.toString(),agent.toString(),task.toString()));}
    private void management(ManagementContext c){if(closed||!world.equals(c.world()))throw new SecurityException("DELIVERY_MANAGEMENT_WORLD");port.authorizeManagement(c);}
    public synchronized Delivery managementInspect(ManagementContext c,UUID id)throws Exception{management(c);var d=load(id);if(d==null||!d.owner().equals(c.owner()))throw new SecurityException("DELIVERY_MANAGEMENT_OWNER");return d;}
    public synchronized boolean archived(UUID id)throws Exception{return RetainedRows.archived(db,world,"mineagent_deliveries_v1",id.toString());}
    public synchronized boolean mayArchive(Delivery d){return TERMINAL.contains(d.status())&&(d.sessionId()==null||d.closeConfirmed()||port.mayArchive(d));}
    public synchronized ManagementPage managementList(ManagementContext c,String status,String archive,int offset,int limit)throws Exception{
        management(c);var states=new HashSet<>(Set.of("ALL","OFFERED","OPENING","CLIENT_RECEIVED","RENDERED","INTERACTED","SUSPENDED","CLOSE_REQUESTED","REJECTED","CLOSED","REVOKED","EXPIRED","FAILED","UNAVAILABLE"));states.addAll(CODE);if(!states.contains(status)||!Set.of("ALL","HOT","ARCHIVED").contains(archive)||limit>16)throw new IllegalArgumentException("DELIVERY_MANAGEMENT_PAGE");
        String filter=" AND owner=?"+(status.equals("ALL")?"":" AND status='"+status+"'")+(archive.equals("ALL")?"":" AND archived="+(archive.equals("HOT")?0:1));var values=queryRows(filter,List.of(c.owner().toString()),offset,limit,true);long total=countRows(filter,List.of(c.owner().toString()));management(c);return new ManagementPage(total,offset,offset+values.size(),total>offset+values.size(),values);
    }
    public synchronized Map<String,Long> managementUsage(ManagementContext c)throws Exception{management(c);try(var query=db.prepareStatement("SELECT COUNT(*),COALESCE(SUM(archived),0) FROM mineagent_deliveries_v1 WHERE world=? AND owner=?")){query.setString(1,world.toString());query.setString(2,c.owner().toString());try(var rows=query.executeQuery()){long total=rows.next()?rows.getLong(1):0,archived=rows.getLong(2);return Map.of("hot",total-archived,"archived",archived,"total",total,"maximumHot",4096L,"maximumRetained",RetainedRows.MAX_RETAINED_ROWS);}}}
    public synchronized ManagementResult managementWrite(ManagementContext c,UUID operation,UUID id,long revision,String action,boolean confirmed)throws Exception{
        management(c);if(operation==null||revision<1||!confirmed||!Set.of("CLOSE","REVOKE","ARCHIVE").contains(action))throw new IllegalArgumentException("DELIVERY_MANAGEMENT_CONFIRM");return tx(()->{var d=managementInspect(c,id);String fp=hash(List.of(world,c.owner(),id,revision,action));var prior=managementOperation(operation);
            if(prior!=null){if(!prior.owner().equals(c.owner())||!prior.fingerprint().equals(fp))throw new IllegalArgumentException("DELIVERY_OPERATION_REUSED");return new ManagementResult(prior.receipt(),true,d.status(),d.revision(),d.closeConfirmed());}
            try(var query=db.prepareStatement("SELECT 1 FROM mineagent_delivery_operations_v1 WHERE world=? AND id=?")){query.setString(1,world.toString());query.setString(2,operation.toString());try(var rows=query.executeQuery()){if(rows.next())throw new IllegalArgumentException("DELIVERY_OPERATION_REUSED");}}
            if(d.revision()!=revision)throw new IllegalStateException("DELIVERY_MANAGEMENT_STALE");budgetLedger("mineagent_delivery_management_v1");
            if(action.equals("ARCHIVE")){if(!mayArchive(d))throw new IllegalStateException("DELIVERY_ARCHIVE_NOT_SETTLED");try(var query=db.prepareStatement("UPDATE mineagent_deliveries_v1 SET archived=1 WHERE world=? AND id=?")){query.setString(1,world.toString());query.setString(2,id.toString());query.executeUpdate();}}
            else d=stopValue(d,action.equals("REVOKE"));var receipt=new ManagementReceipt(operation,id,action,d.status(),d.revision(),archived(id));String payload=json.writeValueAsString(new ManagementOperation(c.owner(),fp,receipt));RetainedRows.requirePayloadCapacity(db,world,"mineagent_delivery_management_v1",operation,payload,256L*1024*1024,false);
            try(var query=db.prepareStatement("INSERT INTO mineagent_delivery_management_v1(world,id,payload) VALUES(?,?,?)")){query.setString(1,world.toString());query.setString(2,operation.toString());query.setString(3,payload);query.executeUpdate();}management(c);return new ManagementResult(receipt,false,d.status(),d.revision(),d.closeConfirmed());
        });
    }
    private ManagementOperation managementOperation(UUID id)throws Exception{try(var query=db.prepareStatement("SELECT payload FROM mineagent_delivery_management_v1 WHERE world=? AND id=?")){query.setString(1,world.toString());query.setString(2,id.toString());try(var rows=query.executeQuery()){return rows.next()?json.readValue(rows.getString(1),ManagementOperation.class):null;}}}
    private List<Delivery> queryRows(String filter,List<String> args,int offset,int limit,boolean newest)throws Exception{
        if(offset<0||offset>RetainedRows.MAX_RETAINED_ROWS||limit<1||limit>RetainedRows.MAX_RETAINED_ROWS)throw new IllegalArgumentException("DELIVERY_PAGE");var values=new ArrayList<Delivery>();try(var query=db.prepareStatement("SELECT payload FROM mineagent_deliveries_v1 WHERE world=?"+filter+" ORDER BY rowid "+(newest?"DESC":"ASC")+" LIMIT ? OFFSET ?")){int i=1;query.setString(i++,world.toString());for(var arg:args)query.setString(i++,arg);query.setInt(i++,limit);query.setInt(i,offset);try(var rows=query.executeQuery()){while(rows.next())values.add(json.readValue(rows.getString(1),Delivery.class));}}return List.copyOf(values);
    }
    private long countRows(String filter,List<String> args)throws Exception{try(var query=db.prepareStatement("SELECT COUNT(*) FROM mineagent_deliveries_v1 WHERE world=?"+filter)){int i=1;query.setString(i++,world.toString());for(var arg:args)query.setString(i++,arg);try(var rows=query.executeQuery()){return rows.next()?rows.getLong(1):0;}}}
    private long ownerLive(UUID owner)throws Exception{return countRows(" AND owner=? AND archived=0 AND status NOT IN ("+TERMINAL_SQL+")",List.of(owner.toString()));}
    private List<Delivery> hotRows()throws Exception{return queryRows(" AND archived=0",List.of(),0,(int)RetainedRows.MAX_RETAINED_ROWS,false);}
    private int archiveCompleted(UUID owner,int maximum)throws Exception{
        var ids=new ArrayList<Long>();try(var query=db.prepareStatement("SELECT rowid,payload FROM mineagent_deliveries_v1 WHERE world=? AND archived=0 AND status IN ("+TERMINAL_SQL+")"+(owner==null?"":" AND owner=?")+" ORDER BY rowid LIMIT 4096")){query.setString(1,world.toString());if(owner!=null)query.setString(2,owner.toString());try(var rows=query.executeQuery()){while(rows.next()){if(mayArchive(json.readValue(rows.getString(2),Delivery.class)))ids.add(rows.getLong(1));if(ids.size()>=maximum)break;}}}return RetainedRows.archive(db,world,"mineagent_deliveries_v1",ids);
    }
    private Delivery change(Delivery d,Consumer<ObjectNode> edit)throws Exception{var n=(ObjectNode)json.valueToTree(d);edit.accept(n);n.put("revision",d.revision()+1);return json.treeToValue(n,Delivery.class);}
    private String normalize(String data){String result=dev.mineagent.runtime.core.ui.WorldUiData.normalize(data);if(result.getBytes(StandardCharsets.UTF_8).length>8192)throw new IllegalArgumentException("DELIVERY_DATA_BUDGET");return result;}
    public static String dataSha256(String data){try{return dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer.sha256(dev.mineagent.runtime.core.ui.WorldUiData.normalize(data).getBytes(StandardCharsets.UTF_8));}catch(Exception invalid){throw new IllegalArgumentException("DELIVERY_DATA_HASH",invalid);}}
    private String hash(Object value)throws Exception{return dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer.sha256(json.writeValueAsBytes(value));}
    private UUID stable(String type,String key){return UUID.nameUUIDFromBytes((world+"|delivery|"+type+"|"+key).getBytes(StandardCharsets.UTF_8));}
    private Delivery load(UUID id)throws Exception{try(var q=db.prepareStatement("SELECT payload FROM mineagent_deliveries_v1 WHERE world=? AND id=?")){q.setString(1,world.toString());q.setString(2,id.toString());try(var r=q.executeQuery()){return r.next()?json.readValue(r.getString(1),Delivery.class):null;}}}
    private List<Delivery> all()throws Exception{var rows=new ArrayList<Delivery>();try(var q=db.prepareStatement("SELECT payload FROM mineagent_deliveries_v1 WHERE world=? ORDER BY rowid")){q.setString(1,world.toString());try(var r=q.executeQuery()){while(r.next())rows.add(json.readValue(r.getString(1),Delivery.class));}}return rows;}
    private void save(Delivery d)throws Exception{
        var old=load(d.id());if(old==null)RetainedRows.requireCapacity(db,world,"mineagent_deliveries_v1");String payload=json.writeValueAsString(d);boolean settling=old!=null&&old.data().equals(d.data())&&(TERMINAL.contains(d.status())||Set.of("CLOSE_REQUESTED","SUSPENDED","CODE_DOWNLOADED","CODE_RUNNING","CODE_STOPPED","CODE_SUSPENDED","CODE_FAILED").contains(d.status())||d.error().equals("SENDER_RESOURCE_WAITING"));RetainedRows.requirePayloadCapacity(db,world,"mineagent_deliveries_v1",d.id(),payload,256L*1024*1024,settling);
        try(var q=db.prepareStatement("INSERT INTO mineagent_deliveries_v1(world,id,batch,owner,recipient,status,payload,agent,origin_task,origin_intent) VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(world,id) DO UPDATE SET status=excluded.status,payload=excluded.payload,agent=excluded.agent,origin_task=excluded.origin_task,origin_intent=excluded.origin_intent")){q.setString(1,world.toString());q.setString(2,d.id().toString());q.setString(3,d.batchId().toString());q.setString(4,d.owner().toString());q.setString(5,d.recipient().toString());q.setString(6,d.status());q.setString(7,payload);q.setString(8,d.agent().toString());q.setString(9,d.origin()==null?"":d.origin().task().toString());q.setLong(10,d.origin()==null?0:d.origin().intent());q.executeUpdate();}port.changed(d.id());
    }
    private Operation operation(UUID id,String fingerprint)throws Exception{if(managementOperation(id)!=null)throw new IllegalArgumentException("DELIVERY_OPERATION_REUSED");try(var q=db.prepareStatement("SELECT payload FROM mineagent_delivery_operations_v1 WHERE world=? AND id=?")){q.setString(1,world.toString());q.setString(2,id.toString());try(var r=q.executeQuery()){if(!r.next())return null;var op=json.readValue(r.getString(1),Operation.class);if(!op.fingerprint().equals(fingerprint))throw new IllegalArgumentException("DELIVERY_OPERATION_REUSED");return op;}}}
    private void writeOperation(UUID id,String fp,String kind,Object result)throws Exception{String payload=json.writeValueAsString(new Operation(fp,kind,json.writeValueAsString(result)));RetainedRows.requirePayloadCapacity(db,world,"mineagent_delivery_operations_v1",id,payload,256L*1024*1024,false);try(var q=db.prepareStatement("INSERT INTO mineagent_delivery_operations_v1(world,id,payload) VALUES(?,?,?)")){q.setString(1,world.toString());q.setString(2,id.toString());q.setString(3,payload);q.executeUpdate();}}
    private void budgetOperations()throws Exception{budgetLedger("mineagent_delivery_operations_v1");}
    private void budgetLedger(String table)throws Exception{RetainedRows.requireCapacity(db,world,table);if(RetainedRows.usage(db,world,table).hot()>=8192){var ids=new ArrayList<Long>();try(var query=db.prepareStatement("SELECT rowid FROM "+table+" WHERE world=? AND archived=0 ORDER BY rowid LIMIT 256")){query.setString(1,world.toString());try(var rows=query.executeQuery()){while(rows.next())ids.add(rows.getLong(1));}}RetainedRows.archive(db,world,table,ids);}if(RetainedRows.usage(db,world,table).hot()>=8192)throw new IllegalStateException("DELIVERY_OPERATION_BUDGET");}
    @FunctionalInterface private interface Work<T>{T run()throws Exception;}
    private <T>T tx(Work<T> work)throws Exception{try(var s=db.createStatement()){s.execute("BEGIN IMMEDIATE");try{T result=work.run();s.execute("COMMIT");return result;}catch(Exception|Error e){try{s.execute("ROLLBACK");}catch(Exception x){e.addSuppressed(x);}throw e;}}}
    @Override public synchronized void close()throws Exception{if(closed)return;closed=true;try{db.close();}finally{try{lock.close();}finally{channel.close();}}}
}
