package dev.mineagent.runtime.core.delivery;

import com.fasterxml.jackson.core.*;
import com.fasterxml.jackson.databind.*;
import java.util.*;

public record DeliveryToolRequest(String tool,UUID packageId,long packageRevision,String canonical,String entryId,String mode,UUID audienceSnapshot,UUID id,long expectedDataRevision,String data,long ttlMillis,int offset,boolean feedbackEnabled,dev.mineagent.runtime.core.feedback.FeedbackDataBinding feedbackData,String canonicalRequest){
    public static final Set<String> TOOLS=Set.of("inspect_content_contract","offer_content","query_deliveries","update_view","close_view","revoke_content");
    private static final ObjectMapper JSON=new ObjectMapper(JsonFactory.builder().enable(StreamReadFeature.STRICT_DUPLICATE_DETECTION).build()).enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS);
    public static DeliveryToolRequest parse(String tool,String source){return parse(tool,source,false);}
    /** Validation-only offer template: no snapshot identity is invented or executed. */
    public static DeliveryToolRequest offerTemplate(String source){return parse("offer_content",source,true);}
    private static DeliveryToolRequest parse(String tool,String source,boolean template){try{
        if(!TOOLS.contains(tool)||source==null||source.length()>16384)throw new IllegalArgumentException();var n=JSON.readTree(source);if(!n.isObject())throw new IllegalArgumentException();var keys=new HashSet<String>();n.fieldNames().forEachRemaining(keys::add);var out=new LinkedHashMap<String,Object>();
        UUID pkg=null,audience=null,id=null;long revision=0,expected=0,ttl=60000;String canonical="",entry="",mode="CONTENT",data="{}";int offset=0;boolean feedbackEnabled=false;dev.mineagent.runtime.core.feedback.FeedbackDataBinding feedbackData=null;
        if(tool.equals("offer_content")){if(!Set.of("package_id","package_revision","canonical_sha256","entry_id","mode","audience_snapshot_id","data","ttl_seconds","feedback_enabled","feedback_binding").containsAll(keys)||!keys.containsAll(Set.of("package_id","package_revision","canonical_sha256","entry_id","data"))||(!template&&!keys.contains("audience_snapshot_id"))||(template&&keys.contains("audience_snapshot_id")))throw new IllegalArgumentException();pkg=UUID.fromString(text(n,"package_id"));revision=number(n,"package_revision");canonical=text(n,"canonical_sha256");entry=text(n,"entry_id");mode=n.has("mode")?text(n,"mode"):"CONTENT";audience=template?null:UUID.fromString(text(n,"audience_snapshot_id"));ttl=n.has("ttl_seconds")?Math.multiplyExact(number(n,"ttl_seconds"),1000):60000;if(revision<1||!canonical.matches("[a-f0-9]{64}")||!entry.matches("[A-Za-z0-9_.-]{1,64}")||!Set.of("CONTENT","HUD","CLIENT_RHINO","CLIENT_JAVA").contains(mode)||ttl<1000||ttl>604800000)throw new IllegalArgumentException();data=dev.mineagent.runtime.core.ui.WorldUiData.normalize(n.get("data").toString());out.put("package_id",pkg);out.put("package_revision",revision);out.put("canonical_sha256",canonical);out.put("entry_id",entry);out.put("mode",mode);if(audience!=null)out.put("audience_snapshot_id",audience);out.put("data",JSON.readTree(data));out.put("ttl_seconds",ttl/1000);if(n.has("feedback_enabled")){if(!n.get("feedback_enabled").isBoolean())throw new IllegalArgumentException();feedbackEnabled=n.get("feedback_enabled").booleanValue();}if(mode.startsWith("CLIENT_")&&feedbackEnabled)throw new IllegalArgumentException();out.put("feedback_enabled",feedbackEnabled);if(n.has("feedback_binding")){if(!feedbackEnabled||mode.startsWith("CLIENT_"))throw new IllegalArgumentException();feedbackData=dev.mineagent.runtime.core.feedback.FeedbackDataBinding.parse(n.get("feedback_binding"));out.put("feedback_binding",feedbackData.wire());}}
        else if(tool.equals("inspect_content_contract")){if(!Set.of("package_id","package_revision","canonical_sha256","entry_id","offset").containsAll(keys)||!keys.containsAll(Set.of("package_id","package_revision","canonical_sha256")))throw new IllegalArgumentException();pkg=UUID.fromString(text(n,"package_id"));revision=number(n,"package_revision");canonical=text(n,"canonical_sha256");entry=n.has("entry_id")?text(n,"entry_id"):"";offset=n.has("offset")?Math.toIntExact(number(n,"offset")):0;if(revision<1||!canonical.matches("[a-f0-9]{64}")||!entry.isEmpty()&&!entry.matches("[A-Za-z0-9_.-]{1,64}")||offset<0||offset>256)throw new IllegalArgumentException();out.put("package_id",pkg);out.put("package_revision",revision);out.put("canonical_sha256",canonical);out.put("offset",offset);if(!entry.isEmpty())out.put("entry_id",entry);}
        else if(tool.equals("query_deliveries")){if(!Set.of("batch_id","offset").containsAll(keys)||!keys.contains("batch_id"))throw new IllegalArgumentException();id=UUID.fromString(text(n,"batch_id"));offset=n.has("offset")?Math.toIntExact(number(n,"offset")):0;if(offset<0||offset>64)throw new IllegalArgumentException();out.put("batch_id",id);out.put("offset",offset);}
        else{var allowed=tool.equals("update_view")?Set.of("delivery_id","expected_data_revision","data"):Set.of("delivery_id");if(!keys.equals(allowed))throw new IllegalArgumentException();id=UUID.fromString(text(n,"delivery_id"));out.put("delivery_id",id);if(tool.equals("update_view")){expected=number(n,"expected_data_revision");if(expected<1)throw new IllegalArgumentException();data=dev.mineagent.runtime.core.ui.WorldUiData.normalize(n.get("data").toString());out.put("expected_data_revision",expected);out.put("data",JSON.readTree(data));}}
        return new DeliveryToolRequest(tool,pkg,revision,canonical,entry,mode,audience,id,expected,data,ttl,offset,feedbackEnabled,feedbackData,JSON.writeValueAsString(out));
    }catch(Exception e){throw new IllegalArgumentException("DELIVERY_TOOL_ARGUMENTS",e);}}
    private static String text(JsonNode n,String key){if(!n.path(key).isTextual())throw new IllegalArgumentException();return n.get(key).asText();}
    private static long number(JsonNode n,String key){var v=n.path(key);if(!v.isIntegralNumber()||!v.canConvertToLong()||v.longValue()>9007199254740991L)throw new IllegalArgumentException();return v.asLong();}
}
