package dev.mineagent.runtime.worker.provider;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.databind.node.ObjectNode;
public final class DeliveryToolSchemas {
    private static final ObjectMapper JSON=new ObjectMapper();private DeliveryToolSchemas(){}
    public static final String INSPECT=build("inspect"),OFFER=build("offer"),QUERY=build("query"),UPDATE=build("update"),STOP=build("stop");
    public static String finishSchema(String source){try{
        var root=(ObjectNode)JSON.readTree(source);var goal=JSON.createObjectNode().put("type","object").put("additionalProperties",false);var p=goal.putObject("properties");var required=goal.putArray("required");
        p.putObject("kind").put("const","content_delivery");p.putObject("delivery_id").put("type","string").put("format","uuid");for(String key:new String[]{"expected_revision","data_revision"})p.putObject(key).put("type","integer").put("minimum",1).put("maximum",9007199254740991L);p.putObject("data_sha256").put("type","string").put("pattern","^[a-f0-9]{64}$");var states=p.putObject("status").putArray("enum");dev.mineagent.runtime.core.delivery.DeliveryGoal.STATES.stream().sorted().forEach(states::add);var evidence=p.putObject("evidence").putArray("enum");dev.mineagent.runtime.core.delivery.DeliveryGoal.EVIDENCE.stream().sorted().forEach(evidence::add);
        for(String key:new String[]{"kind","delivery_id","expected_revision","data_revision","data_sha256","status","evidence"})required.add(key);((com.fasterxml.jackson.databind.node.ArrayNode)root.path("properties").path("checks").path("items").path("oneOf")).add(goal);return JSON.writeValueAsString(root);
    }catch(Exception invalid){throw new IllegalStateException("DELIVERY_FINISH_SCHEMA",invalid);}}
    private static String build(String mode){try{var root=JSON.createObjectNode().put("type","object").put("additionalProperties",false);var p=root.putObject("properties");var required=root.putArray("required");
        if(mode.equals("offer")){for(String key:new String[]{"package_id","audience_snapshot_id"}){p.putObject(key).put("type","string").put("format","uuid");required.add(key);}p.putObject("package_revision").put("type","integer").put("minimum",1);p.putObject("canonical_sha256").put("type","string").put("pattern","^[a-f0-9]{64}$");p.putObject("entry_id").put("type","string").put("maxLength",64);p.putObject("mode").putArray("enum").add("CONTENT").add("HUD").add("CLIENT_RHINO").add("CLIENT_JAVA");p.set("data",JSON.createObjectNode());p.putObject("feedback_enabled").put("type","boolean").put("description","Explicitly request separately authorized declared UI feedback. CLIENT code modes require false and never inherit feedback authority.");var binding=p.putObject("feedback_binding").put("type","object").put("additionalProperties",false);var bp=binding.putObject("properties");bp.putObject("instance_id").put("type","string").put("format","uuid");bp.putObject("namespace").put("type","string").put("maxLength",64);bp.putObject("schema_version").put("type","integer").put("minimum",1);for(String key:new String[]{"read_keys","write_keys"})bp.putObject(key).put("type","array").put("minItems",1).put("maxItems",8).putObject("items").put("type","string");binding.putArray("required").add("instance_id").add("namespace").add("schema_version").add("read_keys").add("write_keys");p.putObject("ttl_seconds").put("type","integer").put("minimum",1).put("maximum",604800);required.add("package_revision").add("canonical_sha256").add("entry_id").add("data");}
        else if(mode.equals("inspect")){p.putObject("package_id").put("type","string").put("format","uuid");p.putObject("package_revision").put("type","integer").put("minimum",1);p.putObject("canonical_sha256").put("type","string").put("pattern","^[a-f0-9]{64}$");p.putObject("entry_id").put("type","string").put("maxLength",64);p.putObject("offset").put("type","integer").put("minimum",0).put("maximum",256);required.add("package_id").add("package_revision").add("canonical_sha256");}
        else if(mode.equals("query")){p.putObject("batch_id").put("type","string").put("format","uuid");p.putObject("offset").put("type","integer").put("minimum",0).put("maximum",64);required.add("batch_id");}
        else{p.putObject("delivery_id").put("type","string").put("format","uuid");required.add("delivery_id");if(mode.equals("update")){p.putObject("expected_data_revision").put("type","integer").put("minimum",1);p.set("data",JSON.createObjectNode());required.add("expected_data_revision").add("data");}}
        return JSON.writeValueAsString(root);
    }catch(Exception e){throw new IllegalStateException("DELIVERY_SCHEMA",e);}}
}
