package dev.mineagent.runtime.worker.provider;
import com.fasterxml.jackson.databind.ObjectMapper;
public final class FeedbackToolSchemas {
    private FeedbackToolSchemas(){}
    public static final String INSPECT="{\"type\":\"object\",\"properties\":{},\"additionalProperties\":false}";
    public static final String REPLY="{\"type\":\"object\",\"properties\":{\"text\":{\"type\":\"string\",\"minLength\":1,\"maxLength\":4096}},\"required\":[\"text\"],\"additionalProperties\":false}";
    public static final String FINISH="{\"type\":\"object\",\"properties\":{\"checks\":{\"type\":\"array\",\"minItems\":1,\"maxItems\":1,\"items\":{\"type\":\"object\",\"properties\":{\"kind\":{\"const\":\"feedback_reply\"},\"operation_id\":{\"type\":\"string\",\"format\":\"uuid\"}},\"required\":[\"kind\",\"operation_id\"],\"additionalProperties\":false}}},\"required\":[\"checks\"],\"additionalProperties\":false}";
    public static final String SUBSCRIBE=subscribe();
    private static String subscribe(){try{var json=new ObjectMapper();var root=json.createObjectNode().put("type","object").put("additionalProperties",false);var p=root.putObject("properties");for(String key:new String[]{"package_id","canonical_sha256","entry_path","policy_sha256"})p.putObject(key).put("type","string");p.putObject("package_revision").put("type","integer").put("minimum",1);p.putObject("events").put("type","array").put("minItems",1).put("maxItems",8).put("uniqueItems",true).putObject("items").put("type","string");p.putObject("mode").putArray("enum").add("RECORD_ONLY").add("AGENT_WAKE");p.putObject("goal").put("type","string").put("maxLength",200);for(String name:new String[]{"max_wakes","max_model_calls","pending_limit","cooldown_ms","ttl_seconds"})p.putObject(name).put("type","integer").put("minimum",name.equals("ttl_seconds")||name.equals("pending_limit")?1:0).put("maximum",switch(name){case "max_wakes"->32;case "max_model_calls"->16;case "pending_limit"->8;case "cooldown_ms"->600000;default->604800;});root.putArray("required").add("package_id").add("package_revision").add("canonical_sha256").add("entry_path").add("policy_sha256").add("events").add("mode");return json.writeValueAsString(root);}catch(Exception e){throw new IllegalStateException("FEEDBACK_SCHEMA",e);}}
}
