package dev.mineagent.runtime.worker.provider;
import com.fasterxml.jackson.databind.JsonNode;
import java.util.*;
/** Reassembles real OpenAI-compatible SSE tool deltas; incomplete/oversized calls are never executable. */
public final class StreamingToolCalls {
    private static final class Call{StringBuilder id=new StringBuilder(),name=new StringBuilder(),args=new StringBuilder();}
    private static IllegalArgumentException invalid(String code,String detail){return new IllegalArgumentException(code,new IllegalArgumentException(detail));}
    private final Map<Integer,Call> calls=new TreeMap<>();private int length;
    public void accept(JsonNode delta){if(delta.has("tool_calls")&&!delta.path("tool_calls").isNull()&&!delta.path("tool_calls").isArray())throw invalid("TOOL_STREAM_TYPE","delta.tool_calls must be an array");for(var part:delta.path("tool_calls")){if(!part.path("index").isIntegralNumber()||!part.path("index").canConvertToInt())throw invalid("TOOL_STREAM_INDEX","tool_calls[].index must be an integer");int index=part.path("index").asInt();if(index<0||index>=dev.mineagent.runtime.core.conversation.ConversationTools.MAX_CALLS_PER_ROUND)throw invalid("TOOL_STREAM_BUDGET","tool_calls index "+index+" exceeds the per-response call range 0.."+(dev.mineagent.runtime.core.conversation.ConversationTools.MAX_CALLS_PER_ROUND-1));var c=calls.computeIfAbsent(index,k->new Call());append(c.id,part.path("id"),"tool_calls["+index+"].id");append(c.name,part.path("function").path("name"),"tool_calls["+index+"].function.name");append(c.args,part.path("function").path("arguments"),"tool_calls["+index+"].function.arguments");if(c.id.length()>160||c.name.length()>64||c.args.length()>196608||length>4*1024*1024)throw invalid("TOOL_STREAM_BUDGET","tool_calls["+index+"] exceeds a transport bound: id<=160, name<=64, arguments<=196608, total<=4194304 characters");}}
    private void append(StringBuilder out,JsonNode n,String field){if(n.isMissingNode()||n.isNull())return;if(!n.isTextual())throw invalid("TOOL_STREAM_TYPE",field+" must be a text delta, received "+n.getNodeType());out.append(n.textValue());length+=n.textValue().length();}
    public List<ToolCall> finish(){var result=new ArrayList<ToolCall>();var ids=new HashSet<String>();for(var c:calls.values()){String id=c.id.toString(),name=c.name.toString(),args=c.args.toString();if(id.isBlank()||!ids.add(id)||name.isBlank()||name.length()>64)throw invalid("TOOL_STREAM_INCOMPLETE","Each tool call must have a unique nonempty id and a nonempty name of at most 64 characters; received id="+id+", name="+name);if(args.length()>dev.mineagent.runtime.core.conversation.ConversationTools.maxArgumentCharacters(name))throw invalid("TOOL_STREAM_BUDGET","Arguments for "+name+" exceed "+dev.mineagent.runtime.core.conversation.ConversationTools.maxArgumentCharacters(name)+" characters");result.add(new ToolCall(id,name,args));}return List.copyOf(result);}
}
