package dev.mineagent.runtime.core.host;
import java.util.UUID;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class HostCommandRequestTest {
    @Test void exactApprovalHashChangesWithCodePurposeOrTimeout(){var id=UUID.randomUUID();var base=new HostCommandRequest(id,"read app","print(1)",5);assertNotEquals(base.sha256(),new HostCommandRequest(id,"read app","print(2)",5).sha256());assertNotEquals(base.sha256(),new HostCommandRequest(id,"different task","print(1)",5).sha256());assertNotEquals(base.sha256(),new HostCommandRequest(id,"read app","print(1)",6).sha256());}
    @Test void misleadingControlsExcessiveCodeAndTimeoutAreRejected(){var id=UUID.randomUUID();assertThrows(IllegalArgumentException.class,()->new HostCommandRequest(id,"task","abc\u202e",5));assertThrows(IllegalArgumentException.class,()->new HostCommandRequest(id,"task\nnext","print(1)",5));assertThrows(IllegalArgumentException.class,()->new HostCommandRequest(id,"task","x".repeat(8193),5));assertThrows(IllegalArgumentException.class,()->new HostCommandRequest(id,"task","print(1)",61));}
    @Test void installerApprovalBindsPackagesAndRejectsOptionsPathsAndUrls(){var id=UUID.randomUUID();var a=HostCommandRequest.install(id,"dependencies",java.util.List.of("colorama==0.4.6"),180);assertEquals(HostCommandRequest.Kind.INSTALL_PACKAGES,a.kind());assertNotEquals(a.sha256(),HostCommandRequest.install(id,"dependencies",java.util.List.of("colorama>=0.4.6,<1"),180).sha256());for(String bad:java.util.List.of("--target=x","../other","https://example.org/a.whl","x @ https://example.org/a","x;evil","-r file"))assertThrows(IllegalArgumentException.class,()->HostCommandRequest.install(id,"deps",java.util.List.of(bad),60));assertThrows(IllegalArgumentException.class,()->new HostCommandRequest(id,"deps","misleading",60,HostCommandRequest.Kind.INSTALL_PACKAGES,java.util.List.of("colorama")));}
}
