package dev.mineagent.runtime.neoforge.body;
import com.fasterxml.jackson.databind.ObjectMapper;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;
import dev.mineagent.runtime.api.agent.AgentMode;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.Difficulty;
import net.minecraft.world.InteractionHand;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.entity.projectile.arrow.AbstractArrow;
import net.minecraft.world.item.*;
import net.minecraft.world.level.GameType;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.gamerules.GameRules;
import net.minecraft.world.level.storage.LevelData;
import net.minecraft.world.phys.*;
import net.minecraft.stats.Stats;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.event.tick.ServerTickEvent;
import net.neoforged.neoforge.event.entity.living.LivingDeathEvent;
import java.nio.file.*;
import java.util.*;

/** Explicit isolated Native survival fixture. Inventory/food priming is setup, not claimed gameplay output. */
@EventBusSubscriber(modid="mineagent_runtime")
public final class BodySurvivalSmokeServer {
    public static volatile UUID agent;public static volatile String wanted="",failure="";public static volatile boolean humanRespawn,done;
    public static final Set<String> seen=java.util.concurrent.ConcurrentHashMap.newKeySet();
    private static final ObjectMapper JSON=new ObjectMapper();private static int phase,at;private static MineAgentPlayer dead,first;private static ServerPlayer oldViewer;
    private static long ticksBefore;private static int playBefore,sprintBefore,jumpsBefore,deathsBefore,cancelled;private static boolean cancelDeath,failCancel;private static UUID use;
    private static final AABB AREA=new AABB(790,165,-5,830,185,15);
    private static void require(boolean ok,String code){if(!ok)throw new IllegalStateException(code);}
    private static Path root(net.minecraft.server.MinecraftServer s){return s.getServerDirectory().resolve("body-survival-evidence");}
    private static void save(net.minecraft.server.MinecraftServer s,String file,Object value)throws Exception{Files.createDirectories(root(s));Files.writeString(root(s).resolve(file),JSON.writeValueAsString(value));}
    private static int stat(ServerPlayer p,net.minecraft.resources.Identifier id){return p.getStats().getValue(Stats.CUSTOM.get(id));}
    private static int count(ServerPlayer p,Item item){int n=0;for(int i=0;i<p.getInventory().getContainerSize();i++)if(p.getInventory().getItem(i).is(item))n+=p.getInventory().getItem(i).getCount();return n;}
    private static int dropped(net.minecraft.server.level.ServerLevel l,Item item){return l.getEntitiesOfClass(ItemEntity.class,AREA).stream().filter(e->e.getItem().is(item)).mapToInt(e->e.getItem().getCount()).sum();}
    public static Map<String,Object> snapshot(MineAgentPlayer p){var n=new LinkedHashMap<String,Object>();n.put("agent",p.agentId());n.put("uuid",p.getUUID());n.put("javaBody",System.identityHashCode(p));n.put("entityId",p.getId());n.put("connection",System.identityHashCode(p.connection));n.put("listenerBound",p.connection.player==p);n.put("clientLoaded",p.connection.hasClientLoaded());n.put("health",p.getHealth());n.put("food",p.getFoodData().getFoodLevel());n.put("saturation",p.getFoodData().getSaturationLevel());n.put("mode",p.gameMode.getGameModeForPlayer().getName());n.put("serverTick",p.level().getServer().getTickCount());n.put("nativeTicks",p.nativeTicks());n.put("playTime",stat(p,Stats.PLAY_TIME));n.put("sprintCm",stat(p,Stats.SPRINT_ONE_CM));n.put("jumps",stat(p,Stats.JUMP));n.put("deaths",stat(p,Stats.DEATHS));n.put("acceptedDeath",p.deathAccepted());n.put("removed",p.isRemoved());n.put("position",List.of(p.getX(),p.getY(),p.getZ()));n.put("diamonds",count(p,Items.DIAMOND));n.put("emeralds",count(p,Items.EMERALD));n.put("gold",count(p,Items.GOLD_INGOT));n.put("cursor",p.containerMenu.getCarried().getCount());n.put("fallCm",stat(p,Stats.FALL_ONE_CM));n.put("experience",p.totalExperience);n.put("usingItem",p.isUsingItem());n.put("onGround",p.onGround());n.put("velocity",p.getDeltaMovement().toString());n.put("movementOutcome",p.movementController().outcome());n.put("movementSteps",p.movementController().executedSteps());return n;}
    private static void hold(MineAgentPlayer p){p.movementController().stop();require(p.claimTaskControl(UUID.randomUUID(),()->true,()->{cancelled++;if(failCancel){failCancel=false;throw new IllegalStateException("CONTROLLED_CANCEL_FAILURE");}}),"SURVIVAL_CONTROL_BUSY");}
    private static void observe(ServerPlayer viewer,Vec3 target){
        var camera=target.add(0,3,5);viewer.setGameMode(GameType.SPECTATOR);
        viewer.teleportTo(viewer.level(),camera.x,camera.y,camera.z,Set.of(),180,36,true);
    }
    @SubscribeEvent public static void death(LivingDeathEvent event){if(Boolean.getBoolean("mineagent.bodySurvivalSmoke")&&cancelDeath&&event.getEntity() instanceof MineAgentPlayer p&&p.agentId().equals(agent)){p.setHealth(4);event.setCanceled(true);}}
    @SubscribeEvent public static void tick(ServerTickEvent.Post event)throws Exception{
        if(!Boolean.getBoolean("mineagent.bodySurvivalSmoke")||done||!failure.isEmpty())return;var server=event.getServer();var level=server.overworld();var bodies=MineAgentRuntimeServices.bodies(server);
        var viewer=server.getPlayerList().getPlayers().stream().filter(p->!(p instanceof MineAgentPlayer)).findFirst().orElse(null);if(viewer==null)return;
        try{require(phase==0||server.getTickCount()-at<600,"SURVIVAL_TIMEOUT_"+phase);
            if(phase==0){server.setDifficulty(Difficulty.HARD,true);level.getGameRules().set(GameRules.KEEP_INVENTORY,false,server);level.getGameRules().set(GameRules.NATURAL_HEALTH_REGENERATION,false,server);level.getGameRules().set(GameRules.RESPAWN_RADIUS,0,server);
                for(int x=796;x<=822;x++)for(int z=-2;z<=10;z++){level.setBlockAndUpdate(new BlockPos(x,169,z),Blocks.STONE.defaultBlockState());for(int y=170;y<=179;y++)level.setBlockAndUpdate(new BlockPos(x,y,z),Blocks.AIR.defaultBlockState());}
                for(int x=799;x<=814;x++)for(int z:new int[]{0,2})for(int y=170;y<=173;y++)level.setBlockAndUpdate(new BlockPos(x,y,z),Blocks.GLASS.defaultBlockState());
                for(int x:new int[]{799,814})for(int y=170;y<=173;y++)level.setBlockAndUpdate(new BlockPos(x,y,1),Blocks.GLASS.defaultBlockState());level.setBlockAndUpdate(new BlockPos(805,170,1),Blocks.STONE.defaultBlockState());
                viewer.setGameMode(GameType.CREATIVE);observe(viewer,new Vec3(800.5,170,1.5));
                agent=bodies.create("Survival body",viewer,AgentMode.SURVIVAL).agentId();first=bodies.body(agent).orElseThrow();first.teleportTo(level,800.5,170,1.5,Set.of(),0,0,true);first.getInventory().clearContent();first.setHealth(20);hold(first);first.setRespawnPosition(new ServerPlayer.RespawnConfig(LevelData.RespawnData.of(level.dimension(),new BlockPos(801,170,5),0,0),true),false);
                save(server,"setup.json",Map.of("body",snapshot(first),"fixtureSetup","Explicit local floor/corridor, survival state and starting exhaustion; no Provider","viewer",viewer.getUUID()));wanted="spawn";phase=1;at=server.getTickCount();return;
            }
            var body=bodies.body(agent).orElse(null);require(body!=null,"SURVIVAL_BODY_MISSING");
            switch(phase){
                case 1->{if(!seen.contains("spawn"))return;body.getFoodData().setFoodLevel(10);body.getFoodData().setSaturation(0);body.getFoodData().addExhaustion(3.9f);body.setSprinting(true);ticksBefore=body.nativeTicks();playBefore=stat(body,Stats.PLAY_TIME);sprintBefore=stat(body,Stats.SPRINT_ONE_CM);jumpsBefore=stat(body,Stats.JUMP);body.movementController().movePreciselyTo(new Vec3(812.5,170,1.5));save(server,"movement-before.json",snapshot(body));phase=2;at=server.getTickCount();}
                case 2->{require(!body.movementController().outcome().equals("UNREACHABLE"),"SURVIVAL_PATH_UNREACHABLE");if(!body.movementController().outcome().equals("ARRIVED"))return;require(body.position().distanceToSqr(812.5,170,1.5)<.2&&stat(body,Stats.SPRINT_ONE_CM)>sprintBefore+600&&stat(body,Stats.JUMP)>jumpsBefore&&body.getFoodData().getFoodLevel()<10,"NATIVE_MOVEMENT_OR_HUNGER_MISSING");require(stat(body,Stats.PLAY_TIME)-playBefore==body.nativeTicks()-ticksBefore,"NATIVE_PLAYER_TICK_RATE");long before=body.nativeTicks();int played=stat(body,Stats.PLAY_TIME);body.tick();body.doTick();bodies.tickBodies(server.getTickCount());require(before==body.nativeTicks()&&played==stat(body,Stats.PLAY_TIME),"DUPLICATE_BODY_TICK");save(server,"movement-verified.json",snapshot(body));body.setSprinting(false);body.movementController().stop();body.setHealth(20);body.teleportTo(level,812.5,177,1.5,Set.of(),0,0,true);body.setDeltaMovement(Vec3.ZERO);body.setOnGround(false);phase=3;at=server.getTickCount();}
                case 3->{if(!body.onGround()||server.getTickCount()-at<12)return;require(body.getHealth()>0&&body.getHealth()<20,"NATIVE_FALL_DAMAGE_MISSING");save(server,"fall-verified.json",snapshot(body));body.setHealth(6);body.getFoodData().setFoodLevel(0);body.getFoodData().setSaturation(0);phase=4;at=server.getTickCount();}
                case 4->{if(body.getHealth()>=6)return;require(body.getHealth()>0,"STARVATION_DIED_TOO_EARLY");save(server,"starvation-verified.json",snapshot(body));level.getGameRules().set(GameRules.NATURAL_HEALTH_REGENERATION,true,server);body.setHealth(5);body.getFoodData().setFoodLevel(20);body.getFoodData().setSaturation(5);phase=5;at=server.getTickCount();}
                case 5->{if(body.getHealth()<=5)return;save(server,"regen-verified.json",snapshot(body));level.getGameRules().set(GameRules.NATURAL_HEALTH_REGENERATION,false,server);body.getInventory().setItem(0,new ItemStack(Items.DIAMOND,5));deathsBefore=stat(body,Stats.DEATHS);cancelDeath=true;body.invulnerableTime=0;body.hurtServer(level,body.damageSources().genericKill(),1000);cancelDeath=false;require(body.isAlive()&&!body.deathAccepted()&&cancelled==0&&count(body,Items.DIAMOND)==5&&stat(body,Stats.DEATHS)==deathsBefore,"CANCELLED_DEATH_CHANGED_LIFECYCLE");save(server,"cancelled-death.json",snapshot(body));phase=6;at=server.getTickCount();}
                case 6->{if(server.getTickCount()-at<40)return;require(body==first&&body.isAlive()&&cancelled==0,"CANCELLED_DEATH_RESPAWNED");body.getInventory().clearContent();body.getInventory().setItem(0,new ItemStack(Items.BOW));body.getInventory().setItem(1,new ItemStack(Items.ARROW));body.getInventory().setItem(2,new ItemStack(Items.DIAMOND,5));body.getInventory().setSelectedSlot(0);body.inventoryMenu.setCarried(new ItemStack(Items.EMERALD,3));body.inventoryMenu.getSlot(1).set(new ItemStack(Items.GOLD_INGOT,2));use=UUID.randomUUID();require(body.beginTaskItemUse(use,InteractionHand.MAIN_HAND)&&body.isUsingItem(),"BOW_SETUP_FAILED");observe(viewer,body.position());phase=61;at=server.getTickCount();}
                case 61->{if(server.getTickCount()-at<30)return;require(body.isUsingItem(),"BOW_NOT_HELD");dead=body;body.invulnerableTime=0;body.hurtServer(level,body.damageSources().genericKill(),1000);require(body.deathAccepted()&&cancelled==1&&!body.isUsingItem()&&!body.taskControlOwned(),"ACCEPTED_DEATH_NOT_STOPPED");require(!body.claimTaskControl(UUID.randomUUID(),()->true,()->{})&&!body.beginTaskItemUse(UUID.randomUUID(),InteractionHand.MAIN_HAND)&&!body.beginMining(new BlockPos(812,169,1)),"DEAD_BODY_ACTION_ACCEPTED");body.completeUsingItem();body.doCloseContainer();require(body.containerMenu.getCarried().getCount()==3,"DEAD_CURSOR_CLOSED_EARLY");int deaths=stat(body,Stats.DEATHS);body.die(body.damageSources().genericKill());require(stat(body,Stats.DEATHS)==deaths&&deaths==deathsBefore+1,"DEATH_REPLAYED");save(server,"death-drop.json",Map.of("body",snapshot(body),"dropsDiamonds",dropped(level,Items.DIAMOND),"dropsEmeralds",dropped(level,Items.EMERALD),"dropsGold",dropped(level,Items.GOLD_INGOT),"arrowsInWorld",level.getEntitiesOfClass(AbstractArrow.class,AREA).size(),"cancelledControls",cancelled));wanted="dead-drop";phase=7;at=server.getTickCount();}
                case 7->{if(body==dead)return;verifyReplacement(server,body);require(count(body,Items.DIAMOND)==0&&dropped(level,Items.DIAMOND)==5&&count(body,Items.EMERALD)+dropped(level,Items.EMERALD)==3&&count(body,Items.GOLD_INGOT)==0&&dropped(level,Items.GOLD_INGOT)==2&&level.getEntitiesOfClass(AbstractArrow.class,AREA).isEmpty(),"DEATH_ITEMS_OR_USE_REPLAYED");hold(body);save(server,"respawn-drop.json",Map.of("old",snapshot(dead),"fresh",snapshot(body),"dropsDiamonds",dropped(level,Items.DIAMOND),"dropsGold",dropped(level,Items.GOLD_INGOT),"emeraldTotal",count(body,Items.EMERALD)+dropped(level,Items.EMERALD)));observe(viewer,body.position());wanted="respawn-drop";phase=8;at=server.getTickCount();}
                case 8->{if(!seen.contains("respawn-drop"))return;level.getGameRules().set(GameRules.KEEP_INVENTORY,true,server);body.getInventory().clearContent();body.getInventory().setItem(0,new ItemStack(Items.DIAMOND,7));body.inventoryMenu.setCarried(new ItemStack(Items.EMERALD,4));body.inventoryMenu.getSlot(1).set(new ItemStack(Items.GOLD_INGOT,3));body.giveExperiencePoints(100);save(server,"keep-before.json",snapshot(body));dead=body;failCancel=true;body.invulnerableTime=0;body.hurtServer(level,body.damageSources().genericKill(),1000);require(body.deathAccepted()&&cancelled==2,"KEEP_DEATH_NOT_ACCEPTED");save(server,"death-keep.json",snapshot(body));wanted="dead-keep";phase=9;at=server.getTickCount();}
                case 9->{if(body==dead)return;verifyReplacement(server,body);require(count(body,Items.DIAMOND)==7&&body.totalExperience==dead.totalExperience&&dropped(level,Items.DIAMOND)==5&&count(body,Items.EMERALD)==0&&dropped(level,Items.EMERALD)==7&&count(body,Items.GOLD_INGOT)==0&&dropped(level,Items.GOLD_INGOT)==5,"KEEP_INVENTORY_NATIVE_TRANSFER");hold(body);save(server,"respawn-keep.json",Map.of("old",snapshot(dead),"fresh",snapshot(body),"dropsDiamonds",dropped(level,Items.DIAMOND),"dropsEmeralds",dropped(level,Items.EMERALD),"dropsGold",dropped(level,Items.GOLD_INGOT)));observe(viewer,body.position());wanted="respawn-keep";phase=10;at=server.getTickCount();}
                case 10->{if(!seen.contains("respawn-keep"))return;oldViewer=viewer;viewer.setRespawnPosition(new ServerPlayer.RespawnConfig(LevelData.RespawnData.of(level.dimension(),new BlockPos(810,170,6),0,0),true),false);viewer.getInventory().setItem(8,new ItemStack(Items.DIAMOND,11));viewer.setGameMode(GameType.SURVIVAL);viewer.invulnerableTime=0;humanRespawn=true;viewer.hurtServer(level,viewer.damageSources().genericKill(),1000);phase=11;at=server.getTickCount();}
                case 11->{if(viewer==oldViewer||!viewer.isAlive())return;require(!(viewer instanceof MineAgentPlayer)&&viewer.getUUID().equals(oldViewer.getUUID())&&viewer.connection.player==viewer&&viewer.getInventory().getItem(8).getCount()==11,"NORMAL_PLAYER_RESPAWN_CHANGED");save(server,"human-respawn.json",Map.of("uuid",viewer.getUUID(),"newJavaBody",viewer!=oldViewer,"normalClass",viewer.getClass().getName(),"health",viewer.getHealth(),"food",viewer.getFoodData().getFoodLevel(),"diamonds",viewer.getInventory().getItem(8).getCount()));humanRespawn=false;viewer.setGameMode(GameType.CREATIVE);phase=12;at=server.getTickCount();}
                case 12->{if(server.getTickCount()-at<20)return;save(server,"result.json",Map.of("status","NATIVE_AI_SURVIVAL_AND_RESPAWN_VERIFIED","agent",agent,"modelCalls",0,"systemInputInjected",false,"cancelledControls",cancelled,"normalPlayerRegression",true,"fullV1",false));bodies.remove(agent,viewer.getUUID(),true);done=true;}
                default->throw new IllegalStateException("SURVIVAL_PHASE");
            }
        }catch(Exception e){failure=e.toString();save(server,"failure.json",Map.of("phase",phase,"error",failure,"body",bodySafe(bodies)));}
    }
    private static Object bodySafe(MineAgentBodyManager manager){return agent==null?Map.of():manager.body(agent).map(BodySurvivalSmokeServer::snapshot).orElse(Map.of());}
    private static void verifyReplacement(net.minecraft.server.MinecraftServer server,MineAgentPlayer body){require(body!=dead&&dead.isRemoved()&&body.agentId().equals(dead.agentId())&&body.ownerPlayerId().equals(dead.ownerPlayerId())&&server.getPlayerList().getPlayer(agent)==body&&body.level().getEntity(agent)==body&&body.connection==dead.connection&&body.connection.player==body&&body.connection.hasClientLoaded()&&body.getHealth()==body.getMaxHealth()&&body.getFoodData().getFoodLevel()==20&&!body.deathAccepted()&&body.gameMode.getGameModeForPlayer()==GameType.SURVIVAL&&body.position().distanceToSqr(801.5,170,5.5)<4,"NATIVE_RESPAWN_CONTEXT");}
}
