package dev.mineagent.runtime.neoforge.body;
import dev.mineagent.runtime.core.task.SurfacePathfinder;import dev.mineagent.runtime.core.task.SurfacePathfinder.Node;import net.minecraft.core.BlockPos;import net.minecraft.world.level.block.*;import net.minecraft.world.phys.*;import net.minecraft.world.phys.shapes.CollisionContext;import java.util.*;
public final class NativeSurfaceNavigation {
 private static boolean openable(net.minecraft.server.level.ServerPlayer p,BlockPos pos,net.minecraft.world.level.block.state.BlockState s){boolean open=s.getBlock() instanceof DoorBlock d&&d.type().canOpenByHand()&&!s.getValue(DoorBlock.OPEN)||s.getBlock() instanceof FenceGateBlock&&!s.getValue(FenceGateBlock.OPEN);return open&&!dev.mineagent.runtime.neoforge.ui.ServerInteractionRules.denied(p,pos,null,"block_use",false);}
 // Test both vanilla poses, never shrink the standing box or assume every low tunnel is traversable.
 public static boolean clear(net.minecraft.server.level.ServerPlayer p,double x,double y,double z){return clearPose(p,x,y,z,net.minecraft.world.entity.Pose.STANDING)||clearPose(p,x,y,z,net.minecraft.world.entity.Pose.CROUCHING);}
 public static boolean clearPose(net.minecraft.server.level.ServerPlayer p,double x,double y,double z,net.minecraft.world.entity.Pose pose){var box=p.getDimensions(pose).makeBoundingBox(new Vec3(x,y,z)).deflate(.0001);var level=p.level();for(var pos:BlockPos.betweenClosed((int)Math.floor(box.minX),(int)Math.floor(box.minY),(int)Math.floor(box.minZ),(int)Math.floor(box.maxX),(int)Math.floor(box.maxY),(int)Math.floor(box.maxZ))){if(!level.hasChunkAt(pos)||level.isOutsideBuildHeight(pos)||!level.getWorldBorder().isWithinBounds(pos))return false;var state=level.getBlockState(pos);if(!state.getFluidState().isEmpty()||state.is(Blocks.SWEET_BERRY_BUSH)||state.is(Blocks.WITHER_ROSE)||state.is(Blocks.CAMPFIRE)||state.is(Blocks.SOUL_CAMPFIRE)||state.is(Blocks.LAVA)||state.is(Blocks.FIRE)||state.is(Blocks.SOUL_FIRE)||state.is(Blocks.CACTUS)||state.is(Blocks.POWDER_SNOW))return false;if(openable(p,pos,state))continue;for(var shape:state.getCollisionShape(level,pos,CollisionContext.of(p)).toAabbs())if(shape.move(pos).intersects(box))return false;}return true;}
 public static boolean transitionClear(net.minecraft.server.level.ServerPlayer p,Vec3 from,Vec3 to){double top=Math.max(from.y,to.y);int count=Math.max(1,(int)Math.ceil(from.distanceTo(to)*8));for(int i=0;i<=count;i++){double t=(double)i/count;if(!clear(p,from.x+(to.x-from.x)*t,top,from.z+(to.z-from.z)*t))return false;}return true;}
 /** Used by both the local player's native Shift input and the server AI body. */
 public static boolean requiresSneaking(net.minecraft.world.entity.player.Player p,Vec3 next){return dev.mineagent.runtime.core.task.SneakClearance.required(new dev.mineagent.runtime.core.task.SneakClearance.Point(p.getX(),p.getY(),p.getZ()),new dev.mineagent.runtime.core.task.SneakClearance.Point(next.x,next.y,next.z),(point,crouched)->p.level().noCollision(p,p.getDimensions(crouched?net.minecraft.world.entity.Pose.CROUCHING:net.minecraft.world.entity.Pose.STANDING).makeBoundingBox(new Vec3(point.x(),point.y(),point.z())).deflate(.0001)));}

 private static List<Node> floors(net.minecraft.server.level.ServerPlayer p,int x,int z,double near){var out=new ArrayList<Node>();for(int y=(int)Math.floor(near)-4;y<=(int)Math.floor(near)+1;y++){var pos=new BlockPos(x,y,z);if(!p.level().hasChunkAt(pos)||p.level().isOutsideBuildHeight(pos))continue;var s=p.level().getBlockState(pos);if(s.getBlock() instanceof DoorBlock||s.getBlock() instanceof FenceGateBlock||s.is(Blocks.MAGMA_BLOCK)||s.is(Blocks.CACTUS))continue;for(var b:s.getCollisionShape(p.level(),pos,CollisionContext.of(p)).toAabbs()){if(b.maxX<.22||b.minX>.78||b.maxZ<.22||b.minZ>.78)continue;double foot=y+b.maxY;if(foot<near-3.01||foot>near+1.251||!clear(p,x+.5,foot,z+.5))continue;var node=new Node(x,(int)Math.round(foot*16),z);if(!out.contains(node))out.add(node);}}return out;}
 public static List<Vec3> standingPositions(net.minecraft.server.level.ServerPlayer p,int x,int z,double near){return floors(p,x,z,near).stream().map(n->new Vec3(n.x()+.5,n.y(),n.z()+.5)).toList();}
 public static List<Vec3> find(net.minecraft.server.level.ServerPlayer p,Vec3 target,int budget){var start=floors(p,(int)Math.floor(p.getX()),(int)Math.floor(p.getZ()),p.getY()).stream().min(Comparator.comparingDouble(n->Math.abs(n.y()-p.getY()))).orElse(null);var goal=floors(p,(int)Math.floor(target.x),(int)Math.floor(target.z),target.y).stream().min(Comparator.comparingDouble(n->Math.abs(n.y()-target.y))).orElse(null);if(start==null||goal==null)return List.of();var cache=new HashMap<String,List<Node>>();var route=SurfacePathfinder.find(start,goal,budget,n->{var out=new ArrayList<Node>();for(int[] d:new int[][]{{1,0},{-1,0},{0,1},{0,-1}}){int x=n.x()+d[0],z=n.z()+d[1];String key=x+":"+z+":"+(int)Math.floor(n.y());for(var next:cache.computeIfAbsent(key,k->floors(p,x,z,n.y()))){double rise=next.y()-n.y();if(rise>1.251||rise< -3)continue;if(transitionClear(p,new Vec3(n.x()+.5,n.y(),n.z()+.5),new Vec3(next.x()+.5,next.y(),next.z()+.5)))out.add(next);}}return out;});return route.stream().map(n->new Vec3(n.x()+.5,n.y(),n.z()+.5)).toList();}
 public static boolean openOnPath(net.minecraft.server.level.ServerPlayer p,Vec3 waypoint){for(var pos:BlockPos.betweenClosed(BlockPos.containing(waypoint),BlockPos.containing(waypoint).above())){var state=p.level().getBlockState(pos);if(openable(p,pos,state)&&p.distanceToSqr(Vec3.atCenterOf(pos))<6.25&&p.isWithinBlockInteractionRange(pos,1)){var aim=state.getShape(p.level(),pos,CollisionContext.of(p)).toAabbs().stream().map(b->b.move(pos).getCenter()).min(Comparator.comparingDouble(p.getEyePosition()::distanceToSqr)).orElse(Vec3.atCenterOf(pos));var sight=p.level().clip(new net.minecraft.world.level.ClipContext(p.getEyePosition(),aim,net.minecraft.world.level.ClipContext.Block.COLLIDER,net.minecraft.world.level.ClipContext.Fluid.NONE,p));if(sight.getType()!=HitResult.Type.MISS&&!sight.getBlockPos().equals(pos))continue;p.lookAt(net.minecraft.commands.arguments.EntityAnchorArgument.Anchor.EYES,aim);boolean shifted=p.isShiftKeyDown();p.setShiftKeyDown(false);try{p.gameMode.useItemOn(p,p.level(),p.getMainHandItem(),net.minecraft.world.InteractionHand.MAIN_HAND,sight);}finally{p.setShiftKeyDown(shifted);}p.swing(net.minecraft.world.InteractionHand.MAIN_HAND);var after=p.level().getBlockState(pos);if(after.getBlock() instanceof DoorBlock&&!after.getValue(DoorBlock.OPEN)||after.getBlock() instanceof FenceGateBlock&&!after.getValue(FenceGateBlock.OPEN))return false;if(after.getBlock() instanceof DoorBlock||after.getBlock() instanceof FenceGateBlock)if(p instanceof MineAgentPlayer bot)bot.movementController().recordOpened(after.getBlock() instanceof FenceGateBlock);}}return true;}
 private NativeSurfaceNavigation(){}
}
