package dev.mineagent.runtime.client.host;
import dev.mineagent.runtime.core.host.HostCommandRequest;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import java.nio.file.*;
import java.util.*;
import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assumptions.*;
class LocalPowerShellExecutorTest {
    @TempDir Path root;
    private LocalPowerShellExecutor executor(){var p=LocalPowerShellExecutor.discover();assumeTrue(p.isPresent());return new LocalPowerShellExecutor(root,p.orElseThrow());}
    @Test void approvedActualPowerShellUsesUtf8AndDuplicateOperationNeverRunsAgain()throws Exception{var e=executor();var request=new HostCommandRequest(UUID.randomUUID(),"UTF8 contract","[Console]::WriteLine('原生命令成功'); [IO.File]::WriteAllText('receipt.txt','one')",10);var wrong=e.execute(request,"0".repeat(64),()->true);assertEquals("REJECTED",wrong.get("status"));var result=e.execute(request,request.sha256(),()->true);assertEquals("EXECUTED",result.get("status"),result.toString());assertEquals(0,result.get("exitCode"));assertTrue(result.get("stdout").toString().contains("原生命令成功"),result.toString());assertEquals("one",Files.readString(root.resolve("mineagent-host/workspace/receipt.txt")));assertEquals("HOST_OPERATION_NOT_REPLAYABLE",e.execute(request,request.sha256(),()->true).get("error"));String intent=Files.readString(root.resolve("mineagent-host/operations/"+request.operation()+".json"));assertFalse(intent.contains("WriteLine"));}
    @Test void quotesUnicodeBackticksAndDollarInterpolationAreTransportedUnchanged(){var e=executor();String code="$name='原生'; Write-Output \"$name => `\"引号`\"\"";var request=new HostCommandRequest(UUID.randomUUID(),"quote transport",code,10);var result=e.execute(request,request.sha256(),()->true);assertEquals("EXECUTED",result.get("status"),result.toString());assertEquals("原生 => \"引号\"",result.get("stdout").toString().strip());}
    @Test void revokedLocalContextStopsTheOwnedProcessWithoutReplaying(){var e=executor();var request=new HostCommandRequest(UUID.randomUUID(),"cancel test","Start-Sleep -Seconds 20",10);long start=System.nanoTime();var result=e.execute(request,request.sha256(),()->System.nanoTime()-start<java.util.concurrent.TimeUnit.MILLISECONDS.toNanos(900));assertEquals("CANCELLED",result.get("status"),result.toString());assertEquals(true,result.get("sideEffectsMayPersist"));assertFalse(ProcessHandle.of(((Number)result.get("pid")).longValue()).map(ProcessHandle::isAlive).orElse(false));assertEquals("HOST_OPERATION_NOT_REPLAYABLE",e.execute(request,request.sha256(),()->true).get("error"));}
    @Test void actualFailureTimeoutAndPagedOutputHaveDistinctOutcomes()throws Exception{var e=executor();var failure=new HostCommandRequest(UUID.randomUUID(),"failure","throw 'expected-failure'",10);var failed=e.execute(failure,failure.sha256(),()->true);assertEquals("FAILED",failed.get("status"),failed.toString());var timeout=new HostCommandRequest(UUID.randomUUID(),"timeout","Start-Sleep -Seconds 20",1);assertEquals("TIMED_OUT",e.execute(timeout,timeout.sha256(),()->true).get("status"));var noisy=new HostCommandRequest(UUID.randomUUID(),"bounded output","[Console]::Write('x'*20000)",10);var output=e.execute(noisy,noisy.sha256(),()->true);assertEquals("EXECUTED",output.get("status"));assertEquals(false,output.get("outputTruncated"));assertEquals(true,output.get("outputPreviewOnly"));StringBuilder all=new StringBuilder();int offset=0;do{var page=e.output(noisy.operation(),"stdout",offset);all.append(page.get("text"));offset=((Number)page.get("nextOffset")).intValue();}while(offset>=0);assertEquals("x".repeat(20000),all.toString());assertEquals(LocalPowerShellExecutor.OUTPUT_BYTES,output.get("stdout").toString().length());}
    @Test void fullOutputPagesPreserveSupplementaryUnicodeAndRejectInvalidCursors()throws Exception{
        var e=executor();var r=new HostCommandRequest(UUID.randomUUID(),"unicode paging","[Console]::Write(('a'*4095)+'😀尾部')",10);assertEquals("EXECUTED",e.execute(r,r.sha256(),()->true).get("status"));
        var first=e.output(r.operation(),"stdout",0);assertEquals("a".repeat(4095)+"😀",first.get("text"));assertEquals(4097,first.get("nextOffset"));
        var last=e.output(r.operation(),"stdout",4097);assertEquals("尾部",last.get("text"));assertEquals(-1,last.get("nextOffset"));
        assertThrows(IllegalArgumentException.class,()->e.output(r.operation(),"stdout",9000));assertThrows(IllegalArgumentException.class,()->e.output(r.operation(),"../file",0));
    }
}
