package dev.mineagent.runtime.neoforge.client.webui;
import com.google.gson.*;import dev.mineagent.runtime.neoforge.client.screen.*;import dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox;import net.minecraft.client.Minecraft;import net.minecraft.client.gui.components.*;import java.nio.file.*;import java.util.*;
/** Isolated zero-provider Native UI and actual NeoForge Mod list verification. */
public final class AboutUiSmokeClient {
 private static int ticks,phase,wait;private static boolean done;private static JsonObject probe;private static ControlCenterScreen parent;private static AboutScreen about;
 public static boolean active(){return Boolean.getBoolean("mineagent.conversationAgentSmoke")&&System.getProperty("mineagent.conversationAgentScenario","").equals("about_ui");}
 public static void accept(JsonObject value){probe=value;}
 private static void require(boolean v,String code){if(!v)throw new IllegalStateException(code);}
 private static void script(String source){var h=WebGuiHostAdapter.INSTANCE;h.browser().executeJavaScript("(()=>{"+source+"})();",h.browser().getURL(),0);}
 private static void screenshot(Path path){var mc=Minecraft.getInstance();net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),image->{try(image){image.writeToFile(path);}catch(Exception e){throw new IllegalStateException(e);}});}
 public static void tick()throws Exception{if(done)return;var mc=Minecraft.getInstance();ticks++;Path root=Files.createDirectories(mc.gameDirectory.toPath().resolve("about-ui-smoke"));try{
  if(ticks>2400)throw new IllegalStateException("ABOUT_UI_TIMEOUT_"+phase);if(mc.player==null)return;
  if(phase==0){String fp=PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","");if(fp.isEmpty()||new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fp)!=dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){if(mc.screen instanceof ControlCenterScreen s)for(var c:List.copyOf(s.children()))if(c instanceof Button b&&b.active&&b.getMessage().getString().contains("信任此服务器"))b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));return;}if(++wait==1)mc.player.connection.sendCommand("ai accept");if(wait<30)return;parent=ControlCenterScreen.create(null);mc.setScreen(parent);var button=parent.children().stream().filter(c->c instanceof Button b&&b.getMessage().getString().equals("关于")).map(c->(Button)c).findFirst().orElseThrow();button.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));require(mc.screen instanceof AboutScreen,"NATIVE_ABOUT_BUTTON");about=(AboutScreen)mc.screen;phase=1;wait=0;}
  if(phase==1&&++wait>25){String text=about.children().stream().filter(c->c instanceof StringWidget).map(c->((StringWidget)c).getMessage().getString()).collect(java.util.stream.Collectors.joining("\n"));for(String expected:List.of("项目名：DivZero","项目地址：https://github.com/gaoshanliuni/divzero","当前版本："+ProjectAboutClient.info().version(),"开发者：gaoshanliuni"))require(text.replace("\n","").contains(expected),"NATIVE_ABOUT_FIELDS");require(about.iconDraws>0,"NATIVE_ICON_NOT_DRAWN");Files.writeString(root.resolve("native.json"),new Gson().toJson(Map.of("text",text,"iconDraws",about.iconDraws,"fields",ProjectAboutClient.info().fields())));screenshot(root.resolve("native-about.png"));about.onClose();require(mc.screen==parent,"NATIVE_ABOUT_BACK");phase=2;wait=0;}
  if(phase==2&&++wait>10){var screen=new net.neoforged.neoforge.client.gui.ModListScreen(parent);mc.setScreen(screen);phase=21;wait=0;}
  if(phase==21&&++wait>10){var screen=(net.neoforged.neoforge.client.gui.ModListScreen)mc.screen;var list=screen.children().stream().filter(c->c instanceof net.neoforged.neoforge.client.gui.widget.ModListWidget).map(c->(net.neoforged.neoforge.client.gui.widget.ModListWidget)c).findFirst().orElseThrow();var entry=list.children().stream().filter(c->c.getInfo().getModId().equals("mineagent_runtime")).findFirst().orElseThrow();screen.setSelected(entry);require(entry.getInfo().getLogoFile().orElse("").equals("logo.png"),"MOD_LOGO_METADATA");var supplier=net.neoforged.neoforge.resource.ResourcePackLoader.getPackFor("mineagent_runtime").orElseThrow();try(var pack=supplier.openPrimary(new net.minecraft.server.packs.PackLocationInfo("mod/mineagent_runtime",net.minecraft.network.chat.Component.empty(),net.minecraft.server.packs.repository.PackSource.BUILT_IN,Optional.empty()))){var png=pack.getRootResource("logo.png");require(png!=null,"MOD_LIST_ROOT_LOGO_MISSING");try(var in=png.get();var image=com.mojang.blaze3d.platform.NativeImage.read(in)){require(image.getWidth()==1024&&image.getHeight()==1024,"MOD_LIST_LOGO_PNG");}}phase=3;wait=0;}
  if(phase==3&&++wait>25){screenshot(root.resolve("neoforge-mod-list.png"));Files.writeString(root.resolve("mod-logo.json"),"{\"status\":\"ACTUAL_MOD_LIST_LOGO_LOADED\",\"width\":1024,\"height\":1024}");mc.setScreen(null);WebGuiHostAdapter.INSTANCE.open();phase=4;wait=0;}
  var h=WebGuiHostAdapter.INSTANCE;
  if(phase==4&&h.ready()&&++wait>25){script("document.querySelector('#more-menu').open=true;document.querySelector('#open-about').click();");phase=5;wait=0;}
  if(phase>=5&&h.ready()&&ticks%10==0)script("const root=document.querySelector('[data-view-id=runtime-about]'),img=root?.querySelector('img');window.mineagentQuery({request:JSON.stringify({channel:'conversationAgentProbe',fields:Object.fromEntries([...root?.querySelectorAll('[data-about-field]')??[]].map(n=>[n.dataset.aboutField,n.textContent])),imageWidth:img?.naturalWidth??0,moreClosed:!document.querySelector('#more-menu').open,secondary:document.querySelector('#more-panel').contains(document.querySelector('#open-about')),background:root?getComputedStyle(root).backgroundColor:''}),persistent:false,onSuccess(){},onFailure(){}});");
  if(phase==5&&probe!=null&&probe.getAsJsonObject("fields").size()==4&&probe.get("imageWidth").getAsInt()==1024){for(var entry:ProjectAboutClient.info().fields().entrySet())require(probe.getAsJsonObject("fields").get(entry.getKey()).getAsString().equals(entry.getValue()),"F2_ABOUT_FIELDS");require(probe.get("moreClosed").getAsBoolean()&&probe.get("secondary").getAsBoolean(),"F2_ABOUT_SECONDARY_MENU");screenshot(root.resolve("f2-about.png"));Files.writeString(root.resolve("web.json"),probe.toString());phase=6;wait=0;}
  if(phase==6&&++wait>20){Files.writeString(root.resolve("result.json"),"{\"status\":\"NATIVE_F2_ABOUT_AND_MOD_ICON_VERIFIED\",\"providerCalls\":0,\"osInputInjected\":false}");done=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");mc.stop();}
 }catch(Exception e){Files.writeString(root.resolve("failure.json"),new Gson().toJson(Map.of("error",e.toString(),"phase",phase,"probe",probe==null?new JsonObject():probe)));done=true;mc.stop();}}
 private AboutUiSmokeClient(){}
}
