package dev.mineagent.runtime.neoforge.client.webui;
import com.google.gson.*;import net.minecraft.client.Minecraft;
import dev.mineagent.runtime.neoforge.ui.ServerBuildingFiles;
import net.neoforged.bus.api.SubscribeEvent;import net.neoforged.fml.common.EventBusSubscriber;
import java.nio.file.*;import java.io.*;import java.net.*;import java.net.http.*;import java.util.*;import java.util.concurrent.*;import java.util.concurrent.atomic.*;

/** Native selectors are only launched from the trusted F2 shell. File bytes use authenticated :25510 HTTP. */
@EventBusSubscriber(modid="mineagent_runtime",value=net.neoforged.api.distmarker.Dist.CLIENT)
public final class BuildingFilesClient {
    private static final ExecutorService IO=Executors.newSingleThreadExecutor(r->{var t=new Thread(r,"mineagent-file-picker-transfer");t.setDaemon(true);return t;});
    private static final HttpClient HTTP=HttpClient.newBuilder().connectTimeout(java.time.Duration.ofSeconds(5)).followRedirects(HttpClient.Redirect.NEVER).build();
    private static volatile String token="",url="",status="",error="";private static volatile long sent,total,sessionUntil;private static volatile boolean busy;private static Object connection;private static UUID openAgent;private static String activeAgent="";private static final AtomicBoolean cancelled=new AtomicBoolean();
    public static void requestOpen(String agent){var mc=Minecraft.getInstance();if(mc.getSingleplayerServer()==null||mc.player==null)return;openAgent=UUID.fromString(agent);activeAgent=agent;connection=mc.getConnection();WebGuiHostAdapter.INSTANCE.open();}
    @SubscribeEvent public static void tick(net.neoforged.neoforge.client.event.ClientTickEvent.Post e){var mc=Minecraft.getInstance();if(connection!=null&&connection!=mc.getConnection()){token="";url="";connection=null;openAgent=null;activeAgent="";cancelled.set(true);}if(openAgent!=null&&WebGuiHostAdapter.INSTANCE.ready()&&UiClientSessions.current()!=null){var agent=openAgent;openAgent=null;WebGuiHostAdapter.INSTANCE.emit("buildingFilesOpen",Map.of("agentId",agent.toString()));}}
    private static CompletableFuture<Void> bootstrap(){var mc=Minecraft.getInstance();var server=mc.getSingleplayerServer();if(server==null||mc.player==null)return CompletableFuture.failedFuture(new IllegalStateException("BUILDING_LOCAL_OWNER_REQUIRED"));UUID owner=mc.player.getUUID();Object expected=mc.getConnection();if(connection==expected&&!token.isEmpty()&&System.currentTimeMillis()<sessionUntil)return CompletableFuture.completedFuture(null);connection=expected;return server.submit(()->server.getPlayerList().getPlayer(owner)).thenCompose(ServerBuildingFiles::bootstrap).thenAccept(v->{if(Minecraft.getInstance().getConnection()!=expected)throw new IllegalStateException("BUILDING_CONTEXT_CHANGED");url=v.get("url").toString();token=v.get("token").toString();sessionUntil=System.currentTimeMillis()+3300000;});}
    public static CompletableFuture<Map<String,Object>> handle(JsonObject a){String kind=a.get("kind").getAsString();if(kind.equals("status"))return CompletableFuture.completedFuture(Map.of("busy",busy,"status",status,"error",error,"sent",sent,"total",total));if(kind.equals("cancel")){cancelled.set(true);return CompletableFuture.completedFuture(Map.of("status","CANCELLING"));}
        if(!Set.of("list","upload","world","download","select").contains(kind))return CompletableFuture.failedFuture(new IllegalArgumentException("BUILDING_UI_ACTION"));String query=a.has("query")?a.get("query").getAsString():"";int offset=a.has("offset")?a.get("offset").getAsInt():0;String id=a.has("fileId")?a.get("fileId").getAsString():"";if(a.has("agentId")){String agent=a.get("agentId").getAsString();if(!agent.isBlank())UUID.fromString(agent);activeAgent=agent;}
        if(kind.equals("select"))return select(id);
        if(kind.equals("list"))return bootstrap().thenApplyAsync(v->{try{return map(json("/list",Map.of("query",query,"offset",offset)));}catch(Exception e){throw new CompletionException(e);}},IO);
        if(busy)return CompletableFuture.failedFuture(new IllegalStateException("BUILDING_TRANSFER_BUSY"));busy=true;cancelled.set(false);sent=0;total=0;error="";status="选择文件…";
        bootstrap().thenRunAsync(()->{try{if(kind.equals("download"))download(id);else chooseUpload(kind.equals("world"));if(!cancelled.get())status="完成";}catch(Exception e){error=ServerBuildingFiles.error(e);status="未完成";}finally{busy=false;}},IO).exceptionally(e->{error=ServerBuildingFiles.error(e);status="未完成";busy=false;return null;});return CompletableFuture.completedFuture(Map.of("status","STARTED"));
    }
    private static Map<String,Object> map(JsonElement n){return new Gson().fromJson(n,new com.google.gson.reflect.TypeToken<Map<String,Object>>(){}.getType());}
    private static JsonObject json(String path,Object body)throws Exception{var request=HttpRequest.newBuilder(URI.create(url+path)).timeout(java.time.Duration.ofMinutes(10)).header("Authorization","Bearer "+token).header("Content-Type","application/json").POST(HttpRequest.BodyPublishers.ofString(new Gson().toJson(body))).build();var response=HTTP.send(request,HttpResponse.BodyHandlers.ofString());JsonObject value=JsonParser.parseString(response.body()).getAsJsonObject();if(response.statusCode()!=200)throw new IllegalStateException(value.get("error").getAsString());return value;}
    private static void check(){if(cancelled.get())throw new IllegalStateException("BUILDING_CANCELLED");}
    private static void chooseUpload(boolean world)throws Exception{
        if(dev.mineagent.runtime.neoforge.ui.BuildingImportSmokeServer.active()&&!world){Path fixture=Minecraft.getInstance().gameDirectory.toPath().resolve("fixture-house.litematic");Files.copy(Minecraft.getInstance().gameDirectory.toPath().resolve("runtime-item-source.json"),fixture,StandardCopyOption.REPLACE_EXISTING);BuildingImportSmokeClient.fixturePicker=true;uploadPath(fixture,false);return;}
        String selected;if(world)selected=org.lwjgl.util.tinyfd.TinyFileDialogs.tinyfd_selectFolderDialog("选择 Java 世界文件夹（包含 level.dat）",(CharSequence)null);else try(var stack=org.lwjgl.system.MemoryStack.stackPush()){var patterns=stack.mallocPointer(5);for(String s:List.of("*.litematic","*.nbt","*.schem","*.schematic","*.zip"))patterns.put(stack.UTF8(s));patterns.flip();selected=org.lwjgl.util.tinyfd.TinyFileDialogs.tinyfd_openFileDialog("选择建筑文件",(CharSequence)null,patterns,"Minecraft 建筑文件",true);}
        if(selected==null){cancelled.set(true);status="已取消选择";return;}List<Path> paths=Arrays.stream(selected.split("\\|")).map(Path::of).toList();for(Path path:paths){check();uploadPath(path,world);}
    }
    /** Also used by isolated Native acceptance, with a fixture-selected copy rather than OS input injection. */
    static void uploadPath(Path selected,boolean world)throws Exception{
        if(Files.isSymbolicLink(selected))throw new IllegalArgumentException("BUILDING_SELECTED_LINK");List<Path> files;
        if(world){if(!Files.isRegularFile(selected.resolve("level.dat"),LinkOption.NOFOLLOW_LINKS))throw new IllegalArgumentException("BUILDING_WORLD_LEVEL_REQUIRED");try(var walk=Files.walk(selected)){files=walk.filter(f->Files.isRegularFile(f,LinkOption.NOFOLLOW_LINKS)&&!Files.isSymbolicLink(f)).filter(f->{String rel=selected.relativize(f).toString().replace('\\','/');return rel.equals("level.dat")||rel.matches("(?:.*/)?region/r\\.-?[0-9]+\\.-?[0-9]+\\.mca");}).sorted().toList();}}else files=List.of(selected);
        for(var f:files)total+=Files.size(f);String upload=json("/begin",Map.of("name",selected.getFileName().toString(),"kind",world?"WORLD":"FILE")).get("upload").getAsString();boolean complete=false;
        try{for(var f:files){check();String relative=world?selected.relativize(f).toString().replace('\\','/'):f.getFileName().toString();String part=json("/file",Map.of("upload",upload,"path",relative,"bytes",Files.size(f))).get("part").getAsString();status="上传 "+f.getFileName();try(var in=Files.newInputStream(f,LinkOption.NOFOLLOW_LINKS)){byte[] buffer=new byte[1024*1024];long offset=0;for(int n;(n=in.read(buffer))!=-1;){check();var response=HTTP.send(HttpRequest.newBuilder(URI.create(url+"/chunk/"+upload+"/"+part+"/"+offset)).timeout(java.time.Duration.ofSeconds(30)).header("Authorization","Bearer "+token).PUT(HttpRequest.BodyPublishers.ofByteArray(buffer,0,n)).build(),HttpResponse.BodyHandlers.ofString());if(response.statusCode()!=200)throw new IllegalStateException(JsonParser.parseString(response.body()).getAsJsonObject().get("error").getAsString());long next=JsonParser.parseString(response.body()).getAsJsonObject().get("offset").getAsLong();if(next!=offset+n)throw new IllegalStateException("BUILDING_UPLOAD_RECEIPT");offset=next;sent+=n;}}}check();json("/finish",Map.of("upload",upload));complete=true;}finally{if(!complete)try{json("/cancel",Map.of("upload",upload));}catch(Exception ignored){}}
    }
    private static void download(String id)throws Exception{UUID.fromString(id);var meta=HTTP.send(HttpRequest.newBuilder(URI.create(url+"/asset/"+id)).header("Authorization","Bearer "+token).GET().build(),HttpResponse.BodyHandlers.ofString());if(meta.statusCode()!=200)throw new IllegalStateException("BUILDING_FILE_NOT_FOUND");var file=JsonParser.parseString(meta.body()).getAsJsonObject();String name=file.get("name").getAsString()+(file.get("kind").getAsString().equals("WORLD")?".zip":"");
        String chosen=dev.mineagent.runtime.neoforge.ui.BuildingImportSmokeServer.zero()?Minecraft.getInstance().gameDirectory.toPath().resolve("building-import-smoke/downloaded-house.litematic").toString():org.lwjgl.util.tinyfd.TinyFileDialogs.tinyfd_saveFileDialog("保存建筑文件",name,null,(CharSequence)null);if(chosen==null){cancelled.set(true);status="已取消保存";return;}Path target=Path.of(chosen);if(Files.exists(target,LinkOption.NOFOLLOW_LINKS))throw new IllegalArgumentException("BUILDING_SAVE_CHOOSE_NEW_NAME");status="下载…";
        var response=HTTP.send(HttpRequest.newBuilder(URI.create(url+"/download/"+id)).timeout(java.time.Duration.ofMinutes(10)).header("Authorization","Bearer "+token).GET().build(),HttpResponse.BodyHandlers.ofInputStream());if(response.statusCode()!=200){response.body().close();throw new IllegalStateException("BUILDING_DOWNLOAD_FAILED");}Path temp=Files.createTempFile(target.toAbsolutePath().getParent(),".mineagent-download-",".part");boolean saved=false;try(var in=response.body();var out=Files.newOutputStream(temp)){byte[] b=new byte[65536];for(int n;(n=in.read(b))!=-1;){check();out.write(b,0,n);sent+=n;if(sent>dev.mineagent.runtime.core.building.BuildingFileStore.MAX_ASSET_BYTES+16*1024*1024L)throw new IllegalStateException("BUILDING_DOWNLOAD_SIZE");}}catch(Exception e){Files.deleteIfExists(temp);throw e;}try{Files.move(temp,target,StandardCopyOption.ATOMIC_MOVE);saved=true;}finally{if(!saved)Files.deleteIfExists(temp);}}
    private static CompletableFuture<Map<String,Object>> select(String id){UUID file=UUID.fromString(id);var mc=Minecraft.getInstance();var s=mc.getSingleplayerServer();if(s==null||mc.player==null)return CompletableFuture.failedFuture(new IllegalArgumentException("BUILDING_LOCAL_OWNER_REQUIRED"));UUID owner=mc.player.getUUID(),agent=activeAgent.isBlank()?null:UUID.fromString(activeAgent);return s.submit(()->s.getPlayerList().getPlayer(owner)).thenCompose(p->ServerBuildingFiles.selected(p,agent,file));}
    private BuildingFilesClient(){}
}
