package dev.mineagent.runtime.neoforge.client.webui;
import com.google.gson.*;import dev.mineagent.runtime.neoforge.ui.BuildingImportSmokeServer;import dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen;import dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox;import net.minecraft.client.Minecraft;import java.nio.file.*;import java.util.*;
public final class BuildingImportSmokeClient {
 private static int ticks,phase,wait;private static JsonObject probe;private static boolean done,downloadClicked,downloadVerified;public static volatile boolean fixturePicker;
 public static void accept(JsonObject p){probe=p;}
 private static void script(String code){var h=WebGuiHostAdapter.INSTANCE;h.browser().executeJavaScript("(()=>{"+code+"})();",h.browser().getURL(),0);}
 public static void tick()throws Exception{if(done)return;var mc=Minecraft.getInstance();ticks++;Path root=Files.createDirectories(mc.gameDirectory.toPath().resolve("building-import-smoke"));try{if(!BuildingImportSmokeServer.failure.isEmpty())throw new IllegalStateException(BuildingImportSmokeServer.failure);if(ticks>36000)throw new IllegalStateException("BUILDING_SMOKE_TIMEOUT_"+phase);if(mc.player==null||!BuildingImportSmokeServer.ready)return;
  if(phase==0){String fp=PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","");if(fp.isEmpty()||new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fp)!=dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){if(mc.screen instanceof ControlCenterScreen s)for(var child:List.copyOf(s.children()))if(child instanceof net.minecraft.client.gui.components.Button b&&b.active&&b.getMessage().getString().contains("信任此服务器"))b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));return;}if(++wait==1)mc.player.connection.sendCommand("ai accept");if(wait<40)return;BuildingImportSmokeServer.clientReady=true;mc.setScreen(null);if(BuildingImportSmokeServer.zero()){mc.player.connection.sendCommand("ai files "+BuildingImportSmokeServer.agent);phase=2;return;}mc.player.connection.sendChat(BuildingImportSmokeServer.searchOnly()?"@建筑助手 联网查找好看的中世纪小屋投影或schematic，读取具体作品来源，给我实际作品链接。不要放置建筑，不上传文件。若有公开直链可只下载并识别；没有就说明，别伪造下载。":"@建筑助手 先上网搜一下好看的中世纪小屋获取参考来源，然后请求我上传已准备的投影文件。收到后识别并把文件里的建筑放在(4,111,4)，不照图片猜造。接受blocks_only：只恢复方块状态，不还原实体/箱子物品等NBT。要实际应用并检查，不要只提交计划。不要改玩家站的位置。");phase=1;}
  if(BuildingImportSmokeServer.searchOnly()&&BuildingImportSmokeServer.complete&&phase<5)phase=5;
  if(phase==1&&BuildingImportSmokeServer.waiting){mc.player.connection.sendCommand("ai files "+BuildingImportSmokeServer.agent);phase=2;}
  var host=WebGuiHostAdapter.INSTANCE;if(phase>=2&&host.ready()&&ticks%10==0)script("window.mineagentQuery({request:JSON.stringify({channel:'conversationAgentProbe',fileWindow:!!document.querySelector('[data-view-id=runtime-building-files] [data-file-rows]'),count:document.querySelectorAll('[data-view-id=runtime-building-files] [data-file-id]').length,status:document.querySelector('[data-file-status]')?.textContent??''}),persistent:false,onSuccess(){},onFailure(){}});");
  if(phase==2&&probe!=null&&probe.get("fileWindow").getAsBoolean()){script("[...document.querySelectorAll('[data-view-id=runtime-building-files] button')].find(b=>b.textContent==='上传文件').click();");phase=3;}
  if(phase==3&&BuildingImportSmokeServer.zero()&&probe!=null&&probe.get("count").getAsInt()>0){if(!downloadClicked){downloadClicked=true;script("[...document.querySelectorAll('[data-view-id=runtime-building-files] button')].find(b=>b.textContent==='下载').click();");}Path target=root.resolve("downloaded-house.litematic");if(!Files.exists(target))return;if(Files.mismatch(target,mc.gameDirectory.toPath().resolve("runtime-item-source.json"))!=-1)throw new IllegalStateException("DOWNLOAD_BYTES_CHANGED");downloadVerified=true;}
  if(phase==3&&probe!=null&&probe.get("count").getAsInt()>0){Files.writeString(root.resolve("ui.json"),probe.toString());script("document.querySelector('[data-view-id=runtime-building-files] [data-file-id]').click();");phase=4;wait=0;}
  if(phase==4&&++wait==20){net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),img->{try(img){img.writeToFile(root.resolve("f2-upload.png"));}catch(Exception e){BuildingImportSmokeServer.failure=e.toString();}});host.hideWorkspace();phase=5;}
  if(phase==5&&BuildingImportSmokeServer.complete){if(!fixturePicker&&!BuildingImportSmokeServer.searchOnly())throw new IllegalStateException("FIXTURE_PICKER_NOT_RECORDED");phase=6;wait=0;mc.player.setYRot(-65);mc.player.setXRot(-12);}
  if(phase==6&&++wait>30){done=true;net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),img->{try(img){img.writeToFile(root.resolve("native-house.png"));Files.writeString(root.resolve("client.json"),new Gson().toJson(Map.of("status",BuildingImportSmokeServer.searchOnly()?"REAL_BUILDING_SEARCH_CLIENT_COMPLETE":BuildingImportSmokeServer.zero()?"F2_UPLOAD_DOWNLOAD_ZERO_MODEL_VERIFIED":"F2_HTTP_25510_UPLOAD_AND_NATIVE_BUILD_VERIFIED","fixtureFilePicker",fixturePicker,"downloadVerified",downloadVerified,"osInputInjected",false)));dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");}catch(Exception e){try{Files.writeString(root.resolve("failure.txt"),e.toString());}catch(Exception ignored){}}finally{dev.mineagent.runtime.neoforge.client.cinematic.CinematicCaptureClient.finish();}});}
 }catch(Exception e){done=true;Files.writeString(root.resolve("client-failure.json"),new Gson().toJson(Map.of("error",e.toString(),"phase",phase,"probe",probe==null?new JsonObject():probe)));dev.mineagent.runtime.neoforge.client.cinematic.CinematicCaptureClient.finish();}}
 private BuildingImportSmokeClient(){}
}
