package dev.mineagent.runtime.neoforge.client.webui;

import dev.mineagent.runtime.api.packages.ClientRuntimeHost;
import dev.mineagent.runtime.api.packages.ClientPackageBridge;
import dev.mineagent.runtime.api.ui.UiProtocol.*;
import dev.mineagent.runtime.client.scripts.LocalClientScriptStore;
import dev.mineagent.runtime.client.trust.ServerTrustStore;
import dev.mineagent.runtime.client.webui.PackagePreviewTransfer;
import dev.mineagent.runtime.core.packages.*;
import dev.mineagent.runtime.neoforge.content.ManagedClientResourcePackGuard;
import dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox;
import dev.mineagent.runtime.scripting.ManagedScriptRuntime;
import dev.mineagent.runtime.scripting.javaext.ClientJavaExtensionManager;
import net.minecraft.client.Minecraft;
import net.minecraft.network.chat.Component;

import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.BooleanSupplier;

/** Signed CLIENT Rhino/Java sources share download/consent bookkeeping but execute in separate typed runtimes. */
public final class ClientScriptPackages {
    private static final ExecutorService IO=Executors.newVirtualThreadPerTaskExecutor();
    private static final ManagedScriptRuntime SCRIPTS=new ManagedScriptRuntime();private static final ClientJavaExtensionManager JAVA=new ClientJavaExtensionManager();private static final Map<String,Binding> LIVE=new LinkedHashMap<>();private static final Map<String,String> STATUS=new HashMap<>();private static final Map<String,ClientJavaCompiler.Built> BUILDS=new HashMap<>();private static final Map<UUID,ClientDependencyGraph> RESERVATIONS=new LinkedHashMap<>();private static Map<UUID,List<UUID>> CONSUMER_INDEX=Map.of();
    private static final Set<Download> downloads=ConcurrentHashMap.newKeySet();private static volatile Download download;private static String downloadOutcome="";private static long downloadGeneration,tick;private static LocalClientScriptStore.Job active;private static Pending finish;private static final Set<UUID> DELIVERY_REPORTS=new HashSet<>();
    private record Pending(LocalClientScriptStore.Job job,boolean success,String code){}
    private record Resolved(dev.mineagent.runtime.api.packages.RuntimePackage manifest,byte[] bundle,String bundleHash,String entry,Map<String,String> sources,boolean javaSource){public Resolved{bundle=bundle.clone();sources=Map.copyOf(sources);}@Override public byte[] bundle(){return bundle.clone();}}
    private record DependencyContext(ScriptDependencyGraph script,JavaDependencyGraph javaGraph,ClientDependencyGraph mixed,List<java.nio.file.Path> artifacts,Map<String,UUID> owners,Map<UUID,Binding> direct){public DependencyContext{artifacts=List.copyOf(artifacts);owners=Map.copyOf(owners);direct=Map.copyOf(direct);}}
    private record Prepared(Resolved resolved,ClientJavaCompiler.Built javaBuild,String sourceHash,String runtimeSourceHash,DependencyContext dependencies){}
    private static final class Binding {
        final LocalClientScriptStore.Asset asset;final Object connection;final String environment;final boolean javaSource;final Host host;final String sourceHash,runtimeSourceHash;final DependencyContext dependencies;final ClientJavaCompiler.Built javaBuild;final List<Runnable> callbacks=new ArrayList<>();final List<AutoCloseable> resources=new ArrayList<>();boolean enabled=true,current=true;
        Binding(LocalClientScriptStore.Asset asset,Object connection,String environment,boolean javaSource,String sourceHash,String runtimeSourceHash,DependencyContext dependencies,ClientJavaCompiler.Built javaBuild){this.asset=asset;this.connection=connection;this.environment=environment;this.javaSource=javaSource;this.sourceHash=sourceHash;this.runtimeSourceHash=runtimeSourceHash;this.dependencies=dependencies;this.javaBuild=javaBuild;host=new Host(this);}
        boolean authority(){return enabled&&current&&connection==mc().getConnection()&&mc().player!=null&&mc().level!=null;}
        void callbacks(){if(!authority())return;for(var callback:List.copyOf(callbacks)){if(!authority())return;callback.run();}}
        void closeResources()throws Exception{Exception first=null;for(var resource:List.copyOf(resources).reversed())try{resource.close();}catch(Exception|LinkageError failure){if(first==null)first=failure instanceof Exception e?e:new IllegalStateException("CLIENT_CODE_CLEANUP_UNKNOWN",failure);}resources.clear();callbacks.clear();if(first!=null)throw first;}
    }
    public static final class Host implements ClientRuntimeHost {
        private final Binding binding;private Host(Binding value){binding=value;}private void require(){if(!binding.authority())throw new SecurityException("CLIENT_CODE_AUTHORITY_CHANGED");}
        @Override public Minecraft minecraft(){require();return mc();}@Override public net.minecraft.client.player.LocalPlayer player(){require();return mc().player;}@Override public long tick(){require();return tick;}@Override public String packageId(){return binding.asset.manifest().packageId().toString();}
        @Override public void status(String value){require();validateStatus(value);STATUS.put(binding.asset.filename(),value);}@Override public String status(){require();return STATUS.getOrDefault(binding.asset.filename(),"");}
        @Override public void message(String value){require();if(value==null||value.isBlank()||value.length()>512||value.chars().anyMatch(c->c=='\r'||c=='\n'))throw new IllegalArgumentException("CLIENT_CODE_MESSAGE");mc().player.sendSystemMessage(Component.literal(value));}
        @Override public AutoCloseable onTick(Runnable callback){require();Objects.requireNonNull(callback);if(binding.callbacks.size()>=128||binding.resources.size()>=256)throw new IllegalStateException("CLIENT_CODE_CALLBACK_LIMIT");var open=new AtomicBoolean(true);binding.callbacks.add(callback);AutoCloseable handle=()->{if(open.compareAndSet(true,false))binding.callbacks.remove(callback);};binding.resources.add(handle);return handle;}
        @Override public AutoCloseable cleanupStatus(String value){require();validateStatus(value);if(binding.resources.size()>=256)throw new IllegalStateException("CLIENT_CODE_RESOURCE_LIMIT");var open=new AtomicBoolean(true);AutoCloseable handle=()->{if(open.compareAndSet(true,false))STATUS.put(binding.asset.filename(),value);};binding.resources.add(handle);return handle;}
        private static void validateStatus(String value){if(value==null||value.length()>256||value.chars().anyMatch(Character::isISOControl))throw new IllegalArgumentException("CLIENT_CODE_STATUS");}
    }
    private static final class Download {
        final Session session;final Object connection;final UUID delivery,id;final long revision;final String canonical,server,fingerprint;final boolean javaSource;final CompletableFuture<Map<String,Object>> future=new CompletableFuture<>();final long expires=System.currentTimeMillis()+120000;String transfer,transferHash;PackagePreviewTransfer.Assembler bytes;
        Download(Session session,UUID delivery,UUID id,long revision,String canonical,boolean javaSource)throws Exception{this.session=session;connection=mc().getConnection();this.delivery=delivery;this.id=id;this.revision=revision;this.canonical=canonical;this.javaSource=javaSource;server=serverId();fingerprint=trust().trustedFingerprint(server);if(!fingerprint.equalsIgnoreCase(PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","")))throw new IllegalStateException("CLIENT_CODE_TRUST_CHANGED");}
    }
    private ClientScriptPackages(){}
    private static Minecraft mc(){return Minecraft.getInstance();}private static LocalClientScriptStore store()throws Exception{return LocalClientScriptStore.get(mc().gameDirectory.toPath());}private static ServerTrustStore trust()throws Exception{return new ServerTrustStore(mc().gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties"));}private static String serverId(){return mc().getCurrentServer()==null?"local-integrated":mc().getCurrentServer().ip;}private static void thread(){if(!mc().isSameThread())throw new IllegalStateException("CLIENT_CODE_CLIENT_THREAD");}private static boolean javaSource(LocalClientScriptStore.Asset asset){return ClientJavaPlan.managedName(asset.filename());}
    public static BooleanSupplier webScope(){Session s=UiClientSessions.current();Object c=mc().getConnection();if(s==null||s.binding().actorKind()!=ActorKind.PLAYER||!s.binding().viewId().equals("runtime-shell")||!s.binding().entryPath().equals("trusted/shell")||!s.binding().ownerPackageId().equals(dev.mineagent.runtime.neoforge.ui.ServerUiRuntime.TRUSTED_SHELL_PACKAGE)||!s.binding().actorId().equals(s.binding().viewerPlayerId())||s.binding().preview()||s.binding().taskId()!=null)throw new SecurityException("CLIENT_CODE_TRUSTED_SHELL_REQUIRED");return ()->UiClientSessions.current()==s&&mc().getConnection()==c&&WebGuiHostAdapter.INSTANCE.ready();}
    public static Map<String,Object> startDownload(UUID id,long revision,String canonical,boolean javaSource){thread();long generation=++downloadGeneration;downloadOutcome="DOWNLOADING";var result=download(id,revision,canonical,javaSource);result.whenComplete((value,error)->mc().execute(()->{if(error!=null)dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.warn("CLIENT code download could not start code={} type={}",code(error),error.getClass().getSimpleName(),error);if(generation==downloadGeneration)downloadOutcome=error==null?Objects.toString(value.get("code"),"CLIENT_CODE_FAILED"):code(error);}));if(result.isDone())try{return result.join();}catch(CompletionException failure){return Map.of("code",code(failure));}return Map.of("code","ACCEPTED","state","DOWNLOADING");}
    public static CompletableFuture<Map<String,Object>> download(UUID id,long revision,String canonical,boolean javaSource){return download(null,id,revision,canonical,javaSource);}
    public static Map<String,Object> startDeliveryDownload(UUID delivery,UUID id,long revision,String canonical,boolean javaSource){thread();long generation=++downloadGeneration;downloadOutcome="DOWNLOADING";var result=download(delivery,id,revision,canonical,javaSource);result.whenComplete((value,error)->mc().execute(()->{if(generation==downloadGeneration)downloadOutcome=error==null?Objects.toString(value.get("code"),"CLIENT_CODE_FAILED"):code(error);}));if(result.isDone())try{return result.join();}catch(CompletionException failure){return Map.of("code",code(failure));}return Map.of("code","ACCEPTED","state","DOWNLOADING");}
    private static CompletableFuture<Map<String,Object>> download(UUID delivery,UUID id,long revision,String canonical,boolean javaSource){thread();webScope();try{var d=new Download(UiClientSessions.current(),delivery,id,revision,canonical,javaSource);downloads.add(d);download=d;String action=delivery!=null?"delivery.codeAccept":javaSource?"package.clientJavaPrepare":"package.clientScriptPrepare";var arguments=new LinkedHashMap<String,String>();if(delivery!=null)arguments.put("deliveryId",delivery.toString());else{arguments.put("packageId",id.toString());arguments.put("packageRevision",Long.toString(revision));arguments.put("canonical",canonical);}UiClientSessions.command(action,arguments,UUID.randomUUID()).whenComplete((r,error)->{if(!current(d))return;try{if(error!=null||r.code()!=Code.ACCEPTED)throw new IllegalStateException(javaSource?"CLIENT_JAVA_DOWNLOAD_FAILED":"CLIENT_SCRIPT_DOWNLOAD_FAILED");var v=r.values();if(delivery!=null&&!delivery.toString().equals(v.get("deliveryId"))||!id.toString().equals(v.get("packageId"))||!Long.toString(revision).equals(v.get("packageRevision"))||delivery!=null&&!canonical.equals(v.get("canonicalSha256"))||delivery==null&&!canonical.equals(v.get("canonical"))||delivery!=null&&!v.get("language").equals(javaSource?"JAVA":"RHINO"))throw new IllegalStateException(javaSource?"CLIENT_JAVA_SOURCE_CHANGED":"CLIENT_SCRIPT_SOURCE_CHANGED");d.transfer=UUID.fromString(v.get("transferId")).toString();d.transferHash=v.get("sha256");d.bytes=new PackagePreviewTransfer.Assembler(Integer.parseInt(v.get("size")),d.transferHash,javaSource?ClientJavaPlan.MAX_BUNDLE:ClientScriptPlan.MAX_BUNDLE);next(d);}catch(Exception failure){fail(d,failure);}});return d.future;}catch(Exception failure){return CompletableFuture.failedFuture(failure);}}
    private static void removed(Download d){downloads.remove(d);if(download==d)download=downloads.stream().findFirst().orElse(null);}
    private static boolean current(Download d){if(!downloads.contains(d))return false;if(d.session!=UiClientSessions.current()||d.connection!=mc().getConnection()||System.currentTimeMillis()>=d.expires||!WebGuiHostAdapter.INSTANCE.ready()){fail(d,d.javaSource?"CLIENT_JAVA_DOWNLOAD_CONTEXT_CHANGED":"CLIENT_SCRIPT_DOWNLOAD_CONTEXT_CHANGED");return false;}return true;}
    private static void next(Download d){if(!current(d))return;if(d.bytes.offset()==d.bytes.size()){CompletableFuture.supplyAsync(()->decode(d),IO).whenComplete((resolved,error)->mc().execute(()->{if(!current(d))return;if(error!=null){fail(d,error);return;}CompletableFuture.supplyAsync(()->save(d,resolved),IO).whenComplete((asset,failure)->mc().execute(()->{if(!current(d))return;if(failure!=null){fail(d,failure);return;}release(d);removed(d);d.future.complete(Map.of("code",d.javaSource?"CLIENT_JAVA_DOWNLOADED_NOT_APPROVED":"CLIENT_SCRIPT_DOWNLOADED_NOT_APPROVED","filename",asset.filename(),"revision",asset.revision()));}));}));return;}int offset=d.bytes.offset();String action=d.delivery!=null?"delivery.codeChunk":d.javaSource?"package.clientJavaChunk":"package.clientScriptChunk";UiClientSessions.command(action,Map.of("transferId",d.transfer,"offset",Integer.toString(offset)),UUID.randomUUID()).whenComplete((r,error)->{if(!current(d))return;try{if(error!=null||r.code()!=Code.OBSERVED||!Integer.toString(offset).equals(r.values().get("offset")))throw new IllegalStateException(d.javaSource?"CLIENT_JAVA_DOWNLOAD_FAILED":"CLIENT_SCRIPT_DOWNLOAD_FAILED");d.bytes.append(offset,Base64.getDecoder().decode(r.values().get("bytes")));next(d);}catch(Exception failure){fail(d,failure);}});}
    private static Resolved decode(Download d){try{var t=trust();if(!t.trustedFingerprint(d.server).equals(d.fingerprint))throw new IllegalStateException("CLIENT_CODE_TRUST_CHANGED");byte[] body=d.bytes.finish();if(d.javaSource){var r=ClientJavaPlan.decode(body,d.id,d.revision,d.canonical,(value,sig)->t.verify(d.server,value,sig));return new Resolved(r.plan().manifest(),r.bundle(),r.bundleHash(),r.plan().entrypoint(),r.sources(),true);}var r=ClientScriptPlan.decode(body,d.id,d.revision,d.canonical,(value,sig)->t.verify(d.server,value,sig));return new Resolved(r.plan().manifest(),r.bundle(),r.bundleHash(),r.plan().entrypoint(),r.modules(),false);}catch(Exception failure){throw new CompletionException(failure);}}
    private static LocalClientScriptStore.Asset save(Download d,Resolved r){try{if(!downloads.contains(d))throw new IllegalStateException("CLIENT_CODE_DOWNLOAD_CONTEXT_CHANGED");var local=store();var asset=r.javaSource()?local.downloaded(d.server,d.fingerprint,new ClientJavaPlan.Resolved(ClientJavaPlan.inspect(r.manifest()),r.bundle(),r.bundleHash(),r.sources())):local.downloaded(d.server,d.fingerprint,new ClientScriptPlan.Resolved(ClientScriptPlan.inspect(r.manifest()),r.bundle(),r.bundleHash(),r.sources()));if(d.delivery!=null)local.bindDelivery(d.delivery,asset);return asset;}catch(Exception failure){throw new CompletionException(failure);}}
    private static void release(Download d){if(d.transfer!=null&&UiClientSessions.current()==d.session)UiClientSessions.command(d.delivery!=null?"delivery.codeRelease":d.javaSource?"package.clientJavaRelease":"package.clientScriptRelease",Map.of("transferId",d.transfer),UUID.randomUUID());}private static void fail(Download d,Throwable failure){dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.warn("CLIENT code download failed code={} type={}",code(failure),failure.getClass().getSimpleName(),failure);fail(d,code(failure));}private static void fail(Download d,String value){if(!downloads.contains(d))return;if(d.delivery!=null&&d.transferHash!=null&&d.transferHash.matches("[a-f0-9]{64}")&&UiClientSessions.current()==d.session){var args=Map.of("deliveryId",d.delivery.toString(),"packageId",d.id.toString(),"packageRevision",Long.toString(d.revision),"canonicalSha256",d.canonical,"language",d.javaSource?"JAVA":"RHINO","localState","FAILED","assetRevision","1","bundleHash",d.transferHash);UiClientSessions.command("delivery.codeState",args,UUID.nameUUIDFromBytes(("client-code-delivery-download-failed|"+d.delivery+"|"+value).getBytes(java.nio.charset.StandardCharsets.UTF_8)));}release(d);removed(d);d.future.complete(Map.of("code",value));}public static void cancelDownload(){thread();var d=download;if(d!=null)fail(d,d.javaSource?"CLIENT_JAVA_DOWNLOAD_CANCELLED":"CLIENT_SCRIPT_DOWNLOAD_CANCELLED");}
    private static String environment(){return ManagedClientResourcePackGuard.environment().fingerprint();}
    private static void trusted(LocalClientScriptStore.Asset asset)throws Exception{var t=trust();if(!t.trustedFingerprint(asset.serverId()).equals(asset.fingerprint()))throw new IllegalStateException("CLIENT_CODE_TRUST_CHANGED");String expected=javaSource(asset)?ClientJavaPlan.inspect(asset.manifest()).filename(LocalClientScriptStore.publisher(asset.serverId(),asset.fingerprint())):ClientScriptPlan.inspect(asset.manifest()).filename(LocalClientScriptStore.publisher(asset.serverId(),asset.fingerprint()));if(!expected.equals(asset.filename()))throw new IllegalStateException("CLIENT_CODE_IDENTITY");if(!RuntimePackageCanonicalizer.sha256(asset.manifest()).equals(asset.manifest().canonicalSha256())||!t.verify(asset.serverId(),asset.manifest().canonicalSha256().getBytes(java.nio.charset.StandardCharsets.US_ASCII),Base64.getDecoder().decode(asset.manifest().signature())))throw new IllegalStateException("CLIENT_CODE_SIGNATURE");var result=NativeCompatibilityPolicy.check(asset.manifest(),ManagedClientResourcePackGuard.environment(),"CLIENT");if(!result.allowed())throw new IllegalStateException(result.code());}
    private static boolean runtimeLoaded(Binding binding){return binding.javaSource?JAVA.isLoaded(binding.asset.manifest().packageId()):SCRIPTS.isLoaded(binding.asset.manifest().packageId());}
    private static List<UUID> consumers(Binding binding){return CONSUMER_INDEX.getOrDefault(binding.asset.manifest().packageId(),List.of());}
    private static Binding binding(UUID packageId){var matches=LIVE.values().stream().filter(b->b.asset.manifest().packageId().equals(packageId)&&runtimeLoaded(b)&&b.authority()).toList();if(matches.size()!=1)throw new IllegalStateException("CLIENT_CODE_DEPENDENCY_NOT_RUNNING");return matches.getFirst();}
    private static DependencyContext dependencies(LocalClientScriptStore.Asset root)throws Exception{
        boolean java=javaSource(root);var found=new LinkedHashMap<UUID,Binding>();collect(root.manifest().dependencies(),found,new HashSet<>(Set.of(root.manifest().packageId())),0);var mixedNodes=new ArrayList<ClientDependencyGraph.Node>();for(var b:found.values()){var p=b.asset.manifest();if(b.javaSource&&b.javaBuild==null)throw new IllegalStateException("CLIENT_JAVA_DEPENDENCY_BUILD_MISSING");mixedNodes.add(new ClientDependencyGraph.Node(p.packageId(),p.version(),p.revision(),p.canonicalSha256(),p.packageId(),b.asset.revision(),b.javaSource?ClientDependencyGraph.Language.JAVA:ClientDependencyGraph.Language.RHINO,b.sourceHash,b.javaSource?b.javaBuild.artifactHash():b.runtimeSourceHash,b.javaSource?b.javaBuild.className():ClientScriptPlan.inspect(p).entrypoint(),p.dependencies()));}var mixed=new ClientDependencyGraph(1,root.manifest().packageId(),root.manifest().dependencies(),mixedNodes);var sameRequired=same(root.manifest().dependencies(),found,java);var sameIds=new LinkedHashSet<UUID>();sameIds(sameRequired.keySet(),found,java,sameIds);
        ScriptDependencyGraph script=ScriptDependencyGraph.empty(root.manifest().packageId());JavaDependencyGraph javaGraph=JavaDependencyGraph.empty(root.manifest().packageId());var artifacts=new ArrayList<java.nio.file.Path>();var owners=new LinkedHashMap<String,UUID>();if(java){var nodes=new ArrayList<JavaDependencyGraph.Node>();for(var id:sameIds){var b=found.get(id);var p=b.asset.manifest();nodes.add(new JavaDependencyGraph.Node(p.packageId(),p.version(),p.revision(),p.canonicalSha256(),p.packageId(),b.asset.revision(),b.javaBuild.artifactHash(),b.sourceHash,b.javaBuild.className(),b.javaBuild.classpathHash(),same(p.dependencies(),found,true)));}javaGraph=new JavaDependencyGraph(1,root.manifest().packageId(),sameRequired,nodes);for(var node:javaGraph.nodes()){var b=found.get(node.packageId());artifacts.add(b.javaBuild.artifact());try(var jar=new java.util.jar.JarFile(b.javaBuild.artifact().toFile(),false)){var entries=jar.entries();while(entries.hasMoreElements()){String name=entries.nextElement().getName();if(!name.endsWith(".class")||name.equals("module-info.class")||name.startsWith("META-INF/"))continue;String className=name.substring(0,name.length()-6).replace('/','.');UUID old=owners.putIfAbsent(className,node.publication());if(old!=null&&!old.equals(node.publication()))throw new IllegalStateException("CLIENT_JAVA_DEPENDENCY_CLASS_AMBIGUOUS");}}}}
        else{var nodes=new ArrayList<ScriptDependencyGraph.Node>();for(var id:sameIds){var b=found.get(id);var p=b.asset.manifest();nodes.add(new ScriptDependencyGraph.Node(p.packageId(),p.version(),p.revision(),p.canonicalSha256(),p.packageId(),b.asset.revision(),b.runtimeSourceHash,ClientScriptPlan.inspect(p).entrypoint(),same(p.dependencies(),found,false)));}script=new ScriptDependencyGraph(1,root.manifest().packageId(),sameRequired,nodes);}var direct=new LinkedHashMap<UUID,Binding>();for(var id:root.manifest().dependencies().keySet())direct.put(id,found.get(id));return new DependencyContext(script,javaGraph,mixed,artifacts,owners,direct);
    }
    private static void collect(Map<UUID,String> edges,Map<UUID,Binding> found,Set<UUID> visiting,int depth){if(depth>32)throw new IllegalStateException("CLIENT_CODE_DEPENDENCY_DEPTH");for(var edge:edges.entrySet()){if(!visiting.add(edge.getKey()))throw new IllegalStateException("CLIENT_CODE_DEPENDENCY_CYCLE");var b=binding(edge.getKey());if(!b.asset.manifest().version().equals(edge.getValue()))throw new IllegalStateException("CLIENT_CODE_DEPENDENCY_VERSION");var prior=found.putIfAbsent(edge.getKey(),b);if(prior!=null&&prior!=b)throw new IllegalStateException("CLIENT_CODE_DEPENDENCY_CHANGED");if(prior==null)collect(b.asset.manifest().dependencies(),found,visiting,depth+1);visiting.remove(edge.getKey());}}
    private static Map<UUID,String> same(Map<UUID,String> edges,Map<UUID,Binding> found,boolean java){var result=new TreeMap<UUID,String>();for(var edge:edges.entrySet())if(found.get(edge.getKey()).javaSource==java)result.put(edge.getKey(),edge.getValue());return result;}
    private static void sameIds(Set<UUID> next,Map<UUID,Binding> found,boolean java,Set<UUID> result){for(var id:next)if(result.add(id))sameIds(same(found.get(id).asset.manifest().dependencies(),found,java).keySet(),found,java,result);}
    private static List<Map<String,Object>> dependencyView(LocalClientScriptStore.Asset asset){return asset.manifest().dependencies().entrySet().stream().sorted(Map.Entry.comparingByKey()).map(e->{var b=LIVE.values().stream().filter(v->v.asset.manifest().packageId().equals(e.getKey())&&runtimeLoaded(v)).findFirst().orElse(null);return Map.<String,Object>of("packageId",e.getKey(),"version",e.getValue(),"language",b==null?"UNKNOWN":b.javaSource?"JAVA":"RHINO","state",b==null?"NOT_RUNNING":b.asset.manifest().version().equals(e.getValue())?"RUNNING":"MISMATCH");}).toList();}
    private static void reserve(Binding binding){UUID root=binding.asset.manifest().packageId();var graph=binding.dependencies.mixed();if(!graph.root().equals(root))throw new IllegalStateException("CLIENT_DEPENDENCY_ROOT");var old=RESERVATIONS.get(root);if(old!=null&&!old.equals(graph))throw new IllegalStateException("CLIENT_CODE_DEPENDENCY_CHANGED");for(var node:graph.nodes()){binding(node.packageId());graph.requireEmbedded(node,RESERVATIONS.get(node.runtime()));}if(old==null){RESERVATIONS.put(root,graph);reindex();}}
    private static void releaseReservation(UUID root){RESERVATIONS.remove(root);reindex();}
    private static void reindex(){var index=new LinkedHashMap<UUID,ArrayList<UUID>>();RESERVATIONS.forEach((consumer,graph)->graph.scopes().forEach(scope->index.computeIfAbsent(scope,k->new ArrayList<>()).add(consumer)));var result=new LinkedHashMap<UUID,List<UUID>>();index.forEach((id,list)->result.put(id,list.stream().sorted().toList()));CONSUMER_INDEX=Map.copyOf(result);}
    private static boolean attempted(Binding binding){UUID id=binding.asset.manifest().packageId();return binding.javaSource?JAVA.attempted(id):SCRIPTS.attempted(id);}
    private static ClientPackageBridge bridge(Binding caller){return (dependency,member,arguments)->{thread();if(!caller.authority())throw new SecurityException("CLIENT_CODE_AUTHORITY_CHANGED");var target=caller.dependencies.direct().get(dependency);if(target==null)throw new SecurityException("CLIENT_PACKAGE_DEPENDENCY_UNDECLARED");if(!target.authority()||!runtimeLoaded(target))throw new IllegalStateException("CLIENT_CODE_DEPENDENCY_NOT_RUNNING");Object result=target.javaSource?JAVA.call(dependency,member,arguments):SCRIPTS.callExternal(dependency,member,arguments);if(!caller.authority()||!target.authority()||!runtimeLoaded(target))throw new IllegalStateException("CLIENT_CODE_DEPENDENCY_CHANGED");return result;};}
    private static List<Map<String,Object>> deliveryView(String filename)throws Exception{return store().codeDeliveries().stream().filter(v->v.filename().equals(filename)).map(v->Map.<String,Object>of("deliveryId",v.deliveryId(),"reportedState",v.reportedState(),"reportedAssetRevision",v.reportedAssetRevision())).toList();}
    private static boolean deliveryStartReady(LocalClientScriptStore.Asset asset)throws Exception{var links=store().codeDeliveries().stream().filter(v->v.filename().equals(asset.filename())).toList();return links.isEmpty()||links.stream().allMatch(v->v.reportedAssetRevision()==asset.revision()&&Set.of("DOWNLOADED","STOPPED","FAILED").contains(v.reportedState()));}
    private static String readiness(LocalClientScriptStore.Asset asset){if(asset.state().equals("RUNNING")&&loaded(asset.filename()))return "RUNNING";if(asset.state().equals("DOWNLOADED"))return "DOWNLOADED";if(asset.state().equals("STOPPED"))return "STOPPED";if(Set.of("FAILED","UNKNOWN").contains(asset.state()))return "FAILED";return "";}
    private static void reportDeliveries(){if(UiClientSessions.current()==null)return;try{webScope();var local=store();String server=serverId(),fingerprint=trust().trustedFingerprint(server);for(var link:local.codeDeliveries()){if(DELIVERY_REPORTS.contains(link.deliveryId())||!link.serverId().equals(server)||!link.fingerprint().equals(fingerprint))continue;LocalClientScriptStore.Asset asset;try{asset=local.get(link.filename());}catch(Exception missing){continue;}String state=readiness(asset);if(state.isEmpty()||link.reportedAssetRevision()==asset.revision()&&link.reportedState().equals(state))continue;DELIVERY_REPORTS.add(link.deliveryId());long linkRevision=link.revision(),assetRevision=asset.revision();var args=Map.of("deliveryId",link.deliveryId().toString(),"packageId",link.packageId().toString(),"packageRevision",Long.toString(link.packageRevision()),"canonicalSha256",link.canonical(),"language",link.language(),"localState",state,"assetRevision",Long.toString(assetRevision),"bundleHash",asset.bundleHash());UUID operation=UUID.nameUUIDFromBytes(("client-code-delivery-state|"+link.deliveryId()+"|"+assetRevision+"|"+state).getBytes(java.nio.charset.StandardCharsets.UTF_8));UiClientSessions.command("delivery.codeState",args,operation).whenComplete((receipt,error)->mc().execute(()->{DELIVERY_REPORTS.remove(link.deliveryId());try{if(error==null&&receipt.code()==Code.APPLIED)local.reported(link.deliveryId(),linkRevision,assetRevision,state);}catch(Exception ignored){}}));}}catch(Exception ignored){}}
    public static Map<String,Object> read(int offset)throws Exception{thread();if(offset<0||offset>4096)throw new IllegalArgumentException("CLIENT_CODE_PAGE");var local=store();var all=local.list();var values=new ArrayList<Object>();for(var a:all.stream().skip(offset).limit(8).toList()){String error="";try{trusted(a);}catch(Exception failure){error=code(failure);}String dependencyError="";try{dependencies(a);}catch(Exception failure){dependencyError=code(failure);}var binding=LIVE.get(a.filename());boolean loaded=binding!=null&&runtimeLoaded(binding),deliveryReady=deliveryStartReady(a);var consumerIds=binding==null?List.<UUID>of():consumers(binding);var job=local.latest(a.filename());values.add(Map.ofEntries(Map.entry("filename",a.filename()),Map.entry("name",a.manifest().name()),Map.entry("language",javaSource(a)?"JAVA":"RHINO"),Map.entry("packageId",a.manifest().packageId()),Map.entry("canonical",a.manifest().canonicalSha256()),Map.entry("fingerprint",a.fingerprint()),Map.entry("state",a.state()),Map.entry("code",a.code()),Map.entry("revision",a.revision()),Map.entry("loadedNow",loaded),Map.entry("runtimeStatus",STATUS.getOrDefault(a.filename(),"")),Map.entry("dependencies",dependencyView(a)),Map.entry("deliveries",deliveryView(a.filename())),Map.entry("dependencyError",dependencyError),Map.entry("consumers",consumerIds),Map.entry("build",build(a.filename())),Map.entry("error",error),Map.entry("canStart",active==null&&download==null&&!loaded&&deliveryReady&&Set.of("DOWNLOADED","STOPPED","FAILED").contains(a.state())&&error.isEmpty()&&dependencyError.isEmpty()&&mc().getConnection()!=null),Map.entry("canStop",active==null&&download==null&&loaded&&consumerIds.isEmpty()),Map.entry("job",job.<Object>map(j->Map.of("operation",j.input().operation(),"action",j.input().action(),"phase",j.phase(),"code",j.code(),"before",j.before(),"after",j.after(),"revision",j.revision())).orElse(Map.of()))));}return Map.ofEntries(Map.entry("items",values),Map.entry("offset",offset),Map.entry("nextOffset",offset+values.size()),Map.entry("more",offset+values.size()<all.size()),Map.entry("environment",environment()),Map.entry("busy",active!=null||download!=null),Map.entry("downloadOutcome",downloadOutcome),Map.entry("download",download==null?Map.of():Map.of("packageId",download.id,"language",download.javaSource?"JAVA":"RHINO","received",download.bytes==null?0:download.bytes.offset(),"total",download.bytes==null?0:download.bytes.size())));}
    public static Map<String,Object> change(UUID operation,String filename,String action,long expected,String expectedEnvironment,boolean confirmed,String actor,BooleanSupplier scope)throws Exception{
        thread();if(!confirmed||!scope.getAsBoolean())throw new SecurityException("CLIENT_CODE_LOCAL_CONSENT_REQUIRED");if(active!=null||download!=null)throw new IllegalStateException("CLIENT_CODE_BUSY");if(!environment().equals(expectedEnvironment))throw new IllegalStateException("CLIENT_CODE_CONTEXT_CHANGED");var local=store();var asset=local.get(filename);if(asset.revision()!=expected)throw new IllegalStateException("CLIENT_CODE_STALE");var input=new LocalClientScriptStore.Input(operation,filename,action,expected,expectedEnvironment,actor);var old=local.job(operation);if(old.isPresent()){if(!old.get().input().equals(input))throw new IllegalStateException("CLIENT_CODE_OPERATION_REUSED");return Map.of("code","ACCEPTED","job",old.get());}
        if(action.equals("START")){trusted(asset);if(LIVE.values().stream().anyMatch(b->b.asset.manifest().packageId().equals(asset.manifest().packageId())))throw new IllegalStateException("CLIENT_CODE_PRIOR_ACTIVE");var dependencyContext=dependencies(asset);var job=local.begin(input,"RUNNING");active=job;Object connection=mc().getConnection();var permit=new AtomicBoolean(true);CompletableFuture.supplyAsync(()->prepare(asset,local,dependencyContext,connection,permit),IO).whenComplete((prepared,error)->mc().execute(()->{if(active!=job){permit.set(false);return;}if(error!=null){complete(job,false,code(error));return;}try{if(!scope.getAsBoolean()||connection!=mc().getConnection()||!environment().equals(expectedEnvironment))throw new IllegalStateException("CLIENT_CODE_CONTEXT_CHANGED");trusted(asset);dependencies(asset);var dispatched=local.dispatch(job);active=dispatched;start(dispatched,asset,prepared,connection);complete(dispatched,true,prepared.resolved().javaSource()?"CLIENT_JAVA_STARTED":"CLIENT_SCRIPT_STARTED");}catch(Exception failure){complete(active,false,code(failure));}finally{permit.set(false);}}));}
        else{var binding=LIVE.get(filename);if(binding==null)throw new IllegalStateException("CLIENT_CODE_NOT_RUNNING");requireCanStop(binding);var job=local.begin(input,"STOPPED");active=local.dispatch(job);boolean java=javaSource(asset),success=stop(filename,"CLIENT_CODE_USER_STOP");complete(active,success,success?(java?"CLIENT_JAVA_STOPPED":"CLIENT_SCRIPT_STOPPED"):java?"CLIENT_JAVA_STOP_UNKNOWN":"CLIENT_SCRIPT_STOP_UNKNOWN");}
        return Map.of("code","ACCEPTED","job",active==null?local.job(operation).orElseThrow():active);
    }
    private static Prepared prepare(LocalClientScriptStore.Asset asset,LocalClientScriptStore local,DependencyContext dependencies,Object connection,AtomicBoolean permit){try{boolean java=javaSource(asset);byte[] body=java?ClientJavaPlan.read(local.cacheDirectory().resolve(asset.filename())):ClientScriptPlan.read(local.cacheDirectory().resolve(asset.filename()));if(!RuntimePackageCanonicalizer.sha256(body).equals(asset.bundleHash()))throw new IllegalStateException(java?"CLIENT_JAVA_BUNDLE_HASH":"CLIENT_SCRIPT_BUNDLE_HASH");var t=trust();Resolved resolved;if(java){var r=ClientJavaPlan.decode(body,asset.manifest().packageId(),asset.manifest().revision(),asset.manifest().canonicalSha256(),(value,sig)->t.verify(asset.serverId(),value,sig));resolved=new Resolved(r.plan().manifest(),r.bundle(),r.bundleHash(),r.plan().entrypoint(),r.sources(),true);}else{var r=ClientScriptPlan.decode(body,asset.manifest().packageId(),asset.manifest().revision(),asset.manifest().canonicalSha256(),(value,sig)->t.verify(asset.serverId(),value,sig));resolved=new Resolved(r.plan().manifest(),r.bundle(),r.bundleHash(),r.plan().entrypoint(),r.modules(),false);}var refs=new TreeMap<String,dev.mineagent.runtime.api.packages.CodeDraft.SourceRef>();for(var file:resolved.sources().entrySet())refs.put(file.getKey(),CodeDraftSources.ref(file.getValue()));String sourceHash=CodeDraftSources.fingerprint(resolved.entry(),refs,resolved.manifest().dependencies()),runtimeSourceHash=java?sourceHash:CodeDraftSources.fingerprint(resolved.entry(),refs,dependencies.script().required());var build=java?ClientJavaCompiler.compile(mc().gameDirectory.toPath(),new ClientJavaPlan.Resolved(ClientJavaPlan.inspect(resolved.manifest()),resolved.bundle(),resolved.bundleHash(),resolved.sources()),dependencies.artifacts(),resolved.manifest().dependencies(),dependencies.mixed().receiptHash(),()->permit.get()&&connection==mc().getConnection()):null;if(build!=null&&!build.sourceHash().equals(sourceHash))throw new IllegalStateException("CLIENT_JAVA_DEPENDENCY_SOURCE_CHANGED");return new Prepared(resolved,build,sourceHash,runtimeSourceHash,dependencies);}catch(Exception failure){throw new CompletionException(failure);}}
    private static void start(LocalClientScriptStore.Job job,LocalClientScriptStore.Asset asset,Prepared prepared,Object connection)throws Exception{var binding=new Binding(new LocalClientScriptStore.Asset(asset.filename(),asset.serverId(),asset.fingerprint(),asset.manifest(),asset.bundleHash(),job.input().environment(),"STARTING","",asset.revision()+1,true),connection,job.input().environment(),prepared.resolved().javaSource(),prepared.sourceHash(),prepared.runtimeSourceHash(),prepared.dependencies(),prepared.javaBuild());reserve(binding);LIVE.put(asset.filename(),binding);STATUS.put(asset.filename(),"");try{var bindings=Map.<String,Object>of("client",binding.host,"packages",bridge(binding));if(binding.javaSource){var build=Objects.requireNonNull(prepared.javaBuild());JAVA.load(asset.manifest().packageId(),build.artifact(),build.artifactHash(),build.className(),bindings,prepared.dependencies().javaGraph(),prepared.dependencies().owners());BUILDS.put(asset.filename(),build);}else{SCRIPTS.pin(asset.manifest().packageId(),prepared.dependencies().script());SCRIPTS.load(asset.manifest().packageId(),asset.manifest().revision(),prepared.resolved().sources(),prepared.resolved().entry(),bindings,binding::authority,tick,new ManagedScriptRuntime.Link(prepared.dependencies().script(),prepared.runtimeSourceHash()));}if(!binding.authority())throw new IllegalStateException("CLIENT_CODE_AUTHORITY_CHANGED");}catch(Exception|LinkageError failure){binding.enabled=false;LIVE.remove(asset.filename());try{if(binding.javaSource)JAVA.unload(asset.manifest().packageId());else{SCRIPTS.releaseBeforeLoad(asset.manifest().packageId());SCRIPTS.unload(asset.manifest().packageId());}}catch(Exception|LinkageError ignored){}if(!attempted(binding))releaseReservation(asset.manifest().packageId());try{binding.closeResources();}catch(Exception ignored){}throw failure;}}
    private static void requireCanStop(Binding binding){if(!consumers(binding).isEmpty())throw new IllegalStateException("CLIENT_CODE_DEPENDENCY_IN_USE");if(binding.javaSource)JAVA.requireCanUnload(binding.asset.manifest().packageId());else SCRIPTS.requireCanUnload(binding.asset.manifest().packageId());}
    private static boolean stop(String filename,String reason){var binding=LIVE.get(filename);if(binding==null)return false;requireCanStop(binding);LIVE.remove(filename);binding.enabled=false;if(!binding.javaSource)SCRIPTS.suspend(binding.asset.manifest().packageId());boolean invoked=false,clean=true;try{invoked=binding.javaSource?JAVA.unload(binding.asset.manifest().packageId()):SCRIPTS.unload(binding.asset.manifest().packageId());if(!invoked)STATUS.put(filename,reason+":NOT_LOADED");}catch(Exception|LinkageError failure){STATUS.put(filename,binding.javaSource?"CLIENT_JAVA_STOP_UNKNOWN":"CLIENT_SCRIPT_STOP_UNKNOWN");clean=false;}if(!attempted(binding))releaseReservation(binding.asset.manifest().packageId());try{binding.closeResources();}catch(Exception failure){STATUS.put(filename,binding.javaSource?"CLIENT_JAVA_STOP_UNKNOWN":"CLIENT_SCRIPT_STOP_UNKNOWN");clean=false;}return invoked&&clean;}
    private static void complete(LocalClientScriptStore.Job job,boolean success,String value){try{store().finish(job,success,value);active=null;finish=null;}catch(Exception failure){active=job;finish=new Pending(job,success,value);}}
    public static void tick(){thread();tick++;for(var d:List.copyOf(downloads))current(d);if(finish!=null){var pending=finish;complete(pending.job(),pending.success(),pending.code());}if(tick%20==0){for(var entry:List.copyOf(LIVE.entrySet())){var binding=entry.getValue();try{binding.current=binding.connection==mc().getConnection()&&binding.environment.equals(environment());trusted(store().get(entry.getKey()));}catch(Exception failure){binding.current=false;}if(!binding.current)automaticStop(entry.getKey(),"CLIENT_CODE_SOURCE_OR_CONTEXT_CHANGED");}reportDeliveries();}SCRIPTS.tick(tick);SCRIPTS.fire("client.tick",tick);for(var entry:List.copyOf(LIVE.entrySet())){var binding=entry.getValue();try{if(binding.javaSource)binding.callbacks();}catch(Exception|LinkageError failure){binding.current=false;}if(!binding.current||!runtimeLoaded(binding)||!binding.javaSource&&SCRIPTS.failure(binding.asset.manifest().packageId()).isPresent())automaticStop(entry.getKey(),binding.javaSource?"CLIENT_JAVA_CALLBACK_FAILED":"CLIENT_SCRIPT_CALLBACK_FAILED");}}
    private static void automaticStop(String filename,String reason){automaticStop(filename,reason,new HashSet<>());}
    private static void automaticStop(String filename,String reason,Set<String> seen){if(!seen.add(filename))return;var target=LIVE.get(filename);if(target==null)return;UUID id=target.asset.manifest().packageId();for(var entry:List.copyOf(LIVE.entrySet()))if(!entry.getKey().equals(filename)&&dependsOn(entry.getValue(),id))automaticStop(entry.getKey(),reason,seen);try{var local=store();var a=local.get(filename);if(!a.state().equals("RUNNING")&&!a.state().equals("STARTING")){stop(filename,reason);return;}String env=a.environment().matches("[a-f0-9]{64}")?a.environment():environment();var input=new LocalClientScriptStore.Input(UUID.randomUUID(),filename,"STOP",a.revision(),env,"LOCAL_RUNTIME");var job=local.dispatch(local.begin(input,"STOPPED"));boolean success=stop(filename,reason);local.finish(job,success,success?reason:javaSource(a)?"CLIENT_JAVA_STOP_UNKNOWN":"CLIENT_SCRIPT_STOP_UNKNOWN");}catch(Exception failure){try{stop(filename,reason);}catch(Exception ignored){}}}
    private static boolean dependsOn(Binding binding,UUID target){return binding.dependencies.mixed().nodes().stream().anyMatch(n->n.packageId().equals(target));}
    public static void connectionClosed(){thread();cancelDownload();DELIVERY_REPORTS.clear();var seen=new HashSet<String>();for(String filename:List.copyOf(LIVE.keySet()))automaticStop(filename,"CLIENT_CODE_CONNECTION_CLOSED",seen);}public static boolean loaded(String filename){var binding=LIVE.get(filename);return binding!=null&&runtimeLoaded(binding);}public static String runtimeStatus(String filename){return STATUS.getOrDefault(filename,"");}public static Map<String,Object> build(String filename){var b=BUILDS.get(filename);return b==null?Map.of():Map.of("artifact",b.artifactHash(),"className",b.className(),"sourceHash",b.sourceHash(),"classpath",b.classpathHash(),"environment",b.environment());}
    public static String code(Throwable failure){for(int i=0;failure!=null&&i<12;i++,failure=failure.getCause()){String value=Objects.toString(failure.getMessage(),"");if(value.equals("SERVER_IDENTITY_NOT_TRUSTED"))return "CLIENT_CODE_TRUST_REQUIRED";if(value.equals("STUDIO_SCRIPT_DEPENDENCY_IN_USE"))return "CLIENT_CODE_DEPENDENCY_IN_USE";if(value.startsWith("CLIENT_JAVA_COMPILE_REJECTED"))return "CLIENT_JAVA_COMPILE_REJECTED";if(value.matches("(?:CLIENT_CODE|CLIENT_SCRIPT|CLIENT_JAVA|CLIENT_PACKAGE|NATIVE_COMPATIBILITY|NATIVE_ENVIRONMENT)_[A-Z0-9_]{1,96}"))return value;}return "CLIENT_CODE_FAILED";}
}
