package dev.mineagent.runtime.neoforge.client.webui;

import com.google.gson.*;
import dev.mineagent.runtime.client.scripts.LocalClientScriptStore;
import dev.mineagent.runtime.neoforge.network.UiPayloads;
import net.minecraft.client.Minecraft;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.ClientTickEvent;
import net.neoforged.neoforge.client.network.ClientPacketDistributor;
import java.nio.file.*;
import java.util.*;

/** Real recipient UI flow: offer only, explicit download, separate local start/stop, or independent rejection. */
@EventBusSubscriber(modid="mineagent_runtime",value=Dist.CLIENT)
public final class ClientCodeDeliverySmokeClient {
    private static final String ROLE=System.getProperty("mineagent.deliverySmokeRole","");private static final Gson JSON=new Gson();private static JsonObject info,dom;private static String run="startup";private static int ticks,phase,after;private static boolean trusted,pressed,opened,ended;
    private ClientCodeDeliverySmokeClient(){}public static boolean enabled(){return Boolean.getBoolean("mineagent.clientCodeDeliverySmoke")&&Set.of("A","B").contains(ROLE);}public static boolean accept(UiPayloads.Event event){if(!enabled()||!event.channel().equals("clientCodeDeliveryFixture"))return false;info=JsonParser.parseString(event.json()).getAsJsonObject();run=info.get("run").getAsString();return true;}public static void acceptProbe(JsonObject value){if(enabled())dom=value;}private static Path root(){return Minecraft.getInstance().gameDirectory.toPath().resolve("client-code-delivery-evidence").resolve(run);}private static void write(String name,Object value)throws Exception{Files.createDirectories(root());Files.writeString(root().resolve(name),JSON.toJson(value));}private static void require(boolean value,String code){if(!value)throw new IllegalStateException(code);}private static void control(String action){ClientPacketDistributor.sendToServer(new UiPayloads.Command(UUID.randomUUID(),"deliveryFixture",JSON.toJson(Map.of("action",action))));}private static void main(String source){var host=WebGuiHostAdapter.INSTANCE;host.browser().executeJavaScript("(()=>{"+source+"})();",host.browser().getURL(),0);}private static JsonObject target(){return info.getAsJsonObject(ROLE.equals("A")?"rhino":"java");}private static JsonObject rejected(){return info.getAsJsonObject(ROLE.equals("A")?"java":"rhino");}private static JsonObject targetPackage(){return info.getAsJsonObject(ROLE.equals("A")?"rhinoPackage":"javaPackage");}private static boolean java(){return ROLE.equals("B");}private static LocalClientScriptStore.Asset asset()throws Exception{UUID id=UUID.fromString(targetPackage().get("packageId").getAsString());return LocalClientScriptStore.get(Minecraft.getInstance().gameDirectory.toPath()).list().stream().filter(a->a.manifest().packageId().equals(id)).findFirst().orElseThrow(()->new IllegalStateException("CLIENT_CODE_DELIVERY_ASSET_MISSING"));}private static String running(){return java()?"DELIVERED_JAVA_RUNNING":"DELIVERED_RHINO_RUNNING";}private static String cleaned(){return java()?"DELIVERED_JAVA_CLEANED":"DELIVERED_RHINO_CLEANED";}
    @SubscribeEvent public static void tick(ClientTickEvent.Post event)throws Exception{if(!enabled()||ended)return;var mc=Minecraft.getInstance();var host=WebGuiHostAdapter.INSTANCE;ticks++;try{if(ticks>12000)throw new IllegalStateException("CLIENT_CODE_DELIVERY_TIMEOUT_"+phase);if(mc.player!=null&&ticks%20==0){control("info");write("progress.json",Map.of("phase",phase,"trusted",trusted,"target",info==null||!info.has("rhino")?"":target().toString()));}if(mc.player!=null&&!trusted){if(mc.screen instanceof dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen screen&&!pressed)for(var child:screen.children())if(child instanceof net.minecraft.client.gui.components.Button button&&button.active&&button.getMessage().getString().equals("信任此服务器")){button.onPress(new net.minecraft.client.input.InputWithModifiers(){public int input(){return org.lwjgl.glfw.GLFW.GLFW_KEY_ENTER;}public int modifiers(){return 0;}});pressed=true;break;}if(ticks%40==0)ClientPacketDistributor.sendToServer(new dev.mineagent.runtime.neoforge.network.MineAgentPayloads.PanelRequest());var snapshot=dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox.snapshot();String fingerprint=snapshot.values().getOrDefault("security.identityFingerprint","");if(mc.getCurrentServer()!=null&&Boolean.parseBoolean(snapshot.values().getOrDefault("runtime.initialized","false"))&&new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status(mc.getCurrentServer().ip,fingerprint)==dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){trusted=true;if(mc.screen instanceof dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen)mc.setScreen(null);after=ticks+40;}}
        if(phase==0&&trusted&&info!=null&&info.get("ready").getAsBoolean()&&ticks>=after){require(LocalClientScriptStore.get(mc.gameDirectory.toPath()).list().isEmpty(),"CLIENT_CODE_DELIVERY_PREEXISTING_ASSET");host.open();opened=true;phase=1;}
        if(phase==1&&host.ready()&&UiClientSessions.current()!=null){main("document.querySelector('#open-deliveries')?.click();");phase=2;after=ticks+30;}
        if(phase==2&&ticks>=after&&ticks%10==0){String target=target().get("deliveryId").getAsString(),reject=rejected().get("deliveryId").getAsString();if(target().get("status").getAsString().equals("CODE_DOWNLOADED"))main("window.dispatchEvent(new Event('mineagent:client-script-probe'));const r=document.querySelector('[data-delivery-id=\""+reject+"\"] [data-action=delivery-reject]');if(r&&!r.disabled)r.click();");else main("window.dispatchEvent(new Event('mineagent:client-script-probe'));const t=document.querySelector('[data-delivery-id=\""+target+"\"] [data-action=delivery-code-download]');if(t&&!t.disabled)t.click();");if(dom!=null)write("dom-probe.json",dom);if(target().get("status").getAsString().equals("CODE_DOWNLOADED")&&rejected().get("status").getAsString().equals("REJECTED")){var asset=asset();require(asset.state().equals("DOWNLOADED")&&!asset.localConsent(),"CLIENT_CODE_DELIVERY_DOWNLOAD_EXECUTED");write("downloaded.json",Map.of("asset",asset,"target",target(),"rejected",rejected(),"systemInputInjected",false));main("document.querySelector('#open-client-scripts')?.click();");phase=3;after=ticks+20;}}
        if(phase==3&&ticks>=after&&ticks%10==0){String name=targetPackage().get("name").getAsString(),language=java()?"JAVA":"RHINO";main("const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-client-scripts');const c=[...p?.querySelectorAll('article')||[]].find(n=>n.querySelector('strong')?.textContent.startsWith("+JSON.toJson(name)+"));const q=c?.querySelector('input[type=checkbox]');const b=[...c?.querySelectorAll('button')||[]].find(n=>n.textContent==='本机编译并启动 CLIENT "+language+"');if(q&&b&&!b.disabled&&!window.__codeStarted){q.checked=true;window.__codeStarted=true;b.click();}");var asset=asset();if(asset.state().equals("RUNNING")&&ClientScriptPackages.loaded(asset.filename())&&ClientScriptPackages.runtimeStatus(asset.filename()).equals(running())&&target().get("status").getAsString().equals("CODE_RUNNING")){write("running.json",Map.of("asset",asset,"server",target(),"runtimeStatus",ClientScriptPackages.runtimeStatus(asset.filename())));phase=4;after=ticks+20;}}
        if(phase==4&&ticks>=after&&ticks%10==0){String name=targetPackage().get("name").getAsString();main("const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-client-scripts');const c=[...p?.querySelectorAll('article')||[]].find(n=>n.querySelector('strong')?.textContent.startsWith("+JSON.toJson(name)+"));const q=c?.querySelector('input[type=checkbox]');const b=[...c?.querySelectorAll('button')||[]].find(n=>n.textContent==='停止此本机代码');if(q&&b&&!b.disabled&&!window.__codeStopped){q.checked=true;window.__codeStopped=true;b.click();}");var asset=asset();if(asset.state().equals("STOPPED")&&!ClientScriptPackages.loaded(asset.filename())&&ClientScriptPackages.runtimeStatus(asset.filename()).equals(cleaned())&&target().get("status").getAsString().equals("CODE_STOPPED")){write("stopped.json",Map.of("asset",asset,"server",target(),"runtimeStatus",ClientScriptPackages.runtimeStatus(asset.filename())));control("done");phase=5;after=ticks+30;}}
        if(phase==5&&ticks>=after){write("result.json",Map.of("status","REAL_RECIPIENT_CLIENT_CODE_APPROVE_REJECT_START_STOP_VERIFIED","role",ROLE,"acceptedMode",java()?"CLIENT_JAVA":"CLIENT_RHINO","rejectedMode",java()?"CLIENT_RHINO":"CLIENT_JAVA","providerCalls",0,"systemInputInjected",false));ended=true;if(opened)host.close();mc.stop();dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_DELIVERY_CLIENT_OK role={} clientCode=true",ROLE);}}
        catch(Exception failure){fail(failure);}}
    private static void fail(Exception failure){if(ended)return;ended=true;try{write("failure.json",Map.of("phase",phase,"error",failure.toString(),"info",info==null?new JsonObject():info));}catch(Exception ignored){}WebGuiHostAdapter.INSTANCE.close();Minecraft.getInstance().stop();dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.error("DELIVERY_CLIENT_FAILED role={} clientCode=true phase={} error={}",ROLE,phase,failure.toString());}
}
