package dev.mineagent.runtime.neoforge.client.webui;

import com.fasterxml.jackson.databind.ObjectMapper;
import dev.mineagent.runtime.api.packages.*;
import dev.mineagent.runtime.core.packages.*;
import dev.mineagent.runtime.neoforge.content.NativePackageCompatibility;
import dev.mineagent.runtime.worker.compile.JavaSourceCompiler;

import java.io.*;
import java.lang.module.*;
import java.nio.file.*;
import java.util.*;
import java.util.function.BooleanSupplier;
import java.util.jar.*;

/** Materializes the actual CLIENT FML module layer into a hash-locked local Javac classpath. */
public final class ClientJavaCompiler {
    public record Classpath(String hash,String environment,String mapping,List<Path> jars,int modules,int classes,long bytes){public Classpath{jars=List.copyOf(jars);}}
    public record Built(Path artifact,String artifactHash,String className,String sourceHash,String classpathHash,String environment,List<?> diagnostics){}
    private static volatile Classpath cached;private static final Object LOCK=new Object();
    private ClientJavaCompiler(){}
    public static Classpath capture(Path game,BooleanSupplier permit)throws Exception{
        var env=NativePackageCompatibility.observe();var old=cached;if(old!=null&&old.environment().equals(env.fingerprint())&&old.jars().stream().allMatch(Files::isRegularFile))return old;
        synchronized(LOCK){old=cached;if(old!=null&&old.environment().equals(env.fingerprint())&&old.jars().stream().allMatch(Files::isRegularFile))return old;if(!permit.getAsBoolean())throw new IllegalStateException("CLIENT_JAVA_CONTEXT_CHANGED");ModuleLayer layer=net.neoforged.fml.loading.FMLLoader.getCurrent().getGameLayer();if(layer==null)throw new IllegalStateException("CLIENT_JAVA_MODULE_LAYER_UNAVAILABLE");
            Path directory=game.resolve("mineagent-runtime-data/client-java-classpath");Files.createDirectories(directory);if(Files.isSymbolicLink(directory)||!Files.isDirectory(directory,LinkOption.NOFOLLOW_LINKS))throw new IllegalStateException("CLIENT_JAVA_CLASSPATH_LINK");var layers=new ArrayList<ModuleLayer>();collect(layer,Collections.newSetFromMap(new IdentityHashMap<>()),layers);var jars=new ArrayList<Path>();var descriptors=new ArrayList<Map<String,Object>>();var seen=new HashMap<String,String>();long total=0;int classes=0,moduleCount=0;
            for(var current:layers)for(var module:current.modules().stream().sorted(Comparator.comparing(Module::getName)).toList()){
                String name=module.getName();if(name.startsWith("java.")||name.startsWith("jdk."))continue;if(++moduleCount>512)throw new IllegalStateException("CLIENT_JAVA_CLASSPATH_LIMIT");var reference=current.configuration().findModule(name).orElseThrow().reference();var output=new Bounded();int count=0;
                try(var reader=reference.open();var entries=reader.list();var jar=new JarOutputStream(output)){var paths=entries.filter(p->p.endsWith(".class")&&!p.equals("module-info.class")&&!p.startsWith("META-INF/")).limit(300001).sorted().toList();if(paths.size()>300000)throw new IllegalStateException("CLIENT_JAVA_CLASSPATH_LIMIT");for(String path:paths){if(path.startsWith("/")||path.contains("..")||path.contains("\\")||path.length()>1024)throw new IllegalStateException("CLIENT_JAVA_CLASSPATH_ENTRY");byte[] bytes;try(var in=reader.open(path).orElseThrow()){bytes=in.readNBytes(8*1024*1024+1);}if(bytes.length>8*1024*1024||(total+=bytes.length)>512L*1024*1024||++classes>300000)throw new IllegalStateException("CLIENT_JAVA_CLASSPATH_LIMIT");String hash=RuntimePackageCanonicalizer.sha256(bytes),prior=seen.putIfAbsent(path,hash);if(prior!=null&&!prior.equals(hash))throw new IllegalStateException("CLIENT_JAVA_CLASSPATH_AMBIGUOUS");var e=new JarEntry(path);e.setTime(0);jar.putNextEntry(e);jar.write(bytes);jar.closeEntry();count++;if(count%512==0&&!permit.getAsBoolean())throw new IllegalStateException("CLIENT_JAVA_CONTEXT_CHANGED");}}
                if(count==0){moduleCount--;continue;}byte[] image=output.toByteArray();String hash=RuntimePackageCanonicalizer.sha256(image);Path target=directory.resolve(hash+".jar");publish(target,image,hash);jars.add(target);descriptors.add(Map.of("name",name,"hash",hash,"classes",count,"bytes",image.length));
            }
            boolean support=false;var supportTypes=new LinkedHashMap<String,Class<?>>();supportTypes.put("dev/mineagent/runtime/api/packages/ClientRuntimeHost.class",ClientRuntimeHost.class);supportTypes.put("dev/mineagent/runtime/api/packages/ClientPackageBridge.class",ClientPackageBridge.class);supportTypes.put("dev/mineagent/runtime/api/packages/ClientPackageExports.class",ClientPackageExports.class);supportTypes.put("dev/mineagent/runtime/scripting/javaext/ClientRuntimeExtension.class",dev.mineagent.runtime.scripting.javaext.ClientRuntimeExtension.class);supportTypes.put("dev/mineagent/runtime/scripting/javaext/RuntimeExtension.class",dev.mineagent.runtime.scripting.javaext.RuntimeExtension.class);var missing=supportTypes.entrySet().stream().filter(e->!seen.containsKey(e.getKey())).toList();if(!missing.isEmpty()){support=true;var output=new Bounded();int count=0;try(var jar=new JarOutputStream(output)){for(var item:missing){byte[] bytes;try(var in=item.getValue().getResourceAsStream("/"+item.getKey())){if(in==null)throw new IllegalStateException("CLIENT_JAVA_RUNTIME_API_SUPPORT_MISSING");bytes=in.readNBytes(8*1024*1024+1);}if(bytes.length<4||bytes.length>8*1024*1024||bytes[0]!=(byte)0xCA||bytes[1]!=(byte)0xFE||bytes[2]!=(byte)0xBA||bytes[3]!=(byte)0xBE||(total+=bytes.length)>512L*1024*1024||++classes>300000)throw new IllegalStateException("CLIENT_JAVA_RUNTIME_API_SUPPORT_INVALID");String classHash=RuntimePackageCanonicalizer.sha256(bytes),prior=seen.putIfAbsent(item.getKey(),classHash);if(prior!=null&&!prior.equals(classHash))throw new IllegalStateException("CLIENT_JAVA_CLASSPATH_AMBIGUOUS");var entry=new JarEntry(item.getKey());entry.setTime(0);jar.putNextEntry(entry);jar.write(bytes);jar.closeEntry();count++;}}byte[] image=output.toByteArray();String imageHash=RuntimePackageCanonicalizer.sha256(image);Path target=directory.resolve(imageHash+".jar");publish(target,image,imageHash);jars.add(target);descriptors.add(Map.of("name","mineagent-runtime-api-support","hash",imageHash,"classes",count,"bytes",image.length));}
            for(String required:List.of("net/minecraft/client/Minecraft.class","net/neoforged/neoforge/common/NeoForge.class"))if(!seen.containsKey(required))throw new IllegalStateException("CLIENT_JAVA_CLASSPATH_INCOMPLETE");if(!permit.getAsBoolean()||!env.fingerprint().equals(NativePackageCompatibility.observe().fingerprint()))throw new IllegalStateException("CLIENT_JAVA_CONTEXT_CHANGED");String mapping=support?"RAW_CLIENT_MODULE_RESOURCES_WITH_RUNTIME_API_SUPPORT":"RAW_CLIENT_MODULE_RESOURCES_NOT_LIVE_TRANSFORMS";String hash=RuntimePackageCanonicalizer.sha256(RuntimePackageCanonicalizer.stableJson(Map.of("schema",1,"physicalSide","CLIENT","mapping",mapping,"environment",env.wire(),"modules",descriptors)));return cached=new Classpath(hash,env.fingerprint(),mapping,jars,jars.size(),classes,total);
        }
    }
    public static Built compile(Path game,ClientJavaPlan.Resolved resolved,BooleanSupplier permit)throws Exception{return compile(game,resolved,List.of(),resolved.plan().manifest().dependencies(),"",permit);}
    public static Built compile(Path game,ClientJavaPlan.Resolved resolved,List<Path> dependencyArtifacts,Map<UUID,String> dependencies,String dependencyHash,BooleanSupplier permit)throws Exception{
        var raw=capture(game,permit);if(dependencyArtifacts.size()>64||!dependencies.equals(resolved.plan().manifest().dependencies())||!dependencyHash.matches("(?:[a-f0-9]{64})?"))throw new IllegalArgumentException("CLIENT_JAVA_DEPENDENCY_CONTEXT");var all=new ArrayList<Path>();all.addAll(dependencyArtifacts);all.addAll(raw.jars());String classpathHash=RuntimePackageCanonicalizer.sha256(RuntimePackageCanonicalizer.stableJson(Map.of("raw",raw.hash(),"dependencyGraph",dependencyHash,"artifacts",dependencyArtifacts.stream().map(p->{try{return dev.mineagent.runtime.scripting.javaext.JavaExtensionManager.sha256(p);}catch(Exception e){throw new IllegalStateException(e);}}).toList())));if(!permit.getAsBoolean())throw new IllegalStateException("CLIENT_JAVA_CONTEXT_CHANGED");String entry=resolved.plan().entrypoint(),className=JavaSourceCompiler.inferClassName(resolved.sources().get(entry));var refs=new TreeMap<String,CodeDraft.SourceRef>();for(var file:resolved.sources().entrySet())refs.put(file.getKey(),CodeDraftSources.ref(file.getValue()));String sourceHash=CodeDraftSources.fingerprint(entry,refs,dependencies);Path directory=game.resolve("mineagent-runtime-data/client-java-artifacts");Files.createDirectories(directory);Path artifact=directory.resolve(resolved.bundleHash()+"-"+classpathHash+".jar");var context=new LinkedHashMap<String,Object>();context.put("physicalSide","CLIENT");context.put("environment",raw.environment());context.put("clientClasspath",classpathHash);context.put("rawClientClasspath",raw.hash());context.put("dependencyGraph",dependencyHash);context.put("mapping",raw.mapping());context.put("packageCanonical",resolved.plan().manifest().canonicalSha256());var result=new JavaSourceCompiler().compileWorkspace(className,entry,resolved.sources(),artifact,all,context,dependencies);if(!result.success())throw new IllegalStateException("CLIENT_JAVA_COMPILE_REJECTED:"+result.diagnostics().stream().limit(4).toList());String artifactHash=dev.mineagent.runtime.scripting.javaext.JavaExtensionManager.sha256(artifact);verifyReceipt(artifact,className,sourceHash,raw.environment(),classpathHash,dependencyHash);if(!permit.getAsBoolean())throw new IllegalStateException("CLIENT_JAVA_CONTEXT_CHANGED");return new Built(artifact,artifactHash,className,sourceHash,classpathHash,raw.environment(),result.diagnostics());
    }
    private static void verifyReceipt(Path artifact,String className,String sourceHash,String environment,String classpathHash,String dependencyHash)throws Exception{try(var jar=new JarFile(artifact.toFile(),false)){var entry=jar.getJarEntry("META-INF/mineagent/compilation.json");if(entry==null)throw new IllegalStateException("CLIENT_JAVA_COMPILE_RECEIPT");var node=new ObjectMapper().readTree(jar.getInputStream(entry));if(!node.path("className").asText().equals(className)||!node.path("sourceSha256").asText().equals(sourceHash)||!node.path("physicalSide").asText().equals("CLIENT")||!node.path("environment").asText().equals(environment)||!node.path("clientClasspath").asText().equals(classpathHash)||!node.path("dependencyGraph").asText().equals(dependencyHash))throw new IllegalStateException("CLIENT_JAVA_COMPILE_RECEIPT");if(jar.getJarEntry(className.replace('.','/')+".class")==null)throw new IllegalStateException("CLIENT_JAVA_COMPILE_ENTRY");}}
    private static void collect(ModuleLayer layer,Set<ModuleLayer> seen,List<ModuleLayer> out){if(!seen.add(layer))return;out.add(layer);for(var parent:layer.parents())collect(parent,seen,out);}
    private static void publish(Path target,byte[] bytes,String hash)throws Exception{if(Files.exists(target,LinkOption.NOFOLLOW_LINKS)){if(Files.isSymbolicLink(target)||!Files.isRegularFile(target)||!dev.mineagent.runtime.scripting.javaext.JavaExtensionManager.sha256(target).equals(hash))throw new IllegalStateException("CLIENT_JAVA_CLASSPATH_CHANGED");return;}Path temporary=Files.createTempFile(target.getParent(),".mineagent-client-classpath-",".pending");try{Files.write(temporary,bytes);Files.move(temporary,target,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException unsupported){Files.move(temporary,target);}finally{Files.deleteIfExists(temporary);}}
    private static final class Bounded extends ByteArrayOutputStream {private void reserve(int n){if(n<0||(long)count+n>256L*1024*1024)throw new IllegalStateException("CLIENT_JAVA_CLASSPATH_LIMIT");}@Override public synchronized void write(int b){reserve(1);super.write(b);}@Override public synchronized void write(byte[] b,int o,int n){Objects.checkFromIndexSize(o,n,b.length);reserve(n);super.write(b,o,n);}}
}
