package dev.mineagent.runtime.neoforge.client.webui;

import com.google.gson.*;
import dev.mineagent.runtime.client.scripts.LocalClientScriptStore;
import dev.mineagent.runtime.neoforge.ui.ClientScriptSmokeServer;
import net.minecraft.client.Minecraft;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.ClientTickEvent;

import java.nio.file.*;
import java.util.*;

/** Two-process real CEF CLIENT Rhino lifecycle; JavaScript DOM calls only, never OS input or a Provider. */
@EventBusSubscriber(modid="mineagent_runtime",value=Dist.CLIENT)
public final class ClientScriptSmokeClient {
    private static final Gson JSON=new Gson();private static JsonObject probe;private static int ticks,phase,after,closedCount,stoppedAt;private static boolean backup,trusted,trustPressed,opened,finished;private static String filename="",closedStatus="";
    private ClientScriptSmokeClient(){}
    public static void accept(JsonObject value){if(ClientScriptSmokeServer.enabled())probe=value;}
    private static Path root(){return Minecraft.getInstance().gameDirectory.toPath().resolve("client-script-smoke");}
    private static void write(String name,Object value)throws Exception{Files.createDirectories(root());Files.writeString(root().resolve(name+".json"),JSON.toJson(value));}
    private static void require(boolean value,String code){if(!value)throw new IllegalStateException(code);}
    private static void script(String code){var host=WebGuiHostAdapter.INSTANCE;host.browser().executeJavaScript("(()=>{"+code+"})();",host.browser().getURL(),0);}
    private static void action(String key,String code){script("window.__clientScriptSmoke??={};if(window.__clientScriptSmoke["+JSON.toJson(key)+"])return;const ok=(()=>{"+code+"})();if(ok)window.__clientScriptSmoke["+JSON.toJson(key)+"]=true;");}
    private static void poll(){script("window.dispatchEvent(new Event('mineagent:client-script-probe'));");}
    private static String text(String key){return probe==null||!probe.has(key)?"":probe.get(key).getAsString();}
    private static LocalClientScriptStore.Asset asset()throws Exception{var id=ClientScriptSmokeServer.runtimePackage.packageId();return LocalClientScriptStore.get(Minecraft.getInstance().gameDirectory.toPath()).list().stream().filter(a->a.manifest().packageId().equals(id)).findFirst().orElseThrow(()->new IllegalStateException("CLIENT_SCRIPT_SMOKE_ASSET_MISSING"));}
    private static int statusCount(String status){if(!status.startsWith("TICK:"))return -1;return Integer.parseInt(status.split(":",3)[1]);}
    private static void fail(Throwable error)throws Exception{finished=true;write("client-failure-"+ClientScriptSmokeServer.stage(),Map.of("phase",phase,"ticks",ticks,"error",error.toString(),"serverFailure",Objects.toString(ClientScriptSmokeServer.failure,""),"probe",probe==null?"{}":probe.toString()));WebGuiHostAdapter.INSTANCE.close();Minecraft.getInstance().stop();}
    @SubscribeEvent public static void tick(ClientTickEvent.Post event)throws Exception{
        if(!ClientScriptSmokeServer.enabled()||finished)return;var mc=Minecraft.getInstance();var host=WebGuiHostAdapter.INSTANCE;ticks++;
        try{
            if(ticks>7000)throw new IllegalStateException("CLIENT_SCRIPT_CEF_TIMEOUT_"+phase);if(ClientScriptSmokeServer.failure!=null)throw new IllegalStateException(ClientScriptSmokeServer.failure);
            if(!backup&&mc.screen instanceof net.minecraft.client.gui.screens.BackupConfirmScreen screen){backup=true;var field=screen.getClass().getDeclaredField("onProceed");field.setAccessible(true);((net.minecraft.client.gui.screens.BackupConfirmScreen.Listener)field.get(screen)).proceed(false,false);}
            if(!trusted&&mc.player!=null){if(ticks%20==0)net.neoforged.neoforge.client.network.ClientPacketDistributor.sendToServer(new dev.mineagent.runtime.neoforge.network.MineAgentPayloads.PanelRequest());if(mc.screen instanceof dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen screen&&!trustPressed)for(var child:screen.children())if(child instanceof net.minecraft.client.gui.components.Button button&&button.active&&button.getMessage().getString().equals("信任此服务器")){button.onPress(new net.minecraft.client.input.InputWithModifiers(){public int input(){return org.lwjgl.glfw.GLFW.GLFW_KEY_ENTER;}public int modifiers(){return 0;}});trustPressed=true;net.neoforged.neoforge.client.network.ClientPacketDistributor.sendToServer(new dev.mineagent.runtime.neoforge.network.MineAgentPayloads.PanelRequest());break;}var snapshot=dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox.snapshot();String fingerprint=snapshot.values().getOrDefault("security.identityFingerprint","");var trustStatus=new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fingerprint);if(trustStatus==dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED&&(trustPressed||ClientScriptSmokeServer.stage().equals("resume"))){trusted=true;write("trust-"+ClientScriptSmokeServer.stage(),Map.of("actualNativeTrustButton",trustPressed,"previouslyStoredTrust",!trustPressed,"fingerprint",fingerprint,"systemInputInjected",false));mc.setScreen(null);}else return;}
            if(ClientScriptSmokeServer.runtimePackage==null)return;
                if(ClientScriptSmokeServer.stage().equals("resume")&&phase==0){var a=asset();filename=a.filename();require(a.state().equals("STOPPED")&&!a.localConsent()&&!ClientScriptPackages.loaded(filename),"CLIENT_SCRIPT_RESTART_REPLAYED");require(Set.of("CLIENT_CODE_CONNECTION_CLOSED","CLIENT_SCRIPT_CONNECTION_CLOSED","CLIENT_CODE_RESTART_NOT_RUNNING").contains(a.code()),"CLIENT_SCRIPT_RESTART_STATE");write("resume-initial",Map.of("asset",a,"loaded",false,"runtimeStatus",ClientScriptPackages.runtimeStatus(filename)));phase=100;}
            if(!opened&&(phase==0||phase==100)){opened=true;host.open();}
            if(phase==5){if(ticks<after)return;String now=ClientScriptPackages.runtimeStatus(filename);int count=statusCount(now);require(ClientScriptPackages.loaded(filename)&&count>closedCount,"CLIENT_SCRIPT_STOPPED_WITH_F2");write("prepare-running-after-f2-close",Map.of("before",closedStatus,"after",now,"loaded",true,"providerCalls",0,"systemInputInjected",false));dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CLIENT_SCRIPT_PREPARE_OK");finished=true;mc.stop();return;}
            if(phase==104&&ticks>=after){require(!ClientScriptPackages.loaded(filename)&&ClientScriptPackages.runtimeStatus(filename).equals("CLEANED"),"CLIENT_SCRIPT_CALLBACK_AFTER_STOP");var a=asset();require(a.state().equals("STOPPED")&&!a.localConsent(),"CLIENT_SCRIPT_STOP_LEDGER");write("result",Map.of("status","REAL_CEF_CLIENT_RHINO_TRUST_START_CLOSE_CONTINUE_RESTART_STOP_VERIFIED","asset",a,"runtimeStatus",ClientScriptPackages.runtimeStatus(filename),"managedCallbacksStopped",true,"providerCalls",0,"systemInputInjected",false,"clientJavaExecuted",false,"fullV1",false));finished=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CLIENT_SCRIPT_RESUME_OK");host.close();mc.stop();return;}
            if(!host.ready()||UiClientSessions.current()==null||ticks%10!=0)return;poll();String catalog=text("catalogText"),manager=text("clientScriptText");
            switch(phase){
                case 0->{action("catalog","document.querySelector('#open-package-catalog')?.click();return true;");if(catalog.contains(ClientScriptSmokeServer.PACKAGE_NAME)&&catalog.contains("本机 CLIENT 原生代码下载 / 执行"))phase=1;}
                case 1->{action("open-manager","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-package-catalog');const c=[...p?.querySelectorAll('article')||[]].find(n=>n.querySelector('strong')?.textContent==="+JSON.toJson(ClientScriptSmokeServer.PACKAGE_NAME)+");const b=[...c?.querySelectorAll('button')||[]].find(n=>n.textContent==='本机 CLIENT 原生代码下载 / 执行');if(!b)return false;b.click();return true;");if(manager.contains("所选服务器包："+ClientScriptSmokeServer.PACKAGE_NAME)&&manager.contains("下载 CLIENT Rhino（不执行）"))phase=2;}
                case 2->{action("download","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-client-scripts');const b=[...p?.querySelectorAll('button')||[]].find(n=>n.textContent==='下载 CLIENT Rhino（不执行）');if(!b||b.disabled)return false;b.click();return true;");if(manager.contains("DOWNLOADED · 当前进程 未运行")&&manager.contains("CLIENT_SCRIPT_DOWNLOADED_NOT_APPROVED")){var a=asset();filename=a.filename();require(!a.localConsent()&&!ClientScriptPackages.loaded(filename),"CLIENT_SCRIPT_DOWNLOAD_AUTO_STARTED");require(text("cardBackground").startsWith("rgba("),"CLIENT_SCRIPT_GLASS_CARD");write("downloaded",Map.of("asset",a,"runtimeStatus",ClientScriptPackages.runtimeStatus(filename),"cardBackground",text("cardBackground")));phase=3;}}
                case 3->{action("start-prepare","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-client-scripts');const c=[...p?.querySelectorAll('article')||[]].find(n=>n.querySelector('strong')?.textContent.startsWith("+JSON.toJson(ClientScriptSmokeServer.PACKAGE_NAME)+"));const q=c?.querySelector('input[type=checkbox]');const b=[...c?.querySelectorAll('button')||[]].find(n=>n.textContent==='本机编译并启动 CLIENT RHINO');if(!q||!b||b.disabled)return false;q.checked=true;b.click();return true;");String status=ClientScriptPackages.runtimeStatus(filename);if(manager.contains("RUNNING · 当前进程 已运行")&&statusCount(status)>=10){write("prepare-running",Map.of("asset",asset(),"status",status,"loaded",true));closedStatus=status;closedCount=statusCount(status);host.close();UiClientSessions.reset(true);opened=false;phase=5;after=ticks+60;}}
                case 100->{action("open-local-manager","document.querySelector('#open-client-scripts')?.click();return true;");if(manager.contains(ClientScriptSmokeServer.PACKAGE_NAME)&&manager.contains("STOPPED · 当前进程 未运行"))phase=101;}
                case 101->{action("start-resume","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-client-scripts');const c=[...p?.querySelectorAll('article')||[]].find(n=>n.querySelector('strong')?.textContent.startsWith("+JSON.toJson(ClientScriptSmokeServer.PACKAGE_NAME)+"));const q=c?.querySelector('input[type=checkbox]');const b=[...c?.querySelectorAll('button')||[]].find(n=>n.textContent==='本机编译并启动 CLIENT RHINO');if(!q||!b||b.disabled)return false;q.checked=true;b.click();return true;");if(manager.contains("RUNNING · 当前进程 已运行")&&statusCount(ClientScriptPackages.runtimeStatus(filename))>=10)phase=102;}
                case 102->{action("stop-resume","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-client-scripts');const c=[...p?.querySelectorAll('article')||[]].find(n=>n.querySelector('strong')?.textContent.startsWith("+JSON.toJson(ClientScriptSmokeServer.PACKAGE_NAME)+"));const q=c?.querySelector('input[type=checkbox]');const b=[...c?.querySelectorAll('button')||[]].find(n=>n.textContent==='停止此本机代码');if(!q||!b||b.disabled)return false;q.checked=true;b.click();return true;");phase=103;}
                case 103->{action("stop-resume","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-client-scripts');const c=[...p?.querySelectorAll('article')||[]].find(n=>n.querySelector('strong')?.textContent.startsWith("+JSON.toJson(ClientScriptSmokeServer.PACKAGE_NAME)+"));const q=c?.querySelector('input[type=checkbox]');const b=[...c?.querySelectorAll('button')||[]].find(n=>n.textContent==='停止此本机代码');if(!q||!b||b.disabled)return false;q.checked=true;b.click();return true;");if(manager.contains("STOPPED · 当前进程 未运行")&&manager.contains("CLIENT_SCRIPT_STOPPED")&&ClientScriptPackages.runtimeStatus(filename).equals("CLEANED")){stoppedAt=ticks;after=ticks+50;phase=104;}}
            }
        }catch(Exception error){fail(error);throw error;}
    }
}
