package dev.mineagent.runtime.neoforge.client.webui;
import com.google.gson.*;
import dev.mineagent.runtime.api.ui.UiProtocol.*;
import dev.mineagent.runtime.neoforge.ui.ConversationSmokeServer;
import net.minecraft.client.Minecraft;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.ClientTickEvent;
import java.nio.file.*;
import java.util.*;
@EventBusSubscriber(modid="mineagent_runtime",value=Dist.CLIENT)
public final class ConversationSmokeClient {
    private static final Gson JSON=new Gson();private static int ticks,phase,after;private static boolean backup,trusted,pressed,busy,captured,summaryViewed,negativeCaptured;private static JsonObject probe;
    public static void accept(JsonObject value){probe=value;}
    private static Path root(){return Minecraft.getInstance().gameDirectory.toPath().resolve("conversation-evidence");}
    private static void js(String code){var h=WebGuiHostAdapter.INSTANCE;h.browser().executeJavaScript("(()=>{"+code+"})();",h.browser().getURL(),0);}
    private static void click(String selector){js("document.querySelector("+JSON.toJson(selector)+")?.click();");}
    private static void edit(String selector,String text){js("const e=document.querySelector("+JSON.toJson(selector)+");if(e){e.value="+JSON.toJson(text)+";e.dispatchEvent(new Event('input',{bubbles:true}));}");}
    private static void select(UUID id){probe=null;js("const e=document.querySelector('#conversation-list');if(e){e.value="+JSON.toJson(id.toString())+";e.dispatchEvent(new Event('change',{bubbles:true}));}");}
    private static boolean selected(UUID id){return probe!=null&&probe.has("selected")&&probe.get("selected").getAsString().equals(id.toString());}
    private static String value(String key){return probe==null||!probe.has(key)?"":probe.get(key).getAsString();}
    private static void save(String name,Object data){try{Files.writeString(root().resolve(ConversationSmokeServer.stage()+"-"+name+".json"),JSON.toJson(data));}catch(Exception e){fail(e);}}
    private static void fail(Throwable e){ConversationSmokeServer.failure=e.getMessage()==null?e.getClass().getSimpleName():e.getMessage();}
    @SubscribeEvent public static void tick(ClientTickEvent.Post event)throws Exception{
        if(!ConversationSmokeServer.enabled()||phase==99)return;var mc=Minecraft.getInstance();var host=WebGuiHostAdapter.INSTANCE;ticks++;Files.createDirectories(root());
        if(phase==98){if(ticks>=after){phase=99;mc.stop();}return;}
        if(ConversationSmokeServer.failure!=null||ticks>5000){save("failure",Map.of("phase",phase,"error",String.valueOf(ConversationSmokeServer.failure),"probe",probe==null?new JsonObject():probe));host.close();mc.disconnectFromWorld(net.minecraft.network.chat.Component.literal("Conversation fixture failed"));phase=98;after=ticks+20;return;}
        if(phase==90){if(ticks>=after){phase=99;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_{}_OK",ConversationSmokeServer.stage().toUpperCase(Locale.ROOT));mc.stop();}return;}
        if(!backup&&mc.screen instanceof net.minecraft.client.gui.screens.BackupConfirmScreen s){backup=true;var f=s.getClass().getDeclaredField("onProceed");f.setAccessible(true);((net.minecraft.client.gui.screens.BackupConfirmScreen.Listener)f.get(s)).proceed(false,false);}
        if(mc.player!=null&&!trusted){if(mc.screen instanceof dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen screen&&!pressed)for(var c:screen.children())if(c instanceof net.minecraft.client.gui.components.Button b&&b.active&&b.getMessage().getString().equals("信任此服务器")){b.onPress(new net.minecraft.client.input.InputWithModifiers(){public int input(){return org.lwjgl.glfw.GLFW.GLFW_KEY_ENTER;}public int modifiers(){return 0;}});pressed=true;break;}
            String fp=dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","");if(!fp.isEmpty()&&new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fp)==dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){trusted=true;mc.setScreen(null);}else return;}
        if(phase==0&&trusted&&ConversationSmokeServer.ready){host.open();phase=1;}
        if(!host.ready()||UiClientSessions.current()==null)return;
        if(ticks%10==0)js("const rows=[...document.querySelectorAll('#chat-history article')],sel=document.querySelector('#conversation-list');window.mineagentQuery({request:JSON.stringify({channel:'conversationProbe',summaryState:document.querySelector('#conversation-summary-body')?.dataset.summaryState||'',summaryText:document.querySelector('#conversation-summary-body')?.innerText.slice(0,10000)||'',revision:document.querySelector('#conversation-manager')?.dataset.revision||'',selected:sel?.value||'',options:sel?[...sel.options].map(o=>o.value):[],first:rows.length?Number(rows[0].querySelector('strong').textContent.match(/^#(\\d+)/)?.[1]):0,history:document.querySelector('#chat-history')?.innerText.slice(0,20000)||'',draft:document.querySelector('#chat-draft')?.value||'',disabled:document.querySelector('#chat-draft')?.disabled??true,status:document.querySelector('#conversation-status')?.textContent||''}),persistent:false,onSuccess(){},onFailure(){}});");
        if(ticks%40==0)save("progress",Map.of("phase",phase,"ticks",ticks,"probe",probe==null?new JsonObject():probe));
        if(phase==1){click("#open-chat");phase=2;after=ticks+25;}
        if(phase==2&&ticks>=after){probe=null;js("const e=document.querySelector('#chat-agent');e.value="+JSON.toJson(ConversationSmokeServer.agent.toString())+";e.dispatchEvent(new Event('change',{bubbles:true}));");phase=3;}
        if(phase==3&&probe!=null&&probe.getAsJsonArray("options").toString().contains(ConversationSmokeServer.a.toString())){select(ConversationSmokeServer.stage().equals("prepare")?ConversationSmokeServer.a:ConversationSmokeServer.b);phase=ConversationSmokeServer.stage().equals("prepare")?4:30;after=ticks+20;}
        if(phase==4&&ticks>=after&&selected(ConversationSmokeServer.a)&&probe.get("first").getAsInt()>0){if(probe.get("first").getAsInt()==1&&value("history").contains("HISTORY_USER_0")){save("oldest-page",probe);select(ConversationSmokeServer.a);phase=5;}else{click("#conversation-older");after=ticks+20;}}
        if(phase==5&&selected(ConversationSmokeServer.a)&&!probe.get("disabled").getAsBoolean()&&probe.get("first").getAsInt()>20){edit("#chat-draft","CURRENT_CONVERSATION_A");js("[...document.querySelector('#chat-draft').parentElement.querySelectorAll('button')].find(b=>b.textContent==='发送私密消息').click();");phase=6;}
        if(phase==6&&!ConversationSmokeServer.summaryFailureMode().isEmpty()&&Files.exists(mc.gameDirectory.toPath().resolve("conversation-summary-pending"))&&selected(ConversationSmokeServer.a)&&value("summaryState").equals("PENDING")){
            save("summary-in-flight",probe);js("document.querySelector('#conversation-summary').open=true;");if(ConversationSmokeServer.summaryFailureMode().equals("cancel"))click("#conversation-cancel");else Files.writeString(mc.gameDirectory.toPath().resolve("conversation-summary-release"),"Explicit failure-response release, not a model retry.");phase=60;
        }
        if(phase==60&&ConversationSmokeServer.aDone){if(ConversationSmokeServer.summaryFailureMode().equals("cancel"))Files.writeString(mc.gameDirectory.toPath().resolve("conversation-summary-release"),"Released only after actual GUI cancellation reached Native terminal state.");phase=61;}
        if(phase==61&&ConversationSmokeServer.negativeStable&&value("history").contains(ConversationSmokeServer.expectedError())&&value("summaryState").equals(ConversationSmokeServer.expectedSummaryState())){phase=62;after=ticks+25;}
        if(phase==62&&ticks>=after&&!busy){save("summary-negative-gui",probe);busy=true;net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),img->{try(img){img.writeToFile(root().resolve("prepare-summary-negative-gui.png"));negativeCaptured=true;}catch(Exception e){mc.execute(()->fail(e));}});}
        if(phase==62&&negativeCaptured){busy=false;edit("#conversation-title","日常 B");click("#conversation-create");phase=7;}
        if(phase==6&&Files.exists(mc.gameDirectory.toPath().resolve("conversation-a-pending"))){edit("#conversation-title","日常 B");click("#conversation-create");phase=7;}
        if(phase==7&&ConversationSmokeServer.b!=null&&selected(ConversationSmokeServer.b)&&!probe.get("disabled").getAsBoolean()){edit("#chat-draft","UNSENT_B_CANARY");phase=8;after=ticks+15;}
        if(phase==8&&ticks>=after&&value("draft").equals("UNSENT_B_CANARY")){ConversationSmokeServer.switchPersona=true;phase=9;}
        if(phase==9&&ConversationSmokeServer.aDone&&Files.exists(mc.gameDirectory.toPath().resolve("conversation-release-a"))){if(!selected(ConversationSmokeServer.b)||!value("draft").equals("UNSENT_B_CANARY")||value("history").contains("CONTROLLED_REPLY_A")){fail(new IllegalStateException("CONVERSATION_LATE_REPLY_SWITCHED_B"));return;}save("late-A-preserved-B",probe);edit("#chat-draft","CURRENT_CONVERSATION_B");js("[...document.querySelector('#chat-draft').parentElement.querySelectorAll('button')].find(b=>b.textContent==='发送私密消息').click();");phase=10;}
        if(phase==10&&ConversationSmokeServer.bDone&&value("history").contains("CONTROLLED_REPLY_B")){if(ConversationSmokeServer.nativeMode()){click("#conversation-native-route");phase=40;}else{edit("#chat-draft","RESTART_B_DRAFT");edit("#conversation-title","日常 B 改名");click("[data-conversation-action=rename]");phase=11;}}
        if(phase==40&&ConversationSmokeServer.nativeRoutingEnabled){mc.player.connection.sendChat("CURRENT_CONVERSATION_NATIVE");phase=41;}
        if(phase==41&&ConversationSmokeServer.nativeDone&&value("history").contains("CONTROLLED_REPLY_NATIVE")){
            var receipt=dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox.conversationReceipt();if(!receipt.code().equals("ACCEPTED"))throw new IllegalStateException("NATIVE_CHAT_NOT_ACCEPTED");ConversationSmokeServer.nativeOperation=receipt.operationId();Files.writeString(root().resolve("native-operation.json"),JSON.toJson(receipt));click("#conversation-native-route");
            net.neoforged.neoforge.client.network.ClientPacketDistributor.sendToServer(new dev.mineagent.runtime.neoforge.network.MineAgentPayloads.ConversationSend(ConversationSmokeServer.agent.toString(),"LEGACY_SHOULD_NOT_DISPATCH",false));phase=42;
        }
        if(phase==42&&dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox.conversationState().errorCode().equals("CONVERSATION_ID_REQUIRED")&&!ConversationSmokeServer.nativeRoutingEnabled){save("legacy-rejected",dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox.conversationState());edit("#chat-draft","RESTART_B_DRAFT");edit("#conversation-title","日常 B 改名");click("[data-conversation-action=rename]");phase=11;}
        if(phase==11&&ConversationSmokeServer.bRevision==2&&value("revision").equals("2")){click("[data-conversation-action=archive]");phase=12;}
        if(phase==12&&ConversationSmokeServer.bRevision==3&&value("revision").equals("3")){click("[data-conversation-action=restore]");phase=13;}
        if(phase==13&&ConversationSmokeServer.bRevision==4&&value("revision").equals("4")){click("[data-conversation-action=delete]");phase=14;}
        if(phase==14&&ConversationSmokeServer.bRevision==5&&value("revision").equals("5")){click("[data-conversation-action=restore]");phase=15;}
        if(phase==15&&ConversationSmokeServer.bRevision==6&&!busy){busy=true;UiClientSessions.command("conversation.read",Map.of("kind","get","agentId",ConversationSmokeServer.agent.toString(),"conversationId",ConversationSmokeServer.foreign.toString()),UUID.randomUUID()).thenCompose(r->{if(r.code()!=Code.PERMISSION_DENIED)throw new IllegalStateException("CONVERSATION_FOREIGN_READ");save("foreign-denied",r);return UiClientSessions.command("conversation.read",Map.of("kind","get","agentId",ConversationSmokeServer.otherAgent.toString(),"conversationId",ConversationSmokeServer.a.toString()),UUID.randomUUID());}).thenCompose(r->{if(r.code()!=Code.PERMISSION_DENIED)throw new IllegalStateException("CONVERSATION_WRONG_AGENT_READ");save("wrong-agent-denied",r);return UiClientSessions.command("conversation.read",Map.of("kind","list","agentId",ConversationSmokeServer.agent.toString(),"state","ALL","search","SECRET_OTHER","before","0"),UUID.randomUUID());}).whenComplete((r,e)->mc.execute(()->{if(e!=null){fail(e);return;}if(JsonParser.parseString(r.values().get("state")).getAsJsonObject().getAsJsonArray("conversations").size()!=0){fail(new IllegalStateException("CONVERSATION_SEARCH_LEAK"));return;}save("private-search",r);busy=false;phase=20;after=ticks+35;}));}
        if(phase==30&&selected(ConversationSmokeServer.b)&&value("draft").equals("RESTART_B_DRAFT")&&!busy){busy=true;save("restored-B-draft",probe);UiClientSessions.command("conversation.write",Map.of("kind","send","agentId",ConversationSmokeServer.agent.toString(),"conversationId",ConversationSmokeServer.a.toString(),"expectedRevision","1","text","CURRENT_CONVERSATION_A"),ConversationSmokeServer.aOperation).whenComplete((r,e)->mc.execute(()->{if(e!=null||!"true".equals(r.values().get("duplicate"))){fail(e==null?new IllegalStateException("CONVERSATION_REPLAY_DISPATCHED"):e);return;}save("restart-send-duplicate",r);busy=false;phase=20;after=ticks+35;}));}
        if(phase==20&&ticks>=after){if(ConversationSmokeServer.summaryMode()&&!summaryViewed){select(ConversationSmokeServer.a);phase=50;}else if(ConversationSmokeServer.nativeMode()&&ConversationSmokeServer.stage().equals("resume")){net.neoforged.neoforge.client.network.ClientPacketDistributor.sendToServer(new dev.mineagent.runtime.neoforge.network.MineAgentPayloads.ConversationSendV2(ConversationSmokeServer.nativeOperation,UiClientSessions.current().binding().worldId(),ConversationSmokeServer.agent,ConversationSmokeServer.b,1,"CURRENT_CONVERSATION_NATIVE"));phase=43;}else{save("gui",probe);ConversationSmokeServer.finish=true;phase=21;}}
        if(phase==50&&selected(ConversationSmokeServer.a)&&value("summaryState").equals(ConversationSmokeServer.expectedSummaryState())){click("#conversation-summary-title");phase=51;}
        if(phase==51&&(ConversationSmokeServer.summaryFailureMode().isEmpty()?value("summaryText").contains("SUMMARY_ANCHOR"):value("summaryState").equals(ConversationSmokeServer.expectedSummaryState())&&!value("summaryText").isBlank())){save("summary-gui",probe);summaryViewed=true;select(ConversationSmokeServer.b);phase=52;}
        if(phase==52&&selected(ConversationSmokeServer.b)&&value("draft").equals("RESTART_B_DRAFT")){phase=20;after=ticks+15;}
        if(phase==43){var receipt=dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox.conversationReceipt();if(receipt.operationId().equals(ConversationSmokeServer.nativeOperation)){if(!receipt.code().equals("ACCEPTED")||!"true".equals(receipt.values().get("duplicate"))){fail(new IllegalStateException("NATIVE_RESTART_REPLAY_FAILED"));return;}save("native-restart-replay",receipt);save("gui",probe);ConversationSmokeServer.finish=true;phase=21;}}
        if(phase==21&&ConversationSmokeServer.done&&!busy){busy=true;net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),img->{try(img){img.writeToFile(root().resolve(ConversationSmokeServer.stage()+"-gui.png"));captured=true;}catch(Exception e){mc.execute(()->fail(e));}});}
        if(phase==21&&captured){host.close();mc.disconnectFromWorld(net.minecraft.network.chat.Component.literal("Conversation fixture done"));phase=90;after=ticks+20;}
    }
}
