package dev.mineagent.runtime.neoforge.client.webui;
import com.google.gson.*;import dev.mineagent.runtime.neoforge.ui.FeedbackNineSmokeServer;import dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen;import dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox;import net.minecraft.client.Minecraft;import java.nio.file.*;import java.util.*;
public final class FeedbackNineSmokeClient {
 private static int ticks,phase,wait,axeFrames,tableFrames;private static boolean done,busy,keySaved;private static UUID sentApproval;private static JsonObject probe;private static long generation;private static ControlCenterScreen modelScreen;private static int entityWait;
 public static void accept(JsonObject data){probe=data;}
 private static void script(String source){var h=WebGuiHostAdapter.INSTANCE;h.browser().executeJavaScript("(()=>{"+source+"})();",h.browser().getURL(),0);}
 public static void tick()throws Exception{if(done)return;var mc=Minecraft.getInstance();ticks++;Path root=Files.createDirectories(mc.gameDirectory.toPath().resolve("nine-feedback-smoke"));try{if(ticks%100==0)Files.writeString(root.resolve("client-progress.json"),new Gson().toJson(Map.of("phase",phase,"probe",probe==null?new JsonObject():probe)));if(!FeedbackNineSmokeServer.failure.isEmpty())throw new IllegalStateException(FeedbackNineSmokeServer.failure);if(ticks>28000)throw new IllegalStateException("NINE_CLIENT_TIMEOUT_"+phase);if(mc.player==null||!FeedbackNineSmokeServer.ready||busy)return;var actor=mc.level.getPlayerByUUID(FeedbackNineSmokeServer.agent);if(actor!=null){if(actor.getMainHandItem().is(net.minecraft.world.item.Items.IRON_AXE))axeFrames++;if(actor.getMainHandItem().is(net.minecraft.world.item.Items.CRAFTING_TABLE))tableFrames++;}
 if(phase==0){String fp=PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","");if(fp.isEmpty()||new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fp)!=dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){if(mc.screen instanceof ControlCenterScreen s)for(var c:List.copyOf(s.children()))if(c instanceof net.minecraft.client.gui.components.Button b&&b.active&&b.getMessage().getString().contains("信任此服务器"))b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));return;}if(++wait==1)mc.player.connection.sendCommand("ai accept");if(wait<40)return;FeedbackNineSmokeServer.clientReady=true;mc.setScreen(null);phase=1;}
 if(FeedbackNineSmokeServer.real()){if(FeedbackNineSmokeServer.complete){Files.writeString(root.resolve("client.json"),new Gson().toJson(Map.of("status","REAL_CHAT_CLIENT_COMPLETE","axeFrames",axeFrames,"craftingTableFrames",tableFrames)));finish();}return;}
 var token=FeedbackNineSmokeServer.approval;if(token!=null&&!token.equals(sentApproval)){sentApproval=token;mc.player.connection.sendCommand("ai access_reply "+token+" "+FeedbackNineSmokeServer.approvalChoice);}
 if(FeedbackNineSmokeServer.lockStep>FeedbackNineSmokeServer.lockSent){int step=FeedbackNineSmokeServer.lockStep;var pos=step==1||step==5?new net.minecraft.core.BlockPos(0,111,0):new net.minecraft.core.BlockPos(-5+step,111,2);mc.gameMode.useItemOn(mc.player,net.minecraft.world.InteractionHand.MAIN_HAND,new net.minecraft.world.phys.BlockHitResult(net.minecraft.world.phys.Vec3.atCenterOf(pos),net.minecraft.core.Direction.UP,pos,false));FeedbackNineSmokeServer.lockSent=step;}
 if(phase==1&&FeedbackNineSmokeServer.uiReady){if(axeFrames==0||tableFrames==0)throw new IllegalStateException("BODY_HELD_ITEMS_NOT_CLIENT_VISIBLE");modelScreen=ControlCenterScreen.create(null,dev.mineagent.runtime.api.config.PanelSection.PROVIDERS);mc.setScreen(modelScreen);phase=2;wait=0;}
 if(phase==2&&++wait>20){var names=modelScreen.children().stream().filter(c->c instanceof net.minecraft.client.gui.components.Button).map(c->((net.minecraft.client.gui.components.Button)c).getMessage().getString()).toList();if(!names.containsAll(List.of("DeepSeek","GLM","OpenAI","Ollama","保存"))||names.contains("Comfy")||names.contains("Key"))throw new IllegalStateException("MODEL_PAGE_LAYOUT");var key=modelScreen.children().stream().filter(c->c instanceof net.minecraft.client.gui.components.EditBox&&((net.minecraft.client.gui.components.EditBox)c).getMessage().getString().equals("API Key")).map(c->(net.minecraft.client.gui.components.EditBox)c).findFirst().orElseThrow();busy=true;mc.getSingleplayerServer().submit(()->dev.mineagent.runtime.neoforge.MineAgentRuntimeServices.config(mc.getSingleplayerServer()).secretValue("provider.openai.apiKey").orElseThrow()).whenComplete((value,error)->mc.execute(()->{try{if(error!=null)throw new IllegalStateException("INLINE_KEY_FIXTURE_SOURCE");key.setValue(value);generation=PanelSnapshotInbox.generation();for(var c:List.copyOf(modelScreen.children()))if(c instanceof net.minecraft.client.gui.components.Button b&&b.getMessage().getString().equals("保存"))b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));phase=3;wait=0;}catch(Exception e){FeedbackNineSmokeServer.failure=e.toString();}finally{busy=false;}}));}
 if(phase==3&&++wait>20&&PanelSnapshotInbox.generation()>generation){if(mc.screen!=modelScreen)throw new IllegalStateException("INLINE_KEY_LEFT_SCREEN");Files.writeString(root.resolve("native-model-page.json"),"{\"status\":\"INLINE_KEY_PRESETS_NO_COMFY_VERIFIED\"}");net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),img->{try(img){img.writeToFile(root.resolve("native-model-page.png"));}catch(Exception e){FeedbackNineSmokeServer.failure=e.toString();}});mc.setScreen(null);WebGuiHostAdapter.INSTANCE.open();phase=4;wait=0;}
 var host=WebGuiHostAdapter.INSTANCE;if(phase>=4&&host.ready()&&ticks%10==0)script("window.mineagentQuery({request:JSON.stringify({channel:'conversationAgentProbe',packageText:document.querySelector('[data-view-id=runtime-package-catalog]')?.innerText??'',faces:document.querySelector('.scene-preview-canvas')?.dataset.faces??'',access:!!document.querySelector('[data-agent-card=\""+FeedbackNineSmokeServer.agent+"\"]'),previewTitle:document.querySelector('[data-view-id=runtime-preview]')?.innerText??''}),persistent:false,onSuccess(){},onFailure(){}});");
 if(phase==4&&host.ready()&&++wait>20){script("document.querySelector('#open-agents').click();document.querySelector('#open-package-catalog').click();");phase=5;wait=0;}
 if(phase==5&&probe!=null&&probe.get("packageText").getAsString().contains("动画测试体")&&++wait>20){script("[...document.querySelectorAll('#package-creatures button')].find(b=>b.textContent==='预览生物').click();");phase=6;wait=0;}
 if(phase==6&&probe!=null&&probe.get("previewTitle").getAsString().contains("动画测试体")&&!probe.get("faces").getAsString().isEmpty()&&++wait>20){script("[...document.querySelectorAll('#package-catalog-list button')].find(b=>b.textContent==='预览物品 / 模型').click();");phase=7;wait=0;}
 if(phase==7&&++wait>25){script("const b=[...document.querySelectorAll('#package-catalog-detail button')].find(b=>b.textContent.includes('models/item.json'));if(b)b.click();");phase=8;wait=0;}
 if(phase==8&&probe!=null&&probe.get("previewTitle").getAsString().contains("预览测试物品")&&++wait>25){Files.writeString(root.resolve("package-preview.json"),probe.toString());script("const card=document.querySelector('[data-agent-card=\""+FeedbackNineSmokeServer.agent+"\"]'),panel=[...card.querySelectorAll('details')].find(d=>d.querySelector('summary')?.textContent==='响应权限（仅创建者）');panel.querySelector('select').value='ALLOW_LIST';[...panel.querySelectorAll('button')].find(b=>b.textContent==='保存响应模式').click();");phase=9;wait=0;}
 if(phase==9&&++wait>30){var s=mc.getSingleplayerServer();busy=true;s.submit(()->dev.mineagent.runtime.neoforge.ui.ServerChatAccess.policy(s,FeedbackNineSmokeServer.agent).mode()).whenComplete((mode,error)->mc.execute(()->{busy=false;if(error!=null||!mode.equals("ALLOW_LIST"))FeedbackNineSmokeServer.failure="F2_CHAT_ACCESS_MODE_NOT_SAVED";else{host.hideWorkspace();phase=10;wait=0;mc.player.setYRot(-90);mc.player.setXRot(10);}}));}
 if(phase==10&&++wait>80){var c=mc.level.getEntity(FeedbackNineSmokeServer.creature);if(c!=null)mc.gameMode.attack(mc.player,c);phase=11;wait=0;}
 if(phase==11&&++wait>80){var seen=dev.mineagent.runtime.neoforge.client.objects.RuntimeCreatureRenderer.animationsSeen.getOrDefault(FeedbackNineSmokeServer.creature,Set.of());Files.writeString(root.resolve("animations.json"),new Gson().toJson(Map.of("seen",seen,"draws",dev.mineagent.runtime.neoforge.client.objects.RuntimeCreatureRenderer.drawn.getOrDefault(FeedbackNineSmokeServer.creature,0))));FeedbackNineSmokeServer.uiDone=true;phase=12;}
 if(phase==12&&FeedbackNineSmokeServer.entityLocked&&!FeedbackNineSmokeServer.lockedInputSent&&++entityWait>20){var target=mc.level.getEntity(FeedbackNineSmokeServer.creature);if(target!=null){mc.gameMode.interact(mc.player,target,new net.minecraft.world.phys.EntityHitResult(target,target.position().add(0,.4,0)),net.minecraft.world.InteractionHand.MAIN_HAND);mc.gameMode.attack(mc.player,target);FeedbackNineSmokeServer.lockedInputSent=true;entityWait=0;}}
 if(phase==12&&FeedbackNineSmokeServer.entityUnlocked&&!FeedbackNineSmokeServer.unlockedInputSent&&++entityWait>20){var target=mc.level.getEntity(FeedbackNineSmokeServer.creature);if(target!=null){mc.gameMode.interact(mc.player,target,new net.minecraft.world.phys.EntityHitResult(target,target.position().add(0,.4,0)),net.minecraft.world.InteractionHand.MAIN_HAND);FeedbackNineSmokeServer.unlockedInputSent=true;}}
 if(phase==12&&FeedbackNineSmokeServer.complete){Files.writeString(root.resolve("client.json"),new Gson().toJson(Map.of("status","NATIVE_BODY_LOCKS_INLINE_KEY_CATALOG_ACCESS_UI_VERIFIED","axeFrames",axeFrames,"craftingTableFrames",tableFrames,"osInputInjected",false)));finish();}
 }catch(Exception e){Files.writeString(root.resolve("client-failure.json"),new Gson().toJson(Map.of("error",e.toString(),"phase",phase,"probe",probe==null?new JsonObject():probe)));done=true;dev.mineagent.runtime.neoforge.client.cinematic.CinematicCaptureClient.finish();}}
 private static void finish(){done=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");Minecraft.getInstance().stop();}
 private FeedbackNineSmokeClient(){}
}
