package dev.mineagent.runtime.neoforge.client.webui;
import com.google.gson.*;import dev.mineagent.runtime.neoforge.client.screen.*;import dev.mineagent.runtime.neoforge.client.language.ClientLanguage;import dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox;import net.minecraft.client.Minecraft;import net.minecraft.client.gui.components.*;import java.nio.file.*;import java.util.*;
/** Actual Native/F2 language transitions; no model requests, no OS input. */
public final class LanguageUiSmokeClient {
 private static int ticks,phase,wait;private static boolean done,creating;private static JsonObject probe;private static UUID agent;private static String providerModel;
 public static boolean active(){return Boolean.getBoolean("mineagent.conversationAgentSmoke")&&System.getProperty("mineagent.conversationAgentScenario","").equals("language_ui");}
 public static void accept(JsonObject p){probe=p;}
 private static void require(boolean v,String code){if(!v)throw new IllegalStateException(code);}
 private static void script(String s){var h=WebGuiHostAdapter.INSTANCE;h.browser().executeJavaScript("(()=>{"+s+"})();",h.browser().getURL(),0);}
 private static void click(net.minecraft.client.gui.screens.Screen screen,String text){var b=screen.children().stream().filter(v->v instanceof Button button&&button.getMessage().getString().equals(text)).map(v->(Button)v).findFirst().orElseThrow(()->new IllegalStateException("NATIVE_BUTTON_MISSING:"+text));require(b.active,"BUTTON_DISABLED");b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));}
 private static void screenshot(Path p){var mc=Minecraft.getInstance();net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),img->{try(img){img.writeToFile(p);}catch(Exception e){throw new IllegalStateException(e);}});}
 public static void tick()throws Exception{if(done)return;var mc=Minecraft.getInstance();ticks++;var root=Files.createDirectories(mc.gameDirectory.toPath().resolve("language-ui-smoke"));try{if(ticks>4200)throw new IllegalStateException("LANGUAGE_UI_TIMEOUT_"+phase);if(mc.player==null||creating)return;
  if(phase==0){String fp=PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","");if(fp.isEmpty()||new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fp)!=dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){if(mc.screen instanceof ControlCenterScreen s)for(var c:List.copyOf(s.children()))if(c instanceof Button b&&b.active&&b.getMessage().getString().contains("信任此服务器"))b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));return;}if(++wait==1)mc.player.connection.sendCommand("ai accept");if(wait<35)return;require(ClientLanguage.language().equals("zh_cn"),"NOT_CHINESE_DEFAULT");var panel=ControlCenterScreen.create(null);mc.setScreen(panel);click(panel,"语言");require(mc.screen instanceof LanguageScreen,"NATIVE_LANGUAGE_ENTRY");screenshot(root.resolve("native-panel-zh.png"));mc.screen.onClose();creating=true;mc.getSingleplayerServer().submit(()->{var s=mc.getSingleplayerServer();var p=s.getPlayerList().getPlayer(mc.player.getUUID());s.getPlayerList().op(p.nameAndId());providerModel=dev.mineagent.runtime.neoforge.MineAgentRuntimeServices.config(s).snapshot().values().get("provider.openai.model");return dev.mineagent.runtime.neoforge.MineAgentRuntimeServices.bodies(s).createPersistentAt("更多",p.getUUID(),p.level(),p.position().add(2,0,0)).agentId();}).whenComplete((id,error)->mc.execute(()->{creating=false;if(error!=null)throw new IllegalStateException(error);agent=id;mc.setScreen(null);WebGuiHostAdapter.INSTANCE.open();phase=1;wait=0;}));}
  var h=WebGuiHostAdapter.INSTANCE;
  if(phase==1&&h.ready()&&++wait>35){script("document.querySelector('#more-menu').open=true;document.querySelector('#open-language').click();");phase=2;wait=0;}
  if(phase>=2&&phase<=5&&h.ready()&&ticks%10==0)script("const root=document.querySelector('[data-view-id=runtime-language]');window.mineagentQuery({request:JSON.stringify({channel:'conversationAgentProbe',language:document.documentElement.dataset.uiLanguage,chat:document.querySelector('#open-chat')?.textContent,more:document.querySelector('#more-menu summary')?.textContent,about:document.querySelector('#open-about')?.textContent,choice:root?.querySelector('#ui-language-choice')?.value??'',ready:!!root?.querySelector('#ui-language-apply')&&!root.querySelector('#ui-language-apply').disabled,body:document.querySelector('[data-view-id=runtime-chat]')?.textContent??'',aboutFields:Object.fromEntries([...document.querySelectorAll('[data-about-field]')].map(n=>[n.dataset.aboutField,n.textContent])),agentText:document.querySelector('[data-agent-card=\""+agent+"\"]')?.textContent??''}),persistent:false,onSuccess(){},onFailure(){}});");
  if(phase==2&&probe!=null&&probe.get("ready").getAsBoolean()){require(probe.get("language").getAsString().equals("zh_cn")&&probe.get("chat").getAsString().equals("对话"),"F2_DEFAULT_NOT_CHINESE");screenshot(root.resolve("f2-zh.png"));script("document.querySelector('#ui-language-choice').value='en_us';document.querySelector('#ui-language-apply').click();");phase=3;wait=0;probe=null;}
  if(phase==3&&probe!=null&&probe.get("language").getAsString().equals("en_us")){require(probe.get("chat").getAsString().equals("Chat")&&probe.get("more").getAsString().equals("More")&&probe.get("about").getAsString().equals("About"),"F2_ENGLISH_LABELS");var prefs=new dev.mineagent.runtime.client.control.UiLanguagePreferences(mc.gameDirectory.toPath().resolve("config/mineagent-ui-language.properties"));require(prefs.state().language().equals("en_us"),"ENGLISH_NOT_PERSISTED");Files.writeString(root.resolve("english.json"),probe.toString());script("document.querySelector('#more-menu').open=true;document.querySelector('#open-about').click();document.querySelector('#open-agents').click();");phase=4;wait=0;}
  if(phase==4&&probe!=null&&probe.get("agentText").getAsString().contains("更多")&&probe.getAsJsonObject("aboutFields").size()==4&&++wait>20){require(probe.get("agentText").getAsString().contains("Default model")&&!probe.get("agentText").getAsString().contains("默认模型")&&probe.get("agentText").getAsString().contains("Creative"),"ENGLISH_AGENT_TERMS");Files.writeString(root.resolve("user-data-preserved.json"),probe.toString());screenshot(root.resolve("f2-en.png"));h.hideWorkspace();var panel=ControlCenterScreen.create(null);mc.setScreen(panel);require(panel.getTitle().getString().equals("MineAgent Control Center"),"NATIVE_ENGLISH_TITLE");click(panel,"About");require(mc.screen instanceof AboutScreen,"NATIVE_ENGLISH_ABOUT");phase=6;wait=0;}
  if(phase==6&&++wait>25){var text=mc.screen.children().stream().filter(c->c instanceof StringWidget).map(c->((StringWidget)c).getMessage().getString()).collect(java.util.stream.Collectors.joining("\n"));require(text.contains("Version:")&&text.contains("1.0.0")&&text.contains("Developer:"),"NATIVE_ENGLISH_FIELDS");Files.writeString(root.resolve("native-en.json"),text);screenshot(root.resolve("native-en.png"));mc.screen.onClose();click(mc.screen,"Language");require(mc.screen instanceof LanguageScreen,"NATIVE_EN_LANGUAGE_ENTRY");phase=10;wait=0;}
  if(phase==10&&++wait>20){screenshot(root.resolve("native-language-en.png"));click(mc.screen,"简体中文");click(mc.screen,"Apply language");phase=7;wait=0;}
  if(phase==7&&ClientLanguage.language().equals("zh_cn")&&mc.screen instanceof ControlCenterScreen&&++wait>15){require(mc.screen.getTitle().getString().equals("MineAgent 控制中心"),"NATIVE_CHINESE_RESTORE");mc.setScreen(null);h.open();phase=8;wait=0;}
  if(phase==8&&h.ready()&&++wait>35){require(new dev.mineagent.runtime.client.control.UiLanguagePreferences(mc.gameDirectory.toPath().resolve("config/mineagent-ui-language.properties")).state().language().equals("zh_cn"),"CHINESE_NOT_PERSISTED");creating=true;mc.getSingleplayerServer().submit(()->{var s=mc.getSingleplayerServer();return providerModel.equals(dev.mineagent.runtime.neoforge.MineAgentRuntimeServices.config(s).snapshot().values().get("provider.openai.model"))&&dev.mineagent.runtime.neoforge.MineAgentRuntimeServices.bodies(s).body(agent).orElseThrow().getName().getString().equals("更多");}).whenComplete((ok,error)->mc.execute(()->{creating=false;try{require(error==null&&ok,"LANGUAGE_CHANGED_MODEL_OR_AGENT_NAME");Files.writeString(root.resolve("result.json"),"{\"status\":\"BILINGUAL_NATIVE_F2_LOCAL_PERSISTENCE_VERIFIED\",\"modelRequests\":0,\"userDataUnchanged\":true}");done=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");mc.stop();}catch(Exception ex){throw new IllegalStateException(ex);}}));phase=9;}
 }catch(Exception e){Files.writeString(root.resolve("failure.json"),new Gson().toJson(Map.of("error",e.toString(),"phase",phase,"probe",probe==null?new JsonObject():probe)));done=true;mc.stop();}}
 private LanguageUiSmokeClient(){}
}
