package dev.mineagent.runtime.neoforge.client.webui;
import com.google.gson.*;
import dev.mineagent.runtime.api.ui.UiProtocol.*;
import dev.mineagent.runtime.neoforge.ui.WorldUiSmokeServer;
import net.minecraft.client.Minecraft;
import java.nio.file.*;
import java.util.*;
/** Real GUI delegation and host mutation through a clearly-labelled localhost planner. */
public final class LivePlacementSmokeClient {
    private static final Gson JSON=new Gson();public static boolean finished;private static int phase,ticks,after;private static boolean busy,released;private static String view;private static JsonObject probe,before;
    private static UUID packageId;private static long packageRevision;private static boolean reopening,reopenDone,opacityRestoreRequested,reopenShot,recoveryShot,shotPending;private static String reopenedView;private static int reopenTicks;
    private LivePlacementSmokeClient(){}public static void accept(JsonObject value){probe=value;}
    public static String mode(){return System.getProperty("mineagent.livePlacementSmoke","");}
    public static Double opacity(){return mode().startsWith("opacity-")?(mode().equals("opacity-zero")?0d:.5):null;}
    public static boolean realModel(){return mode().equals("real");}
    private static Path root(){return Minecraft.getInstance().gameDirectory.toPath().resolve(WorldUiSmokeServer.directory()).resolve("live-placement");}
    private static void main(String code){var h=WebGuiHostAdapter.INSTANCE;h.browser().executeJavaScript("(()=>{"+code+"})();",h.browser().getURL(),0);}
    private static void save(String name,Object value)throws Exception{Files.writeString(root().resolve(name+".json"),JSON.toJson(value));}
    private static void require(boolean ok,String code){if(!ok)throw new IllegalStateException(code);}
    private static void rejectUnsupportedDefault()throws Exception{
        var blobs=new HashMap<String,byte[]>();var refs=new HashMap<String,dev.mineagent.runtime.api.packages.RuntimeResourceRef>();
        for(var e:Map.of("ui/index.html","<!doctype html><p>UNSUPPORTED_OPACITY_DEFAULT</p>","ui/view-settings.json","{\"schema\":1,\"entries\":{\"ui/index.html\":{\"anchor\":\"CENTER\",\"width\":400,\"height\":300,\"opacity\":0.35}}}").entrySet()){
            byte[] bytes=e.getValue().getBytes(java.nio.charset.StandardCharsets.UTF_8);String hash=dev.mineagent.runtime.api.ui.UiCapture.sha256(bytes);blobs.put(hash,bytes);refs.put(e.getKey(),new dev.mineagent.runtime.api.packages.RuntimeResourceRef(e.getKey(),hash,dev.mineagent.runtime.api.packages.RuntimeResourceSide.CLIENT,e.getKey().endsWith("html")?"text/html":"application/json",bytes.length));}
        var e=refs.get("ui/index.html");var p=new dev.mineagent.runtime.api.packages.RuntimePackage(UUID.randomUUID(),dev.mineagent.runtime.api.packages.RuntimePackageType.CONTENT,"Unsupported default fixture","1",dev.mineagent.runtime.api.packages.ActivationMode.HOT_RUNTIME,Map.of(),Set.of(),Map.of("ui",new dev.mineagent.runtime.api.packages.RuntimeEntrypoint(e.path(),e.side(),e.sha256())),Map.of(),refs,dev.mineagent.runtime.api.packages.PackageOrigin.LOCAL_STUDIO,false,1,e.sha256(),"LOCAL_NEGATIVE_NOT_MODEL",0);
        boolean denied=false;try{WebGuiHostAdapter.INSTANCE.openPackagePreview(p,blobs::get,e.path(),false);}catch(IllegalStateException rejected){denied="UI_OPACITY_BACKEND_REQUIRED".equals(rejected.getMessage());}require(denied,"UNSUPPORTED_DEFAULT_WAS_OPENED");save("package-default-backend-denied",Map.of("status","UI_OPACITY_BACKEND_REQUIRED"));
    }
    private static void reopenScreenshot(String file,boolean recovery){shotPending=true;net.minecraft.client.Screenshot.takeScreenshot(Minecraft.getInstance().getMainRenderTarget(),image->{try(image){image.writeToFile(root().resolve(file));Minecraft.getInstance().execute(()->{shotPending=false;if(recovery)recoveryShot=true;else reopenShot=true;});}catch(Exception e){Minecraft.getInstance().execute(()->fail(e));}});}
    private static String action(JsonObject layout){return JSON.toJson(Map.of("action","present","operationId",UUID.randomUUID(),"expectedLayoutRevision",layout.get("revision").getAsLong(),"placement",Map.of("anchor","TOP_RIGHT","width",500,"height",360,"offsetX",-24,"offsetY",12)));}
    public static void step(String sourceView){if(finished)return;var mc=Minecraft.getInstance();var host=WebGuiHostAdapter.INSTANCE;ticks++;
        try{Files.createDirectories(root());require(ticks<2200,"LIVE_PLACEMENT_TIMEOUT");if(ticks%30==0)save("progress",Map.of("phase",phase,"ticks",ticks,"taskStatus",WorldUiSmokeServer.presentationStatus,"layout",view==null||host.viewLayout(view)==null?new JsonObject():host.viewLayout(view)));
            if(phase==0&&!busy&&WorldUiSmokeServer.presentationAgent!=null){busy=true;var pkg=host.viewPackage(sourceView);packageId=pkg.packageId();packageRevision=pkg.revision();PackagePreviewClient.open(pkg.packageId(),pkg.revision()).whenComplete((r,e)->mc.execute(()->{try{if(e!=null||r.code()!=Code.ACCEPTED)throw new IllegalStateException("PLACEMENT_PREVIEW_FAILED",e);view=r.values().get("viewId");phase=1;busy=false;}catch(Exception failed){fail(failed);}}));}
            if(phase==1&&!busy&&host.packageLoaded(view)&&host.viewLayout(view)!=null){if(mode().equals("opacity-unavailable"))rejectUnsupportedDefault();busy=true;PageControlClient.prepare(view).whenComplete((r,e)->mc.execute(()->{try{if(e!=null||r.code()!=Code.ACCEPTED)throw new IllegalStateException("PLACEMENT_BIND_FAILED",e);before=UiPresentationClient.observe(view);if(opacity()!=null&&!mode().equals("opacity-unavailable")){require(before.get("opacity").getAsDouble()==.35&&before.get("opacitySupported").getAsBoolean(),"PACKAGE_OPACITY_DEFAULT_FAILED");save("package-opacity-default",before);}UiPresentationClient.apply(view,host.packageUrl(view),"fixture-denied",before,action(before),()->true).whenComplete((v,error)->mc.execute(()->{try{require(error==null&&JsonParser.parseString(v).getAsJsonObject().get("status").getAsString().equals("UI_PRESENTATION_DENIED"),"PLAYER_PRESENTATION_NOT_DENIED");save("player-denied",JsonParser.parseString(v));main("document.querySelector('[data-view-id=\""+view+"\"] [data-action=open-page-delegation]').click();");phase=2;busy=false;}catch(Exception failed){fail(failed);}}));}catch(Exception failed){fail(failed);}}));}
            if(view!=null&&ticks%10==0)main("const c=document.querySelector('[data-delegation-view=\""+view+"\"]');window.mineagentQuery({request:JSON.stringify({channel:'livePlacementProbe',ready:!!c,agentReady:!!c&&[...c.querySelectorAll('select[data-field=agent] option')].some(o=>o.value==='"+WorldUiSmokeServer.presentationAgent+"')}),persistent:false,onSuccess(){},onFailure(){}});");
            if(phase==2&&probe!=null&&probe.get("agentReady").getAsBoolean()){main("const c=document.querySelector('[data-delegation-view=\""+view+"\"]');for(const [field,value]of [['agent','"+WorldUiSmokeServer.presentationAgent+"'],['goal','请把当前窗口摆到可用区域右上角：宽500、高360（CSS像素），右边缘离可用区域右边24，顶部离可用区域顶部12。只调整窗口，不触碰页面内容"+(opacity()==null?"":"，Native透明度设为"+opacity())+"']]){const e=c.querySelector('[data-field='+field+']');e.value=value;e.dispatchEvent(new Event('input',{bubbles:true}));}for(const field of ['presentationOnly','consent']){const e=c.querySelector('[data-field='+field+']');e.checked=true;e.dispatchEvent(new Event('change',{bubbles:true}));}c.querySelector('[data-action=delegate]').click();");phase=3;}
            if(phase==3&&Set.of("stale","cancel").contains(mode())&&!released&&Files.exists(mc.gameDirectory.toPath().resolve("live-placement-provider-pending"))){before=host.viewLayout(view);save("pending-before",before);if(mode().equals("stale")){org.lwjgl.glfw.GLFW.glfwSetWindowSize(mc.getWindow().handle(),1400,900);phase=31;after=ticks+40;}else{main("document.querySelector('[data-view-id=\""+view+"\"] .agent-stop').click();");phase=32;}}
            if(phase==31&&ticks>=after){var current=host.viewLayout(view);require(current.get("revision").getAsLong()>before.get("revision").getAsLong(),"STALE_LAYOUT_PERTURBATION_FAILED");save("resized-before-model-return",current);Files.writeString(mc.gameDirectory.toPath().resolve("live-placement-provider-release"),"Release explicitly stale model action after actual resize.");released=true;phase=3;}
            if(phase==32&&WorldUiSmokeServer.presentationStatus.equals("USER_INTERRUPTED")){Files.writeString(mc.gameDirectory.toPath().resolve("live-placement-provider-release"),"Release only after Native task stopped.");released=true;phase=33;after=ticks+80;}
            if(phase==33&&ticks>=after){var current=host.viewLayout(view);require(current.getAsJsonObject("bounds").equals(before.getAsJsonObject("bounds"))&&!current.get("source").getAsString().equals("AGENT"),"CANCELLED_PRESENTATION_MUTATED_LAYOUT");save("cancelled-after",current);phase=5;}
            if(phase==3&&mode().equals("opacity-unavailable")&&WorldUiSmokeServer.presentationStatus.equals("ACTION_UI_OPACITY_BACKEND_REQUIRED")){var layout=UiPresentationClient.observe(view);require(!layout.get("opacitySupported").getAsBoolean()&&layout.getAsJsonObject("bounds").equals(before.getAsJsonObject("bounds")),"UNSUPPORTED_OPACITY_CHANGED_LAYOUT");save("backend-rejected",layout);phase=5;}
            if(phase==3&&!WorldUiSmokeServer.presentationStatus.isBlank()&&!Set.of("WAIT_RENDERER","RUNNING","PRESENTATION_VERIFIED").contains(WorldUiSmokeServer.presentationStatus))throw new IllegalStateException("LIVE_PLACEMENT_TERMINAL_"+WorldUiSmokeServer.presentationStatus);
            if(phase==3&&WorldUiSmokeServer.presentationStatus.equals("PRESENTATION_VERIFIED")){var layout=UiPresentationClient.observe(view);if(opacity()!=null){if(!layout.has("opacityPaint"))return;require(Double.compare(layout.get("opacity").getAsDouble(),opacity())==0,"OPACITY_NOT_APPLIED");save("opacity-native",WebGuiAtlasCompositor.snapshot());}var b=layout.getAsJsonObject("bounds");var area=layout.getAsJsonObject("area");require(layout.get("source").getAsString().equals("AGENT")&&Math.abs(b.get("width").getAsDouble()-500)<1&&Math.abs(b.get("height").getAsDouble()-360)<1&&Math.abs(b.get("x").getAsDouble()-(area.get("x").getAsDouble()+area.get("width").getAsDouble()-524))<1&&Math.abs(b.get("y").getAsDouble()-area.get("y").getAsDouble()-12)<1,"PRESENTATION_FINAL_BOUNDS");save("applied-native",layout);phase=4;after=ticks+30;}
            if(phase==4&&ticks>=after&&!busy){busy=true;var layout=host.viewLayout(view);UiPresentationClient.apply(view,host.packageUrl(view),"after-stop",layout,action(layout),()->true).whenComplete((v,e)->mc.execute(()->{try{require(e==null&&JsonParser.parseString(v).getAsJsonObject().get("status").getAsString().equals("UI_PRESENTATION_DENIED"),"STOPPED_PRESENTATION_NOT_DENIED");save("after-completion-denied",JsonParser.parseString(v));busy=false;phase=5;}catch(Exception failed){fail(failed);}}));}
            if(phase==5&&!busy){busy=true;phase=6;net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),img->{try(img){img.writeToFile(root().resolve("result.png"));busy=false;}catch(Exception e){mc.execute(()->fail(e));}});}
            if(phase==6&&!busy){save("result",Map.of("status",WorldUiSmokeServer.presentationStatus,"mode",mode(),"providerMode",realModel()?"REAL_MODEL":"CONTROLLED_LOCALHOST","realModel",realModel(),"configuredModel",System.getProperty("mineagent.livePlacementModel","controlled-live-placement"),"fullV1",false));finished=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_LIVE_PLACEMENT_OK");}
        }catch(Exception e){fail(e);}
    }
    private static void fail(Exception e){try{save("failure",Map.of("phase",phase,"error",e.toString()));}catch(Exception ignored){}WorldUiSmokeServer.failure="LIVE_PLACEMENT_FAILED_"+phase;}
    public static boolean afterReopen(){if(Set.of("cancel","opacity-unavailable").contains(mode())||reopenDone)return true;var mc=Minecraft.getInstance();var host=WebGuiHostAdapter.INSTANCE;
        try{if(shotPending)return false;require(++reopenTicks<180,"LIVE_PLACEMENT_RESTORE_TIMEOUT");if(!reopening){reopening=true;PackagePreviewClient.open(packageId,packageRevision).whenComplete((r,e)->mc.execute(()->{if(e!=null||r.code()!=Code.ACCEPTED){fail(new IllegalStateException("LIVE_PLACEMENT_REOPEN_FAILED",e));return;}reopenedView=r.values().get("viewId");}));return false;}
            var layout=reopenedView==null?null:UiPresentationClient.observe(reopenedView);if(layout==null||!layout.get("visible").getAsBoolean()||!opacityRestoreRequested&&!layout.get("source").getAsString().equals("AGENT"))return false;
            var b=layout.getAsJsonObject("bounds");var a=layout.getAsJsonObject("area");require(Math.abs(b.get("x").getAsDouble()-(a.get("x").getAsDouble()+a.get("width").getAsDouble()-524))<1&&Math.abs(b.get("width").getAsDouble()-500)<1&&Math.abs(b.get("height").getAsDouble()-360)<1,"LIVE_PLACEMENT_RESTORED_WRONG_BOUNDS");if(opacity()!=null){if(!layout.has("opacityPaint")||opacityRestoreRequested&&layout.get("opacity").getAsDouble()!=1)return false;require(Double.compare(layout.get("opacity").getAsDouble(),opacityRestoreRequested?1:opacity())==0,"OPACITY_RESTORE_FAILED");}
            if(opacity()!=null&&!reopenShot){reopenScreenshot("new-browser-opacity.png",false);return false;}
            if(!opacityRestoreRequested)save("new-browser-restored",layout);
            if(mode().equals("opacity-zero")&&!Boolean.getBoolean("mineagent.opacityPersistenceSmoke")&&!opacityRestoreRequested){opacityRestoreRequested=true;main("document.querySelector('[data-restore-opacity-view=\""+reopenedView+"\"]').click();");return false;}
            if(opacityRestoreRequested){if(layout.get("opacity").getAsDouble()!=1||!layout.get("source").getAsString().equals("PLAYER"))return false;save("player-opacity-restored",layout);if(!recoveryShot){reopenScreenshot("player-opacity-restored.png",true);return false;}}
            if(Boolean.getBoolean("mineagent.opacityPersistenceSmoke"))OpacityPersistenceSmokeClient.prepared(packageId,packageRevision,opacity(),layout,WorldUiSmokeServer.RUN);
            reopenDone=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_LIVE_PLACEMENT_RESTORE_OK");return true;
        }catch(Exception e){fail(e);return false;}
    }
}
