package dev.mineagent.runtime.neoforge.client.webui;
import com.google.gson.*;import dev.mineagent.runtime.neoforge.ui.MediaToolsSmokeServer;import dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen;import dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox;import net.minecraft.client.Minecraft;import java.nio.file.*;import java.util.*;
public final class MediaToolsSmokeClient {
 private static int ticks,phase,wait;private static boolean done,busy;private static JsonObject probe;private static int displayedThinking;private static long hiddenBefore;private static boolean clicked;
 public static void accept(JsonObject p){probe=p;}public static void chat(net.minecraft.network.chat.Component c){if(c.getString().startsWith("[造物助手][思考]"))displayedThinking++;}
 private static void script(String code){var h=WebGuiHostAdapter.INSTANCE;h.browser().executeJavaScript("(()=>{"+code+"})();",h.browser().getURL(),0);}
 public static void tick()throws Exception{if(done)return;var mc=Minecraft.getInstance();ticks++;Path root=Files.createDirectories(mc.gameDirectory.toPath().resolve("media-tools-smoke"));try{if(ticks%100==0)Files.writeString(root.resolve("client-progress.json"),new Gson().toJson(Map.of("phase",phase,"probe",probe==null?new JsonObject():probe,"complete",MediaToolsSmokeServer.complete)));if(!MediaToolsSmokeServer.failure.isEmpty())throw new IllegalStateException(MediaToolsSmokeServer.failure);if(ticks>30000)throw new IllegalStateException("MEDIA_TIMEOUT_"+phase);if(mc.player==null||!MediaToolsSmokeServer.ready||busy)return;
 if(phase==0){if(!Files.exists(root.resolve("mod-icon.json"))){String logo=net.neoforged.fml.ModList.get().getModContainerById("mineagent_runtime").orElseThrow().getModInfo().getLogoFile().orElseThrow();try(var in=MediaToolsSmokeClient.class.getResourceAsStream("/"+logo)){if(in==null)throw new IllegalStateException("MOD_ICON_NOT_PACKAGED");byte[] data=in.readAllBytes();String hash=dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer.sha256(data);if(!hash.equals("2421874f851588083e1339640a0284c1ad10a24069caa9b6ab7b354ab1e58f58"))throw new IllegalStateException("MOD_ICON_DIFFERS_FROM_WORKSPACE");var png=javax.imageio.ImageIO.read(new java.io.ByteArrayInputStream(data));if(png==null||png.getWidth()!=1024||png.getHeight()!=1024)throw new IllegalStateException("MOD_ICON_INVALID");Files.writeString(root.resolve("mod-icon.json"),new Gson().toJson(Map.of("logoFile",logo,"sha256",hash,"status","WORKSPACE_ICON_PACKAGED_AND_RECOGNIZED")));}}String fp=PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","");if(fp.isEmpty()||new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fp)!=dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){if(mc.screen instanceof ControlCenterScreen screen)for(var child:List.copyOf(screen.children()))if(child instanceof net.minecraft.client.gui.components.Button b&&b.active&&b.getMessage().getString().contains("信任此服务器"))b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));return;}if(++wait==1)mc.player.connection.sendCommand("ai accept");if(wait<40)return;busy=true;var preferences=dev.mineagent.runtime.neoforge.client.chat.NativeChatPreferencesClient.view();dev.mineagent.runtime.neoforge.client.chat.NativeChatPreferencesClient.save(false,((Number)preferences.get("revision")).longValue()).whenComplete((v,e)->mc.execute(()->{if(e!=null)MediaToolsSmokeServer.failure=e.toString();busy=false;}));phase=1;return;}
 if(phase==1){MediaToolsSmokeServer.clientReady=true;mc.setScreen(null);if(!MediaToolsSmokeServer.saved())mc.player.connection.sendChat("@造物助手 保持正在进行的跟随，不重建自己。为自己生成蓝白机器人PNG皮肤并热切换，再导出当前皮肤，只把双眼改为金色再次应用。创建橙色球形模型JSON文件，给下载入口并打开可旋转缩放预览，最后打开皮肤界面。不要修改其它游戏内容。");phase=2;}
 var host=WebGuiHostAdapter.INSTANCE;if(phase>=2&&host.ready()&&ticks%10==0)script("const c=document.querySelector('.scene-preview-canvas');window.mineagentQuery({request:JSON.stringify({channel:'conversationAgentProbe',preview:!!c,previewPresetCount:document.querySelectorAll('[data-view-id=runtime-preview] select').length,packageLabel:document.querySelector('#open-package-catalog')?.textContent??'',faces:c?.dataset.faces??'',yaw:c?.dataset.yaw??'',zoom:c?.dataset.zoom??'',skins:!!document.querySelector('[data-view-id=runtime-skins] [data-skin-file]'),attachments:!!document.querySelector('#conversation-attach'),previewText:document.querySelector('[data-view-id=runtime-preview]')?.innerText??'',skinText:document.querySelector('[data-view-id=runtime-skins]')?.innerText??''}),persistent:false,onSuccess(){},onFailure(){}});");
 if(phase==2&&MediaToolsSmokeServer.complete&&probe!=null&&probe.get("skins").getAsBoolean()&&!probe.get("faces").getAsString().isEmpty()){if(displayedThinking!=0||MediaToolsSmokeServer.thinking.isEmpty()||!MediaToolsSmokeServer.saved()&&dev.mineagent.runtime.neoforge.client.chat.NativeChatPreferencesClient.hiddenMessages==0)throw new IllegalStateException("NATIVE_THINKING_FILTER_OR_HISTORY");Files.writeString(root.resolve("before-interaction.json"),probe.toString());script("const c=document.querySelector('.scene-preview-canvas'),capture=c.setPointerCapture;c.setPointerCapture=()=>{};c.dispatchEvent(new PointerEvent('pointerdown',{clientX:100,clientY:100,pointerId:1,button:0}));c.dispatchEvent(new PointerEvent('pointermove',{clientX:150,clientY:120,pointerId:1,button:0}));c.dispatchEvent(new PointerEvent('pointerup',{pointerId:1}));c.setPointerCapture=capture;c.dispatchEvent(new WheelEvent('wheel',{deltaY:-350,cancelable:true}));");phase=3;wait=0;}
 if(phase==3&&++wait>20){if(probe.get("previewPresetCount").getAsInt()!=0||!probe.get("packageLabel").getAsString().equals("包管理"))throw new IllegalStateException("PREVIEW_PRESETS_OR_PACKAGE_LABEL");if(probe.get("yaw").getAsDouble()==-.6||probe.get("zoom").getAsDouble()<=1)throw new IllegalStateException("PREVIEW_INTERACTION_NOT_UPDATED");Files.writeString(root.resolve("after-interaction.json"),probe.toString());script("[...document.querySelectorAll(\"#minimized button\")].find(b=>b.textContent===\"预览\")?.click();");phase=31;wait=0;}
 if(phase==31&&++wait>15){net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),img->{try(img){img.writeToFile(root.resolve("preview-and-skins.png"));}catch(Exception e){MediaToolsSmokeServer.failure=e.toString();}});phase=4;wait=0;}
 if(phase==4&&++wait>20){var skin=dev.mineagent.runtime.neoforge.client.AgentSkinClient.skin(MediaToolsSmokeServer.agent);if(skin==null||!skin.body().texturePath().toString().contains("dynamic_skin"))throw new IllegalStateException("CUSTOM_SKIN_NOT_NATIVE");hiddenBefore=dev.mineagent.runtime.neoforge.client.chat.NativeChatPreferencesClient.hiddenMessages;message("hidden-probe");phase=5;wait=0;}
 if(phase==5&&++wait>20){if(dev.mineagent.runtime.neoforge.client.chat.NativeChatPreferencesClient.hiddenMessages<=hiddenBefore||countThinking()!=0)throw new IllegalStateException("HIDDEN_THINKING_REACHED_CHAT");script("const t=document.querySelector('#native-thinking-visible');if(!t)throw new Error('TOGGLE_MISSING');t.checked=true;t.dispatchEvent(new Event('change'));");phase=6;wait=0;}
 if(phase==6&&++wait>20&&dev.mineagent.runtime.neoforge.client.chat.NativeChatPreferencesClient.showThinking()){message("visible-probe");phase=7;wait=0;}
 if(phase==7&&++wait>20){if(countThinking()==0)throw new IllegalStateException("VISIBLE_THINKING_MISSING");host.hideWorkspace();mc.setScreen(ControlCenterScreen.create(null,dev.mineagent.runtime.api.config.PanelSection.CONVERSATIONS));phase=8;wait=0;}
 if(phase==8&&++wait>15){boolean pressed=false;for(var child:List.copyOf(mc.screen.children()))if(child instanceof net.minecraft.client.gui.components.Button b&&b.active&&b.getMessage().getString().startsWith("聊天思考：")){b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));pressed=true;break;}if(!pressed)throw new IllegalStateException("NATIVE_THINKING_TOGGLE_MISSING");phase=9;wait=0;}
 if(phase==9&&++wait>20&&!dev.mineagent.runtime.neoforge.client.chat.NativeChatPreferencesClient.showThinking()){if(countThinking()!=0)throw new IllegalStateException("OLD_THINKING_NOT_CLEARED");Files.writeString(root.resolve("thinking-toggle.json"),new Gson().toJson(Map.of("f2Toggle",true,"nativeToggle",true,"filteredMessages",dev.mineagent.runtime.neoforge.client.chat.NativeChatPreferencesClient.hiddenMessages,"oldNativeMessagesRemoved",true,"realProviderHistoryChars",MediaToolsSmokeServer.saved()?0:MediaToolsSmokeServer.thinking.length())));mc.setScreen(null);if(MediaToolsSmokeServer.saved()){host.open();phase=10;}else phase=20;wait=0;}
 if(phase==10&&host.ready()&&++wait>20){script("document.querySelector('#conversation-attach').click();");phase=11;wait=0;}
 if(phase==11&&++wait>20){script("[...document.querySelectorAll('[data-view-id=runtime-building-files] button')].find(b=>b.textContent==='上传文件夹').click();");phase=12;wait=0;}
 if(phase==12&&++wait>40){script("const row=[...document.querySelectorAll('[data-view-id=runtime-building-files] .event-card')].find(r=>r.querySelector('strong')?.textContent==='generic-fixture');const b=row&&[...row.querySelectorAll('button')].find(b=>b.textContent==='下载');if(b&&!b.dataset.testClicked){b.dataset.testClicked='true';b.click();}");Path zip=root.resolve("downloaded-files.zip");if(Files.isRegularFile(zip)&&Files.size(zip)>0){try(var archive=new java.util.zip.ZipFile(zip.toFile())){if(archive.getEntry("空目录/")==null||archive.getEntry("empty.txt")==null||archive.getEntry("nested/bytes.dat")==null||!Arrays.equals(archive.getInputStream(archive.getEntry("nested/bytes.dat")).readAllBytes(),new byte[]{0,1,2,3})||!new String(archive.getInputStream(archive.getEntry("notes.txt")).readAllBytes(),java.nio.charset.StandardCharsets.UTF_8).equals("通用文件，不是建筑"))throw new IllegalStateException("GENERIC_FOLDER_CHANGED");}catch(java.util.zip.ZipException unfinished){return;}Files.writeString(root.resolve("generic-files.json"),"{\"status\":\"F2_ATTACHMENT_GENERIC_FOLDER_HTTP_UPLOAD_DOWNLOAD_VERIFIED\",\"emptyDirectoryPreserved\":true}");phase=20;wait=0;}}
 if(phase==20&&++wait>20){script("const p=document.querySelector('[data-skin-preset]');p.value='alex:wide';[...document.querySelectorAll('[data-view-id=runtime-skins] button')].find(b=>b.textContent==='切换内置皮肤').click();");phase=21;wait=0;}
 if(phase==21&&++wait>30){var skin=dev.mineagent.runtime.neoforge.client.AgentSkinClient.skin(MediaToolsSmokeServer.agent);if(skin!=null&&skin.body().texturePath().toString().endsWith("wide/alex.png")){verifyIdentity(false);script("[...document.querySelectorAll('[data-view-id=runtime-skins] button')].find(b=>b.textContent==='应用 PNG').click();");phase=22;wait=0;}}
 if(phase==22&&++wait>30){var skin=dev.mineagent.runtime.neoforge.client.AgentSkinClient.skin(MediaToolsSmokeServer.agent);if(skin!=null&&skin.body().texturePath().toString().contains("dynamic_skin")){verifyIdentity(true);Files.writeString(root.resolve("skin-roundtrip.json"),"{\"status\":\"PNG_BUILTIN_PNG_IDENTITY_AND_FOLLOW_VERIFIED\"}");phase=30;wait=0;}}
 if(phase==30&&++wait>20){host.hideWorkspace();Files.writeString(root.resolve("client.json"),new Gson().toJson(Map.of("status","NATIVE_PNG_PREVIEW_CHAT_TOGGLES_VERIFIED","skinTexture",dev.mineagent.runtime.neoforge.client.AgentSkinClient.skin(MediaToolsSmokeServer.agent).body().texturePath().toString(),"realProviderHistoryChars",MediaToolsSmokeServer.saved()?0:MediaToolsSmokeServer.thinking.length(),"previewDragAndZoom",true,"f2AndNativeThinkingToggles",true,"osInputInjected",false)));done=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");mc.stop();}

 }catch(Exception e){done=true;Files.writeString(root.resolve("client-failure.json"),new Gson().toJson(Map.of("error",e.toString(),"phase",phase,"probe",probe==null?new JsonObject():probe)));mc.stop();}}
 private static void verifyIdentity(boolean png){var mc=Minecraft.getInstance();mc.getSingleplayerServer().execute(()->{try{MediaToolsSmokeServer.verifyIdentity(mc.getSingleplayerServer(),png);}catch(Exception e){MediaToolsSmokeServer.failure=e.toString();}});}
 private static long countThinking(){return ((dev.mineagent.runtime.neoforge.mixin.client.ChatHistoryAccess)Minecraft.getInstance().gui.getChat()).mineagent$messages().stream().filter(m->dev.mineagent.runtime.neoforge.client.chat.NativeChatPreferencesClient.thinking(m.content())).count();}
 private static void message(String text){var mc=Minecraft.getInstance();UUID owner=mc.player.getUUID();mc.getSingleplayerServer().execute(()->mc.getSingleplayerServer().getPlayerList().getPlayer(owner).sendSystemMessage(net.minecraft.network.chat.Component.translatableWithFallback("mineagent.chat.thinking","[%s][思考]%s","造物助手",text)));}
 private MediaToolsSmokeClient(){}
}
