package dev.mineagent.runtime.neoforge.client.webui;

import com.google.gson.*;
import dev.mineagent.runtime.neoforge.compile.NativeApiSmokeServer;
import net.minecraft.client.Minecraft;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.ClientTickEvent;
import java.nio.file.*;
import java.util.*;

/** Real CEF/bridge Native API selection flow. JavaScript DOM actions only; no OS input and no Provider. */
@EventBusSubscriber(modid="mineagent_runtime",value=Dist.CLIENT)
public final class NativeApiSmokeClient {
    private static final Gson JSON=new Gson();private static JsonObject probe;private static int ticks,phase,resetAt;private static boolean opened,finished;private static UUID oldSession;
    private NativeApiSmokeClient(){}
    public static void accept(JsonObject value){if(Boolean.getBoolean("mineagent.nativeApiSmoke"))probe=value;}
    private static Path root(){return Minecraft.getInstance().gameDirectory.toPath().resolve("native-api-smoke");}
    private static void script(String code){var h=WebGuiHostAdapter.INSTANCE;h.browser().executeJavaScript("(()=>{"+code+"})();",h.browser().getURL(),0);}
    private static void action(String key,String code){script("window.__nativeApiSmoke??={};if(window.__nativeApiSmoke["+JSON.toJson(key)+"])return;const ok=(()=>{"+code+"})();if(ok)window.__nativeApiSmoke["+JSON.toJson(key)+"]=true;");}
    private static void poll(){script("window.dispatchEvent(new Event('mineagent:native-api-probe'));");}
    private static String text(){return probe==null||!probe.has("nativeText")?"":probe.get("nativeText").getAsString();}
    private static JsonObject selection(){return probe==null||!probe.has("selection")?new JsonObject():probe.getAsJsonObject("selection");}
    private static boolean coder(){return Boolean.getBoolean("mineagent.nativeApiCoderSmoke");}
    private static void require(boolean value,String code){if(!value)throw new IllegalStateException(code);}
    private static void fail(Throwable failure)throws Exception {finished=true;Files.createDirectories(root());Files.writeString(root().resolve("failure.json"),JSON.toJson(Map.of("phase",phase,"error",failure.toString(),"probe",probe==null?new JsonObject():probe)));var mc=Minecraft.getInstance();WebGuiHostAdapter.INSTANCE.close();mc.stop();}
    @SubscribeEvent public static void tick(ClientTickEvent.Post event)throws Exception {
        if(!Boolean.getBoolean("mineagent.nativeApiSmoke")||finished)return;var mc=Minecraft.getInstance();ticks++;Files.createDirectories(root());var host=WebGuiHostAdapter.INSTANCE;
        try{
            if(ticks>5000)throw new IllegalStateException("NATIVE_API_CEF_TIMEOUT_"+phase);if(mc.player!=null&&!opened){opened=true;host.open();}if(phase==7){if(ticks-resetAt<30)return;host.open();if(!host.ready()||UiClientSessions.current()==null||UiClientSessions.current().sessionId().equals(oldSession))return;script("document.querySelector('#open-native-api').click();");phase=8;return;}if(!host.ready()||UiClientSessions.current()==null||ticks%10!=0)return;poll();
            switch(phase){
                case 0->{action("open-refresh","document.querySelector('#open-native-api').click();const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-native-api');const b=[...p?.querySelectorAll('button')||[]].find(n=>n.textContent==='刷新 raw Native 快照');if(!b||b.disabled)return false;b.click();return true;");phase=1;}
                case 1->{action("open-refresh","document.querySelector('#open-native-api').click();const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-native-api');const b=[...p?.querySelectorAll('button')||[]].find(n=>n.textContent==='刷新 raw Native 快照');if(!b||b.disabled)return false;b.click();return true;");if(!text().contains("snapshot ")||!text().contains("minecraft"))return;phase=2;}
                case 2->{action("module","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-native-api');const c=[...p?.querySelectorAll('article')||[]].find(n=>n.querySelector('strong')?.textContent.startsWith('minecraft ·'));const b=[...c?.querySelectorAll('button')||[]].find(n=>n.textContent==='浏览类与符号');if(!b)return false;b.click();return true;");if(text().contains("module minecraft"))phase=3;}
                case 3->{action("search","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-native-api');const i=p?.querySelector('input[aria-label=\"类名包含文本\"]');const b=[...p?.querySelectorAll('button')||[]].find(n=>n.textContent==='按名称查找');if(!i||!b)return false;i.value='MinecraftServer';b.click();return true;");if(text().contains("net.minecraft.server.MinecraftServer"))phase=4;}
                case 4->{action("class","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-native-api');const b=[...p?.querySelectorAll('button')||[]].find(n=>n.textContent==='net.minecraft.server.MinecraftServer');if(!b)return false;b.click();return true;");if(text().contains("class SHA")&&text().contains("读取 FML transformed 成员"))phase=5;}
                case 5->{action("transformed","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-native-api');const b=[...p?.querySelectorAll('button')||[]].find(n=>n.textContent==='读取 FML transformed 成员');if(!b)return false;b.click();return true;");if(text().contains("FML_TRANSFORM_PIPELINE_PREDEFINE")&&text().contains("选入 Coder overlay"))phase=6;}
                case 6->{action("select","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-native-api');const b=[...p?.querySelectorAll('button')||[]].find(n=>n.textContent==='选入 Coder overlay');if(!b)return false;b.click();return true;");var s=selection();if(s.has("overlays")&&s.getAsJsonArray("overlays").size()==1){String id=s.getAsJsonArray("overlays").get(0).getAsString();UUID.fromString(id);require(s.getAsJsonArray("items").isEmpty(),"NATIVE_API_RAW_SELECTION_LEAK");require(s.get("snapshot").getAsString().matches("[a-f0-9]{64}"),"NATIVE_API_SELECTION_SNAPSHOT");Files.writeString(root().resolve("selected.json"),probe.toString());if(coder())phase=20;else{oldSession=UiClientSessions.current().sessionId();host.close();UiClientSessions.reset(true);probe=null;resetAt=ticks;phase=7;}}}
                case 8->{var s=selection();if(!s.has("overlays")||!s.getAsJsonArray("overlays").isEmpty())return;Files.writeString(root().resolve("result.json"),JSON.toJson(Map.of("status","REAL_CEF_NATIVE_TRANSFORMED_SELECTION_VERIFIED","newSession",true,"oldSelectionCleared",true,"providerCalls",0,"systemInputInjected",false,"fullV1",false)));finished=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_NATIVE_API_OK");host.close();mc.stop();}
                case 20->{action("studio-new-java","let p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-java-studio');if(!p){document.querySelector('#open-java-studio').click();return false;}const b=[...p.querySelectorAll('button')].find(n=>n.textContent==='新建 java 草稿');if(!b)return false;b.click();return true;");if(documentReady("Code Studio · 新草稿"))phase=21;}
                case 21->{String agent=Objects.toString(NativeApiSmokeServer.agent,"");if(agent.isEmpty())return;action("coder-submit","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-java-studio');const labels=[...p?.querySelectorAll('label')||[]];const path=labels.find(n=>n.textContent.startsWith('源码路径'))?.querySelector('input');const agent=labels.find(n=>n.textContent.startsWith('新任务归属 Agent'))?.querySelector('select');const details=p?.querySelector('details.studio-coder-panel');if(!path||!agent||!details||![...agent.options].some(n=>n.value==="+JSON.toJson(agent)+"))return false;path.value='dev/mineagent/smoke/CoderOverlayExtension.java';path.dispatchEvent(new Event('input',{bubbles:true}));agent.value="+JSON.toJson(agent)+";agent.dispatchEvent(new Event('change',{bubbles:true}));details.open=true;const prompt=labels.find(n=>n.textContent.startsWith('生成或修改需求'))?.querySelector('textarea');const fee=labels.find(n=>n.textContent.includes('明确同意本请求'))?.querySelector('input');const nativeShare=labels.find(n=>n.textContent.includes('明确同意向当前 Provider 发送 Native API'))?.querySelector('input');const submit=[...details.querySelectorAll('button')].find(n=>n.textContent==='确认新建 Coder 请求');if(!prompt||!fee||!nativeShare||!submit||submit.disabled)return false;prompt.value='生成一个最小 RuntimeExtension，start 返回固定字符串，不访问世界。';prompt.dispatchEvent(new Event('input',{bubbles:true}));fee.checked=true;fee.dispatchEvent(new Event('change',{bubbles:true}));nativeShare.checked=true;nativeShare.dispatchEvent(new Event('change',{bubbles:true}));submit.click();return true;");if(documentReady("尝试 1 · ACCEPTED")&&documentReady("Native raw 0 / overlay 1"))phase=22;}
                case 22->{action("coder-adopt","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-java-studio');const card=[...p?.querySelectorAll('article')||[]].find(n=>n.textContent.includes('尝试 1 · ACCEPTED'));const check=[...card?.querySelectorAll('label')||[]].find(n=>n.textContent.includes('确认采用'))?.querySelector('input');const b=[...card?.querySelectorAll('button')||[]].find(n=>n.textContent==='采用此候选为新草稿');if(!check||!b)return false;check.checked=true;b.click();return true;");if(documentReady("ADOPTED")&&documentReady("打开采用的草稿"))phase=23;}
                case 23->{action("open-adopted","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-java-studio');const b=[...p?.querySelectorAll('button')||[]].find(n=>n.textContent.startsWith('打开采用的草稿'));if(!b)return false;b.click();return true;");if(documentReady("发布将复用冻结 Native raw 0 / overlay 1"))phase=24;}
                case 24->{action("publish-source","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-java-studio');const b=[...p?.querySelectorAll('button')||[]].find(n=>n.textContent==='发布为统一 RuntimePackage 源码');if(!b||b.disabled)return false;b.click();return true;");if(documentReady("包库 r1")&&documentReady("发布将复用冻结 Native raw 0 / overlay 1"))phase=25;}
                case 25->{action("run-publication","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-java-studio');const labels=[...p?.querySelectorAll('label')||[]];const c=labels.find(n=>n.textContent.includes('明确编译并调用 Java start'))?.querySelector('input');const b=[...p?.querySelectorAll('button')||[]].find(n=>n.textContent==='编译并启动此保存版本');if(!c||!b||b.disabled)return false;c.checked=true;b.click();return true;");if(documentReady("Java · PUBLISHED · 当前句柄 true"))phase=26;}
                case 26->{action("stop-publication","const p=[...document.querySelectorAll('.window')].find(n=>n.dataset.viewId==='runtime-java-studio');const card=[...p?.querySelectorAll('article')||[]].find(n=>n.textContent.includes('Java · PUBLISHED · 当前句柄 true'));const c=[...card?.querySelectorAll('label')||[]].find(n=>n.textContent.includes('仅停止此 publication'))?.querySelector('input');const b=[...card?.querySelectorAll('button')||[]].find(n=>n.textContent==='停止原执行');if(!c||!b)return false;c.checked=true;b.click();return true;");if(documentReady("Java · STOP_RETURNED")){Files.writeString(root().resolve("coder-result.json"),JSON.toJson(Map.of("status","REAL_CEF_NATIVE_CODER_ADOPT_PUBLICATION_VERIFIED","controlledProviderCalls",1,"paidProviderCalls",0,"systemInputInjected",false,"fullV1",false)));finished=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_NATIVE_API_OK");host.close();mc.stop();}}
            }
        }catch(Exception failure){fail(failure);throw failure;}
    }
    private static boolean documentReady(String text){return WebGuiHostAdapter.INSTANCE.ready()&&WebGuiHostAdapter.INSTANCE.browser()!=null&&probe!=null&&probe.has("studioText")&&probe.get("studioText").getAsString().contains(text);}
}
