package dev.mineagent.runtime.neoforge.client.webui;
import com.google.gson.JsonObject;import net.minecraft.client.Minecraft;import java.util.*;import java.util.concurrent.*;import net.neoforged.bus.api.SubscribeEvent;import net.neoforged.fml.common.EventBusSubscriber;
@EventBusSubscriber(modid="mineagent_runtime",value=net.neoforged.api.distmarker.Dist.CLIENT)
public final class SkinUiClient {
 private static String pending;private static Object connection;
 public static void open(String agent){UUID.fromString(agent);var mc=Minecraft.getInstance();if(mc.player==null)return;pending=agent;connection=mc.getConnection();WebGuiHostAdapter.INSTANCE.open();}
 @SubscribeEvent public static void tick(net.neoforged.neoforge.client.event.ClientTickEvent.Post e){if(connection!=Minecraft.getInstance().getConnection()){pending=null;connection=null;}if(pending!=null&&WebGuiHostAdapter.INSTANCE.ready()&&UiClientSessions.current()!=null){String agent=pending;pending=null;WebGuiHostAdapter.INSTANCE.emit("skinUiOpen",Map.of("agentId",agent));}}
 public static CompletableFuture<Map<String,Object>> handle(JsonObject a){var mc=Minecraft.getInstance();var server=mc.getSingleplayerServer();if(server==null||mc.player==null)return CompletableFuture.failedFuture(new IllegalStateException("SKIN_LOCAL_OWNER_REQUIRED"));UUID owner=mc.player.getUUID(),agent=UUID.fromString(a.get("agentId").getAsString());Object wire=mc.getConnection();String kind=a.get("kind").getAsString();return server.submit(()->server.getPlayerList().getPlayer(owner)).thenComposeAsync(p->{if(p==null||Minecraft.getInstance().getConnection()!=wire)return CompletableFuture.failedFuture(new IllegalStateException("SKIN_CONTEXT_CHANGED"));if(kind.equals("read"))return dev.mineagent.runtime.neoforge.ui.ServerAgentSkins.uiRead(p,agent,a.has("query")?a.get("query").getAsString():".png",a.has("offset")?a.get("offset").getAsInt():0);if(kind.equals("apply")){var args=new com.fasterxml.jackson.databind.ObjectMapper().createObjectNode().put("file_id",a.get("file_id").getAsString()).put("model",a.get("model").getAsString()).put("expected_revision",a.get("expected_revision").getAsLong());return dev.mineagent.runtime.neoforge.ui.ConversationAgentTools.execute(p,agent,UUID.fromString(a.get("operationId").getAsString()),"set_skin_png",args.toString(),()->Minecraft.getInstance().getConnection()==wire&&server.getPlayerList().getPlayer(owner)==p);}if(kind.equals("preset")){var args=new com.fasterxml.jackson.databind.ObjectMapper().createObjectNode().put("kind","vanilla").put("skin",a.get("skin").getAsString()).put("expected_revision",a.get("expected_revision").getAsLong());return dev.mineagent.runtime.neoforge.ui.ConversationAgentTools.execute(p,agent,UUID.fromString(a.get("operationId").getAsString()),"set_appearance",args.toString(),()->Minecraft.getInstance().getConnection()==wire&&server.getPlayerList().getPlayer(owner)==p);}return CompletableFuture.failedFuture(new IllegalArgumentException("SKIN_UI_KIND"));},server);}
 private SkinUiClient(){}
}
