package dev.mineagent.runtime.neoforge.client.webui;
import com.google.gson.*;
import dev.mineagent.runtime.api.ui.*;
import dev.mineagent.runtime.api.ui.UiProtocol.*;
import dev.mineagent.runtime.core.ui.*;
import net.minecraft.client.Minecraft;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicBoolean;
import java.util.function.BooleanSupplier;
/** One current delegated view, durable intent, then a version-checked trusted-host mutation. */
public final class UiPresentationClient {
    private static final Gson JSON=new Gson();private static final Map<UUID,Flight> pending=new LinkedHashMap<>();
    private static final ExecutorService IO=new ThreadPoolExecutor(1,1,30,TimeUnit.SECONDS,new ArrayBlockingQueue<>(32),r->{var t=new Thread(r,"mineagent-ui-placement");t.setDaemon(true);return t;},new ThreadPoolExecutor.AbortPolicy());
    private static UiPlacementJournal journal;private static UUID journalWorld;
    private static final class Flight {
        final UUID id=UUID.randomUUID();final String view,url,document,hostDocument;final Session source,shell;final UiPresentationAction action;final UiPlacementJournal.Input input;final BooleanSupplier owner;final AtomicBoolean valid=new AtomicBoolean(true);final CompletableFuture<String> result=new CompletableFuture<>();UiPlacementJournal store;JsonObject opacityPaint;boolean prepared,dispatched;
        Flight(String view,String url,String document,String hostDocument,Session source,Session shell,UiPresentationAction action,UiPlacementJournal.Input input,BooleanSupplier owner){this.view=view;this.url=url;this.document=document;this.hostDocument=hostDocument;this.source=source;this.shell=shell;this.action=action;this.input=input;this.owner=owner;}
    }
    private UiPresentationClient(){}
    public static JsonObject observe(String view){var host=WebGuiHostAdapter.INSTANCE;var value=host.viewLayout(view);if(value==null)return null;var d=host.viewPackage(view);var shell=UiClientSessions.current();var source=PackageContentClient.session(view);boolean allowed=d!=null&&shell!=null&&!host.packageHidden(view)&&UiPresentationPolicy.canAgent(source,shell.binding().viewerPlayerId(),d.packageId(),d.revision(),view);value.addProperty("canPresent",allowed);value.addProperty("opacitySupported",WebGuiAtlasCompositor.inputAvailable());if(value.has("bounds")&&!value.get("bounds").isJsonNull()&&value.has("hostDocumentId")){var paint=WebGuiAtlasCompositor.presentationPaint(view,value.get("hostDocumentId").getAsString(),bounds(value.getAsJsonObject("bounds")),null);if(paint.get("status").equals("NATIVE_ATLAS_PAINTED")){value.add("opacityPaint",JSON.toJsonTree(paint));value.addProperty("opacity",((Number)paint.get("opacity")).doubleValue());}}return value;}
    public static CompletableFuture<String> apply(String view,String url,String document,JsonObject observed,String encoded,BooleanSupplier owner){
        Flight f=null;try{var mc=Minecraft.getInstance();var host=WebGuiHostAdapter.INSTANCE;var d=host.viewPackage(view);var shell=UiClientSessions.current();var source=PackageContentClient.session(view);var action=UiPresentationAction.parse(encoded);
            if(d==null||shell==null||!UiPresentationPolicy.canAgent(source,shell.binding().viewerPlayerId(),d.packageId(),d.revision(),view)||observed==null||!observed.has("hostDocumentId"))throw new SecurityException("UI_PRESENTATION_DENIED");
            if(action.placement().opacity()!=null&&!WebGuiAtlasCompositor.inputAvailable())throw new IllegalStateException("UI_OPACITY_BACKEND_REQUIRED");
            if(action.expectedLayoutRevision()!=observed.get("revision").getAsLong())throw new IllegalStateException("STALE_LAYOUT");if(pending.size()>=8)throw new IllegalStateException("UI_PRESENTATION_BUSY");
            var server=mc.getCurrentServer();var scope=new UiPlacementJournal.Scope(server==null?"local-integrated":server.ip,source.binding().worldId(),shell.binding().viewerPlayerId(),source.binding().actorId(),d.packageId(),d.entry(),WorldUiProtocol.localStateTarget(source.binding()));
            var input=new UiPlacementJournal.Input(action.operationId(),scope,d.revision(),source.binding().taskId(),source.binding().taskRevision(),action.expectedLayoutRevision(),action.placement());f=new Flight(view,url,document,observed.get("hostDocumentId").getAsString(),source,shell,action,input,owner);var flight=f;pending.put(f.id,f);
            if(!current(f))throw new IllegalStateException("USER_INTERRUPTED");
            permit(f).thenCompose(ignored->{if(!current(flight))throw new IllegalStateException("USER_INTERRUPTED");var currentLayout=WebGuiHostAdapter.INSTANCE.viewLayout(view);long currentRevision=currentLayout==null?0:currentLayout.get("revision").getAsLong();return CompletableFuture.supplyAsync(()->{try{if(!flight.valid.get())throw new IllegalStateException("USER_INTERRUPTED");if(journal==null||!scope.world().equals(journalWorld)){if(journal!=null)journal.close();journalWorld=scope.world();journal=UiPlacementJournal.open(mc.gameDirectory.toPath().resolve("mineagent-runtime-data/ui-placement-"+journalWorld+".db"),journalWorld);}flight.store=journal;return journal.prepare(input,currentRevision,flight.valid.get());}catch(Exception e){throw new CompletionException(e);}},IO);}).whenComplete((prepared,error)->mc.execute(()->{
                if(error!=null){finishFailure(flight,error);return;}flight.prepared=prepared.execute();if(!current(flight)){finishFailure(flight,new IllegalStateException("USER_INTERRUPTED"));return;}
                if(!prepared.execute()){var old=prepared.record();var value=old.response().isEmpty()?new JsonObject():JsonParser.parseString(old.response()).getAsJsonObject();if(!value.has("status"))value.addProperty("status","UI_PRESENTATION_UNKNOWN");value.addProperty("operationId",action.operationId().toString());value.addProperty("duplicate",true);value.addProperty("reapplied",false);retire(flight,value.toString());return;}
                permit(flight).whenComplete((ignored,e)->mc.execute(()->{if(e!=null){finishFailure(flight,e);return;}if(!WebGuiNativeInput.afterInputs(()->dispatch(flight)))finishFailure(flight,new IllegalStateException("UI_INPUT_QUEUE_BUSY"));}));
            }));
            f.result.orTimeout(15,TimeUnit.SECONDS).whenComplete((value,error)->{if(error!=null)mc.execute(()->finishFailure(flight,error));});return f.result;
        }catch(Exception error){if(f!=null)pending.remove(f.id);return CompletableFuture.completedFuture(failure(null,error));}
    }
    private static CompletableFuture<Void> permit(Flight f){if(!current(f))return CompletableFuture.failedFuture(new IllegalStateException("USER_INTERRUPTED"));return UiClientSessions.command("ui.presentationPermit",Map.of("sourceSessionId",f.source.sessionId().toString(),"viewId",f.view,"packageId",f.input.scope().packageId().toString(),"packageRevision",Long.toString(f.input.packageRevision())),UUID.randomUUID()).thenApply(r->{if(r.code()!=Code.OBSERVED)throw new SecurityException("UI_PRESENTATION_DENIED");return null;});}
    private static boolean current(Flight f){var host=WebGuiHostAdapter.INSTANCE;return host.ready()&&f.valid.get()&&f.owner.getAsBoolean()&&UiClientSessions.current()==f.shell&&ReadOnlyUiLease.sameContext(PackageContentClient.session(f.view),f.source)&&!host.packageHidden(f.view)&&f.url.equals(host.packageUrl(f.view))&&Minecraft.getInstance().screen instanceof WebGuiInteractionScreen;}
    private static void dispatch(Flight f){try{var layout=WebGuiHostAdapter.INSTANCE.viewLayout(f.view);if(!current(f))throw new IllegalStateException("USER_INTERRUPTED");if(layout==null||!layout.get("hostDocumentId").getAsString().equals(f.hostDocument)||layout.get("revision").getAsLong()!=f.action.expectedLayoutRevision())throw new IllegalStateException("STALE_LAYOUT");
        if(f.action.placement().opacity()!=null&&!WebGuiAtlasCompositor.inputAvailable())throw new IllegalStateException("UI_OPACITY_BACKEND_REQUIRED");
        f.dispatched=true;WebGuiHostAdapter.INSTANCE.emit("presentationApply",Map.of("requestId",f.id,"operationId",f.action.operationId(),"viewId",f.view,"url",f.url,"documentId",f.document,"hostDocumentId",f.hostDocument,"packageId",f.input.scope().packageId(),"packageRevision",f.input.packageRevision(),"expectedLayoutRevision",f.action.expectedLayoutRevision(),"placement",f.action.placement()));
    }catch(Exception e){finishFailure(f,e);}}
    public static Map<String,Object> paint(UUID request){
        Flight f=pending.get(request);if(f==null||!f.dispatched||!current(f)||f.action.placement().opacity()==null)return Map.of("status","UI_PRESENTATION_UNKNOWN");
        var layout=WebGuiHostAdapter.INSTANCE.viewLayout(f.view);if(layout==null||!layout.get("visible").getAsBoolean())return Map.of("status","PENDING");
        var proof=WebGuiAtlasCompositor.presentationPaint(f.view,f.hostDocument,f.action.placement().resolve(bounds(layout.getAsJsonObject("area"))),f.action.placement().opacity());
        if(proof.get("status").equals("NATIVE_ATLAS_PAINTED"))f.opacityPaint=JSON.toJsonTree(proof).getAsJsonObject();return proof;
    }
    public static void acknowledge(JsonObject message){Flight f=pending.get(UUID.fromString(message.get("requestId").getAsString()));if(f==null)return;try{
        var receipt=message.getAsJsonObject("receipt");if(!current(f))throw new IllegalStateException("USER_INTERRUPTED");if(!receipt.get("operationId").getAsString().equals(f.action.operationId().toString())||!receipt.get("documentId").getAsString().equals(f.document))throw new IllegalArgumentException("UI_PRESENTATION_RECEIPT");String status=receipt.get("status").getAsString();
        if(status.equals("APPLIED_HOST")){if(!receipt.get("persisted").getAsBoolean())throw new IllegalStateException("UI_PRESENTATION_UNKNOWN");var actual=receipt.getAsJsonObject("actual");if(!actual.get("hostDocumentId").getAsString().equals(f.hostDocument)||!actual.get("viewId").getAsString().equals(f.view)||actual.get("revision").getAsLong()<f.action.expectedLayoutRevision())throw new IllegalStateException("UI_PRESENTATION_RECEIPT");var expected=f.action.placement().resolve(bounds(actual.getAsJsonObject("area")));var b=bounds(actual.getAsJsonObject("bounds"));if(Math.abs(b.x()-expected.x())>1||Math.abs(b.y()-expected.y())>1||Math.abs(b.width()-expected.width())>1||Math.abs(b.height()-expected.height())>1)throw new IllegalStateException("UI_PRESENTATION_BOUNDS");
            if(f.action.placement().opacity()!=null){var alpha=f.action.placement().opacity();if(!actual.has("opacity")||Double.compare(actual.get("opacity").getAsDouble(),alpha)!=0||f.opacityPaint==null||!f.opacityPaint.equals(receipt.getAsJsonObject("opacityPaint"))||!WebGuiAtlasCompositor.presentationPaint(f.view,f.hostDocument,expected,alpha).get("status").equals("NATIVE_ATLAS_PAINTED"))throw new IllegalStateException("UI_PRESENTATION_UNKNOWN");}
        }
        String encoded=receipt.toString();CompletableFuture.runAsync(()->{try{if(status.equals("APPLIED_HOST"))f.store.applied(f.input,encoded);else if(Set.of("STALE_LAYOUT","STALE_VIEW","NOT_INTERACTABLE").contains(status))f.store.rejected(f.input,encoded);else f.store.unknown(f.input,"UI_PRESENTATION_UNKNOWN");}catch(Exception e){throw new CompletionException(e);}},IO).whenComplete((v,e)->Minecraft.getInstance().execute(()->{if(e!=null)finishFailure(f,e);else retire(f,encoded);}));
    }catch(Exception e){finishFailure(f,e);}}
    private static UiPresentationAction.Bounds bounds(JsonObject b){return new UiPresentationAction.Bounds(b.get("x").getAsDouble(),b.get("y").getAsDouble(),b.get("width").getAsDouble(),b.get("height").getAsDouble());}
    private static String failure(UUID id,Throwable error){while(error.getCause()!=null)error=error.getCause();String code=error.getMessage();if(code==null||!Set.of("USER_INTERRUPTED","STALE_LAYOUT","UI_PRESENTATION_DENIED","UI_PRESENTATION_BUSY","UI_PRESENTATION_INPUT","UI_PRESENTATION_UNKNOWN","OPERATION_ID_REUSED","UI_PRESENTATION_LEDGER_FULL","UI_INPUT_QUEUE_BUSY","UI_OPACITY_BACKEND_REQUIRED").contains(code))code="UI_PRESENTATION_FAILED";var value=new JsonObject();value.addProperty("status",code);if(id!=null)value.addProperty("operationId",id.toString());return value.toString();}
    private static void finishFailure(Flight f,Throwable e){if(!pending.containsKey(f.id))return;f.valid.set(false);if(f.prepared&&f.store!=null)try{CompletableFuture.runAsync(()->{try{if(f.dispatched)f.store.unknown(f.input,"UI_PRESENTATION_UNKNOWN");else f.store.rejected(f.input,failure(f.action.operationId(),e));}catch(Exception ignored){}},IO);}catch(RejectedExecutionException ignored){}retire(f,failure(f.action.operationId(),e));}
    private static void retire(Flight f,String result){pending.remove(f.id,f);f.valid.set(false);f.result.complete(result);}
    public static void cancel(String view){for(var f:List.copyOf(pending.values()))if(f.view.equals(view))finishFailure(f,new IllegalStateException("USER_INTERRUPTED"));}
    public static void clear(){for(var f:List.copyOf(pending.values()))finishFailure(f,new IllegalStateException("USER_INTERRUPTED"));}
}
