package dev.mineagent.runtime.neoforge.client.webui;
import com.google.gson.*;
import dev.mineagent.runtime.api.packages.*;
import dev.mineagent.runtime.neoforge.ui.WorldUiSmokeServer;
import dev.mineagent.runtime.neoforge.client.MineAgentClientMod;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.client.input.KeyEvent;
import org.lwjgl.glfw.GLFW;
import java.nio.file.*;
import java.util.*;
/** Explicit local lifecycle fixture. Robot sends OS keys only while this isolated game owns focus. */
public final class WorkspaceSmokeClient {
    private static final Gson JSON=new Gson();public static boolean finished;private static int phase,ticks,after;private static boolean busy,left;
    private static java.awt.Robot robot;private static final Set<Integer> keys=new HashSet<>();private static Object browser;private static String hud,worldView;private static JsonObject probe,before;private static long pulse,screenshots;private static float hiddenYaw;private static boolean originalHudHidden;
    private static Screen previous;private static net.minecraft.client.gui.screens.options.controls.KeyBindsScreen controls;private static net.minecraft.client.gui.components.Button change;
    private static int coldPhase,coldTicks,coldAfter;private static Object coldBrowser;private static boolean coldDone;
    private WorkspaceSmokeClient(){}
    public static void accept(JsonObject value){probe=value;}
    private static Path root(){return Minecraft.getInstance().gameDirectory.toPath().resolve(WorldUiSmokeServer.directory()).resolve("workspace");}
    private static void main(String code){var h=WebGuiHostAdapter.INSTANCE;h.browser().executeJavaScript("(()=>{"+code+"})();",h.browser().getURL(),0);}
    private static void save(String name,Object value)throws Exception{Files.writeString(root().resolve(name+".json"),JSON.toJson(value));}
    private static void require(boolean condition,String code){if(!condition)throw new IllegalStateException(code);}
    private static void down(int key){require(GLFW.glfwGetWindowAttrib(Minecraft.getInstance().getWindow().handle(),GLFW.GLFW_FOCUSED)==GLFW.GLFW_TRUE,"WORKSPACE_GAME_NOT_FOCUSED");robot.keyPress(key);keys.add(key);}
    private static void up(int key){robot.keyRelease(key);keys.remove(key);}
    private static void cursorCss(double x,double y){var window=Minecraft.getInstance().getWindow();GLFW.glfwSetCursorPos(window.handle(),x*window.getScreenWidth()/probe.get("viewportWidth").getAsDouble(),y*window.getScreenHeight()/probe.get("viewportHeight").getAsDouble());}
    private static void cleanup(){if(robot!=null){for(int key:List.copyOf(keys))up(key);if(left){robot.mouseRelease(java.awt.event.InputEvent.BUTTON1_DOWN_MASK);left=false;}}}
    private static void rawKey(int key,int action)throws Exception{var method=net.minecraft.client.KeyboardHandler.class.getDeclaredMethod("keyPress",long.class,int.class,KeyEvent.class);method.setAccessible(true);method.invoke(Minecraft.getInstance().keyboardHandler,Minecraft.getInstance().getWindow().handle(),action,new KeyEvent(key,GLFW.glfwGetKeyScancode(key),0));}
    private static void preedit(boolean composing)throws Exception{var method=net.minecraft.client.KeyboardHandler.class.getDeclaredMethod("preeditCallback",long.class,net.minecraft.client.input.PreeditEvent.class);method.setAccessible(true);method.invoke(Minecraft.getInstance().keyboardHandler,Minecraft.getInstance().getWindow().handle(),composing?new net.minecraft.client.input.PreeditEvent("拼",1,List.of("拼"),0):null);}
    private static long screenshotCount()throws Exception{Path p=Minecraft.getInstance().gameDirectory.toPath().resolve("screenshots");if(!Files.exists(p))return 0;try(var list=Files.list(p)){return list.count();}}
    private static void snap(String name){busy=true;net.minecraft.client.Screenshot.takeScreenshot(Minecraft.getInstance().getMainRenderTarget(),img->{try(img){img.writeToFile(root().resolve(name+".png"));}catch(Exception e){WorldUiSmokeServer.failure="WORKSPACE_SCREENSHOT_FAILED";}finally{busy=false;}});}
    private static boolean shown(){return WebGuiHostAdapter.INSTANCE.workspaceShown()&&Minecraft.getInstance().screen instanceof WebGuiInteractionScreen&&!Minecraft.getInstance().mouseHandler.isMouseGrabbed();}
    private static boolean hidden(){return !WebGuiHostAdapter.INSTANCE.workspaceShown()&&Minecraft.getInstance().screen==null&&Minecraft.getInstance().mouseHandler.isMouseGrabbed();}
    private static void poll(){main("const chat=document.querySelector('[data-view-id=runtime-chat]'),hud=document.querySelector('[data-view-id=\""+hud+"\"]');window.mineagentQuery({request:JSON.stringify({channel:'workspaceSmokeProbe',viewportWidth:innerWidth,viewportHeight:innerHeight,workspace:document.body.dataset.workspaceVisible,interacting:document.body.dataset.interacting,dock:getComputedStyle(document.querySelector('#dock')).visibility,selected:document.querySelector('#conversation-list')?.value||'',agents:[...document.querySelectorAll('#chat-agent option')].map(n=>n.value),conversations:[...document.querySelectorAll('#conversation-list option')].map(n=>n.value),draft:document.querySelector('#chat-draft')?.value||'',history:document.querySelector('#chat-history')?.textContent||'',scroll:document.querySelector('#chat-history')?.scrollTop||0,rect:chat?.getBoundingClientRect().toJSON(),bar:chat?.querySelector('.titlebar').getBoundingClientRect().toJSON(),sameNode:!!chat&&chat===window.__workspaceChatNode,chatVisible:!!chat&&getComputedStyle(chat).display!=='none',hudVisible:!!hud&&getComputedStyle(hud).display!=='none',windows:[...document.querySelectorAll('.window')].map(n=>({id:n.dataset.viewId,mode:n.dataset.mode,visible:getComputedStyle(n).display!=='none'}))}),persistent:false,onSuccess(){},onFailure(){}});");}
    public static boolean coldStep(){if(coldDone)return true;var mc=Minecraft.getInstance();var host=WebGuiHostAdapter.INSTANCE;coldTicks++;
        try{Files.createDirectories(root());require(coldTicks<700,"WORKSPACE_COLD_TIMEOUT");
            if(coldPhase==0){require(host.browser()==null&&mc.screen==null,"WORKSPACE_COLD_BASELINE");robot=new java.awt.Robot();GLFW.glfwFocusWindow(mc.getWindow().handle());coldPhase=1;coldAfter=coldTicks+10;}
            if(coldPhase==1&&coldTicks>=coldAfter){require(mc.mouseHandler.isMouseGrabbed(),"WORKSPACE_COLD_MOUSE_BASELINE");down(java.awt.event.KeyEvent.VK_F2);coldPhase=2;}
            if(coldPhase==2&&host.ready()){require(shown(),"WORKSPACE_COLD_SHOW_FAILED");coldBrowser=host.browser();up(java.awt.event.KeyEvent.VK_F2);save("cold-open",Map.of("browserReady",host.ready(),"mouseGrabbed",mc.mouseHandler.isMouseGrabbed(),"actualOsF2",true,"readyMillis",host.readyMillis()));snap("cold-open");coldPhase=3;coldAfter=coldTicks+15;}
            if(coldPhase==3&&!busy&&coldTicks>=coldAfter){down(java.awt.event.KeyEvent.VK_F2);coldPhase=4;coldAfter=coldTicks+12;}
            if(coldPhase==4&&coldTicks>=coldAfter){up(java.awt.event.KeyEvent.VK_F2);require(hidden()&&host.browser()==coldBrowser,"WORKSPACE_COLD_HIDE_DESTROYED_HOST");save("cold-hide",Map.of("sameBrowser",host.browser()==coldBrowser,"mouseGrabbed",mc.mouseHandler.isMouseGrabbed()));coldDone=true;return true;}
        }catch(Exception e){cleanup();try{save("cold-failure",Map.of("phase",coldPhase,"error",e.toString()));}catch(Exception ignored){}WorldUiSmokeServer.failure="WORKSPACE_COLD_FAILED";}return false;
    }
    public static void step(String view){if(finished)return;var mc=Minecraft.getInstance();var host=WebGuiHostAdapter.INSTANCE;ticks++;
        try{
            Files.createDirectories(root());require(ticks<2600,"WORKSPACE_FIXTURE_TIMEOUT");if(phase>0&&ticks%10==0&&host.ready())poll();if(ticks%40==0)save("progress",Map.of("phase",phase,"ticks",ticks,"probe",probe==null?new JsonObject():probe));
            if(phase==0){browser=host.browser();worldView=view;originalHudHidden=mc.options.hideGui;robot=new java.awt.Robot();GLFW.glfwFocusWindow(mc.getWindow().handle());screenshots=screenshotCount();
                byte[] html="<!doctype html><html><body><b>F2_HUD_LIFECYCLE_FIXTURE</b><p id='ticks'>HUD_TICK:0</p><script>let n=0;setInterval(()=>document.querySelector('#ticks').textContent='HUD_TICK:'+ ++n,100);</script></body></html>".getBytes(java.nio.charset.StandardCharsets.UTF_8);String hash=dev.mineagent.runtime.core.objects.RuntimeModelBundle.hash(html);var ref=new RuntimeResourceRef("ui/index.html",hash,RuntimeResourceSide.CLIENT,"text/html",html.length);var pkg=new RuntimePackage(UUID.randomUUID(),RuntimePackageType.CONTENT,"F2 HUD · 本地生命周期夹具","1",ActivationMode.HOT_RUNTIME,Map.of(),Set.of(),Map.of("hud",new RuntimeEntrypoint(ref.path(),ref.side(),hash)),Map.of(),Map.of(ref.path(),ref),PackageOrigin.LOCAL_STUDIO,false,1,hash,"LOCAL_LIFECYCLE_FIXTURE_NOT_PUBLISHED",0);hud=host.openPackagePreview(pkg,ignored->html,ref.path(),true);save("fixture",Map.of("hudOrigin","EXPLICIT_LOCAL_LIFECYCLE_NOT_SCORE_BUSINESS","providerCalls",0,"keyInput","OS_ROBOT_WITH_GAME_FOCUS_GUARD","repeatAndPreeditInput","EXPLICIT_NATIVE_HANDLER_INJECTION"));mc.setScreen(null);phase=1;after=ticks+20;}
            if(phase==1&&ticks>=after&&host.packageLoaded(hud)){require(hidden(),"WORKSPACE_INITIAL_MOUSE_GRAB");down(java.awt.event.KeyEvent.VK_F2);phase=2;after=ticks+30;}
            if(phase==2&&ticks>=after){require(shown(),"WORKSPACE_F2_DID_NOT_RELEASE_MOUSE");for(int i=0;i<20;i++)rawKey(GLFW.GLFW_KEY_F2,GLFW.GLFW_REPEAT);require(shown(),"WORKSPACE_REPEAT_TOGGLED");up(java.awt.event.KeyEvent.VK_F2);require(screenshotCount()==screenshots,"WORKSPACE_F2_ALSO_SCREENSHOT");main("document.querySelector('#open-chat').click();");phase=3;}
            if(phase==3&&probe!=null&&probe.getAsJsonArray("agents").toString().contains(WorldUiSmokeServer.workspaceAgent.toString())){main("const e=document.querySelector('#chat-agent');e.value='"+WorldUiSmokeServer.workspaceAgent+"';e.dispatchEvent(new Event('change',{bubbles:true}));");phase=4;}
            if(phase==4&&probe.getAsJsonArray("conversations").toString().contains(WorldUiSmokeServer.workspaceConversation.toString())){main("const e=document.querySelector('#conversation-list');e.value='"+WorldUiSmokeServer.workspaceConversation+"';e.dispatchEvent(new Event('change',{bubbles:true}));");phase=5;}
            if(phase==5&&probe.get("selected").getAsString().equals(WorldUiSmokeServer.workspaceConversation.toString())&&probe.get("history").getAsString().contains("F2_HISTORY")){main("const e=document.querySelector('#chat-draft');e.value='F2_DRAFT_PRESERVED';e.dispatchEvent(new Event('input',{bubbles:true}));window.__workspaceChatNode=document.querySelector('[data-view-id=runtime-chat]');document.querySelector('#chat-history').scrollTop=70;");phase=6;after=ticks+20;}
            if(phase==6&&ticks>=after){require(probe.get("draft").getAsString().equals("F2_DRAFT_PRESERVED"),"WORKSPACE_DRAFT_NOT_SET");save("shown",probe);before=probe.deepCopy();snap("shown");phase=7;}
            if(phase==7&&!busy){var bar=probe.getAsJsonObject("bar");cursorCss(bar.get("x").getAsDouble()+80,bar.get("y").getAsDouble()+20);robot.mousePress(java.awt.event.InputEvent.BUTTON1_DOWN_MASK);left=true;phase=8;after=ticks+10;}
            if(phase==8&&ticks>=after){var bar=before.getAsJsonObject("bar");cursorCss(bar.get("x").getAsDouble()+115,bar.get("y").getAsDouble()+35);phase=9;after=ticks+20;}
            if(phase==9&&ticks>=after){require(!probe.get("rect").equals(before.get("rect")),"WORKSPACE_NATIVE_DRAG_NOT_OBSERVED");before=probe.deepCopy();save("before-hide-during-drag",before);pulse=WorldUiSmokeServer.workspacePulse;down(java.awt.event.KeyEvent.VK_F2);phase=10;after=ticks+15;}
            if(phase==10&&ticks>=after){require(hidden()&&!mc.mouseHandler.isLeftPressed()&&!mc.mouseHandler.isRightPressed()&&!mc.options.keyAttack.isDown()&&!mc.options.keyUse.isDown(),"WORKSPACE_HIDDEN_INPUT_STUCK");up(java.awt.event.KeyEvent.VK_F2);robot.mouseRelease(java.awt.event.InputEvent.BUTTON1_DOWN_MASK);left=false;hiddenYaw=mc.player.getYRot();phase=11;after=ticks+80;}
            if(phase==11&&(ticks==after-60||ticks==after-40)){require(mc.isWindowActive(),"WORKSPACE_CAMERA_FOCUS");var cursor=java.awt.MouseInfo.getPointerInfo().getLocation();robot.mouseMove(cursor.x+35,cursor.y+3);}
            if(phase==11&&ticks>=after&&!busy){save("hidden-checks",Map.of("sameBrowser",host.browser()==browser,"packageLoaded",host.packageLoaded(worldView),"hudVisible",probe.get("hudVisible"),"chatVisible",probe.get("chatVisible"),"pulseBefore",pulse,"pulseAfter",WorldUiSmokeServer.workspacePulse,"taskRevision",WorldUiSmokeServer.workspaceTaskRevision,"yawBefore",hiddenYaw,"yawAfter",mc.player.getYRot()));require(host.browser()==browser&&host.packageLoaded(worldView)&&probe.get("hudVisible").getAsBoolean()&&!probe.get("chatVisible").getAsBoolean()&&WorldUiSmokeServer.workspacePulse>pulse&&WorldUiSmokeServer.workspaceTaskRevision==1&&mc.player.getYRot()!=hiddenYaw,"WORKSPACE_HIDDEN_LIFECYCLE_FAILED");save("hidden-native",Map.of("probe",probe,"pulseBefore",pulse,"pulseAfter",WorldUiSmokeServer.workspacePulse,"mouseGrabbed",mc.mouseHandler.isMouseGrabbed(),"yawBefore",hiddenYaw,"yawAfter",mc.player.getYRot(),"taskRevision",WorldUiSmokeServer.workspaceTaskRevision));phase=12;snap("hidden-with-hud");}
            if(phase==12&&!busy){down(java.awt.event.KeyEvent.VK_F2);phase=13;after=ticks+15;}
            if(phase==13&&ticks>=after){up(java.awt.event.KeyEvent.VK_F2);require(shown()&&probe.get("sameNode").getAsBoolean()&&probe.get("draft").equals(before.get("draft"))&&probe.get("scroll").equals(before.get("scroll"))&&probe.get("rect").equals(before.get("rect")),"WORKSPACE_RESTORE_STATE_CHANGED");save("restored",probe);down(java.awt.event.KeyEvent.VK_F2);phase=14;after=ticks+12;}
            if(phase==14&&ticks>=after){up(java.awt.event.KeyEvent.VK_F2);require(hidden(),"WORKSPACE_SECOND_HIDE_FAILED");host.openStandalone();phase=15;after=ticks+15;}
            if(phase==15&&ticks>=after){require(!host.workspaceShown()&&mc.screen instanceof WebGuiInteractionScreen&&!probe.get("chatVisible").getAsBoolean(),"WORKSPACE_STANDALONE_REVEALED_MANAGEMENT");save("standalone",probe);down(java.awt.event.KeyEvent.VK_F2);phase=16;after=ticks+12;}
            if(phase==16&&ticks>=after){up(java.awt.event.KeyEvent.VK_F2);require(shown(),"WORKSPACE_FROM_STANDALONE_FAILED");previous=mc.screen;controls=new net.minecraft.client.gui.screens.options.controls.KeyBindsScreen(previous,mc.options);mc.setScreen(controls);var field=controls.getClass().getDeclaredField("keyBindsList");field.setAccessible(true);var list=(net.minecraft.client.gui.screens.options.controls.KeyBindsList)field.get(controls);int index=0;for(var entry:list.children()){if(entry.getClass().getSimpleName().equals("KeyEntry")){var key=entry.getClass().getDeclaredField("key");key.setAccessible(true);if(key.get(entry)==MineAgentClientMod.TOGGLE_WORKSPACE){var b=entry.getClass().getDeclaredField("changeButton");b.setAccessible(true);change=(net.minecraft.client.gui.components.Button)b.get(entry);list.setScrollAmount(Math.max(0,index*20-80));break;}}index++;}require(change!=null,"WORKSPACE_BINDING_NOT_IN_CONTROLS");phase=17;after=ticks+15;}
            if(phase==17&&ticks>=after){require(change.getY()>0&&change.getBottom()<controls.height,"WORKSPACE_CONTROLS_BUTTON_OFFSCREEN");snap("controls");double scale=(double)mc.getWindow().getWidth()/controls.width;GLFW.glfwSetCursorPos(mc.getWindow().handle(),(change.getX()+change.getWidth()/2.0)*scale,(change.getY()+change.getHeight()/2.0)*scale);robot.mousePress(java.awt.event.InputEvent.BUTTON1_DOWN_MASK);left=true;phase=18;after=ticks+6;}
            if(phase==18&&ticks>=after){robot.mouseRelease(java.awt.event.InputEvent.BUTTON1_DOWN_MASK);left=false;require(controls.selectedKey==MineAgentClientMod.TOGGLE_WORKSPACE,"WORKSPACE_CONTROLS_CLICK_FAILED");down(java.awt.event.KeyEvent.VK_F8);phase=19;after=ticks+8;}
            if(phase==19&&ticks>=after){up(java.awt.event.KeyEvent.VK_F8);phase=20;after=ticks+8;}
            if(phase==20&&ticks>=after){require(mc.screen==controls&&MineAgentClientMod.TOGGLE_WORKSPACE.getKey().getValue()==GLFW.GLFW_KEY_F8,"WORKSPACE_NATIVE_REBIND_FAILED");mc.options.save();save("rebound",Map.of("key",MineAgentClientMod.TOGGLE_WORKSPACE.saveString(),"screenshotKey",mc.options.keyScreenshot.saveString(),"nativeScreenRetained",true));controls.onClose();phase=21;after=ticks+15;}
            if(phase==21&&ticks>=after){screenshots=screenshotCount();down(java.awt.event.KeyEvent.VK_F2);phase=22;after=ticks+6;}
            if(phase==22&&ticks>=after){up(java.awt.event.KeyEvent.VK_F2);phase=23;after=ticks+30;}
            if(phase==23&&ticks>=after){require(shown()&&screenshotCount()>screenshots,"WORKSPACE_OLD_KEY_NOT_RELEASED");save("old-key-released",Map.of("screenshotsBefore",screenshots,"screenshotsAfter",screenshotCount(),"stillShown",shown()));down(java.awt.event.KeyEvent.VK_F8);phase=24;after=ticks+12;}
            if(phase==24&&ticks>=after){up(java.awt.event.KeyEvent.VK_F8);require(hidden(),"WORKSPACE_REBOUND_KEY_NOT_WORKING");mc.setScreen(new net.minecraft.client.gui.screens.inventory.InventoryScreen(mc.player));previous=mc.screen;down(java.awt.event.KeyEvent.VK_F8);phase=25;after=ticks+12;}
            if(phase==25&&ticks>=after){up(java.awt.event.KeyEvent.VK_F8);require(mc.screen==previous,"WORKSPACE_CLOSED_NATIVE_INVENTORY");save("native-screen-priority",Map.of("screen",mc.screen.getClass().getSimpleName(),"unchanged",true));mc.setScreen(null);down(java.awt.event.KeyEvent.VK_F8);phase=26;after=ticks+12;}
            if(phase==26&&ticks>=after){up(java.awt.event.KeyEvent.VK_F8);require(shown(),"WORKSPACE_SHOW_BEFORE_IME");preedit(true);down(java.awt.event.KeyEvent.VK_F8);phase=27;after=ticks+12;}
            if(phase==27&&ticks>=after){up(java.awt.event.KeyEvent.VK_F8);require(shown(),"WORKSPACE_CONSUMED_PREEDIT_KEY");preedit(false);save("native-preedit-priority",Map.of("injection","EXPLICIT_NATIVE_PREEDIT_NOT_OS_IME_QUALITY","workspaceRetained",true));WorldUiSmokeServer.WorkspaceProof.requested=true;phase=28;}
            if(phase==28&&WorldUiSmokeServer.WorkspaceProof.saved){require(host.browser()==browser&&WorldUiSmokeServer.workspaceTaskRevision==1,"WORKSPACE_FINAL_PARITY");require(mc.options.hideGui==originalHudHidden,"WORKSPACE_TOGGLED_VANILLA_HUD");cleanup();save("result",Map.of("status","WORKSPACE_NATIVE_OS_KEYS_VERIFIED","providerCalls",0,"fullV1",false,"reboundKey",MineAgentClientMod.TOGGLE_WORKSPACE.saveString(),"browserPreserved",true));finished=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_WORKSPACE_OK");}
        }catch(Exception e){cleanup();try{save("failure",Map.of("phase",phase,"error",e.toString(),"probe",probe==null?new JsonObject():probe));}catch(Exception ignored){}WorldUiSmokeServer.failure="WORKSPACE_FAILED_"+phase+"_"+e.getClass().getSimpleName();}
    }
}
