package dev.mineagent.runtime.neoforge.client.webui;
import com.google.gson.*;
import dev.mineagent.runtime.api.ui.UiProtocol.*;
import dev.mineagent.runtime.neoforge.ui.WorldUiSmokeServer;
import dev.mineagent.runtime.neoforge.client.objects.RuntimeObjectRenderer;
import net.minecraft.client.Minecraft;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.ClientTickEvent;
import java.nio.file.*;
import java.util.*;

/** Actual Native interaction followed by ordinary CEF/SDK controls. Explicit fixture, no AI/Provider. */
@EventBusSubscriber(modid="mineagent_runtime",value=Dist.CLIENT)
public final class WorldUiSmokeClient {
    private static int ticks,phase,after;private static boolean busy,backup;private static String view;private static JsonObject proof,probe;private static Session old;
    private static boolean trusted,trustPressed;private static int initialScreenClearTicks;
    private static Session reopened;
    private static final Gson JSON=new Gson();private WorldUiSmokeClient(){}
    public static void accept(JsonObject value){probe=value;}
    private static Path root(){return Minecraft.getInstance().gameDirectory.toPath().resolve(WorldUiSmokeServer.directory());}
    private static void main(String script){var h=WebGuiHostAdapter.INSTANCE;h.browser().executeJavaScript("(()=>{"+script+"})();",h.browser().getURL(),0);}
    private static void frame(String script){var h=WebGuiHostAdapter.INSTANCE;String url=h.packageUrl(view);for(long id:h.browser().getFrameIdentifiers()){var f=h.browser().getFrame(id);if(f!=null&&!f.isMain()&&url.equals(f.getURL())){f.executeJavaScript(script,url,0);return;}}throw new IllegalStateException("WORLD_UI_FRAME_MISSING");}
    @SubscribeEvent public static void tick(ClientTickEvent.Post event)throws Exception{
        if(OpacityPersistenceSmokeClient.resuming()){OpacityPersistenceSmokeClient.tick();return;}
        if(!WorldUiSmokeServer.enabled()||phase==99)return;var mc=Minecraft.getInstance();var host=WebGuiHostAdapter.INSTANCE;ticks++;Files.createDirectories(root());
        if(!backup&&mc.screen instanceof net.minecraft.client.gui.screens.BackupConfirmScreen s){backup=true;var f=s.getClass().getDeclaredField("onProceed");f.setAccessible(true);((net.minecraft.client.gui.screens.BackupConfirmScreen.Listener)f.get(s)).proceed(false,false);}
        if(WorldUiSmokeServer.failure!=null||ticks>4000){Files.writeString(root().resolve("client-failure.json"),JSON.toJson(Map.of("phase",phase,"error",String.valueOf(WorldUiSmokeServer.failure),"screen",mc.screen==null?"NONE":mc.screen.getClass().getName(),"initialized",dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox.snapshot().values().getOrDefault("runtime.initialized","false"))));phase=99;host.close();mc.stop();return;}
        if(phase==8){if(ticks>=after){phase=99;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_WORLD_UI_OK run={}",WorldUiSmokeServer.RUN);mc.stop();}return;}
        if(!trusted&&mc.player!=null){
            if(ticks%20==0)net.neoforged.neoforge.client.network.ClientPacketDistributor.sendToServer(new dev.mineagent.runtime.neoforge.network.MineAgentPayloads.PanelRequest());
            if(mc.screen instanceof dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen screen&&!trustPressed)for(var child:screen.children())if(child instanceof net.minecraft.client.gui.components.Button b&&b.active&&b.getMessage().getString().equals("信任此服务器")){b.onPress(new net.minecraft.client.input.InputWithModifiers(){public int input(){return org.lwjgl.glfw.GLFW.GLFW_KEY_ENTER;}public int modifiers(){return 0;}});trustPressed=true;net.neoforged.neoforge.client.network.ClientPacketDistributor.sendToServer(new dev.mineagent.runtime.neoforge.network.MineAgentPayloads.PanelRequest());break;}
            var snapshot=dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox.snapshot();String fingerprint=snapshot.values().getOrDefault("security.identityFingerprint","");
            if(ticks%20==0)Files.writeString(root().resolve("startup-observation.json"),JSON.toJson(Map.of("ticks",ticks,"trustPressed",trustPressed,"initialized",snapshot.values().getOrDefault("runtime.initialized","false"),"fingerprint",fingerprint)));
            if(trustPressed&&Boolean.parseBoolean(snapshot.values().getOrDefault("runtime.initialized","false"))&&new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fingerprint)==dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){trusted=true;Files.writeString(root().resolve("trust.json"),JSON.toJson(Map.of("actualNativeTrustButton",true,"fingerprint",fingerprint)));mc.setScreen(null);}else return;
        }
        if(NativePopupSmokeClient.enabled()){NativePopupSmokeClient.tick(trusted);return;}
        if(NativeAtlasInputSmokeClient.enabled()){NativeAtlasInputSmokeClient.tick(trusted);return;}
        if(NativeAtlasSmokeClient.enabled()){NativeAtlasSmokeClient.tick(trusted);return;}
        if(phase==0){initialScreenClearTicks=mc.screen==null&&trusted?initialScreenClearTicks+1:0;}
        if(phase==0&&(Boolean.getBoolean("mineagent.workspaceSmoke")||initialScreenClearTicks>=20)&&WorldUiSmokeServer.ready&&RuntimeObjectRenderer.drawn.getOrDefault(WorldUiSmokeServer.firstObject,0)>10){
            if(Boolean.getBoolean("mineagent.workspaceSmoke")){if(!WorkspaceSmokeClient.coldStep())return;}else if(host.ready())throw new IllegalStateException("WORLD_UI_SHOULD_START_WITHOUT_CONTROL_PANEL");
            var e=mc.level.getEntity(WorldUiSmokeServer.firstObject);mc.gameMode.interact(mc.player,e,new net.minecraft.world.phys.EntityHitResult(e,e.position().add(0,1,0)),net.minecraft.world.InteractionHand.MAIN_HAND);phase=1;
        }
        if(host.ready()&&ticks%10==0)main("window.mineagentQuery({request:JSON.stringify({channel:'worldUiSmokeProbe',chat:!!document.querySelector('#chat-draft'),generation:!!document.querySelector('#generation-prompt'),statusWindow:!!document.querySelector('#echo-input'),statusVisible:!!document.querySelector('[data-view-id=runtime-status]')&&getComputedStyle(document.querySelector('[data-view-id=runtime-status]')).display!=='none',windows:[...document.querySelectorAll('.window')].map(n=>({id:n.dataset.viewId,title:n.dataset.title,kind:n.dataset.contentKind,visible:getComputedStyle(n).display!=='none'}))}),persistent:false,onSuccess(){},onFailure(){}});");
        if(phase==1&&host.ready()){
            var views=PackageContentClient.worldViews();if(views.size()==1&&PackageContentClient.session(views.getFirst())!=null&&probe!=null){
                view=views.getFirst();old=PackageContentClient.session(view);if(probe.get("chat").getAsBoolean()||probe.get("generation").getAsBoolean()||probe.get(Boolean.getBoolean("mineagent.workspaceSmoke")?"statusVisible":"statusWindow").getAsBoolean())throw new IllegalStateException("WORLD_UI_CONTROL_PANEL_COUPLED");
                Files.writeString(root().resolve("standalone.json"),JSON.toJson(Map.of("probe",probe,"session",old)));phase=2;after=ticks+20;
            }
        }
        if(phase==2&&ticks>=after&&!busy){busy=true;PackagePageAgent.inspectManagedView(view).whenComplete((value,error)->mc.execute(()->{try{
            if(error!=null)throw new IllegalStateException(error);Files.writeString(root().resolve("before-dom.json"),value);String text=JsonParser.parseString(value).getAsJsonObject().get("visibleText").getAsString();if(!text.contains("initial")){busy=false;after=ticks+10;return;}
            frame("const f=document.querySelector('#label');f.value='仅修改实例一';f.dispatchEvent(new Event('input',{bubbles:true}));document.querySelector('#save').click();");phase=3;after=ticks+30;busy=false;
        }catch(Exception e){fail(e);}}));}
        if(phase==3&&WorldUiSmokeServer.changed&&!busy){busy=true;frame("window.worldFixtureProbe();");phase=4;after=ticks+20;busy=false;}
        if(phase==4&&ticks>=after&&!busy){busy=true;PackagePageAgent.inspectManagedView(view).whenComplete((value,error)->mc.execute(()->{try{
            if(error!=null)throw new IllegalStateException(error);String text=JsonParser.parseString(value).getAsJsonObject().get("visibleText").getAsString();int start=text.indexOf("WORLD_UI_PROOF:");if(start<0){busy=false;after=ticks+10;return;}
            proof=JsonParser.parseString(text.substring(start+15)).getAsJsonObject();Files.writeString(root().resolve("proof.json"),JSON.toJson(proof));Files.writeString(root().resolve("verified-dom.json"),value);
            if(!proof.get("stale").getAsString().equals("WORLD_UI_STATE_CONFLICT")||!proof.get("scope").getAsString().equals("PERMISSION_DENIED")||!proof.get("draftPreserved").getAsBoolean()||!proof.getAsJsonObject("after").getAsJsonObject("data").get("readOnlyGuard").getAsBoolean()||text.contains("NATIVE_PRIVATE_NOT_PUBLISHED"))throw new IllegalStateException("WORLD_UI_BOUNDARY_PROOF_FAILED");
            frame("document.querySelector('#proof').textContent='';");main("document.querySelector('#open-chat').click();document.querySelector('[data-view-id=runtime-chat] [aria-label=关闭]').click();");phase=5;after=ticks+25;busy=false;
        }catch(Exception e){fail(e);}}));}
        if(phase==5&&ticks>=after&&!busy){busy=true;PackagePageAgent.captureManagedView(view).whenComplete((shot,error)->mc.execute(()->{try{if(error!=null)throw new IllegalStateException(error);Files.write(root().resolve("private.png"),shot.png());net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),image->{try(image){image.writeToFile(root().resolve("world-ui.png"));mc.execute(()->{busy=false;phase=6;after=ticks+10;});}catch(Exception e){mc.execute(()->fail(e));}});}catch(Exception e){fail(e);}}));}
        if(phase==6&&ticks>=after){if(Boolean.getBoolean("mineagent.objectDirectorySmoke")&&!dev.mineagent.runtime.neoforge.task.ObjectDirectorySmokeServer.finished)return;if(!LivePlacementSmokeClient.mode().isEmpty()&&!LivePlacementSmokeClient.finished){LivePlacementSmokeClient.step(view);return;}if(ViewSettingsSmokeClient.enabled()&&!ViewSettingsSmokeClient.finished){ViewSettingsSmokeClient.step(view);return;}if(Boolean.getBoolean("mineagent.workspaceSmoke")&&!WorkspaceSmokeClient.finished){WorkspaceSmokeClient.step(view);return;}if(WorldUiSmokeServer.moving()&&!WorldInstanceMoveSmokeClient.finished){WorldInstanceMoveSmokeClient.step(old);return;}host.close();WorldUiSmokeServer.closedUi=true;phase=7;after=ticks+80;}
        if(phase==71&&WorldUiSmokeServer.moving()&&UiClientSessions.current()!=null&&host.ready()&&!WorldInstanceMoveSmokeClient.replayAfterRootRenewal())return;
        if(phase==7&&WorldUiSmokeServer.independent&&ticks>=after&&!busy){busy=true;host.openStandalone();phase=71;}
        if(phase==71&&UiClientSessions.current()!=null&&host.ready()){if(!LivePlacementSmokeClient.mode().isEmpty()&&!LivePlacementSmokeClient.afterReopen())return;phase=72;var args=proof.getAsJsonObject("lastArgs");UiClientSessions.contentRequest("command",old,"worldui.action",Map.of("name","rename","payload",JSON.toJson(args.get("payload")),"expectedRevision",args.get("revision").getAsString()),UUID.fromString(proof.get("operation").getAsString())).whenComplete((receipt,error)->mc.execute(()->{try{
            if(error!=null)throw new IllegalStateException(error);Files.writeString(root().resolve("closed-replay.json"),JSON.toJson(receipt));if(Set.of(Code.APPLIED,Code.OBSERVED,Code.IN_PROGRESS).contains(receipt.code()))throw new IllegalStateException("WORLD_UI_CLOSED_REPLAY_LEAKED");var entity=mc.level.getEntity(WorldUiSmokeServer.firstObject);mc.gameMode.interact(mc.player,entity,new net.minecraft.world.phys.EntityHitResult(entity,entity.position().add(0,1,0)),net.minecraft.world.InteractionHand.MAIN_HAND);phase=73;busy=false;
        }catch(Exception e){fail(e);}}));}
        if(phase==73&&!busy&&PackageContentClient.worldViews().size()==1){var id=PackageContentClient.worldViews().getFirst();var session=PackageContentClient.session(id);if(session!=null){if(ViewSettingsSmokeClient.enabled()&&!ViewSettingsSmokeClient.afterReopen(id))return;reopened=session;if(old.sessionId().equals(reopened.sessionId()))throw new IllegalStateException("WORLD_UI_SESSION_REUSED");phase=74;busy=true;var args=proof.getAsJsonObject("lastArgs");UiClientSessions.contentRequest("command",reopened,"worldui.action",Map.of("name","rename","payload",JSON.toJson(args.get("payload")),"expectedRevision",args.get("revision").getAsString()),UUID.fromString(proof.get("operation").getAsString())).whenComplete((receipt,error)->mc.execute(()->{try{if(error!=null||receipt.code()!=Code.APPLIED)throw new IllegalStateException("WORLD_UI_DURABLE_REPLY_MISSING",error);Files.writeString(root().resolve("reopened-replay.json"),JSON.toJson(Map.of("oldSession",old,"freshSession",reopened,"receipt",receipt)));WorldUiSmokeServer.moveAway=true;busy=false;after=ticks+30;}catch(Exception e){fail(e);}}));}}
        if(phase==74&&WorldUiSmokeServer.away&&ticks>=after&&!busy){phase=75;busy=true;var args=proof.getAsJsonObject("lastArgs");UiClientSessions.contentRequest("command",reopened,"worldui.action",Map.of("name","rename","payload",JSON.toJson(args.get("payload")),"expectedRevision",args.get("revision").getAsString()),UUID.fromString(proof.get("operation").getAsString())).whenComplete((receipt,error)->mc.execute(()->{try{if(error!=null)throw new IllegalStateException(error);Files.writeString(root().resolve("distance-replay.json"),JSON.toJson(receipt));if(Set.of(Code.APPLIED,Code.OBSERVED,Code.IN_PROGRESS).contains(receipt.code()))throw new IllegalStateException("WORLD_UI_DISTANCE_REPLAY_LEAKED");WorldUiSmokeServer.finish=true;busy=false;}catch(Exception e){fail(e);}}));}
        if(phase==75&&WorldUiSmokeServer.done&&!busy){var composition=WebGuiPaintComposition.snapshot();if(!composition.get("status").equals("PAINT_LAYOUT_MATCHED"))return;Files.writeString(root().resolve("paint-layout-final.json"),JSON.toJson(composition));var paint=McefPaintBoundary.metrics();Files.writeString(root().resolve("paint-boundary.json"),JSON.toJson(paint));if(((Number)paint.get("midFrameUploads")).longValue()!=0||((Number)paint.get("applied")).longValue()==0)throw new IllegalStateException("PAINT_BOUNDARY_NOT_VERIFIED");Files.writeString(root().resolve("client-result.json"),JSON.toJson(Map.of("status","WORLD_UI_PLAYER_INSTANCE_VERIFIED","newSessionDurableDedup",true,"distanceRevocation",true,"providerCalls",0,"fullV1",false)));phase=8;host.close();Files.writeString(root().resolve("paint-boundary-closed.json"),JSON.toJson(McefPaintBoundary.metrics()));Files.writeString(root().resolve("paint-layout-closed.json"),JSON.toJson(WebGuiPaintComposition.snapshot()));if(((Number)McefPaintBoundary.metrics().get("pending")).intValue()!=0)throw new IllegalStateException("PAINT_QUEUE_NOT_CLEARED");mc.disconnectFromWorld(net.minecraft.network.chat.Component.literal("World UI fixture complete"));after=ticks+20;}
    }
    private static void fail(Exception e){try{Files.writeString(root().resolve("client-failure.json"),JSON.toJson(Map.of("phase",phase,"error",e.toString())));}catch(Exception ignored){}phase=99;WebGuiHostAdapter.INSTANCE.close();Minecraft.getInstance().stop();throw new IllegalStateException("WORLD_UI_SMOKE_FAILED",e);}
}
