package dev.mineagent.runtime.worker.generation;

import dev.mineagent.runtime.api.packages.*;
import dev.mineagent.runtime.core.crypto.IdentitySigner;
import dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer;
import dev.mineagent.runtime.core.packages.RuntimePackageLibrary;
import java.nio.charset.StandardCharsets;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.UUID;

/** Publishes verified generated bytes into the existing library, never a parallel UI-package system. */
public final class RuntimePackagePublisher {
    private RuntimePackagePublisher() {}
    public static RuntimePackage publish(ParsedRuntimePackage parsed, UUID id, RuntimePackageLibrary library,
                                         IdentitySigner signer) throws Exception {
        var candidate = prepare(parsed, id, signer);
        var installed = library.install(candidate);
        if (!installed.accepted()) throw new IllegalStateException("PACKAGE_PUBLICATION_REJECTED: " + installed.errorCode());
        return library.get(id).orElseThrow();
    }
    /** Build/sign off the game thread; installation still requires the authoritative commit fence. */
    public static RuntimePackage prepare(ParsedRuntimePackage parsed, UUID id, IdentitySigner signer) throws Exception {
        return prepare(parsed,id,signer,PackageOrigin.GENERATED);
    }
    public static RuntimePackage prepare(ParsedRuntimePackage parsed,UUID id,IdentitySigner signer,PackageOrigin origin)throws Exception{
        FeedbackPackageContract.validate(parsed);
        if(origin!=PackageOrigin.GENERATED&&origin!=PackageOrigin.EXPLICIT_IMPORT)throw new IllegalArgumentException("PACKAGE_ORIGIN");
        var resources = new LinkedHashMap<String, RuntimeResourceRef>();
        for (var f : parsed.files()) resources.put(f.path(), new RuntimeResourceRef(f.path(), f.sha256(), f.side(), f.mediaType(), f.content().length));
        var definitions = new LinkedHashMap<UUID, RuntimeDefinition>();
        parsed.definitions().forEach(d -> definitions.put(d.definitionId(), d));
        var draft = new RuntimePackage(id, parsed.type(), parsed.name(), parsed.version(), parsed.activationMode(),
                parsed.dependencies(), parsed.permissions(), parsed.entrypoints(), definitions, resources, origin,
                false, 1, "0".repeat(64), "", System.currentTimeMillis(),parsed.nativeCompatibility());
        if(draft.activationMode()==ActivationMode.BOOT_EXTENSION)dev.mineagent.runtime.core.boot.BootExtensionPlan.validate(draft);
        if(draft.entrypoints().containsKey("client"))dev.mineagent.runtime.core.packages.ClientScriptPlan.inspect(draft);
        if(draft.entrypoints().containsKey("client_java"))dev.mineagent.runtime.core.packages.ClientJavaPlan.inspect(draft);
        String hash = RuntimePackageCanonicalizer.sha256(draft);
        return new RuntimePackage(id, draft.type(), draft.name(), draft.version(), draft.activationMode(), draft.dependencies(),
                draft.permissions(), draft.entrypoints(), draft.definitions(), draft.resources(), draft.origin(), false, 1,
                hash, Base64.getEncoder().encodeToString(signer.sign(hash.getBytes(StandardCharsets.US_ASCII))), draft.updatedAtEpochMillis(),draft.nativeCompatibility());
    }
}
