package dev.mineagent.runtime.core.interaction;
import org.junit.jupiter.api.Test;import static org.junit.jupiter.api.Assertions.*;import dev.mineagent.runtime.core.creature.*;
class EntityInteropSpecTest {
 @Test void selectorsAndLogicKeepIndependentEvents(){var r=EntityLogicSpec.parse("""
 {"entity_type":"twilightforest:naga","block":["attack","move"],"damage_taken_multiplier":0.5,"blocked_goals":["twilightforest.entity.ai.goal.NagaSmashGoal"],"callbacks":{"interact":[{"type":"effect","value":"minecraft:glowing"}]}}
 """);assertTrue(r.block().contains("attack"));assertFalse(r.block().contains("attacked"));assertEquals(.5,r.taken());assertTrue(r.selector().matches("minecraft:overworld","x","twilightforest:naga","",-1));assertFalse(r.selector().matches("minecraft:the_nether","x","twilightforest:naga","",-1));assertFalse(r.selector().matches("minecraft:overworld","x","twilightforest:naga","",0));}
 @Test void visualTracksUsePixelPartsAndBlockRootAndAllowMultipart(){var r=EntityAnimationSpec.parse("""
 {"entity_type":"twilightforest:naga","part_index":0,"block_native":true,"mode":"replace","root":[{"tick":0,"translation":[0,1,0]}],"parts":{"root/head":[{"tick":0,"translation":[32,0,0],"rotation":[0,0,30]}]}}
 """);assertTrue(r.blockNative());assertFalse(r.additive());assertEquals(1,CreatureAnimation.sample(r.root(),0)[1]);assertEquals(2,CreatureAnimation.sample(r.parts().get("root/head"),0)[0]);assertEquals(30,CreatureAnimation.sample(r.parts().get("root/head"),0)[5]);assertTrue(r.selector().matches("minecraft:overworld","x","twilightforest:naga","",0));}
 @Test void invalidOrAmbiguousSelectorsCallbacksAndCoordinatesFail(){assertThrows(IllegalArgumentException.class,()->EntityLogicSpec.parse("{\"entity_type\":\"minecraft:cow\",\"entity_id\":\"00000000-0000-0000-0000-000000000001\"}"));assertThrows(IllegalArgumentException.class,()->EntityLogicSpec.parse("{\"entity_type\":\"minecraft:cow\",\"movement_scale\":[-1,1,1]}"));assertThrows(IllegalArgumentException.class,()->EntityLogicSpec.parse("{\"entity_type\":\"minecraft:cow\",\"callbacks\":{\"interact\":[{\"type\":\"python\",\"value\":\"x\"}]}}"));assertThrows(IllegalArgumentException.class,()->EntityAnimationSpec.parse("{\"entity_type\":\"minecraft:cow\",\"part_index\":1.5}"));}
 @Test void reusableNativeVisualIsAReferenceNotABossClassClone(){var d=CreatureDefinition.parse("{\"name\":\"borrowed\",\"native_visual\":\"twilightforest:naga\",\"health\":40,\"disposition\":\"friendly\"}");assertEquals("twilightforest:naga",d.nativeVisual());assertEquals(40,d.health());assertEquals("friendly",d.disposition());assertEquals("",CreatureDefinition.parse("{\"name\":\"old\"}").nativeVisual());assertThrows(IllegalArgumentException.class,()->CreatureDefinition.parse("{\"name\":\"recursive\",\"native_visual\":\"mineagent_runtime:runtime_creature\"}"));}
}
