package dev.mineagent.runtime.scripting.javaext;

import dev.mineagent.runtime.api.packages.ClientPackageData;
import dev.mineagent.runtime.api.packages.ClientPackageExports;
import dev.mineagent.runtime.core.packages.JavaDependencyGraph;
import java.net.*;
import java.nio.file.*;
import java.util.*;

/** CLIENT-only explicit-consent loader with exact already-running same-language dependency pins. */
public final class ClientJavaExtensionManager implements AutoCloseable {
    private record Loaded(ClientRuntimeExtension extension,ChildFirst loader,String hash,String entrypoint){}
    private final Map<UUID,Loaded> loaded=new LinkedHashMap<>();private final Set<UUID> attempted=new HashSet<>();private final Map<UUID,JavaDependencyGraph> reservations=new LinkedHashMap<>();private Map<UUID,List<UUID>> consumers=Map.of();
    public synchronized void pin(UUID consumer,JavaDependencyGraph graph){if(!graph.root().equals(consumer))throw new IllegalStateException("CLIENT_JAVA_DEPENDENCY_ROOT");var old=reservations.get(consumer);if(old!=null&&!old.equals(graph))throw new IllegalStateException("CLIENT_JAVA_DEPENDENCY_CHANGED");for(var node:graph.nodes()){var dependency=loaded.get(node.publication());if(dependency==null||!dependency.hash().equals(node.artifact())||!dependency.entrypoint().equals(node.className()))throw new IllegalStateException("CLIENT_JAVA_DEPENDENCY_NOT_LOADED");graph.requireEmbedded(node,reservations.get(node.publication()));}if(old==null){reservations.put(consumer,graph);reindex();}}
    private void reindex(){var index=new LinkedHashMap<UUID,ArrayList<UUID>>();reservations.forEach((consumer,graph)->graph.scopes().forEach(scope->index.computeIfAbsent(scope,k->new ArrayList<>()).add(consumer)));var next=new LinkedHashMap<UUID,List<UUID>>();index.forEach((id,list)->next.put(id,list.stream().sorted().toList()));consumers=Map.copyOf(next);}
    public synchronized List<UUID> consumers(UUID dependency){return consumers.getOrDefault(dependency,List.of());}
    public synchronized boolean attempted(UUID scope){return attempted.contains(scope);}
    public synchronized void requireCanUnload(UUID scope){if(!consumers(scope).isEmpty())throw new IllegalStateException("CLIENT_CODE_DEPENDENCY_IN_USE");}
    private void release(UUID scope){reservations.remove(scope);attempted.remove(scope);reindex();}
    public synchronized Object load(UUID scope,Path jar,String expected,String entrypoint,Map<String,Object> bindings)throws Exception{return load(scope,jar,expected,entrypoint,bindings,JavaDependencyGraph.empty(scope),Map.of());}
    public synchronized Object load(UUID scope,Path jar,String expected,String entrypoint,Map<String,Object> bindings,JavaDependencyGraph graph,Map<String,UUID> owners)throws Exception{
        Objects.requireNonNull(scope);if(loaded.containsKey(scope)||attempted.contains(scope))throw new IllegalStateException("CLIENT_JAVA_PRIOR_ACTIVE_OR_UNKNOWN");pin(scope,graph);ChildFirst loader=null;boolean invoked=false;try{var routes=new LinkedHashMap<String,ClassLoader>();for(var e:owners.entrySet()){if(!graph.scopes().contains(e.getValue()))throw new IllegalStateException("CLIENT_JAVA_DEPENDENCY_CLASS_OWNER");var dependency=loaded.get(e.getValue());if(dependency==null)throw new IllegalStateException("CLIENT_JAVA_DEPENDENCY_NOT_LOADED");if(routes.put(e.getKey(),dependency.loader())!=null)throw new IllegalStateException("CLIENT_JAVA_DEPENDENCY_CLASS_AMBIGUOUS");}var actual=new LinkedHashMap<>(bindings);if(!graph.required().isEmpty()){var dependencies=new LinkedHashMap<UUID,ClientRuntimeExtension>();for(var id:graph.required().keySet())dependencies.put(id,loaded.get(graph.node(id).publication()).extension());actual.put("dependencies",Map.copyOf(dependencies));}
            Path file=requireJar(jar);if(!JavaExtensionManager.sha256(file).equals(expected))throw new IllegalStateException("CLIENT_JAVA_ARTIFACT_HASH");if(entrypoint==null||!entrypoint.matches("[A-Za-z_$][A-Za-z0-9_$.]{0,255}"))throw new IllegalArgumentException("CLIENT_JAVA_ENTRYPOINT");loader=new ChildFirst(new URL[]{file.toUri().toURL()},new DependencyLoader(routes));attempted.add(scope);Class<?> type=Class.forName(entrypoint,false,loader);if(!ClientRuntimeExtension.class.isAssignableFrom(type))throw new IllegalArgumentException("CLIENT_JAVA_INTERFACE_REQUIRED");var extension=(ClientRuntimeExtension)type.getDeclaredConstructor().newInstance();invoked=true;Object result=extension.start(Map.copyOf(actual));loaded.put(scope,new Loaded(extension,loader,expected,entrypoint));return result;
        }catch(Exception|LinkageError failure){if(!invoked)release(scope);if(loader!=null)try{loader.close();}catch(Exception cleanup){failure.addSuppressed(cleanup);}if(invoked)throw new IllegalStateException("CLIENT_JAVA_START_UNKNOWN",failure);if(failure instanceof Exception e)throw e;throw new IllegalStateException("CLIENT_JAVA_START_LINKAGE_UNCERTAIN",failure);}
    }
    public synchronized boolean isLoaded(UUID scope){return loaded.containsKey(scope);}
    public synchronized Object call(UUID scope,String export,List<?> arguments)throws Exception{if(export==null||export.length()>128||!export.isEmpty()&&(!export.matches("[A-Za-z_$][A-Za-z0-9_$]{0,127}")||Set.of("__proto__","prototype","constructor").contains(export)))throw new IllegalArgumentException("CLIENT_PACKAGE_EXPORT");var value=loaded.get(scope);if(value==null)throw new IllegalStateException("CLIENT_JAVA_DEPENDENCY_NOT_LOADED");if(!(value.extension() instanceof ClientPackageExports callable))throw new IllegalStateException("CLIENT_JAVA_DEPENDENCY_EXPORTS_REQUIRED");return ClientPackageData.copy(callable.call(export,ClientPackageData.arguments(arguments)));}
    public synchronized boolean unload(UUID scope)throws Exception{requireCanUnload(scope);var value=loaded.remove(scope);if(value==null){if(!attempted.contains(scope))release(scope);return false;}try{value.extension.stop();}catch(LinkageError failure){throw new IllegalStateException("CLIENT_JAVA_STOP_LINKAGE_UNCERTAIN",failure);}finally{value.loader.close();release(scope);}return true;}
    private static Path requireJar(Path value)throws Exception{if(value==null)throw new IllegalArgumentException("CLIENT_JAVA_ARTIFACT_REQUIRED");Path path=value.toAbsolutePath().normalize();if(!Files.isRegularFile(path,LinkOption.NOFOLLOW_LINKS)||Files.isSymbolicLink(path))throw new IllegalArgumentException("CLIENT_JAVA_ARTIFACT_FILE");try(var in=Files.newInputStream(path)){byte[] magic=in.readNBytes(4);if(magic.length!=4||magic[0]!='P'||magic[1]!='K'||!((magic[2]==3&&magic[3]==4)||(magic[2]==5&&magic[3]==6)))throw new IllegalArgumentException("CLIENT_JAVA_ARTIFACT_FORMAT");}return path;}
    @Override public synchronized void close()throws Exception{Exception first=null;while(!loaded.isEmpty()){UUID candidate=loaded.keySet().stream().filter(id->consumers(id).isEmpty()).findFirst().orElse(null);if(candidate==null){if(first==null)first=new IllegalStateException("CLIENT_JAVA_DEPENDENCY_CLEANUP_BLOCKED");break;}try{unload(candidate);}catch(Exception failure){if(first==null)first=failure;}}if(first!=null)throw first;}
    private static final class DependencyLoader extends ClassLoader {private final Map<String,ClassLoader> routes;DependencyLoader(Map<String,ClassLoader> routes){super(ClientRuntimeExtension.class.getClassLoader());this.routes=routes;}@Override protected Class<?> loadClass(String name,boolean resolve)throws ClassNotFoundException{var owner=routes.get(name);return owner==null?super.loadClass(name,resolve):owner.loadClass(name);}}
    private static final class ChildFirst extends URLClassLoader {ChildFirst(URL[] urls,ClassLoader parent){super(urls,parent);}@Override protected Class<?> loadClass(String name,boolean resolve)throws ClassNotFoundException{synchronized(getClassLoadingLock(name)){Class<?> type=findLoadedClass(name);if(type==null){boolean parent=name.startsWith("java.")||name.startsWith("javax.")||name.startsWith("dev.mineagent.runtime.api.")||name.equals(RuntimeExtension.class.getName())||name.equals(ClientRuntimeExtension.class.getName());if(!parent)try{type=findClass(name);}catch(ClassNotFoundException ignored){}if(type==null)type=super.loadClass(name,false);}if(resolve)resolveClass(type);return type;}}}
}
