package dev.mineagent.runtime.core.files;
import com.fasterxml.jackson.databind.*;
import java.io.*;import java.nio.file.*;import java.nio.channels.FileChannel;import java.nio.ByteBuffer;import java.security.*;import java.util.*;import java.util.zip.*;

/** Player-selected files only. Random storage paths, immutable published assets, private manifests. */
public final class FileLibrary {
    public static final long MAX_ASSET_BYTES=8L*1024*1024*1024;
    private static final ObjectMapper JSON=new ObjectMapper();
    public record Asset(UUID id,UUID owner,String name,String kind,long bytes,String sha256,long created,String source){}
    private static final class Upload{final UUID id=UUID.randomUUID(),owner;final String name,kind;final Path root;long bytes;int directories;final Map<UUID,Part> parts=new LinkedHashMap<>();Upload(UUID owner,String name,String kind,Path root){this.owner=owner;this.name=name;this.kind=kind;this.root=root;}}
    private static final class Part{final UUID id=UUID.randomUUID();final String path;final long total;final Path file;long offset;Part(String path,long total,Path file){this.path=path;this.total=total;this.file=file;}}
    private final Path root;private final Map<UUID,Upload> uploads=new HashMap<>();
    public FileLibrary(Path root)throws IOException{this.root=root.toAbsolutePath().normalize();Files.createDirectories(this.root);if(Files.isSymbolicLink(this.root))throw new IOException("BUILDING_STORE_LINK");}
    private static void require(boolean v,String code){if(!v)throw new IllegalArgumentException("BUILDING_"+code);}
    public static String safeRelative(String name){require(name!=null&&!name.isBlank()&&name.length()<=512&&!name.startsWith("/")&&!name.contains("\\")&&!name.contains(":")&&!name.codePoints().anyMatch(c->c<32),"FILE_PATH");var parts=name.split("/",-1);for(String part:parts)require(!part.isBlank()&&!part.equals(".")&&!part.equals("..")&&!part.endsWith(".")&&!part.endsWith(" "),"FILE_PATH");return name;}
    public static boolean allowed(String name){try{safeRelative(name);return true;}catch(IllegalArgumentException invalid){return false;}}

    private Path directory(UUID id){return root.resolve(id.toString());}
    public synchronized UUID begin(UUID owner,String name,String kind)throws IOException{require(Set.of("FILE","FOLDER","WORLD").contains(kind)&&name!=null&&!name.isBlank()&&name.length()<=240&&!name.codePoints().anyMatch(c->c<32),"UPLOAD_ARGUMENTS");safeRelative(name);require(!name.contains("/")&&(!kind.equals("FILE")||allowed(name)),"FILE_NAME");require(uploads.values().stream().filter(u->u.owner.equals(owner)).count()<4,"UPLOAD_BUSY");var u=new Upload(owner,name,kind,root.resolve("pending-"+UUID.randomUUID()));Files.createDirectory(u.root);Files.createDirectory(u.root.resolve("data"));uploads.put(u.id,u);return u.id;}
    private Upload upload(UUID owner,UUID id){var u=uploads.get(id);require(u!=null&&u.owner.equals(owner),"UPLOAD_NOT_FOUND");return u;}
    public synchronized void directory(UUID owner,UUID upload,String path)throws IOException{var u=upload(owner,upload);require(!u.kind.equals("FILE")&&++u.directories<=20000,"FOLDER_DIRECTORY_LIMIT");safeRelative(path);Path target=u.root.resolve("data").resolve(path).normalize();require(target.startsWith(u.root.resolve("data")),"FILE_PATH");Files.createDirectories(target);}
    public synchronized UUID beginFile(UUID owner,UUID upload,String path,long bytes)throws IOException{var u=upload(owner,upload);safeRelative(path);require(allowed(path)&&bytes>=0&&bytes<=MAX_ASSET_BYTES&&u.bytes+bytes<=MAX_ASSET_BYTES&&u.parts.size()<20000,"FILE_SIZE_OR_TYPE");require(!u.kind.equals("FILE")||u.parts.isEmpty(),"SINGLE_FILE_REQUIRED");require(u.parts.values().stream().noneMatch(p->p.path.equals(path)),"DUPLICATE_FILE");Path target=u.root.resolve("data").resolve(path).normalize();require(target.startsWith(u.root.resolve("data")),"FILE_PATH");Files.createDirectories(target.getParent());Files.createFile(target);var part=new Part(path,bytes,target);u.parts.put(part.id,part);u.bytes+=bytes;return part.id;}
    public synchronized long chunk(UUID owner,UUID upload,UUID part,long offset,byte[] data)throws IOException{var u=upload(owner,upload);var p=u.parts.get(part);require(p!=null&&p.offset==offset&&data.length>0&&data.length<=1024*1024&&p.offset+data.length<=p.total,"CHUNK_OFFSET_OR_SIZE");require(Files.getFileStore(root).getUsableSpace()>256L*1024*1024,"DISK_SPACE");try(var out=FileChannel.open(p.file,StandardOpenOption.WRITE)){out.position(offset);var buffer=ByteBuffer.wrap(data);while(buffer.hasRemaining())out.write(buffer);out.force(false);}p.offset+=data.length;return p.offset;}
    public synchronized Asset finish(UUID owner,UUID upload,String source)throws Exception{
        var u=upload(owner,upload);require((!u.kind.equals("FILE")||!u.parts.isEmpty())&&u.parts.values().stream().allMatch(p->p.offset==p.total),"UPLOAD_INCOMPLETE");UUID id=UUID.randomUUID();Path dir=directory(id);String kind=u.kind;

        var digest=MessageDigest.getInstance("SHA-256");for(var p:u.parts.values().stream().sorted(Comparator.comparing(v->v.path)).toList()){if(!u.kind.equals("FILE")){digest.update(p.path.getBytes(java.nio.charset.StandardCharsets.UTF_8));digest.update((byte)0);digest.update(ByteBuffer.allocate(8).putLong(p.total).array());}try(var in=Files.newInputStream(p.file)){byte[] b=new byte[65536];for(int n;(n=in.read(b))!=-1;)digest.update(b,0,n);}}
        String hash=HexFormat.of().formatHex(digest.digest());var asset=new Asset(id,owner,u.name,kind,u.bytes,hash,System.currentTimeMillis(),source==null?"LOCAL_UPLOAD":source);Files.writeString(u.root.resolve("asset.json"),JSON.writeValueAsString(asset));Files.move(u.root,dir,StandardCopyOption.ATOMIC_MOVE);uploads.remove(upload);return asset;
    }
    public Asset asset(UUID owner,UUID id)throws IOException{Path dir=directory(id),meta=dir.resolve("asset.json");require(Files.isRegularFile(meta,LinkOption.NOFOLLOW_LINKS)&&!Files.isSymbolicLink(dir),"FILE_NOT_FOUND");var a=JSON.readValue(Files.readString(meta),Asset.class);require(a.owner.equals(owner)&&a.id.equals(id),"FILE_SCOPE");return a;}
    public Map<String,Object> list(UUID owner,String query,int offset)throws Exception{require(query.length()<=128&&offset>=0,"FILE_QUERY");var rows=new ArrayList<Asset>();try(var dirs=Files.list(root)){for(var dir:dirs.toList()){if(!dir.getFileName().toString().matches("[a-f0-9-]{36}"))continue;try{var a=asset(owner,UUID.fromString(dir.getFileName().toString()));if(a.name.toLowerCase(Locale.ROOT).contains(query.toLowerCase(Locale.ROOT)))rows.add(a);}catch(IllegalArgumentException scope){if(!scope.getMessage().equals("BUILDING_FILE_SCOPE"))throw scope;}}}rows.sort(Comparator.comparingLong(Asset::created).reversed());require(offset<=rows.size(),"FILE_OFFSET");return Map.of("files",rows.subList(offset,Math.min(offset+32,rows.size())),"total",rows.size(),"nextOffset",offset+32<rows.size()?offset+32:-1);}
    public Path data(UUID owner,UUID id)throws IOException{asset(owner,id);return directory(id).resolve("data");}
    public Path file(UUID owner,UUID id,String entry)throws Exception{var a=asset(owner,id);Path data=data(owner,id);if(!a.kind.equals("FILE")&&(entry==null||entry.isBlank()))return data;if(entry==null||entry.isBlank()){try(var walk=Files.walk(data)){var files=walk.filter(p->Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)).toList();require(files.size()==1,"FILE_ENTRY_REQUIRED");return files.getFirst();}}safeRelative(entry);Path p=data.resolve(entry).normalize();require(p.startsWith(data)&&Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)&&!Files.isSymbolicLink(p),"FILE_ENTRY");return p;}
    public Asset importFile(UUID owner,Path selected,String source)throws Exception{require(Files.isRegularFile(selected,LinkOption.NOFOLLOW_LINKS)&&!Files.isSymbolicLink(selected),"SELECTED_FILE");String name=selected.getFileName().toString();UUID upload=begin(owner,name,"FILE");long size=Files.size(selected);UUID file=beginFile(owner,upload,name,size);try(var in=Files.newInputStream(selected)){byte[] b=new byte[1024*1024];long offset=0;for(int n;(n=in.read(b))!=-1;)offset=chunk(owner,upload,file,offset,n==b.length?b:Arrays.copyOf(b,n));}return finish(owner,upload,source);}
    /** Bounded ZIP expansion inside the library only; no file is executed or installed. */
    public synchronized Path expand(UUID owner,UUID id)throws Exception{
        Path archive=file(owner,id,"");if(!archive.getFileName().toString().toLowerCase(Locale.ROOT).endsWith(".zip"))return archive;Path target=directory(id).resolve("expanded");if(Files.isDirectory(target))return target;Path pending=directory(id).resolve("expanding-"+UUID.randomUUID());checkZipDirectory(archive);Files.createDirectory(pending);boolean ok=false;try(var zip=new ZipFile(archive.toFile())){var names=new HashSet<String>();long expanded=0;int count=0;var entries=zip.entries();while(entries.hasMoreElements()){var e=entries.nextElement();String name=e.getName();if(e.isDirectory()){safeRelative(name.endsWith("/")?name.substring(0,name.length()-1):name);continue;}safeRelative(name);require(names.add(name)&&++count<=50000,"ARCHIVE_ENTRIES");require(e.getSize()>=0&&e.getSize()<=MAX_ASSET_BYTES-expanded&&(e.getCompressedSize()<=0||e.getSize()/Math.max(1,e.getCompressedSize())<=2000),"ARCHIVE_SIZE");require(Files.getFileStore(root).getUsableSpace()>e.getSize()+256L*1024*1024,"DISK_SPACE");Path path=pending.resolve(name).normalize();require(path.startsWith(pending),"FILE_PATH");Files.createDirectories(path.getParent());try(var in=zip.getInputStream(e);var out=Files.newOutputStream(path,StandardOpenOption.CREATE_NEW)){byte[] b=new byte[65536];var crc=new CRC32();long size=0;for(int n;(n=in.read(b))!=-1;){crc.update(b,0,n);size+=n;expanded+=n;require(size<=e.getSize()&&expanded<=MAX_ASSET_BYTES,"ARCHIVE_SIZE");out.write(b,0,n);}require(size==e.getSize(),"ARCHIVE_SIZE");require(crc.getValue()==e.getCrc(),"ARCHIVE_CRC");}}Files.move(pending,target,StandardCopyOption.ATOMIC_MOVE);ok=true;return target;}finally{if(!ok)deletePrivateTree(pending);}}
    private static void checkZipDirectory(Path file)throws IOException{
        try(var f=new RandomAccessFile(file.toFile(),"r")){long length=f.length();if(length<22)throw new IOException("BUILDING_ARCHIVE_HEADER");int tailSize=(int)Math.min(length,65557);byte[] tail=new byte[tailSize];f.seek(length-tailSize);f.readFully(tail);var b=java.nio.ByteBuffer.wrap(tail).order(java.nio.ByteOrder.LITTLE_ENDIAN);int end=-1;for(int i=tailSize-22;i>=0;i--)if(b.getInt(i)==0x06054b50&&i+22+Short.toUnsignedInt(b.getShort(i+20))==tailSize){end=i;break;}require(end>=0,"ARCHIVE_HEADER");require(b.getShort(end+4)==0&&b.getShort(end+6)==0,"ARCHIVE_SPLIT_UNSUPPORTED");long entries=Short.toUnsignedInt(b.getShort(end+10)),size=Integer.toUnsignedLong(b.getInt(end+12)),offset=Integer.toUnsignedLong(b.getInt(end+16));
            if(entries==65535||size==0xffffffffL||offset==0xffffffffL){require(end>=20&&b.getInt(end-20)==0x07064b50&&b.getInt(end-16)==0&&b.getInt(end-4)==1,"ARCHIVE_ZIP64_HEADER");long at=b.getLong(end-12);require(at>=0&&at<=length-56,"ARCHIVE_ZIP64_HEADER");byte[] header=new byte[56];f.seek(at);f.readFully(header);var h=java.nio.ByteBuffer.wrap(header).order(java.nio.ByteOrder.LITTLE_ENDIAN);require(h.getInt(0)==0x06064b50&&h.getInt(16)==0&&h.getInt(20)==0,"ARCHIVE_ZIP64_HEADER");entries=h.getLong(32);size=h.getLong(40);offset=h.getLong(48);}
            require(entries>=0&&entries<=50000&&size>=0&&size<=64L*1024*1024&&offset>=0&&offset<=length-size,"ARCHIVE_DIRECTORY_BUDGET");}
    }
    public static Path worldRoot(Path directory)throws IOException{try(var walk=Files.walk(directory,5)){var roots=walk.filter(p->p.getFileName().toString().equals("level.dat")&&Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)).map(Path::getParent).toList();require(roots.size()==1,"WORLD_ROOT_AMBIGUOUS");return roots.getFirst();}}
    private void deletePrivateTree(Path dir)throws IOException{require(dir.toAbsolutePath().normalize().startsWith(root)&&!dir.equals(root),"DELETE_BOUNDARY");try(var walk=Files.walk(dir)){for(var p:walk.sorted(Comparator.reverseOrder()).toList())Files.deleteIfExists(p);}}
    public synchronized void cancel(UUID owner,UUID id)throws IOException{var u=upload(owner,id);uploads.remove(id);deletePrivateTree(u.root);}
    public void archive(UUID owner,UUID id,OutputStream target)throws Exception{var a=asset(owner,id);if(a.kind.equals("FILE")){Files.copy(file(owner,id,""),target);return;}Path data=data(owner,id);try(var zip=new ZipOutputStream(target);var walk=Files.walk(data)){for(var p:walk.filter(v->!v.equals(data)&&!Files.isSymbolicLink(v)).sorted().toList()){boolean dir=Files.isDirectory(p,LinkOption.NOFOLLOW_LINKS);zip.putNextEntry(new ZipEntry(data.relativize(p).toString().replace('\\','/')+(dir?"/":"")));if(!dir)Files.copy(p,zip);zip.closeEntry();}}}
}
