package dev.mineagent.runtime.core.creature;
import java.nio.file.*;
import java.sql.*;
import java.util.*;
/** World/owner scoped species; optimistic updates cannot overwrite another species revision. */
public final class CreatureStore implements AutoCloseable {
    public record Species(UUID id,UUID owner,long revision,String source){public CreatureDefinition definition(){return CreatureDefinition.parse(source);}}
    private final Connection db;private final UUID world;
    public CreatureStore(Path path,UUID world)throws Exception{this.world=Objects.requireNonNull(world);Files.createDirectories(path.toAbsolutePath().getParent());db=DriverManager.getConnection("jdbc:sqlite:"+path.toAbsolutePath());try(var s=db.createStatement()){s.execute("PRAGMA busy_timeout=5000");s.execute("CREATE TABLE IF NOT EXISTS mineagent_creatures_v1(world TEXT NOT NULL,owner TEXT NOT NULL,id TEXT NOT NULL,revision INTEGER NOT NULL,source TEXT NOT NULL,PRIMARY KEY(world,id))");}catch(Exception failure){try{db.close();}catch(SQLException close){failure.addSuppressed(close);}throw failure;}}
    public synchronized Optional<Species> get(UUID owner,UUID id)throws Exception{try(var q=db.prepareStatement("SELECT revision,source FROM mineagent_creatures_v1 WHERE world=? AND owner=? AND id=?")){q.setString(1,world.toString());q.setString(2,owner.toString());q.setString(3,id.toString());try(var r=q.executeQuery()){return r.next()?Optional.of(new Species(id,owner,r.getLong(1),r.getString(2))):Optional.empty();}}}
    public synchronized List<Species> list(UUID owner,int offset)throws Exception{if(offset<0)throw new IllegalArgumentException("CREATURE_OFFSET");try(var q=db.prepareStatement("SELECT id,revision,source FROM mineagent_creatures_v1 WHERE world=? AND owner=? ORDER BY id LIMIT 16 OFFSET ?")){q.setString(1,world.toString());q.setString(2,owner.toString());q.setInt(3,offset);try(var r=q.executeQuery()){var out=new ArrayList<Species>();while(r.next())out.add(new Species(UUID.fromString(r.getString(1)),owner,r.getLong(2),r.getString(3)));return List.copyOf(out);}}}
    public synchronized Species put(UUID owner,UUID id,long expected,String source)throws Exception{var def=CreatureDefinition.parse(source);if(expected<0||expected==Long.MAX_VALUE)throw new IllegalArgumentException("CREATURE_REVISION");String sql=expected==0?"INSERT OR IGNORE INTO mineagent_creatures_v1(source,revision,world,owner,id) VALUES(?,?,?,?,?)":"UPDATE mineagent_creatures_v1 SET source=?,revision=? WHERE world=? AND owner=? AND id=? AND revision=?";try(var q=db.prepareStatement(sql)){q.setString(1,def.source());q.setLong(2,expected+1);q.setString(3,world.toString());q.setString(4,owner.toString());q.setString(5,id.toString());if(expected!=0)q.setLong(6,expected);if(q.executeUpdate()!=1)throw new IllegalStateException("CREATURE_STALE_REVISION");}return new Species(id,owner,expected+1,def.source());}
    @Override public synchronized void close()throws SQLException{db.close();}
}
