package dev.mineagent.runtime.core.creature;
import com.fasterxml.jackson.databind.JsonNode;import java.util.*;
/** Visual-only keyframes; never changes collision, damage or navigation authority. */
public final class CreatureAnimation {
 public record Frame(double tick,List<Double> translation,List<Double> rotation,List<Double> scale){}
 public record Clip(int duration,boolean loop,int interval,List<Frame> frames,Map<String,List<Frame>> bones){
  public Clip(int duration,boolean loop,int interval,List<Frame> frames){this(duration,loop,interval,frames,Map.of());}
  public Clip { frames=List.copyOf(frames);bones=Map.copyOf(bones); }
 }
 public static Map<String,Clip> parse(JsonNode node){if(node==null||node.isMissingNode())return Map.of();if(!node.isObject()||node.size()>8)throw new IllegalArgumentException("CREATURE_ANIMATIONS");var result=new LinkedHashMap<String,Clip>();node.properties().forEach(entry->{if(!Set.of("idle","walk","random","hurt","attack","death","interact","ride").contains(entry.getKey()))throw new IllegalArgumentException("CREATURE_ANIMATION_EVENT");var n=entry.getValue();keys(n,"duration_ticks","loop","interval_ticks","keyframes","bones");int duration=integer(n,"duration_ticks",40,1,72000),interval=integer(n,"interval_ticks",200,duration,72000);if(n.has("loop")&&!n.get("loop").isBoolean())throw new IllegalArgumentException("CREATURE_ANIMATION_LOOP");var frames=new ArrayList<Frame>();var array=n.path("keyframes");if(!n.has("keyframes")&&n.has("bones")){var identity=new com.fasterxml.jackson.databind.ObjectMapper().createArrayNode();identity.addObject().put("tick",0);array=identity;}if(!array.isArray()||array.size()<1||array.size()>64)throw new IllegalArgumentException("CREATURE_ANIMATION_FRAMES");double previous=-1;for(var f:array){keys(f,"tick","translation","rotation","scale");double tick=f.path("tick").asDouble(-1);if(!f.path("tick").isNumber()||!Double.isFinite(tick)||tick<=previous||tick<0||tick>duration)throw new IllegalArgumentException("CREATURE_ANIMATION_TIME");previous=tick;frames.add(new Frame(tick,vector(f,"translation",0,-4,4),vector(f,"rotation",0,-720,720),vector(f,"scale",1,.1,4)));}var tracks=new LinkedHashMap<String,List<Frame>>();if(n.has("bones")){var bones=n.get("bones");if(!bones.isObject()||bones.size()>32)throw new IllegalArgumentException("CREATURE_ANIMATION_BONES");for(var bone:bones.properties()){if(!bone.getKey().matches("[a-zA-Z][a-zA-Z0-9_]{0,47}"))throw new IllegalArgumentException("CREATURE_BONE_NAME");var wrapper=new com.fasterxml.jackson.databind.ObjectMapper().createObjectNode();var track=wrapper.putObject("idle");track.put("duration_ticks",duration);track.set("keyframes",bone.getValue());tracks.put(bone.getKey(),parse(wrapper).get("idle").frames());}}result.put(entry.getKey(),new Clip(duration,n.path("loop").asBoolean(entry.getKey().equals("idle")||entry.getKey().equals("walk")),interval,List.copyOf(frames),tracks));});return Map.copyOf(result);}
 private static void keys(JsonNode n,String... fields){if(!n.isObject()||!Set.of(fields).containsAll(n.properties().stream().map(Map.Entry::getKey).toList()))throw new IllegalArgumentException("CREATURE_ANIMATION_FIELDS");}
 private static int integer(JsonNode n,String key,int fallback,int min,int max){if(!n.has(key))return Math.max(min,fallback);var v=n.get(key);if(!v.isIntegralNumber()||!v.canConvertToInt()||v.intValue()<min||v.intValue()>max)throw new IllegalArgumentException("CREATURE_ANIMATION_NUMBER");return v.intValue();}
 private static List<Double> vector(JsonNode n,String key,double fallback,double min,double max){if(!n.has(key))return List.of(fallback,fallback,fallback);var a=n.get(key);if(!a.isArray()||a.size()!=3)throw new IllegalArgumentException("CREATURE_ANIMATION_VECTOR");var out=new ArrayList<Double>();for(var x:a){double value=x.asDouble();if(!x.isNumber()||!Double.isFinite(value)||value<min||value>max)throw new IllegalArgumentException("CREATURE_ANIMATION_VECTOR");out.add(value);}return List.copyOf(out);}
 public static double[] sample(Clip clip,double age){double[] out={0,0,0,0,0,0,1,1,1};if(clip==null||clip.frames.isEmpty())return out;double t=clip.loop?Math.max(0,age)%clip.duration:Math.min(clip.duration,Math.max(0,age));Frame a=clip.frames.getFirst(),b=a;for(var f:clip.frames){if(f.tick<=t)a=f;if(f.tick>=t){b=f;break;}b=f;}double weight=b.tick<=a.tick?0:Math.max(0,Math.min(1,(t-a.tick)/(b.tick-a.tick)));var av=new ArrayList<Double>(a.translation);av.addAll(a.rotation);av.addAll(a.scale);var bv=new ArrayList<Double>(b.translation);bv.addAll(b.rotation);bv.addAll(b.scale);for(int i=0;i<9;i++)out[i]=av.get(i)+(bv.get(i)-av.get(i))*weight;return out;}
 public static double[] sampleBone(Clip clip,String bone,double age){return clip==null?sample(null,age):sample(new Clip(clip.duration,clip.loop,clip.interval,clip.bones.getOrDefault(bone,List.of())),age);}
 private CreatureAnimation(){}
}
