package dev.mineagent.runtime.api.ui;

import java.util.*;

/** Exact display lease. It never confers package ownership, world interaction, or Agent control. */
public final class DeliveryProtocol {
    public static final Set<String> CAPABILITIES=Set.of("delivery.read");
    public static final Set<String> FEEDBACK_CAPABILITIES=Set.of("delivery.read","feedback.submit","feedback.read");
    private DeliveryProtocol(){}
    public static String capability(String action){return switch(action){case "desktop.start","desktop.cancel"->"task.manage";case "desktop.read"->"shell.read";case "studio.read"->"package.preview";case "studio.write"->"package.generate";case "preferences.read"->"conversation.read";case "preferences.write"->"conversation.write";case "package.assetsRead"->"package.preview";case "package.assetsWrite"->"package.generate";case "boot.read"->"world.inspect";case "boot.change"->"world.activate";case "nativeApi.read","nativeApi.refresh"->"world.inspect";case "package.resourcePrepare","package.clientScriptPrepare","package.clientJavaPrepare"->"package.preview";case "package.resourceChunk","package.clientScriptChunk","package.clientJavaChunk"->"package.chunk";case "package.resourceRelease","package.clientScriptRelease","package.clientJavaRelease"->"package.release";case "dataPack.read","world.restoreRead"->"world.inspect";case "dataPack.change"->"world.activate";case "world.restoreResume","world.compatibility"->"world.activate";case "persona.read","persona.save"->"persona.manage";case "agent.modelRead","agent.modelSave","agent.modelModels"->"agent.manage";case "settings.read","settings.write"->"settings.manage";case "task.start","task.control","task.replan","task.eventsRead","task.eventsWrite","task.schedulesRead","task.schedulesWrite","task.historyRead"->"task.manage";case "delivery.accept","delivery.chunk","delivery.release","delivery.codeAccept","delivery.codeChunk","delivery.codeRelease"->"delivery.transfer";case "delivery.manageRead","delivery.manageWrite","delivery.reject","delivery.received","delivery.painted","delivery.closed","delivery.visibility","delivery.codeState"->"delivery.lifecycle";case "feedback.history","feedback.list","feedback.stateRead"->"feedback.read";default->action;};}
    public record Launch(UUID deliveryId,UUID leaseId,String viewId,UUID packageId,long packageRevision,String canonicalSha256,String entryPath,String mode,UUID viewer,long expiresAt,String feedbackPolicySha256){
        public Launch(UUID deliveryId,UUID leaseId,String viewId,UUID packageId,long revision,String hash,String entry,String mode,UUID viewer,long expiresAt){this(deliveryId,leaseId,viewId,packageId,revision,hash,entry,mode,viewer,expiresAt,"");}
        public Launch{Objects.requireNonNull(deliveryId);Objects.requireNonNull(leaseId);Objects.requireNonNull(packageId);Objects.requireNonNull(viewer);feedbackPolicySha256=feedbackPolicySha256==null?"":feedbackPolicySha256;if(!feedbackPolicySha256.isEmpty()&&(!feedbackPolicySha256.matches("[a-f0-9]{64}")||!mode.equals("CONTENT")))throw new IllegalArgumentException("DELIVERY_FEEDBACK_GRANT");if(!viewId.equals("delivery-"+leaseId)||packageRevision<1||canonicalSha256==null||!canonicalSha256.matches("[a-f0-9]{64}")||entryPath==null||!entryPath.startsWith("ui/")||!entryPath.endsWith(".html")||!Set.of("CONTENT","HUD").contains(mode)||expiresAt<0)throw new IllegalArgumentException("DELIVERY_LAUNCH");}
        public UiProtocol.Binding binding(UUID world,String packageVersion){return new UiProtocol.Binding(viewId,packageId,packageRevision,packageVersion,entryPath,world,viewer,viewer,UiProtocol.ActorKind.PLAYER,null,0,"delivery:"+deliveryId+":"+leaseId,false,feedbackPolicySha256.isEmpty()?CAPABILITIES:FEEDBACK_CAPABILITIES);}
    }
    public static boolean bound(UiProtocol.Binding b){return b!=null&&b.targetObjectId().startsWith("delivery:");}
    public static UUID deliveryId(UiProtocol.Binding b){return ids(b)[0];}
    public static UUID leaseId(UiProtocol.Binding b){return ids(b)[1];}
    public static boolean feedbackEnabled(UiProtocol.Binding b){ids(b);return b.capabilities().equals(FEEDBACK_CAPABILITIES);}
    private static UUID[] ids(UiProtocol.Binding b){if(!bound(b)||b.preview()||b.actorKind()!=UiProtocol.ActorKind.PLAYER||!b.actorId().equals(b.viewerPlayerId())||b.taskId()!=null||b.taskRevision()!=0||!Set.of(CAPABILITIES,FEEDBACK_CAPABILITIES).contains(b.capabilities()))throw new IllegalArgumentException("DELIVERY_BINDING");String[] values=b.targetObjectId().split(":",-1);if(values.length!=3)throw new IllegalArgumentException("DELIVERY_TARGET");UUID d=UUID.fromString(values[1]),l=UUID.fromString(values[2]);if(!b.viewId().equals("delivery-"+l))throw new IllegalArgumentException("DELIVERY_VIEW");return new UUID[]{d,l};}
    public static void require(UiProtocol.Session session,UiProtocol.Session shell,Launch launch,String canonical){
        if(session==null||shell==null||!session.serverInstanceId().equals(shell.serverInstanceId())||!session.binding().equals(launch.binding(shell.binding().worldId(),session.binding().packageVersion()))||!launch.viewer().equals(shell.binding().viewerPlayerId())||!launch.canonicalSha256().equals(canonical)||session.expiresAtMillis()>launch.expiresAt())throw new SecurityException("DELIVERY_SESSION_CONTEXT");ids(session.binding());
    }
}
