package dev.mineagent.runtime.core.task;
import org.junit.jupiter.api.Test;import java.util.*;import static org.junit.jupiter.api.Assertions.*;
class NavigationSearchTest {
    @Test void multiTargetReachabilityNeverCachesSliceExhaustionAsNoPath(){var a=new SurfacePathfinder.Node(0,0,0);var b=new SurfacePathfinder.Node(1,0,0);var c=new SurfacePathfinder.Node(2,0,0);var reach=new SurfaceReachability(a,n->n.equals(a)?List.of(new SurfacePathfinder.PathStep(a,b,SurfacePathfinder.Action.WALK,SurfacePathfinder.Posture.STANDING,1)):n.equals(b)?List.of(new SurfacePathfinder.PathStep(b,c,SurfacePathfinder.Action.WALK,SurfacePathfinder.Posture.STANDING,1)):List.of());reach.advance(1,()->true);assertEquals(SurfaceReachability.Reachability.REACHABLE,reach.state(b));assertEquals(SurfaceReachability.Reachability.UNKNOWN,reach.state(c));reach.advance(1,()->true);assertEquals(SurfaceReachability.Reachability.REACHABLE,reach.state(c));}
    @Test void budgetCanResumeRatherThanClaimUnreachable(){var start=new SurfacePathfinder.Node(0,0,0);var goal=new SurfacePathfinder.Node(7,0,0);var search=new SurfacePathfinder.Search(start,goal,n->n.x()<7?List.of(new SurfacePathfinder.PathStep(n,new SurfacePathfinder.Node(n.x()+1,0,0),SurfacePathfinder.Action.WALK,SurfacePathfinder.Posture.STANDING,1)):List.of());assertEquals(SurfacePathfinder.Status.BUDGET_EXHAUSTED,search.advance(2).status());assertEquals(SurfacePathfinder.Status.BUDGET_EXHAUSTED,search.advance(2).status());var result=search.advance(20);assertEquals(SurfacePathfinder.Status.FOUND,result.status());assertEquals(7,result.steps().size());assertEquals(goal,result.steps().getLast().to());}
    @Test void unloadedAndNoPathAreDistinct(){var n=new SurfacePathfinder.Node(0,0,0);var goal=new SurfacePathfinder.Node(1,0,0);assertEquals(SurfacePathfinder.Status.NO_PATH,new SurfacePathfinder.Search(n,goal,a->List.of()).advance(5).status());assertEquals(SurfacePathfinder.Status.WAITING_CHUNKS,new SurfacePathfinder.Search(n,goal,new SurfacePathfinder.TraversalEvaluator(){public List<SurfacePathfinder.PathStep> neighbors(SurfacePathfinder.Node a){return List.of();}public boolean encounteredUnloaded(){return true;}}).advance(5).status());}
    @Test void ladderEdgesCanBeVertical(){var a=new SurfacePathfinder.Node(0,0,0);var b=new SurfacePathfinder.Node(0,16,0);var result=new SurfacePathfinder.Search(a,b,n->List.of(new SurfacePathfinder.PathStep(a,b,SurfacePathfinder.Action.CLIMB,SurfacePathfinder.Posture.STANDING,1))).advance(3);assertEquals(SurfacePathfinder.Status.FOUND,result.status());assertEquals(SurfacePathfinder.Action.CLIMB,result.steps().getFirst().action());}
    @Test void emptyRouteDoesNotBypassBackoff(){var retry=new NavigationRetry();retry.reset(10);assertTrue(retry.ready(10));retry.failed(10);for(int t=11;t<30;t++)assertFalse(retry.ready(t));assertTrue(retry.ready(30));retry.failed(30);assertEquals(70,retry.next());}
}
