package dev.mineagent.runtime.neoforge.content;

import dev.mineagent.runtime.core.creature.*;
import dev.mineagent.runtime.core.objects.RuntimeMesh;
import net.minecraft.network.chat.Component;
import net.minecraft.network.syncher.*;
import net.minecraft.server.level.*;
import net.minecraft.world.*;
import net.minecraft.world.entity.*;
import net.minecraft.world.entity.ai.attributes.*;
import net.minecraft.world.entity.ai.goal.*;
import net.minecraft.world.entity.animal.Animal;
import net.minecraft.world.entity.player.Player;
import net.minecraft.world.entity.item.ItemEntity;
import net.minecraft.world.item.*;
import net.minecraft.world.item.trading.*;
import net.minecraft.world.level.Level;
import net.minecraft.world.level.storage.*;
import net.minecraft.world.phys.Vec3;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.Identifier;
import java.util.*;

/** Native living carrier with data-defined geometry and independent server-authoritative behaviours. */
public final class RuntimeCreatureEntity extends Animal implements Merchant {
    private static final EntityDataAccessor<String> SOURCE=SynchedEntityData.defineId(RuntimeCreatureEntity.class,EntityDataSerializers.STRING);
    private static final EntityDataAccessor<String> OWNER=SynchedEntityData.defineId(RuntimeCreatureEntity.class,EntityDataSerializers.STRING);
    private CreatureDefinition definition;private String parsed="";private UUID species;private long revision;
    private int navigationAttemptTick;private boolean lastNavigationAccepted;private String command="stay";private List<Vec3> patrol=List.of();private int point;
    private final Map<UUID,Long> proximityLast=new HashMap<>();private final Set<UUID> nearby=new HashSet<>();
    public int interactionAnimationTicks;
    @Override public void handleEntityEvent(byte id){if(id==67){interactionAnimationTicks=20;return;}super.handleEntityEvent(id);}
    private Player trader;private MerchantOffers offers=new MerchantOffers();
    private long tradesDone,bartersDone,proximityEvents,attacksDone,childrenBorn,effectsDone,giftsDone,soundsDone;private UUID fuseActor;private int fuseRemaining;private CreatureDefinition.ProximityAction fuseAction;private String lastError="";
    public RuntimeCreatureEntity(EntityType<? extends Animal> type,Level level){super(type,level);setPersistenceRequired();}
    public static AttributeSupplier.Builder createAttributes(){return Animal.createAnimalAttributes().add(Attributes.MAX_HEALTH,20).add(Attributes.MOVEMENT_SPEED,.25).add(Attributes.ATTACK_DAMAGE,3).add(Attributes.FOLLOW_RANGE,24);}
    @Override protected void defineSynchedData(SynchedEntityData.Builder b){super.defineSynchedData(b);b.define(SOURCE,"");b.define(OWNER,"");}
    @Override protected void registerGoals(){goalSelector.addGoal(0,new FloatGoal(this));goalSelector.addGoal(1,new MeleeAttackGoal(this,1.2,true));goalSelector.addGoal(2,new BreedGoal(this,1));goalSelector.addGoal(6,new LookAtPlayerGoal(this,Player.class,8));}
    public CreatureDefinition definition(){String source=entityData.get(SOURCE);if(source.isEmpty())return null;if(!source.equals(parsed)){definition=CreatureDefinition.parse(source);parsed=source;}return definition;}
    public UUID owner(){try{return UUID.fromString(entityData.get(OWNER));}catch(IllegalArgumentException e){return null;}}
    public UUID species(){return species;}public long revision(){return revision;}
    public void bind(CreatureStore.Species value,boolean fresh){var d=value.definition();cancelFuse();species=value.id();revision=value.revision();entityData.set(OWNER,value.owner().toString());entityData.set(SOURCE,value.source());getAttribute(Attributes.MAX_HEALTH).setBaseValue(d.health());getAttribute(Attributes.MOVEMENT_SPEED).setBaseValue(d.speed());getAttribute(Attributes.ATTACK_DAMAGE).setBaseValue(d.damage());setHealth(fresh?(float)d.health():Math.min(getHealth(),(float)d.health()));setCustomName(Component.literal(d.name()));setCustomNameVisible(true);refreshDimensions();if(trader!=null)trader.closeContainer();offers=new MerchantOffers();for(var t:d.trades())offers.add(new MerchantOffer(new ItemCost(item(t.input()),t.inputCount()),new ItemStack(item(t.output()),t.outputCount()),Integer.MAX_VALUE,0,0));lastError="";}
    public static Item item(String id){var key=Identifier.parse(id);if(!BuiltInRegistries.ITEM.containsKey(key)||BuiltInRegistries.ITEM.getValue(key)==Items.AIR)throw new IllegalArgumentException("CREATURE_UNKNOWN_ITEM:"+id);return BuiltInRegistries.ITEM.getValue(key);}
    @Override public EntityDimensions getDefaultDimensions(Pose pose){var d=definition();if(d==null)return super.getDefaultDimensions(pose);var c=RuntimeMesh.parse(d.model()).collision();return EntityDimensions.scalable((float)Math.max(c.width(),c.depth()),(float)c.height()).scale(isBaby()?.5F:1);}
    @Override public void onSyncedDataUpdated(EntityDataAccessor<?> a){super.onSyncedDataUpdated(a);if(a.equals(SOURCE))refreshDimensions();}
    @Override public boolean isFood(ItemStack stack){var d=definition();return d!=null&&!d.food().isEmpty()&&stack.is(item(d.food()));}
    @Override public boolean canMate(Animal other){return other instanceof RuntimeCreatureEntity e&&Objects.equals(species,e.species)&&Objects.equals(owner(),e.owner())&&super.canMate(other);}
    @Override public RuntimeCreatureEntity getBreedOffspring(ServerLevel level,AgeableMob partner){if(!(partner instanceof RuntimeCreatureEntity e)||!Objects.equals(species,e.species)||!Objects.equals(owner(),e.owner()))return null;var child=new RuntimeCreatureEntity(dev.mineagent.runtime.neoforge.MineAgentRegistries.RUNTIME_CREATURE.get(),level);child.bind(new CreatureStore.Species(species,owner(),revision,entityData.get(SOURCE)),true);return child;}
    @Override public void finalizeSpawnChildFromBreeding(ServerLevel level,Animal other,AgeableMob child){super.finalizeSpawnChildFromBreeding(level,other,child);if(child!=null)childrenBorn++;}
    @Override public InteractionResult mobInteract(Player player,InteractionHand hand){if(!level().isClientSide())level().broadcastEntityEvent(this,(byte)67);var d=definition();if(d==null)return InteractionResult.PASS;if(isFood(player.getItemInHand(hand)))return super.mobInteract(player,hand);
        if(d.rideable()&&!isBaby()&&owner()!=null&&owner().equals(player.getUUID())&&!player.isSecondaryUseActive()&&player.getItemInHand(hand).isEmpty()&&!isVehicle()){if(!level().isClientSide()){getNavigation().stop();setTarget(null);player.startRiding(this);}return InteractionResult.SUCCESS;}
        if(!d.trades().isEmpty()&&!isBaby()&&!isVehicle()&&(trader==null||trader==player)){if(!level().isClientSide()){getNavigation().stop();setTradingPlayer(player);openTradingScreen(player,getDisplayName(),1);}return InteractionResult.SUCCESS;}
        return super.mobInteract(player,hand);
    }
    @Override public LivingEntity getControllingPassenger(){return definition()!=null&&definition().rideable()&&getFirstPassenger() instanceof Player p&&Objects.equals(owner(),p.getUUID())?p:null;}
    @Override protected void tickRidden(Player controller,Vec3 input){super.tickRidden(controller,input);setRot(controller.getYRot(),controller.getXRot()*.5F);yRotO=yBodyRot=yHeadRot=getYRot();}
    @Override protected Vec3 getRiddenInput(Player p,Vec3 input){return new Vec3(p.xxa*.5,0,p.zza<0?p.zza*.25:p.zza);}
    @Override protected float getRiddenSpeed(Player p){return (float)getAttributeValue(Attributes.MOVEMENT_SPEED);}
    public void command(String action,List<Vec3> points,LivingEntity target){if(definition()==null||!definition().companion())throw new IllegalArgumentException("CREATURE_NOT_COMPANION");if(!Set.of("follow","stay","attack","patrol").contains(action))throw new IllegalArgumentException("CREATURE_COMMAND");if(action.equals("attack")&&(target==null||!target.isAlive()||target==this||Objects.equals(target.getUUID(),owner())||distanceToSqr(target)>4096))throw new IllegalArgumentException("CREATURE_ATTACK_TARGET");if(action.equals("patrol")&&(points.size()<2||points.size()>16))throw new IllegalArgumentException("CREATURE_PATROL_POINTS");command=action;patrol=List.copyOf(points);point=0;getNavigation().stop();setTarget(action.equals("attack")?target:null);}
    @Override public void tick(){super.tick();if(interactionAnimationTicks>0)interactionAnimationTicks--;if(!(level() instanceof ServerLevel level)||definition()==null||species==null)return;
        if(tickCount%40==0)try{var latest=RuntimeCreatures.get(level.getServer()).get(owner(),species).orElse(null);if(latest==null){getNavigation().stop();setTarget(null);lastError="CREATURE_DEFINITION_MISSING";return;}if(latest.revision()!=revision)bind(latest,false);}catch(Exception e){lastError="CREATURE_STORE_UNAVAILABLE";getNavigation().stop();setTarget(null);return;}
        if(!lastError.isEmpty()){cancelFuse();return;}var d=definition();try{if(!tickFuse(level))return;}catch(RuntimeException failure){lastError="CREATURE_EXPLOSION_OUTCOME_UNKNOWN";cancelFuse();return;}if(isVehicle()||trader!=null){cancelFuse();getNavigation().stop();setTarget(null);return;}
        if(tickCount%10!=0)return;if(getTarget()!=null&&(!getTarget().isAlive()||distanceToSqr(getTarget())>4096))setTarget(null);
        if(getTarget()==null&&!d.disposition().equals("friendly")){var attacker=getLastHurtByMob();if(attacker!=null&&attacker.isAlive()&&!Objects.equals(attacker.getUUID(),owner())&&distanceToSqr(attacker)<576)setTarget(attacker);else if(d.disposition().equals("hostile")){var target=level.getEntitiesOfClass(ServerPlayer.class,getBoundingBox().inflate(16),v->!v.isCreative()&&!v.isSpectator()).stream().min(Comparator.comparingDouble(this::distanceToSqr)).orElse(null);if(target!=null)setTarget(target);}}
        if(getTarget()==null&&!isInLove()&&d.companion()){var p=owner()==null?null:level.getPlayerByUUID(owner());if(command.equals("follow")&&p!=null&&distanceToSqr(p)>6.25)getNavigation().moveTo(p,1.1);else if(command.equals("follow"))getNavigation().stop();else if(command.equals("patrol")&&!patrol.isEmpty()){var v=patrol.get(point);if(distanceToSqr(v)<2){point=(point+1)%patrol.size();v=patrol.get(point);}if(level.hasChunkAt(net.minecraft.core.BlockPos.containing(v))){navigationAttemptTick=tickCount;lastNavigationAccepted=getNavigation().moveTo(v.x,v.y,v.z,1);}}}
        if(d.barter()!=null&&tickCount%20==0){var t=d.barter();for(var dropped:level.getEntitiesOfClass(ItemEntity.class,getBoundingBox().inflate(2),x->x.isAlive()&&x.getItem().is(item(t.input()))&&x.getItem().getCount()>=t.inputCount()&&!x.entityTags().contains("mineagent.creature.output"))){var output=new ItemEntity(level,getX(),getY()+.5,getZ(),new ItemStack(item(t.output()),t.outputCount()));output.addTag("mineagent.creature.output");output.setDefaultPickUpDelay();if(level.addFreshEntity(output)){dropped.getItem().shrink(t.inputCount());if(dropped.getItem().isEmpty())dropped.discard();bartersDone++;}break;}}
        if(d.proximityRadius()>0){var now=level.getGameTime();var inside=new HashSet<UUID>();for(var p:level.getEntitiesOfClass(ServerPlayer.class,getBoundingBox().inflate(d.proximityRadius()),x->!x.isSpectator()&&x.isAlive()&&distanceToSqr(x)<=d.proximityRadius()*d.proximityRadius())){inside.add(p.getUUID());if(!nearby.contains(p.getUUID())&&now-proximityLast.getOrDefault(p.getUUID(),Long.MIN_VALUE/2)>=d.proximityCooldown()){if(!d.proximityMessage().isBlank())p.sendSystemMessage(Component.literal("["+d.name()+"] "+d.proximityMessage()));try{applyProximity(level,p,d);}catch(RuntimeException failure){lastError="CREATURE_EVENT_FAILED:"+failure.getClass().getSimpleName();cancelFuse();}proximityLast.put(p.getUUID(),now);proximityEvents++;if(!lastError.isEmpty())break;}}nearby.clear();nearby.addAll(inside);proximityLast.entrySet().removeIf(e->now-e.getValue()>d.proximityCooldown()&&!inside.contains(e.getKey()));}
    }
    private void applyProximity(ServerLevel level,ServerPlayer player,CreatureDefinition d){
        for(var a:d.proximityActions())switch(a.type()){
            case "message"->player.sendSystemMessage(Component.literal("["+d.name()+"] "+a.text()));
            case "effect"->{var effect=BuiltInRegistries.MOB_EFFECT.wrapAsHolder(BuiltInRegistries.MOB_EFFECT.getValue(Identifier.parse(a.id())));if(player.addEffect(new net.minecraft.world.effect.MobEffectInstance(effect,a.durationTicks(),a.level()-1),this))effectsDone++;}
            case "give_item"->{var stack=new ItemStack(item(a.id()),a.count());player.getInventory().add(stack);if(!stack.isEmpty())player.drop(stack,false);player.inventoryMenu.broadcastChanges();giftsDone++;}
            case "sound"->{level.playSound(null,getX(),getY(),getZ(),BuiltInRegistries.SOUND_EVENT.getValue(Identifier.parse(a.id())),net.minecraft.sounds.SoundSource.NEUTRAL,(float)a.volume(),(float)a.pitch());soundsDone++;}
            case "explosion"->{if(fuseActor==null){fuseActor=player.getUUID();fuseAction=a;fuseRemaining=a.fuseTicks();level.playSound(null,getX(),getY(),getZ(),net.minecraft.sounds.SoundEvents.CREEPER_PRIMED,net.minecraft.sounds.SoundSource.HOSTILE,1,1);}}
            default->throw new IllegalStateException("CREATURE_ACTION_TYPE");
        }
    }
    private void cancelFuse(){fuseActor=null;fuseAction=null;fuseRemaining=0;}
    private boolean tickFuse(ServerLevel level){
        if(fuseActor==null)return true;var player=level.getPlayerByUUID(fuseActor);var d=definition();
        if(!isAlive()||isVehicle()||trader!=null||player==null||!player.isAlive()||player.isSpectator()||distanceToSqr(player)>d.proximityRadius()*d.proximityRadius()){cancelFuse();return true;}
        if(--fuseRemaining>0)return true;var action=fuseAction;cancelFuse();
        level.explode(this,getX(),getY(),getZ(),(float)action.power(),false,action.breakBlocks()?Level.ExplosionInteraction.MOB:Level.ExplosionInteraction.NONE);discard();return false;
    }
    @Override public boolean doHurtTarget(ServerLevel level,Entity target){if(Objects.equals(target.getUUID(),owner())&&definition()!=null&&!definition().disposition().equals("hostile"))return false;boolean hit=super.doHurtTarget(level,target);if(hit)attacksDone++;return hit;}
    public Map<String,Object> observation(){var r=new LinkedHashMap<String,Object>();r.put("entity_id",getUUID());r.put("species_id",species==null?"":species);r.put("revision",revision);r.put("name",getName().getString());r.put("health",getHealth());r.put("position",List.of(getX(),getY(),getZ()));r.put("command",command);r.put("target",getTarget()==null?"":getTarget().getUUID());r.put("navigationDone",getNavigation().isDone());r.put("navigationAccepted",lastNavigationAccepted);r.put("navigationAttemptTick",navigationAttemptTick);r.put("tick",tickCount);r.put("trader",trader==null?"":trader.getUUID());r.put("patrolPoints",patrol.stream().map(v->List.of(v.x,v.y,v.z)).toList());r.put("patrolIndex",point);r.put("inLove",isInLove());r.put("onGround",onGround());r.put("rider",getFirstPassenger()==null?"":getFirstPassenger().getUUID());r.put("baby",isBaby());r.put("fuseTicks",fuseRemaining);r.put("fuseActor",fuseActor==null?"":fuseActor);r.put("events",Map.of("trade",tradesDone,"barter",bartersDone,"proximity",proximityEvents,"attack",attacksDone,"breeding",childrenBorn,"effect",effectsDone,"give_item",giftsDone,"sound",soundsDone));r.put("error",lastError);return r;}
    @Override protected void addAdditionalSaveData(ValueOutput o){super.addAdditionalSaveData(o);o.putString("CreatureSource",entityData.get(SOURCE));o.putString("CreatureOwner",entityData.get(OWNER));o.putString("CreatureSpecies",species==null?"":species.toString());o.putLong("CreatureRevision",revision);o.putString("CreatureCommand",command);o.putString("CreaturePatrol",patrol.stream().map(v->v.x+","+v.y+","+v.z).collect(java.util.stream.Collectors.joining(";")));o.putLong("CreatureTrades",tradesDone);o.putLong("CreatureBarters",bartersDone);o.putLong("CreatureProximity",proximityEvents);o.putLong("CreatureAttacks",attacksDone);o.putLong("CreatureChildren",childrenBorn);o.putLong("CreatureEffects",effectsDone);o.putLong("CreatureGifts",giftsDone);o.putLong("CreatureSounds",soundsDone);o.store("CreatureOffers",MerchantOffers.CODEC,offers);}
    @Override protected void readAdditionalSaveData(ValueInput i){super.readAdditionalSaveData(i);String source=i.getStringOr("CreatureSource","");if(source.isEmpty())return;try{bind(new CreatureStore.Species(UUID.fromString(i.getStringOr("CreatureSpecies","")),UUID.fromString(i.getStringOr("CreatureOwner","")),i.getLongOr("CreatureRevision",1),source),false);command=i.getStringOr("CreatureCommand","stay");if(!Set.of("follow","stay","patrol").contains(command))command="stay";String points=i.getStringOr("CreaturePatrol","");var list=new ArrayList<Vec3>();if(!points.isEmpty())for(String v:points.split(";")){var c=v.split(",");if(c.length!=3||list.size()>=16)throw new IllegalArgumentException();var point=new Vec3(Double.parseDouble(c[0]),Double.parseDouble(c[1]),Double.parseDouble(c[2]));if(!Double.isFinite(point.lengthSqr()))throw new IllegalArgumentException();list.add(point);}patrol=List.copyOf(list);tradesDone=i.getLongOr("CreatureTrades",0);bartersDone=i.getLongOr("CreatureBarters",0);proximityEvents=i.getLongOr("CreatureProximity",0);attacksDone=i.getLongOr("CreatureAttacks",0);childrenBorn=i.getLongOr("CreatureChildren",0);effectsDone=i.getLongOr("CreatureEffects",0);giftsDone=i.getLongOr("CreatureGifts",0);soundsDone=i.getLongOr("CreatureSounds",0);offers=i.read("CreatureOffers",MerchantOffers.CODEC).orElse(offers);}catch(Exception e){lastError="CREATURE_SAVED_DATA_INVALID";entityData.set(SOURCE,"");}}
    @Override public void setTradingPlayer(Player p){trader=p;}@Override public Player getTradingPlayer(){return trader;}@Override public MerchantOffers getOffers(){return offers;}@Override public void overrideOffers(MerchantOffers v){offers=v;}@Override public void notifyTrade(MerchantOffer o){o.increaseUses();tradesDone++;}@Override public void notifyTradeUpdated(ItemStack s){}@Override public int getVillagerXp(){return 0;}@Override public void overrideXp(int xp){}@Override public boolean showProgressBar(){return false;}@Override public net.minecraft.sounds.SoundEvent getNotifyTradeSound(){return net.minecraft.sounds.SoundEvents.VILLAGER_YES;}@Override public boolean isClientSide(){return level().isClientSide();}@Override public boolean stillValid(Player p){return isAlive()&&p==trader&&distanceToSqr(p)<=64;}
}
