package dev.mineagent.runtime.neoforge.content;
import com.fasterxml.jackson.databind.JsonNode;
import dev.mineagent.runtime.core.creature.*;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;
import net.minecraft.server.MinecraftServer;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.server.permissions.Permissions;
import net.minecraft.world.entity.LivingEntity;
import net.minecraft.world.phys.Vec3;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import java.util.*;

@EventBusSubscriber(modid="mineagent_runtime")
public final class RuntimeCreatures implements AutoCloseable {
    private static final Map<MinecraftServer,RuntimeCreatures> ACTIVE=new IdentityHashMap<>();
    private final CreatureStore store;private final Map<UUID,CreatureStore.Species> cache=new HashMap<>();
    private RuntimeCreatures(MinecraftServer s)throws Exception{store=new CreatureStore(s.getServerDirectory().resolve("mineagent-runtime-data/runtime.db"),MineAgentRuntimeServices.worldId(s));}
    public static RuntimeCreatures get(MinecraftServer s){if(!s.isSameThread())throw new IllegalStateException("CREATURE_SERVER_THREAD");return ACTIVE.computeIfAbsent(s,k->{try{return new RuntimeCreatures(k);}catch(Exception e){throw new IllegalStateException("CREATURE_STORE",e);}});}
    public Optional<CreatureStore.Species> get(UUID owner,UUID id)throws Exception{if(owner==null||id==null)return Optional.empty();var hit=cache.get(id);if(hit!=null)return hit.owner().equals(owner)?Optional.of(hit):Optional.empty();var value=store.get(owner,id);value.ifPresent(v->cache.put(id,v));return value;}
    public static Map<String,Object> inspect(ServerPlayer p,JsonNode a)throws Exception{keys(a,"offset","entity_offset");int offset=integer(a,"offset",0),entityOffset=integer(a,"entity_offset",0);var runtime=get(p.level().getServer());var species=runtime.store.list(p.getUUID(),offset);species.forEach(v->runtime.cache.put(v.id(),v));var entities=p.level().getAllEntities();var list=new ArrayList<RuntimeCreatureEntity>();for(var entity:entities)if(entity instanceof RuntimeCreatureEntity e&&p.getUUID().equals(e.owner()))list.add(e);list.sort(Comparator.comparing(e->e.getUUID().toString()));var result=new LinkedHashMap<String,Object>();result.put("contract",CreatureDefinition.CONTRACT);result.put("species",species);result.put("nextOffset",species.size()==16?offset+16:-1);result.put("entities",list.stream().skip(entityOffset).limit(32).map(RuntimeCreatureEntity::observation).toList());result.put("nextEntityOffset",entityOffset+32<list.size()?entityOffset+32:-1);result.put("entityScope","CURRENT_DIMENSION_LOADED_ONLY");return result;}
    public static Map<String,Object> define(ServerPlayer p,UUID operation,JsonNode a)throws Exception{authority(p);keys(a,"source","species_id","expected_revision");if(!a.path("source").isTextual())throw new IllegalArgumentException("CREATURE_SOURCE");var d=CreatureDefinition.parse(a.path("source").textValue());if(!d.food().isEmpty())RuntimeCreatureEntity.item(d.food());for(var t:d.trades())validate(t);if(d.barter()!=null)validate(d.barter());for(var action:d.proximityActions()){
        var key=action.id().isEmpty()?null:net.minecraft.resources.Identifier.parse(action.id());
        if(action.type().equals("effect")&&!net.minecraft.core.registries.BuiltInRegistries.MOB_EFFECT.containsKey(key))throw new IllegalArgumentException("CREATURE_EFFECT_UNKNOWN");
        if(action.type().equals("sound")&&!net.minecraft.core.registries.BuiltInRegistries.SOUND_EVENT.containsKey(key))throw new IllegalArgumentException("CREATURE_SOUND_UNKNOWN");
        if(action.type().equals("give_item")&&action.count()>RuntimeCreatureEntity.item(action.id()).getDefaultMaxStackSize())throw new IllegalArgumentException("CREATURE_ITEM_STACK_SIZE");
    }UUID id=a.has("species_id")?UUID.fromString(a.path("species_id").asText()):operation;long expected=0;if(a.has("species_id")){if(!a.path("expected_revision").isIntegralNumber()||!a.path("expected_revision").canConvertToLong()||a.path("expected_revision").longValue()<1)throw new IllegalArgumentException("CREATURE_EXPECTED_REVISION");expected=a.path("expected_revision").longValue();}else if(a.has("expected_revision")&&a.path("expected_revision").asLong(-1)!=0)throw new IllegalArgumentException("CREATURE_NEW_REVISION");var runtime=get(p.level().getServer());var result=runtime.store.put(p.getUUID(),id,expected,d.source());runtime.cache.put(id,result);int updated=0;for(var level:p.level().getServer().getAllLevels())for(var entity:level.getAllEntities())if(entity instanceof RuntimeCreatureEntity e&&id.equals(e.species())&&p.getUUID().equals(e.owner())){e.bind(result,false);updated++;}return Map.of("status","APPLIED","species",result,"updatedLoaded",updated,"spawned",false);}
    private static void validate(CreatureDefinition.Trade t){if(t.inputCount()>RuntimeCreatureEntity.item(t.input()).getDefaultMaxStackSize()||t.outputCount()>RuntimeCreatureEntity.item(t.output()).getDefaultMaxStackSize())throw new IllegalArgumentException("CREATURE_ITEM_STACK_SIZE");}
    public static Map<String,Object> control(ServerPlayer p,JsonNode a)throws Exception{authority(p);keys(a,"action","species_id","entity_id","position","points","target_id");String action=a.path("action").asText();if(action.equals("spawn")){var s=get(p.level().getServer()).get(p.getUUID(),UUID.fromString(a.path("species_id").asText())).orElseThrow(()->new IllegalArgumentException("CREATURE_SPECIES_NOT_OWNED"));Vec3 v=a.has("position")?position(p,a.get("position")):p.position().add(p.getLookAngle().multiply(2,0,2));position(p,new com.fasterxml.jackson.databind.ObjectMapper().valueToTree(List.of(v.x,v.y,v.z)));var e=new RuntimeCreatureEntity(dev.mineagent.runtime.neoforge.MineAgentRegistries.RUNTIME_CREATURE.get(),p.level());e.bind(s,true);e.setPos(v);if(!p.level().noCollision(e)||!p.level().addFreshEntity(e))throw new IllegalStateException("CREATURE_SPAWN_BLOCKED");return Map.of("status","APPLIED","entity",e.observation());}
        var entity=p.level().getEntity(UUID.fromString(a.path("entity_id").asText()));if(!(entity instanceof RuntimeCreatureEntity e)||!p.getUUID().equals(e.owner()))throw new SecurityException("CREATURE_ENTITY_NOT_OWNED_OR_UNLOADED");if(action.equals("remove")){e.discard();return Map.of("status","APPLIED","removed",e.getUUID());}var points=new ArrayList<Vec3>();if(a.has("points")){if(!a.get("points").isArray()||a.get("points").size()>16)throw new IllegalArgumentException("CREATURE_POINTS");for(var v:a.get("points"))points.add(position(p,v));}LivingEntity target=null;if(a.has("target_id")){var t=p.level().getEntity(UUID.fromString(a.path("target_id").asText()));if(t instanceof LivingEntity l)target=l;}e.command(action,points,target);return Map.of("status","STARTED","entity",e.observation(),"completion","OBSERVE_SUBSEQUENT_NATIVE_TICKS");}
    private static Vec3 position(ServerPlayer p,JsonNode n){if(!n.isArray()||n.size()!=3)throw new IllegalArgumentException("CREATURE_POSITION");for(var v:n)if(!v.isNumber()||!Double.isFinite(v.doubleValue()))throw new IllegalArgumentException("CREATURE_POSITION");var pos=new Vec3(n.get(0).doubleValue(),n.get(1).doubleValue(),n.get(2).doubleValue());var block=net.minecraft.core.BlockPos.containing(pos);if(p.distanceToSqr(pos)>4096||!p.level().hasChunkAt(block)||!p.level().getWorldBorder().isWithinBounds(block)||block.getY()<p.level().getMinY()||block.getY()>p.level().getMaxY())throw new IllegalArgumentException("CREATURE_POSITION_NOT_LOCAL_LOADED");return pos;}
    private static void authority(ServerPlayer p){if(!p.permissions().hasPermission(Permissions.COMMANDS_GAMEMASTER))throw new SecurityException("CREATURE_GAMEMASTER_REQUIRED");}
    private static int integer(JsonNode a,String k,int fallback){if(!a.has(k))return fallback;if(!a.get(k).isIntegralNumber()||!a.get(k).canConvertToInt()||a.get(k).intValue()<0)throw new IllegalArgumentException("CREATURE_OFFSET");return a.get(k).intValue();}
    private static void keys(JsonNode n,String...allowed){var set=Set.of(allowed);n.fieldNames().forEachRemaining(k->{if(!set.contains(k))throw new IllegalArgumentException("CREATURE_ARGUMENT:"+k);});}
    @SubscribeEvent public static void stop(net.neoforged.neoforge.event.server.ServerStoppedEvent e)throws Exception{var r=ACTIVE.remove(e.getServer());if(r!=null)r.close();}
    @Override public void close()throws Exception{store.close();cache.clear();}
}
