package dev.mineagent.runtime.core.building;
import dev.mineagent.runtime.core.files.*;
import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.net.*;import java.net.http.*;import java.util.*;import java.io.*;import java.util.zip.*;import com.fasterxml.jackson.databind.*;import static org.junit.jupiter.api.Assertions.*;
class BuildingTransferTest {
 @TempDir Path root;private static final ObjectMapper JSON=new ObjectMapper();private final HttpClient http=HttpClient.newHttpClient();
 @Test void actualHttpUploadDownloadRequiresSessionAndExactOffsets()throws Exception{var store=new FileLibrary(root);UUID owner=UUID.randomUUID();try(var server=new LocalFileTransferServer(store,0)){String base="http://127.0.0.1:"+server.port(),token=server.session(owner,"").get("token").toString();var denied=http.send(HttpRequest.newBuilder(URI.create(base+"/list")).POST(HttpRequest.BodyPublishers.ofString("{}")).build(),HttpResponse.BodyHandlers.ofString());assertEquals(401,denied.statusCode());String upload=post(base,token,"/begin",Map.of("name","房子.litematic","kind","FILE")).path("upload").asText();String part=post(base,token,"/file",Map.of("upload",upload,"path","房子.litematic","bytes",3)).path("part").asText();var req=HttpRequest.newBuilder(URI.create(base+"/chunk/"+upload+"/"+part+"/0")).header("Authorization","Bearer "+token).PUT(HttpRequest.BodyPublishers.ofByteArray(new byte[]{1,2,3})).build();assertEquals(200,http.send(req,HttpResponse.BodyHandlers.ofString()).statusCode());assertEquals(400,http.send(req,HttpResponse.BodyHandlers.ofString()).statusCode());var asset=post(base,token,"/finish",Map.of("upload",upload));String id=asset.path("id").asText();var download=http.send(HttpRequest.newBuilder(URI.create(base+"/download/"+id)).header("Authorization","Bearer "+token).GET().build(),HttpResponse.BodyHandlers.ofByteArray());assertArrayEquals(new byte[]{1,2,3},download.body());String other=server.session(UUID.randomUUID(),"").get("token").toString();assertEquals(400,http.send(HttpRequest.newBuilder(URI.create(base+"/download/"+id)).header("Authorization","Bearer "+other).GET().build(),HttpResponse.BodyHandlers.ofString()).statusCode());assertThrows(IllegalArgumentException.class,()->store.file(UUID.randomUUID(),UUID.fromString(id),""));}}
 private JsonNode post(String base,String token,String path,Object obj)throws Exception{var response=http.send(HttpRequest.newBuilder(URI.create(base+path)).header("Authorization","Bearer "+token).POST(HttpRequest.BodyPublishers.ofString(JSON.writeValueAsString(obj))).build(),HttpResponse.BodyHandlers.ofString());assertEquals(200,response.statusCode(),response.body());return JSON.readTree(response.body());}
 @Test void archiveTraversalRejectedAndArbitraryFilesRemainInertData()throws Exception{var store=new FileLibrary(root.resolve("store"));UUID owner=UUID.randomUUID();Path zip=root.resolve("bad.zip");try(var z=new ZipOutputStream(Files.newOutputStream(zip))){z.putNextEntry(new ZipEntry("../escape.nbt"));z.write(new byte[]{1});z.closeEntry();}var bad=store.importFile(owner,zip,"LOCAL_TEST");assertThrows(IllegalArgumentException.class,()->store.expand(owner,bad.id()));assertFalse(Files.exists(root.resolve("escape.nbt")));Path good=root.resolve("good.zip");try(var z=new ZipOutputStream(Files.newOutputStream(good))){z.putNextEntry(new ZipEntry("startup.exe"));z.write(new byte[]{1});z.closeEntry();z.putNextEntry(new ZipEntry("sample.nbt"));z.write(new byte[]{2});z.closeEntry();}var a=store.importFile(owner,good,"LOCAL_TEST");Path expanded=store.expand(owner,a.id());assertArrayEquals(new byte[]{1},Files.readAllBytes(expanded.resolve("startup.exe")));assertArrayEquals(new byte[]{2},Files.readAllBytes(expanded.resolve("sample.nbt")));}
 @Test void genericEmptyFolderAndEmptyFilesRoundTrip()throws Exception{var store=new FileLibrary(root);UUID owner=UUID.randomUUID(),u=store.begin(owner,"project","FOLDER");store.directory(owner,u,"empty/sub");store.beginFile(owner,u,"readme.txt",0);var a=store.finish(owner,u,"LOCAL_TEST");var bytes=new ByteArrayOutputStream();store.archive(owner,a.id(),bytes);var names=new HashSet<String>();try(var zip=new ZipInputStream(new ByteArrayInputStream(bytes.toByteArray()))){for(var e=zip.getNextEntry();e!=null;e=zip.getNextEntry())names.add(e.getName());}assertTrue(names.contains("empty/sub/"));assertTrue(names.contains("readme.txt"));}
 @Test void incompleteUploadsNeverPublishAndCancelDeletesOnlyOwnTemp()throws Exception{var store=new FileLibrary(root);UUID owner=UUID.randomUUID(),up=store.begin(owner,"tiny.nbt","FILE");store.beginFile(owner,up,"tiny.nbt",10);assertThrows(IllegalArgumentException.class,()->store.finish(owner,up,"LOCAL_TEST"));assertEquals(0,store.list(owner,"",0).get("total"));store.cancel(owner,up);assertThrows(IllegalArgumentException.class,()->store.beginFile(owner,UUID.randomUUID(),"../x.nbt",1));}
}
