package dev.mineagent.runtime.core.building;
import org.junit.jupiter.api.Test;import org.junit.jupiter.api.io.TempDir;import java.nio.file.*;import java.io.*;import java.util.*;import java.util.zip.*;import static org.junit.jupiter.api.Assertions.*;
class BuildingFormatsTest {
 @TempDir Path root;
 static Map<String,Object> state(String name){return Map.of("Name",name);}
 static byte[] nbt(Map<String,Object> tag)throws Exception{var bytes=new ByteArrayOutputStream();var d=new DataOutputStream(bytes);d.writeByte(10);d.writeUTF("");write(d,tag);return bytes.toByteArray();}
 static int type(Object o){return o instanceof Byte?1:o instanceof Short?2:o instanceof Integer?3:o instanceof Long?4:o instanceof byte[]?7:o instanceof String?8:o instanceof List?9:o instanceof Map?10:o instanceof int[]?11:o instanceof long[]?12:0;}
 static void write(DataOutputStream d,Object o)throws Exception{switch(type(o)){case 1->d.writeByte((byte)o);case 2->d.writeShort((short)o);case 3->d.writeInt((int)o);case 4->d.writeLong((long)o);case 7->{var a=(byte[])o;d.writeInt(a.length);d.write(a);}case 8->d.writeUTF((String)o);case 9->{var a=(List<?>)o;d.writeByte(a.isEmpty()?0:type(a.getFirst()));d.writeInt(a.size());for(var v:a)write(d,v);}case 10->{for(var e:((Map<?,?>)o).entrySet()){d.writeByte(type(e.getValue()));d.writeUTF(e.getKey().toString());write(d,e.getValue());}d.writeByte(0);}case 11->{var a=(int[])o;d.writeInt(a.length);for(int v:a)d.writeInt(v);}case 12->{var a=(long[])o;d.writeInt(a.length);for(long v:a)d.writeLong(v);}default->throw new IllegalArgumentException();}}
 static long[] packed(int[] values,int bits,boolean padded){long[] a=new long[padded?(values.length+64/bits-1)/(64/bits):(values.length*bits+63)/64];for(int i=0;i<values.length;i++)for(int b=0;b<bits;b++)if((values[i]&(1<<b))!=0){long bit=padded?(long)(i/(64/bits))*64+(i%(64/bits))*bits+b:(long)i*bits+b;a[(int)(bit/64)]|=1L<<(bit%64);}return a;}
 @Test void litematicaCrossLongBoundaryNegativeSizeAndEmptyLists()throws Exception{int[] values=new int[67];for(int i=0;i<values.length;i++)values[i]=i%5;var region=Map.of("Position",Map.of("x",5,"y",0,"z",0),"Size",Map.of("x",-67,"y",1,"z",1),"BlockStatePalette",List.of(state("minecraft:air"),state("minecraft:stone"),state("minecraft:gold_block"),state("minecraft:dirt"),state("minecraft:glass")),"BlockStates",packed(values,3,false),"Entities",List.of(),"TileEntities",List.of());var data=Map.of("Version",6,"MinecraftDataVersion",3465,"Regions",Map.of("negative",region));Path p=root.resolve("negative.litematic");try(var out=new GZIPOutputStream(Files.newOutputStream(p))){out.write(nbt(data));}var doc=BuildingDocument.read(p);assertEquals(-61,doc.bounds().min().x());var blocks=new ArrayList<BuildingDocument.Block>();doc.stream(null,true,blocks::add,()->true);assertEquals(67,blocks.size());assertEquals("minecraft:stone",blocks.get(21).state());assertEquals(5,blocks.getLast().pos().x());assertEquals(0L,doc.metadata().get("entityRecords"));}
 @Test void structureCarriesPropertiesAndReportsOmittedNbt(){Map<String,Object> n=Map.of("size",List.of(2,1,1),"palette",List.of(Map.of("Name","minecraft:oak_stairs","Properties",Map.of("facing","west","half","top"))),"blocks",List.of(Map.of("pos",List.of(0,0,0),"state",0,"nbt",Map.of("Command","untrusted"))));var doc=BuildingDocument.fromNbt(n);var blocks=new ArrayList<BuildingDocument.Block>();doc.stream(null,false,blocks::add,()->true);assertEquals("minecraft:oak_stairs[facing=west,half=top]",blocks.getFirst().state());assertEquals(1L,doc.metadata().get("blockEntityRecords"));}
 @Test void spongeV2V3OffsetAndVarint(){for(int version:List.of(2,3)){var n=new HashMap<String,Object>(Map.of("Version",version,"Width",(short)2,"Height",(short)1,"Length",(short)1,"Offset",new int[]{-4,5,6}));var data=Map.of("Palette",Map.of("minecraft:air",0,"minecraft:stone",1),version==3?"Data":"BlockData",new byte[]{1,0});if(version==3)n.put("Blocks",data);else n.putAll(data);var doc=BuildingDocument.fromNbt(version==3?Map.of("Schematic",n):n);var blocks=new ArrayList<BuildingDocument.Block>();doc.stream(null,false,blocks::add,()->true);assertEquals(1,blocks.size());assertEquals(new BuildingDocument.Pos(-4,5,6),blocks.getFirst().pos());}}
 @Test void legacyRetainsIdDataNotSilentAir(){var doc=BuildingDocument.fromNbt(Map.of("Width",(short)2,"Height",(short)1,"Length",(short)1,"Blocks",new byte[]{1,53},"Data",new byte[]{0,6}));var blocks=new ArrayList<BuildingDocument.Block>();doc.stream(null,false,blocks::add,()->true);assertEquals("mineagent_legacy:block_53_6",blocks.getLast().state());}
 @Test void sparseSpongePaletteIdsAreNotConfusedWithArraySize(){var doc=BuildingDocument.fromNbt(Map.of("Version",2,"Width",(short)1,"Height",(short)1,"Length",(short)1,"Palette",Map.of("stone",130),"BlockData",new byte[]{(byte)0x82,1}));var b=new ArrayList<BuildingDocument.Block>();doc.stream(null,false,b::add,()->true);assertEquals("minecraft:stone",b.getFirst().state());}
 @Test void oversizedSourceCanBeInspectedAndClipped(){int[] values=new int[2050];Arrays.fill(values,1);var doc=BuildingDocument.fromNbt(Map.of("Version",6,"Regions",Map.of("wide",Map.of("Position",Map.of("x",0,"y",0,"z",0),"Size",Map.of("x",2050,"y",1,"z",1),"BlockStatePalette",List.of(state("minecraft:air"),state("minecraft:stone")),"BlockStates",packed(values,2,false)))));var b=new ArrayList<BuildingDocument.Block>();doc.stream(new BuildingDocument.Bounds(new BuildingDocument.Pos(2040,0,0),new BuildingDocument.Pos(2049,0,0)),false,b::add,()->true);assertEquals(10,b.size());assertEquals(2050,doc.bounds().size().getFirst());}
 @Test void corruptPaletteAndArrayAreRejected(){var n=Map.of("Version",6,"Regions",Map.of("bad",Map.of("Position",Map.of("x",0,"y",0,"z",0),"Size",Map.of("x",16,"y",1,"z",1),"BlockStatePalette",List.of(state("minecraft:air")),"BlockStates",new long[0])));assertThrows(IllegalArgumentException.class,()->BuildingDocument.fromNbt(n));assertThrows(IOException.class,()->BuildingNbt.read(new ByteArrayInputStream(new byte[]{10,0,0,7,0,1,65,-1,-1,-1,-1})));}
 @Test void modernAnvilReadsSelectedCoordinatesAndRejectsMissingChunks()throws Exception{Path region=Files.createDirectories(root.resolve("region"));Files.write(root.resolve("level.dat"),nbt(Map.of("Data",Map.of("DataVersion",3465))));int[] values=new int[4096];values[1+16*2+256*3]=1;var chunk=Map.of("DataVersion",3465,"xPos",0,"zPos",0,"sections",List.of(Map.of("Y",(byte)4,"block_states",Map.of("palette",List.of(state("minecraft:air"),state("minecraft:gold_block")),"data",packed(values,4,true)))));var b=new ByteArrayOutputStream();try(var z=new DeflaterOutputStream(b)){z.write(nbt(chunk));}byte[] payload=b.toByteArray();try(var out=new RandomAccessFile(region.resolve("r.0.0.mca").toFile(),"rw")){out.setLength(12288);out.writeInt(2<<8|1);out.seek(8192);out.writeInt(payload.length+1);out.writeByte(2);out.write(payload);}var blocks=new ArrayList<BuildingDocument.Block>();var bounds=new BuildingDocument.Bounds(new BuildingDocument.Pos(0,64,0),new BuildingDocument.Pos(15,79,15));var result=AnvilBuildingReader.stream(root,"minecraft:overworld",bounds,false,blocks::add,()->true);assertEquals(1,blocks.size());assertEquals(new BuildingDocument.Pos(1,67,2),blocks.getFirst().pos());assertEquals(0L,result.get("missingChunks"));assertEquals(1,AnvilBuildingReader.inspect(root,0).get("totalRegions"));}
}
