package dev.mineagent.runtime.api.permission;

public enum PermissionAction {
    CHAT,
    START_TASK,
    CREATE_AGENT,
    MODIFY_AGENT,
    CANCEL_AGENT_TASK,
    RUN_CODE,
    MANAGE_PACKAGES,
    MANAGE_PROVIDERS,
    MANAGE_PERMISSIONS,
    CONTROL_PUBLIC_MEDIA,
    MANAGE_SCOREBOARD,
    DISCOVER_OBJECTS,
    SUBSCRIBE_EVENTS,
    SCHEDULE_TASKS,
    ACCESS_SHARED_STATE,
    OFFER_CONTENT,
    RECEIVE_UI_FEEDBACK,
    RESTORE_BACKUP,
    VIEW_DIAGNOSTICS
}
