package dev.mineagent.runtime.core.agent;
import com.fasterxml.jackson.databind.JsonNode;import java.awt.image.BufferedImage;import java.io.*;import javax.imageio.ImageIO;import java.util.*;
/** A tiny, data-only pixel-art skin authoring format; PNG never contains executable code. */
public final class SkinImage {
 public record Rect(int x,int y,int width,int height){}
 public static Map<String,Rect> regions(String model){int arm=model.equals("slim")?3:4;var map=new LinkedHashMap<String,Rect>();cube(map,"head",0,0,8,8,8);cube(map,"head.overlay",32,0,8,8,8);cube(map,"torso",16,16,8,12,4);cube(map,"torso.overlay",16,32,8,12,4);cube(map,"right_arm",40,16,arm,12,4);cube(map,"right_arm.overlay",40,32,arm,12,4);cube(map,"left_arm",32,48,arm,12,4);cube(map,"left_arm.overlay",48,48,arm,12,4);cube(map,"right_leg",0,16,4,12,4);cube(map,"right_leg.overlay",0,32,4,12,4);cube(map,"left_leg",16,48,4,12,4);cube(map,"left_leg.overlay",0,48,4,12,4);return Collections.unmodifiableMap(map);}
 private static void cube(Map<String,Rect> m,String p,int u,int v,int w,int h,int d){m.put(p+".top",new Rect(u+d,v,w,d));m.put(p+".bottom",new Rect(u+d+w,v,w,d));m.put(p+".right",new Rect(u,v+d,d,h));m.put(p+".front",new Rect(u+d,v+d,w,h));m.put(p+".left",new Rect(u+d+w,v+d,d,h));m.put(p+".back",new Rect(u+d*2+w,v+d,w,h));}
 public static byte[] normalize(byte[] png)throws IOException{
  if(png.length<33||png.length>262144||png[0]!=(byte)137||png[1]!=80||png[2]!=78||png[3]!=71)throw new IOException("SKIN_PNG_REQUIRED");var header=java.nio.ByteBuffer.wrap(png);int w=header.getInt(16),h=header.getInt(20);if(w!=64||h!=32&&h!=64)throw new IOException("SKIN_SIZE_64_REQUIRED");BufferedImage input=ImageIO.read(new ByteArrayInputStream(png));if(input==null||input.getWidth()!=64||input.getHeight()!=h)throw new IOException("SKIN_PNG_INVALID");var image=new BufferedImage(64,64,BufferedImage.TYPE_INT_ARGB);for(int y=0;y<h;y++)for(int x=0;x<64;x++)image.setRGB(x,y,input.getRGB(x,y));
  if(h==32){copyMirroredLimb(image,0,16,16,48);copyMirroredLimb(image,40,16,32,48);boolean opaque=true;for(int y=0;y<32;y++)for(int x=32;x<64;x++)opaque&=(image.getRGB(x,y)>>>24)>=128;if(opaque)for(int y=0;y<32;y++)for(int x=32;x<64;x++)image.setRGB(x,y,image.getRGB(x,y)&0xffffff);}
  opaque(image,0,0,32,16);opaque(image,0,16,64,32);opaque(image,16,48,48,64);return encode(image);
 }
 private static void copyMirroredLimb(BufferedImage image,int sx,int sy,int dx,int dy){int[][] faces={{4,0,4,0,4,4},{8,0,8,0,4,4},{0,4,8,4,4,12},{4,4,4,4,4,12},{8,4,0,4,4,12},{12,4,12,4,4,12}};for(var f:faces)for(int y=0;y<f[5];y++)for(int x=0;x<f[4];x++)image.setRGB(dx+f[2]+x,dy+f[3]+y,image.getRGB(sx+f[0]+f[4]-1-x,sy+f[1]+y));}
 private static void opaque(BufferedImage image,int x0,int y0,int x1,int y1){for(int y=y0;y<y1;y++)for(int x=x0;x<x1;x++)image.setRGB(x,y,image.getRGB(x,y)|0xff000000);}
 private static int color(String s){if(s==null||!s.matches("#[0-9a-fA-F]{6}(?:[0-9a-fA-F]{2})?"))throw new IllegalArgumentException("SKIN_COLOR");return (int)Long.parseLong((s.length()==7?"ff":"")+s.substring(1),16);}
 private static void fill(BufferedImage image,int x,int y,int w,int h,int color){if(x<0||y<0||w<1||h<1||x+w>64||y+h>64)throw new IllegalArgumentException("SKIN_RECT");for(int yy=y;yy<y+h;yy++)for(int xx=x;xx<x+w;xx++)image.setRGB(xx,yy,color);}
 public static byte[] paint(byte[] base,String model,JsonNode a)throws IOException{if(!Set.of("wide","slim").contains(model))throw new IllegalArgumentException("SKIN_MODEL");BufferedImage image;if(base==null){image=new BufferedImage(64,64,BufferedImage.TYPE_INT_ARGB);int color=color(a.path("base_color").asText("#b7c9d2"));fill(image,0,0,32,16,color);fill(image,0,16,64,16,color);fill(image,16,48,32,16,color);}else image=ImageIO.read(new ByteArrayInputStream(normalize(base)));var rects=a.path("rects");if(!rects.isArray()||rects.size()>256)throw new IllegalArgumentException("SKIN_RECTS");var regions=regions(model);for(var r:rects){Rect part=r.has("part")?regions.get(r.path("part").asText()):new Rect(0,0,64,64);if(part==null)throw new IllegalArgumentException("SKIN_PART");int x=number(r,"x",0),y=number(r,"y",0),w=number(r,"width",part.width-x),h=number(r,"height",part.height-y);if(x<0||y<0||x+w>part.width||y+h>part.height)throw new IllegalArgumentException("SKIN_PART_BOUNDS");fill(image,part.x+x,part.y+y,w,h,color(r.path("color").asText()));}return normalize(encode(image));}
 private static int number(JsonNode n,String key,int def){if(!n.has(key))return def;if(!n.get(key).isIntegralNumber()||!n.get(key).canConvertToInt())throw new IllegalArgumentException("SKIN_RECT");return n.get(key).intValue();}
 private static byte[] encode(BufferedImage image)throws IOException{var out=new ByteArrayOutputStream();if(!ImageIO.write(image,"PNG",out))throw new IOException("SKIN_PNG_ENCODER");return out.toByteArray();}
 private SkinImage(){}
}
