package dev.mineagent.runtime.neoforge.client.screen;
import dev.mineagent.runtime.neoforge.client.language.ClientLanguage;import net.minecraft.client.Minecraft;import net.minecraft.client.gui.components.*;import net.minecraft.client.gui.screens.Screen;import net.minecraft.network.chat.Component;
public final class LanguageScreen extends Screen {
 private final Screen parent;private String selected;private long revision;private Button follow,zh,en,save;private StringWidget status;
 public LanguageScreen(Screen parent){super(ClientLanguage.component(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("语言设置")));this.parent=parent;var state=ClientLanguage.view();selected=(String)state.get("language");revision=((Number)state.get("revision")).longValue();}
 @Override protected void init(){int x=Math.max(12,width/2-200),w=Math.min(400,width-24),y=Math.max(18,height/2-85);addRenderableWidget(new StringWidget(x,y,w,20,title,font));int third=(w-8)/3;follow=addRenderableWidget(Button.builder(ClientLanguage.component("跟随游戏"),b->{selected="auto";refresh();}).bounds(x,y+28,third,22).build());zh=addRenderableWidget(Button.builder(Component.literal("简体中文"),b->{selected="zh_cn";refresh();}).bounds(x+third+4,y+28,third,22).build());en=addRenderableWidget(Button.builder(Component.literal("English"),b->{selected="en_us";refresh();}).bounds(x+(third+4)*2,y+28,w-2*(third+4),22).build());status=addRenderableWidget(new StringWidget(x,y+60,w,20,ClientLanguage.component(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("仅影响本机界面，不翻译对话或玩家输入。")),font));addRenderableWidget(new StringWidget(x,y+82,w,20,ClientLanguage.component(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("应用将关闭 WebGUI；请先保存其它表单。")),font));save=addRenderableWidget(Button.builder(ClientLanguage.component(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("应用语言")),b->{save.active=follow.active=zh.active=en.active=false;ClientLanguage.save(selected,revision).whenComplete((value,error)->Minecraft.getInstance().execute(()->{if(Minecraft.getInstance().screen!=this)return;if(error!=null){status.setMessage(ClientLanguage.component(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("保存失败，请重新打开设置。")));save.active=true;refresh();return;}dev.mineagent.runtime.neoforge.client.webui.WebGuiHostAdapter.INSTANCE.close();Minecraft.getInstance().setScreen(ControlCenterScreen.create(null));}));}).bounds(x,y+110,w,22).build());addRenderableWidget(Button.builder(ClientLanguage.component(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("返回")),b->onClose()).bounds(x,y+138,w,20).build());refresh();}
 private void refresh(){follow.active=!selected.equals("auto");zh.active=!selected.equals("zh_cn");en.active=!selected.equals("en_us");}
 @Override public boolean isPauseScreen(){return false;}
 @Override public void onClose(){Minecraft.getInstance().setScreen(parent);}
}
