modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="gaoshanliuni"
displayURL="https://github.com/gaoshanliuni/divzero"
logoFile="logo.png"
description='''
面向 Minecraft 26.1.2 NeoForge 的游戏内 AI 玩家、自动编程与动态内容运行时。
'''

[[mixins]]
config="mineagent_runtime.mixins.json"

[[mixins]]
config="mineagent_actions.mixins.json"

[[mixins]]
config="mineagent_webgui.mixins.json"

[[mixins]]
config="mineagent_webgui_common.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies.${mod_id}]]
modId="yes_steve_model"
type="optional"
versionRange="[2.6.5-neoforge+mc26.1,2.7)"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="webgui"
type="required"
versionRange="[1.6.2+mc26.1.2]"
ordering="AFTER"
side="BOTH"

[[dependencies.${mod_id}]]
modId="mcef"
type="required"
versionRange="[2.2.0]"
ordering="AFTER"
side="CLIENT"
