package dev.mineagent.runtime.core.config;
import dev.mineagent.runtime.api.config.ConfigPatch;
import dev.mineagent.runtime.api.worker.WorkerEnvelope;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;
/** Per-world/Agent selection; absence means live global inheritance, never a copied initial model. */
public final class AgentModelSettings {
 private static final ObjectMapper JSON=new ObjectMapper();
 public record Choice(UUID world,UUID agent,String mode,String model,String baseUrl,long revision){public Choice{Objects.requireNonNull(world);Objects.requireNonNull(agent);if(!Set.of("DEFAULT","CUSTOM").contains(mode)||revision<0||model==null||baseUrl==null||mode.equals("CUSTOM")&&(!validModel(model)||!WebSettingsCatalog.safeUrl(baseUrl))||mode.equals("DEFAULT")&&(!model.isEmpty()||!baseUrl.isEmpty()))throw new IllegalArgumentException("AGENT_MODEL_INVALID");}}
 private AgentModelSettings(){}
 public static boolean validModel(String model){return model!=null&&!model.isBlank()&&model.equals(model.strip())&&model.length()<=256&&model.codePoints().noneMatch(Character::isISOControl);}
 public static String origin(String url){if(!WebSettingsCatalog.safeUrl(url))throw new IllegalArgumentException("AGENT_MODEL_API_REQUIRED");return url.endsWith("/")?url:url+"/";}
 private static String key(UUID world,UUID agent){return "ai.model."+world+"."+agent;}
 public static Choice read(Map<String,String> values,UUID world,UUID agent){String raw=values.get(key(world,agent));if(raw==null)return new Choice(world,agent,"DEFAULT","","",0);try{var c=JSON.readValue(raw,Choice.class);if(!world.equals(c.world())||!agent.equals(c.agent()))throw new IllegalArgumentException();return c;}catch(Exception e){throw new IllegalArgumentException("AGENT_MODEL_STATE_INVALID");}}
 public static Choice save(ServerConfigService config,UUID world,UUID agent,long expected,String mode,String model,String expectedBase)throws Exception{synchronized(config){var snapshot=config.snapshot();var old=read(snapshot.values(),world,agent);if(old.revision()!=expected)throw new IllegalStateException("AGENT_MODEL_STALE");String url="";if(mode.equals("CUSTOM")){url=origin(snapshot.values().getOrDefault("provider.openai.baseUrl",""));if(!url.equals(origin(expectedBase))||!Boolean.parseBoolean(snapshot.values().getOrDefault("provider.openai.enabled","true")))throw new IllegalStateException("AGENT_MODEL_API_CHANGED");}var choice=new Choice(world,agent,mode,mode.equals("CUSTOM")?model:"",url,expected+1);var result=config.apply(new ConfigPatch(snapshot.revision(),Map.of(key(world,agent),JSON.writeValueAsString(choice))),true);if(!result.accepted())throw new IllegalStateException(result.errorCode());return choice;}}
 public static WorkerEnvelope bind(ServerConfigService config,WorkerEnvelope request){var data=request.payload();if(!data.containsKey("agentId")||!data.containsKey("worldId"))return request;var withThinking=new LinkedHashMap<String,Object>(data);withThinking.put("agentThinking",AgentThinkingSettings.read(config.snapshot().values(),UUID.fromString(data.get("worldId").toString()),UUID.fromString(data.get("agentId").toString())));request=new WorkerEnvelope(request.protocolVersion(),request.requestId(),request.type(),withThinking);data=request.payload();var choice=read(config.snapshot().values(),UUID.fromString(data.get("worldId").toString()),UUID.fromString(data.get("agentId").toString()));if(choice.mode().equals("DEFAULT"))return request;var payload=new LinkedHashMap<String,Object>(data);payload.put("agentModel",Map.of("world",choice.world().toString(),"agent",choice.agent().toString(),"model",choice.model(),"baseUrl",choice.baseUrl(),"revision",choice.revision()));return new WorkerEnvelope(request.protocolVersion(),request.requestId(),request.type(),payload);}
 public static WorkerEnvelope context(WorkerEnvelope request,UUID world,UUID agent){if(world==null||agent==null)return request;var p=new LinkedHashMap<String,Object>(request.payload());p.put("worldId",world.toString());p.put("agentId",agent.toString());return new WorkerEnvelope(request.protocolVersion(),request.requestId(),request.type(),p);}
}
