package dev.mineagent.runtime.neoforge.integration;
import net.minecraft.world.entity.Entity;import java.util.*;
/** Optional, version-observed public Naga API. Never loads an arbitrary class or executes user method names. */
public final class TwilightNagaInterop {
 public static boolean supports(Entity e){return net.minecraft.core.registries.BuiltInRegistries.ENTITY_TYPE.getKey(e.getType()).toString().equals("twilightforest:naga");}
 public static Map<String,Object> inspect(Entity e){if(!supports(e))return Map.of("adapter","generic");var out=new LinkedHashMap<String,Object>();out.put("adapter","twilightforest_naga_public_api");out.put("modVersion",net.neoforged.fml.ModList.get().getModContainerById("twilightforest").map(c->c.getModInfo().getVersion().toString()).orElse(""));try{for(String name:List.of("isDazed","isCharging","isStunlessCharging"))out.put(name,e.getClass().getMethod(name).invoke(e));Object pattern=e.getClass().getMethod("getMovementPattern").invoke(e);out.put("movementPhase",String.valueOf(pattern.getClass().getMethod("getState").invoke(pattern)));out.put("actions",List.of("naga.daze","naga.circle","naga.crumble"));out.put("multipart",true);out.put("sourceNote","NagaSegment forwards damage to its parent at 2/3; parent policies apply after the native conversion. Its collision attack is intercepted before pushing or hurting.");}catch(ReflectiveOperationException ex){out.put("error","NAGA_ADAPTER_VERSION_UNSUPPORTED");}return out;}
 public static void action(Entity e,String action)throws ReflectiveOperationException{if(!supports(e))throw new IllegalArgumentException("NAGA_ADAPTER_TARGET");String method=switch(action){case "naga.daze"->"doDaze";case "naga.circle"->"forceCircle";case "naga.crumble"->"doCrumblePlayer";default->throw new IllegalArgumentException("NAGA_ADAPTER_ACTION");};Object pattern=e.getClass().getMethod("getMovementPattern").invoke(e);pattern.getClass().getMethod(method).invoke(pattern);if(action.equals("naga.daze")||action.equals("naga.circle")){e.getClass().getMethod("setDazed",boolean.class).invoke(e,action.equals("naga.daze"));e.getClass().getMethod("setCharging",boolean.class).invoke(e,false);e.getClass().getMethod("setStunlessCharging",boolean.class).invoke(e,false);}}
 private TwilightNagaInterop(){}
}
