package dev.mineagent.runtime.client.scripts;

import com.fasterxml.jackson.databind.ObjectMapper;
import dev.mineagent.runtime.api.packages.RuntimePackage;
import dev.mineagent.runtime.core.packages.*;

import java.nio.file.*;
import java.nio.channels.*;
import java.sql.*;
import java.util.*;

/** Exact local consent and lifecycle journal for signed CLIENT scripts. Nothing is auto-started after process restart. */
public final class LocalClientScriptStore implements AutoCloseable {
    public record Asset(String filename,String serverId,String fingerprint,RuntimePackage manifest,String bundleHash,String environment,String state,String code,long revision,boolean localConsent){ }
    public record CodeDelivery(UUID deliveryId,String filename,String serverId,String fingerprint,UUID packageId,long packageRevision,String canonical,String language,long reportedAssetRevision,String reportedState,long revision){public CodeDelivery{Objects.requireNonNull(deliveryId);Objects.requireNonNull(packageId);if(!(ClientScriptPlan.managedName(filename)||ClientJavaPlan.managedName(filename))||serverId==null||serverId.isBlank()||!fingerprint.matches("[a-f0-9]{64}")||packageRevision<1||!canonical.matches("[a-f0-9]{64}")||!Set.of("RHINO","JAVA").contains(language)||reportedAssetRevision<0||!Set.of("","DOWNLOADED","RUNNING","STOPPED","FAILED").contains(reportedState)||revision<1)throw new IllegalArgumentException("CLIENT_CODE_DELIVERY");}}
    public record Input(UUID operation,String filename,String action,long expectedRevision,String environment,String actor){public Input{Objects.requireNonNull(operation);if(!(ClientScriptPlan.managedName(filename)||ClientJavaPlan.managedName(filename))||!Set.of("START","STOP").contains(action)||expectedRevision<1||!environment.matches("[a-f0-9]{64}")||actor==null||actor.isBlank()||actor.length()>80)throw new IllegalArgumentException("CLIENT_SCRIPT_OPERATION");}}
    public record Job(Input input,String before,String after,String phase,String code,long revision,long updatedAt){public Job{if(!Set.of("PREPARING","DISPATCHING","COMPLETED","FAILED","UNKNOWN").contains(phase)||!code.matches("[A-Z0-9_]{0,96}")||revision<1)throw new IllegalArgumentException("CLIENT_SCRIPT_JOB");}}
    private static final Map<Path,LocalClientScriptStore> OPEN=new HashMap<>();
    private final Path root;private final Connection db;private final FileChannel channel;private final FileLock lock;private final ObjectMapper json=new ObjectMapper();private final Map<String,Asset> assets=new LinkedHashMap<>();
    public static synchronized LocalClientScriptStore get(Path root)throws Exception{Path real=root.toRealPath();var current=OPEN.get(real);if(current==null){current=new LocalClientScriptStore(real);OPEN.put(real,current);}return current;}
    private LocalClientScriptStore(Path root)throws Exception{
        this.root=root;Path directory=root.resolve("config");Files.createDirectories(directory);if(!directory.toRealPath().getParent().equals(root))throw new IllegalStateException("CLIENT_SCRIPT_CONFIG_LINK");
        Path file=directory.resolve("mineagent-client-scripts.db"),lease=directory.resolve("mineagent-client-scripts.lock");for(Path p:List.of(file,lease))if(Files.exists(p,LinkOption.NOFOLLOW_LINKS)&&(!Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)||Files.isSymbolicLink(p)))throw new IllegalStateException("CLIENT_SCRIPT_STORE_LINK");
        channel=FileChannel.open(lease,StandardOpenOption.CREATE,StandardOpenOption.WRITE);FileLock acquired=null;Connection connection=null;
        try{acquired=channel.tryLock();if(acquired==null)throw new IllegalStateException("CLIENT_SCRIPT_STORE_IN_USE");connection=DriverManager.getConnection("jdbc:sqlite:"+file);db=connection;lock=acquired;
            try(var s=db.createStatement()){s.execute("PRAGMA busy_timeout=1500");s.execute("PRAGMA journal_mode=WAL");s.execute("CREATE TABLE IF NOT EXISTS client_script_assets_v1(filename TEXT PRIMARY KEY,payload TEXT NOT NULL,bytes INTEGER NOT NULL,content_bytes INTEGER NOT NULL)");s.execute("CREATE TABLE IF NOT EXISTS client_script_jobs_v1(id TEXT PRIMARY KEY,filename TEXT NOT NULL,payload TEXT NOT NULL,phase TEXT NOT NULL,bytes INTEGER NOT NULL,updated INTEGER NOT NULL)");s.execute("CREATE INDEX IF NOT EXISTS client_script_job_asset ON client_script_jobs_v1(filename,updated DESC)");s.execute("CREATE TABLE IF NOT EXISTS client_code_deliveries_v1(id TEXT PRIMARY KEY,filename TEXT NOT NULL,payload TEXT NOT NULL,bytes INTEGER NOT NULL)");s.execute("CREATE INDEX IF NOT EXISTS client_code_delivery_asset ON client_code_deliveries_v1(filename)");}
            reload();for(var a:List.copyOf(assets.values()))if(Set.of("STARTING","RUNNING","STOPPING","UNKNOWN").contains(a.state())){var stopped=new Asset(a.filename(),a.serverId(),a.fingerprint(),a.manifest(),a.bundleHash(),a.environment(),"STOPPED","CLIENT_CODE_RESTART_NOT_RUNNING",a.revision()+1,false);write(stopped);assets.put(stopped.filename(),stopped);}var interrupted=new ArrayList<Job>();try(var q=db.prepareStatement("SELECT payload FROM client_script_jobs_v1 WHERE phase IN ('PREPARING','DISPATCHING')");var r=q.executeQuery()){while(r.next())interrupted.add(json.readValue(r.getString(1),Job.class));}for(var j:interrupted)finish(j,false,"CLIENT_CODE_RESTART_NOT_RUNNING");
        }catch(Exception failure){if(connection!=null)connection.close();if(acquired!=null)acquired.release();channel.close();throw failure;}
    }
    public Path cacheDirectory(){return root.resolve("mineagent-runtime-data/client-script-cache");}
    public static String publisher(String server,String fingerprint)throws Exception{return RuntimePackageCanonicalizer.sha256(RuntimePackageCanonicalizer.stableJson(Map.of("server",server,"fingerprint",fingerprint)));}
    public synchronized Asset get(String filename){var a=assets.get(filename);if(a==null)throw new IllegalStateException("CLIENT_SCRIPT_NOT_CACHED");return a;}
    public synchronized List<Asset> list(){return List.copyOf(assets.values());}
    public synchronized Optional<Job> job(UUID id)throws Exception{try(var q=db.prepareStatement("SELECT payload FROM client_script_jobs_v1 WHERE id=?")){q.setString(1,id.toString());try(var r=q.executeQuery()){return r.next()?Optional.of(json.readValue(r.getString(1),Job.class)):Optional.empty();}}}
    public synchronized Optional<Job> latest(String filename)throws Exception{try(var q=db.prepareStatement("SELECT payload FROM client_script_jobs_v1 WHERE filename=? ORDER BY updated DESC LIMIT 1")){q.setString(1,filename);try(var r=q.executeQuery()){return r.next()?Optional.of(json.readValue(r.getString(1),Job.class)):Optional.empty();}}}
    public synchronized List<CodeDelivery> codeDeliveries()throws Exception{var result=new ArrayList<CodeDelivery>();try(var q=db.prepareStatement("SELECT payload FROM client_code_deliveries_v1 ORDER BY rowid");var r=q.executeQuery()){while(r.next())result.add(json.readValue(r.getString(1),CodeDelivery.class));}return List.copyOf(result);}
    public synchronized CodeDelivery bindDelivery(UUID delivery,Asset asset)throws Exception{var old=codeDeliveries().stream().filter(v->v.deliveryId().equals(delivery)).findFirst().orElse(null);String language=ClientJavaPlan.managedName(asset.filename())?"JAVA":"RHINO";if(old!=null){if(!old.filename().equals(asset.filename())||!old.serverId().equals(asset.serverId())||!old.fingerprint().equals(asset.fingerprint())||!old.packageId().equals(asset.manifest().packageId())||old.packageRevision()!=asset.manifest().revision()||!old.canonical().equals(asset.manifest().canonicalSha256())||!old.language().equals(language))throw new IllegalStateException("CLIENT_CODE_DELIVERY_REUSED");return old;}if(aggregate("client_code_deliveries_v1","COUNT(*)")>=4096)throw new IllegalStateException("CLIENT_CODE_DELIVERY_BUDGET");var next=new CodeDelivery(delivery,asset.filename(),asset.serverId(),asset.fingerprint(),asset.manifest().packageId(),asset.manifest().revision(),asset.manifest().canonicalSha256(),language,0,"",1);write(next);return next;}
    public synchronized CodeDelivery reported(UUID delivery,long expected,long assetRevision,String state)throws Exception{var current=codeDeliveries().stream().filter(v->v.deliveryId().equals(delivery)).findFirst().orElseThrow(()->new IllegalStateException("CLIENT_CODE_DELIVERY_MISSING"));if(current.revision()!=expected)throw new IllegalStateException("CLIENT_CODE_DELIVERY_STALE");var next=new CodeDelivery(current.deliveryId(),current.filename(),current.serverId(),current.fingerprint(),current.packageId(),current.packageRevision(),current.canonical(),current.language(),assetRevision,state,current.revision()+1);write(next);return next;}
    public synchronized Asset downloaded(String server,String fingerprint,ClientScriptPlan.Resolved resolved)throws Exception{
        return downloaded(server,fingerprint,resolved.plan().manifest(),resolved.plan().filename(publisher(server,fingerprint)),resolved.bundle(),resolved.bundleHash(),false);
    }
    public synchronized Asset downloaded(String server,String fingerprint,ClientJavaPlan.Resolved resolved)throws Exception{
        return downloaded(server,fingerprint,resolved.plan().manifest(),resolved.plan().filename(publisher(server,fingerprint)),resolved.bundle(),resolved.bundleHash(),true);
    }
    private Asset downloaded(String server,String fingerprint,RuntimePackage manifest,String filename,byte[] bundle,String bundleHash,boolean javaSource)throws Exception{
        var old=assets.get(filename);if(old!=null){if(!old.bundleHash().equals(bundleHash))throw new IllegalStateException("CLIENT_SCRIPT_CACHE_CONFLICT");if(Set.of("STARTING","RUNNING","STOPPING","UNKNOWN").contains(old.state()))throw new IllegalStateException("CLIENT_CODE_PRIOR_ACTIVE");if(old.state().equals("DOWNLOADED"))return old;var reset=new Asset(old.filename(),old.serverId(),old.fingerprint(),old.manifest(),old.bundleHash(),"","DOWNLOADED",javaSource?"CLIENT_JAVA_DOWNLOADED_NOT_APPROVED":"CLIENT_SCRIPT_DOWNLOADED_NOT_APPROVED",old.revision()+1,false);write(reset);assets.put(reset.filename(),reset);return reset;}
        var next=new Asset(filename,server,fingerprint,manifest,bundleHash,"","DOWNLOADED",javaSource?"CLIENT_JAVA_DOWNLOADED_NOT_APPROVED":"CLIENT_SCRIPT_DOWNLOADED_NOT_APPROVED",1,false);byte[] raw=json.writeValueAsBytes(next);
        if(raw.length>512*1024||aggregate("client_script_assets_v1","COUNT(*)")>=4096||aggregate("client_script_assets_v1","COALESCE(SUM(bytes),0)")+raw.length+512>32L*1024*1024||aggregate("client_script_assets_v1","COALESCE(SUM(content_bytes),0)")+bundle.length>512L*1024*1024)throw new IllegalStateException("CLIENT_SCRIPT_CACHE_BUDGET");
        if(javaSource)ClientJavaPlan.publish(cacheDirectory(),filename,bundle,bundleHash);else ClientScriptPlan.publish(cacheDirectory(),filename,bundle,bundleHash);write(next);assets.put(filename,next);return next;
    }
    public synchronized Job begin(Input input,String after)throws Exception{
        var old=job(input.operation());if(old.isPresent()){if(!old.get().input().equals(input))throw new IllegalStateException("CLIENT_SCRIPT_OPERATION_REUSED");return old.get();}var a=get(input.filename());if(a.revision()!=input.expectedRevision())throw new IllegalStateException("CLIENT_SCRIPT_STALE");
        if(input.action().equals("START")&&!Set.of("DOWNLOADED","STOPPED","FAILED").contains(a.state())||input.action().equals("STOP")&&!a.state().equals("RUNNING"))throw new IllegalStateException("CLIENT_SCRIPT_STATE_CHANGED");
        if(aggregate("client_script_jobs_v1","COUNT(*)")>=65536||aggregate("client_script_jobs_v1","COALESCE(SUM(bytes),0)")>64L*1024*1024-65536)throw new IllegalStateException("CLIENT_SCRIPT_JOB_BUDGET");var next=new Job(input,a.state(),after,"PREPARING","",1,System.currentTimeMillis());write(next);return next;
    }
    public synchronized Job dispatch(Job expected)throws Exception{
        var current=job(expected.input().operation()).orElseThrow();if(!current.equals(expected)||!current.phase().equals("PREPARING"))throw new IllegalStateException("CLIENT_SCRIPT_JOB_CHANGED");var a=get(current.input().filename());if(a.revision()!=current.input().expectedRevision())throw new IllegalStateException("CLIENT_SCRIPT_STALE");
        var next=new Job(current.input(),current.before(),current.after(),"DISPATCHING","",current.revision()+1,System.currentTimeMillis());var asset=new Asset(a.filename(),a.serverId(),a.fingerprint(),a.manifest(),a.bundleHash(),current.input().environment(),current.input().action().equals("START")?"STARTING":"STOPPING","",a.revision()+1,current.input().action().equals("START"));
        db.setAutoCommit(false);try{write(asset);write(next);db.commit();assets.put(asset.filename(),asset);return next;}catch(Exception failure){db.rollback();throw failure;}finally{db.setAutoCommit(true);}
    }
    public synchronized Job finish(Job expected,boolean success,String code)throws Exception{
        var current=job(expected.input().operation()).orElseThrow();if(!current.input().equals(expected.input()))throw new IllegalStateException("CLIENT_SCRIPT_OPERATION_REUSED");reload();if(Set.of("COMPLETED","FAILED","UNKNOWN").contains(current.phase()))return current;if(code==null||!code.matches("[A-Z0-9_]{1,96}"))throw new IllegalArgumentException("CLIENT_SCRIPT_CODE");
        boolean dispatch=current.phase().equals("DISPATCHING"),start=current.input().action().equals("START"),restart=code.equals("CLIENT_SCRIPT_RESTART_NOT_RUNNING")||code.equals("CLIENT_CODE_RESTART_NOT_RUNNING"),unknown=code.equals("CLIENT_JAVA_START_UNKNOWN")||dispatch&&!start;String state=success?(start?"RUNNING":"STOPPED"):restart?"STOPPED":unknown?"UNKNOWN":"FAILED";var next=new Job(current.input(),current.before(),state,success?"COMPLETED":unknown?"UNKNOWN":"FAILED",code,current.revision()+1,System.currentTimeMillis());var a=get(current.input().filename());var asset=new Asset(a.filename(),a.serverId(),a.fingerprint(),a.manifest(),a.bundleHash(),a.environment(),state,code,a.revision()+1,success&&start);
        db.setAutoCommit(false);try{write(asset);write(next);db.commit();assets.put(asset.filename(),asset);return next;}catch(Exception failure){db.rollback();throw failure;}finally{db.setAutoCommit(true);}
    }
    private void reload()throws Exception{var next=new LinkedHashMap<String,Asset>();try(var q=db.prepareStatement("SELECT filename,payload FROM client_script_assets_v1");var r=q.executeQuery()){while(r.next()){var a=json.readValue(r.getString(2),Asset.class);if(!a.filename().equals(r.getString(1))||!(ClientScriptPlan.managedName(a.filename())||ClientJavaPlan.managedName(a.filename())))throw new IllegalStateException("CLIENT_SCRIPT_RECORD");next.put(a.filename(),a);}}assets.clear();assets.putAll(next);}
    private void write(Asset a)throws Exception{String raw=json.writeValueAsString(a);long content=ClientJavaPlan.managedName(a.filename())?ClientJavaPlan.inspect(a.manifest()).bytes():ClientScriptPlan.inspect(a.manifest()).bytes();try(var q=db.prepareStatement("INSERT INTO client_script_assets_v1 VALUES(?,?,?,?) ON CONFLICT(filename) DO UPDATE SET payload=excluded.payload,bytes=excluded.bytes")){q.setString(1,a.filename());q.setString(2,raw);q.setInt(3,raw.getBytes(java.nio.charset.StandardCharsets.UTF_8).length);q.setLong(4,content);q.executeUpdate();}}
    private void write(Job j)throws Exception{String raw=json.writeValueAsString(j);if(raw.length()>65536)throw new IllegalStateException("CLIENT_SCRIPT_JOB_BUDGET");try(var q=db.prepareStatement("INSERT INTO client_script_jobs_v1 VALUES(?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET payload=excluded.payload,phase=excluded.phase,bytes=excluded.bytes,updated=excluded.updated")){q.setString(1,j.input().operation().toString());q.setString(2,j.input().filename());q.setString(3,raw);q.setString(4,j.phase());q.setInt(5,raw.getBytes(java.nio.charset.StandardCharsets.UTF_8).length);q.setLong(6,j.updatedAt());q.executeUpdate();}}
    private void write(CodeDelivery value)throws Exception{String raw=json.writeValueAsString(value);if(raw.getBytes(java.nio.charset.StandardCharsets.UTF_8).length>65536)throw new IllegalStateException("CLIENT_CODE_DELIVERY_BUDGET");try(var q=db.prepareStatement("INSERT INTO client_code_deliveries_v1 VALUES(?,?,?,?) ON CONFLICT(id) DO UPDATE SET filename=excluded.filename,payload=excluded.payload,bytes=excluded.bytes")){q.setString(1,value.deliveryId().toString());q.setString(2,value.filename());q.setString(3,raw);q.setInt(4,raw.getBytes(java.nio.charset.StandardCharsets.UTF_8).length);q.executeUpdate();}}
    private long aggregate(String table,String expression)throws SQLException{try(var q=db.prepareStatement("SELECT "+expression+" FROM "+table);var r=q.executeQuery()){return r.next()?r.getLong(1):0;}}
    @Override public synchronized void close()throws Exception{db.close();lock.release();channel.close();synchronized(LocalClientScriptStore.class){OPEN.remove(root,this);}}
}
