package dev.mineagent.runtime.neoforge.client.chat;
import dev.mineagent.runtime.neoforge.ui.AgentModelSmokeServer;import dev.mineagent.runtime.neoforge.client.webui.*;import dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen;import dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox;import net.minecraft.client.Minecraft;import com.google.gson.*;import java.nio.file.*;import java.util.*;
public final class AgentModelSmokeClient {
 private static int ticks,phase,wait;private static boolean done,busy,listed,refreshed;private static JsonObject probe;
 public static void accept(JsonObject v){probe=v;}
 private static void script(String s){var h=WebGuiHostAdapter.INSTANCE;h.browser().executeJavaScript("(()=>{"+s+"})();",h.browser().getURL(),0);}
 private static void require(boolean v,String code){if(!v)throw new IllegalStateException(code);}
 public static void tick()throws Exception{if(done)return;var mc=Minecraft.getInstance();var host=WebGuiHostAdapter.INSTANCE;ticks++;Path root=Files.createDirectories(mc.gameDirectory.toPath().resolve("agent-model-smoke"));try{
  require(AgentModelSmokeServer.failure.isEmpty(),AgentModelSmokeServer.failure);require(ticks<18000,"AGENT_MODEL_TIMEOUT_"+phase);if(mc.player==null||!AgentModelSmokeServer.ready||busy)return;
  if(ticks%100==0)Files.writeString(root.resolve("progress.json"),new Gson().toJson(Map.of("phase",phase,"verified",AgentModelSmokeServer.verified,"probe",probe==null?new JsonObject():probe)));
  if(phase==0){String fp=PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","");if(fp.isEmpty()||new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fp)!=dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){if(mc.screen instanceof ControlCenterScreen s)for(var child:List.copyOf(s.children()))if(child instanceof net.minecraft.client.gui.components.Button b&&b.active&&b.getMessage().getString().contains("信任此服务器"))b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));return;}if(++wait==1)mc.player.connection.sendCommand("ai accept");if(wait<40)return;AgentModelSmokeServer.clientReady=true;mc.setScreen(null);if(!AgentModelSmokeServer.uiOnly())mc.player.connection.sendChat("@默认助手 不调用任何工具、不操作游戏或电脑，只回复DEFAULT_A。");phase=1;}
  if(phase==1&&AgentModelSmokeServer.verified==1){host.open();phase=2;}
  if(phase>=2&&host.ready()&&UiClientSessions.current()!=null&&ticks%10==0)script("window.mineagentQuery({request:JSON.stringify({channel:'conversationAgentProbe',cards:[...document.querySelectorAll('[data-agent-card]')].map(n=>n.dataset.agentCard),title:document.querySelector('#agent-model-title')?.textContent??'',mode:document.querySelector('#agent-model-mode')?.value??'',models:[...document.querySelectorAll('#agent-model-list option')].map(n=>n.value),customVisible:(document.querySelector('#agent-model-custom-label')?.getBoundingClientRect().height??0)>0,selected:document.querySelector('#agent-model-list')?.value??'',status:document.querySelector('#agent-model-status')?.textContent??'',catalog:document.querySelector('#agent-model-catalog-status')?.textContent??'',catalogError:document.querySelector('#agent-model-catalog-status')?.dataset.error??''}),persistent:false,onSuccess(){},onFailure(){}});");
  if(phase==2&&host.ready()&&UiClientSessions.current()!=null){script("document.querySelector('#open-agents').click();");phase=3;}
  if(phase==3&&probe!=null&&probe.getAsJsonArray("cards").toString().contains(AgentModelSmokeServer.second.toString())){script("document.querySelector('[data-agent-card=\""+AgentModelSmokeServer.second+"\"] [data-agent-action=model]').click();");phase=4;}
  if(phase==4&&probe.get("title").getAsString().contains("独立助手")&&(probe.getAsJsonArray("models").toString().contains("deepseek-v4-pro")||probe.get("catalog").getAsString().contains("失败"))){listed=probe.getAsJsonArray("models").toString().contains("deepseek-v4-pro");if(!listed&&!refreshed){refreshed=true;script("document.querySelector('#agent-model-refresh').click();");return;}require(probe.get("mode").getAsString().equals("DEFAULT"),"NEW_AGENT_NOT_DEFAULT");script("const mode=document.querySelector('#agent-model-mode');mode.value='CUSTOM';mode.dispatchEvent(new Event('change'));const s=document.querySelector('#agent-model-list');s.value='';s.dispatchEvent(new Event('change'));");phase=5;}
  if(phase==5&&probe.get("customVisible").getAsBoolean()){script((listed?"const s=document.querySelector('#agent-model-list');s.value='deepseek-v4-pro';s.dispatchEvent(new Event('change'));":"const s=document.querySelector('#agent-model-custom');s.value='deepseek-v4-pro';s.dispatchEvent(new Event('input'));")+"document.querySelector('#agent-model-save').click();");phase=6;}
  if(phase==6&&probe.get("status").getAsString().startsWith("已保存")&&(listed?probe.get("selected").getAsString().equals("deepseek-v4-pro"):probe.get("customVisible").getAsBoolean())){require(probe.get("customVisible").getAsBoolean()!=listed,"CUSTOM_FIELD_STATE");Files.writeString(root.resolve("selection.json"),probe.toString());busy=true;net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),img->{try(img){img.writeToFile(root.resolve("per-agent-model.png"));}catch(Exception e){AgentModelSmokeServer.failure=e.toString();}finally{busy=false;}});host.hideWorkspace();if(!AgentModelSmokeServer.uiOnly())mc.player.connection.sendChat("@独立助手 不调用任何工具、不操作游戏或电脑，只回复CUSTOM_B。");phase=7;}
  if(phase==7&&AgentModelSmokeServer.verified==2){host.open();phase=8;}
  if(phase==8&&host.ready()&&UiClientSessions.current()!=null){script("const mode=document.querySelector('#agent-model-mode');mode.value='DEFAULT';mode.dispatchEvent(new Event('change'));document.querySelector('#agent-model-save').click();");phase=9;wait=0;}
  if(phase==9&&++wait>30&&probe.get("mode").getAsString().equals("DEFAULT")&&probe.get("status").getAsString().startsWith("已保存")){host.hideWorkspace();if(!AgentModelSmokeServer.uiOnly())mc.player.connection.sendChat("@独立助手 不调用任何工具、不操作游戏或电脑，只回复RESTORED_B。");phase=10;}
  if(phase==10&&AgentModelSmokeServer.complete){require(!AgentModelSmokeServer.uiOnly()||listed,"CATALOG_MUST_BE_SELECTED_IN_UI_RECHECK");Files.writeString(root.resolve("client.json"),new Gson().toJson(Map.of("status",AgentModelSmokeServer.uiOnly()?"F2_AGENT_MODEL_CATALOG_ZERO_MODEL_VERIFIED":"REAL_F2_PER_AGENT_MODEL_AND_RESTORE_VERIFIED","catalogSelection",listed,"customInputToggle",true,"otherAgentUnaffected",true,"osInputInjected",false)));done=true;host.close();dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");mc.stop();}
 }catch(Exception e){done=true;Files.writeString(root.resolve("client-failure.json"),new Gson().toJson(Map.of("phase",phase,"error",e.toString(),"probe",probe==null?new JsonObject():probe)));host.close();mc.stop();}}
}
