package dev.mineagent.runtime.neoforge.client.chat;
import dev.mineagent.runtime.neoforge.ui.ClearancePathSmokeServer;import dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen;import dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox;import net.minecraft.client.Minecraft;import java.nio.file.*;import java.util.*;
public final class ClearancePathSmokeClient {
 private static boolean done;private static int ticks,wait,crouchFrames,standFrames;
 public static void tick()throws Exception{if(done)return;var mc=Minecraft.getInstance();ticks++;var root=Files.createDirectories(mc.gameDirectory.toPath().resolve("clearance-path-smoke"));try{if(!ClearancePathSmokeServer.failure.isEmpty())throw new IllegalStateException(ClearancePathSmokeServer.failure);if(ticks>36000)throw new IllegalStateException("CLEARANCE_TIMEOUT");if(mc.player==null||!ClearancePathSmokeServer.ready)return;var b=mc.level.getPlayerByUUID(ClearancePathSmokeServer.agent);if(b!=null){if(b.isCrouching())crouchFrames++;else standFrames++;}if(!ClearancePathSmokeServer.clientReady){String fp=PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","");if(fp.isEmpty()||new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fp)!=dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){if(mc.screen instanceof ControlCenterScreen s)for(var c:List.copyOf(s.children()))if(c instanceof net.minecraft.client.gui.components.Button button&&button.active&&button.getMessage().getString().contains("信任此服务器"))button.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));return;}if(++wait==1)mc.player.connection.sendCommand("ai accept");if(wait<40)return;mc.setScreen(null);ClearancePathSmokeServer.clientReady=true;}
 if(mc.player!=null&&ClearancePathSmokeServer.clientReady&&!ClearancePathSmokeServer.real())mc.options.keyUp.setDown(ClearancePathSmokeServer.playerReuse>0);
 if(ClearancePathSmokeServer.complete){mc.options.keyUp.setDown(false);if(!ClearancePathSmokeServer.schema()&&(crouchFrames==0||standFrames==0))throw new IllegalStateException("POSE_NOT_CLIENT_VISIBLE");Files.writeString(root.resolve("client.json"),new com.google.gson.Gson().toJson(Map.of("status","CLIENT_POSES_VERIFIED","crouchFrames",crouchFrames,"standFrames",standFrames,"osInputInjected",false)));done=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");dev.mineagent.runtime.neoforge.client.cinematic.CinematicCaptureClient.finish();}
 }catch(Exception e){mc.options.keyUp.setDown(false);Files.writeString(root.resolve("client-failure.json"),e.toString());done=true;dev.mineagent.runtime.neoforge.client.cinematic.CinematicCaptureClient.finish();}}
 private ClearancePathSmokeClient(){}
}
