package dev.mineagent.runtime.neoforge.client.chat;
import dev.mineagent.runtime.neoforge.ui.*;
import net.minecraft.client.Minecraft;
import net.minecraft.world.scores.DisplaySlot;
import java.nio.file.*;
import java.util.*;
final class ConversationBasketballSmokeClient {
    private static int ticks,wait,seen,holding,captureWait;private static boolean sent,done,captured;private static volatile boolean captureBusy;
    static void tick()throws Exception{
        if(done)return;var mc=Minecraft.getInstance();var root=Files.createDirectories(mc.gameDirectory.toPath().resolve("runtime-item-smoke"));ticks++;
        try{
            if(!ConversationRuntimeItemSmokeServer.failure.isEmpty())throw new IllegalStateException(ConversationRuntimeItemSmokeServer.failure);if(ticks>18000)throw new IllegalStateException("BASKETBALL_CLIENT_TIMEOUT");if(mc.player==null||!ConversationRuntimeItemSmokeServer.ready)return;
            if(!ConversationRuntimeItemSmokeServer.saved()&&!sent&&++wait>=15){sent=true;String prompt=System.getProperty("mineagent.conversationAgentScenario","").equals("basketball_layout")?"@工具助手 新建完整篮球HOT包。前包立柱、篮板、后侧环边沿重叠导致启用失败；请放在实例原点前的空地，各solid件留空隙，中心足够0.4格球通过。保留64×32球面黑线、40Tick蓄力投掷反弹拾回、3格篮架、真实向下入圈加2分及原生计分板。用awardScoreOnce与flight.throwerName稳定身份计分，别删除名字后改未知。collision底部0且原点对称，偏移传createObject。审查启用才首次发球，恢复不重发，不加换色切换或旧示例。":System.getProperty("mineagent.conversationAgentScenario","").equals("basketball_retry")?"@工具助手 新建修正后的完整篮球HOT包：前包球与篮圈collision的y_min非0、边沿collision偏离原点，全部无效，不要复用。所有碰撞盒必须原点对称、底部0，圆周偏移交给createObject。我要0.4格高精度球，40Tick蓄力投掷反弹拾回；3格高空心可碰撞篮圈、篮板立柱。先查建模能力，计分用新awardScoreOnce，真实向下入圈加2分，每次投掷一次；原生计分板。生成后审查启用才首次发球，恢复不重发。不额外做换色版，不用旧示例或命令模拟。":"@工具助手 我要完整篮球玩法：给我一个圆润橙色带黑线的篮球和附近的篮球架。请自主建模生成独立HOT包，球直径约0.4格、40Tick满蓄力，松手投掷原件、能反弹并拾回。篮框在离地3格，有可穿过的空洞与可碰撞边沿、篮板和立柱。真实从上往下投入才加2分，同一次投掷只计一次，投偏或从下往上穿过不计分；显示原生计分板。全部由你生成脚本，不用旧篮球示例，不用命令模拟。先检查可用建模能力，生成后等我审查启用，首次创建才发一球，恢复不重发。";if(prompt.length()>256)throw new IllegalStateException("BASKETBALL_PROMPT_LENGTH");Files.writeString(root.resolve("prompt.txt"),prompt);mc.player.connection.sendChat(prompt);}
            if(ConversationRuntimeItemSmokeServer.itemReady&&mc.screen!=null)mc.setScreen(null);
            int request=ConversationBasketballSmokeServer.request;if(request>=1&&request<=3&&request!=seen&&!mc.player.getMainHandItem().isEmpty()){if(++wait<20)return;seen=request;holding=1;mc.options.keyUse.setDown(true);mc.gameMode.useItem(mc.player,net.minecraft.world.InteractionHand.MAIN_HAND);wait=0;}
            if(holding>0){mc.options.keyUse.setDown(true);holding++;int target=seen==1?8:seen==2?36:20;if(ConversationBasketballSmokeServer.observedUseTicks>=target){mc.options.keyUse.setDown(false);mc.gameMode.releaseUsingItem(mc.player);holding=0;}}
            if(ConversationBasketballSmokeServer.capture&&!captured&&++captureWait>50&&!mc.player.getMainHandItem().isEmpty()){var drawn=dev.mineagent.runtime.neoforge.client.objects.RuntimeObjectRenderer.drawn;if(drawn.size()<7||dev.mineagent.runtime.neoforge.client.objects.RuntimeThrownItemRenderer.rendered<1)throw new IllegalStateException("BASKETBALL_CLIENT_MODELS_NOT_RENDERED");var board=mc.level.getScoreboard();var o=board.getDisplayObjective(DisplaySlot.SIDEBAR);if(o==null)return;int sum=0;for(var score:board.listPlayerScores(o))sum+=score.value();if(sum!=4)return;captured=true;captureBusy=true;net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),img->{try(img){img.writeToFile(root.resolve("basketball-scoreboard.png"));}catch(Exception e){ConversationRuntimeItemSmokeServer.failure=e.toString();}finally{captureBusy=false;}});Files.writeString(root.resolve("basketball-client-score.json"),new com.google.gson.Gson().toJson(Map.of("objective",o.getName(),"score",sum,"nativeSidebar",true,"worldModelsDrawn",drawn.size(),"flightRenderSubmissions",dev.mineagent.runtime.neoforge.client.objects.RuntimeThrownItemRenderer.rendered)));}
            if(captured&&!captureBusy)ConversationRuntimeItemSmokeServer.clientCaptured=true;
            if(ConversationRuntimeItemSmokeServer.verified){mc.options.keyUse.setDown(false);Files.writeString(root.resolve("client.json"),new com.google.gson.Gson().toJson(Map.of("nativeUseAndRelease",true,"systemInputInjected",false,"keyMappingReleased",!mc.options.keyUse.isDown(),"nativeScoreboardReadback",true)));done=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");dev.mineagent.runtime.neoforge.client.cinematic.CinematicCaptureClient.finish();}
        }catch(Exception e){mc.options.keyUse.setDown(false);done=true;Files.writeString(root.resolve("client-failure.json"),new com.google.gson.Gson().toJson(Map.of("error",e.toString(),"request",seen)));dev.mineagent.runtime.neoforge.client.cinematic.CinematicCaptureClient.finish();}
    }
}
