package dev.mineagent.runtime.neoforge.client.chat;
import dev.mineagent.runtime.neoforge.ui.ConversationWatchSmokeServer;
import dev.mineagent.runtime.neoforge.client.webui.*;
import dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox;
import dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen;
import net.minecraft.client.Minecraft;
import com.google.gson.*;
import java.nio.file.*;import java.util.*;
public final class ConversationWatchSmokeClient {
 private static JsonObject probe;public static void accept(JsonObject value){probe=value;}
 private static int phase,ticks,wait,samples;private static boolean done,busy;private static String view="",first="";
 public static void tick()throws Exception{if(done)return;var mc=Minecraft.getInstance();var host=WebGuiHostAdapter.INSTANCE;var root=Files.createDirectories(mc.gameDirectory.toPath().resolve("watch-smoke"));ticks++;try{
  if(!ConversationWatchSmokeServer.failure.isEmpty())throw new IllegalStateException(ConversationWatchSmokeServer.failure);if(ticks>25000)throw new IllegalStateException("WATCH_TIMEOUT_"+phase);if(mc.player==null||!ConversationWatchSmokeServer.ready)return;
  if(phase==0){String fp=PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","");if(fp.isEmpty()||new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fp)!=dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){if(mc.screen instanceof ControlCenterScreen s)for(var child:List.copyOf(s.children()))if(child instanceof net.minecraft.client.gui.components.Button b&&b.active&&b.getMessage().getString().contains("信任此服务器"))b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));return;}if(++wait==1)mc.player.connection.sendCommand("ai accept");if(wait<40)return;mc.setScreen(null);if(!ConversationWatchSmokeServer.saved())mc.player.connection.sendChat("@读数助手 帮我创建并启用一个右键打开独立半透明网页窗口的读数台，放在我身边。网页每秒实时显示我的X坐标和以我为中心半径2格的石头总数，不用反复问模型。为便于辨认，分别显示为 X=保留2位小数、STONE=整数。使用真实游戏读数；窗口关闭停止读取，不要聊天冒充网页。");phase=1;}
  if(phase==1&&ConversationWatchSmokeServer.generated&&mc.level.getEntity(ConversationWatchSmokeServer.object)!=null){var e=mc.level.getEntity(ConversationWatchSmokeServer.object);mc.gameMode.interact(mc.player,e,new net.minecraft.world.phys.EntityHitResult(e,e.position().add(0,.5,0)),net.minecraft.world.InteractionHand.MAIN_HAND);phase=2;}
  if(phase==2&&PackageContentClient.worldViews().size()==1){view=PackageContentClient.worldViews().getFirst();if(PackageContentClient.session(view)!=null)phase=3;}
  if(phase>=6&&host.ready()&&UiClientSessions.current()!=null&&ticks%10==0){String js="window.mineagentQuery({request:JSON.stringify({channel:'conversationAgentProbe',list:[...document.querySelectorAll('#package-catalog-list button')].map(b=>b.textContent),detail:[...document.querySelectorAll('#package-catalog-detail button')].map(b=>b.textContent),status:document.querySelector('#package-catalog-status')?.textContent||''}),persistent:false,onSuccess(){},onFailure(){}});";host.browser().executeJavaScript(js,host.browser().getURL(),0);}
  if(phase==6&&host.ready()&&UiClientSessions.current()!=null){host.browser().executeJavaScript("document.querySelector('#open-package-catalog').click();",host.browser().getURL(),0);phase=7;}
  if(phase==7&&probe!=null&&probe.getAsJsonArray("list").toString().contains("当前包与真实版本")){host.browser().executeJavaScript("[...document.querySelectorAll('#package-catalog-list button')].find(b=>b.textContent==='当前包与真实版本').click();",host.browser().getURL(),0);phase=8;}
  if(phase==8&&probe!=null&&probe.getAsJsonArray("detail").toString().contains("确认启用此版本")){ConversationWatchSmokeServer.historyStarted=true;host.browser().executeJavaScript("[...document.querySelectorAll('#package-catalog-detail button')].find(b=>b.textContent==='确认启用此版本').click();",host.browser().getURL(),0);phase=9;}
  if(phase>=7&&probe!=null&&probe.getAsJsonArray("detail").toString().contains("结果待核对"))throw new IllegalStateException("HISTORY_BUTTON_FAILED:"+probe);
  if(phase>=6&&++wait>800)throw new IllegalStateException("HISTORY_UI_TIMEOUT:"+phase+":"+probe);
  if(phase==9&&ConversationWatchSmokeServer.historyVerified){Files.writeString(root.resolve("history-client.json"),new Gson().toJson(Map.of("status","HISTORICAL_ENABLE_BUTTON_VERIFIED","probe",probe)));host.close();done=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");mc.stop();}
  if((phase==3||phase==4)&&!busy&&ticks%25==0){busy=true;PackagePageAgent.inspectManagedView(view).whenComplete((value,error)->mc.execute(()->{try{if(error!=null)throw new IllegalStateException(error);var data=JsonParser.parseString(value).getAsJsonObject();String text=data.get("visibleText").getAsString().replaceAll("\\s+","");Files.writeString(root.resolve("sample-"+(samples++)+".json"),value);String x=String.format(java.util.Locale.ROOT,"X=%.2f",ConversationWatchSmokeServer.expectedX),stone="STONE="+ConversationWatchSmokeServer.expectedStone;if(!text.contains(x)||!text.contains(stone)){busy=false;return;}if(phase==3){first=text;ConversationWatchSmokeServer.change=true;phase=4;}else if(ConversationWatchSmokeServer.changed&&!text.equals(first)){phase=5;PackagePageAgent.captureManagedView(view).whenComplete((shot,failure)->mc.execute(()->{try{if(failure!=null)throw new IllegalStateException(failure);Files.write(root.resolve("live-window.png"),shot.png());Files.writeString(root.resolve("client.json"),new Gson().toJson(Map.of("status","REAL_GENERATED_LIVE_WEBUI_VERIFIED","savedArtifact",ConversationWatchSmokeServer.saved(),"samples",samples,"before",first,"after",text,"actualX",ConversationWatchSmokeServer.expectedX,"actualStone",ConversationWatchSmokeServer.expectedStone,"modelNotUsedForRefresh",true)));phase=6;wait=0;host.open();}catch(Exception e){fail(root,e);}finally{busy=false;}}));return;}busy=false;}catch(Exception e){fail(root,e);}}));}
 }catch(Exception e){fail(root,e);}}
 private static void fail(Path root,Exception e){try{Files.writeString(root.resolve("client-failure.json"),new Gson().toJson(Map.of("phase",phase,"error",e.toString())));}catch(Exception ignored){}done=true;busy=false;WebGuiHostAdapter.INSTANCE.close();Minecraft.getInstance().stop();}
}
