package dev.mineagent.runtime.neoforge.client.chat;
import dev.mineagent.runtime.neoforge.ui.ConversationFeedbackSmokeServer;
import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.components.Button;
import net.minecraft.client.input.KeyEvent;
import java.nio.file.*;import java.util.*;
final class ConversationFeedbackSmokeClient {
 private static int ticks,sent,hostApprovals,catalogPhase,catalogOffset;private static boolean done,copyReceived;private static String interruptCommand="";private static final Set<UUID> approved=new HashSet<>();
 static void chat(net.minecraft.network.chat.Component message){if(!ConversationFeedbackSmokeServer.active())return;message.visit((style,text)->{if(text.contains("打断并发送")&&style.getClickEvent() instanceof net.minecraft.network.chat.ClickEvent.RunCommand run)interruptCommand=run.command();if(style.getClickEvent() instanceof net.minecraft.network.chat.ClickEvent.CopyToClipboard copy&&copy.value().equals("/time query daytime"))copyReceived=true;return Optional.empty();},net.minecraft.network.chat.Style.EMPTY);}
 static void tick()throws Exception{if(done)return;var mc=Minecraft.getInstance();ticks++;Path root=Files.createDirectories(mc.gameDirectory.toPath().resolve("feedback-smoke"));try{
  if(!ConversationFeedbackSmokeServer.failure.isEmpty())throw new IllegalStateException(ConversationFeedbackSmokeServer.failure);if(ticks>18000)throw new IllegalStateException("FEEDBACK_CLIENT_TIMEOUT");if(mc.player==null||!ConversationFeedbackSmokeServer.ready)return;
  if(ConversationFeedbackSmokeServer.interrupt()){
   if(sent==0){mc.player.connection.sendCommand("ai accept");mc.player.connection.sendChat("@工具助手 请用中文写一篇不少于800字的古典城堡建筑建议，只聊天，不使用任何工具。");sent=10;}
   if(sent==10&&Files.exists(mc.gameDirectory.toPath().resolve("real-provider-audit/1-started.json"))){mc.player.connection.sendChat("@工具助手 取消上一条长文，现在只回答：中断成功。不要调用任何工具。");sent=11;}
   if(sent==11&&!interruptCommand.isEmpty()){mc.player.connection.sendCommand(interruptCommand.substring(1));sent=12;}
   if(sent==12&&ConversationFeedbackSmokeServer.verified>=2){Files.writeString(root.resolve("client.json"),new com.google.gson.Gson().toJson(Map.of("status","NATIVE_INTERRUPT_BUTTON_COMMAND_VERIFIED","buttonCommand",interruptCommand,"systemInputInjected",false)));done=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");dev.mineagent.runtime.neoforge.client.cinematic.CinematicCaptureClient.finish();}return;
  }
  var hostPending=dev.mineagent.runtime.neoforge.client.host.ClientHostCommands.smokePending();if(!hostPending.isEmpty()){if(ConversationFeedbackSmokeServer.remaining())throw new IllegalStateException("HOST_MUST_NOT_REPEAT");String script=hostPending.get("script").toString().strip();if(!script.equals("print('feedback-host-ok')")&&!script.equals("print(\"feedback-host-ok\")"))throw new IllegalStateException("HOST_FIXTURE_UNEXPECTED_SCRIPT_REVIEW_REQUIRED");UUID op=UUID.fromString(hostPending.get("operation").toString());if(approved.add(op)){hostApprovals++;mc.player.connection.sendCommand(hostPending.get("approveCommand").toString());}}
  if(sent==0&&ConversationFeedbackSmokeServer.zero()){mc.player.connection.sendCommand("ai accept");sent=2;}
  if(sent==0){mc.player.connection.sendCommand("ai accept");mc.player.connection.sendChat(ConversationFeedbackSmokeServer.remaining()?"@工具助手 请永久记住我的建筑材料偏好是石英。把你自己的身体传送到我身边，开始跟随我并奔跑，核对实际结果。不要执行任何电脑命令。":"@工具助手 本轮重新测试：请永久记住我的建筑材料偏好是石英。把你自己的身体传送到我身边，开始跟随我，开启奔跑。通过专用Python仅执行 print('feedback-host-ok')，不要执行其它电脑命令。请真实调用并核对。");mc.setScreen(new net.minecraft.client.gui.screens.ChatScreen("",false));sent=1;}
  if(sent==1&&ConversationFeedbackSmokeServer.verified>=1){mc.player.connection.sendChat("@工具助手 取消跟随并停下；拿出你背包里的苹果，只丢一个，然后核对。读取刚保存的长期建筑偏好并告诉我；以后说话改成青色#55FFFF，发一个可以点击复制 /time query daytime 的消息按钮。不要执行该游戏命令。");sent=2;}
  if(sent==2&&ConversationFeedbackSmokeServer.verified>=2){if(ConversationFeedbackSmokeServer.zero()&&!catalog(mc,root))return;var body=mc.level.getPlayerByUUID(ConversationFeedbackSmokeServer.agent);if(!copyReceived)throw new IllegalStateException("NATIVE_COPY_BUTTON_NOT_RECEIVED");if(body==null||!body.getName().getString().equals("工具助手"))throw new IllegalStateException("AI_NATIVE_NAME_NOT_PROJECTED");Files.writeString(root.resolve("client.json"),new com.google.gson.Gson().toJson(Map.of("status","FEEDBACK_NATIVE_CLIENT_VERIFIED","name",body.getName().getString(),"nativeCopyButtonReceived",copyReceived,"hostApprovals",hostApprovals,"priorScreen","ChatScreen","zeroProviderNativeOnly",ConversationFeedbackSmokeServer.zero())));done=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");dev.mineagent.runtime.neoforge.client.cinematic.CinematicCaptureClient.finish();}
 }catch(Exception e){done=true;Files.writeString(root.resolve("client-failure.json"),new com.google.gson.Gson().toJson(Map.of("error",e.toString(),"sent",sent,"hostApprovals",hostApprovals)));dev.mineagent.runtime.neoforge.client.cinematic.CinematicCaptureClient.finish();}}
 private static boolean catalog(Minecraft mc,Path root)throws Exception{
  var snapshot=dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox.snapshot().values();
  if(catalogPhase==0){mc.setScreen(new net.minecraft.client.gui.screens.ChatScreen("@",false));catalogPhase=1;return false;}
  if(catalogPhase==1){if(NativeAgentChat.names().size()!=70)return false;var completion=dev.mineagent.runtime.core.interaction.AgentMention.complete("@同伴69",5,NativeAgentChat.names()).orElseThrow();if(!completion.values().contains("@同伴69 "))throw new IllegalStateException("CATALOG_LAST_MENTION_ABSENT");mc.setScreen(dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen.create(null,dev.mineagent.runtime.api.config.PanelSection.AGENTS));catalogPhase=2;return false;}
  int offset=Integer.parseInt(snapshot.getOrDefault("agent.offset","-1"));if(offset!=catalogOffset)return false;
  if(catalogPhase==2&&offset==64){if(!snapshot.get("agent.count").equals("6")||!snapshot.get("agent.total").equals("70"))throw new IllegalStateException("CATALOG_FINAL_PAGE");catalogPhase=3;}
  if(catalogPhase==3&&offset==0){Files.writeString(root.resolve("catalog.json"),new com.google.gson.Gson().toJson(Map.of("status","NATIVE_SEVENTY_AGENTS_PAGES_AND_NAMES_VERIFIED","names",NativeAgentChat.names(),"lastOffset",64,"returnedToStart",true)));return true;}
  String label=catalogPhase==2?"下一组 AI":"上一组 AI";if(!(mc.screen instanceof dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen screen))throw new IllegalStateException("CATALOG_SCREEN");
  for(var child:List.copyOf(screen.children()))if(child instanceof Button b&&b.active&&b.getMessage().getString().equals(label)){catalogOffset=offset+(catalogPhase==2?8:-8);b.onPress(new KeyEvent(257,0,0));return false;}return false;
 }
}
