package dev.mineagent.runtime.neoforge.client.chat;
import dev.mineagent.runtime.neoforge.ui.ConversationRecoverySmokeServer;
import dev.mineagent.runtime.neoforge.client.webui.*;
import dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen;
import dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox;
import net.minecraft.client.Minecraft;
import com.google.gson.*;
import java.nio.file.*;import java.util.*;
/** Actual F2 button -> bridge -> new real DeepSeek request; does not call send itself. */
public final class ConversationRecoverySmokeClient {
 private static int ticks,phase,wait,round=1;private static boolean done;private static JsonObject probe;private static UUID previous;
 public static void accept(JsonObject v){probe=v;}
 private static void script(String s){var host=WebGuiHostAdapter.INSTANCE;host.browser().executeJavaScript("(()=>{"+s+"})();",host.browser().getURL(),0);}
 private static void require(boolean v,String code){if(!v)throw new IllegalStateException(code);}
 public static void tick()throws Exception{if(done)return;var mc=Minecraft.getInstance();var host=WebGuiHostAdapter.INSTANCE;ticks++;Path root=Files.createDirectories(mc.gameDirectory.toPath().resolve("recovery-smoke"));try{
  require(ConversationRecoverySmokeServer.failure.isEmpty(),ConversationRecoverySmokeServer.failure);require(ticks<15000,"RECOVERY_TIMEOUT_"+phase);if(mc.player==null||!ConversationRecoverySmokeServer.ready)return;
  if(ticks%100==0)Files.writeString(root.resolve("progress.json"),new Gson().toJson(Map.of("phase",phase,"round",round,"verified",ConversationRecoverySmokeServer.verified,"probe",probe==null?new JsonObject():probe)));
  if(phase==0){String fp=PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","");if(fp.isEmpty()||new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fp)!=dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){if(mc.screen instanceof ControlCenterScreen s)for(var child:List.copyOf(s.children()))if(child instanceof net.minecraft.client.gui.components.Button b&&b.active&&b.getMessage().getString().contains("信任此服务器"))b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));return;}if(++wait==1)mc.player.connection.sendCommand("ai accept");if(wait<40)return;mc.setScreen(null);host.open();phase=1;}
  if(phase>=1&&host.ready()&&UiClientSessions.current()!=null&&ticks%10==0)script("window.mineagentQuery({request:JSON.stringify({channel:'conversationAgentProbe',agents:[...document.querySelectorAll('#chat-agent option')].map(o=>o.value),conversations:[...document.querySelectorAll('#conversation-list option')].map(o=>o.value),selected:document.querySelector('#conversation-list')?.value??'',recoveries:[...document.querySelectorAll('[data-recovery-message]')].map(b=>({id:b.dataset.recoveryMessage,disabled:b.disabled,text:b.textContent})),draft:document.querySelector('#chat-draft')?.value??'',status:document.querySelector('#conversation-status')?.textContent??''}),persistent:false,onSuccess(){},onFailure(){}});");
  if(phase==1&&probe!=null&&probe.getAsJsonArray("agents").toString().contains(ConversationRecoverySmokeServer.agent.toString())){script("const s=document.querySelector('#chat-agent');s.value='"+ConversationRecoverySmokeServer.agent+"';s.dispatchEvent(new Event('change'));");phase=2;}
  if(phase==2&&probe.getAsJsonArray("conversations").toString().contains(ConversationRecoverySmokeServer.conversation.toString())){script("const s=document.querySelector('#conversation-list');s.value='"+ConversationRecoverySmokeServer.conversation+"';s.dispatchEvent(new Event('change'));");phase=3;}
  if(phase==3&&probe.get("selected").getAsString().equals(ConversationRecoverySmokeServer.conversation.toString())&&probe.getAsJsonArray("recoveries").size()==1){Files.writeString(root.resolve("button-"+round+".json"),probe.toString());script("const d=document.querySelector('#chat-draft');d.value='保留这条未发送的草稿';d.dispatchEvent(new Event('input',{bubbles:true}));const b=document.querySelector('[data-recovery-message]');b.scrollIntoView({block:'center'});b.click();b.click();");phase=4;}
  if(phase==4&&ConversationRecoverySmokeServer.verified>=round&&probe.getAsJsonArray("recoveries").isEmpty()){require(probe.get("draft").getAsString().equals("保留这条未发送的草稿"),"RECOVERY_DRAFT_LOST");Files.writeString(root.resolve("web-"+round+".json"),probe.toString());if(round==1){previous=ConversationRecoverySmokeServer.conversation;ConversationRecoverySmokeServer.next=true;round=2;phase=5;}else{Files.writeString(root.resolve("client.json"),new Gson().toJson(Map.of("status","REAL_F2_UNKNOWN_AND_CONTEXT_RECOVERY_VERIFIED","doubleClickReservedOneRequest",true,"draftPreserved",true,"osInputInjected",false)));done=true;host.close();dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");mc.stop();}}
  if(phase==5&&!previous.equals(ConversationRecoverySmokeServer.conversation)){script("const s=document.querySelector('#conversation-list');s.value='';s.dispatchEvent(new Event('change'));document.querySelector('#conversation-more').open=true;[...document.querySelectorAll('#conversation-manager button')].find(b=>b.textContent==='搜索').click();");phase=2;}
 }catch(Exception e){done=true;Files.writeString(root.resolve("client-failure.json"),new Gson().toJson(Map.of("error",e.toString(),"phase",phase,"probe",probe==null?new JsonObject():probe)));host.close();mc.stop();}}
}
