package dev.mineagent.runtime.neoforge.client.chat;
import dev.mineagent.runtime.neoforge.ui.ConversationCreatureSmokeServer;
import dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox;
import dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen;
import net.minecraft.client.Minecraft;
import java.nio.file.*;import java.util.*;
public final class ConversationCreatureSmokeClient {
 private static int ticks,wait,ridingTicks;private static boolean sent,done,merchant,captured,busy;
 public static void tick()throws Exception{if(done)return;var mc=Minecraft.getInstance();ticks++;var root=Files.createDirectories(mc.gameDirectory.toPath().resolve("creature-smoke"));try{
  if(!ConversationCreatureSmokeServer.failure.isEmpty())throw new IllegalStateException(ConversationCreatureSmokeServer.failure);if(ticks>22000)throw new IllegalStateException("CREATURE_CLIENT_TIMEOUT");if(mc.player==null||!ConversationCreatureSmokeServer.ready)return;
  if(!sent){String fp=PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","");if(fp.isEmpty()||new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fp)!=dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){if(mc.screen instanceof ControlCenterScreen s)for(var child:List.copyOf(s.children()))if(child instanceof net.minecraft.client.gui.components.Button b&&b.active&&b.getMessage().getString().contains("信任此服务器"))b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));return;}if(++wait==1)mc.player.connection.sendCommand("ai accept");if(wait<40)return;mc.setScreen(null);org.lwjgl.glfw.GLFW.glfwFocusWindow(mc.getWindow().handle());if(!ConversationCreatureSmokeServer.saved())mc.player.connection.sendChat("@生物助手 创建并在附近各生成一只新的友好星球伙伴、中立守卫、敌对小怪。星球伙伴用球形自定义模型，能右键用1绿宝石换2苹果，吃附近丢下的1金锭吐出1石英，靠近提示欢迎，吃小麦繁殖、可骑乘、听从跟随战斗巡逻命令。守卫和小怪用简单自定义模型。真实执行并读回，不用原版生物冒充。");sent=true;ConversationCreatureSmokeServer.clientReady=true;}
  if(mc.screen instanceof net.minecraft.client.gui.screens.inventory.MerchantScreen)merchant=true;
  if(ConversationCreatureSmokeServer.stage==8){mc.setScreen(null);mc.options.keyUp.setDown(++ridingTicks<=12);}else mc.options.keyUp.setDown(false);
  if(ConversationCreatureSmokeServer.mainEntity!=null&&mc.level.getEntity(ConversationCreatureSmokeServer.mainEntity) instanceof dev.mineagent.runtime.neoforge.content.RuntimeCreatureEntity e&&ConversationCreatureSmokeServer.stage<2){var delta=e.getEyePosition().subtract(mc.player.getEyePosition());mc.player.setYRot((float)Math.toDegrees(Math.atan2(-delta.x,delta.z)));mc.player.setXRot((float)-Math.toDegrees(Math.atan2(delta.y,Math.sqrt(delta.x*delta.x+delta.z*delta.z))));}
  if(ConversationCreatureSmokeServer.stage>=1&&!captured&&dev.mineagent.runtime.neoforge.client.objects.RuntimeCreatureRenderer.drawn.getOrDefault(ConversationCreatureSmokeServer.mainEntity,0)>5){captured=true;busy=true;net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),img->{try(img){img.writeToFile(root.resolve("custom-creature.png"));}catch(Exception e){ConversationCreatureSmokeServer.failure=e.toString();}finally{busy=false;}});}
  if(ConversationCreatureSmokeServer.complete&&!busy){if(!merchant||!captured)throw new IllegalStateException("CREATURE_NATIVE_RENDER_OR_MENU_MISSING");Files.writeString(root.resolve("client.json"),new com.google.gson.Gson().toJson(Map.of("status","CREATURE_NATIVE_CLIENT_VERIFIED","merchantScreen",merchant,"rendered",captured,"nativeRidingInput",true,"osInputInjected",false)));done=true;mc.options.keyUp.setDown(false);dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");mc.stop();}
 }catch(Exception e){done=true;mc.options.keyUp.setDown(false);Files.writeString(root.resolve("client-failure.json"),new com.google.gson.Gson().toJson(Map.of("error",e.toString(),"stage",ConversationCreatureSmokeServer.stage,"merchant",merchant,"captured",captured)));mc.stop();}}
}
