package dev.mineagent.runtime.neoforge.client.chat;
import dev.mineagent.runtime.neoforge.ui.ConversationThinkingSmokeServer;
import dev.mineagent.runtime.neoforge.client.webui.*;
import dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen;
import dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox;
import net.minecraft.client.Minecraft;
import com.google.gson.*;
import java.nio.file.*;
import java.util.*;
public final class ConversationThinkingSmokeClient {
 private static int phase,ticks,wait,parts;private static boolean done,busy,streaming,banner;private static JsonObject probe;private static final StringBuilder nativeThinking=new StringBuilder(),nativeAnswer=new StringBuilder();
 public static void accept(JsonObject v){probe=v;}
 public static void chat(net.minecraft.network.chat.Component message){String s=message.getString();if(s.equals("[思考助手]思考中")||s.equals("[思考助手] 思考中"))banner=true;String prefix="[思考助手][思考]";if(s.startsWith(prefix)){String part=s.substring(prefix.length());if(part.length()>240||!part.isEmpty()&&(Character.isHighSurrogate(part.charAt(part.length()-1))||Character.isLowSurrogate(part.charAt(0))))ConversationThinkingSmokeServer.failure="THINKING_NATIVE_SEGMENT";nativeThinking.append(part);parts++;if(!ConversationThinkingSmokeServer.complete)streaming=true;}else if(s.startsWith("[思考助手] ")&&!s.contains("正在处理")&&!s.contains("本次未完成"))nativeAnswer.append(s.substring("[思考助手] ".length()));}
 private static void require(boolean v,String code){if(!v)throw new IllegalStateException(code);}
 private static void script(String s){var host=WebGuiHostAdapter.INSTANCE;host.browser().executeJavaScript("(()=>{"+s+"})();",host.browser().getURL(),0);}
 private static void capture(Path root,String name){busy=true;net.minecraft.client.Screenshot.takeScreenshot(Minecraft.getInstance().getMainRenderTarget(),image->{try(image){image.writeToFile(root.resolve(name+".png"));}catch(Exception e){ConversationThinkingSmokeServer.failure="THINKING_SCREENSHOT";}finally{busy=false;}});}
 public static void tick()throws Exception{if(done)return;var mc=Minecraft.getInstance();var host=WebGuiHostAdapter.INSTANCE;Path root=Files.createDirectories(mc.gameDirectory.toPath().resolve("thinking-smoke"));ticks++;
  try{if(ticks%100==0)Files.writeString(root.resolve("progress.json"),new Gson().toJson(Map.of("phase",phase,"parts",parts,"complete",ConversationThinkingSmokeServer.complete,"probe",probe==null?new JsonObject():probe,"screen",mc.screen==null?"none":mc.screen.getClass().getSimpleName())));
   require(ConversationThinkingSmokeServer.failure.isEmpty(),ConversationThinkingSmokeServer.failure);require(ticks<11000,"THINKING_TIMEOUT_"+phase);if(mc.player==null||!ConversationThinkingSmokeServer.ready||busy)return;
   if(phase==0){String fp=PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","");if(fp.isEmpty()||new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fp)!=dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){if(mc.screen instanceof ControlCenterScreen s)for(var child:List.copyOf(s.children()))if(child instanceof net.minecraft.client.gui.components.Button b&&b.active&&b.getMessage().getString().contains("信任此服务器"))b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));return;}if(++wait==1)mc.player.connection.sendCommand("ai accept");if(wait<40)return;mc.setScreen(null);if(ConversationThinkingSmokeServer.saved()){phase=3;wait=0;}else{mc.player.connection.sendChat("@思考助手 只聊天，不调用任何工具、不操作游戏或电脑。从1到30的整数中选5个不同的数，任意两个数的差至少为3，且总和能被7整除，共有多少种选法？请认真计算，最后给出整数答案和简短校验。");phase=1;wait=0;}}
   if(phase==1&&ConversationThinkingSmokeServer.complete&&nativeThinking.toString().equals(ConversationThinkingSmokeServer.thinking)&&nativeAnswer.toString().equals(ConversationThinkingSmokeServer.answer)){require(streaming&&ConversationThinkingSmokeServer.sawStreaming&&!banner,"THINKING_NATIVE_STREAM_OR_BANNER");Files.writeString(root.resolve("native.json"),new Gson().toJson(Map.of("parts",parts,"streaming",streaming,"standaloneBanner",banner,"thinkingMatchesStored",true,"answerMatchesStored",true)));mc.setScreen(new net.minecraft.client.gui.screens.ChatScreen("",false));phase=2;}
   if(phase==2){if(++wait<10)return;capture(root,"native-thinking");phase=3;wait=0;}
   if(phase==3&&ConversationThinkingSmokeServer.complete){host.open();phase=4;}
   if(phase>=4&&host.ready()&&UiClientSessions.current()!=null&&ticks%10==0){script("Promise.all([...document.querySelectorAll('.conversation-thinking')].map(async d=>{const text=d.querySelector('pre').textContent,digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text));return {open:d.open,chars:text.length,sha256:[...new Uint8Array(digest)].map(x=>x.toString(16).padStart(2,'0')).join(''),bodyVisible:d.querySelector('pre').getBoundingClientRect().height>0,moreHidden:d.querySelector('button').hidden};})).then(thinking=>window.mineagentQuery({request:JSON.stringify({channel:'conversationAgentProbe',agents:[...document.querySelectorAll('#chat-agent option')].map(o=>o.value),conversations:[...document.querySelectorAll('#conversation-list option')].map(o=>o.value),selected:document.querySelector('#conversation-list')?.value??'',thinking}),persistent:false,onSuccess(){},onFailure(){}}));");}
   if(phase==4&&probe!=null&&probe.getAsJsonArray("agents").toString().contains(ConversationThinkingSmokeServer.agent.toString())){script("const s=document.querySelector('#chat-agent');s.value='"+ConversationThinkingSmokeServer.agent+"';s.dispatchEvent(new Event('change'));");phase=5;}
   if(phase==5&&probe.getAsJsonArray("conversations").toString().contains(ConversationThinkingSmokeServer.conversation.toString())){script("const s=document.querySelector('#conversation-list');s.value='"+ConversationThinkingSmokeServer.conversation+"';s.dispatchEvent(new Event('change'));");phase=6;}
   if(phase==6&&probe.getAsJsonArray("thinking").size()==1){var d=probe.getAsJsonArray("thinking").get(0).getAsJsonObject();require(!d.get("open").getAsBoolean()&&!d.get("bodyVisible").getAsBoolean(),"THINKING_NOT_COLLAPSED");Files.writeString(root.resolve("web-collapsed.json"),probe.toString());script("document.querySelector('.conversation-thinking').scrollIntoView({block:'start'});");phase=60;wait=0;}
   if(phase==60&&++wait>=10){capture(root,"web-collapsed");phase=7;wait=0;}
   if(phase==7&&!busy){script("const d=document.querySelector('.conversation-thinking');d.querySelector('summary').click();d.scrollIntoView({block:'start'});");phase=8;}
   if(phase==8&&probe.getAsJsonArray("thinking").size()==1){var d=probe.getAsJsonArray("thinking").get(0).getAsJsonObject();if(d.get("open").getAsBoolean()&&d.get("bodyVisible").getAsBoolean()&&d.get("chars").getAsInt()==ConversationThinkingSmokeServer.thinking.length()&&d.get("sha256").getAsString().equals(dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer.sha256(ConversationThinkingSmokeServer.thinking))){Files.writeString(root.resolve("web-expanded.json"),probe.toString());script("document.querySelector('.conversation-thinking').scrollIntoView({block:'start'});");phase=80;wait=0;}else if(d.get("open").getAsBoolean()&&!d.get("moreHidden").getAsBoolean()&&ticks%30==0)script("const b=document.querySelector('.conversation-thinking button');if(b&&!b.disabled)b.click();");}
   if(phase==80&&++wait>=10){capture(root,"web-expanded");phase=9;}
   if(phase==9&&!busy){Files.writeString(root.resolve("client.json"),new Gson().toJson(Map.of("status",ConversationThinkingSmokeServer.saved()?"SAVED_REAL_THINKING_WEB_VERIFIED":"REAL_THINKING_NATIVE_WEB_VERIFIED","nativeStreamMatchesDatabase",!ConversationThinkingSmokeServer.saved(),"standaloneBannerAbsent",true,"defaultCollapsed",true,"expandedMatchesDatabase",true,"systemInputInjected",false)));done=true;host.close();dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");mc.stop();}
  }catch(Exception e){done=true;Files.writeString(root.resolve("failure.json"),new Gson().toJson(Map.of("error",e.toString(),"phase",phase,"probe",probe==null?new JsonObject():probe)));host.close();mc.stop();}
 }
}
