package dev.mineagent.runtime.neoforge.client.chat;
import dev.mineagent.runtime.neoforge.ui.FeedbackChatSmokeServer;import dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen;import dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox;import net.minecraft.client.Minecraft;import java.nio.file.*;import java.util.*;
public final class FeedbackChatSmokeClient {
 private static int ticks,phase,wait;private static boolean done,cancelSent,staleSent;public static boolean buttons,expired;
 public static void message(String text){if(text.contains("[打断并发送这条消息]")&&text.contains("[取消发送这条消息]"))buttons=true;if(text.contains("CONVERSATION_BUTTON_EXPIRED"))expired=true;}
 public static void tick()throws Exception{if(done)return;var mc=Minecraft.getInstance();ticks++;Path root=Files.createDirectories(mc.gameDirectory.toPath().resolve("chat-lifecycle-smoke"));try{if(!FeedbackChatSmokeServer.failure.isEmpty())throw new IllegalStateException(FeedbackChatSmokeServer.failure);if(ticks>18000)throw new IllegalStateException("CHAT_LIFECYCLE_TIMEOUT_"+phase);if(mc.player==null||!FeedbackChatSmokeServer.ready)return;
 if(phase==0){String fp=PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","");if(fp.isEmpty()||new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fp)!=dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){if(mc.screen instanceof ControlCenterScreen s)for(var c:List.copyOf(s.children()))if(c instanceof net.minecraft.client.gui.components.Button b&&b.active&&b.getMessage().getString().contains("信任此服务器"))b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));return;}if(++wait==1)mc.player.connection.sendCommand("ai accept");if(wait<40)return;mc.setScreen(null);mc.player.connection.sendCommand("ai default "+FeedbackChatSmokeServer.agent);mc.player.connection.sendCommand("ai thinking deep low "+FeedbackChatSmokeServer.agent);mc.player.connection.sendCommand("ai thinking see off");phase=1;wait=0;}
 if(phase==1&&++wait>20){if(NativeChatPreferencesClient.showThinking())throw new IllegalStateException("THINKING_SEE_COMMAND_NOT_APPLIED");FeedbackChatSmokeServer.clientReady=true;mc.player.connection.sendChat("FIRST_OLD_CONTEXT：仅本会话测试标记。不要记忆、不要调用工具，只回复FIRST_COMPLETE。");mc.player.connection.sendChat("CANCELLED_QUEUE_MARKER：这条待发送消息将被取消，不应提交。");mc.player.connection.sendChat("QUEUED_SENT_MARKER：不要调用工具，只回复QUEUED_COMPLETE。");phase=2;}
 if(phase==2&&FeedbackChatSmokeServer.cancelId!=null&&!cancelSent){cancelSent=true;mc.player.connection.sendCommand("ai cancel_send "+FeedbackChatSmokeServer.cancelId);}
 if(phase==2&&FeedbackChatSmokeServer.stage>=2&&!staleSent){staleSent=true;mc.player.connection.sendCommand("ai interrupt "+FeedbackChatSmokeServer.agent+" active:"+FeedbackChatSmokeServer.firstOperation);}
 if(phase==2&&FeedbackChatSmokeServer.stage==3){if(!buttons||!cancelSent||!staleSent)throw new IllegalStateException("NATIVE_QUEUE_BUTTONS_NOT_VERIFIED");mc.player.connection.sendCommand("ai chat delete");phase=3;}
 if(phase==3&&FeedbackChatSmokeServer.stage==4){mc.player.connection.sendCommand("ai thinking deep high "+FeedbackChatSmokeServer.agent);phase=4;wait=0;}
 if(phase==4&&++wait>20){mc.player.connection.sendChat("不要调用工具，只回复NEW_CONTEXT_OK。");phase=5;}
 if(phase==5&&FeedbackChatSmokeServer.complete){if(!expired)throw new IllegalStateException("OLD_INTERRUPT_BUTTON_NOT_REJECTED");Files.writeString(root.resolve("client.json"),"{\"status\":\"REAL_DEFAULT_CHAT_QUEUE_CANCEL_DELETE_COMMANDS_VERIFIED\",\"staleInterruptRejected\":true,\"thinkingHidden\":true}");done=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");mc.stop();}
 }catch(Exception e){done=true;Files.writeString(root.resolve("client-failure.json"),"{\"error\":\""+e.toString().replace("\\","/").replace("\"","'")+"\",\"phase\":"+phase+"}");mc.stop();}}
 private FeedbackChatSmokeClient(){}
}
