package dev.mineagent.runtime.neoforge.client.chat;
import dev.mineagent.runtime.neoforge.ui.PythonHostSmokeServer;
import dev.mineagent.runtime.neoforge.client.host.ClientHostCommands;
import dev.mineagent.runtime.neoforge.client.screen.ControlCenterScreen;
import dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox;
import net.minecraft.client.Minecraft;
import java.util.*;import java.nio.file.*;
/** Executes the actual client commands bound to local chat buttons, after an exact hash review file. */
public final class PythonHostSmokeClient {
 private static int ticks,wait,approved,negativeWait;private static boolean sent,done,screenshot,capturing;private static final Set<String> decisions=new HashSet<>();private static String oldApprove="",pendingOperation="";private static int pendingTicks;
 public static void tick()throws Exception{if(done)return;var mc=Minecraft.getInstance();ticks++;var root=Files.createDirectories(mc.gameDirectory.toPath().resolve("python-host-smoke"));try{
  if(!PythonHostSmokeServer.failure.isEmpty())throw new IllegalStateException(PythonHostSmokeServer.failure);if(ticks>18000)throw new IllegalStateException("PYTHON_HOST_TIMEOUT");if(mc.player==null||!PythonHostSmokeServer.ready)return;
  if(!sent){String fp=PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","");if(fp.isEmpty()||new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).status("local-integrated",fp)!=dev.mineagent.runtime.client.trust.TrustStatus.TRUSTED){if(mc.screen instanceof ControlCenterScreen s)for(var child:List.copyOf(s.children()))if(child instanceof net.minecraft.client.gui.components.Button b&&b.active&&b.getMessage().getString().contains("信任此服务器"))b.onPress(new net.minecraft.client.input.KeyEvent(257,0,0));return;}if(++wait==1)mc.player.connection.sendCommand("ai accept");if(wait<40)return;mc.setScreen(null);if(!PythonHostSmokeServer.saved())mc.player.connection.sendChat("@Python助手 使用专用Python安装colorama==0.4.6，成功后import读取版本，用sys.executable启动隐藏Python子进程输出PYTHON_CHILD_OK，把colorama_version、python（sys.executable）、child_stdout写到工作目录python-host-proof.json。不要PowerShell或系统Python，不操作其它文件或应用，每次等聊天按钮确认。");mc.setScreen(new net.minecraft.client.gui.screens.ChatScreen("",false));sent=true;PythonHostSmokeServer.clientReady=true;}
  var pending=ClientHostCommands.smokePending();if(!pending.isEmpty()){
   if(!(mc.screen instanceof net.minecraft.client.gui.screens.ChatScreen))throw new IllegalStateException("PYTHON_APPROVAL_CHANGED_SCREEN");String op=pending.get("operation").toString();if(!op.equals(pendingOperation)){pendingOperation=op;pendingTicks=0;}pendingTicks++;Path request=root.resolve("command-"+op+".json");if(!Files.exists(request))Files.writeString(request,new com.google.gson.Gson().toJson(pending));
   if(!screenshot&&!capturing&&pendingTicks>=15){capturing=true;net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),img->{try(img){img.writeToFile(root.resolve("native-chat-confirmation.png"));screenshot=true;}catch(Exception e){PythonHostSmokeServer.failure="PYTHON_CHAT_SCREENSHOT_FAILED";}finally{capturing=false;}});}
   if(PythonHostSmokeServer.negative){if(++negativeWait==1&&!oldApprove.isEmpty())mc.player.connection.sendCommand(oldApprove);if(negativeWait>20&&decisions.add(op))mc.player.connection.sendCommand(pending.get("rejectCommand").toString());}
   else{Path review=root.resolve("approve-"+op+".txt");if(Files.exists(review)&&Files.readString(review).strip().equals(pending.get("hash"))&&decisions.add(op)){mc.player.connection.sendCommand(pending.get("viewCommand").toString());oldApprove=pending.get("approveCommand").toString();mc.player.connection.sendCommand(oldApprove);mc.player.connection.sendCommand(oldApprove);approved++;}}
  }
  if(ticks%100==0)Files.writeString(root.resolve("progress.json"),new com.google.gson.Gson().toJson(Map.of("ticks",ticks,"approved",approved,"pending",pending.isEmpty()?"":pending.get("operation"),"realComplete",PythonHostSmokeServer.realComplete,"screen",mc.screen==null?"none":mc.screen.getClass().getSimpleName())));
  if(PythonHostSmokeServer.complete&&!capturing){var decisions=ClientHostCommands.smokeDecisions();if(((Number)decisions.get("accepted")).intValue()<2||((Number)decisions.get("rejected")).intValue()<1||((Number)decisions.get("invalidToken")).intValue()<1||((Number)decisions.get("duplicateApprove")).intValue()<1||!screenshot)throw new IllegalStateException("PYTHON_APPROVAL_EVIDENCE_MISSING:"+decisions);Files.writeString(root.resolve("client.json"),new com.google.gson.Gson().toJson(Map.of("status",PythonHostSmokeServer.saved()?"SAVED_REAL_PYTHON_NATIVE_CHAT_APPROVAL_VERIFIED":"REAL_PYTHON_NATIVE_CHAT_APPROVAL_VERIFIED","decisions",decisions,"fixtureClicks",approved,"fullscreenApprovalOpened",false,"duplicateClicksDidNotDuplicate",true,"staleApprovalDidNotApproveNewRequest",true,"systemInputInjected",false)));done=true;dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.info("MINEAGENT_CONVERSATION_AGENT_OK");dev.mineagent.runtime.neoforge.client.cinematic.CinematicCaptureClient.finish();}
 }catch(Exception e){done=true;Files.writeString(root.resolve("client-failure.json"),new com.google.gson.Gson().toJson(Map.of("error",e.toString(),"approved",approved)));dev.mineagent.runtime.neoforge.client.cinematic.CinematicCaptureClient.finish();}}
}
