package dev.mineagent.runtime.neoforge.client.nativeui;

import com.google.gson.*;
import com.lowdragmc.lowdraglib2.gui.ui.elements.*;
import dev.mineagent.runtime.neoforge.client.language.ClientLanguage;
import net.minecraft.network.chat.Component;
import java.util.*;

/** Explicit owner preferences remain separate from world facts and permission grants. */
final class NativePreferencesPanel {
    private record Choice(String id,String name){@Override public String toString(){return name;}}
    private final NativeWorkspaceScreen host;private final WorkspaceWindow window;private final ScrollerView list;private final TextElement notice=WorkspacePanels.text("");private String mode="list";private int offset,next;private boolean more,busy;private UUID operation;
    static void open(NativeWorkspaceScreen host){if(!host.revealWindow("preferences"))new NativePreferencesPanel(host);}
    private NativePreferencesPanel(NativeWorkspaceScreen host){this.host=host;window=host.window("preferences",t("我的长期偏好"),560,390);var tools=WorkspacePanels.row();tools.getLayout().height(25);window.body.addChild(tools);tools.addChild(button("偏好条目",()->{if(busy)return;mode="list";offset=0;load();}));tools.addChild(button("使用记录",()->{if(busy)return;mode="uses";offset=0;load();}));tools.addChild(button("新增明确偏好",()->edit(new JsonObject())));tools.addChild(button("刷新",this::load));window.body.addChild(WorkspacePanels.text(t("偏好只用于本人指定用途的模型请求，不授予权限。启用内容会发送给配置的 Provider。")));window.body.addChild(notice);list=WorkspacePanels.scroller(window.body);var nav=WorkspacePanels.row();nav.getLayout().height(25);window.body.addChild(nav);nav.addChild(button("上一页",()->{offset=Math.max(0,offset-8);load();}));nav.addChild(button("下一页",()->{if(more){offset=next;load();}}));nav.addChild(button("核对上次操作",this::receipt));load();}
    private void load(){if(busy)return;busy=true;String requested=mode;WorkspacePanels.request("preferences.read",Map.of("kind",requested,"offset",Integer.toString(offset))).whenComplete((reply,error)->{busy=false;if(!host.activeContext()||window.closed()||!mode.equals(requested))return;if(error!=null){WorkspacePanels.failure(notice,error);return;}var data=WorkspacePanels.state(reply).getAsJsonObject("state");more=data.get("more").getAsBoolean();next=data.get("nextOffset").getAsInt();list.clearAllScrollViewChildren();for(var raw:data.getAsJsonArray("items")){var item=raw.getAsJsonObject();var card=WorkspacePanels.card(list,text(item,mode.equals("uses")?"purpose":"key"));if(mode.equals("uses")){card.addChild(WorkspacePanels.text(text(item,"phase")));card.addChild(button("详情",()->NativeReadout.show(host,"preference-use-"+text(item,"request"),"使用记录",item)));}else{card.addChild(WorkspacePanels.text(text(item,"value")));card.addChild(WorkspacePanels.text((item.get("enabled").getAsBoolean()?t("已启用"):t("已暂停"))+" · "+text(item,"revision")));var actions=WorkspacePanels.row();actions.getLayout().height(25);card.addChild(actions);actions.addChild(button("编辑范围与内容",()->edit(item)));actions.addChild(button(item.get("enabled").getAsBoolean()?"暂停":"启用",()->change(item,"ENABLE",Map.of("enabled",Boolean.toString(!item.get("enabled").getAsBoolean())))));actions.addChild(button("删除",()->Dialog.showCheckBox(t("删除偏好"),text(item,"key"),yes->{if(yes)change(item,"DELETE",Map.of());}).show(window.body)));}}notice.setText(Component.literal(t("记录")+" · "+data.get("total").getAsString()));});}
    private void edit(JsonObject entry){
        var editor=host.window("preference-edit-"+text(entry,"id"),t("编辑明确偏好"),480,375);editor.body.clearAllChildren();if(!text(entry,"world").isBlank()&&!text(entry,"world").equals(NativeWorkspaceConnection.current().binding().worldId().toString()))editor.body.addChild(WorkspacePanels.text(t("原条目属于其它世界；选择“仅当前世界”保存会明确移到当前世界。")));var error=WorkspacePanels.text("");editor.body.addChild(error);var key=new TextField().setText(text(entry,"key"),false);key.textFieldStyle(style->style.placeholder(Component.literal(t("偏好名称，例如建筑风格"))));key.getLayout().height(25).widthPercent(100);editor.body.addChild(key);var value=new TextArea();value.setValue(text(entry,"value").split("\n",-1),false);value.getLayout().flex(1).widthPercent(100);editor.body.addChild(value);
        var scope=new Selector<Choice>();var scopes=List.of(new Choice("CURRENT_WORLD",t("仅当前世界")),new Choice("ALL_WORLDS",t("本人所有世界")));scope.setCandidates(scopes);scope.setValue(scopes.get(entry.has("id")&&text(entry,"world").isBlank()?1:0),false);scope.getLayout().height(25).widthPercent(100);editor.body.addChild(scope);var agent=new Selector<Choice>();var all=new Choice("",t("我发起请求的任意 AI"));agent.setCandidates(List.of(all));agent.setValue(all,false);agent.getLayout().height(25).widthPercent(100);editor.body.addChild(agent);scope.setOnValueChanged(choice->{agent.setActive(choice.id.equals("CURRENT_WORLD"));if(choice.id.equals("ALL_WORLDS"))agent.setValue(all,false);});
        WorkspacePanels.request("shell.read",Map.of()).whenComplete((reply,failure)->{if(editor.closed())return;if(failure!=null){WorkspacePanels.failure(error,failure);return;}var choices=new ArrayList<Choice>();choices.add(all);for(var raw:JsonParser.parseString(reply.values().get("agents")).getAsJsonArray()){var item=raw.getAsJsonObject();choices.add(new Choice(text(item,"id"),text(item,"name")));}agent.setCandidates(choices);choices.stream().filter(choice->choice.id.equals(text(entry,"agent"))).findFirst().ifPresent(choice->agent.setValue(choice,false));agent.setActive(scope.getValue().id.equals("CURRENT_WORLD"));});
        var selected=new LinkedHashSet<String>();if(entry.has("purposes"))entry.getAsJsonArray("purposes").forEach(item->selected.add(item.getAsString()));else selected.add("CONVERSATION");var purposes=WorkspacePanels.row();purposes.getLayout().height(25);editor.body.addChild(purposes);for(var choice:List.of(new Choice("CONVERSATION",t("正式对话")),new Choice("PLANNING",t("普通任务规划")),new Choice("GENERATION",t("内容包生成 / 改版")))){var toggle=new Toggle().setText(choice.name);toggle.setOn(selected.contains(choice.id),false);toggle.registerValueListener(on->{if(on)selected.add(choice.id);else selected.remove(choice.id);});purposes.addChild(toggle);}
        var enabled=new Toggle().setText(t("启用所选用途"));enabled.setOn(!entry.has("enabled")||entry.get("enabled").getAsBoolean(),false);editor.body.addChild(enabled);editor.body.addChild(button("保存偏好",()->{if(key.getValue().isBlank()||key.getValue().length()>64||String.join("\n",value.getValue()).length()>1024){error.setText(Component.literal(t("请填写不超过限制的名称和内容。")));return;}editor.body.setActive(false);mutate(entry,"SAVE",Map.of("key",key.getValue(),"value",String.join("\n",value.getValue()),"scope",scope.getValue().id,"agentId",scope.getValue().id.equals("ALL_WORLDS")?"":agent.getValue().id,"purposes",String.join(",",selected),"enabled",Boolean.toString(enabled.isOn()))).whenComplete((reply,failure)->{editor.body.setActive(true);if(failure!=null)WorkspacePanels.failure(error,failure);else editor.close();});}));
    }
    private void change(JsonObject entry,String action,Map<String,String> edited){mutate(entry,action,edited).exceptionally(error->null);}
    private java.util.concurrent.CompletableFuture<dev.mineagent.runtime.api.ui.UiProtocol.Receipt> mutate(JsonObject entry,String action,Map<String,String> edited){
        if(busy||operation!=null)return java.util.concurrent.CompletableFuture.failedFuture(new IllegalStateException("PREFERENCE_OUTCOME_PENDING"));busy=true;operation=UUID.randomUUID();var args=new LinkedHashMap<>(Map.of("kind","change","action",action,"id",text(entry,"id"),"expected",entry.has("revision")?text(entry,"revision"):"0","key",text(entry,"key"),"value",text(entry,"value"),"scope",text(entry,"world").isBlank()?"ALL_WORLDS":"CURRENT_WORLD","agentId",text(entry,"agent"),"purposes","","enabled","false"));args.put("confirmed","true");args.putAll(edited);
        return NativeWorkspaceConnection.command("preferences.write",args,operation).thenApply(reply->{String code=reply.values().getOrDefault("errorCode","");if(reply.code()==dev.mineagent.runtime.api.ui.UiProtocol.Code.APPLIED&&code.isBlank()){operation=null;return reply;}
            if(!code.isBlank()&&!Set.of("PREFERENCE_FAILED","PREFERENCE_STORE_UNAVAILABLE").contains(code)||Set.of(dev.mineagent.runtime.api.ui.UiProtocol.Code.PERMISSION_DENIED,dev.mineagent.runtime.api.ui.UiProtocol.Code.INVALID_REQUEST,dev.mineagent.runtime.api.ui.UiProtocol.Code.STALE_VIEW).contains(reply.code()))operation=null;
            throw new IllegalStateException(code.isBlank()?reply.code().name():code);
        }).whenComplete((reply,error)->{busy=false;if(window.closed())return;if(error!=null)WorkspacePanels.failure(notice,error);else load();});
    }
    private void receipt(){if(operation==null||busy)return;busy=true;WorkspacePanels.request("preferences.read",Map.of("kind","receipt","operationId",operation.toString())).whenComplete((reply,error)->{busy=false;if(error!=null){WorkspacePanels.failure(notice,error);return;}operation=null;NativeReadout.show(host,"preference-receipt","偏好操作回执",WorkspacePanels.state(reply));load();});}
    private static String text(JsonObject object,String key){return object.has(key)&&!object.get(key).isJsonNull()?object.get(key).getAsString():"";}
    private static String t(String text){return ClientLanguage.t(text);}
    private static Button button(String text,Runnable action){return NativeUiTheme.button(t(text),action);}
}
