package dev.mineagent.runtime.neoforge.client.nativeui;

import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.databind.node.ObjectNode;
import com.lowdragmc.lowdraglib2.gui.ui.UIElement;
import com.lowdragmc.lowdraglib2.gui.ui.elements.TextField;
import com.lowdragmc.lowdraglib2.gui.ui.event.*;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;
import dev.mineagent.runtime.neoforge.ui.ConversationAgentTools;
import net.minecraft.client.Minecraft;
import java.nio.file.*;
import java.util.*;
import java.util.concurrent.*;

/** Isolated production-JAR fixture. No model calls; drives the real server RPC and KubeJS/LDLib2 runtime. */
public final class NativeUiSmokeClient {
    private static final ObjectMapper JSON=new ObjectMapper();
    private static final String SOURCE="""
        {"id":"quest","title":"DivZero native UI","surface":"HUD","handlers":{"gift":{"tool":"give_item","arguments":{"item":"minecraft:stone","count":1},"resultKey":"giftResult"}},"sources":{"nativeScore":{"kind":"score","objective":"native_ui_score","holder":"$viewer"}},"data":{"query":"","balance":25,"done":false,"nativeScore":5},
        "root":{"id":"root","type":"column","style":"width: 270; height: 205; padding-all: 10; background: #d9222939; gap: 5;","children":[
        {"id":"heading","type":"label","text":"DivZero / LDLib2 + KubeJS","style":"height: 18; color: #ffffff;"},
        {"id":"search","type":"input","bind":"query","style":"height: 20;"},
        {"id":"live-score","type":"label","bind":"nativeScore","style":"height: 18; color: #ffffff;"},
        {"id":"balance","type":"label","bind":"balance","style":"height: 18; color: #ffe16a;"},
        {"id":"progress","type":"progress","value":0.6,"style":"height: 12;"},
        {"id":"buy","type":"button","text":"Update balance / toggle task","style":"height: 22;","events":{"click":[{"op":"set","key":"balance","value":17},{"op":"toggle","key":"done"},{"op":"emit","action":"gift","args":{}}]}},
        {"id":"task","type":"toggle","text":"Task complete","bind":"done"}]}}
        """;
    private static int ticks,stage,wait,setupTicks;private static boolean busy,finished,setupRequested,setupAccepted;private static UUID agent;private static int beforeGift;private static UUID conversation;private static UUID personaProfile;private static UIElement oldWidget;private static final List<Object> receipts=new ArrayList<>();
    public static void tick(){
        if(!Boolean.getBoolean("mineagent.nativeUiSmoke")||finished)return;var mc=Minecraft.getInstance();
        if(++ticks>(Boolean.getBoolean("mineagent.nativeUiModelSmoke")?18000:6000)){fail(new IllegalStateException("NATIVE_UI_SMOKE_TIMEOUT stage="+stage));return;}
        if(mc.player==null||mc.level==null||mc.getSingleplayerServer()==null||busy)return;
        try{
            if(!setupRequested){setupRequested=true;net.neoforged.neoforge.client.network.ClientPacketDistributor.sendToServer(new dev.mineagent.runtime.neoforge.network.MineAgentPayloads.PanelRequest());return;}
            if(!setupAccepted){var values=dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox.snapshot().values();String fingerprint=values.getOrDefault("security.identityFingerprint","");if(fingerprint.isEmpty()||!dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox.signatureValid())return;new dev.mineagent.runtime.client.trust.ServerTrustStore(mc.gameDirectory.toPath().resolve("config/mineagent-trusted-servers.properties")).confirm("local-integrated",fingerprint,Base64.getDecoder().decode(values.get("security.identityPublicKey")));mc.player.connection.sendCommand("ai accept");setupAccepted=true;return;}
            if(++setupTicks<35)return;
            if(agent==null&&(Boolean.getBoolean("mineagent.nativeUiSavedTitle")||Boolean.getBoolean("mineagent.nativeUiRestoreOnly"))){busy=true;var server=mc.getSingleplayerServer();var owner=mc.player.getUUID();server.submit(()->MineAgentRuntimeServices.bodies(server).definitions().stream().filter(a->a.ownerPlayerId().equals(owner)&&a.displayName().equals("NativeUiBuilder")).findFirst().orElseThrow().agentId()).whenComplete((id,error)->mc.execute(()->{busy=false;if(error!=null){fail(error);return;}agent=id;stage=Boolean.getBoolean("mineagent.nativeUiRestoreOnly")?40:9;mc.setScreen(null);}));return;}
            if(agent==null){busy=true;var owner=mc.player.getUUID();var server=mc.getSingleplayerServer();server.submit(()->{var p=server.getPlayerList().getPlayer(owner);server.getPlayerList().op(p.nameAndId());p.setGameMode(net.minecraft.world.level.GameType.CREATIVE);beforeGift=p.getInventory().countItem(net.minecraft.world.item.Items.STONE);var scoreboard=server.getScoreboard();var objective=scoreboard.addObjective("native_ui_score",net.minecraft.world.scores.criteria.ObjectiveCriteria.DUMMY,net.minecraft.network.chat.Component.literal("Native score"),net.minecraft.world.scores.criteria.ObjectiveCriteria.RenderType.INTEGER,false,null);scoreboard.getOrCreatePlayerScore(p,objective).set(5);return MineAgentRuntimeServices.bodies(server).createPersistentAt("NativeUiBuilder",owner,p.level(),p.position().add(2,0,0)).agentId();}).whenComplete((id,error)->mc.execute(()->{busy=false;if(error!=null){fail(error);return;}agent=id;mc.setScreen(null);}));return;}
            if(stage==40){if(++wait<40)return;wait=0;call("inspect_native_ui",JSON.createObjectNode().put("id","quest"),value->{var state=JSON.valueToTree(value);var views=state.path("client").path("views");require(views.size()==1,"RESTORED_HUD_MISSING");var view=views.get(0);require(view.path("revision").asLong()==5&&view.path("visible").asBoolean()&&!view.path("interactive").asBoolean()&&view.path("data").path("nativeScore").asInt()==9&&mc.screen==null,"RESTORED_HUD_STATE");stage=41;});return;}
            if(stage==41){if(++wait<20)return;wait=0;screenshot("10-restored-native-hud.png");stage=21;return;}
            if(stage==0&&Boolean.getBoolean("mineagent.nativeUiBuiltinOnly")){stage=9;return;}
            if(stage==0){call("set_native_ui",base(0).put("source",SOURCE),r->{applied(r,1);require(mc.screen==null,"PASSIVE_HUD_OPENED_SCREEN");stage=1;});return;}
            if(stage==1){if(++wait<30)return;screenshot("01-passive.png");wait=0;call("control_native_ui",base(1).put("action","interact"),r->{applied(r,2);stage=2;});return;}
            if(stage==2){if(++wait<15)return;wait=0;((TextField)NativeInterfacesClient.smokeWidget("quest","search")).setText("oak");var event=UIEvent.create(UIEvents.MOUSE_DOWN);event.target=NativeInterfacesClient.smokeWidget("quest","buy");event.button=0;UIEventDispatcher.dispatchEvent(event);oldWidget=NativeInterfacesClient.smokeWidget("quest","progress");call("inspect_native_ui",JSON.createObjectNode().put("id","quest"),r->{var client=JSON.valueToTree(r).path("client").path("views").get(0);require(client.path("data").path("query").asText().equals("oak")&&client.path("data").path("balance").asInt()==17&&client.path("data").path("done").asBoolean(),"KUBEJS_INPUT_OR_BUTTON");stage=22;wait=0;});return;}
            if(stage==22){if(++wait<25)return;wait=0;call("inspect_native_ui",JSON.createObjectNode().put("id","quest"),value->{var state=JSON.valueToTree(value);require(state.path("events").size()==1&&state.path("events").get(0).path("state").asText().equals("COMPLETED")&&state.path("client").path("views").get(0).path("data").path("giftResult").path("status").asText().equals("APPLIED"),"NATIVE_CALLBACK_NOT_APPLIED");NativeInterfacesClient.smokeReplayLastEmission();stage=23;});return;}
            if(stage==23){if(++wait<25)return;wait=0;busy=true;var server=mc.getSingleplayerServer();var owner=mc.player.getUUID();server.submit(()->server.getPlayerList().getPlayer(owner).getInventory().countItem(net.minecraft.world.item.Items.STONE)).whenComplete((count,error)->mc.execute(()->{busy=false;try{if(error!=null)throw new IllegalStateException(error);require(count==beforeGift+1,"NATIVE_CALLBACK_DUPLICATED_WORLD_EFFECT");receipts.add(Map.of("callbackInventoryBefore",beforeGift,"callbackInventoryAfter",count,"duplicateEffect",false));stage=3;}catch(Exception failure){fail(failure);}}));return;}
            if(stage==3){System.setProperty("mineagent.nativeUiSmokeLoseCommit","true");var args=base(2);args.putObject("data").put("balance",19);call("patch_native_ui_data",args,r->{require("UNKNOWN".equals(r.get("status")),"LOST_COMMIT_NOT_UNKNOWN");require(oldWidget==NativeInterfacesClient.smokeWidget("quest","progress"),"DATA_REBUILT_TREE");require(((com.lowdragmc.lowdraglib2.gui.ui.elements.Toggle)NativeInterfacesClient.smokeWidget("quest","task")).getValue(),"PATCH_OVERWROTE_LOCAL_STATE");call("inspect_native_ui",JSON.createObjectNode().put("id","quest"),observed->{var value=JSON.valueToTree(observed);require(value.path("saved").path("revision").asLong()==3&&"COMMITTED_FROM_CLIENT_EVIDENCE".equals(value.path("reconciliation").asText()),"CANDIDATE_NOT_RECONCILED");stage=30;});});return;}
            if(stage==30){busy=true;var server=mc.getSingleplayerServer();var owner=mc.player.getUUID();server.submit(()->{var player=server.getPlayerList().getPlayer(owner);server.getScoreboard().getOrCreatePlayerScore(player,server.getScoreboard().getObjective("native_ui_score")).set(9);return true;}).whenComplete((value,error)->mc.execute(()->{busy=false;if(error!=null){fail(error);return;}wait=0;stage=31;}));return;}
            if(stage==31){if(++wait<25)return;wait=0;call("inspect_native_ui",JSON.createObjectNode().put("id","quest"),value->{var state=JSON.valueToTree(value).path("client").path("views").get(0);require(state.path("data").path("nativeScore").asInt()==9&&state.path("revision").asLong()==3,"LIVE_SCORE_SOURCE_DID_NOT_UPDATE");stage=4;});return;}
            if(stage==4){screenshot("02-interactive.png");call("set_native_ui",base(3).put("source",SOURCE.replace("#d9222939","#e0101420").replace("DivZero / LDLib2 + KubeJS","Live revised / input retained")),r->{applied(r,4);require(((TextField)NativeInterfacesClient.smokeWidget("quest","search")).getValue().equals("oak"),"HOT_UPDATE_LOST_DRAFT");oldWidget=NativeInterfacesClient.smokeWidget("quest","search");stage=5;});return;}
            if(stage==5){call("set_native_ui",base(4).put("source",SOURCE.replace("width: 270","unknown-property: 270")),r->{require("REJECTED".equals(r.get("status")),"BAD_STYLE_ACCEPTED");require(oldWidget==NativeInterfacesClient.smokeWidget("quest","search"),"FAILED_BUILD_REPLACED_OLD_TREE");stage=6;});return;}
            if(stage==6){screenshot("03-revised.png");call("set_native_ui",base(1).put("source",SOURCE),r->{require("REJECTED".equals(r.get("status")),"STALE_UPDATE_ACCEPTED");stage=7;});return;}
            if(stage==7){call("control_native_ui",base(4).put("action","release"),r->{applied(r,5);require(mc.screen==null,"HUD_RELEASE_LEFT_SCREEN");stage=8;});return;}
            if(stage==8){if(++wait<25)return;wait=0;screenshot("04-restored-hud.png");call("inspect_native_ui",JSON.createObjectNode().put("id","quest"),r->{var n=JSON.valueToTree(r);require(n.path("saved").path("revision").asLong()==5,"STORE_REVISION");require(!n.path("client").path("views").get(0).path("interactive").asBoolean(),"HUD_STILL_INTERACTIVE");stage=9;});return;}
            if(stage==9&&Boolean.getBoolean("mineagent.nativeUiSavedTitle")){if(!(mc.screen instanceof NativeWorkspaceScreen)){NativeWorkspaceScreen.openForAgent(agent.toString(),"NativeUiBuilder");return;}if(!NativeWorkspaceConnection.ready())return;busy=true;WorkspacePanels.request("conversation.read",Map.of("kind","list","agentId",agent.toString(),"state","ACTIVE","search","我的花园小屋","before","0")).whenComplete((receipt,error)->{busy=false;try{if(error!=null)throw new IllegalStateException(error);var list=WorkspacePanels.state(receipt).getAsJsonArray("conversations");require(list.size()==1,"SAVED_TITLE_NOT_FOUND");conversation=UUID.fromString(list.get(0).getAsJsonObject().get("conversationId").getAsString());NativeWorkspaceScreen.openConversation(agent.toString(),"NativeUiBuilder",conversation.toString());stage=10;wait=0;}catch(Exception failure){fail(failure);}});return;}
            if(stage==9){if(!(mc.screen instanceof NativeWorkspaceScreen)){NativeWorkspaceScreen.openForAgent(agent.toString(),"NativeUiBuilder");return;}if(!NativeWorkspaceConnection.ready())return;busy=true;WorkspacePanels.request("conversation.write",Map.of("kind","create","agentId",agent.toString(),"title","Native workspace test","autoTitle","true")).whenComplete((receipt,error)->{busy=false;try{if(error!=null)throw new IllegalStateException(error);conversation=UUID.fromString(WorkspacePanels.state(receipt).get("conversationId").getAsString());NativeWorkspaceScreen.openConversation(agent.toString(),"NativeUiBuilder",conversation.toString());stage=10;}catch(Exception e){fail(e);}});return;}
            if(stage==10){if(++wait<35)return;wait=0;require(mc.screen instanceof NativeWorkspaceScreen,"NATIVE_WORKSPACE_NOT_OPEN");receipts.add(Map.of("ime",((NativeWorkspaceScreen)mc.screen).smokeIme()));var workspace=((NativeWorkspaceScreen)mc.screen).smokeState();require(!workspace.get("selected").toString().isBlank(),"NATIVE_CONVERSATION_NOT_READ");receipts.add(Map.of("workspace",workspace,"kubejsInstalled",net.neoforged.fml.ModList.get().isLoaded("kubejs")));screenshot("05-native-workspace.png");if(Boolean.getBoolean("mineagent.nativeUiSavedTitle")){require(((Number)workspace.get("messageRows")).intValue()>=2&&((Number)workspace.get("bodyChars")).intValue()>80&&((Number)workspace.get("visibleRows")).intValue()>=2,"SAVED_MESSAGE_BODY_NOT_VISIBLE "+workspace);receipts.add(Map.of("savedConversationReadback",workspace));stage=21;return;}AgentProfileScreen.open(agent,"NativeUiBuilder");stage=11;return;}
            if(stage==11){if(++wait<35)return;wait=0;require(mc.screen instanceof AgentProfileScreen,"AI_PROFILE_NOT_OPEN");screenshot("06-agent-profile.png");stage=12;return;}
            if(stage==12){busy=true;personaProfile=UUID.randomUUID();WorkspacePanels.request("persona.libraryWrite",Map.of("kind","save","agentId",agent.toString(),"profileId",personaProfile.toString(),"name","建筑搭档 / Builder","text","按构件建造，完工前检查实际方块和通路。"))
                .thenCompose(receipt->WorkspacePanels.request("persona.libraryRead",Map.of("kind","get","agentId",agent.toString(),"profileId",personaProfile.toString())))
                .whenComplete((receipt,error)->{busy=false;try{if(error!=null)throw new IllegalStateException(error);require(WorkspacePanels.state(receipt).get("text").getAsString().contains("通路"),"PERSONA_LIBRARY_READBACK");receipts.add(Map.of("personaProfile",WorkspacePanels.state(receipt).get("id").getAsString()));((AgentProfileScreen)mc.screen).smokeTab("persona");stage=13;}catch(Exception failure){fail(failure);}});return;}
            if(stage==13){if(++wait<30)return;wait=0;screenshot("07-persona-library.png");stage=14;return;}
            if(stage==14){var source=JSON.writeValueAsString(dev.mineagent.runtime.core.objects.ModelGeometryTools.capabilities().get("minimalModel"));call("open_preview",JSON.createObjectNode().put("kind","model").put("source",source),receipt->{require("PREVIEW_OPENED".equals(receipt.get("status")),"NATIVE_PREVIEW_NOT_OPEN");stage=15;});return;}
            if(stage==15){if(!Boolean.TRUE.equals(NativePreview.smokeState().get("ready")))return;NativePreview.smokeZoom();stage=16;return;}
            if(stage==16){if(++wait<25||!Boolean.TRUE.equals(NativePreview.smokeState().get("painted")))return;wait=0;require(((Number)NativePreview.smokeState().get("zoom")).doubleValue()>1,"NATIVE_PREVIEW_ZOOM");screenshot("08-native-model-preview.png");receipts.add(Map.of("preview",NativePreview.smokeState()));stage=17;return;}
            if(stage==17&&Boolean.getBoolean("mineagent.nativeUiModelSmoke")){busy=true;WorkspacePanels.request("conversation.read",Map.of("kind","messages","agentId",agent.toString(),"conversationId",conversation.toString(),"before","0")).thenCompose(receipt->WorkspacePanels.request("conversation.write",Map.of("kind","send","agentId",agent.toString(),"conversationId",conversation.toString(),"expectedRevision",WorkspacePanels.state(receipt).getAsJsonObject("conversation").get("revision").getAsString(),"text","我们来聊聊建一座带花园的中世纪小屋。请用一句中文回应，不使用工具，不执行游戏操作。"))).whenComplete((receipt,error)->{busy=false;if(error!=null){fail(error);return;}stage=18;wait=0;});return;}
            if(stage==18){if(++wait<20)return;wait=0;busy=true;WorkspacePanels.request("conversation.read",Map.of("kind","messages","agentId",agent.toString(),"conversationId",conversation.toString(),"before","0")).whenComplete((receipt,error)->{busy=false;try{if(error!=null)throw new IllegalStateException(error);var state=WorkspacePanels.state(receipt);var chat=state.getAsJsonObject("conversation");String generated=chat.get("title").getAsString();if(generated.equals("Native workspace test"))return;require(!generated.isBlank()&&generated.length()<=48,"MODEL_TITLE_INVALID");receipts.add(Map.of("modelTitle",generated,"messages",JSON.readTree(state.getAsJsonArray("messages").toString())));NativeWorkspaceScreen.openConversation(agent.toString(),"NativeUiBuilder",conversation.toString());stage=19;wait=0;}catch(Exception failure){fail(failure);}});return;}
            if(stage==19){if(++wait<35)return;wait=0;screenshot("09-model-conversation-title.png");busy=true;WorkspacePanels.request("conversation.read",Map.of("kind","messages","agentId",agent.toString(),"conversationId",conversation.toString(),"before","0")).thenCompose(receipt->WorkspacePanels.request("conversation.write",Map.of("kind","rename","agentId",agent.toString(),"conversationId",conversation.toString(),"expectedRevision",WorkspacePanels.state(receipt).getAsJsonObject("conversation").get("revision").getAsString(),"title","我的花园小屋"))).whenComplete((receipt,error)->{busy=false;if(error!=null){fail(error);return;}stage=20;wait=0;});return;}
            if(stage==20){if(++wait<40)return;wait=0;busy=true;WorkspacePanels.request("conversation.read",Map.of("kind","messages","agentId",agent.toString(),"conversationId",conversation.toString(),"before","0")).whenComplete((receipt,error)->{busy=false;try{if(error!=null)throw new IllegalStateException(error);require(WorkspacePanels.state(receipt).getAsJsonObject("conversation").get("title").getAsString().equals("我的花园小屋"),"MANUAL_TITLE_LOST");receipts.add(Map.of("manualTitle","我的花园小屋"));stage=21;}catch(Exception failure){fail(failure);}});return;}
            if(stage==17||stage==21){if(++wait<20)return;Files.writeString(output().resolve("result.json"),JSON.writeValueAsString(Map.of("status","PASS","modelCalls",Boolean.getBoolean("mineagent.nativeUiModelSmoke")?"SEE_PROVIDER_AUDIT":0,"receipts",receipts,"coverage",Boolean.getBoolean("mineagent.nativeUiRestoreOnly")?List.of("hud_after_restart","passive_restore","restored_revision","live_score_after_restart"):Boolean.getBoolean("mineagent.nativeUiSavedTitle")?List.of("saved_real_model_conversation","manual_title_persistence","native_message_body","no_model_replay"):Boolean.getBoolean("mineagent.nativeUiBuiltinOnly")?List.of("builtin_without_kubejs","conversation_rpc","native_workspace","agent_profile","named_persona_library","native_model_preview","preview_zoom"):List.of("server_rpc","persistent_revision","kubejs_tree","native_hud","explicit_interaction","live_input","button_binding","incremental_data","hot_structure","retained_draft","bad_candidate_rollback","stale_rejection","uncertain_commit_reconciliation","live_score_source","scoped_callback","callback_deduplication","named_persona_library","native_model_preview","preview_zoom"))));finished=true;mc.stop();}
        }catch(Exception error){fail(error);}
    }
    private static ObjectNode base(long revision){return JSON.createObjectNode().put("id","quest").put("expected_revision",revision);}
    private static void applied(Map<String,Object> result,long revision){require("APPLIED".equals(result.get("status"))&&((Number)result.get("revision")).longValue()==revision,"APPLY_RECEIPT "+result);}
    private static void require(boolean yes,String message){if(!yes)throw new IllegalStateException(message);}
    private static void call(String tool,JsonNode arguments,java.util.function.Consumer<Map<String,Object>> accept){
        busy=true;var mc=Minecraft.getInstance();var owner=mc.player.getUUID();var server=mc.getSingleplayerServer();
        server.submit(()->ConversationAgentTools.execute(server.getPlayerList().getPlayer(owner),agent,UUID.randomUUID(),tool,arguments.toString(),()->true)).thenCompose(f->f).whenComplete((result,error)->mc.execute(()->{
            busy=false;try{if(error!=null)throw new IllegalStateException(error);receipts.add(Map.of("tool",tool,"result",result));accept.accept(result);}catch(Exception failure){fail(failure);}
        }));
    }
    private static Path output()throws Exception{String name=System.getProperty("mineagent.nativeUiOutput","native-ui-smoke");if(!name.matches("native-ui-[A-Za-z0-9_-]+"))throw new IllegalArgumentException("SMOKE_OUTPUT_SCOPE");return Files.createDirectories(Minecraft.getInstance().gameDirectory.toPath().resolve(name));}
    private static void screenshot(String name)throws Exception{Path target=output().resolve(name);net.minecraft.client.Screenshot.takeScreenshot(Minecraft.getInstance().getMainRenderTarget(),image->{try(image){image.writeToFile(target);}catch(Exception e){fail(e);}});}
    private static void fail(Throwable error){if(finished)return;finished=true;try{Files.writeString(output().resolve("failure.json"),JSON.writeValueAsString(Map.of("stage",stage,"error",error.toString(),"receipts",receipts)));}catch(Exception ignored){}dev.mineagent.runtime.neoforge.MineAgentRuntimeMod.LOGGER.error("NATIVE_UI_SMOKE_FAILED stage={}",stage,error);Minecraft.getInstance().stop();}
    private NativeUiSmokeClient(){}
}
