package dev.mineagent.runtime.neoforge.client.nativeui;

import com.google.gson.*;
import com.lowdragmc.lowdraglib2.gui.ui.UIElement;
import com.lowdragmc.lowdraglib2.gui.ui.elements.*;
import dev.mineagent.runtime.neoforge.client.language.ClientLanguage;
import net.minecraft.network.chat.Component;
import java.util.*;
import java.util.function.BooleanSupplier;

/** One editor shared by the AI's own panel and the integrated F2 workspace. */
public final class NativeBehaviorPanel {
    private record Choice(String id,String label){@Override public String toString(){return t(label);}}
    private static final List<NativeBehaviorPanel> OPEN=new ArrayList<>();
    private final String agent;private final BooleanSupplier current;private final UIElement container;private final Object hostScreen=net.minecraft.client.Minecraft.getInstance().screen;private final Object connection=net.minecraft.client.Minecraft.getInstance().getConnection(),level=net.minecraft.client.Minecraft.getInstance().level;private final TextElement status,progress,targetStatus;
    private final Selector<Choice> mode,strategy,engagement,target,actor,region,routeMode;
    private final Selector<Integer> radius;private final JsonArray route=new JsonArray();
    private JsonObject state,active,activeDetails;private boolean loading,saving,initialized,actorPending=true;private long next;
    private static String t(String s){return ClientLanguage.t(s);}
    public static void open(NativeWorkspaceScreen host,String id,String name){if(host.revealWindow("behavior-"+id))return;var window=host.window("behavior-"+id,name+" · "+t("行为模式"),490,420);attach(window.body,id,()->!window.closed());}
    public static void attach(UIElement parent,String agent,BooleanSupplier current){OPEN.add(new NativeBehaviorPanel(parent,agent,current));}
    public static void tick(){for(var panel:List.copyOf(OPEN)){if(!panel.current.getAsBoolean()||panel.connection!=net.minecraft.client.Minecraft.getInstance().getConnection()||panel.level!=net.minecraft.client.Minecraft.getInstance().level){OPEN.remove(panel);continue;}if(panel.hostScreen==net.minecraft.client.Minecraft.getInstance().screen)panel.read();}}
    private NativeBehaviorPanel(UIElement parent,String agent,BooleanSupplier current){
        this.agent=agent;this.current=current;this.container=parent;var scroll=WorkspacePanels.scroller(parent);var body=new UIElement();body.getLayout().widthPercent(100).gapAll(5);scroll.addScrollViewChild(body);
        status=NativeUiTheme.text(t("读取行为状态…"),NativeUiTheme.ACCENT,10);body.addChild(status);targetStatus=NativeUiTheme.text("",NativeUiTheme.MUTED,9);body.addChild(targetStatus);progress=NativeUiTheme.text("",NativeUiTheme.MUTED,9);body.addChild(progress);
        actor=selector(body,"执行身体",new String[][]{{"ai","AI 自己"},{"player","接管我的身体"}});actor.setOnValueChanged(value->{active=null;initialized=false;actorPending=true;next=0;});
        mode=selector(body,"主工作",new String[][]{{"IDLE","待命"},{"WANDER","自由活动"},{"FOLLOW","跟随"},{"PATROL","巡逻"},{"GUARD","警戒"},{"FARM","农务"},{"FISH","钓鱼"},{"COMBAT","战斗"}});
        strategy=selector(body,"战斗方式",new String[][]{{"AUTO","自动选择"},{"HIT_AND_RUN","近战跑打"},{"RANGED_KITE","远程控距"},{"HOLD_POSITION","守住阵地"},{"DISENGAGE","脱离交战"}});
        engagement=selector(body,"交战规则",new String[][]{{"SELF_DEFENSE","只自卫"},{"PROTECT","保护对象"},{"CLEAR_AREA","清理防区"},{"SPECIFIED","只攻击指定对象"},{"NONE","不攻击"}});
        target=selector(body,"目标 / 保护对象",new String[][]{{"$owner","主人"}});
        region=selector(body,"区域来源",new String[][]{{"LOOK","看向的位置"},{"CURRENT","当前位置"},{"PREVIOUS","沿用当前工作区域"}});
        var rangeRow=WorkspacePanels.row();rangeRow.getLayout().height(25);body.addChild(rangeRow);rangeRow.addChild(WorkspacePanels.text(t("区域半径")));radius=new Selector<>();radius.setCandidates(List.of(4,8,16));radius.setValue(4,false);rangeRow.addChild(radius);
        routeMode=selector(body,"巡逻方式",new String[][]{{"LOOP","循环"},{"PING_PONG","往返"},{"ONCE","一次"}});
        var points=WorkspacePanels.row();points.getLayout().height(25);body.addChild(points);points.addChild(NativeUiTheme.button(t("添加当前位置为路标"),()->{if(state!=null){route.add(state.getAsJsonObject("context").get("position").deepCopy());progress.setText(Component.literal(t("路标数量")+": "+route.size()));}}));points.addChild(NativeUiTheme.button(t("清空路标"),()->{while(!route.isEmpty())route.remove(0);}));
        var actions=WorkspacePanels.row();actions.getLayout().height(27);parent.addChild(actions);actions.addChild(NativeUiTheme.button(t("切换主工作"),this::start));actions.addChild(NativeUiTheme.button(t("只改战斗规则"),this::rules));
        var controls=WorkspacePanels.row();controls.getLayout().height(27);parent.addChild(controls);controls.addChild(NativeUiTheme.button(t("暂停"),()->control("pause")));controls.addChild(NativeUiTheme.button(t("继续"),()->control("resume")));controls.addChild(NativeUiTheme.button(t("全部停止"),()->send("stop_all",new JsonObject())));
        body.addChild(NativeUiTheme.text(t("战斗方式与主工作独立。缺少目标或范围时会说明原因。"),NativeUiTheme.MUTED,8));read();
    }
    private static Selector<Choice> selector(UIElement body,String label,String[][] choices){var row=WorkspacePanels.row();row.getLayout().height(25);body.addChild(row);var title=WorkspacePanels.text(t(label));title.getLayout().width(128);row.addChild(title);var select=new Selector<Choice>();select.getLayout().flex(1);var values=Arrays.stream(choices).map(p->new Choice(p[0],p[1])).toList();select.setCandidates(values);select.setValue(values.getFirst(),false);row.addChild(select);return select;}
    private static void choose(Selector<Choice> selector,String id){for(var value:selector.getCandidates())if(value.id.equals(id)){selector.setValue(value,false);return;}}
    private void read(){if(loading||saving||!NativeWorkspaceConnection.ready()||System.currentTimeMillis()<next)return;loading=true;next=System.currentTimeMillis()+1000;
        WorkspacePanels.request("behavior.read",Map.of("agentId",agent)).whenComplete((receipt,error)->{loading=false;if(!current.getAsBoolean())return;if(error!=null){WorkspacePanels.failure(status,error);return;}state=WorkspacePanels.state(receipt);actorPending=false;active=null;
            for(var row:state.getAsJsonArray("skills")){var session=row.getAsJsonObject().getAsJsonObject("session");if(session.getAsJsonObject("spec").get("actor").getAsString().equals(actor.getValue().id)&&!Set.of("COMPLETED","CANCELLED","FAILED").contains(session.get("state").getAsString())&&!session.get("reason").getAsString().equals("TEMPORARY_WORK")){active=session;activeDetails=row.getAsJsonObject();}}
            if(active==null){status.setText(Component.literal(t("待命")));progress.setText(Component.literal(""));targetStatus.setText(Component.literal(""));}else{var spec=active.getAsJsonObject("spec");String targetName=activeDetails.getAsJsonObject("combat").get("targetName").getAsString();if(targetName.isBlank())targetName=spec.get("target").getAsString().equals("$owner")?t("主人"):spec.get("area").isJsonNull()?"":t("工作区域");targetStatus.setText(Component.literal(t("当前目标")+": "+targetName));status.setText(Component.literal(t(label(spec.get("kind").getAsString()))+" · "+NativeUiTheme.state(active.get("state").getAsString())));progress.setText(Component.literal(t(reason(active.get("reason").getAsString()))+" · "+progress(active.getAsJsonObject("counters"))));if(!initialized){choose(mode,spec.get("kind").getAsString());choose(strategy,spec.getAsJsonObject("combat").get("strategy").getAsString());choose(engagement,spec.getAsJsonObject("combat").get("engagement").getAsString());}}
            if(!initialized){var options=new ArrayList<Choice>();options.add(new Choice("$owner","主人"));for(var row:state.getAsJsonObject("context").getAsJsonArray("entities")){var e=row.getAsJsonObject();options.add(new Choice(e.get("id").getAsString(),e.get("name").getAsString()));}target.setCandidates(options);target.setValue(options.getFirst(),false);initialized=true;}
        });
    }
    private static String reason(String code){return switch(code){case "WAITING_FOR_CROP_GROWTH"->"等待作物成熟";case "WAITING_FOR_REAL_BITE"->"等待鱼咬钩";case "SEED_REQUIRED_FOR_REPLANT","SEED_NOT_READY"->"等待补种种子";case "INVENTORY_FULL"->"背包已满，等待整理";case "DEFENDING_THEN_RESUME"->"正在防御，之后继续工作";case "THREAT_CLEARANCE_HYSTERESIS"->"正在确认威胁已解除";case "USER_PAUSED","INPUT_OR_MENU_PAUSED"->"已暂停";case "IDLE_BY_PLAYER","NO_ELIGIBLE_THREATS","ENGAGEMENT_DISABLED"->"待命";case "FOLLOW_DISTANCE_SATISFIED","FOLLOW_HYSTERESIS"->"保持跟随距离";case "PROTECTED_TARGET_ABSENT"->"等待保护对象";case "PROTECTING_TARGET"->"正在保护目标";case "WAITING_CHUNKS"->"等待区块加载";case "RESTART_REQUIRES_RESUME"->"重启后等待恢复";case "RESTART_REQUIRES_RECONCILIATION"->"需要核对旧操作后恢复";default->code.isEmpty()?"执行中":"等待条件恢复";};}
    private static String progress(JsonObject c){return t("已收获")+": "+count(c,"harvested")+" · "+t("已补种")+": "+count(c,"planted")+" · "+t("渔获")+": "+count(c,"fishingCatches");}
    private static long count(JsonObject c,String key){return c.has(key)?c.get(key).getAsLong():0;}
    private String label(String key){return switch(key){case "IDLE"->"待命";case "WANDER"->"自由活动";case "FOLLOW"->"跟随";case "PATROL"->"巡逻";case "GUARD"->"警戒";case "FARM"->"农务";case "FISH"->"钓鱼";default->"战斗";};}
    private JsonObject base(){if(state==null||actorPending)throw new IllegalStateException(t("等待状态读取"));var n=new JsonObject();n.addProperty("id","mode_"+UUID.randomUUID().toString().substring(0,8));n.addProperty("actor",actor.getValue().id);n.addProperty("kind",mode.getValue().id);n.addProperty("dimension",state.getAsJsonObject("context").get("dimension").getAsString());n.addProperty("expected_revision",0);return n;}
    private void area(JsonObject n){
        if(region.getValue().id.equals("PREVIOUS")){if(active==null||active.getAsJsonObject("spec").get("area").isJsonNull())throw new IllegalArgumentException(t("当前没有工作区域"));var a=active.getAsJsonObject("spec").getAsJsonObject("area");for(String key:List.of("min","max")){var point=a.getAsJsonObject(key);var list=new JsonArray();for(String axis:List.of("x","y","z"))list.add(point.get(axis));n.add(key,list);}return;}
        var p=state.getAsJsonObject("context").getAsJsonArray(region.getValue().id.equals("LOOK")?"look":"position");if(p.size()!=3)throw new IllegalArgumentException(t("请先看向目标区域，或选择当前位置"));int radius=this.radius.getValue();var min=new JsonArray();var max=new JsonArray();for(int i=0;i<3;i++){int v=(int)Math.floor(p.get(i).getAsDouble());min.add(v-(i==1?1:radius));max.add(v+(i==1?1:radius));}n.add("min",min);n.add("max",max);
    }
    private JsonObject combat(){var n=new JsonObject();n.addProperty("strategy",strategy.getValue().id);n.addProperty("engagement",engagement.getValue().id);switch(engagement.getValue().id){case "PROTECT"->n.addProperty("protect",target.getValue().id);case "SPECIFIED"->{if(target.getValue().id.equals("$owner"))throw new IllegalArgumentException(t("请选择可交战的目标"));n.addProperty("target",target.getValue().id);}case "CLEAR_AREA"->area(n);}return n;}
    private void start(){try{var n=base();String kind=mode.getValue().id;if(Set.of("WANDER","GUARD","FARM","FISH").contains(kind))area(n);if(kind.equals("FOLLOW"))n.addProperty("target",target.getValue().id);if(kind.equals("PATROL")){if(route.isEmpty())throw new IllegalArgumentException(t("请先添加路标"));n.add("route",route.deepCopy());n.addProperty("repeat",!routeMode.getValue().id.equals("ONCE"));n.addProperty("ping_pong",routeMode.getValue().id.equals("PING_PONG"));}n.add("combat",combat());send("set_behavior_mode",n);}catch(Exception e){WorkspacePanels.failure(status,e);}}
    private void rules(){try{if(actorPending)throw new IllegalStateException(t("等待状态读取"));if(active==null){var n=base();n.addProperty("kind","IDLE");n.addProperty("only_if_idle",true);n.add("combat",combat());send("set_behavior_mode",n);return;}var n=identity();n.add("combat",combat());send("set_combat_policy",n);}catch(Exception e){WorkspacePanels.failure(status,e);}}
    private JsonObject identity(){if(active==null)throw new IllegalStateException(t("当前没有运行任务"));var n=new JsonObject();n.addProperty("id",active.getAsJsonObject("spec").get("id").getAsString());n.add("expected_revision",active.get("revision"));return n;}
    private void control(String action){try{var n=identity();n.addProperty("action",action);send("control_behavior",n);}catch(Exception e){WorkspacePanels.failure(status,e);}}
    private void send(String tool,JsonObject n){if(saving)return;saving=true;WorkspacePanels.request("behavior.write",Map.of("agentId",agent,"tool",tool,"source",n.toString())).whenComplete((receipt,error)->{saving=false;if(!current.getAsBoolean())return;if(error!=null)WorkspacePanels.failure(status,error);else{status.setText(Component.literal(t("已应用")));next=0;read();}});}
    private static NativeBehaviorPanel smoke(String agent){if(!Boolean.getBoolean("mineagent.skillSmoke"))throw new IllegalStateException("SMOKE_DISABLED");return OPEN.stream().filter(p->p.agent.equals(agent)&&p.current.getAsBoolean()&&p.hostScreen==net.minecraft.client.Minecraft.getInstance().screen).reduce((a,b)->b).orElseThrow();}
    public static boolean smokeReady(String agent){return smoke(agent).state!=null&&!smoke(agent).loading;}
    public static void smokeSelect(String agent,String field,String value){var p=smoke(agent);var selector=switch(field){case "mode"->p.mode;case "strategy"->p.strategy;case "engagement"->p.engagement;case "region"->p.region;default->throw new IllegalArgumentException();};choose(selector,value);}
    private static Button find(UIElement node,String label){if(node instanceof Button b&&b.text.getText().getString().equals(label))return b;for(var child:node.getChildren()){var found=find(child,label);if(found!=null)return found;}return null;}
    public static void smokeClick(String agent,String label,boolean release){smokeClickElement(smoke(agent).container,t(label),release);}
    static void smokeClickElement(UIElement root,String label,boolean release){if(!Boolean.getBoolean("mineagent.skillSmoke"))throw new IllegalStateException("SMOKE_DISABLED");var b=find(root,label);if(b==null)throw new IllegalStateException("BUTTON_NOT_FOUND");var screen=(com.lowdragmc.lowdraglib2.gui.holder.ModularUIScreen)net.minecraft.client.Minecraft.getInstance().screen;float x=b.getPositionX()+b.getSizeWidth()/2,y=b.getPositionY()+b.getSizeHeight()/2;screen.modularUI.refreshHoveredElementAtScreen(x,y);var widget=com.lowdragmc.lowdraglib2.gui.ui.ModularUIClientAccess.getWidget(screen.modularUI);var event=new net.minecraft.client.input.MouseButtonEvent(x,y,new net.minecraft.client.input.MouseButtonInfo(0,0));if(release)widget.mouseReleased(event);else widget.mouseClicked(event,false);}
    private NativeBehaviorPanel(){throw new AssertionError();}
}
