package dev.mineagent.runtime.neoforge.client.nativeui;

import com.google.gson.*;
import com.lowdragmc.lowdraglib2.gui.ui.UIElement;
import com.lowdragmc.lowdraglib2.gui.ui.elements.*;
import dev.mineagent.runtime.neoforge.client.language.ClientLanguage;
import net.minecraft.network.chat.Component;
import java.util.*;
import static dev.mineagent.runtime.neoforge.client.nativeui.NativeStudioPanel.*;

/** Provider requests produce reviewed candidates. Adoption, publication and execution are independent. */
final class NativeCoderPanel {
    private static final Set<NativeCoderPanel> OPEN=new HashSet<>();
    static void open(NativeWorkspaceScreen host,JsonObject base){String key="coder-"+(base==null?"new":text(base,"id"));if(!host.revealWindow(key))new NativeCoderPanel(host,base,key);}
    private record Diagnostic(String kind,String id,String label){@Override public String toString(){return label;}}
    private final NativeWorkspaceScreen host;private final WorkspaceWindow window;private final JsonObject base;private final ScrollerView content;private final TextElement notice=WorkspacePanels.text("");private final UIElement requestForm=new UIElement();
    private final TextArea prompt=new TextArea();private final TextField path=new TextField();private final Selector<Integer> budget=new Selector<>();private final Selector<Diagnostic> diagnostic=new Selector<>();
    private final Toggle consent=new Toggle(),sources=new Toggle(),nativeContext=new Toggle(),workspace=new Toggle();private JsonObject job;private int offset;private boolean busy,formVisible;private long epoch,nextPoll;private UUID pending;
    private NativeCoderPanel(NativeWorkspaceScreen host,JsonObject base,String key){
        this.host=host;this.base=base==null?null:base.deepCopy();window=host.window(key,t("Coder 请求"),570,440);OPEN.add(this);var form=requestForm;form.getLayout().widthPercent(100).gapAll(3);
        if(base!=null&&text(base,"targetSide").equals("CLIENT"))form.addChild(WorkspacePanels.text(t("此 Coder 入口处理服务端源码；客户端源码可通过对话生成内容包并独立批准。")));
        path.setText(base==null?"server/studio.js":text(base,"path"),false);path.setActive(base==null);path.getLayout().height(23).widthPercent(100);form.addChild(path);prompt.getLayout().height(60).widthPercent(100);form.addChild(prompt);
        var options=WorkspacePanels.row();options.getLayout().height(25);form.addChild(options);budget.setCandidates(List.of(1,2,3));budget.setValue(1,false);options.addChild(WorkspacePanels.text(t("最多模型调用次数")));options.addChild(budget);workspace.setText(t("多文件工作区"));workspace.setOn(base!=null&&(yes(base,"workspace")||base.get("fileCount").getAsInt()>1),false);workspace.setActive(base==null||base.get("fileCount").getAsInt()<=1);options.addChild(workspace);
        var choices=new ArrayList<Diagnostic>();choices.add(new Diagnostic("","",t("不附带执行诊断")));if(base!=null)for(var raw:base.getAsJsonArray("publications")){var p=raw.getAsJsonObject();choices.add(new Diagnostic(text(p,"language"),text(p,"id"),text(p,"language")+" · "+text(p,"state")));}diagnostic.setCandidates(choices);diagnostic.setValue(choices.getFirst(),false);diagnostic.getLayout().widthPercent(100).height(23);form.addChild(diagnostic);
        consent.setText(t("同意本次模型调用预算与费用；不会自动采用或执行"));form.addChild(consent);sources.setText(t("单独允许向 Provider 发送完整依赖源码（含私有实现）"));form.addChild(sources);nativeContext.setText(t("单独允许发送已选 Native 声明及冻结的实际类上下文"));form.addChild(nativeContext);
        var actions=WorkspacePanels.row();actions.getLayout().height(25);form.addChild(actions);actions.addChild(NativeUiTheme.button(t("提交 Coder 请求"),this::submit));var navigation=WorkspacePanels.row();navigation.getLayout().height(25);window.body.addChild(navigation);navigation.addChild(NativeUiTheme.button(t("新请求"),this::form));navigation.addChild(NativeUiTheme.button(t("本人历史"),()->list(0)));navigation.addChild(NativeUiTheme.button(t("核对原请求"),()->{if(pending!=null)observe(pending.toString());else if(job!=null)observe(text(job,"id"));}));navigation.addChild(NativeUiTheme.button(t("选择 Native 上下文"),()->NativeApiPanel.open(host)));window.body.addChild(notice);content=WorkspacePanels.scroller(window.body);form();
    }
    private void form(){if(busy)return;formVisible=true;content.clearAllScrollViewChildren();content.addScrollViewChild(requestForm);notice.setText(Component.literal(base==null?t("新请求仅生成候选源码，不自动运行。"):text(base,"path")+" · r"+text(base,"revision")));}
    private boolean live(){return host.activeContext()&&!window.closed();}
    private void submit(){
        if(busy||!live())return;if(pending!=null){observe(pending.toString());return;}if(!consent.isOn()){notice.setText(Component.literal(t("请先确认模型调用预算与费用。")));return;}
        String agent=base==null?host.selectedAgentId():text(base,"agentId");if(agent.isBlank()||String.join("\n",prompt.getValue()).isBlank()){notice.setText(Component.literal(t("请选择 AI 并填写明确需求")));return;}
        var selection=NativeApiPanel.selection();if(!selection.isEmpty()&&!nativeContext.isOn()){notice.setText(Component.literal(t("请单独确认发送 Native 上下文")));return;}
        var args=new LinkedHashMap<String,String>();args.put("action","coderSubmit");args.put("path",path.getValue());args.put("prompt",String.join("\n",prompt.getValue()));args.put("agentId",agent);args.put("baseDraft",base==null?"":text(base,"id"));args.put("baseRevision",base==null?"0":text(base,"revision"));args.put("maxAttempts",budget.getValue().toString());args.put("diagnosticKind",diagnostic.getValue().kind());args.put("publicationId",diagnostic.getValue().id());args.put("workspace",Boolean.toString(workspace.isOn()));args.put("shareDependencySources",Boolean.toString(sources.isOn()));if(!selection.isEmpty()){args.putAll(selection);args.put("shareNativeContext","true");}
        pending=UUID.randomUUID();consent.setOn(false,false);sources.setOn(false,false);nativeContext.setOn(false,false);send(args,pending,true);
    }
    private void send(Map<String,String> args,UUID operation,boolean admission){if(busy)return;busy=true;long ticket=++epoch;write(args,operation).whenComplete((value,error)->{busy=false;if(!live()||ticket!=epoch)return;if(error!=null){WorkspacePanels.failure(notice,error);return;}if(admission)pending=null;if(value.has("draftId")){document(host,text(value,"draftId"));if(job!=null)observe(text(job,"id"));}else{job=value;draw();}nextPoll=System.currentTimeMillis()+2500;});}
    private void list(int page){if(busy||!live())return;formVisible=false;offset=page;busy=true;long ticket=++epoch;read(Map.of("kind","coderList","offset",Integer.toString(page))).whenComplete((value,error)->{busy=false;if(!live()||ticket!=epoch)return;if(error!=null){WorkspacePanels.failure(notice,error);return;}job=null;content.clearAllScrollViewChildren();for(var raw:value.getAsJsonArray("jobs")){var row=raw.getAsJsonObject();var card=WorkspacePanels.card(content,text(row,"path")+" · "+text(row,"state"));card.addChild(WorkspacePanels.text(row.getAsJsonArray("attempts").size()+" / "+text(row,"maxAttempts")));card.addChild(NativeUiTheme.button(t("查看请求与候选"),()->observe(text(row,"id"))));}pager(content,value,page,4,this::list);});}
    private void observe(String id){if(busy||!live())return;busy=true;long ticket=++epoch;read(Map.of("kind","coderGet","jobId",id)).whenComplete((value,error)->{busy=false;if(!live()||ticket!=epoch)return;if(error!=null){WorkspacePanels.failure(notice,error);return;}if(pending!=null&&pending.toString().equals(text(value,"id")))pending=null;job=value;draw();nextPoll=System.currentTimeMillis()+2500;});}
    private void part(JsonObject job,String part,int attempt){NativeReadout.open(host,"coder-text-"+text(job,"id")+"-"+part+attempt,t("请求与候选证据"),"studio.read",page->Map.of("kind","coderText","jobId",text(job,"id"),"revision",text(job,"revision"),"part",part,"attempt",Integer.toString(attempt),"offset",Integer.toString(page)),1024);}
    private void draw(){
        formVisible=false;content.clearAllScrollViewChildren();notice.setText(Component.literal(text(job,"state")+" · "+text(job,"error")));JsonObject selected=job.deepCopy();var summary=WorkspacePanels.card(content,text(selected,"path"));summary.addChild(WorkspacePanels.text(t("候选状态不代表源码已运行或世界效果已验证。")));var documents=WorkspacePanels.row();documents.getLayout().height(25);summary.addChild(documents);
        for(var entry:Map.of("request","原需求","base","基线源码","diagnostics","执行诊断","metadata","完整元数据","dependencies","冻结依赖声明").entrySet())documents.addChild(NativeUiTheme.button(t(entry.getValue()),()->part(selected,entry.getKey(),0)));
        if(selected.get("nativeTypeCount").getAsInt()+selected.get("nativeOverlayCount").getAsInt()>0)summary.addChild(NativeUiTheme.button(t("冻结 Native 上下文"),()->part(selected,"nativeSelection",0)));if(yes(selected,"workspace"))summary.addChild(NativeUiTheme.button(t("完整基线文件"),()->files(selected,0,0)));
        var attempts=selected.getAsJsonArray("attempts");
        for(int index=0;index<attempts.size();index++){
            var attempt=attempts.get(index).getAsJsonObject();int ordinal=attempt.get("ordinal").getAsInt();var card=WorkspacePanels.card(content,t("尝试")+" "+ordinal+" · "+text(attempt,"state"));card.addChild(WorkspacePanels.text(text(attempt,"provider")+" · "+text(attempt,"responseModel")));var actions=WorkspacePanels.row();actions.getLayout().height(25);card.addChild(actions);
            for(var entry:Map.of("raw","原始返回","source","候选源码","validation","验证诊断").entrySet())actions.addChild(NativeUiTheme.button(t(entry.getValue()),()->part(selected,entry.getKey(),ordinal)));
            if(!text(attempt,"dependencyApiHash").isBlank())card.addChild(NativeUiTheme.button(t("依赖 API 上下文"),()->part(selected,"dependencyApi",ordinal)));if(!text(attempt,"nativeContextHash").isBlank())card.addChild(NativeUiTheme.button(t("实际发送的 Native 上下文"),()->part(selected,"nativeContext",ordinal)));if(!text(attempt,"dependencySourcesHash").isBlank())card.addChild(NativeUiTheme.button(t("实际发送的依赖源码"),()->part(selected,"dependencySources",ordinal)));if(yes(selected,"workspace")&&!text(attempt,"sourceHash").isBlank())card.addChild(NativeUiTheme.button(t("候选文件与增删改"),()->files(selected,ordinal,0)));
            if(index==attempts.size()-1&&text(attempt,"state").equals("ACCEPTED")&&Set.of("READY","ADOPTING").contains(text(selected,"state"))){var approve=new Toggle().setText(t("已审阅候选及依赖，采用为新草稿；不发布或运行"));card.addChild(approve);card.addChild(NativeUiTheme.button(t("采用候选"),()->{if(approve.isOn())send(Map.of("action","coderAdopt","jobId",text(selected,"id"),"revision",text(selected,"revision"),"sourceHash",text(attempt,"candidateHash")),UUID.randomUUID(),false);}));}
        }
        if(Set.of("PENDING","GENERATING","VALIDATING","READY").contains(text(selected,"state"))){var confirm=new Toggle().setText(t("取消后续工作；已发送请求仍可能计费，原结果保留"));summary.addChild(confirm);summary.addChild(NativeUiTheme.button(t("取消后续处理"),()->{if(confirm.isOn())send(Map.of("action","coderCancel","jobId",text(selected,"id"),"revision",text(selected,"revision")),UUID.randomUUID(),false);}));}
        if(!text(selected,"adoptedDraft").isBlank())summary.addChild(NativeUiTheme.button(t("打开已采用草稿"),()->document(host,text(selected,"adoptedDraft"))));
        if(text(selected,"state").equals("FAILED")&&!attempts.isEmpty()){var last=attempts.get(attempts.size()-1).getAsJsonObject();if(text(last,"state").equals("REJECTED")&&!text(last,"rawHash").isBlank())repair(selected);}
        summary.addChild(NativeUiTheme.button(t("只读刷新原请求"),()->observe(text(selected,"id"))));
    }
    private void repair(JsonObject selected){
        var card=WorkspacePanels.card(content,t("基于确定失败新建修复请求"));var requirements=new TextArea();requirements.getLayout().height(55).widthPercent(100);card.addChild(requirements);var attempts=new Selector<Integer>();attempts.setCandidates(List.of(1,2,3));attempts.setValue(1,false);card.addChild(attempts);
        var confirm=new Toggle().setText(t("同意新请求预算与费用，不自动采用或执行"));card.addChild(confirm);var share=new Toggle().setText(t("允许再次发送完整依赖源码"));card.addChild(share);var nativeShare=new Toggle().setText(t("允许再次发送原请求冻结的 Native 上下文"));card.addChild(nativeShare);
        card.addChild(NativeUiTheme.button(t("新建修复请求"),()->{if(!confirm.isOn())return;if(text(selected,"dependencyContextKind").equals("RHINO_SOURCES")&&!share.isOn()||selected.get("nativeTypeCount").getAsInt()+selected.get("nativeOverlayCount").getAsInt()>0&&!nativeShare.isOn()){notice.setText(Component.literal(t("请单独确认共享所需上下文")));return;}send(Map.of("action","coderRepair","jobId",text(selected,"id"),"revision",text(selected,"revision"),"prompt",String.join("\n",requirements.getValue()),"maxAttempts",attempts.getValue().toString(),"shareDependencySources",Boolean.toString(share.isOn()),"shareNativeContext",Boolean.toString(nativeShare.isOn())),UUID.randomUUID(),false);}));
    }
    private void files(JsonObject selected,int attempt,int offset){
        var detail=host.window("coder-files-"+text(selected,"id")+"-"+attempt,t("候选文件与增删改"),520,355);detail.body.clearAllChildren();var root=new UIElement();root.getLayout().widthPercent(100).flex(1);detail.body.addChild(root);var status=WorkspacePanels.text(t("正在读取…"));root.addChild(status);
        read(Map.of("kind","coderFiles","jobId",text(selected,"id"),"revision",text(selected,"revision"),"attempt",Integer.toString(attempt),"offset",Integer.toString(offset))).whenComplete((value,error)->{if(!live()||detail.closed()||root.getParent()!=detail.body)return;if(error!=null){WorkspacePanels.failure(status,error);return;}status.setText(Component.literal(t("只读候选文件")));var list=WorkspacePanels.scroller(root);for(var raw:value.getAsJsonArray("files")){var file=raw.getAsJsonObject();var card=WorkspacePanels.card(list,text(file,"path"));card.addChild(WorkspacePanels.text(text(file,"change")+" · "+text(file,"bytes")+" B"));card.addChild(NativeUiTheme.button(t("查看源码"),()->NativeReadout.open(host,"coder-file-"+text(selected,"id")+"-"+text(file,"hash"),"候选源码","studio.read",page->Map.of("kind","coderFile","jobId",text(selected,"id"),"revision",text(selected,"revision"),"attempt",text(file,"sourceAttempt"),"path",text(file,"path"),"hash",text(file,"hash"),"offset",Integer.toString(page)),1024)));}pager(root,value,offset,8,page->files(selected,attempt,page));});
    }
    private static void pager(UIElement root,JsonObject value,int offset,int size,java.util.function.IntConsumer run){var row=WorkspacePanels.row();row.getLayout().height(25);root.addChild(row);var back=NativeUiTheme.button(t("上一页"),()->run.accept(Math.max(0,offset-size)));back.setActive(offset>0);row.addChild(back);var next=NativeUiTheme.button(t("下一页"),()->run.accept(value.get("nextOffset").getAsInt()));next.setActive(yes(value,"more"));row.addChild(next);}
    static void tick(){OPEN.removeIf(p->!p.live());if(!NativeWorkspaceScreen.visible())return;for(var panel:OPEN)if(!panel.formVisible&&!panel.busy&&panel.job!=null&&Set.of("PENDING","GENERATING","VALIDATING").contains(text(panel.job,"state"))&&System.currentTimeMillis()>=panel.nextPoll)panel.observe(text(panel.job,"id"));}
    private static String t(String value){return ClientLanguage.t(value);}
}
