package dev.mineagent.runtime.neoforge.client.nativeui;

import com.google.gson.*;
import com.lowdragmc.lowdraglib2.gui.ui.elements.*;
import dev.mineagent.runtime.neoforge.client.language.ClientLanguage;
import net.minecraft.network.chat.Component;
import java.util.*;
import java.util.concurrent.*;

/** Secondary conversation views keep original text/provenance and never invoke a model on reads/imports. */
final class NativeConversationExtras {
    private static CompletableFuture<JsonObject> read(String kind,String agent,String conversation,Map<String,String> extra){var args=new LinkedHashMap<String,String>();args.put("kind",kind);args.put("agentId",agent);if(!conversation.isBlank())args.put("conversationId",conversation);args.putAll(extra);return WorkspacePanels.request("conversation.read",args).thenApply(WorkspacePanels::state);}
    static void open(NativeWorkspaceScreen host,String agent,String conversation){if(conversation.isBlank())return;var window=host.window("conversation-details-"+conversation,t("会话详情"),560,380);window.body.clearAllChildren();var nav=WorkspacePanels.row();nav.getLayout().height(25);window.body.addChild(nav);var notice=WorkspacePanels.text(t("读取详情不会调用模型。"));window.body.addChild(notice);var list=WorkspacePanels.scroller(window.body);long[] epoch={0};
        Runnable summary=()->showSummary(host,window,list,notice,agent,conversation,"",++epoch[0],epoch);nav.addChild(button("摘要与来源",summary));nav.addChild(button("请求预算",()->context(host,window,list,notice,agent,conversation,"",++epoch[0],epoch)));nav.addChild(button("旧审计片段",()->imports(host,agent)));summary.run();}
    static void context(NativeWorkspaceScreen host,String agent,String conversation,String message){var window=host.window("message-context-"+message,t("请求详情"),550,370);window.body.clearAllChildren();var notice=WorkspacePanels.text("");window.body.addChild(notice);var list=WorkspacePanels.scroller(window.body);context(host,window,list,notice,agent,conversation,message,0,new long[]{0});}
    private static boolean current(NativeWorkspaceScreen host,WorkspaceWindow window,long token,long[] epoch){return host.activeContext()&&!window.closed()&&token==epoch[0];}
    private static void context(NativeWorkspaceScreen host,WorkspaceWindow window,ScrollerView list,TextElement notice,String agent,String conversation,String message,long token,long[] epoch){
        read("context",agent,conversation,message.isBlank()?Map.of():Map.of("messageId",message)).whenComplete((data,error)->{if(!current(host,window,token,epoch))return;if(error!=null){WorkspacePanels.failure(notice,error);return;}list.clearAllScrollViewChildren();var budget=data.getAsJsonObject("currentBudget");var card=WorkspacePanels.card(list,t("下一次请求的预算"));card.addChild(WorkspacePanels.text(t("输入预算")+" · "+text(budget,"contextTokenBudget")));card.addChild(WorkspacePanels.text(t("摘要请求上限")+" · "+text(budget,"summaryMaxCalls")));card.addChild(WorkspacePanels.text(t("每批摘要输入")+" · "+text(budget,"summaryInputBudget")));card.addChild(WorkspacePanels.text(t("输入估算是保守上界，不是精确 token 计数或费用。")));
            if(data.has("turn")){var turn=data.getAsJsonObject("turn");var details=WorkspacePanels.card(list,t("所选请求"));details.addChild(WorkspacePanels.text(t(text(turn,"requestState"))));details.addChild(WorkspacePanels.text(t("已保存的输入估算")+" · "+text(turn,"estimatedTokens")));if(turn.has("modelReceipt")&&!turn.get("modelReceipt").isJsonNull()){var model=turn.getAsJsonObject("modelReceipt");details.addChild(WorkspacePanels.text(t("请求模型")+" · "+text(model,"requestedModel")));details.addChild(WorkspacePanels.text(t("服务端报告模型")+" · "+text(model,"responseModel")));}if(!text(turn,"summaryId").isBlank())details.addChild(button("查看本次摘要",()->showSummary(host,window,list,notice,agent,conversation,text(turn,"summaryId"),++epoch[0],epoch)));}
            card.addChild(button("详细回执",()->NativeReadout.show(host,"conversation-receipt-"+conversation+message,"请求回执",data)));notice.setText(Component.literal(t("读取完成；没有调用模型。")));
        });
    }
    private static void showSummary(NativeWorkspaceScreen host,WorkspaceWindow window,ScrollerView list,TextElement notice,String agent,String conversation,String summary,long token,long[] epoch){
        read("summary",agent,conversation,summary.isBlank()?Map.of():Map.of("summaryId",summary)).whenComplete((data,error)->{if(!current(host,window,token,epoch))return;if(error!=null){WorkspacePanels.failure(notice,error);return;}list.clearAllScrollViewChildren();var card=WorkspacePanels.card(list,t("摘要与来源"));card.addChild(WorkspacePanels.text(t(text(data,"state"))));if(data.has("sourceValid"))card.addChild(WorkspacePanels.text(data.get("sourceValid").getAsBoolean()?t("来源版本已校验"):t("来源版本未通过校验，不能当作当前记忆。")));if(!text(data,"text").isBlank())card.addChild(WorkspacePanels.text(text(data,"text")));if(!text(data,"error").isBlank())card.addChild(WorkspacePanels.text(text(data,"error")));if(data.has("summaryId")){card.addChild(button("来源与版本详情",()->NativeReadout.show(host,"summary-source-"+text(data,"summaryId"),"摘要来源",data)));if(!text(data,"parentId").isBlank())card.addChild(button("上一版摘要",()->showSummary(host,window,list,notice,agent,conversation,text(data,"parentId"),++epoch[0],epoch)));}notice.setText(Component.literal(t("摘要不替代原文；未校验来源不会用于当前上下文。")));});
    }
    static void imports(NativeWorkspaceScreen host,String agent){if(!host.revealWindow("audit-import-"+agent))new Importer(host,agent);}
    private static final class Importer {
        final NativeWorkspaceScreen host;final String agent;final WorkspaceWindow window;final ScrollerView list;final TextElement notice=WorkspacePanels.text("");boolean busy,running;long epoch,before;String mode="candidates";
        Importer(NativeWorkspaceScreen host,String agent){this.host=host;this.agent=agent;window=host.window("audit-import-"+agent,t("旧审计片段导入"),565,395);var tools=WorkspacePanels.row();tools.getLayout().height(25);window.body.addChild(tools);tools.addChild(button("查找本人旧记录",()->{if(busy)return;running=false;mode="candidates";before=0;load();}));tools.addChild(button("已有导入",()->{if(busy)return;running=false;mode="jobs";before=0;load();}));tools.addChild(button("暂停后续批次",()->running=false));window.body.addChild(WorkspacePanels.text(t("仅导入身份可核验的审计片段到独立归档会话；不会覆盖原会话、自动续聊或执行旧动作。")));window.body.addChild(notice);list=WorkspacePanels.scroller(window.body);window.body.addChild(button("更早记录",this::load));load();}
        boolean current(long token){return host.activeContext()&&!window.closed()&&epoch==token;}
        void load(){if(busy)return;busy=true;long token=++epoch;String selected=mode;read(selected.equals("jobs")?"auditJobs":"auditCandidates",agent,"",Map.of("before",Long.toString(before))).whenComplete((data,error)->{busy=false;if(!current(token))return;if(error!=null){WorkspacePanels.failure(notice,error);return;}list.clearAllScrollViewChildren();if(selected.equals("jobs")){var jobs=data.getAsJsonArray("jobs");for(var raw:jobs)job(raw.getAsJsonObject());if(!jobs.isEmpty())before=jobs.get(jobs.size()-1).getAsJsonObject().get("upperSequence").getAsLong();}else{for(var raw:data.getAsJsonArray("candidates"))candidate(raw.getAsJsonObject());before=data.get("nextBefore").getAsLong();}notice.setText(Component.literal(t("只读核验完成，没有调用模型。")));});}
        void candidate(JsonObject value){var card=WorkspacePanels.card(list,text(value,"sourceConversationId"));card.addChild(WorkspacePanels.text(t(text(value,"state"))));if(!text(value,"state").equals("VERIFIED"))return;card.addChild(WorkspacePanels.text(t("可用审计记录")+" · "+text(value,"availableRecords")));card.addChild(button("导入到独立归档",()->Dialog.showCheckBox(t("确认导入"),t("来源可能已经脱敏、截断或过期，不等于完整聊天恢复。"),yes->{if(!yes||busy)return;busy=true;long token=epoch;var args=new LinkedHashMap<String,String>();args.put("kind","auditStart");args.put("agentId",agent);for(String key:List.of("sourceConversationId","upperSequence","availableRecords","identityHash"))args.put(key,text(value,key));args.put("confirmed","true");WorkspacePanels.request("conversation.write",args).whenComplete((reply,error)->{busy=false;if(!current(token))return;if(error!=null){WorkspacePanels.failure(notice,error);return;}mode="jobs";before=0;running=true;step(WorkspacePanels.state(reply),token);});}).show(window.body)));}
        void job(JsonObject value){var card=WorkspacePanels.card(list,text(value,"sourceConversationId"));card.addChild(WorkspacePanels.text(t(text(value,"state"))+" · "+text(value,"seenRecords")+" / "+text(value,"expectedRecords")));if(Set.of("READY","PAUSED_ARCHIVE").contains(text(value,"state")))card.addChild(button("继续导入",()->{if(busy)return;running=true;step(value,epoch);}));card.addChild(button("打开归档片段",()->{running=false;NativeWorkspaceScreen.openConversation(agent,"AI",text(value,"conversationId"));}));}
        void step(JsonObject value,long token){if(!running||!current(token))return;busy=true;WorkspacePanels.request("conversation.write",Map.of("kind","auditStep","agentId",agent,"jobId",text(value,"jobId"),"cursor",text(value,"cursor"))).whenComplete((reply,error)->{busy=false;if(!current(token))return;if(error!=null){running=false;WorkspacePanels.failure(notice,error);return;}var next=WorkspacePanels.state(reply);list.clearAllScrollViewChildren();job(next);notice.setText(Component.literal(t(text(next,"state"))));if(!text(next,"state").equals("READY")||text(next,"cursor").equals(text(value,"cursor"))){running=false;return;}CompletableFuture.delayedExecutor(200,TimeUnit.MILLISECONDS).execute(()->net.minecraft.client.Minecraft.getInstance().execute(()->step(next,token)));});}
    }
    private static String text(JsonObject object,String key){return object.has(key)&&!object.get(key).isJsonNull()?object.get(key).getAsString():"";}
    private static String t(String text){return ClientLanguage.t(text);}
    private static Button button(String text,Runnable action){return NativeUiTheme.button(t(text),action);}
    private NativeConversationExtras(){}
}
