package dev.mineagent.runtime.neoforge.client.nativeui;

import com.google.gson.*;
import com.lowdragmc.lowdraglib2.gui.ui.UIElement;
import com.lowdragmc.lowdraglib2.gui.ui.elements.*;
import dev.mineagent.runtime.neoforge.client.language.ClientLanguage;
import net.minecraft.network.chat.Component;
import java.util.*;
import java.util.concurrent.CompletableFuture;

/** Native package catalog details retain signed-head fences on every read and explicit write. */
final class NativePackagePanel {
    private static NativePackagePanel smokeLast;
    static Map<String,Object> smokeState(){if(!Boolean.getBoolean("mineagent.nativeUiSmoke"))throw new IllegalStateException("SMOKE_DISABLED");var p=smokeLast;return p==null?Map.of():Map.of("name",p.head.get("name").getAsString(),"rows",p.content.viewContainer.getChildren().size(),"status",p.status.getText().getString(),"pending",p.pendingAsset!=null);}
    static void smokeModels(){smokeLast.models(0);}
    static void smokeVersions(){smokeLast.versions(0);}
    static void smokeRename(){smokeLast.asset("RENAME",smokeLast.head,"Native catalog alias");}
    private final NativeWorkspaceScreen host;private final WorkspaceWindow window;private final ScrollerView content;
    private final TextElement status=WorkspacePanels.text("");private JsonObject head;private long epoch,aliasRevision;private boolean writing;private UUID pendingAsset,pendingWorld;private Button check;
    static void open(NativeWorkspaceScreen host,JsonObject head){String id=head.get("packageId").getAsString();if(host.revealWindow("package-"+id))return;new NativePackagePanel(host,head);}
    private NativePackagePanel(NativeWorkspaceScreen host,JsonObject head){
        if(Boolean.getBoolean("mineagent.nativeUiSmoke"))smokeLast=this;this.host=host;this.head=head.deepCopy();window=host.window("package-"+head.get("packageId").getAsString(),head.get("name").getAsString(),545,385);
        var navigation=WorkspacePanels.row();navigation.getLayout().height(25);window.body.addChild(navigation);
        navigation.addChild(NativeUiTheme.button(t("概览"),this::overview));navigation.addChild(NativeUiTheme.button(t("模型预览"),()->models(0)));navigation.addChild(NativeUiTheme.button(t("历史版本"),()->versions(0)));navigation.addChild(NativeUiTheme.button(t("运行实例"),()->NativeInstancePanel.open(host,head)));navigation.addChild(NativeUiTheme.button(t("刷新"),this::refresh));
        check=NativeUiTheme.button(t("核对上次操作"),this::checkAsset);check.setDisplay(false);window.body.addChild(check);window.body.addChild(status);content=WorkspacePanels.scroller(window.body);overview();
    }
    private Map<String,String> args(String kind,int offset){var args=new LinkedHashMap<String,String>();args.put("kind",kind);args.put("packageId",head.get("packageId").getAsString());args.put("headRevision",head.get("revision").getAsString());args.put("headHash",head.get("canonicalSha256").getAsString());if(offset>=0)args.put("offset",Integer.toString(offset));return args;}
    private CompletableFuture<JsonObject> read(Map<String,String> args){return WorkspacePanels.request("task.historyRead",args).thenApply(WorkspacePanels::state);}
    private long begin(){content.clearAllScrollViewChildren();status.setText(Component.literal(t("正在读取…")));return ++epoch;}
    private boolean current(long ticket){return host.activeContext()&&!window.closed()&&ticket==epoch;}
    private void failed(Throwable error){WorkspacePanels.failure(status,error);}
    private UIElement card(String title){return WorkspacePanels.card(content,title);}
    private void refresh(){long ticket=begin();read(Map.of("kind","package","packageId",head.get("packageId").getAsString(),"headRevision","0","headHash","")).whenComplete((value,error)->{if(!current(ticket))return;if(error!=null){failed(error);return;}head=value;overview();});}
    private void overview(){
        long ticket=begin();read(args("package",-1)).whenComplete((value,error)->{if(!current(ticket))return;if(error!=null){failed(error);return;}head=value;var details=card(value.get("name").getAsString());details.addChild(WorkspacePanels.text(t("版本")+" · "+value.get("version").getAsString()));details.addChild(WorkspacePanels.text(t("启用方式")+" · "+value.get("activationMode").getAsString()));
            var actions=WorkspacePanels.row();actions.getLayout().height(25);details.addChild(actions);actions.addChild(NativeUiTheme.button(t("模型预览"),()->models(0)));actions.addChild(NativeUiTheme.button(t("历史版本"),()->versions(0)));actions.addChild(NativeUiTheme.button(t("运行实例"),()->NativeInstancePanel.open(host,head)));
            var lifecycle=WorkspacePanels.row();lifecycle.getLayout().height(25);details.addChild(lifecycle);
            if(value.get("resourcePackAvailable").getAsBoolean())lifecycle.addChild(NativeUiTheme.button(t("本机资源包"),()->NativeLifecyclePanel.open(host,head,NativeLifecyclePanel.Kind.RESOURCE)));
            if(value.get("dataPackAvailable").getAsBoolean())lifecycle.addChild(NativeUiTheme.button(t("数据包与世界计划"),()->NativeLifecyclePanel.open(host,head,NativeLifecyclePanel.Kind.DATA)));
            if(value.get("bootAvailable").getAsBoolean())lifecycle.addChild(NativeUiTheme.button(t("启动扩展"),()->NativeLifecyclePanel.open(host,head,NativeLifecyclePanel.Kind.BOOT)));
            if(value.get("clientScriptAvailable").getAsBoolean()||value.get("clientJavaAvailable").getAsBoolean())lifecycle.addChild(NativeUiTheme.button(t("本机客户端代码"),()->NativeLifecyclePanel.open(host,head,NativeLifecyclePanel.Kind.CLIENT)));
            var editors=WorkspacePanels.row();editors.getLayout().height(25);details.addChild(editors);
            if(value.get("javaAvailable").getAsBoolean())editors.addChild(NativeUiTheme.button("SERVER Java",()->NativeStudioPanel.fromPackage(host,head,"SERVER","JAVA")));
            if(value.get("scriptAvailable").getAsBoolean())editors.addChild(NativeUiTheme.button("SERVER Rhino",()->NativeStudioPanel.fromPackage(host,head,"SERVER","RHINO")));
            if(value.get("clientJavaAvailable").getAsBoolean())editors.addChild(NativeUiTheme.button("CLIENT Java",()->NativeStudioPanel.fromPackage(host,head,"CLIENT","JAVA")));
            if(value.get("clientScriptAvailable").getAsBoolean())editors.addChild(NativeUiTheme.button("CLIENT Rhino",()->NativeStudioPanel.fromPackage(host,head,"CLIENT","RHINO")));
            var library=card(t("资产管理"));var buttons=WorkspacePanels.row();buttons.getLayout().height(25);library.addChild(buttons);buttons.addChild(NativeUiTheme.button(t("库名称"),this::rename));buttons.addChild(NativeUiTheme.button(t("保存为副本"),()->nameDialog("COPY",head)));
            buttons.addChild(NativeUiTheme.button(t("跨世界资产"),()->NativeAssetsPanel.open(host,head)));
            var technical=card(t("版本校验"));technical.addChild(WorkspacePanels.text(value.get("canonicalSha256").getAsString()));status.setText(Component.literal(""));
        });
    }
    private void models(int offset){long ticket=begin();read(args("models",offset)).whenComplete((value,error)->{if(!current(ticket))return;if(error!=null){failed(error);return;}if(value.getAsJsonArray("items").isEmpty())content.addScrollViewChild(WorkspacePanels.text(t("没有声明可预览的模型JSON。")));for(var raw:value.getAsJsonArray("items")){var model=raw.getAsJsonObject();var card=card(model.get("name").getAsString());card.addChild(WorkspacePanels.text(model.get("path").getAsString()));card.addChild(NativeUiTheme.button(t("打开预览"),()->read(Map.of("kind","modelPreview","packageId",head.get("packageId").getAsString(),"definitionId",model.get("definitionId").getAsString(),"path",model.get("path").getAsString(),"revision",head.get("revision").getAsString())).exceptionally(failure->{failed(failure);return null;})));}pager(offset,16,value,()->models(Math.max(0,offset-16)),()->models(value.get("nextOffset").getAsInt()));status.setText(Component.literal(""));});}
    private void versions(int offset){long ticket=begin();read(args("versions",offset)).whenComplete((value,error)->{if(!current(ticket))return;if(error!=null){failed(error);return;}for(var raw:value.getAsJsonArray("versions")){var version=raw.getAsJsonObject();var card=card(version.get("version").getAsString());card.addChild(WorkspacePanels.text(t("修订")+" "+version.get("revision").getAsString()));var actions=WorkspacePanels.row();actions.getLayout().height(25);card.addChild(actions);actions.addChild(NativeUiTheme.button(t("查看资源"),()->files(version,0)));actions.addChild(NativeUiTheme.button(t("保存为副本"),()->copyVersion(version)));}pager(offset,8,value,()->versions(Math.max(0,offset-8)),()->versions(value.get("nextOffset").getAsInt()));status.setText(Component.literal(t("历史版本复制为独立包，保留原包。")));});}
    private Map<String,String> versionArgs(String kind,JsonObject version,int offset){var args=new LinkedHashMap<>(args(kind,offset));args.put("versionRevision",version.get("revision").getAsString());args.put("snapshotHash",version.get("payloadHash").getAsString());return args;}
    private void files(JsonObject version,int offset){long ticket=begin();read(versionArgs("version",version,offset)).whenComplete((value,error)->{if(!current(ticket))return;if(error!=null){failed(error);return;}for(var raw:value.getAsJsonArray("files")){var file=raw.getAsJsonObject();var card=card(file.get("path").getAsString());card.addChild(WorkspacePanels.text(file.get("mediaType").getAsString()+" · "+file.get("bytes").getAsString()+" B"));card.addChild(NativeUiTheme.button(t("查看内容"),()->fileText(version,file.get("path").getAsString(),0)));}pager(offset,8,value,()->files(version,Math.max(0,offset-8)),()->files(version,value.get("nextOffset").getAsInt()));status.setText(Component.literal(t("读取文件时校验版本和内容哈希。")));});}
    private void fileText(JsonObject version,String path,int offset){long ticket=begin();var args=versionArgs("versionFile",version,offset);args.put("path",path);read(args).whenComplete((value,error)->{if(!current(ticket))return;if(error!=null){failed(error);return;}var body=card(path);body.addChild(WorkspacePanels.text(value.get("text").getAsString()));pager(offset,1024,value,()->fileText(version,path,Math.max(0,offset-1024)),()->fileText(version,path,value.get("nextOffset").getAsInt()));status.setText(Component.literal(t("只读查看")));});}
    private void pager(int offset,int size,JsonObject value,Runnable previous,Runnable next){var row=WorkspacePanels.row();row.getLayout().height(25);var back=NativeUiTheme.button(t("上一页"),previous);back.setActive(offset>0);row.addChild(back);var forward=NativeUiTheme.button(t("下一页"),next);forward.setActive(value.has("more")&&value.get("more").getAsBoolean());row.addChild(forward);content.addScrollViewChild(row);}
    private void nameDialog(String action,JsonObject source){if(writing)return;if(pendingWorld!=null){checkWorld(0);return;}if(pendingAsset!=null){checkAsset();return;}String name=head.get("name").getAsString()+(action.equals("RENAME")?"":" · "+t("副本"));Dialog.stringEditorDialog(t(action.equals("RENAME")?"重命名":"保存为副本"),name,value->(action.equals("RENAME")||!value.isBlank())&&value.length()<=128&&value.codePoints().noneMatch(Character::isISOControl),value->asset(action,source,value)).show(window.body);}
    private void asset(String action,JsonObject source,String name){if(writing||pendingAsset!=null)return;writing=true;pendingAsset=UUID.randomUUID();var args=new LinkedHashMap<String,String>();args.put("kind","change");args.put("action",action);args.put("packageId",source.get("packageId").getAsString());args.put("packageRevision",source.get("revision").getAsString());args.put("canonical",source.get("canonicalSha256").getAsString());args.put("name",name);args.put("shelfId","");args.put("expectedRevision",action.equals("COPY_VERSION")?head.get("revision").getAsString():action.equals("RENAME")?Long.toString(aliasRevision):"0");args.put("confirmed","true");WorkspacePanels.request("package.assetsWrite",args,pendingAsset).whenComplete((receipt,error)->{writing=false;if(window.closed()||!host.activeContext())return;if(error!=null){check.setDisplay(true);failed(error);return;}pendingAsset=null;check.setDisplay(false);status.setText(Component.literal(t("已保存")));if(action.equals("RENAME"))refresh();else{String target=WorkspacePanels.state(receipt).get("target").getAsString();read(Map.of("kind","package","packageId",target,"headRevision","0","headHash","")).thenAccept(value->{if(host.activeContext()&&!window.closed())open(host,value);}).exceptionally(failure->{failed(failure);return null;});}});}
    private void rename(){if(writing)return;long ticket=epoch;WorkspacePanels.request("package.assetsRead",Map.of("kind","inspect","packageId",head.get("packageId").getAsString(),"packageRevision",head.get("revision").getAsString(),"canonical",head.get("canonicalSha256").getAsString())).whenComplete((receipt,error)->{if(!current(ticket))return;if(error!=null){failed(error);return;}aliasRevision=WorkspacePanels.state(receipt).getAsJsonObject("alias").get("revision").getAsLong();nameDialog("RENAME",head);});}
    private void checkAsset(){if(pendingAsset==null){if(pendingWorld!=null)checkWorld(0);return;}if(writing)return;writing=true;UUID operation=pendingAsset;WorkspacePanels.request("package.assetsRead",Map.of("kind","receipt","operationId",operation.toString())).whenComplete((receipt,error)->{writing=false;if(window.closed()||!host.activeContext())return;if(error!=null){failed(error);return;}status.setText(Component.literal(WorkspacePanels.state(receipt).getAsJsonObject("receipt").get("outcome").getAsString()));pendingAsset=null;check.setDisplay(false);refresh();});}
    private void copyVersion(JsonObject version){long ticket=epoch;read(versionArgs("version",version,0)).whenComplete((value,error)->{if(!current(ticket))return;if(error!=null){failed(error);return;}nameDialog("COPY_VERSION",value.getAsJsonObject("manifest"));});}
    private void instances(){long ticket=begin();WorkspacePanels.request("world.inspect",Map.of("packageId",head.get("packageId").getAsString(),"packageRevision",head.get("revision").getAsString())).whenComplete((receipt,error)->{if(!current(ticket))return;if(error!=null){failed(error);return;}var values=receipt.values();var live=JsonParser.parseString(values.get("activations")).getAsJsonArray();var definitions=JsonParser.parseString(values.get("definitions")).getAsJsonArray();var anchor=JsonParser.parseString(values.get("anchor")).getAsJsonObject();for(var raw:definitions){var definition=raw.getAsJsonObject();String id=definition.get("id").getAsString();var box=card(definition.get("name").getAsString());var active=new ArrayList<JsonObject>();for(var a:live){var instance=a.getAsJsonObject();if(instance.get("definitionId").getAsString().equals(id)&&instance.get("state").getAsString().equals("ACTIVE"))active.add(instance);}if(active.isEmpty()&&values.get("activationMode").equals("HOT_RUNTIME")){box.addChild(WorkspacePanels.text(t("原点")+" · "+anchor.get("x").getAsString()+", "+anchor.get("y").getAsString()+", "+anchor.get("z").getAsString()+" · "+anchor.get("dimension").getAsString()));box.addChild(NativeUiTheme.button(t("确认启用"),()->activate(id,anchor)));}for(var instance:active){box.addChild(WorkspacePanels.text(t("已启用")));box.addChild(NativeUiTheme.button(t("停用"),()->{if(writing)return;writing=true;WorkspacePanels.request("world.disable",Map.of("activationId",instance.get("operationId").getAsString())).whenComplete((result,failure)->{writing=false;if(failure!=null)failed(failure);else instances();});}));}}status.setText(Component.literal(values.get("activationMode").equals("HOT_RUNTIME")?t("操作会检查当前版本与权限。") :t("此包使用独立的重载或启动流程。")));});}
    private void activate(String definition,JsonObject anchor){if(writing)return;if(pendingWorld!=null){checkWorld(0);return;}writing=true;pendingWorld=UUID.randomUUID();var args=new LinkedHashMap<String,String>();args.put("packageId",head.get("packageId").getAsString());args.put("packageRevision",head.get("revision").getAsString());args.put("definitionId",definition);for(var field:List.of("dimension","x","y","z"))args.put(field,anchor.get(field).getAsString());args.put("confirmed","true");args.put("autoRestore","false");WorkspacePanels.request("world.activate",args,pendingWorld).whenComplete((receipt,error)->{writing=false;if(window.closed()||!host.activeContext())return;if(error!=null){check.setDisplay(true);failed(error);return;}var value=JsonParser.parseString(receipt.values().get("activation")).getAsJsonObject();status.setText(Component.literal(value.get("state").getAsString()));if(value.get("state").getAsString().equals("ACTIVE")){pendingWorld=null;check.setDisplay(false);refresh();}else check.setDisplay(true);});}
    private void checkWorld(int offset){
        if(pendingWorld==null||writing)return;writing=true;UUID operation=pendingWorld;
        read(Map.of("kind","package","packageId",head.get("packageId").getAsString(),"headRevision","0","headHash","")).thenCompose(fresh->{head=fresh;return WorkspacePanels.request("world.inspect",Map.of("packageId",head.get("packageId").getAsString(),"packageRevision",head.get("revision").getAsString(),"offset",Integer.toString(offset)));}).whenComplete((receipt,error)->{
            writing=false;if(window.closed()||!host.activeContext())return;if(error!=null){failed(error);return;}var rows=JsonParser.parseString(receipt.values().get("activations")).getAsJsonArray();for(var raw:rows){var value=raw.getAsJsonObject();if(value.get("operationId").getAsString().equals(operation.toString())){status.setText(Component.literal(value.get("state").getAsString()+(value.has("error")?" · "+value.get("error").getAsString():"")));if(value.get("state").getAsString().equals("ACTIVE")){pendingWorld=null;check.setDisplay(false);instances();}return;}}if(rows.size()==16)checkWorld(offset+16);else status.setText(Component.literal(t("结果尚未确认，请勿重复提交。")));
        });
    }
    private static String t(String value){return ClientLanguage.t(value);}
}
