package dev.mineagent.runtime.neoforge.client.nativeui;

import com.google.gson.*;
import com.lowdragmc.lowdraglib2.gui.ui.UIElement;
import com.lowdragmc.lowdraglib2.gui.ui.elements.*;
import dev.mineagent.runtime.neoforge.client.language.ClientLanguage;
import net.minecraft.network.chat.Component;
import java.util.*;
import java.util.function.*;
import java.util.concurrent.*;
import static dev.mineagent.runtime.neoforge.client.nativeui.NativeStudioPanel.text;
import static dev.mineagent.runtime.neoforge.client.nativeui.NativeStudioPanel.yes;

/** Task history and persistent schedule/event management. Readouts never resume historical actions. */
final class NativeTasksPanel {
    private static final Set<NativeTasksPanel> OPEN=new HashSet<>();
    private final NativeWorkspaceScreen host;private final WorkspaceWindow window;private final ScrollerView content;private final TextElement notice=WorkspacePanels.text("");
    private final Selector<String> state=new Selector<>(),modeFilter=new Selector<>(),archive=new Selector<>();
    private String category="task",selected="";private int offset;private boolean busy;private long epoch,nextPoll;
    static void open(NativeWorkspaceScreen host){if(!host.revealWindow("tasks"))new NativeTasksPanel(host);}
    private NativeTasksPanel(NativeWorkspaceScreen host){
        this.host=host;window=host.window("tasks",t("任务、调度与事件"),545,390);OPEN.add(this);var tabs=WorkspacePanels.row();tabs.getLayout().height(25);window.body.addChild(tabs);
        for(var tab:Map.of("task","任务历史","schedule","定时与条件任务","event","事件与订阅").entrySet())tabs.addChild(button(t(tab.getValue()),()->switchCategory(tab.getKey())));
        tabs.addChild(button(t("新任务"),()->start(null)));tabs.addChild(button(t("只读刷新"),this::read));
        var filters=WorkspacePanels.row();filters.getLayout().height(25);window.body.addChild(filters);state.getLayout().flex(1);modeFilter.getLayout().flex(1);archive.getLayout().flex(1);filters.addChildren(state,modeFilter,archive);window.body.addChild(notice);content=WorkspacePanels.scroller(window.body);
        state.setOnValueChanged(v->{selected="";offset=0;read();});modeFilter.setOnValueChanged(v->{selected="";offset=0;read();});archive.setOnValueChanged(v->{selected="";offset=0;read();});switchCategory("task");
    }
    private boolean live(){return host.activeContext()&&!window.closed();}
    private String reader(){return category.equals("task")?"task.historyRead":category.equals("schedule")?"task.schedulesRead":"task.eventsRead";}
    private void switchCategory(String kind){selectCategory(kind,"");}
    private void selectCategory(String kind,String selection){if(busy)return;category=kind;selected=selection;offset=0;NativeUiTheme.options(state);state.setCandidates(kind.equals("task")?List.of("ALL","RUNNING","PAUSED","WAITING_FOR_PLAYER","FAILED","COMPLETED","CANCELLED"):kind.equals("schedule")?List.of("ALL","ACTIVE","PAUSED","CANCELLED","EXPIRED","FINISHED"):List.of("ALL","ACTIVE","PAUSED","CANCELLED"));state.setValue("ALL",false);NativeUiTheme.options(modeFilter);modeFilter.setCandidates(List.of("ALL","RECORD_ONLY","AGENT_WAKE","SCRIPT","STATE_PUSH"));modeFilter.setValue("ALL",false);modeFilter.setDisplay(kind.equals("event"));NativeUiTheme.options(archive);archive.setCandidates(List.of("ALL","ACTIVE","ARCHIVED"));archive.setValue("ALL",false);archive.setDisplay(kind.equals("task"));read();}
    private Map<String,String> args(){var args=new LinkedHashMap<String,String>();args.put("kind",selected.isBlank()?"list":"detail");args.put("offset",Integer.toString(offset));if(selected.isBlank()){args.put("state",state.getValue());if(category.equals("task"))args.put("archive",archive.getValue());if(category.equals("event"))args.put("mode",modeFilter.getValue());}else args.put(category.equals("task")?"taskId":category.equals("schedule")?"scheduleId":"subscriptionId",selected);return args;}
    private void read(){if(busy||!live())return;busy=true;long ticket=++epoch;WorkspacePanels.request(reader(),args()).whenComplete((receipt,error)->{busy=false;if(!live()||ticket!=epoch)return;if(error!=null){WorkspacePanels.failure(notice,error);return;}var data=WorkspacePanels.state(receipt);content.clearAllScrollViewChildren();notice.setText(Component.literal(t("读取历史不会新建、恢复或重放操作。")));if(selected.isBlank())list(data);else if(category.equals("task"))task(data);else definition(data);nextPoll=System.currentTimeMillis()+4000;});}
    private void list(JsonObject data){for(var raw:data.getAsJsonArray("items")){var item=raw.getAsJsonObject();var card=WorkspacePanels.card(content,category.equals("task")?text(item,"title"):text(item,"agentName")+" · "+text(item,category.equals("schedule")?"kind":"mode"));card.addChild(WorkspacePanels.text(label(text(item,category.equals("task")?"status":"state"))+" · r"+text(item,"revision")));if(item.has("goal"))card.addChild(WorkspacePanels.text(text(item,"goal")));card.addChild(button(t("查看与管理"),()->{selected=text(item,"id");offset=0;read();}));}pager(content,data,16,page->{offset=page;read();});}
    private void back(UIElement card){card.addChild(button(t("返回列表"),()->{selected="";offset=0;read();}));}
    private void task(JsonObject data){
        var task=data.getAsJsonObject("task");var card=WorkspacePanels.card(content,text(task,"title"));back(card);card.addChild(WorkspacePanels.text(label(text(task,"status"))+" · "+text(task,"completedSteps")+" / "+text(task,"stepCount")));if(!text(task,"reason").isBlank())card.addChild(WorkspacePanels.text(text(task,"reason")));
        var controls=WorkspacePanels.row();controls.getLayout().height(25);card.addChild(controls);if(Set.of("RUNNING","WAITING_FOR_PLAYER").contains(text(task,"status")))controls.addChild(button(t("暂停"),()->taskControl(task,"pause")));if(!Set.of("COMPLETED","CANCELLED").contains(text(task,"status")))controls.addChild(button(t("取消任务"),()->taskControl(task,"cancel")));controls.addChild(button(t("重新规划"),()->start(task)));
        card.addChild(button(t("预算与调用记录"),()->NativeReadout.open(host,"task-budget-"+selected,"预算与调用记录","task.historyRead",page->Map.of("kind","budget","taskId",text(task,"id"),"offset",Integer.toString(page)),8)));
        card.addChild(button(t("完整状态说明"),()->NativeReadout.open(host,"task-reason-"+selected,"完整状态说明","task.historyRead",page->Map.of("kind","reason","taskId",text(task,"id"),"revision",text(task,"revision"),"offset",Integer.toString(page)),1024)));
        card.addChild(button(t("世界动作与回执"),()->batches(text(task,"id"),0)));
        for(var raw:data.getAsJsonArray("steps")){var step=raw.getAsJsonObject();var item=WorkspacePanels.card(content,text(step,"id"));item.addChild(WorkspacePanels.text(label(text(step,"status"))));item.addChild(button(t("步骤依赖"),()->NativeReadout.open(host,"task-deps-"+text(task,"id")+text(step,"id"),"步骤依赖","task.historyRead",page->Map.of("kind","dependencies","taskId",text(task,"id"),"stepId",text(step,"id"),"revision",text(task,"revision"),"offset",Integer.toString(page)),64)));}pager(content,data,8,page->{offset=page;read();});
    }
    private void taskControl(JsonObject task,String action){write("task.control",Map.of("taskId",text(task,"id"),"taskRevision",text(task,"revision"),"control",action),this::read);}
    private void start(JsonObject original){
        String agent=original==null?host.selectedAgentId():text(original,"agentId");if(agent.isBlank()){notice.setText(Component.literal(t("请先选择 AI")));return;}var dialog=host.window("task-request-"+(original==null?"new":text(original,"id")),t(original==null?"新任务":"重新规划"),480,320);dialog.body.clearAllChildren();var goal=new TextArea();goal.getLayout().height(90).widthPercent(100);goal.setValue(new String[]{original==null?"":text(original,"title")},false);dialog.body.addChild(goal);var note=new TextArea();note.getLayout().height(50).widthPercent(100);dialog.body.addChild(note);var consent=new Toggle().setText(t("已核对实际状态；新规划不重放已执行或未知的动作"));if(original!=null)dialog.body.addChild(consent);var scope=new Selector<String>();NativeUiTheme.options(scope);scope.setCandidates(List.of("GENERAL","UI_PACKAGE"));scope.setValue("GENERAL",false);if(original==null)dialog.body.addChild(scope);var status=WorkspacePanels.text("");dialog.body.addChild(status);final UUID[] pending={null};
        dialog.body.addChild(button(t("提交任务"),()->{if(pending[0]!=null||busy)return;if(original!=null&&!consent.isOn())return;String prompt=String.join("\n",goal.getValue());if(prompt.isBlank())return;pending[0]=UUID.randomUUID();var args=original==null?Map.of("agentId",agent,"prompt",prompt,"scope",scope.getValue()):Map.of("sourceTaskId",text(original,"id"),"sourceRevision",text(original,"revision"),"goal",prompt,"note",String.join("\n",note.getValue()),"confirmed","true");WorkspacePanels.request(original==null?"task.start":"task.replan",args,pending[0]).whenComplete((receipt,error)->{if(!live()||dialog.closed())return;if(error!=null){WorkspacePanels.failure(status,error);return;}dialog.close();selectCategory("task",receipt.values().get("taskId"));});}));
    }
    private void definition(JsonObject data){
        boolean schedule=category.equals("schedule");var def=data.getAsJsonObject(schedule?"definition":"subscription");var card=WorkspacePanels.card(content,text(def,"agentName")+" · "+text(def,"mode"));back(card);card.addChild(WorkspacePanels.text(label(text(def,"state"))+" · r"+text(def,"revision")));if(!text(def,"error").isBlank())card.addChild(WorkspacePanels.text(text(def,"error")));
        var controls=WorkspacePanels.row();controls.getLayout().height(25);card.addChild(controls);for(var action:Map.of("PAUSED","暂停","CANCELLED","取消","ACTIVE","恢复").entrySet()){String flag=action.getKey().equals("PAUSED")?"canPause":action.getKey().equals("ACTIVE")?"canResume":"canCancel";var button=button(t(action.getValue()),()->confirmation(def,action.getKey(),schedule));button.setActive(yes(def,flag));controls.addChild(button);}if(data.has("retention")&&yes(data.getAsJsonObject("retention"),"canArchive"))controls.addChild(button(t("归档"),()->confirmation(def,"ARCHIVE",schedule)));
        card.addChild(button(t("定义与来源"),()->NativeReadout.show(host,"managed-definition-"+selected,"定义与来源",data.get(schedule?"spec":"request"))));if(data.has("sourceState"))card.addChild(button(t("当前来源状态"),()->NativeReadout.show(host,"managed-source-"+selected,"当前来源状态",data.get("sourceState"))));
        for(var raw:data.getAsJsonArray(schedule?"occurrences":"history")){var item=raw.getAsJsonObject();var row=WorkspacePanels.card(content,label(text(item,"state")));if(!text(item,"error").isBlank())row.addChild(WorkspacePanels.text(text(item,"error")));row.addChild(button(t("读取本条记录"),()->NativeReadout.show(host,"managed-record-"+text(item,"id"),"执行记录",item)));if(!text(item,"taskId").isBlank())row.addChild(button(t("查看关联任务"),()->{selectCategory("task",text(item,"taskId"));}));if(schedule&&yes(item,"canInspectDeliveries"))row.addChild(button(t("逐人投递回执"),()->NativeReadout.open(host,"schedule-delivery-"+text(item,"id"),"逐人投递回执","task.schedulesRead",page->Map.of("kind","deliveries","scheduleId",text(def,"id"),"occurrenceId",text(item,"id"),"offset",Integer.toString(page)),8)));}pager(content,data,8,page->{offset=page;read();});
    }
    private void confirmation(JsonObject definition,String action,boolean schedule){Dialog.showCheckBox(t("确认变更"),t(action.equals("ACTIVE")?"恢复只使用当前授权，不重放历史，也不重置预算。":action.equals("ARCHIVE")?"归档不删除数据，也不退还已使用的预算。":"停止后续触发，不回滚已经发生的效果。"),confirmed->{if(!confirmed)return;var args=new LinkedHashMap<String,String>();args.put(schedule?"scheduleId":"subscriptionId",text(definition,"id"));args.put("expectedRevision",text(definition,"revision"));args.put("confirmed","true");if(schedule){args.put("kind","write");args.put("action",action);}else{args.put("kind",action.equals("ARCHIVE")?"archive":"state");if(!action.equals("ARCHIVE"))args.put("state",action);}write(schedule?"task.schedulesWrite":"task.eventsWrite",args,this::read);}).show(window.body);}
    private void write(String action,Map<String,String> args,Runnable after){if(busy||!live())return;busy=true;WorkspacePanels.request(action,args,UUID.randomUUID()).whenComplete((value,error)->{busy=false;if(!live())return;if(error!=null){WorkspacePanels.failure(notice,error);return;}after.run();});}
    private void batches(String task,int offset){var dialog=host.window("task-batches-"+task,t("世界动作与回执"),520,355);dialog.body.clearAllChildren();var root=new UIElement();root.getLayout().widthPercent(100).flex(1);dialog.body.addChild(root);var status=WorkspacePanels.text(t("正在读取…"));root.addChild(status);WorkspacePanels.request("task.historyRead",Map.of("kind","world","taskId",task,"offset",Integer.toString(offset))).whenComplete((receipt,error)->{if(!live()||dialog.closed()||root.getParent()!=dialog.body)return;if(error!=null){WorkspacePanels.failure(status,error);return;}var data=WorkspacePanels.state(receipt);status.setText(Component.literal(t("历史读取不会重放动作。")));var list=WorkspacePanels.scroller(root);for(var raw:data.getAsJsonArray("batches")){var batch=raw.getAsJsonObject();var card=WorkspacePanels.card(list,text(batch,"intent")+" · "+text(batch,"state"));card.addChild(WorkspacePanels.text(text(batch,"cursor")+" / "+text(batch,"total")));card.addChild(button(t("读取本轮回执"),()->batch(task,text(batch,"id"),0)));if(yes(batch,"resumableReadOnlyWait"))card.addChild(button(t("恢复只读等待"),()->WorkspacePanels.request("task.historyRead",Map.of("kind","detail","taskId",task,"offset","0")).thenAccept(result->{var current=WorkspacePanels.state(result).getAsJsonObject("task");taskControl(current,"resumeWorldWait");})));}pager(root,data,8,page->batches(task,page));});}
    private void batch(String task,String id,int offset){var dialog=host.window("task-batch-"+id,t("动作回执"),520,350);dialog.body.clearAllChildren();var root=new UIElement();root.getLayout().widthPercent(100).flex(1);dialog.body.addChild(root);var status=WorkspacePanels.text(t("正在读取…"));root.addChild(status);WorkspacePanels.request("task.historyRead",Map.of("kind","worldBatch","taskId",task,"batchId",id,"offset",Integer.toString(offset))).whenComplete((receipt,error)->{if(!live()||dialog.closed()||root.getParent()!=dialog.body)return;if(error!=null){WorkspacePanels.failure(status,error);return;}var data=WorkspacePanels.state(receipt);status.setText(Component.literal(text(data,"state")));var list=WorkspacePanels.scroller(root);for(var raw:data.getAsJsonArray("receipts")){var row=raw.getAsJsonObject();var card=WorkspacePanels.card(list,text(row,"tool")+" · "+text(row,"code"));card.addChild(WorkspacePanels.text(t(yes(row,"verified")?"已有实际验证回执":"尚未验证")));card.addChild(button(t("读取完整回执"),()->receipt(task,id,text(data,"revision"),text(row,"receipt"))));}pager(root,data,8,page->batch(task,id,page));});}
    private void receipt(String task,String batch,String revision,String index){var args=Map.of("kind","worldReceipt","taskId",task,"batchId",batch,"revision",revision,"receipt",index,"offset","0","expectedHash","");WorkspacePanels.request("task.historyRead",args).whenComplete((receipt,error)->{if(!live())return;if(error!=null){WorkspacePanels.failure(notice,error);return;}String hash=text(WorkspacePanels.state(receipt),"hash");NativeReadout.open(host,"task-receipt-"+batch+index,"完整动作回执","task.historyRead",page->Map.of("kind","worldReceipt","taskId",task,"batchId",batch,"revision",revision,"receipt",index,"offset",Integer.toString(page),"expectedHash",hash),4096);});}
    private void pager(UIElement root,JsonObject value,int size,IntConsumer go){var row=WorkspacePanels.row();row.getLayout().height(25);if(root instanceof ScrollerView list)list.addScrollViewChild(row);else root.addChild(row);int count=value.entrySet().stream().filter(e->e.getValue().isJsonArray()).mapToInt(e->e.getValue().getAsJsonArray().size()).max().orElse(size);int current=value.has("offset")?value.get("offset").getAsInt():Math.max(0,value.get("nextOffset").getAsInt()-count);var before=button(t("上一页"),()->go.accept(Math.max(0,current-size)));before.setActive(current>0);row.addChild(before);var after=button(t("下一页"),()->go.accept(value.get("nextOffset").getAsInt()));after.setActive(yes(value,"more"));row.addChild(after);}
    private Button button(String title,Runnable run){return NativeUiTheme.button(title,()->{if(!busy&&live())run.run();});}
    private static String label(String state){return t(switch(state){case "ACTIVE"->"活动";case "RUNNING"->"运行中";case "PAUSED"->"已暂停";case "CANCELLED"->"已取消";case "FAILED"->"失败";case "COMPLETED"->"已完成";case "WAITING_FOR_PLAYER"->"等待玩家";default->state;});}
    static void tick(){OPEN.removeIf(p->!p.live());if(!NativeWorkspaceScreen.visible())return;for(var panel:OPEN)if(!panel.busy&&panel.selected.isBlank()&&System.currentTimeMillis()>=panel.nextPoll)panel.read();}
    private static String t(String value){return ClientLanguage.t(value);}
}
