package dev.mineagent.runtime.neoforge.client.nativeui;

import com.google.gson.*;
import com.lowdragmc.lowdraglib2.gui.ui.UIElement;
import com.lowdragmc.lowdraglib2.gui.ui.elements.*;
import dev.mineagent.runtime.neoforge.client.language.ClientLanguage;
import net.minecraft.network.chat.Component;
import java.util.*;
import java.util.function.BooleanSupplier;

/** One editor shared by the AI's own panel and the integrated F2 workspace. */
public final class NativeBehaviorPanel {
    private record Choice(String id,String label){@Override public String toString(){return t(label);}}
    private static final List<NativeBehaviorPanel> OPEN=new ArrayList<>();
    private final String agent;private final BooleanSupplier current;private final UIElement container;private final Object hostScreen=net.minecraft.client.Minecraft.getInstance().screen;private final Object connection=net.minecraft.client.Minecraft.getInstance().getConnection(),level=net.minecraft.client.Minecraft.getInstance().level;private final TextElement status,progress,targetStatus,modelStatus;
    private final Selector<Choice> mode,strategy,engagement,target,actor,region,routeMode;
    private final Button boost,learning,neural,recovery;
    private final Selector<Integer> radius;private final JsonArray route=new JsonArray();
    private JsonObject state,active,activeDetails;private boolean loading,saving,initialized,actorPending=true,workDirty,rulesDirty,saveBlocked;private long next,editSerial,stopSerial;private String pendingControl;private String selectedActor="ai";
    private static String t(String s){return ClientLanguage.t(s);}
    public static void open(NativeWorkspaceScreen host,String id,String name){if(host.revealWindow("behavior-"+id))return;var window=host.window("behavior-"+id,name+" · "+t("行为模式"),490,420);attach(window.body,id,()->!window.closed());}
    public static void attach(UIElement parent,String agent,BooleanSupplier current){OPEN.add(new NativeBehaviorPanel(parent,agent,current));}
    public static void tick(){for(var panel:List.copyOf(OPEN)){if(!panel.scope()||!panel.current.getAsBoolean()&&!panel.saving&&!panel.loading&&(!panel.workDirty&&!panel.rulesDirty||panel.saveBlocked)){OPEN.remove(panel);continue;}if(panel.hostScreen==net.minecraft.client.Minecraft.getInstance().screen||panel.workDirty||panel.rulesDirty){panel.flush();panel.read();}}}
    private boolean scope(){var mc=net.minecraft.client.Minecraft.getInstance();return connection==mc.getConnection()&&level==mc.level;}
    private void changed(boolean work){if(!initialized||actorPending)return;editSerial++;workDirty|=work;rulesDirty=true;saveBlocked=false;flush();}
    private void flush(){if(!scope()||saving||loading||actorPending)return;if(pendingControl!=null){String action=pendingControl;pendingControl=null;control(action);return;}if(saveBlocked||!workDirty&&!rulesDirty)return;if(workDirty)start();else rules();}

    private NativeBehaviorPanel(UIElement parent,String agent,BooleanSupplier current){
        this.agent=agent;this.current=current;this.container=parent;var scroll=WorkspacePanels.scroller(parent);var body=new UIElement();body.getLayout().widthPercent(100).gapAll(5);scroll.addScrollViewChild(body);
        status=NativeUiTheme.text(t("读取行为状态…"),NativeUiTheme.ACCENT,10);body.addChild(status);targetStatus=NativeUiTheme.text("",NativeUiTheme.MUTED,9);body.addChild(targetStatus);progress=NativeUiTheme.text("",NativeUiTheme.MUTED,9);body.addChild(progress);
        actor=selector(body,"执行身体",new String[][]{{"ai","AI 自己"},{"player","接管我的身体"}});actor.setOnValueChanged(value->{if(saving||loading||workDirty||rulesDirty){choose(actor,selectedActor);status.setText(Component.literal(t("等待当前修改保存后切换身体")));return;}selectedActor=value.id;active=null;initialized=false;actorPending=true;workDirty=rulesDirty=false;saveBlocked=false;next=0;});
        var enhancementRow=WorkspacePanels.row();enhancementRow.getLayout().height(25);body.addChild(enhancementRow);
        boost=NativeUiTheme.button(t("Boost：关闭"),()->toggleEnhancement("boost"));learning=NativeUiTheme.button(t("权重学习模式：开启"),()->toggleEnhancement("learning"));
        boost.getLayout().flex(1);learning.getLayout().flex(1);enhancementRow.addChild(boost);enhancementRow.addChild(learning);
        var supportRow=WorkspacePanels.row();supportRow.getLayout().height(25);body.addChild(supportRow);
        neural=NativeUiTheme.button(t("神经策略：开启"),()->toggleEnhancement("neural"));recovery=NativeUiTheme.button(t("自主脱困：开启"),()->toggleEnhancement("recovery"));
        neural.getLayout().flex(1);recovery.getLayout().flex(1);supportRow.addChild(neural);supportRow.addChild(recovery);
        modelStatus=NativeUiTheme.text("",NativeUiTheme.MUTED,9);body.addChild(modelStatus);body.addChild(NativeUiTheme.button(t("恢复预训练权重"),this::resetWeights));
        mode=selector(body,"主工作",new String[][]{{"IDLE","待命"},{"WANDER","自由活动"},{"FOLLOW","跟随"},{"PATROL","巡逻"},{"GUARD","警戒"},{"FARM","农务"},{"FISH","钓鱼"},{"COMBAT","战斗"}});
        strategy=selector(body,"战斗方式",new String[][]{{"AUTO","自动选择"},{"HIT_AND_RUN","近战跑打"},{"MELEE_COMBO","近战连击控距"},{"RANGED_KITE","远程控距"},{"HOLD_POSITION","守住阵地"},{"DISENGAGE","脱离交战"}});
        engagement=selector(body,"交战规则",new String[][]{{"SELF_DEFENSE","只自卫"},{"PROTECT","保护对象"},{"CLEAR_AREA","清理防区"},{"SPECIFIED","只攻击指定对象"},{"NONE","不攻击"}});
        target=selector(body,"目标 / 保护对象",new String[][]{{"$owner","主人"}});
        region=selector(body,"区域来源",new String[][]{{"CURRENT","当前位置"},{"LOOK","看向的位置"},{"PREVIOUS","沿用当前工作区域"},{"COMBAT","沿用当前防区"}});
        var rangeRow=WorkspacePanels.row();rangeRow.getLayout().height(25);body.addChild(rangeRow);var rangeLabel=WorkspacePanels.text(t("区域半径"));rangeLabel.getLayout().width(128);rangeRow.addChild(rangeLabel);radius=new Selector<>();radius.getLayout().flex(1);radius.setCandidates(List.of(4,8,16));radius.setValue(4,false);rangeRow.addChild(radius);
        routeMode=selector(body,"巡逻方式",new String[][]{{"LOOP","循环"},{"PING_PONG","往返"},{"ONCE","一次"}});
        var points=WorkspacePanels.row();points.getLayout().height(25);body.addChild(points);points.addChild(NativeUiTheme.button(t("添加当前位置为路标"),()->{if(state!=null){route.add(state.getAsJsonObject("context").get("position").deepCopy());progress.setText(Component.literal(t("路标数量")+": "+route.size()));if(mode.getValue().id.equals("PATROL"))changed(true);}}));points.addChild(NativeUiTheme.button(t("清空路标"),()->{while(!route.isEmpty())route.remove(0);if(mode.getValue().id.equals("PATROL"))changed(true);}));
        mode.setOnValueChanged(value->changed(true));strategy.setOnValueChanged(value->changed(false));engagement.setOnValueChanged(value->{if(initialized&&value.id.equals("SPECIFIED")&&(active==null||!active.getAsJsonObject("spec").getAsJsonObject("combat").get("engagement").getAsString().equals("SPECIFIED"))){var choices=new ArrayList<>(target.getCandidates());choices.addFirst(new Choice("","请选择攻击目标"));target.setCandidates(choices);target.setValue(choices.getFirst(),false);}changed(false);});target.setOnValueChanged(value->changed(mode.getValue().id.equals("FOLLOW")));region.setOnValueChanged(value->changed(Set.of("WANDER","GUARD","FARM","FISH").contains(mode.getValue().id)));radius.setOnValueChanged(value->changed(Set.of("WANDER","GUARD","FARM","FISH").contains(mode.getValue().id)));routeMode.setOnValueChanged(value->changed(mode.getValue().id.equals("PATROL")));
        var controls=WorkspacePanels.row();controls.getLayout().height(27);parent.addChild(controls);controls.addChild(NativeUiTheme.button(t("暂停"),()->control("pause")));controls.addChild(NativeUiTheme.button(t("继续"),()->control("resume")));controls.addChild(NativeUiTheme.button(t("全部停止"),()->send("stop_all",new JsonObject())));
        body.addChild(NativeUiTheme.text(t("战斗方式与主工作独立。缺少目标或范围时会说明原因。"),NativeUiTheme.MUTED,8));read();
    }
    private static Selector<Choice> selector(UIElement body,String label,String[][] choices){var row=WorkspacePanels.row();row.getLayout().height(25);body.addChild(row);var title=WorkspacePanels.text(t(label));title.getLayout().width(128);row.addChild(title);var select=new Selector<Choice>();select.getLayout().flex(1);var values=Arrays.stream(choices).map(p->new Choice(p[0],p[1])).toList();select.setCandidates(values);select.setValue(values.getFirst(),false);row.addChild(select);return select;}
    private static void choose(Selector<Choice> selector,String id){for(var value:selector.getCandidates())if(value.id.equals(id)){selector.setValue(value,false);return;}}
    private void read(){if(loading||saving||!NativeWorkspaceConnection.ready()||System.currentTimeMillis()<next)return;loading=true;next=System.currentTimeMillis()+1000;
        WorkspacePanels.request("behavior.read",Map.of("agentId",agent)).whenComplete((receipt,error)->{loading=false;if(!scope())return;if(error!=null){WorkspacePanels.failure(status,error);saveBlocked=true;return;}state=WorkspacePanels.state(receipt);updateEnhancementLabels();actorPending=false;active=null;
            for(var row:state.getAsJsonArray("skills")){var session=row.getAsJsonObject().getAsJsonObject("session");if(session.getAsJsonObject("spec").get("actor").getAsString().equals(actor.getValue().id)&&!Set.of("COMPLETED","CANCELLED","FAILED").contains(session.get("state").getAsString())&&!session.get("reason").getAsString().equals("TEMPORARY_WORK")){active=session;activeDetails=row.getAsJsonObject();}}
            if(active==null){status.setText(Component.literal(t("待命")));progress.setText(Component.literal(""));targetStatus.setText(Component.literal(""));}else{var spec=active.getAsJsonObject("spec");String targetName=activeDetails.getAsJsonObject("combat").get("targetName").getAsString();if(targetName.isBlank())targetName=spec.get("target").getAsString().equals("$owner")?t("主人"):spec.get("area").isJsonNull()?"":t("工作区域");targetStatus.setText(Component.literal(t("当前目标")+": "+targetName));status.setText(Component.literal(t(label(spec.get("kind").getAsString()))+" · "+t(switch(active.get("state").getAsString()){case "PAUSED"->"已暂停";case "WAITING"->"等待条件恢复";case "SUSPENDED"->"正在防御，之后继续工作";default->"执行中";})));progress.setText(Component.literal(t(reason(active.get("reason").getAsString()))+" · "+progress(active.getAsJsonObject("counters"),spec.get("kind").getAsString())));if(!initialized){choose(mode,spec.get("kind").getAsString());choose(strategy,spec.getAsJsonObject("combat").get("strategy").getAsString());choose(engagement,spec.getAsJsonObject("combat").get("engagement").getAsString());}}
            if(!initialized&&active==null&&state.has("defaults")){var policy=state.getAsJsonObject("defaults").getAsJsonObject(actor.getValue().id);choose(mode,"IDLE");choose(strategy,policy.get("strategy").getAsString());choose(engagement,policy.get("engagement").getAsString());}
            if(!initialized){var options=new ArrayList<Choice>();options.add(new Choice("$owner","主人"));for(var row:state.getAsJsonObject("context").getAsJsonArray("entities")){var e=row.getAsJsonObject();options.add(new Choice(e.get("id").getAsString(),e.get("name").getAsString()));}target.setCandidates(options);target.setValue(options.getFirst(),false);if(active!=null){var spec=active.getAsJsonObject("spec");var policy=spec.getAsJsonObject("combat");String selected=policy.get("engagement").getAsString().equals("PROTECT")?policy.get("protect").getAsString():policy.get("engagement").getAsString().equals("SPECIFIED")?policy.get("target").getAsString():spec.get("target").getAsString();if(!selected.isBlank()&&options.stream().noneMatch(option->option.id.equals(selected))){options.add(new Choice(selected,"当前目标（暂不可见）"));target.setCandidates(options);}choose(target,selected);if(policy.has("area")&&!policy.get("area").isJsonNull())choose(region,"COMBAT");else if(!spec.get("area").isJsonNull())choose(region,"PREVIOUS");while(!route.isEmpty())route.remove(0);for(var point:spec.getAsJsonArray("route")){var xyz=point.getAsJsonObject();var entry=new JsonArray();for(String axis:List.of("x","y","z"))entry.add(xyz.get(axis));route.add(entry);}choose(routeMode,!spec.get("repeat").getAsBoolean()?"ONCE":spec.get("pingPong").getAsBoolean()?"PING_PONG":"LOOP");}else if(state.has("defaults")){var policy=state.getAsJsonObject("defaults").getAsJsonObject(actor.getValue().id);String saved=policy.get("engagement").getAsString().equals("PROTECT")?policy.get("protect").getAsString():policy.get("target").getAsString();if(!saved.isBlank()&&options.stream().noneMatch(option->option.id.equals(saved))){options.add(new Choice(saved,"当前目标（暂不可见）"));target.setCandidates(options);}if(!saved.isBlank())choose(target,saved);if(policy.has("area")&&!policy.get("area").isJsonNull())choose(region,"COMBAT");}initialized=true;}flush();
        });
    }
    private static String reason(String code){return switch(code){case "CHECKING_LAST_THREAT_POSITION"->"检查上次发现敌人的位置";case "WAITING_FOR_CROP_GROWTH"->"等待作物成熟";case "WAITING_FOR_REAL_BITE"->"等待鱼咬钩";case "SEED_REQUIRED_FOR_REPLANT","SEED_NOT_READY"->"等待补种种子";case "INVENTORY_FULL"->"背包已满，等待整理";case "DEFENDING_THEN_RESUME"->"正在防御，之后继续工作";case "THREAT_CLEARANCE_HYSTERESIS"->"正在确认威胁已解除";case "USER_PAUSED","INPUT_OR_MENU_PAUSED"->"已暂停";case "IDLE_BY_PLAYER","NO_ELIGIBLE_THREATS","ENGAGEMENT_DISABLED"->"待命";case "FOLLOW_DISTANCE_SATISFIED","FOLLOW_HYSTERESIS"->"保持跟随距离";case "PROTECTED_TARGET_ABSENT"->"等待保护对象";case "PROTECTING_TARGET"->"正在保护目标";case "WAITING_CHUNKS"->"等待区块加载";case "WAITING_RESPAWN"->"等待重生后恢复";case "RESPAWN_REGION_REQUIRES_RECHECK"->"重生位置变化，请重新确认工作区域";case "TARGET_UNREACHABLE_WAITING_CHANGE"->"目标暂不可达，等待通路变化";case "RESTART_REQUIRES_RESUME"->"重启后等待恢复";case "RESTART_REQUIRES_RECONCILIATION"->"需要核对旧操作后恢复";default->code.isEmpty()?"执行中":"等待条件恢复";};}
    private static String progress(JsonObject c,String kind){if(kind.equals("COMBAT")||count(c,"verifiedHits")>0)return t("有效命中")+": "+count(c,"verifiedHits")+" · "+t("造成伤害")+": "+String.format(java.util.Locale.ROOT,"%.1f",count(c,"damageMilliHearts")/1000d)+" · "+t("承受伤害")+": "+String.format(java.util.Locale.ROOT,"%.1f",count(c,"nativeDamageTakenMilli")/1000d);return t("已收获")+": "+count(c,"harvested")+" · "+t("已补种")+": "+count(c,"planted")+" · "+t("渔获")+": "+count(c,"fishingCatches");}
    private static long count(JsonObject c,String key){return c.has(key)?c.get(key).getAsLong():0;}
    private String label(String key){return switch(key){case "IDLE"->"待命";case "WANDER"->"自由活动";case "FOLLOW"->"跟随";case "PATROL"->"巡逻";case "GUARD"->"警戒";case "FARM"->"农务";case "FISH"->"钓鱼";default->"战斗";};}
    private JsonObject base(){if(state==null||actorPending)throw new IllegalStateException(t("等待状态读取"));var n=new JsonObject();n.addProperty("id","mode_"+UUID.randomUUID().toString().substring(0,8));n.addProperty("actor",actor.getValue().id);n.addProperty("kind",mode.getValue().id);n.addProperty("dimension",state.getAsJsonObject("context").get("dimension").getAsString());n.addProperty("expected_revision",0);return n;}
    private void area(JsonObject n){
        if(Set.of("PREVIOUS","COMBAT").contains(region.getValue().id)){if(active==null&&!region.getValue().id.equals("COMBAT"))throw new IllegalArgumentException(t("当前没有工作区域"));var source=active==null?state.getAsJsonObject("defaults").getAsJsonObject(actor.getValue().id):region.getValue().id.equals("COMBAT")?active.getAsJsonObject("spec").getAsJsonObject("combat"):active.getAsJsonObject("spec");if(!source.has("area")||source.get("area").isJsonNull())throw new IllegalArgumentException(t("当前没有工作区域"));var a=source.getAsJsonObject("area");for(String key:List.of("min","max")){var point=a.getAsJsonObject(key);var list=new JsonArray();for(String axis:List.of("x","y","z"))list.add(point.get(axis));n.add(key,list);}return;}
        var p=state.getAsJsonObject("context").getAsJsonArray(region.getValue().id.equals("LOOK")?"look":"position");if(p.size()!=3)throw new IllegalArgumentException(t("请先看向目标区域，或选择当前位置"));int radius=this.radius.getValue();var min=new JsonArray();var max=new JsonArray();for(int i=0;i<3;i++){int v=(int)Math.floor(p.get(i).getAsDouble());min.add(v-(i==1?1:radius));max.add(v+(i==1?1:radius));}n.add("min",min);n.add("max",max);
    }
    private JsonObject combat(){var n=new JsonObject();n.addProperty("strategy",strategy.getValue().id);n.addProperty("engagement",engagement.getValue().id);switch(engagement.getValue().id){case "PROTECT"->n.addProperty("protect",target.getValue().id);case "SPECIFIED"->{if(target.getValue().id.isBlank())throw new IllegalArgumentException(t("请选择攻击目标"));n.addProperty("target",target.getValue().id.equals("$owner")?state.getAsJsonObject("context").get("ownerId").getAsString():target.getValue().id);}case "CLEAR_AREA"->area(n);}return n;}
    private JsonObject enhancements(){return state==null||!state.has("enhancements")?null:state.getAsJsonObject("enhancements").getAsJsonObject(actor.getValue().id);}
    private JsonObject model(){return state==null||!state.has("enhancements")?null:state.getAsJsonObject("enhancements").getAsJsonObject("models").getAsJsonObject(actor.getValue().id);}
    private void resetWeights(){var model=model();var profile=enhancements();if(model==null||profile==null||actorPending)return;var input=new JsonObject();input.addProperty("actor",actor.getValue().id);input.addProperty("expected_revision",profile.get("revision").getAsLong());input.addProperty("expected_model_version",model.get("version").getAsLong());input.addProperty("resetWeights",true);send("set_actor_enhancements",input);}
    private void updateEnhancementLabels(){var profile=enhancements();if(profile==null)return;
        boost.setText(Component.literal(t(profile.get("boost").getAsBoolean()?"Boost：开启":"Boost：关闭")));
        learning.setText(Component.literal(t(profile.get("learning").getAsBoolean()?"权重学习模式：开启":"权重学习模式：关闭")));
        neural.setText(Component.literal(t(profile.get("neural").getAsBoolean()?"神经策略：开启":"神经策略：关闭")));
        recovery.setText(Component.literal(t(profile.get("recovery").getAsBoolean()?"自主脱困：开启":"自主脱困：关闭")));
        var m=model();if(m!=null)modelStatus.setText(Component.literal(t(switch(m.get("status").getAsString()){case "LOADING_CHECKPOINT"->"读取已保存权重…";case "TRAINING_CANDIDATE"->"正在学习；继续使用已验证权重";case "KEPT_PREVIOUS_WEIGHTS","TRAINING_REJECTED"->"保留当前已验证权重";case "PRETRAINED_CHECKPOINT_INVALID"->"已保存权重不可用，使用预训练权重";case "LEARNED_VALIDATED"->m.has("checkpointSaved")&&m.get("checkpointSaved").getAsBoolean()?"使用已保存的学习权重":"使用本局学习权重";case "RESTORED_CHECKPOINT"->"使用已保存的学习权重";default->"使用预训练权重";})+" · "+t("样本")+": "+m.get("samples").getAsLong()));
    }
    private void toggleEnhancement(String field){var profile=enhancements();if(profile==null||actorPending)return;var input=new JsonObject();input.addProperty("actor",actor.getValue().id);input.addProperty("expected_revision",profile.get("revision").getAsLong());input.addProperty(field,!profile.get(field).getAsBoolean());send("set_actor_enhancements",input);}
    private void start(){try{var n=base();String kind=mode.getValue().id;if(Set.of("WANDER","GUARD","FARM","FISH").contains(kind))area(n);if(kind.equals("FOLLOW"))n.addProperty("target",target.getValue().id);if(kind.equals("PATROL")){if(route.isEmpty())throw new IllegalArgumentException(t("请先添加路标"));n.add("route",route.deepCopy());n.addProperty("repeat",!routeMode.getValue().id.equals("ONCE"));n.addProperty("ping_pong",routeMode.getValue().id.equals("PING_PONG"));}n.add("combat",combat());send("set_behavior_mode",n);}catch(Exception e){saveBlocked=true;WorkspacePanels.failure(status,e);}}
    private void rules(){try{if(actorPending)throw new IllegalStateException(t("等待状态读取"));if(active==null){var n=base();n.addProperty("kind","IDLE");n.addProperty("only_if_idle",true);n.add("combat",combat());send("set_behavior_mode",n);return;}var n=identity();n.add("combat",combat());send("set_combat_policy",n);}catch(Exception e){saveBlocked=true;WorkspacePanels.failure(status,e);}}
    private JsonObject identity(){if(active==null)throw new IllegalStateException(t("当前没有运行任务"));var n=new JsonObject();n.addProperty("id",active.getAsJsonObject("spec").get("id").getAsString());n.add("expected_revision",active.get("revision"));return n;}
    private void control(String action){if(saving||loading){pendingControl=action;return;}try{var n=identity();n.addProperty("action",action);send("control_behavior",n);}catch(Exception e){WorkspacePanels.failure(status,e);}}
    private void send(String tool,JsonObject n){if(tool.equals("stop_all")){stopSerial=++editSerial;pendingControl=null;saveBlocked=false;}else if(saving)return;boolean modeWrite=Set.of("set_behavior_mode","set_combat_policy").contains(tool),submittedWork=modeWrite&&workDirty,submittedRules=modeWrite&&rulesDirty;long submitted=editSerial;if(modeWrite||tool.equals("stop_all")){workDirty=rulesDirty=false;}saving=true;status.setText(Component.literal(t("正在保存…")));
        WorkspacePanels.request("behavior.write",Map.of("agentId",agent,"tool",tool,"source",n.toString())).whenComplete((receipt,error)->{if(submitted<stopSerial)return;saving=false;if(!scope())return;if(error!=null){workDirty|=submittedWork;rulesDirty|=submittedRules;saveBlocked=true;WorkspacePanels.failure(status,error);return;}
            var result=WorkspacePanels.state(receipt);String outcome=result.has("status")?result.get("status").getAsString():"";if(Set.of("REJECTED","FAILED","UNKNOWN").contains(outcome)){saveBlocked=true;workDirty|=submittedWork;rulesDirty|=submittedRules;status.setText(Component.literal(t("保存未完成，请查看状态后重新修改。")));return;}
            status.setText(Component.literal(t(editSerial==submitted?"已保存":"正在保存…")));next=0;read();
        });}

    private static NativeBehaviorPanel smoke(String agent){if(!Boolean.getBoolean("mineagent.skillSmoke"))throw new IllegalStateException("SMOKE_DISABLED");return OPEN.stream().filter(p->p.agent.equals(agent)&&p.current.getAsBoolean()&&p.hostScreen==net.minecraft.client.Minecraft.getInstance().screen).reduce((a,b)->b).orElseThrow();}
    public static boolean smokeReady(String agent){return smoke(agent).state!=null&&!smoke(agent).loading;}
    public static void smokeSelect(String agent,String field,String value){var p=smoke(agent);var selector=switch(field){case "mode"->p.mode;case "strategy"->p.strategy;case "engagement"->p.engagement;case "region"->p.region;default->throw new IllegalArgumentException();};for(var candidate:selector.getCandidates())if(candidate.id.equals(value)){selector.setValue(candidate,true);return;}throw new IllegalArgumentException("SMOKE_CHOICE_MISSING");}
    private static Button find(UIElement node,String label){if(node instanceof Button b&&b.text.getText().getString().equals(label))return b;for(var child:node.getChildren()){var found=find(child,label);if(found!=null)return found;}return null;}
    public static void smokeClick(String agent,String label,boolean release){smokeClickElement(smoke(agent).container,t(label),release);}
    static void smokeClickElement(UIElement root,String label,boolean release){if(!Boolean.getBoolean("mineagent.skillSmoke"))throw new IllegalStateException("SMOKE_DISABLED");var b=find(root,label);if(b==null)throw new IllegalStateException("BUTTON_NOT_FOUND");var screen=(com.lowdragmc.lowdraglib2.gui.holder.ModularUIScreen)net.minecraft.client.Minecraft.getInstance().screen;float x=b.getPositionX()+b.getSizeWidth()/2,y=b.getPositionY()+b.getSizeHeight()/2;screen.modularUI.refreshHoveredElementAtScreen(x,y);var widget=com.lowdragmc.lowdraglib2.gui.ui.ModularUIClientAccess.getWidget(screen.modularUI);var event=new net.minecraft.client.input.MouseButtonEvent(x,y,new net.minecraft.client.input.MouseButtonInfo(0,0));if(release)widget.mouseReleased(event);else widget.mouseClicked(event,false);}
    private NativeBehaviorPanel(){throw new AssertionError();}
}
