package dev.mineagent.runtime.neoforge.client.nativeui;

import com.google.gson.*;
import com.lowdragmc.lowdraglib2.gui.ui.UIElement;
import com.lowdragmc.lowdraglib2.gui.ui.elements.*;
import dev.mineagent.runtime.api.config.PanelSection;
import dev.mineagent.runtime.neoforge.MineAgentRuntimeServices;
import net.minecraft.client.Minecraft;
import net.minecraft.core.BlockPos;
import net.minecraft.server.level.ServerPlayer;
import net.minecraft.world.level.block.Blocks;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.ClientTickEvent;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.Function;

/** Isolated acceptance through visible controls and independent authoritative readback. */
@EventBusSubscriber(modid="mineagent_runtime",value=Dist.CLIENT)
public final class NativeModulesSmokeClient {
    private static CompletableFuture<Map<String,Object>> result;private static UUID agent,mediaId;private static boolean design;private static com.sun.net.httpserver.HttpServer mediaHttp;private static String mediaUrl;private static int stage,ticks,wait;private static boolean busy;private static BlockPos marker;private static final List<Object> checks=new ArrayList<>();
    public static CompletableFuture<Map<String,Object>> run(UUID id){if(!Boolean.getBoolean("mineagent.skillSmoke"))throw new IllegalStateException("SMOKE_DISABLED");design=false;agent=id;stage=ticks=wait=0;busy=false;checks.clear();result=new CompletableFuture<>();NativeWorkspaceScreen.openForAgent(id.toString(),"界面模块验收");org.lwjgl.glfw.GLFW.glfwFocusWindow(Minecraft.getInstance().getWindow().handle());return result;}
    public static CompletableFuture<Map<String,Object>> runDesign(UUID id){var future=run(id);design=true;stage=100;return future;}
    public static CompletableFuture<Map<String,Object>> runMedia(UUID id){var future=run(id);stage=200;future.whenComplete((value,error)->{if(mediaHttp!=null){mediaHttp.stop(0);mediaHttp=null;}});return future;}
    public static CompletableFuture<Map<String,Object>> runMods(UUID id){var future=run(id);stage=300;return future;}
    public static CompletableFuture<Map<String,Object>> runContents(UUID id){var future=run(id);stage=400;return future;}
    private static void serverAsync(Function<ServerPlayer,CompletableFuture<?>> action,String label){busy=true;var mc=Minecraft.getInstance();mc.getSingleplayerServer().submit(()->action.apply(mc.getSingleplayerServer().getPlayerList().getPlayer(mc.player.getUUID()))).thenCompose(value->value).whenComplete((value,error)->mc.execute(()->{busy=false;if(error!=null)result.completeExceptionally(error);else next(label);}));}
    private static void seedItem(ServerPlayer p)throws Exception{
        byte[] bytes="function create(context) { return {}; }".getBytes(java.nio.charset.StandardCharsets.UTF_8);String hash=dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer.sha256(bytes);var side=dev.mineagent.runtime.api.packages.RuntimeResourceSide.SERVER;
        var definition=new dev.mineagent.runtime.api.packages.RuntimeDefinition(UUID.randomUUID(),"目录水晶剑",dev.mineagent.runtime.api.packages.RuntimeDefinitionKind.ITEM,"server",Set.of(),Map.of(),1);
        var parsed=new dev.mineagent.runtime.worker.generation.ParsedRuntimePackage("目录包容器","1.0.0",dev.mineagent.runtime.api.packages.RuntimePackageType.CONTENT,dev.mineagent.runtime.api.packages.ActivationMode.HOT_RUNTIME,Map.of(),Set.of(),Map.of("server",new dev.mineagent.runtime.api.packages.RuntimeEntrypoint("server/main.js",side,hash)),List.of(definition),List.of(new dev.mineagent.runtime.worker.generation.GeneratedFile("server/main.js",side,"application/javascript",hash,bytes)));
        dev.mineagent.runtime.neoforge.ui.ServerPackageRuntime.get(p.level().getServer()).importOwned(p,UUID.randomUUID(),parsed);
    }
    public static CompletableFuture<Map<String,Object>> runLayout(UUID id){var future=run(id);stage=500;return future;}
    private static NativeWorkspaceScreen host(){return (NativeWorkspaceScreen)Minecraft.getInstance().screen;}
    private static UIElement find(UIElement root,String id){if(root.getId().equals(id))return root;for(var child:root.getChildren()){var value=find(child,id);if(value!=null)return value;}return null;}
    private static boolean click(String text){if(!Minecraft.getInstance().isWindowActive())return false;var candidates=new ArrayList<Button>();buttons(host().smokeRoot(),text,candidates);Collections.reverse(candidates);for(var button:candidates){if(!button.isActive()||button.getSizeWidth()<1||button.getSizeHeight()<1)continue;float x=button.getPositionX()+button.getSizeWidth()/2,y=button.getPositionY()+button.getSizeHeight()/2;var screen=host();boolean scrolled=false;for(var parent=button.getParent();parent!=null;parent=parent.getParent())if(parent instanceof ScrollerView scroll){float low=scroll.viewPort.getContentY(),high=low+scroll.viewPort.getContentHeight(),range=scroll.getContainerHeight()-scroll.viewPort.getContentHeight();if(range>0&&(y-button.getSizeHeight()/2<low||y+button.getSizeHeight()/2>high)){if(scroll.viewPort.getContentHeight()<button.getSizeHeight())continue;scroll.verticalScroller.setNormalizedValue(Math.clamp(scroll.verticalScroller.getNormalizedValue()+(y-(low+high)/2)/range,0,1));scrolled=true;break;}}if(scrolled)continue;if(x<0||y<0||x>=screen.width||y>=screen.height)continue;screen.modularUI.refreshHoveredElementAtScreen(x,y);boolean hovered=false;for(var node=screen.modularUI.getLastHoveredElement();node!=null;node=node.getParent())if(node==button)hovered=true;if(!hovered)continue;var widget=com.lowdragmc.lowdraglib2.gui.ui.ModularUIClientAccess.getWidget(screen.modularUI);var event=new net.minecraft.client.input.MouseButtonEvent(x,y,new net.minecraft.client.input.MouseButtonInfo(0,0));widget.mouseClicked(event,false);widget.mouseReleased(event);return true;}return false;}
    private static void buttons(UIElement root,String text,List<Button> out){if(root instanceof Button button&&(text.equals(button.getId())||text.equals(button.text.getText().getString())))out.add(button);for(var child:root.getChildren())buttons(child,text,out);}
    private static boolean hasText(UIElement root,String text){if(root instanceof TextElement label&&label.getText().getString().equals(text)&&label.getSizeHeight()>0)return true;for(var child:root.getChildren())if(hasText(child,text))return true;return false;}
    private static void screenshot(String name){var mc=Minecraft.getInstance();net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),image->{try(image){var out=java.nio.file.Files.createDirectories(mc.gameDirectory.toPath().resolve("module-ui-images"));image.writeToFile(out.resolve(name+".png"));}catch(Exception error){result.completeExceptionally(error);}});}
    private static boolean rawJson(UIElement element){if(element instanceof NativeCodeEditor)return true;if(element instanceof TextElement text){String value=text.getText().getString();if(value.contains("{\"")||value.contains("\":")||value.startsWith("[{"))return true;}for(var child:element.getChildren())if(rawJson(child))return true;return false;}
    private static void next(String check){checks.add(check);stage++;wait=0;}
    private static void require(boolean value,String error){if(!value)throw new IllegalStateException(error);}
    @FunctionalInterface private interface ServerCheck{boolean apply(ServerPlayer player)throws Exception;}
    private static void server(ServerCheck action,String label){busy=true;var mc=Minecraft.getInstance();mc.getSingleplayerServer().submit(()->{try{return action.apply(mc.getSingleplayerServer().getPlayerList().getPlayer(mc.player.getUUID()));}catch(Exception failure){throw new CompletionException(failure);}}).whenComplete((ok,error)->mc.execute(()->{busy=false;if(error!=null)result.completeExceptionally(error);else if(ok)next(label);}));}
    @SubscribeEvent public static void tick(ClientTickEvent.Post event){if(result==null||result.isDone())return;try{
        if(++ticks>(design?18000:3000))throw new IllegalStateException("MODULE_UI_TIMEOUT_"+stage);if(ticks%100==0)java.nio.file.Files.writeString(Minecraft.getInstance().gameDirectory.toPath().resolve("module-ui-progress.json"),new Gson().toJson(Map.of("stage",stage,"ticks",ticks,"checks",checks,"focused",Minecraft.getInstance().isWindowActive())));if(busy||!NativeWorkspaceConnection.ready()||!(Minecraft.getInstance().screen instanceof NativeWorkspaceScreen))return;
        switch(stage){
            case 500->{if(++wait<10)return;var placeholder=new TextField();placeholder.textFieldStyle(style->style.placeholder(net.minecraft.network.chat.Component.literal("保留自定义提示")));NativeUiTheme.controls(placeholder);require(placeholder.getTextFieldStyle().getValueImmediate(com.lowdragmc.lowdraglib2.gui.ui.style.PropertyRegistry.PLACEHOLDER).getString().equals("保留自定义提示"),"AUTHORED_PLACEHOLDER_WAS_CLEARED");var toolbar=find(host().smokeRoot(),"workspace-toolbar");var brand=find(host().smokeRoot(),"workspace-brand");require(toolbar!=null&&brand!=null,"WORKSPACE_BRAND_MISSING");require(Math.abs(brand.getPositionY()+brand.getSizeHeight()/2-toolbar.getPositionY()-toolbar.getSizeHeight()/2)<=1.1,"WORKSPACE_BRAND_NOT_CENTERED");require(!hasText(toolbar,"尺寸")&&!hasText(toolbar,"界面尺寸"),"SCALE_CONTROL_STILL_ON_PRIMARY_TOOLBAR");NativeGenerationPanel.open(host());next("brand-centered-and-scale-removed-from-toolbar");}
            case 501->{if(++wait<10)return;var selector=find(host().smokeRoot(),"generation-category");require(selector!=null&&selector.getSizeWidth()>=96&&selector.getSizeHeight()>=23,"SELECTOR_SHRANK_BELOW_READABLE_SIZE");var candidates=new ArrayList<Button>();buttons(host().smokeRoot(),"创建内容",candidates);require(candidates.stream().anyMatch(button->button.getPositionX()>=selector.getPositionX()+selector.getSizeWidth()),"SELECTOR_OVERLAPS_ADJACENT_CONTROL");screenshot("selector-layout");WorkspacePanels.settings(host());next("selector-does-not-overlap-create-button");}
            case 502->{if(++wait<25)return;var fields=find(host().smokeRoot(),"settings-fields");var footer=find(host().smokeRoot(),"settings-footer");if(!(fields instanceof ScrollerView scroll)||footer==null)return;require(scroll.viewPort.getContentHeight()>=25,"SETTINGS_CONTENT_HAS_NO_USABLE_HEIGHT");require(footer.getPositionY()+footer.getSizeHeight()<=host().height-20,"SETTINGS_FOOTER_OUTSIDE_VIEW");scroll.verticalScroller.setNormalizedValue(1);next("settings-viewport-scrolls-with-visible-footer");}
            case 503->{if(++wait<8)return;screenshot("compact-settings");if(click("界面尺寸"))next("scale-opens-from-settings-submenu");}
            case 504->{if(++wait<6)return;require(find(host().smokeRoot(),"gui-scale-4")!=null,"SETTINGS_SCALE_OPTIONS_MISSING");NativeReadout.show(host(),"layout-graph","恢复操作结果",JsonParser.parseString("{\"status\":\"CONFLICT\",\"written\":0,\"conflicts\":[{\"dimension\":\"minecraft:overworld\",\"position\":[12,64,18]}],\"changes\":[{\"position\":[1,101,-4],\"before\":\"minecraft:gold_block\",\"after\":\"minecraft:stone\"}]}"));host().window("layout-graph","恢复操作结果",535,355).body.setId("layout-graph-report");next("graphical-recovery-report-opened");}
            case 505->{if(++wait<8)return;var report=find(host().smokeRoot(),"layout-graph-report");require(report!=null&&hasText(report,"金块")&&hasText(report,"石头"),"RECOVERY_DIFF_HAS_NO_NATIVE_BLOCK_NAMES");require(!rawJson(report),"RECOVERY_REPORT_EXPOSES_JSON");screenshot("graphical-recovery-report");checks.add("readable-block-icons-and-differences-without-json");result.complete(Map.of("status","PASS","checks",List.copyOf(checks),"modelCalls",0));}
            case 400->{WorkspacePanels.packages(host());next("open-package-manager-before-new-content-exists");}
            case 401->serverAsync(p->{try{
                seedItem(p);var mapper=new com.fasterxml.jackson.databind.ObjectMapper();dev.mineagent.runtime.neoforge.content.RuntimeCreatures.define(p,UUID.randomUUID(),mapper.createObjectNode().put("source","{\"name\":\"目录星球伙伴\"}"));
                dev.mineagent.runtime.neoforge.ui.ServerInteractionRules.set(p,UUID.randomUUID(),mapper.createObjectNode().put("source","{\"name\":\"目录门锁\",\"dimension\":\"minecraft:overworld\",\"position\":[5,100,5],\"events\":[\"block_use\"],\"decision\":\"cancel\"}"),false);
                return dev.mineagent.runtime.neoforge.ui.NativeEntityTemplates.define(p,UUID.randomUUID(),mapper.createObjectNode().put("source","{\"name\":\"目录原生羊\",\"type\":\"minecraft:sheep\"}")).thenCompose(value->{try{return dev.mineagent.runtime.neoforge.ui.ServerEntityInterop.set(p,UUID.randomUUID(),mapper.createObjectNode().put("source","{\"name\":\"目录羊行为\",\"entity_type\":\"minecraft:sheep\",\"block\":[\"attack\"]}"),"logic",false);}catch(Exception error){return CompletableFuture.failedFuture(error);}});
            }catch(Exception error){return CompletableFuture.failedFuture(error);}},"real-owned-content-created-in-original-stores");
            case 402->{var root=host().smokeRoot();if(hasText(root,"目录包容器")&&hasText(root,"目录星球伙伴")&&hasText(root,"目录原生羊")&&hasText(root,"目录羊行为")&&hasText(root,"目录门锁"))next("open-manager-auto-refreshes-all-five-content-types");}
            case 403->{busy=true;WorkspacePanels.request("workspace.read",Map.of("module","contents","kind","list","type","packages","query","水晶剑","offset","0")).whenComplete((reply,error)->{busy=false;if(error!=null){result.completeExceptionally(error);return;}var rows=WorkspacePanels.state(reply).getAsJsonArray("items");require(rows.size()==1&&rows.get(0).getAsJsonObject().get("name").getAsString().equals("目录包容器"),"PACKAGE_SEARCH_IGNORED_ITEM_NAME");next("search-by-contained-item-name-found-real-package");});}
            case 404->{screenshot("package-unified-content");result.complete(Map.of("status","PASS","checks",List.copyOf(checks),"modelCalls",0));}
            case 300->{NativeWorkspaceScreen.openSection(PanelSection.MOD_KNOWLEDGE);next("open-native-mod-knowledge");}
            case 301->{if(NativeWorkspaceModules.smokeReady("mods")&&click("重新索引"))next("visible-start-real-mod-index");}
            case 302->{if(++wait%20!=0)return;busy=true;WorkspacePanels.request("workspace.read",Map.of("module","mods","offset","0","query","")).whenComplete((reply,error)->{busy=false;if(error!=null){result.completeExceptionally(error);return;}var data=WorkspacePanels.state(reply);var status=data.getAsJsonObject("indexState").get("status").getAsString();if(status.equals("FAILED")){result.completeExceptionally(new IllegalStateException("MOD_INDEX_RUNTIME_FAILED_"+data));return;}if(!status.equals("APPLIED"))return;require(data.get("total").getAsInt()>0,"EMPTY_MOD_INDEX");boolean found=false;for(var raw:data.getAsJsonArray("items")){var entry=raw.getAsJsonObject();if(entry.get("modId").getAsString().equals("ldlib2")&&entry.get("classCount").getAsInt()>0)found=true;}require(found,"LDLIB_MOD_CLASSES_NOT_INDEXED");checks.add(data.toString());result.complete(Map.of("status","PASS","checks",List.copyOf(checks),"modelCalls",0));});}
            case 200->{
                var image=new java.awt.image.BufferedImage(32,32,java.awt.image.BufferedImage.TYPE_INT_RGB);for(int x=0;x<32;x++)for(int y=0;y<32;y++)image.setRGB(x,y,(x<16?0xff2200:0x0066ff));var bytes=new java.io.ByteArrayOutputStream();javax.imageio.ImageIO.write(image,"png",bytes);byte[] png=bytes.toByteArray();
                mediaHttp=com.sun.net.httpserver.HttpServer.create(new java.net.InetSocketAddress("127.0.0.1",0),0);mediaHttp.createContext("/image.png",exchange->{try{exchange.getResponseHeaders().set("Content-Type","image/png");exchange.sendResponseHeaders(200,exchange.getRequestMethod().equals("HEAD")?-1:png.length);if(!exchange.getRequestMethod().equals("HEAD"))exchange.getResponseBody().write(png);}finally{exchange.close();}});mediaHttp.start();mediaUrl="http://127.0.0.1:"+mediaHttp.getAddress().getPort()+"/image.png";
                NativeWorkspaceScreen.openSection(PanelSection.MEDIA);server(p->{var config=MineAgentRuntimeServices.config(p.level().getServer());require(config.apply(new dev.mineagent.runtime.api.config.ConfigPatch(config.snapshot().revision(),Map.of("media.allowedHosts","127.0.0.1")),true).accepted(),"FIXTURE_MEDIA_HOST_CONFIG");return true;},"isolated-real-png-http-source");
            }
            case 201->{if(click("添加媒体"))next("visible-add-image-media");}
            case 202->{if(find(host().smokeRoot(),"media-title") instanceof TextField title&&find(host().smokeRoot(),"media-url") instanceof TextField url){title.setText("原生图片播放验收",true);url.setText(mediaUrl,true);if(click("添加"))next("visible-store-real-image-source");}}
            case 203->server(p->{var found=MineAgentRuntimeServices.media(p.level().getServer()).all().stream().filter(e->e.title().equals("原生图片播放验收")).findFirst();if(found.isEmpty())return false;mediaId=found.get().mediaId();return true;},"real-image-entry-saved");
            case 204->{if(click("绑定到当前位置"))next("visible-bind-image-position");}
            case 205->server(p->{var entry=MineAgentRuntimeServices.media(p.level().getServer()).get(mediaId).orElseThrow();return !entry.screenBinding().isBlank();},"image-bound-before-play");
            case 206->{if(click("播放"))next("visible-start-real-playback");}
            case 207->{var mc=Minecraft.getInstance();if(dev.mineagent.runtime.neoforge.client.media.MineAgentMediaPlayback.texture(mc.level.dimension().identifier().toString(),mc.player.blockPosition())!=null)next("actual-worker-decode-packet-and-native-texture-upload");}
            case 208->{if(click("暂停"))next("visible-pause-playback");}
            case 209->server(p->!MineAgentRuntimeServices.media(p.level().getServer()).get(mediaId).orElseThrow().playing(),"pause-persisted");
            case 210->{var mc=Minecraft.getInstance();require(dev.mineagent.runtime.neoforge.client.media.MineAgentMediaPlayback.texture(mc.level.dimension().identifier().toString(),mc.player.blockPosition())!=null,"PAUSE_DROPPED_LAST_FRAME");server(p->{var service=MineAgentRuntimeServices.media(p.level().getServer());for(int i=0;i<24;i++)service.add(p.getUUID(),dev.mineagent.runtime.api.media.MediaKind.IMAGE,"其它媒体 "+i,mediaUrl);dev.mineagent.runtime.neoforge.network.MineAgentNetwork.sendMediaStateTo(p);return true;},"more-than-twenty-media-state-packets");}
            case 211->{if(++wait<30)return;var mc=Minecraft.getInstance();require(dev.mineagent.runtime.neoforge.client.media.MineAgentMediaPlayback.texture(mc.level.dimension().identifier().toString(),mc.player.blockPosition())!=null,"PAGED_MEDIA_STATE_LOST_OLD_IMAGE");checks.add("paused-frame-retained-across-paged-state");result.complete(Map.of("status","PASS","checks",List.copyOf(checks),"modelCalls",0));}
            case 100->{NativeBuildingPanel.open(host(),agent.toString());next("open-building-design-workspace");}
            case 101->{if(click("让 AI 设计"))next("visible-request-ai-design");}
            case 102->{if(find(host().smokeRoot(),"building-design-prompt") instanceof TextArea prompt){prompt.setValue(new String[]{"请只保存一个小型中空石屋的建筑计划，ID 为 ui_design_acceptance，坐标 minecraft:overworld 的 (12,101,12)，外尺寸 5×4×5。地板、外墙和屋顶使用独立稳定构件 ID，留一个两格高门洞，包含尺寸和门洞净空检查。材料石头，不能清空已有世界。只规划保存，不要施工，不需要再次确认。"},true);if(click("提交规划需求"))next("visible-design-submitted-to-real-model");}}
            case 103->{if(++wait%40!=0)return;busy=true;WorkspacePanels.request("building.read",Map.of("kind","inspect","agentId",agent.toString(),"offset","0")).whenComplete((reply,error)->{busy=false;if(error!=null){result.completeExceptionally(error);return;}for(var raw:WorkspacePanels.state(reply).getAsJsonArray("buildings")){var plan=raw.getAsJsonObject();if(plan.get("id").getAsString().equals("ui_design_acceptance")){require(plan.get("status").getAsString().equals("PLANNED")&&plan.get("activeRevision").getAsLong()==0,"MODEL_DESIGN_UNEXPECTED_WORLD_APPLICATION");checks.add(plan.toString());next("real-model-saved-component-plan-without-application");break;}}});}
            case 104->{result.complete(Map.of("status","PASS","checks",List.copyOf(checks),"modelCalls","RECORDED_IN_PROVIDER_AUDIT","planningOnly",true));}
            case 0->{NativeWorkspaceScreen.openSection(PanelSection.MEMORY);next("open-memory-route");}
            case 1->{if(click("新增记忆"))next("visible-add-memory");}
            case 2->{if(find(host().smokeRoot(),"memory-topic") instanceof TextField topic&&find(host().smokeRoot(),"memory-value") instanceof TextArea value){topic.setText("家",true);value.setValue(new String[]{"minecraft:overworld x=425 y=101 z=50"},true);if(click("保存"))next("visible-save-memory");}}
            case 3->{busy=true;WorkspacePanels.request("workspace.read",Map.of("module","memory","scope","dialogue","agentId",agent.toString(),"query","家","offset","0")).whenComplete((reply,error)->{busy=false;if(error!=null){result.completeExceptionally(error);return;}var items=WorkspacePanels.state(reply).getAsJsonArray("items");if(items.size()==1&&items.get(0).getAsJsonObject().get("value").getAsString().contains("425"))next("authoritative-memory-persisted");});}
            case 4->{screenshot("memory-facts");server(p->{try(var store=new dev.mineagent.runtime.core.memory.DialogueMemoryStore(p.level().getServer().getServerDirectory().resolve("mineagent-runtime-data/runtime.db"),MineAgentRuntimeServices.worldId(p.level().getServer()),p.getUUID(),agent,java.time.Clock.systemUTC())){require(store.context("回家",8000).contains("425"),"WORKSPACE_MEMORY_NOT_RECALLED");return true;}catch(Exception error){throw new CompletionException(error);}},"ui-memory-consumed-by-real-recall");}
            case 5->{NativeWorkspaceScreen.openSection(PanelSection.BACKUPS);server(p->{marker=p.blockPosition().offset(1,0,0);p.level().setBlockAndUpdate(marker,Blocks.STONE.defaultBlockState());return true;},"snapshot-marker-stone");}
            case 6->{if(click("创建快照"))next("visible-snapshot-editor");}
            case 7->{if(find(host().smokeRoot(),"snapshot-label") instanceof TextField field){field.setText("可见按钮快照",true);if(click("创建快照"))next("visible-create-snapshot");}}
            case 8->server(p->{var values=MineAgentRuntimeServices.snapshots(p.level().getServer()).all();if(values.stream().noneMatch(s->s.label().equals("可见按钮快照")))return false;p.level().setBlockAndUpdate(marker,Blocks.GOLD_BLOCK.defaultBlockState());return true;},"actual-snapshot-saved-before-world-edit");
            case 9->{if(hasText(host().smokeRoot(),"恢复操作结果")&&click("×")){NativeWorkspaceScreen.openSection(PanelSection.BACKUPS);next("close-backup-result");}}
            case 10->{if(click("预览恢复差异"))next("visible-preview-backup");}
            case 11->{var matches=new ArrayList<Button>();buttons(host().smokeRoot(),"按此预览恢复",matches);if(!matches.isEmpty()&&++wait>3){screenshot("backup-restore-preview");server(p->{p.level().setBlockAndUpdate(marker,Blocks.DIAMOND_BLOCK.defaultBlockState());return true;},"concurrent-player-edit-after-preview");}}
            case 12->{if(click("按此预览恢复"))next("visible-restore-stale-preview");}
            case 13->{if(++wait>30)server(p->{require(p.level().getBlockState(marker).is(Blocks.DIAMOND_BLOCK),"BACKUP_OVERWROTE_LATER_PLAYER_EDIT");return true;},"restore-conflict-preserved-diamond");}
            case 14->{if(hasText(host().smokeRoot(),"恢复操作结果")&&click("×")){NativeWorkspaceScreen.openSection(PanelSection.BACKUPS);next("dismiss-conflict-result");}}
            case 15->{if(click("预览恢复差异"))next("fresh-preview-before-restore");}
            case 16->{if(click("按此预览恢复"))next("visible-restore-fresh-preview");}
            case 17->server(p->p.level().getBlockState(marker).is(Blocks.STONE),"restore-actually-restored-stone");
            case 18->{if(++wait>20&&hasText(host().smokeRoot(),"恢复操作结果")&&click("×")){NativeWorkspaceScreen.openSection(PanelSection.BACKUPS);next("dismiss-restore-result");}}
            case 19->{if(click("修改历史"))next("visible-change-history");}
            case 20->{if(click("撤销"))next("visible-undo-snapshot-restore");}
            case 21->server(p->p.level().getBlockState(marker).is(Blocks.DIAMOND_BLOCK),"undo-restored-previous-diamond");
            case 22->{if(++wait>20&&hasText(host().smokeRoot(),"恢复操作结果")&&click("×")){NativeWorkspaceScreen.openSection(PanelSection.BACKUPS);next("dismiss-undo-result");}}
            case 23->{if(click("重做"))next("visible-redo-snapshot-restore");}
            case 24->server(p->p.level().getBlockState(marker).is(Blocks.STONE),"redo-restored-stone");
            case 25->{NativeWorkspaceScreen.openSection(PanelSection.MEDIA);next("open-media-route");}
            case 26->{if(click("添加媒体"))next("visible-add-media");}
            case 27->{if(find(host().smokeRoot(),"media-title") instanceof TextField title&&find(host().smokeRoot(),"media-url") instanceof TextField url){title.setText("界面媒体验收",true);url.setText("https://example.com/divzero-test-image.png",true);if(click("添加"))next("visible-save-media");}}
            case 28->server(p->MineAgentRuntimeServices.media(p.level().getServer()).all().stream().anyMatch(e->e.title().equals("界面媒体验收")),"media-persisted");
            case 29->{if(click("绑定到当前位置"))next("visible-media-binding");}
            case 30->server(p->{var entry=MineAgentRuntimeServices.media(p.level().getServer()).all().stream().filter(e->e.title().equals("界面媒体验收")).findFirst().orElseThrow();return !entry.screenBinding().isBlank();},"media-binding-persisted");
            case 31->{NativeWorkspaceScreen.openSection(PanelSection.DIAGNOSTICS);next("open-diagnostics-route");}
            case 32->{busy=true;WorkspacePanels.request("workspace.read",Map.of("module","diagnostics","offset","0")).whenComplete((reply,error)->{busy=false;if(error!=null)result.completeExceptionally(error);else{require(WorkspacePanels.state(reply).get("usedMemoryBytes").getAsLong()>0,"DIAGNOSTICS_NOT_LIVE");next("diagnostics-live-server-values");}});}
            case 33->server(p->{p.level().getServer().getPlayerList().deop(p.nameAndId());return true;},"remove-operator-for-permission-check");
            case 34->{busy=true;WorkspacePanels.request("workspace.read",Map.of("module","backups","kind","list","offset","0")).whenComplete((reply,error)->{busy=false;if(error==null)result.completeExceptionally(new IllegalStateException("BACKUP_PERMISSION_BYPASS"));else next("backup-permission-denied");});}
            case 35->server(p->{p.level().getServer().getPlayerList().op(p.nameAndId());return true;},"restore-fixture-operator");
            default->result.complete(Map.of("status","PASS","checks",List.copyOf(checks),"modelCalls",0));
        }
    }catch(Exception failure){result.completeExceptionally(failure);}}
}
