package dev.mineagent.runtime.neoforge.client.nativeui;

import com.google.gson.*;
import com.lowdragmc.lowdraglib2.gui.ui.elements.*;
import dev.mineagent.runtime.neoforge.client.language.ClientLanguage;
import net.minecraft.network.chat.Component;
import java.util.*;
import static dev.mineagent.runtime.neoforge.client.nativeui.NativeStudioPanel.*;

/** Distinguishes immutable RAW resources, FML transformations and actual JVM captures. */
final class NativeApiPanel {
    private static UUID session;private static String selectedSnapshot="";private static final Map<String,Map<String,String>> TYPES=new LinkedHashMap<>();private static final Map<String,String> OVERLAYS=new LinkedHashMap<>();
    static Map<String,String> selection(){var current=NativeWorkspaceConnection.current();if(current==null||!Objects.equals(session,current.sessionId())){session=current==null?null:current.sessionId();selectedSnapshot="";TYPES.clear();OVERLAYS.clear();}if(selectedSnapshot.isBlank()||TYPES.isEmpty()&&OVERLAYS.isEmpty())return Map.of();var json=new Gson();return Map.of("nativeSnapshot",selectedSnapshot,"nativeClasses",json.toJson(TYPES.values()),"nativeLiveSelections",json.toJson(OVERLAYS.keySet()));}
    static void open(NativeWorkspaceScreen host){if(!host.revealWindow("native-api"))new NativeApiPanel(host);}
    private final NativeWorkspaceScreen host;private final WorkspaceWindow window;private final ScrollerView list;private final TextElement notice=WorkspacePanels.text("");private final TextField search=new TextField();
    private String snapshot="",module="",type="",token="",method="",descriptor="",kind="modules";private int offset,textOffset;private long epoch;private boolean busy;
    private NativeApiPanel(NativeWorkspaceScreen host){this.host=host;selection();window=host.window("native-api",t("原生 API"),560,400);var tools=WorkspacePanels.row();tools.getLayout().height(25);window.body.addChild(tools);tools.addChild(button("RAW",()->{kind="modules";offset=textOffset=0;state(false);}));tools.addChild(button("JVM / FML",()->{kind="live_state";offset=textOffset=0;query();}));tools.addChild(button(t("捕获当前类路径"),()->state(true)));tools.addChild(button(t("只读刷新"),()->state(false)));tools.addChild(button(t("已选上下文"),this::selected));window.body.addChild(notice);var filters=WorkspacePanels.row();filters.getLayout().height(24);search.getLayout().flex(1);filters.addChild(search);filters.addChild(button(t("搜索"),()->{offset=textOffset=0;query();}));window.body.addChild(filters);list=WorkspacePanels.scroller(window.body);state(false);}
    private boolean live(){return host.activeContext()&&!window.closed();}
    private void acceptSnapshot(String value){if(value.matches("[a-f0-9]{64}")){snapshot=value;if(!value.equals(selectedSnapshot)){selectedSnapshot=value;TYPES.clear();OVERLAYS.clear();}}}
    private void state(boolean capture){if(busy)return;busy=true;long ticket=++epoch;WorkspacePanels.request(capture?"nativeApi.refresh":"nativeApi.read",Map.of("kind",capture?"refresh":"state")).whenComplete((receipt,error)->{busy=false;if(!live()||ticket!=epoch)return;if(error!=null){WorkspacePanels.failure(notice,error);return;}var data=WorkspacePanels.state(receipt);var environment=data.has("environment")?data.getAsJsonObject("environment"):new JsonObject();acceptSnapshot(text(environment,"snapshot"));notice.setText(Component.literal(text(environment,"status")));if(!snapshot.isBlank())query();else{list.clearAllScrollViewChildren();list.addScrollViewChild(WorkspacePanels.text(t("类路径尚未就绪，可捕获后只读刷新；不会自动重发捕获。")));}});}
    private Map<String,String> args(){var a=new LinkedHashMap<String,String>();a.put("kind",kind);if(kind.equals("live_state"))return a;if(kind.equals("loaded")){a.put("offset",Integer.toString(offset));a.put("search",search.getValue());return a;}a.put(kind.equals("source")?"lineOffset":"offset",Integer.toString(offset));if(kind.startsWith("live_"))a.put("classToken",token);else{a.put("snapshot",snapshot);if(!kind.equals("modules"))a.put("module",module);if(!Set.of("modules","classes").contains(kind))a.put("class",type);}if(kind.equals("classes")||kind.endsWith("members"))a.put("search",search.getValue());if(!Set.of("modules","classes").contains(kind))a.put("textOffset",Integer.toString(textOffset));if(kind.endsWith("method_body")||kind.equals("source")&&!method.isBlank()){a.put("method",method);a.put("descriptor",descriptor);}return a;}
    private void query(){if(busy||!live())return;selection();busy=true;long ticket=++epoch;var arguments=args();WorkspacePanels.request("nativeApi.read",arguments).whenComplete((receipt,error)->{busy=false;if(!live()||ticket!=epoch)return;if(error!=null){WorkspacePanels.failure(notice,error);return;}var data=WorkspacePanels.state(receipt);acceptSnapshot(text(data,"snapshot"));list.clearAllScrollViewChildren();notice.setText(Component.literal(t("只读取目标；RAW、FML 和 JVM 证据来源分别标注。")));draw(data);});}
    private void draw(JsonObject data){
        if(kind.equals("modules")){for(var raw:data.getAsJsonArray("modules")){var item=raw.getAsJsonObject();var card=WorkspacePanels.card(list,text(item,"name")+" · "+text(item,"version"));card.addChild(WorkspacePanels.text(text(item,"classes")+" classes"));card.addChild(button(t("浏览类与符号"),()->{module=text(item,"name");type=method=descriptor="";search.setText("",false);go("classes");}));}}
        else if(kind.equals("classes")){for(var raw:data.getAsJsonArray("classes")){String name=raw.getAsString();list.addScrollViewChild(button(name,()->{type=name;method=descriptor="";search.setText("",false);go("members");}));}}
        else if(kind.equals("live_state")){list.addScrollViewChild(WorkspacePanels.text(new GsonBuilder().setPrettyPrinting().create().toJson(data)));list.addScrollViewChild(button(t("搜索 JVM 已加载类"),()->go("loaded")));}
        else if(kind.equals("loaded")){for(var raw:data.getAsJsonArray("classes")){var item=raw.getAsJsonObject();var card=WorkspacePanels.card(list,text(item,"className"));card.addChild(WorkspacePanels.text(text(item,"moduleName")+" · "+text(item,"loaderKind")));var read=button(t("读取 JVM live 成员"),()->{token=text(item,"token");type=text(item,"className");module=text(item,"moduleName");method=descriptor="";search.setText("",false);go("live_members");});read.setActive(yes(item,"modifiable"));card.addChild(read);}}
        else {
            var evidence=WorkspacePanels.card(list,kind+" · "+type+(method.isBlank()?"":" · "+method));var editor=new NativeCodeEditor("JAVA");editor.load(data.has("text")?text(data,"text"):new GsonBuilder().setPrettyPrinting().create().toJson(data));editor.readOnly(true);editor.getLayout().height(210).flex(0);evidence.addChild(editor);
            var commands=WorkspacePanels.row();commands.getLayout().height(25);list.addScrollViewChild(commands);
            if(kind.equals("members")){
                String key=module+"\n"+type;commands.addChild(button(t(TYPES.containsKey(key)?"移出 Coder 选择":"选入 Coder 声明"),()->{try{if(TYPES.containsKey(key))TYPES.remove(key);else{capacity();TYPES.put(key,Map.of("module",module,"class",type));}query();}catch(Exception e){WorkspacePanels.failure(notice,e);}}));commands.addChild(button("FML transformed",()->go("transformed_members")));
                if(yes(data,"sourceAvailable"))commands.addChild(button(t("源码"),()->{method=descriptor="";go("source");}));
            }
            if(data.has("selectionId")&&!text(data,"selectionId").isBlank()){String id=text(data,"selectionId");commands.addChild(button(t(OVERLAYS.containsKey(id)?"移出 Coder 选择":"选入 Coder 实际类"),()->{try{if(OVERLAYS.containsKey(id))OVERLAYS.remove(id);else{capacity();OVERLAYS.put(id,type+(method.isBlank()?"":"."+method));}query();}catch(Exception e){WorkspacePanels.failure(notice,e);}}));}
            if(data.has("methods"))for(var raw:data.getAsJsonArray("methods")){var item=raw.getAsJsonObject();list.addScrollViewChild(button(text(item,"name")+" "+text(item,"descriptor"),()->{method=text(item,"name");descriptor=text(item,"descriptor");go(kind.startsWith("live_")?"live_method_body":kind.startsWith("transformed_")?"transformed_method_body":"method_body");}));}
            if(data.has("textMore")||textOffset>0){var pages=WorkspacePanels.row();pages.getLayout().height(25);list.addScrollViewChild(pages);var previous=button(t("前一段"),()->{textOffset=Math.max(0,textOffset-4096);query();});previous.setActive(textOffset>0);pages.addChild(previous);var next=button(t("后一段"),()->{textOffset=data.get("nextTextOffset").getAsInt();query();});next.setActive(yes(data,"textMore"));pages.addChild(next);}
        }
        if(data.has("nextOffset")){var row=WorkspacePanels.row();row.getLayout().height(25);list.addScrollViewChild(row);var previous=button(t("上一页"),()->{offset=Math.max(0,offset-(kind.equals("source")?128:kind.endsWith("method_body")?64:16));textOffset=0;query();});previous.setActive(offset>0);row.addChild(previous);var next=button(t("下一页"),()->{offset=data.get("nextOffset").getAsInt();textOffset=0;query();});next.setActive(yes(data,"more"));row.addChild(next);}
    }
    private static void capacity(){if(TYPES.size()+OVERLAYS.size()>=16)throw new IllegalStateException("NATIVE_CODER_SELECTION_LIMIT");}
    private void go(String value){kind=value;offset=textOffset=0;query();}
    private void selected(){selection();list.clearAllScrollViewChildren();notice.setText(Component.literal(t("仅明确勾选共享后，所选上下文才会发送给模型。")));for(var entry:List.copyOf(TYPES.entrySet())){var card=WorkspacePanels.card(list,"RAW · "+entry.getValue().get("class"));card.addChild(button(t("移除"),()->{TYPES.remove(entry.getKey());selected();}));}for(var entry:List.copyOf(OVERLAYS.entrySet())){var card=WorkspacePanels.card(list,"JVM / FML · "+entry.getValue());card.addChild(button(t("移除"),()->{OVERLAYS.remove(entry.getKey());selected();}));}}
    private Button button(String label,Runnable action){return NativeUiTheme.button(label,()->{if(!busy&&live())action.run();});}
    private static String t(String value){return ClientLanguage.t(value);}
}
