package dev.mineagent.runtime.neoforge.client.nativeui;

import com.google.gson.*;
import com.lowdragmc.lowdraglib2.gui.ui.UIElement;
import com.lowdragmc.lowdraglib2.gui.ui.elements.*;
import dev.mineagent.runtime.neoforge.client.language.ClientLanguage;
import net.minecraft.network.chat.Component;
import java.util.*;
import java.util.concurrent.*;

/** Explicit placement, movement and recovery of signed world instances; never a replay of uncertain creation. */
final class NativeInstancePanel {
    private final NativeWorkspaceScreen host;private final WorkspaceWindow window;private final ScrollerView content;
    private final TextElement notice=WorkspacePanels.text("");private JsonObject head;private int offset;private boolean busy;private long epoch;private UUID pending;
    static void open(NativeWorkspaceScreen host,JsonObject head){if(host.revealWindow("instances-"+text(head,"packageId")))return;new NativeInstancePanel(host,head);}
    private NativeInstancePanel(NativeWorkspaceScreen host,JsonObject head){this.host=host;this.head=head.deepCopy();window=host.window("instances-"+text(head,"packageId"),t("运行实例")+" · "+text(head,"name"),540,390);var top=WorkspacePanels.row();top.getLayout().height(25);window.body.addChild(top);top.addChild(NativeUiTheme.button(t("读取实际状态"),this::read));window.body.addChild(notice);content=WorkspacePanels.scroller(window.body);read();}
    private boolean live(){return host.activeContext()&&!window.closed();}
    private static String text(JsonObject value,String key){return value.has(key)&&!value.get(key).isJsonNull()?value.get(key).getAsString():"";}
    private static boolean yes(JsonObject value,String key){return value.has(key)&&value.get(key).getAsBoolean();}
    private Map<String,String> packageArgs(){return Map.of("packageId",text(head,"packageId"),"packageRevision",text(head,"revision"),"offset",Integer.toString(offset));}
    private void read(){if(busy||!live())return;busy=true;long ticket=++epoch;WorkspacePanels.request("task.historyRead",Map.of("kind","package","packageId",text(head,"packageId"),"headRevision","0","headHash","")).thenCompose(receipt->{head=WorkspacePanels.state(receipt);return WorkspacePanels.request("world.inspect",packageArgs());}).whenComplete((receipt,error)->{busy=false;if(!live()||ticket!=epoch)return;if(error!=null){WorkspacePanels.failure(notice,error);return;}content.clearAllScrollViewChildren();var data=receipt.values();var definitions=JsonParser.parseString(data.get("definitions")).getAsJsonArray();var anchor=JsonParser.parseString(data.get("anchor")).getAsJsonObject();var activations=JsonParser.parseString(data.get("activations")).getAsJsonArray();
        if(data.get("activationMode").equals("HOT_RUNTIME"))for(var raw:definitions){var definition=raw.getAsJsonObject();var card=WorkspacePanels.card(content,text(definition,"name"));card.addChild(NativeUiTheme.button(t("新建实例"),()->placement(definition,anchor)));}
        else content.addScrollViewChild(WorkspacePanels.text(t("此包通过其资源、数据或启动生命周期启用。")));
        for(var raw:activations){var activation=raw.getAsJsonObject();String id=text(activation,"operationId");var card=WorkspacePanels.card(content,t(text(activation,"state")));card.addChild(WorkspacePanels.text(text(activation,"error")));if(activation.has("location")){var loc=activation.getAsJsonObject("location");card.addChild(WorkspacePanels.text(text(loc,"dimension")+" · "+text(loc,"x")+", "+text(loc,"y")+", "+text(loc,"z")));}
            var actions=WorkspacePanels.row();actions.getLayout().height(25);card.addChild(actions);actions.addChild(NativeUiTheme.button(t("移动"),()->movement(id)));actions.addChild(NativeUiTheme.button(t("恢复与诊断"),()->restore(id)));if(Set.of("ACTIVE","RESTORE_PENDING","RESTORING").contains(text(activation,"state")))actions.addChild(NativeUiTheme.button(t("停用"),()->write("world.disable",Map.of("activationId",id),()->{offset=0;read();})));
            if(yes(activation,"autoRestore"))card.addChild(NativeUiTheme.button(t("关闭自动恢复"),()->write("world.restoreOff",Map.of("activationId",id,"activationRevision",text(activation,"revision")),this::read)));
            if(pending!=null&&pending.toString().equals(id)&&Set.of("ACTIVE","DISABLED").contains(text(activation,"state")))pending=null;
        }
        var pages=WorkspacePanels.row();pages.getLayout().height(25);var back=NativeUiTheme.button(t("上一页"),()->{offset=Math.max(0,offset-16);read();});back.setActive(offset>0);pages.addChild(back);var next=NativeUiTheme.button(t("下一页"),()->{offset=Integer.parseInt(data.get("nextOffset"));read();});next.setActive(Boolean.parseBoolean(data.get("more")));pages.addChild(next);content.addScrollViewChild(pages);notice.setText(Component.literal(pending==null?"":t("结果尚未确认，请勿重复提交。")));
    });}
    private Map<String,TextField> coordinates(UIElement parent,JsonObject location){var fields=new LinkedHashMap<String,TextField>();var row=WorkspacePanels.row();row.getLayout().height(25);parent.addChild(row);for(String axis:List.of("x","y","z")){var label=WorkspacePanels.text(axis.toUpperCase(Locale.ROOT));label.getLayout().width(12);row.addChild(label);var input=new TextField().setText(text(location,axis),false);input.getLayout().flex(1);row.addChild(input);fields.put(axis,input);}return fields;}
    private static void coordinates(Map<String,String> args,Map<String,TextField> fields){for(var entry:fields.entrySet()){double value=Double.parseDouble(entry.getValue().getValue());if(!Double.isFinite(value)||Math.abs(value)>30000000)throw new IllegalArgumentException("INVALID_COORDINATE");args.put(entry.getKey(),Double.toString(value));}}
    private void placement(JsonObject definition,JsonObject anchor){
        var dialog=host.window("placement-"+text(head,"packageId")+"-"+text(definition,"id"),t("新建实例"),440,260);dialog.body.clearAllChildren();dialog.body.addChild(WorkspacePanels.text(text(definition,"name")+" · "+text(anchor,"dimension")));var fields=coordinates(dialog.body,anchor);var restore=new Toggle().setText(t("允许重新进入世界时恢复此实例"));restore.setActive(yes(definition,"restoreAvailable"));dialog.body.addChild(restore);var consent=new Toggle().setText(t("确认在所选坐标创建新的实例"));dialog.body.addChild(consent);var status=WorkspacePanels.text("");dialog.body.addChild(status);
        dialog.body.addChild(NativeUiTheme.button(t("确认启用"),()->{if(!consent.isOn()||busy)return;if(pending!=null){status.setText(Component.literal(t("结果尚未确认，请勿重复提交。")));return;}try{var args=new LinkedHashMap<>(packageArgs());args.remove("offset");args.put("definitionId",text(definition,"id"));args.put("dimension",text(anchor,"dimension"));coordinates(args,fields);args.put("confirmed","true");args.put("autoRestore",Boolean.toString(restore.isOn()&&yes(definition,"restoreAvailable")));pending=UUID.randomUUID();write("world.activate",args,pending,()->{dialog.close();offset=0;read();});}catch(Exception error){WorkspacePanels.failure(status,error);}}));
    }
    private void movement(String activation){
        var dialog=host.window("instance-move-"+activation,t("移动实例"),470,290);dialog.body.clearAllChildren();var status=WorkspacePanels.text(t("正在读取…"));dialog.body.addChild(status);
        WorkspacePanels.request("world.moveInspect",Map.of("activationId",activation)).whenComplete((receipt,error)->{if(dialog.closed()||!live())return;if(error!=null){WorkspacePanels.failure(status,error);return;}var state=JsonParser.parseString(receipt.values().get("instance")).getAsJsonObject();status.setText(Component.literal(t("仅移动这个实例，保留其身份、监听与计时器。")));var location=state.getAsJsonObject("location");var fields=coordinates(dialog.body,location);var consent=new Toggle().setText(t("明确移动受管部件及其锚点"));dialog.body.addChild(consent);final UUID[] operation={null};
            var apply=NativeUiTheme.button(t("确认移动"),()->{if(!consent.isOn()||busy)return;if(operation[0]!=null){status.setText(Component.literal(t("结果尚未确认，请勿重复提交。")));return;}try{var args=new LinkedHashMap<String,String>();for(String key:List.of("activationId","instanceId","canonical","activationRevision"))args.put(key,text(state,key));args.put("source",location.toString());args.put("confirmed","true");coordinates(args,fields);operation[0]=UUID.randomUUID();write("world.move",args,operation[0],()->{dialog.close();read();});}catch(Exception failure){WorkspacePanels.failure(status,failure);}});apply.setActive(yes(state,"movable"));dialog.body.addChild(apply);dialog.body.addChild(NativeUiTheme.button(t("重新读取实际位置"),()->movement(activation)));
        });
    }
    private void restore(String activation){
        var dialog=host.window("instance-restore-"+activation,t("恢复与诊断"),480,330);dialog.body.clearAllChildren();var status=WorkspacePanels.text(t("正在读取…"));dialog.body.addChild(status);
        WorkspacePanels.request("world.restoreRead",Map.of("activationId",activation)).whenComplete((receipt,error)->{if(dialog.closed()||!live())return;if(error!=null){WorkspacePanels.failure(status,error);return;}var state=WorkspacePanels.state(receipt);status.setText(Component.literal(text(state,"packageName")+" · "+t(text(state,"state"))));var list=WorkspacePanels.scroller(dialog.body);list.addScrollViewChild(WorkspacePanels.text(t("恢复保留原实例身份和状态，只执行恢复入口，不重新执行创建。")));for(String field:List.of("error","restoreBlock","blocked"))if(!text(state,field).isBlank())list.addScrollViewChild(WorkspacePanels.text(text(state,field)));var consent=new Toggle().setText(t("明确授权恢复这个原实例"));list.addScrollViewChild(consent);var resume=NativeUiTheme.button(t("确认恢复"),()->{if(!consent.isOn()||busy)return;var args=new LinkedHashMap<String,String>();args.put("activationId",activation);args.put("confirmed","true");for(String key:List.of("instanceId","canonical","activationRevision","packageRevision","instanceRevision","environment"))args.put(key,text(state,key));write("world.restoreResume",args,()->restore(activation));});resume.setActive(yes(state,"canResume"));list.addScrollViewChild(resume);list.addScrollViewChild(NativeUiTheme.button(t("只读刷新"),()->restore(activation)));list.addScrollViewChild(NativeUiTheme.button(t("停用"),()->write("world.disable",Map.of("activationId",activation),()->restore(activation))));
        });
    }
    private void write(String action,Map<String,String> args,Runnable after){write(action,args,UUID.randomUUID(),after);}
    private void write(String action,Map<String,String> args,UUID operation,Runnable after){if(busy||!live())return;busy=true;WorkspacePanels.request(action,args,operation).whenComplete((receipt,error)->{busy=false;if(!live())return;if(error!=null){WorkspacePanels.failure(notice,error);return;}after.run();});}
    private static String t(String value){return ClientLanguage.t(value);}
}
