package dev.mineagent.runtime.neoforge.client.nativeui;

import com.google.gson.*;
import com.lowdragmc.lowdraglib2.gui.ui.UIElement;
import com.lowdragmc.lowdraglib2.gui.ui.elements.*;
import dev.mineagent.runtime.neoforge.client.language.ClientLanguage;
import net.minecraft.network.chat.Component;
import java.util.*;
import static dev.mineagent.runtime.neoforge.client.nativeui.NativeStudioPanel.*;

/** Multi-file editing, full version restoration and dependency selection use server revision fences. */
final class NativeStudioFiles {
    static void open(Document doc){files(doc,0,0);}
    private static void sourceHistory(Document doc,int offset){
        var window=doc.host.window("studio-source-history-"+doc.id,t("主文件历史"),500,350);var root=mount(window);var status=WorkspacePanels.text(t("正在读取…"));root.addChild(status);var snapshot=doc.args("draftHistory",offset);
        read(snapshot).whenComplete((data,error)->{if(!live(doc,window,root))return;if(error!=null){WorkspacePanels.failure(status,error);return;}status.setText(Component.literal(t("历史读取不执行代码，也不改变当前草稿。")));var list=WorkspacePanels.scroller(root);for(var raw:data.getAsJsonArray("history")){var entry=raw.getAsJsonObject();var card=WorkspacePanels.card(list,t("历史记录")+" "+text(entry,"index"));card.addChild(WorkspacePanels.text(text(entry,"characters")+" "+t("字符")));card.addChild(NativeUiTheme.button(t("查看源码"),()->{
            String key="studio-old-source-"+doc.id+"-"+text(entry,"hash");if(doc.host.revealWindow(key))return;var detail=doc.host.window(key,t("历史源码"),560,410);var notice=WorkspacePanels.text(t("正在读取…"));detail.body.addChild(notice);source(Map.of("kind","historySource","draftId",doc.id,"revision",snapshot.get("revision"),"entryIndex",text(entry,"index"),"hash",text(entry,"hash")),text(entry,"hash"),()->doc.host.activeContext()&&!detail.closed()).whenComplete((source,error2)->{if(detail.closed()||!doc.host.activeContext())return;if(error2!=null){WorkspacePanels.failure(notice,error2);return;}notice.setText(Component.literal(t("此处只读；载入编辑器后仍需单独保存。")));var editor=new NativeCodeEditor(text(doc.state,"language"));editor.load(source);editor.readOnly(true);detail.body.addChild(editor);detail.body.addChild(NativeUiTheme.button(t("载入主文件编辑器"),()->{if(!doc.live()){notice.setText(Component.literal(t("请先重新打开对应草稿")));return;}doc.editor.setValue(source.split("\n",-1),true);doc.window.reveal();}));});
        }));}pager(root,data,offset,8,page->sourceHistory(doc,page));});
    }
    private static Map<String,String> args(Document doc,String kind,long version,int offset){return Map.of("kind",kind,"draftId",doc.id,"revision",text(doc.state,"revision"),"version",Long.toString(version),"offset",Integer.toString(offset));}
    private static UIElement mount(WorkspaceWindow window){window.body.clearAllChildren();var root=new UIElement();root.getLayout().widthPercent(100).flex(1);window.body.addChild(root);return root;}
    private static boolean live(Document doc,WorkspaceWindow window,UIElement root){return doc.host.activeContext()&&!window.closed()&&root.getParent()==window.body;}
    private static void files(Document doc,long version,int offset){
        var window=doc.host.window("studio-files-"+doc.id,t("文件与版本"),525,365);var root=mount(window);var status=WorkspacePanels.text(t("正在读取…"));root.addChild(status);var request=args(doc,"workspaceFiles",version,offset);
        read(request).whenComplete((data,error)->{if(!live(doc,window,root))return;if(error!=null){WorkspacePanels.failure(status,error);return;}status.setText(Component.literal(version==0?t("当前工作区"):t("历史工作区")+" r"+version));var tools=WorkspacePanels.row();tools.getLayout().height(25);root.addChild(tools);tools.addChild(NativeUiTheme.button(t("当前文件"),()->files(doc,0,0)));tools.addChild(NativeUiTheme.button(t("工作区历史"),()->history(doc,0)));tools.addChild(NativeUiTheme.button(t("主文件历史"),()->sourceHistory(doc,0)));if(version==0)tools.addChild(NativeUiTheme.button(t("添加文件"),()->editor(doc,null,0,request.get("revision"))));else{var consent=new Toggle().setText(t("恢复完整文件集和依赖声明，不发布或运行"));root.addChild(consent);root.addChild(NativeUiTheme.button(t("恢复完整工作区"),()->{if(consent.isOn())change(doc,window,status,Map.of("change","restore","path","","target",Long.toString(version),"source","","revision",request.get("revision")),()->{window.close();doc.load();});}));}
            var list=WorkspacePanels.scroller(root);for(var raw:data.getAsJsonArray("files")){var file=raw.getAsJsonObject();var card=WorkspacePanels.card(list,text(file,"path")+(yes(file,"entry")?" · "+t("入口"):""));card.addChild(WorkspacePanels.text(text(file,"bytes")+" B"));card.addChild(NativeUiTheme.button(t("打开源码"),()->{if(version==0&&yes(file,"entry"))document(doc.host,doc.id);else editor(doc,file,version,request.get("revision"));}));}pager(root,data,offset,8,previous->files(doc,version,previous));
        });
    }
    private static void history(Document doc,int offset){var window=doc.host.window("studio-files-"+doc.id,t("文件与版本"),525,365);var root=mount(window);var status=WorkspacePanels.text(t("正在读取…"));root.addChild(status);read(args(doc,"workspaceHistory",0,offset)).whenComplete((data,error)->{if(!live(doc,window,root))return;if(error!=null){WorkspacePanels.failure(status,error);return;}status.setText(Component.literal(t("完整工作区历史")));var list=WorkspacePanels.scroller(root);for(var raw:data.getAsJsonArray("history")){var version=raw.getAsJsonObject();var card=WorkspacePanels.card(list,"r"+text(version,"revision"));card.addChild(WorkspacePanels.text(text(version,"entry")+" · "+text(version,"files")+" "+t("文件")));card.addChild(NativeUiTheme.button(t("查看此版本"),()->files(doc,version.get("revision").getAsLong(),0)));}pager(root,data,offset,4,page->history(doc,page));});}
    private static void editor(Document doc,JsonObject file,long version,String revision){String path=file==null?"":text(file,"path"),key="studio-file-"+doc.id+"-"+(file==null?UUID.randomUUID():path+"-"+version);if(doc.host.revealWindow(key))return;var window=doc.host.window(key,t("工作区源码"),565,425);var status=WorkspacePanels.text(t("正在读取…"));window.body.addChild(status);var future=file==null?java.util.concurrent.CompletableFuture.completedFuture(""):source(Map.of("kind","workspaceSource","draftId",doc.id,"revision",revision,"version",Long.toString(version),"path",path,"hash",text(file,"hash")),text(file,"hash"),()->doc.host.activeContext()&&!window.closed());
        future.whenComplete((original,error)->{if(!doc.host.activeContext()||window.closed())return;if(error!=null){WorkspacePanels.failure(status,error);return;}var name=new TextField().setText(path,false);name.getLayout().height(24).widthPercent(100);window.body.addChild(name);var editor=new NativeCodeEditor(text(doc.state,"language"));String cache=cacheKey(doc.id,revision,path);editor.load(version==0?cached(cache,original):original);editor.readOnly(version>0||editor.source().length()>16000);editor.registerValueListener(lines->{if(version==0)cache(cache,doc.state,path,String.join("\n",lines));});window.body.addChild(editor.tools());window.body.addChild(editor);status.setText(Component.literal(version==0?t("保存只修改草稿，不发布或执行。 "):t("历史版本只读")));if(version>0)return;
            var actions=WorkspacePanels.row();actions.getLayout().height(25);window.body.addChild(actions);actions.addChild(NativeUiTheme.button(t("保存此文件"),()->{if(file!=null&&!name.getValue().equals(path)){status.setText(Component.literal(t("改名请使用独立的重命名操作")));return;}if(editor.source().length()>16000){status.setText(Component.literal(t("源码为空或超过此文件编辑上限。")));return;}change(doc,window,status,Map.of("change",file==null?"add":"put","path",name.getValue(),"target","","source",editor.source(),"revision",revision),()->{saved(cache);window.close();if(doc.live()&&!doc.dirty)doc.load();});}));
            if(file!=null){var consent=new Toggle().setText(t("确认结构变更；路径改动不会自动重写 import 或 require"));window.body.addChild(consent);for(String action:List.of("rename","entry","remove")){if(!action.equals("rename")&&yes(file,"entry"))continue;actions.addChild(NativeUiTheme.button(t(action.equals("rename")?"重命名":action.equals("entry")?"设为入口":"删除文件"),()->{if(!consent.isOn()||!editor.source().equals(original)){status.setText(Component.literal(t("请先保存文件并确认结构变更")));return;}change(doc,window,status,Map.of("change",action,"path",path,"target",action.equals("rename")?name.getValue():"","source","","revision",revision),()->{saved(cache);window.close();if(doc.live()&&!doc.dirty)doc.load();});}));}}
        });
    }
    private static final Map<WorkspaceWindow,UUID> PENDING=new WeakHashMap<>();
    private static void change(Document doc,WorkspaceWindow window,TextElement status,Map<String,String> values,Runnable done){if(PENDING.containsKey(window))return;if(doc.live()&&doc.dirty){status.setText(Component.literal(t("请先保存主文件")));return;}UUID operation=UUID.randomUUID();PENDING.put(window,operation);var args=new LinkedHashMap<>(values);args.put("draftId",doc.id);args.put("action","workspaceFile");write(args,operation).whenComplete((result,error)->{if(window.closed()||!doc.host.activeContext())return;if(error!=null){WorkspacePanels.failure(status,error);return;}PENDING.remove(window);done.run();});}
    static void dependencies(Document doc,int offset){
        var window=doc.host.window("studio-dependencies-"+doc.id,t("依赖声明"),520,355);var root=mount(window);var status=WorkspacePanels.text(t("正在读取…"));root.addChild(status);String revision=text(doc.state,"revision");read(args(doc,"dependencies",0,offset)).whenComplete((data,error)->{if(!live(doc,window,root))return;if(error!=null){WorkspacePanels.failure(status,error);return;}status.setText(Component.literal(text(data,"resolution")));root.addChild(NativeUiTheme.button(t("选择依赖版本"),()->candidates(doc,0)));var list=WorkspacePanels.scroller(root);for(var row:data.getAsJsonArray("dependencies")){var entry=row.getAsJsonObject();var card=WorkspacePanels.card(list,text(entry,"className").isBlank()?text(entry,"version"):text(entry,"className"));card.addChild(WorkspacePanels.text(text(entry,"state")));card.addChild(NativeUiTheme.button(t("移除依赖声明"),()->dependency(doc,window,status,entry,"remove",revision)));}pager(root,data,offset,4,page->dependencies(doc,page));});
    }
    private static void candidates(Document doc,int offset){var window=doc.host.window("studio-dependency-candidates-"+doc.id,t("选择依赖版本"),520,355);var root=mount(window);var status=WorkspacePanels.text(t("正在读取…"));root.addChild(status);String revision=text(doc.state,"revision");read(Map.of("kind","dependencyCandidates","draftId",doc.id,"revision",revision,"offset",Integer.toString(offset))).whenComplete((data,error)->{if(!live(doc,window,root))return;if(error!=null){WorkspacePanels.failure(status,error);return;}status.setText(Component.literal(t("选择准确版本；不会自动启用或复制依赖。")));var list=WorkspacePanels.scroller(root);for(var row:data.getAsJsonArray("items")){var candidate=row.getAsJsonObject();var card=WorkspacePanels.card(list,text(candidate,"name"));card.addChild(WorkspacePanels.text(text(candidate,"version")+" · "+text(candidate,"targetSide")+" · "+text(candidate,"language")));card.addChild(NativeUiTheme.button(t("使用这个版本"),()->dependency(doc,window,status,candidate,"put",revision)));}pager(root,data,offset,8,page->candidates(doc,page));});}
    private static void dependency(Document doc,WorkspaceWindow window,TextElement status,JsonObject item,String change,String revision){if(doc.dirty||PENDING.containsKey(window)){status.setText(Component.literal(t("请先保存主文件")));return;}var args=new LinkedHashMap<String,String>();args.put("action","dependency");args.put("draftId",doc.id);args.put("revision",revision);args.put("change",change);args.put("packageId",text(item,"packageId"));args.put("version",text(item,"version"));if(change.equals("put"))args.put("packageRevision",text(item,"revision"));UUID operation=UUID.randomUUID();PENDING.put(window,operation);write(args,operation).whenComplete((result,error)->{if(!doc.host.activeContext()||window.closed())return;if(error!=null){WorkspacePanels.failure(status,error);return;}PENDING.remove(window);window.close();doc.load();});}
    private static void pager(UIElement root,JsonObject data,int offset,int size,java.util.function.IntConsumer go){var row=WorkspacePanels.row();row.getLayout().height(25);root.addChild(row);var before=NativeUiTheme.button(t("上一页"),()->go.accept(Math.max(0,offset-size)));before.setActive(offset>0);row.addChild(before);var next=NativeUiTheme.button(t("下一页"),()->go.accept(data.get("nextOffset").getAsInt()));next.setActive(yes(data,"more"));row.addChild(next);}
    private static String t(String value){return ClientLanguage.t(value);}
    private NativeStudioFiles(){}
}
