package dev.mineagent.runtime.neoforge.client.nativeui;

import com.google.gson.*;
import com.lowdragmc.lowdraglib2.gui.ui.UIElement;
import com.lowdragmc.lowdraglib2.gui.ui.elements.*;
import dev.mineagent.runtime.neoforge.client.language.ClientLanguage;
import net.minecraft.network.chat.Component;
import java.util.*;
import java.util.concurrent.*;
import java.util.function.*;

/** Native Java/Rhino source workbench. Saving, publishing and executing remain separate operations. */
final class NativeStudioPanel {
    private static Document smokeDocument;
    static NativeCodeEditor smokeEditor(){if(!Boolean.getBoolean("mineagent.nativeStudioSmoke"))throw new IllegalStateException("SMOKE_DISABLED");return smokeDocument==null?null:smokeDocument.editor;}
    static Map<String,Object> smokeState(){if(!Boolean.getBoolean("mineagent.nativeStudioSmoke"))throw new IllegalStateException("SMOKE_DISABLED");var d=smokeDocument;return d==null?Map.of():Map.of("busy",d.busy,"dirty",d.dirty,"revision",d.state==null?0:d.state.get("revision").getAsLong(),"source",d.editor==null?"":d.editor.source());}
    static void smokeSave(){var d=smokeDocument;if(!Boolean.getBoolean("mineagent.nativeStudioSmoke")||d==null)throw new IllegalStateException("SMOKE_DISABLED");d.action(Map.of("action","save","source",d.editor.source()),d::load);}

    record LocalDraft(String id,String revision,String path,String side,String language,String text){}
    private static final Map<String,LocalDraft> UNSAVED=new LinkedHashMap<>();
    static String cacheKey(String id,String revision,String path){var session=NativeWorkspaceConnection.current();if(session==null)throw new IllegalStateException("STUDIO_SESSION_CHANGED");return dev.mineagent.runtime.neoforge.network.PanelSnapshotInbox.snapshot().values().getOrDefault("security.identityFingerprint","")+"|"+session.binding().worldId()+"|"+session.binding().viewerPlayerId()+"|"+id+"|"+revision+"|"+path;}
    static void cache(String key,JsonObject meta,String path,String source){UNSAVED.put(key,new LocalDraft(text(meta,"id"),text(meta,"revision"),path,text(meta,"targetSide"),text(meta,"language"),source));}
    private static void recovered(NativeWorkspaceScreen host){var window=host.window("studio-unsaved",t("未保存的本机编辑"),510,350);window.body.clearAllChildren();var list=WorkspacePanels.scroller(window.body);String prefix=cacheKey("","","");prefix=prefix.substring(0,prefix.length()-2);for(var entry:List.copyOf(UNSAVED.entrySet()))if(entry.getKey().startsWith(prefix)){var data=entry.getValue();var card=WorkspacePanels.card(list,data.path()+" · r"+data.revision());card.addChild(NativeUiTheme.button(t("另存为新草稿"),()->create(host,null,data.side(),data.language(),data.path(),data.text())));card.addChild(NativeUiTheme.button(t("丢弃本机编辑"),()->Dialog.showCheckBox(t("丢弃本机编辑"),t("这只删除未保存的本机副本，不修改服务端草稿。"),yes->{if(yes){UNSAVED.remove(entry.getKey());recovered(host);}}).show(window.body)));}}
    static String cached(String key,String fallback){var value=UNSAVED.get(key);return value==null?fallback:value.text;}
    static void saved(String key){UNSAVED.remove(key);}

    static String text(JsonObject node,String key){return node.has(key)&&!node.get(key).isJsonNull()?node.get(key).getAsString():"";}
    static boolean yes(JsonObject node,String key){return node.has(key)&&node.get(key).getAsBoolean();}
    static CompletableFuture<JsonObject> read(Map<String,String> args){return WorkspacePanels.request("studio.read",args).thenApply(WorkspacePanels::state);}
    static CompletableFuture<JsonObject> write(Map<String,String> args,UUID operation){var values=new LinkedHashMap<>(args);values.put("confirmed","true");return WorkspacePanels.request("studio.write",values,operation).thenApply(WorkspacePanels::state);}
    static void open(NativeWorkspaceScreen host){if(host.revealWindow("studio"))return;var window=host.window("studio",t("代码工作区"),530,360);var top=WorkspacePanels.row();top.getLayout().height(25);window.body.addChild(top);top.addChild(NativeUiTheme.button(t("新建源码"),()->create(host,null,"SERVER","RHINO","server/studio.js","")));top.addChild(NativeUiTheme.button(t("Coder 请求"),()->NativeCoderPanel.open(host,null)));top.addChild(NativeUiTheme.button(t("未保存编辑"),()->recovered(host)));var notice=WorkspacePanels.text("");window.body.addChild(notice);var list=WorkspacePanels.scroller(window.body);int[] offset={0};long[] epoch={0};Runnable[] load={null};load[0]=()->{long ticket=++epoch[0];read(Map.of("kind","list","offset",Integer.toString(offset[0]))).whenComplete((value,error)->{if(!host.activeContext()||window.closed()||ticket!=epoch[0])return;if(error!=null){WorkspacePanels.failure(notice,error);return;}list.clearAllScrollViewChildren();for(var item:value.getAsJsonArray("drafts")){var draft=item.getAsJsonObject();var card=WorkspacePanels.card(list,text(draft,"path"));card.addChild(WorkspacePanels.text(text(draft,"targetSide")+" · "+text(draft,"status")));card.addChild(NativeUiTheme.button(t("打开源码"),()->document(host,text(draft,"id"))));}var pager=WorkspacePanels.row();pager.getLayout().height(24);list.addScrollViewChild(pager);var previous=NativeUiTheme.button(t("上一页"),()->{offset[0]=Math.max(0,offset[0]-8);load[0].run();});previous.setActive(offset[0]>0);pager.addChild(previous);var next=NativeUiTheme.button(t("下一页"),()->{offset[0]=value.get("nextOffset").getAsInt();load[0].run();});next.setActive(yes(value,"more"));pager.addChild(next);});};top.addChild(NativeUiTheme.button(t("刷新"),load[0]));load[0].run();}
    static CompletableFuture<String> source(Map<String,String> args,String expected,BooleanSupplier current){return source(args,expected,current,0,new StringBuilder());}
    private static CompletableFuture<String> source(Map<String,String> args,String expected,BooleanSupplier current,int offset,StringBuilder text){var page=new LinkedHashMap<>(args);page.put("offset",Integer.toString(offset));return read(page).thenCompose(value->{if(!current.getAsBoolean())return CompletableFuture.failedFuture(new IllegalStateException("STUDIO_VIEW_CHANGED"));if(!expected.isEmpty()&&!text(value,"hash").equals(expected))return CompletableFuture.failedFuture(new IllegalStateException("STUDIO_SOURCE_CHANGED"));text.append(value.has("text")?text(value,"text"):text(value,"source"));if(text.length()>4*1024*1024)return CompletableFuture.failedFuture(new IllegalStateException("STUDIO_SOURCE_TRANSPORT_LIMIT"));return yes(value,"more")?source(args,text(value,"hash"),current,value.get("nextOffset").getAsInt(),text):CompletableFuture.completedFuture(text.toString());});}
    static void fromPackage(NativeWorkspaceScreen host,JsonObject head,String side,String language){String key="studio-import-"+text(head,"packageId")+side+language;if(host.revealWindow(key))return;var status=host.window(key,t("读取包源码"),450,220);var notice=WorkspacePanels.text(t("正在读取…"));status.body.addChild(notice);var args=Map.of("kind","package","packageId",text(head,"packageId"),"packageRevision",text(head,"revision"),"targetSide",side,"language",language,"offset","0");read(args).thenCompose(first->source(args,text(head,"canonicalSha256"),()->host.activeContext()&&!status.closed()).thenApply(source->Map.entry(text(first,"path"),source))).whenComplete((value,error)->{if(status.closed()||!host.activeContext())return;if(error!=null){WorkspacePanels.failure(notice,error);return;}status.close();create(host,head,side,language,value.getKey(),value.getValue());});}
    private static void create(NativeWorkspaceScreen host,JsonObject head,String initialSide,String language,String path,String source){
        if(host.selectedAgentId().isBlank()){NativeWorkspaceScreen.notice(t("请先选择 AI"));return;}var window=host.window("studio-new-"+UUID.randomUUID(),t("新建源码"),570,420);String agent=host.selectedAgentId();var top=WorkspacePanels.row();top.getLayout().height(25);window.body.addChild(top);var side=new Selector<String>();side.setCandidates(List.of("SERVER","CLIENT"));side.setValue(initialSide,false);side.setActive(head==null);top.addChild(side);var name=new TextField().setText(path,false);name.getLayout().flex(1);top.addChild(name);var editor=new NativeCodeEditor(language);editor.load(source);side.setOnValueChanged(value->{String old=name.getValue();if(head==null&&(old.startsWith("server/")||old.startsWith("client/")))name.setText(value.toLowerCase(Locale.ROOT)+old.substring(old.indexOf('/')),false);});name.registerValueListener(value->editor.language(value.endsWith(".java")?"JAVA":"RHINO"));window.body.addChild(editor.tools());window.body.addChild(editor);var notice=WorkspacePanels.text(t("保存只建立草稿，不发布或执行。"));window.body.addChild(notice);boolean[] busy={false};UUID[] pending={null};var footer=WorkspacePanels.row();footer.getLayout().height(25);window.body.addChild(footer);
        footer.addChild(NativeUiTheme.button(t("保存草稿"),()->{if(busy[0]||pending[0]!=null)return;if(editor.source().isBlank()||editor.source().length()>16000){notice.setText(Component.literal(t("源码为空或超过此文件编辑上限。")));return;}pending[0]=UUID.randomUUID();busy[0]=true;write(Map.of("action","create","agentId",agent,"path",name.getValue(),"source",editor.source(),"packageId",head==null?"":text(head,"packageId"),"packageRevision",head==null?"0":text(head,"revision"),"targetSide",side.getValue()),pending[0]).whenComplete((value,error)->{busy[0]=false;if(window.closed()||!host.activeContext())return;if(error!=null){WorkspacePanels.failure(notice,error);return;}window.close();document(host,text(value,"draftId"));});}));footer.addChild(NativeUiTheme.button(t("读取草稿列表"),()->open(host)));
    }
    static void document(NativeWorkspaceScreen host,String id){String key="studio-document-"+id;if(host.revealWindow(key))return;new Document(host,id,key);}
    static final class Document {
        final NativeWorkspaceScreen host;final WorkspaceWindow window;final String id;final TextElement notice=WorkspacePanels.text("");JsonObject state;NativeCodeEditor editor;String cacheKey;boolean busy,dirty;long epoch;UUID pending;
        Document(NativeWorkspaceScreen host,String id,String key){this.host=host;this.id=id;window=host.window(key,t("代码编辑器"),580,435);if(Boolean.getBoolean("mineagent.nativeStudioSmoke"))smokeDocument=this;load();}
        boolean live(){return host.activeContext()&&!window.closed();}
        Map<String,String> args(String kind,int offset){return Map.of("kind",kind,"draftId",id,"revision",text(state,"revision"),"offset",Integer.toString(offset));}
        void load(){if(!live()||busy)return;busy=true;long ticket=++epoch;window.body.clearAllChildren();window.body.addChild(notice);notice.setText(Component.literal(t("正在读取…")));read(Map.of("kind","get","draftId",id,"revision","0","offset","0")).thenCompose(value->{state=value;return source(args("source",0),text(value,"sourceHash"),()->live()&&ticket==epoch);}).whenComplete((value,error)->{busy=false;if(!live()||ticket!=epoch)return;if(error!=null){WorkspacePanels.failure(notice,error);return;}cacheKey=cacheKey(id,text(state,"revision"),text(state,"path"));String recovered=cached(cacheKey,value);dirty=!recovered.equals(value);draw(recovered);});}
        void draw(String source){window.body.clearAllChildren();var top=WorkspacePanels.row();top.getLayout().height(24);window.body.addChild(top);var heading=WorkspacePanels.text(text(state,"path")+" · r"+text(state,"revision"));heading.getLayout().width(0).flex(1);top.addChild(heading);top.addChild(NativeUiTheme.button(t("刷新"),()->{if(!dirty)load();else Dialog.showCheckBox(t("重新读取"),t("放弃未保存的编辑并读取当前版本？"),yes->{if(yes)load();}).show(window.body);}));window.body.addChild(notice);notice.setText(Component.literal(text(state,"status")));editor=new NativeCodeEditor(text(state,"language"));editor.load(source);editor.readOnly(source.length()>16000||!text(state,"status").equals("DRAFT"));editor.registerValueListener(lines->{dirty=true;cache(cacheKey,state,text(state,"path"),String.join("\n",lines));});window.body.addChild(editor.tools());window.body.addChild(editor);
            var files=WorkspacePanels.row();files.getLayout().height(25);window.body.addChild(files);files.addChild(NativeUiTheme.button(t("文件与版本"),()->NativeStudioFiles.open(this)));files.addChild(NativeUiTheme.button(t("依赖"),()->NativeStudioFiles.dependencies(this,0)));files.addChild(NativeUiTheme.button(t("Coder"),()->{if(dirty)notice.setText(Component.literal(t("请先保存源码")));else NativeCoderPanel.open(host,state);}));files.addChild(NativeUiTheme.button(t("原生 API"),()->NativeApiPanel.open(host)));
            var footer=WorkspacePanels.row();footer.getLayout().height(25);window.body.addChild(footer);var save=NativeUiTheme.button(t("保存草稿"),()->action(Map.of("action","save","source",editor.source()),this::load));save.setActive(source.length()<=16000&&text(state,"status").equals("DRAFT"));footer.addChild(save);footer.addChild(NativeUiTheme.button(t("发布源码"),()->{if(dirty){notice.setText(Component.literal(t("请先保存源码")));return;}Dialog.stringEditorDialog(t("发布名称"),text(state,"packageName"),name->!name.isBlank()&&name.length()<=128,name->action(Map.of("action","publishSource","name",name,"packageRevision",text(state,"packageRevision")),this::load)).show(window.body);}));footer.addChild(NativeUiTheme.button(t("运行与诊断"),()->publications(0)));
        }
        void action(Map<String,String> values,Runnable done){if(!live()||busy)return;if(pending!=null){notice.setText(Component.literal(t("结果尚未确认，请勿重复提交。")));return;}busy=true;if(editor!=null)editor.readOnly(true);pending=UUID.randomUUID();var args=new LinkedHashMap<>(values);args.put("draftId",id);args.putIfAbsent("revision",text(state,"revision"));write(args,pending).whenComplete((value,error)->{busy=false;if(editor!=null)editor.readOnly(editor.source().length()>16000||!text(state,"status").equals("DRAFT"));if(!live())return;if(error!=null){WorkspacePanels.failure(notice,error);return;}pending=null;dirty=false;saved(cacheKey);done.run();});}
        void publications(int offset){var detail=host.window("studio-runtime-"+id,t("运行与诊断"),530,370);detail.body.clearAllChildren();var marker=new UIElement();marker.getLayout().widthPercent(100).flex(1);detail.body.addChild(marker);var status=WorkspacePanels.text(t("正在读取…"));marker.addChild(status);read(Map.of("kind","get","draftId",id,"revision","0","offset",Integer.toString(offset))).whenComplete((value,error)->{if(!live()||detail.closed()||marker.getParent()!=detail.body)return;if(error!=null){WorkspacePanels.failure(status,error);return;}if(text(value,"sourceHash").equals(text(state,"sourceHash")))state=value;status.setText(Component.literal(t("发布源码不等于执行。执行与停止均以运行记录为准。")));var list=WorkspacePanels.scroller(marker);if(text(value,"targetSide").equals("CLIENT")){list.addScrollViewChild(WorkspacePanels.text(t("客户端源码需先发布，再通过本机客户端代码页面独立批准。")));list.addScrollViewChild(NativeUiTheme.button(t("本机客户端代码"),()->NativeLifecyclePanel.open(host,null,NativeLifecyclePanel.Kind.CLIENT)));return;}var consent=new Toggle().setText(t("明确允许当前准确源码在服务器执行"));list.addScrollViewChild(consent);list.addScrollViewChild(NativeUiTheme.button(t("编译并运行"),()->{if(!consent.isOn()||dirty)return;action(Map.of("action","run"),()->publications(offset));}));
                for(var row:value.getAsJsonArray("publications")){var record=row.getAsJsonObject();var card=WorkspacePanels.card(list,text(record,"language")+" · "+text(record,"state"));if(!text(record,"error").isBlank())card.addChild(WorkspacePanels.text(text(record,"error")));card.addChild(NativeUiTheme.button(t("查看诊断"),()->NativeReadout.open(host,"studio-diagnostic-"+text(record,"id"),"编译诊断","studio.read",page->Map.of("kind",text(record,"language").equals("JAVA")?"diagnostics":"scriptDiag","publicationId",text(record,"id"),"publicationRevision",text(record,"revision"),"offset",Integer.toString(page)),4096)));if(yes(record,"loaded")){var stopConsent=new Toggle().setText(t("停止这个准确的运行记录"));card.addChild(stopConsent);card.addChild(NativeUiTheme.button(t("停止"),()->{if(stopConsent.isOn())action(Map.of("action","stop","publicationId",text(record,"id"),"publicationRevision",text(record,"revision")),()->publications(offset));}));}card.addChild(NativeUiTheme.button(t("打开源稿"),()->document(host,text(record,"draft"))));}
                var pages=WorkspacePanels.row();pages.getLayout().height(25);marker.addChild(pages);var prev=NativeUiTheme.button(t("上一页"),()->publications(Math.max(0,offset-8)));prev.setActive(offset>0);pages.addChild(prev);var next=NativeUiTheme.button(t("下一页"),()->publications(value.get("nextPublicationOffset").getAsInt()));next.setActive(yes(value,"morePublications"));pages.addChild(next);pages.addChild(NativeUiTheme.button(t("只读刷新"),()->publications(offset)));
        });}
    }
    private static String t(String value){return ClientLanguage.t(value);}
    private NativeStudioPanel(){}
}
