package dev.mineagent.runtime.neoforge.client.nativeui;

import com.google.gson.*;
import com.lowdragmc.lowdraglib2.gui.ui.elements.*;
import dev.mineagent.runtime.neoforge.client.language.ClientLanguage;
import dev.mineagent.runtime.neoforge.client.webui.*;
import net.minecraft.client.Minecraft;
import net.minecraft.network.chat.Component;
import java.util.*;

/** Per-AI skin and YSM controls use the existing revision/ownership transactions. */
final class NativeAppearancePanel {
    private record Choice(String id,String label){@Override public String toString(){return label;}}
    private final NativeWorkspaceScreen host;private final WorkspaceWindow window;private final String agent;private final ScrollerView body;private final TextElement notice=WorkspacePanels.text("");private boolean busy;private UUID pending;private int offset;private long epoch;private String query=".png";private JsonObject state;
    static void open(NativeWorkspaceScreen host,String agent){UUID.fromString(agent);if(!host.revealWindow("appearance-"+agent))new NativeAppearancePanel(host,agent);}
    private NativeAppearancePanel(NativeWorkspaceScreen host,String agent){this.host=host;this.agent=agent;window=host.window("appearance-"+agent,t("AI 外观"),530,370);var tabs=WorkspacePanels.row();tabs.getLayout().height(25);window.body.addChild(tabs);tabs.addChild(button("PNG 与内置皮肤",()->{offset=0;skins();}));tabs.addChild(button("YSM 模型",this::ysm));window.body.addChild(notice);body=WorkspacePanels.scroller(window.body);skins();}
    private boolean current(long token){return host.activeContext()&&!window.closed()&&epoch==token;}
    private JsonObject request(String kind){var request=new JsonObject();request.addProperty("kind",kind);request.addProperty("agentId",agent);return request;}
    private void skins(){
        long token=++epoch;body.clearAllScrollViewChildren();if(Minecraft.getInstance().getSingleplayerServer()==null){body.addScrollViewChild(WorkspacePanels.text(t("PNG 文件库需要本机世界；服务器 YSM 外观可使用另一页。")));return;}
        var request=request("read");request.addProperty("query",query);request.addProperty("offset",offset);SkinUiClient.handle(request).whenComplete((value,error)->Minecraft.getInstance().execute(()->{
            if(!current(token))return;if(error!=null){WorkspacePanels.failure(notice,error);return;}state=new Gson().toJsonTree(value).getAsJsonObject();notice.setText(Component.literal(t("当前：")+text(state,"selection")));
            var files=WorkspacePanels.card(body,t("PNG 皮肤"));var select=new Selector<Choice>();var options=new ArrayList<Choice>();for(var raw:state.getAsJsonObject("files").getAsJsonArray("files")){var file=raw.getAsJsonObject();if(text(file,"kind").equals("FILE"))options.add(new Choice(text(file,"id"),text(file,"name")));}select.setCandidates(options);options.stream().filter(c->c.id.equals(text(state,"fileId"))).findFirst().or(()->options.stream().findFirst()).ifPresent(choice->select.setValue(choice,false));select.getLayout().height(25).widthPercent(100);files.addChild(select);
            var model=new Selector<Choice>();var sizes=List.of(new Choice("wide",t("标准手臂")),new Choice("slim",t("纤细手臂")));model.setCandidates(sizes);model.setValue(sizes.get(text(state,"selection").endsWith(":slim")?1:0),false);model.getLayout().height(25).widthPercent(100);files.addChild(model);
            var controls=WorkspacePanels.row();controls.getLayout().height(25);files.addChild(controls);controls.addChild(button("应用 PNG",()->{if(select.getValue()==null)return;var args=request("apply");args.addProperty("file_id",select.getValue().id);args.addProperty("model",model.getValue().id);applySkin(args);}));controls.addChild(button("上传 PNG",()->BuildingFilesClient.requestOpen(agent)));controls.addChild(button("刷新",this::skins));
            var library=WorkspacePanels.card(body,t("内置 / 玩家皮肤"));var presets=new Selector<Choice>();var candidates=new ArrayList<Choice>();for(var raw:state.getAsJsonArray("presets")){var item=raw.getAsJsonObject();candidates.add(new Choice(text(item,"id"),item.has("label")?text(item,"label"):item.has("name")?text(item,"name"):text(item,"id")));}presets.setCandidates(candidates);if(!candidates.isEmpty())presets.setValue(candidates.getFirst(),false);presets.getLayout().height(25).widthPercent(100);library.addChild(presets);library.addChild(button("切换内置皮肤",()->{if(presets.getValue()==null)return;var args=request("preset");args.addProperty("skin",presets.getValue().id);applySkin(args);}));
            var pager=WorkspacePanels.row();pager.getLayout().height(25);body.addScrollViewChild(pager);var previous=button("上一页",()->{offset=Math.max(0,offset-32);skins();});previous.setActive(offset>0);pager.addChild(previous);var next=button("下一页",()->{offset=state.getAsJsonObject("files").get("nextOffset").getAsInt();skins();});next.setActive(state.getAsJsonObject("files").get("nextOffset").getAsInt()>=0);pager.addChild(next);
        }));
    }
    private void applySkin(JsonObject args){if(busy||pending!=null||state==null)return;busy=true;long token=epoch;pending=UUID.randomUUID();args.addProperty("operationId",pending.toString());args.addProperty("expected_revision",state.get("revision").getAsLong());SkinUiClient.handle(args).whenComplete((value,error)->Minecraft.getInstance().execute(()->{busy=false;if(error==null&&value!=null&&!Set.of("UNKNOWN","PENDING","IN_PROGRESS").contains(Objects.toString(value.get("status"),"")))pending=null;if(!current(token))return;if(error!=null){WorkspacePanels.failure(notice,error);return;}String status=Objects.toString(value.get("status"),"");if(!Set.of("APPLIED","CONFIGURED_BODY_NOT_LOADED").contains(status)){notice.setText(Component.literal(status));return;}pending=null;skins();}));}
    private void ysm(){
        long token=++epoch;body.clearAllScrollViewChildren();WorkspacePanels.request("appearance.read",Map.of("agentId",agent)).whenComplete((receipt,error)->{
            if(!current(token))return;if(error!=null){WorkspacePanels.failure(notice,error);return;}var value=WorkspacePanels.state(receipt);notice.setText(Component.literal(text(value,"diagnostic")+" · "+text(value,"version")));var card=WorkspacePanels.card(body,t("YSM 模型"));card.addChild(WorkspacePanels.text(t("只修改选中 AI 的外观；不改变身体、背包、生命或任务。卸载 YSM 需要重启。")));
            var models=new Selector<String>();var choices=new ArrayList<String>();value.getAsJsonArray("models").forEach(entry->choices.add(entry.getAsString()));if(!text(value,"model").isBlank()&&!choices.contains(text(value,"model")))choices.add(text(value,"model"));models.setCandidates(choices);models.setValue(text(value,"model").isBlank()&&!choices.isEmpty()?choices.getFirst():text(value,"model"),false);models.getLayout().height(25).widthPercent(100);card.addChild(models);
            var catalog=WorkspacePanels.row();catalog.getLayout().height(25);card.addChild(catalog);var search=new TextField();search.getLayout().flex(1);catalog.addChild(search);int[] page={0},nextPage={value.get("catalogNextOffset").getAsInt()};boolean[] reading={false};Runnable[] query={null};
            query[0]=()->{if(reading[0])return;reading[0]=true;WorkspacePanels.request("appearance.read",Map.of("agentId",agent,"catalogOffset",Integer.toString(page[0]),"catalogSearch",search.getValue())).whenComplete((response,failure)->{reading[0]=false;if(!current(token))return;if(failure!=null){WorkspacePanels.failure(notice,failure);return;}var available=WorkspacePanels.state(response);var candidates=new ArrayList<String>();available.getAsJsonArray("models").forEach(model->candidates.add(model.getAsString()));String selected=models.getValue();if(selected!=null&&!selected.isBlank()&&!candidates.contains(selected))candidates.add(selected);models.setCandidates(candidates);models.setValue(selected,false);nextPage[0]=available.get("catalogNextOffset").getAsInt();});};
            catalog.addChild(button("搜索",()->{page[0]=0;query[0].run();}));catalog.addChild(button("上一页",()->{page[0]=Math.max(0,page[0]-64);query[0].run();}));catalog.addChild(button("下一页",()->{if(nextPage[0]>=0){page[0]=nextPage[0];query[0].run();}}));

            card.addChild(WorkspacePanels.text(t("纹理 ID（留空使用模型默认）")));var texture=new TextField().setText(text(value,"texture"),false);texture.getLayout().height(24).widthPercent(100);card.addChild(texture);card.addChild(WorkspacePanels.text(t("动画 ID（留空不额外指定）")));var animation=new TextField().setText(text(value,"animation"),false);animation.getLayout().height(24).widthPercent(100);card.addChild(animation);card.addChild(WorkspacePanels.text(t("模型列表来自当前服务器；纹理和动画不伪造可用列表。")));
            var actions=WorkspacePanels.row();actions.getLayout().height(25);card.addChild(actions);var apply=button("应用外观",()->{if(busy||pending!=null||models.getValue()==null)return;busy=true;pending=UUID.randomUUID();WorkspacePanels.request("appearance.apply",Map.of("agentId",agent,"expectedRevision",text(value,"revision"),"model",models.getValue(),"texture",texture.getValue(),"animation",animation.getValue()),pending).whenComplete((r,e)->{busy=false;if(e==null)pending=null;if(!current(token))return;if(e!=null){WorkspacePanels.failure(notice,e);return;}if(!WorkspacePanels.state(r).get("accepted").getAsBoolean()){notice.setText(Component.literal(t("外观没有应用，请读取实际状态。")));return;}pending=null;ysm();});});apply.setActive(value.get("runtimeAvailable").getAsBoolean());actions.addChild(apply);actions.addChild(button("读取外观",this::ysm));
        });
    }
    private static String text(JsonObject object,String key){return object.has(key)&&!object.get(key).isJsonNull()?object.get(key).getAsString():"";}
    private static String t(String text){return ClientLanguage.t(text);}
    private static Button button(String text,Runnable action){return NativeUiTheme.button(t(text),action);}
}
