package dev.mineagent.runtime.core.conversation;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
class ConversationToolsTest {
    @Test void toolContinuationIsNotRejectedByTheHistoricalByteTokenEstimate(){assertDoesNotThrow(()->ConversationTools.requireTransportSize(200000));assertThrows(IllegalArgumentException.class,()->ConversationTools.requireTransportSize(ConversationTools.MAX_TOOL_TRANSPORT_BYTES+1));}
    @Test void registryLookupMatchesDisplayNamesAsWellAsIds(){assertTrue(ConversationTools.matches("mod:sword","星空之刃","星空"));assertTrue(ConversationTools.matches("minecraft:sharpness","Sharpness","SHARP"));assertFalse(ConversationTools.matches("minecraft:stone","石头","钻石"));}
    @Test void declarationsMatchAdmissionAndKeepMissingIntegrationsHonest()throws Exception{var json=new ObjectMapper();assertEquals(ConversationTools.ALL.size(),ConversationTools.NAMES.size());for(var tool:ConversationTools.ALL){var schema=json.readTree(tool.parameters());assertEquals("object",schema.path("type").asText());assertFalse(schema.path("additionalProperties").asBoolean(true));}assertTrue(ConversationTools.mutation("modify_item"));assertFalse(ConversationTools.mutation("inspect_player"));assertFalse(ConversationTools.mutation("inspect_commands"));assertTrue(ConversationTools.NAMES.contains("inspect_commands"));assertFalse(ConversationTools.mutation("inspect_blocks"));assertTrue(ConversationTools.NAMES.contains("inspect_blocks"));assertFalse(ConversationTools.mutation("inspect_blueprints"));assertEquals(12,ConversationTools.MAX_ROUNDS);assertEquals(32,ConversationTools.MAX_TOOL_CALLS);assertFalse(ConversationTools.NAMES.contains("host_command"));assertTrue(ConversationTools.NAMES.contains("web_search"));assertTrue(ConversationTools.NAMES.contains("read_web_page"));assertFalse(ConversationTools.mutation("web_search"));assertFalse(ConversationTools.mutation("inspect_container"));for(String name:java.util.List.of("inspect_modeling","validate_model_geometry")){assertTrue(ConversationTools.NAMES.contains(name));assertFalse(ConversationTools.mutation(name));}for(String name:java.util.List.of("interact_block","quick_move_container","close_container","generate_content_package")){assertTrue(ConversationTools.NAMES.contains(name));assertTrue(ConversationTools.mutation(name));}}
    @Test void nativeSegmentsDoNotTruncateLongRepliesOrSplitEmoji(){String message="你好。"+"abcd😀".repeat(1400)+"结束";var got=new StringBuilder();for(int offset=0;offset<message.length();){String remaining=message.substring(offset);int count=NativeChatSegments.nextLength(remaining,240,true);assertTrue(count>0&&count<=240);String chunk=remaining.substring(0,count);assertFalse(Character.isHighSurrogate(chunk.charAt(chunk.length()-1)));got.append(chunk);offset+=count;}assertEquals(message,got.toString());assertEquals(3,NativeChatSegments.nextLength("你好。后续",240,false));assertEquals(0,NativeChatSegments.nextLength("未完句",240,false));}
}
