package dev.mineagent.runtime.core.task;
import com.fasterxml.jackson.databind.*;
import java.util.*;
/** One next objective, NOT a precomputed keyboard route. Summary is public action intent, not model reasoning. */
public record AutonomyPlan(String action,List<Double> target,int ticks,int slot,String summary,String skill){
    public AutonomyPlan(String action,List<Double> target,int ticks,int slot,String summary){this(action,target,ticks,slot,summary,"");}
    public AutonomyPlan{target=List.copyOf(target);skill=skill==null?"":skill;if(!Set.of("MOVE","LOOK","ATTACK","USE","HOTBAR","JUMP","SNEAK","WAIT","IDLE","SKILL").contains(action)||target.size()!=3||target.stream().anyMatch(v->!Double.isFinite(v)||Math.abs(v)>30000000)||ticks<1||ticks>100||slot<0||slot>8||action.equals("SNEAK")&&slot>1||summary==null||summary.isBlank()||summary.length()>160||action.equals("SKILL")!=!skill.isEmpty())throw new IllegalArgumentException("AUTONOMY_PLAN_BOUNDS");if(action.equals("SKILL"))SkillTools.canonical("start_skill",skill);}
    public static AutonomyPlan parse(String raw)throws Exception{if(raw==null||raw.length()>8192)throw new IllegalArgumentException("AUTONOMY_PLAN_BYTES");String source=raw.strip();if(source.startsWith("```")){int i=source.indexOf('\n');if(i<0||!source.endsWith("```"))throw new IllegalArgumentException("AUTONOMY_JSON");source=source.substring(i+1,source.length()-3).strip();}var json=new ObjectMapper().enable(com.fasterxml.jackson.core.JsonParser.Feature.STRICT_DUPLICATE_DETECTION).enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS);var n=json.readTree(source);if(!n.isObject()||n.size()!=(n.path("action").asText().equals("SKILL")?6:5)||!n.path("action").isTextual()||!n.path("summary").isTextual()||!n.path("target").isArray()||n.path("target").size()!=3||!n.path("ticks").isIntegralNumber()||!n.path("ticks").canConvertToInt()||!n.path("slot").isIntegralNumber()||!n.path("slot").canConvertToInt())throw new IllegalArgumentException("AUTONOMY_FIELDS");var xyz=new ArrayList<Double>();for(var v:n.path("target")){if(!v.isNumber())throw new IllegalArgumentException("AUTONOMY_TARGET");xyz.add(v.doubleValue());}return new AutonomyPlan(n.path("action").asText(),xyz,n.path("ticks").intValue(),n.path("slot").intValue(),n.path("summary").asText(),n.path("action").asText().equals("SKILL")?n.path("skill").toString():"");}
    public static String instructions(){return "你是Minecraft本人身体的闭环控制规划器。持续农务、跟随、巡逻、警戒、钓鱼、战斗或漫步必须交给本地技能，不用反复MOVE/USE替代。此时返回6字段JSON：action=SKILL，target=[0,0,0]，ticks=1，slot=0，summary为简短公开目标，skill为完整对象。skill示例 {\"id\":\"local_farm\",\"expected_revision\":0,\"kind\":\"FARM\",\"actor\":\"player\",\"dimension\":\"minecraft:overworld\",\"min\":[0,64,0],\"max\":[4,65,4],\"repeat\":true}。min/max必须按实际观察的作物/钓点/允许区域计算；维度用真实观察值，不抄示例坐标。kind可FOLLOW/PATROL/GUARD/FARM/FISH/WANDER/COMBAT。FOLLOW/COMBAT用target实体UUID，PATROL用route坐标数组，其余用min/max。返回SKILL后由本地循环运行直到用户停止，不再逐株/逐步请求模型。其它临时移动或视角目标才使用以下5字段协议。只返回完整JSON {\"action\":\"MOVE\",\"target\":[0,0,0],\"ticks\":20,\"slot\":0,\"summary\":\"走向目标\"}，恰好5字段。summary是给玩家看的简短行动意图，不是推理过程。MOVE选择当前16格范围内可站立的绝对目标坐标，真实避障路线由每Tick观察的导航器计算，不生成固定按键序列。LOOK转向绝对世界坐标；ATTACK/USE瞄准给定方块中心后真实点击/按住，必须在交互距离内；HOTBAR选择0..8；JUMP跳一次；SNEAK用slot=1开启持续潜行、slot=0关闭，MOVE也会自动潜行通过低净空并安全恢复；WAIT等待1..100Tick后再观察；IDLE保持接管会话待命，不结束会话也不继续重复请求模型。一次只决定下一项，最多100Tick动作，MOVE可持续到目标。使用实际观察，不猜未加载地形，不传命令/脚本。普通MOVE不猜测水/火/岩浆/悬崖路径；专用SKILL使用统一通行判定处理水域和梯子，不要攻击未要求攻击的对象。每项完成会读回真实位置/方块等再规划；已完成的效果不重复。目标达成后IDLE并说明等新指令；持续巡逻等任务返回SKILL让本地运行，用户没停止不宣称已结束接管。";}
}
