package dev.mineagent.runtime.core.task;
import com.fasterxml.jackson.databind.*;
import java.util.*;
/** One next objective, NOT a precomputed keyboard route. Summary is public action intent, not model reasoning. */
public record AutonomyPlan(String action,List<Double> target,int ticks,int slot,String summary){
    public AutonomyPlan{target=List.copyOf(target);if(!Set.of("MOVE","LOOK","ATTACK","USE","HOTBAR","JUMP","SNEAK","WAIT","IDLE").contains(action)||target.size()!=3||target.stream().anyMatch(v->!Double.isFinite(v)||Math.abs(v)>30000000)||ticks<1||ticks>100||slot<0||slot>8||action.equals("SNEAK")&&slot>1||summary==null||summary.isBlank()||summary.length()>160)throw new IllegalArgumentException("AUTONOMY_PLAN_BOUNDS");}
    public static AutonomyPlan parse(String raw)throws Exception{if(raw==null||raw.length()>8192)throw new IllegalArgumentException("AUTONOMY_PLAN_BYTES");String source=raw.strip();if(source.startsWith("```")){int i=source.indexOf('\n');if(i<0||!source.endsWith("```"))throw new IllegalArgumentException("AUTONOMY_JSON");source=source.substring(i+1,source.length()-3).strip();}var json=new ObjectMapper().enable(com.fasterxml.jackson.core.JsonParser.Feature.STRICT_DUPLICATE_DETECTION).enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS);var n=json.readTree(source);if(!n.isObject()||n.size()!=5||!n.path("action").isTextual()||!n.path("summary").isTextual()||!n.path("target").isArray()||n.path("target").size()!=3||!n.path("ticks").isIntegralNumber()||!n.path("ticks").canConvertToInt()||!n.path("slot").isIntegralNumber()||!n.path("slot").canConvertToInt())throw new IllegalArgumentException("AUTONOMY_FIELDS");var xyz=new ArrayList<Double>();for(var v:n.path("target")){if(!v.isNumber())throw new IllegalArgumentException("AUTONOMY_TARGET");xyz.add(v.doubleValue());}return new AutonomyPlan(n.path("action").asText(),xyz,n.path("ticks").intValue(),n.path("slot").intValue(),n.path("summary").asText());}
    public static String instructions(){return "你是Minecraft本人身体的闭环控制规划器。只返回完整JSON {\"action\":\"MOVE\",\"target\":[0,0,0],\"ticks\":20,\"slot\":0,\"summary\":\"走向目标\"}，恰好5字段。summary是给玩家看的简短行动意图，不是推理过程。MOVE选择当前16格范围内可站立的绝对目标坐标，真实避障路线由每Tick观察的导航器计算，不生成固定按键序列。LOOK转向绝对世界坐标；ATTACK/USE瞄准给定方块中心后真实点击/按住，必须在交互距离内；HOTBAR选择0..8；JUMP跳一次；SNEAK用slot=1开启持续潜行、slot=0关闭，MOVE也会自动潜行通过低净空并安全恢复；WAIT等待1..100Tick后再观察；IDLE保持接管会话待命，不结束会话也不继续重复请求模型。一次只决定下一项，最多100Tick动作，MOVE可持续到目标。使用实际观察，不猜未加载地形，不传命令/脚本。不可走进水/火/岩浆/悬崖，不要攻击未要求攻击的对象。每项完成会读回真实位置/方块等再规划；已完成的效果不重复。目标达成后IDLE并说明等新指令；持续巡逻等任务则继续选择新目标，用户没停止不宣称已结束接管。";}
}
