package dev.mineagent.runtime.core.task;
import com.fasterxml.jackson.databind.*;import dev.mineagent.runtime.core.conversation.ConversationTools.Definition;import java.util.*;

public final class SkillTools {
    public static final Set<String> START=Set.of("set_behavior_mode","start_skill","follow_entity","patrol_route","guard_area","farm_area","fish_at","wander_area","combat_entity");
    public static final Set<String> TOOLS=Set.of("set_behavior_mode","start_skill","follow_entity","patrol_route","guard_area","farm_area","fish_at","wander_area","combat_entity","inspect_skills","control_skill","inspect_behavior","set_combat_policy","control_behavior");
    public static SkillSpec.Kind kind(String name){return switch(name){case "follow_entity"->SkillSpec.Kind.FOLLOW;case "patrol_route"->SkillSpec.Kind.PATROL;case "guard_area"->SkillSpec.Kind.GUARD;case "farm_area"->SkillSpec.Kind.FARM;case "fish_at"->SkillSpec.Kind.FISH;case "wander_area"->SkillSpec.Kind.WANDER;case "combat_entity"->SkillSpec.Kind.COMBAT;default->null;};}
    public static String canonical(String name,String raw){try{if(raw==null||raw.length()>16000)throw new IllegalArgumentException();var json=new ObjectMapper().enable(com.fasterxml.jackson.core.JsonParser.Feature.STRICT_DUPLICATE_DETECTION).enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS);var n=json.readTree(raw);if(n==null||!n.isObject())throw new IllegalArgumentException();if(START.contains(name))SkillSpec.parse(n,kind(name));else if(Set.of("inspect_skills","inspect_behavior").contains(name)){if(n.size()>2||n.has("history")&&!n.get("history").isBoolean()||n.has("offset")&&(!n.get("offset").isIntegralNumber()||n.get("offset").asInt(-1)<0)||n.properties().stream().anyMatch(e->!Set.of("history","offset").contains(e.getKey())))throw new IllegalArgumentException();}else if(Set.of("control_skill","control_behavior").contains(name)){if(n.size()!=3||!n.path("id").isTextual()||n.path("id").asText().length()>96||!n.path("expected_revision").isIntegralNumber()||n.path("expected_revision").asLong()<1||!Set.of("pause","resume","stop","reconcile").contains(n.path("action").asText()))throw new IllegalArgumentException();}else if(name.equals("set_combat_policy")){if(n.size()!=3||!n.path("id").isTextual()||!n.path("expected_revision").isIntegralNumber()||!n.path("combat").isObject())throw new IllegalArgumentException();CombatPolicy.parse(n.get("combat"),CombatPolicy.defaults(SkillSpec.Kind.IDLE,true,""));}else throw new IllegalArgumentException();return n.toString();}catch(Exception e){throw new IllegalArgumentException("SKILL_TOOL_ARGUMENTS",e);}}
    public static Definition definition(String name){
        var json=new ObjectMapper();var schema=json.createObjectNode().put("type","object").put("additionalProperties",false);var props=schema.putObject("properties");var required=schema.putArray("required");
        String description;
        if(Set.of("inspect_skills","inspect_behavior").contains(name)){props.putObject("history").put("type","boolean");props.putObject("offset").put("type","integer").put("minimum",0);description="默认查询活动技能；history=true分页查询已结束技能，每页16条。查询当前AI及本人接管技能的定义、revision、生命周期、阶段、真实计数、暂停原因、子动作回执和作物适配器。";}
        else if(Set.of("control_skill","control_behavior").contains(name)){props.putObject("id").put("type","string");props.putObject("expected_revision").put("type","integer").put("minimum",1);props.putObject("action").putArray("enum").add("pause").add("resume").add("stop").add("reconcile");required.add("id").add("expected_revision").add("action");description="暂停、恢复、取消或先读实际世界/库存核对不确定子动作。取消终止会话，不自动恢复；reconcile只观察并归档旧操作，不重新执行。";}
        else if(name.equals("set_combat_policy")){props.putObject("id").put("type","string");props.putObject("expected_revision").put("type","integer").put("minimum",1);props.set("combat",combatSchema(json));required.add("id").add("expected_revision").add("combat");description="只修改战斗方式/交战规则，不取消或重启当前农务、跟随、巡逻等主工作。先inspect_behavior读取id和revision；策略AUTO/HIT_AND_RUN/MELEE_COMBO/RANGED_KITE/HOLD_POSITION/DISENGAGE，交战NONE/SELF_DEFENSE/PROTECT/CLEAR_AREA/SPECIFIED。MELEE_COMBO参考combo/W-tap/S-tap；AUTO/HIT_AND_RUN/MELEE_COMBO在合适时使用Jump-tap与A/D变向：确认命中后释放疾跑并短跳调距，按真实攻击碰撞箱与飞行物选侧移方向，避免每帧左右抽搐，检查整个跳跃轨迹和落点，不把跳起当免伤，不增加攻击速度或距离。保护对象protect UUID或$owner；指定攻击target UUID；防区min/max独立于主工作区域。默认不攻击玩家；明确指定并授权的玩家可用SPECIFIED交战。友军、有主宠物或excluded保持排除，原生PvP与队伍友伤规则仍有效。";}
        else {
            props.putObject("id").put("type","string").put("pattern","^[A-Za-z][A-Za-z0-9_-]{0,95}$");props.putObject("expected_revision").put("type","integer").put("const",0);props.putObject("actor").putArray("enum").add("ai").add("player");props.putObject("dimension").put("type","string");props.putObject("target").put("type","string");
            var vector=json.createObjectNode().put("type","array").put("minItems",3).put("maxItems",3);vector.putObject("items").put("type","number");props.set("min",vector);props.set("max",vector);props.putObject("route").put("type","array").put("maxItems",128).set("items",vector);
            for(var flag:List.of("repeat","defend","allow_teleport","ping_pong","till","resume_previous","only_if_idle"))props.putObject(flag).put("type","boolean");for(var number:List.of("start_distance","stop_distance"))props.putObject(number).put("type","number");for(var number:List.of("dwell_ticks","limit"))props.putObject(number).put("type","integer").put("minimum",0);props.putObject("crop").put("type","string");
            props.set("combat",combatSchema(json));if(Set.of("start_skill","set_behavior_mode").contains(name)){var kinds=props.putObject("kind").putArray("enum");for(var k:SkillSpec.Kind.values())kinds.add(k.name());required.add("kind");}required.add("id").add("expected_revision").add("dimension");
            description="设置主工作模式并提交持续本地技能"+(kind(name)==null?"":kind(name).name())+"。actor默认ai；只有玩家明确要求接管本人时才player，使用真实客户端输入，游戏画面双击 Esc 退出，聊天/F2内Esc只处理界面。IDLE待命不工作，是否自卫由combat独立控制。COMBAT可以自动选敌；FOLLOW需target实体UUID（AI跟随本人可$owner）；PATROL需route坐标数组，可ping_pong往返；FARM/FISH/WANDER/GUARD需min/max区域。开始距离默认6、停止距离2.5，前者必须更大。repeat默认true；新身体默认自卫，切换工作保留现有战斗策略和交战规则。defend是显式覆盖旧兼容字段，通常省略，改规则用combat；工作遇怪暂时中断后重检恢复；limit=0持续，正数限制巡逻轮数/补种/渔获。FARM必须有原生种子，成熟收获后补种，不直接改作物年龄；crop可指定作物方块ID。FISH需原生鱼竿和岸边，等实际咬钩收竿。COMBAT只有玩家明确指定并授权的目标才允许PvP，被玩家攻击不自动回击；保留原生冷却、弹道与物品消耗。allow_teleport默认false，只有明确要求且具权限才启用。“打架用跑打”只用set_combat_policy，不替换工作。resume_previous=true保留当前工作，临时工作完成后重检恢复。STARTED只表示意图保存，不是完成；模型不逐格规划，不在聊天里循环轮询，后续inspect_skills查状态。";
        }
        return new Definition(name,description,schema.toString());
    }
    private static com.fasterxml.jackson.databind.node.ObjectNode combatSchema(ObjectMapper json){
        var n=json.createObjectNode().put("type","object").put("additionalProperties",false);var p=n.putObject("properties");var strategy=p.putObject("strategy").putArray("enum");for(var v:CombatPolicy.Strategy.values())strategy.add(v.name());var engagement=p.putObject("engagement").putArray("enum");for(var v:CombatPolicy.Engagement.values())engagement.add(v.name());p.putObject("protect").put("type","string");p.putObject("target").put("type","string");p.putObject("excluded").put("type","array").putObject("items").put("type","string");for(String v:List.of("leash","awareness"))p.putObject(v).put("type","number");var vector=json.createObjectNode().put("type","array").put("minItems",3).put("maxItems",3);vector.putObject("items").put("type","number");p.set("min",vector);p.set("max",vector);return n;
    }
    private SkillTools(){}
}
