package dev.mineagent.runtime.core.task;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.core.StreamReadFeature;
import com.fasterxml.jackson.core.JsonFactory;
import java.util.*;
/** Data-only complete-plan validation before any body operation. */
public record WorldActionSpec(String callId,String tool,int x,int y,int z,String block,String message,Map<String,String> options) {
    public WorldActionSpec(String callId,String tool,int x,int y,int z,String block,String message){this(callId,tool,x,y,z,block,message,Map.of());}
    public WorldActionSpec{
        if(callId==null||callId.isBlank()||callId.length()>160||!(Set.of("move_to","break_block","place_block","vein_mine","say","craft_recipe","use_item","find_recipes","create_world_package","inspect_world_content","await_world_activation","inspect_appearance","set_appearance","query_objects","revalidate_objects","create_audience","resolve_audience","inspect_audience","revoke_audience","inspect_state_push_targets","inspect_event_handlers","inspect_score_events","subscribe_score_events","inspect_object_events","subscribe_object_events","subscribe_events","inspect_subscription","set_subscription_state","create_schedule","inspect_schedule","set_schedule_state","inspect_clock","inspect_schedule_handlers","inspect_schedule_push_targets","list_shared_namespaces","read_shared_state","transact_shared_state","watch_shared_state","subscribe_shared_state","subscribe_ui_feedback","inspect_feedback","reply_feedback","inspect_content_contract","offer_content","query_deliveries","update_view","close_view","revoke_content").contains(tool)||dev.mineagent.runtime.core.compile.NativeApiToolRequest.TOOLS.contains(tool)||dev.mineagent.runtime.core.compile.NativeLiveToolRequest.TOOLS.contains(tool)||dev.mineagent.runtime.core.compile.NativeKnowledgeToolRequest.TOOLS.contains(tool))||Math.abs((long)x)>30_000_000||Math.abs((long)z)>30_000_000||y< -2048||y>2048)throw new IllegalArgumentException("WORLD_ACTION_ARGUMENTS");
        options=options==null?Map.of():Map.copyOf(options);
        block=block==null?"":block;message=message==null?"":message;
        if(tool.equals("place_block")&&!block.matches("[a-z0-9_.-]+:[a-z0-9_./-]+")||message.length()>1024||tool.equals("say")&&message.isBlank())throw new IllegalArgumentException("WORLD_ACTION_ARGUMENTS");
        if(tool.equals("craft_recipe")){if(!options.keySet().equals(Set.of("recipe","count","table"))||!resource(options.get("recipe"))||!Set.of("true","false").contains(options.get("table"))||Integer.parseInt(options.get("count"))<1||Integer.parseInt(options.get("count"))>16)throw new IllegalArgumentException("CRAFT_ARGUMENTS");}
        else if(tool.equals("use_item")){if(!options.keySet().equals(Set.of("item","hand"))||!resource(options.get("item"))||!Set.of("MAIN_HAND","OFF_HAND").contains(options.get("hand")))throw new IllegalArgumentException("USE_ARGUMENTS");}
        else if(dev.mineagent.runtime.core.feedback.FeedbackToolRequest.TOOLS.contains(tool)){if(!options.keySet().equals(Set.of("request")))throw new IllegalArgumentException("FEEDBACK_TOOL_OPTIONS");options=Map.of("request",dev.mineagent.runtime.core.feedback.FeedbackToolRequest.parse(tool,options.get("request")).canonical());}
        else if(dev.mineagent.runtime.core.delivery.DeliveryToolRequest.TOOLS.contains(tool)){if(!options.keySet().equals(Set.of("request")))throw new IllegalArgumentException("DELIVERY_TOOL_OPTIONS");options=Map.of("request",dev.mineagent.runtime.core.delivery.DeliveryToolRequest.parse(tool,options.get("request")).canonicalRequest());}
        else if(dev.mineagent.runtime.core.shared.SharedStateToolRequest.TOOLS.contains(tool)){if(!options.keySet().equals(Set.of("request")))throw new IllegalArgumentException("SHARED_TOOL_OPTIONS");options=Map.of("request",dev.mineagent.runtime.core.shared.SharedStateToolRequest.parse(tool,options.get("request")).canonical());}
        else if(dev.mineagent.runtime.core.scheduling.ScheduleToolRequest.TOOLS.contains(tool)){if(!options.keySet().equals(Set.of("request")))throw new IllegalArgumentException("SCHEDULE_TOOL_OPTIONS");options=Map.of("request",dev.mineagent.runtime.core.scheduling.ScheduleToolRequest.parse(tool,options.get("request")).canonical());}
        else if(dev.mineagent.runtime.core.events.EventToolRequest.TOOLS.contains(tool)){if(!options.keySet().equals(Set.of("request")))throw new IllegalArgumentException("EVENT_TOOL_OPTIONS");options=Map.of("request",dev.mineagent.runtime.core.events.EventToolRequest.parse(tool,options.get("request")).canonical());}
        else if(dev.mineagent.runtime.core.directory.AudienceToolRequest.TOOLS.contains(tool)){if(!options.keySet().equals(Set.of("request")))throw new IllegalArgumentException("AUDIENCE_TOOL_OPTIONS");options=Map.of("request",dev.mineagent.runtime.core.directory.AudienceToolRequest.parse(tool,options.get("request")).canonical());}
        else if(dev.mineagent.runtime.core.compile.NativeApiToolRequest.TOOLS.contains(tool)){if(!options.keySet().equals(Set.of("request")))throw new IllegalArgumentException("NATIVE_API_TOOL_OPTIONS");options=Map.of("request",dev.mineagent.runtime.core.compile.NativeApiToolRequest.parse(tool,options.get("request")).canonical());}
        else if(dev.mineagent.runtime.core.compile.NativeLiveToolRequest.TOOLS.contains(tool)){if(!options.keySet().equals(Set.of("request")))throw new IllegalArgumentException("NATIVE_LIVE_TOOL_OPTIONS");options=Map.of("request",dev.mineagent.runtime.core.compile.NativeLiveToolRequest.parse(tool,options.get("request")).canonical());}
        else if(dev.mineagent.runtime.core.compile.NativeKnowledgeToolRequest.TOOLS.contains(tool)){if(!options.keySet().equals(Set.of("request")))throw new IllegalArgumentException("NATIVE_KNOWLEDGE_TOOL_OPTIONS");options=Map.of("request",dev.mineagent.runtime.core.compile.NativeKnowledgeToolRequest.parse(tool,options.get("request")).canonical());}
        else if(tool.equals("query_objects")){if(!options.keySet().equals(Set.of("query")))throw new IllegalArgumentException("DIRECTORY_OPTIONS");options=Map.of("query",dev.mineagent.runtime.core.directory.ObjectQuery.parse(options.get("query")).canonical());}
        else if(tool.equals("revalidate_objects")){if(!options.keySet().equals(Set.of("request")))throw new IllegalArgumentException("DIRECTORY_OPTIONS");options=Map.of("request",dev.mineagent.runtime.core.directory.ObjectRevalidation.parse(options.get("request")).canonical());}
        else if(tool.equals("find_recipes")){if(!options.keySet().equals(Set.of("query"))||options.get("query").isBlank()||options.get("query").length()>80)throw new IllegalArgumentException("RECIPE_QUERY");}
        else if(tool.equals("create_world_package")){var expected=new HashSet<String>();expected.add("prompt");if(options.containsKey("native_observations"))expected.add("native_observations");if(options.containsKey("native_knowledge"))expected.add("native_knowledge");if(!options.keySet().equals(expected)||options.get("prompt").isBlank()||options.get("prompt").length()>8192)throw new IllegalArgumentException("WORLD_PACKAGE_PROMPT");if(options.containsKey("native_observations"))dev.mineagent.runtime.core.compile.NativeObservationSelection.parseCanonical(options.get("native_observations"));if(options.containsKey("native_knowledge"))dev.mineagent.runtime.core.compile.NativeObservationSelection.parseCanonical(options.get("native_knowledge"));}
        else if(tool.equals("inspect_world_content")){if(!options.keySet().equals(Set.of("package_id","offset"))||Integer.parseInt(options.get("offset"))<0||Integer.parseInt(options.get("offset"))>10000)throw new IllegalArgumentException("WORLD_PACKAGE_QUERY");UUID.fromString(options.get("package_id"));}
        else if(tool.equals("await_world_activation")&&options.containsKey("definition_id")){if(!options.keySet().equals(Set.of("package_id","canonical_sha256","definition_id"))||!options.get("canonical_sha256").matches("[a-f0-9]{64}"))throw new IllegalArgumentException("WORLD_RULE_WAIT_ARGUMENTS");UUID.fromString(options.get("package_id"));UUID.fromString(options.get("definition_id"));}
        else if(tool.equals("await_world_activation")){if(!options.keySet().equals(options.containsKey("minimum_objects")?Set.of("package_id","canonical_sha256","minimum_blocks","minimum_objects"):Set.of("package_id","canonical_sha256","minimum_blocks"))||!options.get("canonical_sha256").matches("[a-f0-9]{64}"))throw new IllegalArgumentException("WORLD_ACTIVATION_ARGUMENTS");UUID.fromString(options.get("package_id"));dev.mineagent.runtime.core.objects.WorldFootprint.parse(options);}
        else if(tool.equals("set_appearance")){if(!options.keySet().equals(Set.of("model","texture","animation","expected_revision"))||!AppearanceToolArguments.validId(options.get("model"),false)||!AppearanceToolArguments.validId(options.get("texture"),true)||!AppearanceToolArguments.validId(options.get("animation"),true)||Long.parseLong(options.get("expected_revision"))<0)throw new IllegalArgumentException("APPEARANCE_ARGUMENTS");}
        else if(!options.isEmpty())throw new IllegalArgumentException("WORLD_ACTION_OPTIONS");
    }
    private static boolean resource(String id){return id!=null&&id.matches("[a-z0-9_.-]+:[a-z0-9_./-]+");}
    public boolean hasPosition(){return !dev.mineagent.runtime.core.compile.NativeApiToolRequest.TOOLS.contains(tool)&&!dev.mineagent.runtime.core.compile.NativeLiveToolRequest.TOOLS.contains(tool)&&!dev.mineagent.runtime.core.compile.NativeKnowledgeToolRequest.TOOLS.contains(tool)&&!Set.of("say","use_item","find_recipes","create_world_package","inspect_world_content","await_world_activation","inspect_appearance","set_appearance","query_objects","revalidate_objects","create_audience","resolve_audience","inspect_audience","revoke_audience","inspect_state_push_targets","inspect_event_handlers","inspect_score_events","subscribe_score_events","inspect_object_events","subscribe_object_events","subscribe_events","inspect_subscription","set_subscription_state","create_schedule","inspect_schedule","set_schedule_state","inspect_clock","inspect_schedule_handlers","inspect_schedule_push_targets","list_shared_namespaces","read_shared_state","transact_shared_state","watch_shared_state","subscribe_shared_state","subscribe_ui_feedback","inspect_feedback","reply_feedback","inspect_content_contract","offer_content","query_deliveries","update_view","close_view","revoke_content").contains(tool)&&(!tool.equals("craft_recipe")||options.get("table").equals("true"));}
    public static List<WorldActionSpec> parse(Object raw)throws Exception{
        if(!(raw instanceof List<?> list)||list.isEmpty()||list.size()>16)throw new IllegalArgumentException("WORLD_ACTION_COUNT");
        var json=new ObjectMapper(JsonFactory.builder().enable(StreamReadFeature.STRICT_DUPLICATE_DETECTION).build());var ids=new HashSet<String>();var result=new ArrayList<WorldActionSpec>();
        try{for(var item:list){
            if(!(item instanceof Map<?,?> map)||!(map.get("id") instanceof String id)||!(map.get("name") instanceof String tool)||!(map.get("arguments") instanceof String text))throw new IllegalArgumentException();
            if(!ids.add(id)||text.length()>((Set.of("create_world_package","revalidate_objects").contains(tool)||dev.mineagent.runtime.core.shared.SharedStateToolRequest.TOOLS.contains(tool))?32768:8192))throw new IllegalArgumentException();
            if(dev.mineagent.runtime.core.feedback.FeedbackToolRequest.TOOLS.contains(tool)){result.add(new WorldActionSpec(id,tool,0,0,0,"","",Map.of("request",dev.mineagent.runtime.core.feedback.FeedbackToolRequest.parse(tool,text).canonical())));continue;}
            if(dev.mineagent.runtime.core.delivery.DeliveryToolRequest.TOOLS.contains(tool)){result.add(new WorldActionSpec(id,tool,0,0,0,"","",Map.of("request",dev.mineagent.runtime.core.delivery.DeliveryToolRequest.parse(tool,text).canonicalRequest())));continue;}
            if(dev.mineagent.runtime.core.shared.SharedStateToolRequest.TOOLS.contains(tool)){result.add(new WorldActionSpec(id,tool,0,0,0,"","",Map.of("request",dev.mineagent.runtime.core.shared.SharedStateToolRequest.parse(tool,text).canonical())));continue;}
            if(dev.mineagent.runtime.core.scheduling.ScheduleToolRequest.TOOLS.contains(tool)){result.add(new WorldActionSpec(id,tool,0,0,0,"","",Map.of("request",dev.mineagent.runtime.core.scheduling.ScheduleToolRequest.parse(tool,text).canonical())));continue;}
            if(dev.mineagent.runtime.core.events.EventToolRequest.TOOLS.contains(tool)){result.add(new WorldActionSpec(id,tool,0,0,0,"","",Map.of("request",dev.mineagent.runtime.core.events.EventToolRequest.parse(tool,text).canonical())));continue;}
            if(dev.mineagent.runtime.core.directory.AudienceToolRequest.TOOLS.contains(tool)){result.add(new WorldActionSpec(id,tool,0,0,0,"","",Map.of("request",dev.mineagent.runtime.core.directory.AudienceToolRequest.parse(tool,text).canonical())));continue;}
            if(dev.mineagent.runtime.core.compile.NativeApiToolRequest.TOOLS.contains(tool)){result.add(new WorldActionSpec(id,tool,0,0,0,"","",Map.of("request",dev.mineagent.runtime.core.compile.NativeApiToolRequest.parse(tool,text).canonical())));continue;}
            if(dev.mineagent.runtime.core.compile.NativeLiveToolRequest.TOOLS.contains(tool)){result.add(new WorldActionSpec(id,tool,0,0,0,"","",Map.of("request",dev.mineagent.runtime.core.compile.NativeLiveToolRequest.parse(tool,text).canonical())));continue;}
            if(dev.mineagent.runtime.core.compile.NativeKnowledgeToolRequest.TOOLS.contains(tool)){result.add(new WorldActionSpec(id,tool,0,0,0,"","",Map.of("request",dev.mineagent.runtime.core.compile.NativeKnowledgeToolRequest.parse(tool,text).canonical())));continue;}
            if(tool.equals("query_objects")){result.add(new WorldActionSpec(id,tool,0,0,0,"","",Map.of("query",dev.mineagent.runtime.core.directory.ObjectQuery.parse(text).canonical())));continue;}
            if(tool.equals("revalidate_objects")){result.add(new WorldActionSpec(id,tool,0,0,0,"","",Map.of("request",dev.mineagent.runtime.core.directory.ObjectRevalidation.parse(text).canonical())));continue;}
            var args=json.readTree(text);if(!args.isObject())throw new IllegalArgumentException();
            var keys=new HashSet<String>();args.fieldNames().forEachRemaining(keys::add);
            boolean table=tool.equals("craft_recipe")&&(keys.contains("x")||keys.contains("y")||keys.contains("z"));
            var expected=switch(tool){case "inspect_appearance"->Set.of();case "set_appearance"->Set.of("model","texture","animation","expected_revision");case "create_world_package"->{var v=new HashSet<String>();v.add("prompt");if(keys.contains("native_observation_ids"))v.add("native_observation_ids");if(keys.contains("native_knowledge_ids"))v.add("native_knowledge_ids");yield Set.copyOf(v);}case "inspect_world_content"->keys.contains("offset")?Set.of("package_id","offset"):Set.of("package_id");case "await_world_activation"->keys.contains("definition_id")?Set.of("package_id","canonical_sha256","definition_id"):keys.contains("minimum_objects")?(keys.contains("minimum_blocks")?Set.of("package_id","canonical_sha256","minimum_blocks","minimum_objects"):Set.of("package_id","canonical_sha256","minimum_objects")):Set.of("package_id","canonical_sha256","minimum_blocks");case "say"->Set.of("message");case "place_block"->Set.of("x","y","z","block");case "craft_recipe"->table?Set.of("recipe","count","x","y","z"):Set.of("recipe","count");case "use_item"->keys.contains("hand")?Set.of("item","hand"):Set.of("item");case "find_recipes"->Set.of("query");default->Set.of("x","y","z");};if(!keys.equals(expected))throw new IllegalArgumentException();
            int x=0,y=0,z=0;if(!Set.of("say","use_item","find_recipes","create_world_package","inspect_world_content","await_world_activation","inspect_appearance","set_appearance","query_objects","revalidate_objects","create_audience","resolve_audience","inspect_audience","revoke_audience","inspect_state_push_targets","inspect_event_handlers","inspect_score_events","subscribe_score_events","inspect_object_events","subscribe_object_events","subscribe_events","inspect_subscription","set_subscription_state","create_schedule","inspect_schedule","set_schedule_state","inspect_clock","inspect_schedule_handlers","inspect_schedule_push_targets","list_shared_namespaces","read_shared_state","transact_shared_state","watch_shared_state","subscribe_shared_state","subscribe_ui_feedback","inspect_feedback","reply_feedback","inspect_content_contract","offer_content","query_deliveries","update_view","close_view","revoke_content").contains(tool)&&(!tool.equals("craft_recipe")||table)){for(var key:List.of("x","y","z"))if(!args.path(key).isIntegralNumber()||!args.path(key).canConvertToInt())throw new IllegalArgumentException();x=args.path("x").intValue();y=args.path("y").intValue();z=args.path("z").intValue();}
            if(tool.equals("say")&&!args.path("message").isTextual()||tool.equals("place_block")&&!args.path("block").isTextual())throw new IllegalArgumentException();
            Map<String,String> options=tool.equals("set_appearance")?AppearanceToolArguments.parse(args,"expected_revision"):Map.of();
            if(tool.equals("craft_recipe")){if(!args.path("recipe").isTextual()||!args.path("count").isIntegralNumber()||!args.path("count").canConvertToInt())throw new IllegalArgumentException();options=Map.of("recipe",args.path("recipe").asText(),"count",Integer.toString(args.path("count").intValue()),"table",Boolean.toString(table));}
            if(tool.equals("use_item")){if(!args.path("item").isTextual()||args.has("hand")&&!args.path("hand").isTextual())throw new IllegalArgumentException();options=Map.of("item",args.path("item").asText(),"hand",args.path("hand").asText("MAIN_HAND"));}
            if(tool.equals("find_recipes")){if(!args.path("query").isTextual())throw new IllegalArgumentException();options=Map.of("query",args.path("query").asText());}
            if(tool.equals("create_world_package")){if(!args.path("prompt").isTextual())throw new IllegalArgumentException();var values=new LinkedHashMap<String,String>();values.put("prompt",args.path("prompt").asText());if(args.has("native_observation_ids"))values.put("native_observations",dev.mineagent.runtime.core.compile.NativeObservationSelection.parseArray(args.path("native_observation_ids")).canonical());if(args.has("native_knowledge_ids"))values.put("native_knowledge",dev.mineagent.runtime.core.compile.NativeObservationSelection.parseArray(args.path("native_knowledge_ids")).canonical());options=Map.copyOf(values);}
            if(tool.equals("inspect_world_content")){if(!args.path("package_id").isTextual()||args.has("offset")&&(!args.path("offset").isIntegralNumber()||!args.path("offset").canConvertToInt()))throw new IllegalArgumentException();options=Map.of("package_id",args.path("package_id").asText(),"offset",Integer.toString(args.path("offset").asInt(0)));}
            if(tool.equals("await_world_activation")&&args.has("definition_id")){for(var key:List.of("package_id","canonical_sha256","definition_id"))if(!args.path(key).isTextual())throw new IllegalArgumentException();options=Map.of("package_id",args.path("package_id").asText(),"canonical_sha256",args.path("canonical_sha256").asText(),"definition_id",args.path("definition_id").asText());}
            else if(tool.equals("await_world_activation")){if(!args.path("package_id").isTextual()||!args.path("canonical_sha256").isTextual())throw new IllegalArgumentException();var footprint=dev.mineagent.runtime.core.objects.WorldFootprint.parse(args);var values=new LinkedHashMap<String,String>();values.put("package_id",args.path("package_id").asText());values.put("canonical_sha256",args.path("canonical_sha256").asText());values.put("minimum_blocks",Integer.toString(footprint.blocks()));if(args.has("minimum_objects"))values.put("minimum_objects",Integer.toString(footprint.objects()));options=values;}
            result.add(new WorldActionSpec(id,tool,x,y,z,args.path("block").asText(""),args.path("message").asText(""),options));
        }}catch(Exception invalid){throw new IllegalArgumentException("WORLD_ACTION_ARGUMENTS",invalid);}
        if(result.size()!=1&&result.stream().anyMatch(a->a.tool().equals("create_world_package")))throw new IllegalArgumentException("WORLD_PACKAGE_MUST_BE_SINGLE");
        if(result.size()!=1&&result.stream().anyMatch(a->a.tool().equals("set_appearance")))throw new IllegalArgumentException("APPEARANCE_MUST_BE_SINGLE");
        if(result.size()!=1&&result.stream().anyMatch(a->dev.mineagent.runtime.core.compile.NativeApiToolRequest.TOOLS.contains(a.tool())))throw new IllegalArgumentException("NATIVE_API_TOOL_MUST_BE_SINGLE");
        if(result.size()!=1&&result.stream().anyMatch(a->dev.mineagent.runtime.core.compile.NativeLiveToolRequest.TOOLS.contains(a.tool())))throw new IllegalArgumentException("NATIVE_LIVE_TOOL_MUST_BE_SINGLE");
        if(result.size()!=1&&result.stream().anyMatch(a->dev.mineagent.runtime.core.compile.NativeKnowledgeToolRequest.TOOLS.contains(a.tool())))throw new IllegalArgumentException("NATIVE_KNOWLEDGE_TOOL_MUST_BE_SINGLE");
        return List.copyOf(result);
    }
}
