package dev.mineagent.runtime.core.building;
import java.io.*;import java.nio.file.*;import java.util.*;import java.util.function.*;import java.util.zip.*;
import static dev.mineagent.runtime.core.building.BuildingNbt.*;
import dev.mineagent.runtime.core.building.BuildingDocument.*;

/** Read existing Java Anvil terrain. Never opens a Minecraft world or runs datapacks. */
public final class AnvilBuildingReader {
    public static Map<String,Object> inspect(Path world,int offset)throws Exception{
        var regions=regions(world);if(offset<0||offset>regions.size())throw new IllegalArgumentException("BUILDING_OFFSET");var out=new ArrayList<Object>();for(var file:regions.subList(offset,Math.min(offset+32,regions.size()))){int[] r=regionCoords(file);String dim=dimension(world,file);int chunks=0;String state="OK";try(var f=new RandomAccessFile(file.toFile(),"r")){if(f.length()==0)state="EMPTY_REGION";else if(f.length()<8192)state="INVALID_HEADER";else for(int i=0;i<1024;i++)if(f.readInt()!=0)chunks++;}out.add(Map.of("state",state,"path",world.relativize(file).toString().replace('\\','/'),"dimension",dim,"region",List.of(r[0],r[1]),"xzMin",List.of(r[0]*512,r[1]*512),"xzMax",List.of(r[0]*512+511,r[1]*512+511),"chunks",chunks));}
        var data=child(BuildingNbt.read(world.resolve("level.dat")),"Data");var result=new LinkedHashMap<String,Object>();result.put("format","JAVA_ANVIL_WORLD");result.put("dataVersion",number(data,"DataVersion",-1));result.put("regions",out);result.put("totalRegions",regions.size());result.put("nextOffset",offset+32<regions.size()?offset+32:-1);result.put("untrustedContent",true);result.put("selectionRequired",true);result.put("limitations","Select dimension and absolute source min/max (each <=2048). Terrain blocks only, not players, entities, inventories, commands, functions, datapacks or complete-world execution.");return result;
    }
    private static List<Path> regions(Path root)throws IOException{try(var walk=Files.walk(root)){return walk.filter(p->Files.isRegularFile(p,LinkOption.NOFOLLOW_LINKS)&&!Files.isSymbolicLink(p)&&p.getParent().getFileName().toString().equals("region")&&p.getFileName().toString().matches("r\\.-?[0-9]+\\.-?[0-9]+\\.mca")).sorted().toList();}}
    private static String dimension(Path root,Path f){String p=root.relativize(f.getParent()).toString().replace('\\','/');return switch(p){case "region"->"minecraft:overworld";case "DIM-1/region"->"minecraft:the_nether";case "DIM1/region"->"minecraft:the_end";default->{if(p.startsWith("dimensions/")&&p.endsWith("/region")){String middle=p.substring(11,p.length()-7);int slash=middle.indexOf('/');if(slash>0)yield middle.substring(0,slash)+":"+middle.substring(slash+1);}throw new IllegalArgumentException("BUILDING_WORLD_DIMENSION");}};}
    private static int[] regionCoords(Path p){String[] n=p.getFileName().toString().split("\\.");return new int[]{Integer.parseInt(n[1]),Integer.parseInt(n[2])};}
    private static Path dimensionRoot(Path world,String dimension){if(dimension.equals("minecraft:overworld"))return world;if(dimension.equals("minecraft:the_nether"))return world.resolve("DIM-1");if(dimension.equals("minecraft:the_end"))return world.resolve("DIM1");if(!dimension.matches("[a-z0-9_.-]+:[a-z0-9_/-]+")||dimension.contains(".."))throw new IllegalArgumentException("BUILDING_DIMENSION");return world.resolve("dimensions").resolve(dimension.replace(':','/'));}
    public static Map<String,Object> stream(Path world,String dimension,Bounds bounds,boolean air,Consumer<Block> sink,BooleanSupplier permit)throws Exception{
        if(bounds.size().stream().anyMatch(x->x>2048))throw new IllegalArgumentException("BUILDING_EXTENT_2048");Path folder=dimensionRoot(world,dimension).resolve("region");long chunks=0,missing=0,blocks=0,blockEntities=0;var palette=new TreeSet<String>();
        for(int cx=Math.floorDiv(bounds.min().x(),16);cx<=Math.floorDiv(bounds.max().x(),16);cx++)for(int cz=Math.floorDiv(bounds.min().z(),16);cz<=Math.floorDiv(bounds.max().z(),16);cz++){
            if(!permit.getAsBoolean())throw new IllegalStateException("BUILDING_CANCELLED");Path file=folder.resolve("r."+Math.floorDiv(cx,32)+"."+Math.floorDiv(cz,32)+".mca");if(!Files.isRegularFile(file,LinkOption.NOFOLLOW_LINKS)||Files.size(file)==0){missing++;continue;}var n=chunk(file,cx,cz);if(n==null){missing++;continue;}chunks++;int version=number(n,"DataVersion",-1);var level=n.containsKey("Level")?child(n,"Level"):n;if(number(level,"xPos",Integer.MIN_VALUE)!=cx||number(level,"zPos",Integer.MIN_VALUE)!=cz)throw new IOException("BUILDING_CHUNK_COORDINATES");
            blockEntities+=items(level,level.containsKey("block_entities")?"block_entities":"TileEntities").size();var sections=items(level,level.containsKey("sections")?"sections":"Sections");
            for(var raw:sections){var section=compound(raw);int sy=integer(section.get("Y"));if(sy*16+15<bounds.min().y()||sy*16>bounds.max().y())continue;var container=section.containsKey("block_states")?child(section,"block_states"):section;Object pl=container.get(container.containsKey("palette")?"palette":"Palette");if(pl==null){if(section.containsKey("Blocks"))throw new IOException("BUILDING_PRE_FLATTENING_WORLD_REQUIRES_CONVERSION");continue;}var states=list(pl).stream().map(v->state(compound(v))).toList();if(states.isEmpty()||states.size()>4096)throw new IOException("BUILDING_CHUNK_PALETTE");palette.addAll(states);int bits=Math.max(4,32-Integer.numberOfLeadingZeros(states.size()-1));Object packed=container.get(container.containsKey("data")?"data":"BlockStates");long[] data=packed instanceof long[] a?a:new long[0];boolean padded=version>=2529;int per=64/bits;long expected=padded?(4096+per-1)/per:(4096L*bits+63)/64;if(states.size()>1&&data.length!=expected||states.size()==1&&data.length!=0&&data.length!=expected)throw new IOException("BUILDING_CHUNK_DATA_LENGTH");
                for(int i=0;i<4096;i++){int index=0;if(data.length>0){long bit=(long)i*bits;int word=padded?i/per:(int)(bit>>>6),shift=padded?i%per*bits:(int)(bit&63);long v=data[word]>>>shift;if(!padded&&shift+bits>64)v|=data[word+1]<<(64-shift);index=(int)(v&((1L<<bits)-1));}if(index>=states.size())throw new IOException("BUILDING_PALETTE_INDEX");Pos p=new Pos(cx*16+(i&15),sy*16+(i>>>8),cz*16+(i>>>4&15));String state=states.get(index);if(bounds.contains(p)&&(air||!BuildingDocument.isAir(state))){sink.accept(new Block(p,state));blocks++;}}
            }
        }
        return Map.of("format","JAVA_ANVIL_WORLD","dimension",dimension,"sourceChunks",chunks,"missingChunks",missing,"blocks",blocks,"blockEntityRecords",blockEntities,"palette",palette,"bounds",bounds);
    }
    private static Map<String,Object> chunk(Path file,int x,int z)throws Exception{
        try(var f=new RandomAccessFile(file.toFile(),"r")){long bytes=f.length();if(bytes<8192)throw new IOException("BUILDING_REGION_HEADER");f.seek((Math.floorMod(x,32)+32*Math.floorMod(z,32))*4L);int loc=f.readInt(),sector=loc>>>8,count=loc&255;if(loc==0)return null;if(sector<2||count==0||(long)(sector+count)*4096>bytes)throw new IOException("BUILDING_REGION_LOCATION");f.seek(sector*4096L);int length=f.readInt();int compression=f.readUnsignedByte();if(length<1||length>(long)count*4096-4)throw new IOException("BUILDING_REGION_LENGTH");if((compression&128)!=0)throw new IOException("BUILDING_EXTERNAL_CHUNK_UNSUPPORTED");byte[] raw=new byte[length-1];f.readFully(raw);InputStream in=new ByteArrayInputStream(raw);in=switch(compression){case 1->new GZIPInputStream(in);case 2->new InflaterInputStream(in);case 3->in;default->throw new IOException("BUILDING_REGION_COMPRESSION_UNSUPPORTED");};try(var decoded=in){return BuildingNbt.read(decoded);}}
    }
    private AnvilBuildingReader(){}
}
