package dev.mineagent.runtime.core.building;
import java.nio.file.*;
import java.util.*;
import java.util.function.*;
import static dev.mineagent.runtime.core.building.BuildingNbt.*;

/** Format-independent block stream. Source coordinates and complete state strings are retained. */
public final class BuildingDocument {
    public record Pos(int x,int y,int z){public List<Integer> list(){return List.of(x,y,z);}public Pos add(Pos p){return new Pos(Math.addExact(x,p.x),Math.addExact(y,p.y),Math.addExact(z,p.z));}}
    public record Bounds(Pos min,Pos max){public Bounds{if(min.x>max.x||min.y>max.y||min.z>max.z)throw new IllegalArgumentException("BUILDING_BOUNDS");}public boolean contains(Pos p){return p.x>=min.x&&p.x<=max.x&&p.y>=min.y&&p.y<=max.y&&p.z>=min.z&&p.z<=max.z;}public List<Integer> size(){return List.of(Math.addExact(max.x-min.x,1),Math.addExact(max.y-min.y,1),Math.addExact(max.z-min.z,1));}public Bounds union(Bounds b){return new Bounds(new Pos(Math.min(min.x,b.min.x),Math.min(min.y,b.min.y),Math.min(min.z,b.min.z)),new Pos(Math.max(max.x,b.max.x),Math.max(max.y,b.max.y),Math.max(max.z,b.max.z)));}}
    public record Block(Pos pos,String state){}
    @FunctionalInterface private interface Source{void stream(Bounds selection,Consumer<Block> sink,BooleanSupplier permit);}
    private record Region(String name,Bounds bounds,List<String> palette,Source source){}
    private final String format;private final int dataVersion;private final List<Region> regions=new ArrayList<>();private long blockEntities,entities;private final List<String> warnings=new ArrayList<>();
    private BuildingDocument(String format,int dataVersion){this.format=format;this.dataVersion=dataVersion;}
    public Bounds bounds(){return regions.stream().map(Region::bounds).reduce(Bounds::union).orElseThrow(()->new IllegalArgumentException("BUILDING_NO_REGIONS"));}
    public Map<String,Object> metadata(){var out=new LinkedHashMap<String,Object>();out.put("format",format);out.put("dataVersion",dataVersion);out.put("bounds",bounds());out.put("size",bounds().size());out.put("regions",regions.stream().map(r->Map.of("name",r.name,"bounds",r.bounds,"paletteSize",r.palette.size())).toList());out.put("blockEntityRecords",blockEntities);out.put("entityRecords",entities);out.put("warnings",warnings);out.put("untrustedContent",true);out.put("dataPolicy","Blocks and states only for placement; entity/NBT payload, scheduled ticks, inventories and datapacks are not executed or restored.");return out;}
    public void stream(Bounds selection,boolean air,Consumer<Block> sink,BooleanSupplier permit){for(var r:regions)r.source.stream(selection,b->{if((selection==null||selection.contains(b.pos))&&(air||!isAir(b.state)))sink.accept(b);},permit);}
    public Set<String> palette(){var p=new TreeSet<String>();for(var r:regions)p.addAll(r.palette);return p;}
    public static boolean isAir(String s){return Set.of("minecraft:air","minecraft:cave_air","minecraft:void_air").contains(s);}
    public static BuildingDocument read(Path file)throws Exception{return fromNbt(BuildingNbt.read(file));}
    public static BuildingDocument fromNbt(Map<String,Object> root){
        if(root.containsKey("Regions"))return litematic(root);
        if(root.containsKey("Schematic"))root=child(root,"Schematic");
        if(root.containsKey("Version")&&root.containsKey("Width"))return sponge(root);
        if(root.containsKey("palette")||root.containsKey("palettes"))return structure(root);
        if(root.containsKey("Blocks")&&root.containsKey("Data"))return legacy(root);
        throw new IllegalArgumentException("BUILDING_FORMAT_UNSUPPORTED");
    }
    private static Pos vector(Object o){if(o instanceof Map<?,?>){var n=compound(o);return new Pos(integer(n.get("x")),integer(n.get("y")),integer(n.get("z")));}if(o instanceof int[] a&&a.length==3)return new Pos(a[0],a[1],a[2]);var a=list(o);if(a.size()!=3)throw new IllegalArgumentException("BUILDING_VECTOR");return new Pos(integer(a.get(0)),integer(a.get(1)),integer(a.get(2)));}
    private static long volume(Pos s){if(s.x<1||s.y<1||s.z<1||s.x>30_000_000||s.y>30_000_000||s.z>30_000_000)throw new IllegalArgumentException("BUILDING_SOURCE_SIZE");return Math.multiplyExact(Math.multiplyExact((long)s.x,s.y),s.z);}
    private static Bounds bound(Pos min,Pos size){volume(size);return new Bounds(min,min.add(new Pos(size.x-1,size.y-1,size.z-1)));}
    private static Pos at(long i,Pos size,Pos base){return new Pos(base.x+(int)(i%size.x),base.y+(int)(i/size.x/size.z),base.z+(int)(i/size.x%size.z));}
    private static List<String> states(Object o){var a=list(o);if(a.isEmpty()||a.size()>65536)throw new IllegalArgumentException("BUILDING_PALETTE");return a.stream().map(v->state(compound(v))).toList();}
    private static void active(long i,BooleanSupplier permit){if((i&4095)==0&&(!permit.getAsBoolean()||Thread.currentThread().isInterrupted()))throw new IllegalStateException("BUILDING_CANCELLED");}
    private static void indices(Pos size,Pos base,Bounds selection,java.util.function.LongConsumer consumer,BooleanSupplier permit){Bounds bounds=bound(base,size);int x0=base.x,y0=base.y,z0=base.z,x1=bounds.max.x,y1=bounds.max.y,z1=bounds.max.z;if(selection!=null){x0=Math.max(x0,selection.min.x);y0=Math.max(y0,selection.min.y);z0=Math.max(z0,selection.min.z);x1=Math.min(x1,selection.max.x);y1=Math.min(y1,selection.max.y);z1=Math.min(z1,selection.max.z);}long visited=0;for(int y=y0;y<=y1;y++)for(int z=z0;z<=z1;z++)for(int x=x0;x<=x1;x++){active(visited++,permit);consumer.accept((long)(y-base.y)*size.x*size.z+(long)(z-base.z)*size.x+x-base.x);}}
    private static BuildingDocument litematic(Map<String,Object> n){
        int version=number(n,"Version",-1);if(version<1||version>7)throw new IllegalArgumentException("BUILDING_LITEMATIC_VERSION");var d=new BuildingDocument("LITEMATICA",number(n,"MinecraftDataVersion",-1));var rs=child(n,"Regions");if(rs.isEmpty()||rs.size()>1024)throw new IllegalArgumentException("BUILDING_REGIONS");
        for(String name:new TreeSet<>(rs.keySet())){var r=compound(rs.get(name));Pos p=vector(r.get("Position")),signed=vector(r.get("Size"));if(signed.x==Integer.MIN_VALUE||signed.y==Integer.MIN_VALUE||signed.z==Integer.MIN_VALUE)throw new IllegalArgumentException("BUILDING_SIZE");Pos size=new Pos(Math.abs(signed.x),Math.abs(signed.y),Math.abs(signed.z));long count=volume(size);Pos min=p.add(new Pos(Math.min(0,signed.x+1),Math.min(0,signed.y+1),Math.min(0,signed.z+1)));var palette=states(r.get("BlockStatePalette"));if(!(r.get("BlockStates") instanceof long[] data))throw new IllegalArgumentException("BUILDING_PACKED_STATES");int bits=Math.max(2,32-Integer.numberOfLeadingZeros(palette.size()-1));if(count>(Long.MAX_VALUE-63)/bits||data.length!=(count*bits+63)/64)throw new IllegalArgumentException("BUILDING_PACKED_LENGTH");
            d.blockEntities+=items(r,"TileEntities").size();d.entities+=items(r,"Entities").size();d.regions.add(new Region(name,bound(min,size),palette,(selection,sink,permit)->{indices(size,min,selection,i->{long start=i*bits;int word=(int)(start>>>6),shift=(int)(start&63);long value=data[word]>>>shift;if(shift+bits>64)value|=data[word+1]<<(64-shift);int index=(int)(value&((1L<<bits)-1));if(index>=palette.size())throw new IllegalArgumentException("BUILDING_PALETTE_INDEX");sink.accept(new Block(at(i,size,min),palette.get(index)));},permit);}));
        }
        var sizes=d.bounds().size();if(sizes.stream().anyMatch(v->v>2048))d.warnings.add("Overall extent exceeds 2048: select one region or a smaller bounding box before placing.");return d;
    }
    private static BuildingDocument structure(Map<String,Object> n){var d=new BuildingDocument("STRUCTURE_NBT_CREATE",number(n,"DataVersion",-1));Pos size=vector(n.get("size"));var palette=states(n.containsKey("palette")?n.get("palette"):list(n.get("palettes")).getFirst());if(n.containsKey("palettes")&&list(n.get("palettes")).size()>1)d.warnings.add("Multiple palettes: using variant 0.");var blocks=items(n,"blocks");d.blockEntities=blocks.stream().filter(b->compound(b).containsKey("nbt")).count();d.entities=items(n,"entities").size();Bounds bounds=bound(new Pos(0,0,0),size);d.regions.add(new Region("structure",bounds,palette,(selection,sink,permit)->{var seen=new HashSet<Pos>();long i=0;for(var o:blocks){active(i++,permit);var b=compound(o);Pos p=vector(b.get("pos"));int state=integer(b.get("state"));if(!bounds.contains(p)||state<0||state>=palette.size()||!seen.add(p))throw new IllegalArgumentException("BUILDING_STRUCTURE_BLOCK");sink.accept(new Block(p,palette.get(state)));}}));return d;}
    public static String legacyState(int id,int data){if(id==0)return "minecraft:air";return "mineagent_legacy:block_"+id+"_"+data;}
    private static BuildingDocument legacy(Map<String,Object> n){
        var d=new BuildingDocument("LEGACY_SCHEMATIC",1343);Pos size=new Pos(integer(n.get("Width"))&65535,integer(n.get("Height"))&65535,integer(n.get("Length"))&65535);long count=volume(size);if(!(n.get("Blocks") instanceof byte[] ids)||!(n.get("Data") instanceof byte[] values)||ids.length!=count||values.length!=count)throw new IllegalArgumentException("BUILDING_LEGACY_DATA");byte[] add=n.get("AddBlocks") instanceof byte[] a?a:new byte[0];if(add.length!=0&&add.length!=(count+1)/2)throw new IllegalArgumentException("BUILDING_LEGACY_DATA");
        if(n.containsKey("SchematicaMapping")&&child(n,"SchematicaMapping").keySet().stream().anyMatch(k->k.contains(":")&&!k.startsWith("minecraft:")))throw new IllegalArgumentException("BUILDING_LEGACY_MOD_MAPPING_REQUIRES_CONVERSION");
        var palette=new TreeSet<String>();for(int i=0;i<ids.length;i++){int id=(ids[i]&255)+(add.length==0?0:((add[i/2]>>((i&1)*4))&15)<<8);palette.add(legacyState(id,values[i]&15));}
        d.blockEntities=items(n,"TileEntities").size();d.entities=items(n,"Entities").size();d.regions.add(new Region("schematic",bound(new Pos(0,0,0),size),List.copyOf(palette),(selection,sink,permit)->{for(int i=0;i<ids.length;i++){active(i,permit);int id=(ids[i]&255)+(add.length==0?0:((add[i/2]>>((i&1)*4))&15)<<8);sink.accept(new Block(at(i,size,new Pos(0,0,0)),legacyState(id,values[i]&15)));}}));return d;
    }
    private static BuildingDocument sponge(Map<String,Object> n){int version=number(n,"Version",-1);if(version<1||version>3)throw new IllegalArgumentException("BUILDING_SCHEM_VERSION");var d=new BuildingDocument("SPONGE_SCHEM_"+version,number(n,"DataVersion",-1));Pos size=new Pos(integer(n.get("Width"))&65535,integer(n.get("Height"))&65535,integer(n.get("Length"))&65535);long count=volume(size);Pos base=n.containsKey("Offset")?vector(n.get("Offset")):new Pos(0,0,0);var container=version==3?child(n,"Blocks"):n;var pal=child(container,"Palette");if(pal.isEmpty()||pal.size()>65536)throw new IllegalArgumentException("BUILDING_PALETTE");var byIndex=new TreeMap<Integer,String>();for(var e:pal.entrySet()){int i=integer(e.getValue());String key=e.getKey().contains(":")?e.getKey():"minecraft:"+e.getKey();if(i<0||byIndex.containsKey(i)||!key.matches("[a-z0-9_.-]+:[a-z0-9_./-]+(?:\\[[a-zA-Z0-9_=,.-]+\\])?"))throw new IllegalArgumentException("BUILDING_PALETTE");byIndex.put(i,key);}var palette=List.copyOf(byIndex.values());Object value=container.get(version==3?"Data":"BlockData");if(!(value instanceof byte[] bytes))throw new IllegalArgumentException("BUILDING_SCHEM_DATA");d.blockEntities=items(container,version==1?"TileEntities":"BlockEntities").size();d.entities=items(n,"Entities").size();d.regions.add(new Region("schematic",bound(base,size),List.copyOf(palette),(selection,sink,permit)->{int offset=0;for(long i=0;i<count;i++){active(i,permit);int v=0,shift=0,b;do{if(offset>=bytes.length||shift>=35)throw new IllegalArgumentException("BUILDING_VARINT");b=bytes[offset++]&255;if(shift==28&&(b&0xf0)!=0)throw new IllegalArgumentException("BUILDING_VARINT");v|=(b&127)<<shift;shift+=7;}while((b&128)!=0);if(v<0||!byIndex.containsKey(v))throw new IllegalArgumentException("BUILDING_PALETTE_INDEX");sink.accept(new Block(at(i,size,base),byIndex.get(v)));}if(offset!=bytes.length)throw new IllegalArgumentException("BUILDING_SCHEM_TRAILING");}));return d;}
}
