package dev.mineagent.runtime.neoforge.client;
import dev.mineagent.runtime.neoforge.network.AgentPngSkinPayload;import net.minecraft.client.Minecraft;import net.minecraft.client.renderer.texture.DynamicTexture;import net.minecraft.core.ClientAsset;import net.minecraft.resources.Identifier;import net.minecraft.world.entity.player.*;import java.util.*;
public final class AgentPngSkinClient {
 private record Skin(String hash,long revision,PlayerSkin skin){}private static Object wire;private static final Map<UUID,Skin> skins=new HashMap<>();private static final Set<Identifier> textures=new HashSet<>();
 public static void accept(AgentPngSkinPayload p,Object connection){var mc=Minecraft.getInstance();if(mc.getConnection()==null||mc.getConnection().getConnection()!=connection)return;if(wire!=connection){clear();wire=connection;}var old=skins.get(p.agent());if(old!=null&&old.revision>p.revision())return;byte[] png=p.png();String hash=hash(png);if(!hash.equals(p.sha256()))throw new IllegalArgumentException("SKIN_PAYLOAD_HASH");var texture=new ClientAsset.ResourceTexture(Identifier.fromNamespaceAndPath("mineagent_runtime","dynamic_skin/"+hash));if(!textures.contains(texture.texturePath()))try{var image=com.mojang.blaze3d.platform.NativeImage.read(png);if(image.getWidth()!=64||image.getHeight()!=64){image.close();throw new IllegalArgumentException("SKIN_IMAGE_SIZE");}mc.getTextureManager().register(texture.texturePath(),new DynamicTexture(()->"MineAgent PNG skin",image));textures.add(texture.texturePath());}catch(java.io.IOException e){throw new IllegalArgumentException("SKIN_IMAGE_DECODE",e);}skins.put(p.agent(),new Skin(hash,p.revision(),new PlayerSkin(texture,null,null,p.model().equals("slim")?PlayerModelType.SLIM:PlayerModelType.WIDE,false)));if(old!=null&&!old.hash.equals(hash)&&skins.values().stream().noneMatch(v->v.hash.equals(old.hash))){var obsolete=old.skin.body().texturePath();mc.getTextureManager().release(obsolete);textures.remove(obsolete);}}
 public static PlayerSkin skin(UUID id){var mc=Minecraft.getInstance();if(mc.getConnection()==null||mc.getConnection().getConnection()!=wire){clear();wire=null;return null;}var v=skins.get(id);return v==null?null:v.skin;}
 private static String hash(byte[] bytes){try{return dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer.sha256(bytes);}catch(Exception e){throw new IllegalStateException("SKIN_HASH",e);}}
 private static void clear(){for(var id:textures)Minecraft.getInstance().getTextureManager().release(id);textures.clear();skins.clear();}
 private AgentPngSkinClient(){}
}
