package dev.mineagent.runtime.core.events;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.core.*;
import dev.mineagent.runtime.core.directory.ObjectQuery;
import java.util.*;
public record EventToolRequest(String tool,RuntimeEventStore.Request request,UUID id,long expectedRevision,String state,int offset,String objective) {
    public EventToolRequest(String tool,RuntimeEventStore.Request request,UUID id,long expectedRevision,String state,int offset){this(tool,request,id,expectedRevision,state,offset,"");}
    public static final Set<String> TOOLS=Set.of("inspect_state_push_targets","inspect_event_handlers","inspect_score_events","subscribe_score_events","inspect_object_events","subscribe_object_events","subscribe_ui_feedback","subscribe_events","subscribe_shared_state","inspect_subscription","set_subscription_state");
    private static final ObjectMapper JSON=new ObjectMapper(JsonFactory.builder().enable(StreamReadFeature.STRICT_DUPLICATE_DETECTION).build()).enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS);
    public static EventToolRequest parse(String tool,String source){try{
        if(!TOOLS.contains(tool)||source==null||source.length()>16384)throw new IllegalArgumentException();var n=JSON.readTree(source);
        if(tool.equals("inspect_state_push_targets")){keys(n,Set.of("instance_id","offset"),Set.of("instance_id"));int offset=integer(n,"offset",0);if(offset<0||offset>128)throw new IllegalArgumentException();return new EventToolRequest(tool,null,UUID.fromString(text(n,"instance_id","")),0,"",offset);}
        if(tool.equals("inspect_event_handlers")){keys(n,Set.of("instance_id","offset"),Set.of("instance_id"));int offset=integer(n,"offset",0);if(offset<0||offset>128)throw new IllegalArgumentException();return new EventToolRequest(tool,null,UUID.fromString(text(n,"instance_id","")),0,"",offset);}
        if(tool.equals("inspect_score_events")){keys(n,Set.of("objective","offset"),Set.of());String objective=text(n,"objective","");if(!objective.isEmpty())ScoreEventFilter.name(objective,16);int offset=integer(n,"offset",0);if(offset<0||offset>(objective.isEmpty()?16384:4096))throw new IllegalArgumentException();return new EventToolRequest(tool,null,null,0,"",offset,objective);}
        if(tool.equals("subscribe_score_events")){
            var fields=new HashSet<>(ScoreEventFilter.FIELDS);fields.addAll(Set.of("mode","goal","max_wakes","max_model_calls","pending_limit","cooldown_ms","ttl_seconds","script","push"));keys(n,fields,Set.of("objective","criteria","mode"));
            var filter=ScoreEventFilter.parse(n);String mode=text(n,"mode","");if(mode.equals("AGENT_WAKE")&&(!n.has("goal")||!n.has("max_wakes")||!n.has("max_model_calls")))throw new IllegalArgumentException();
            var request=new RuntimeEventStore.Request(Set.of(ScoreEventFilter.SOURCE),mode,null,text(n,"goal",""),integer(n,"max_wakes",0),integer(n,"max_model_calls",0),integer(n,"pending_limit",4),integer(n,"cooldown_ms",1000),integer(n,"ttl_seconds",3600),null,null,null,filter,ScriptEventConsumer.optional(n),StatePushConsumer.optional(n));return new EventToolRequest(tool,request,null,0,"",0);
        }
        if(tool.equals("inspect_object_events")){keys(n,Set.of("instance_id","offset"),Set.of("instance_id"));int offset=integer(n,"offset",0);if(offset<0||offset>32)throw new IllegalArgumentException();return new EventToolRequest(tool,null,UUID.fromString(text(n,"instance_id","")),0,"",offset);}
        if(tool.equals("subscribe_object_events")){
            var fields=new HashSet<>(ObjectInteractionFilter.FIELDS);fields.addAll(Set.of("mode","goal","max_wakes","max_model_calls","pending_limit","cooldown_ms","ttl_seconds","script","push"));var required=new HashSet<>(ObjectInteractionFilter.FIELDS);required.remove("actor_ids");required.add("mode");keys(n,fields,required);
            var filter=ObjectInteractionFilter.parse(n);String mode=text(n,"mode","");if(mode.equals("AGENT_WAKE")&&(!n.has("goal")||!n.has("max_wakes")||!n.has("max_model_calls")))throw new IllegalArgumentException();
            var request=new RuntimeEventStore.Request(Set.of(ObjectInteractionFilter.SOURCE),mode,null,text(n,"goal",""),integer(n,"max_wakes",0),integer(n,"max_model_calls",0),integer(n,"pending_limit",4),integer(n,"cooldown_ms",1000),integer(n,"ttl_seconds",3600),null,null,filter,null,ScriptEventConsumer.optional(n),StatePushConsumer.optional(n));return new EventToolRequest(tool,request,null,0,"",0);
        }
        if(tool.equals("subscribe_ui_feedback")){
            var fields=new HashSet<>(dev.mineagent.runtime.core.feedback.FeedbackSubscriptionFilter.FIELDS);fields.addAll(Set.of("mode","goal","max_wakes","max_model_calls","pending_limit","cooldown_ms","ttl_seconds"));var required=new HashSet<>(dev.mineagent.runtime.core.feedback.FeedbackSubscriptionFilter.FIELDS);required.add("mode");keys(n,fields,required);
            var filter=dev.mineagent.runtime.core.feedback.FeedbackSubscriptionFilter.parse(n);String mode=text(n,"mode","");if(mode.equals("AGENT_WAKE")&&(!n.has("goal")||!n.has("max_wakes")||!n.has("max_model_calls")))throw new IllegalArgumentException();
            return new EventToolRequest(tool,new RuntimeEventStore.Request(Set.of("UI_FEEDBACK"),mode,null,text(n,"goal",""),integer(n,"max_wakes",0),integer(n,"max_model_calls",0),integer(n,"pending_limit",4),integer(n,"cooldown_ms",1000),integer(n,"ttl_seconds",3600),null,filter),null,0,"",0);
        }
        if(tool.equals("subscribe_shared_state")){
            var fields=new HashSet<>(dev.mineagent.runtime.core.shared.SharedStateTarget.FIELDS);fields.addAll(Set.of("schema_version","keys","when","mode","goal","max_wakes","max_model_calls","pending_limit","cooldown_ms","ttl_seconds","script","push"));var required=new HashSet<>(dev.mineagent.runtime.core.shared.SharedStateTarget.FIELDS);required.addAll(Set.of("schema_version","keys","when","mode"));keys(n,fields,required);
            var filter=dev.mineagent.runtime.core.shared.SharedSubscriptionFilter.parse(n);String mode=text(n,"mode","");if(mode.equals("AGENT_WAKE")&&(!n.has("max_wakes")||!n.has("max_model_calls")||!n.has("goal")))throw new IllegalArgumentException();
            var request=new RuntimeEventStore.Request(Set.of("SHARED_STATE_CHANGED"),mode,null,text(n,"goal",""),integer(n,"max_wakes",0),integer(n,"max_model_calls",0),integer(n,"pending_limit",4),integer(n,"cooldown_ms",1000),integer(n,"ttl_seconds",3600),filter,null,null,null,ScriptEventConsumer.optional(n),StatePushConsumer.optional(n));return new EventToolRequest(tool,request,null,0,"",0);
        }
        if(tool.equals("subscribe_events")){
            keys(n,Set.of("sources","mode","query","goal","max_wakes","max_model_calls","pending_limit","cooldown_ms","ttl_seconds","script","push"),Set.of("sources","mode","query"));
            if(!n.get("sources").isArray()||n.get("sources").isEmpty()||n.get("sources").size()>2)throw new IllegalArgumentException();var sources=new HashSet<String>();for(var value:n.get("sources")){if(!value.isTextual()||!sources.add(value.asText()))throw new IllegalArgumentException();}
            String mode=text(n,"mode","");if(mode.equals("AGENT_WAKE")&&(!n.has("max_wakes")||!n.has("max_model_calls")||!n.has("goal")))throw new IllegalArgumentException();
            var request=new RuntimeEventStore.Request(sources,mode,ObjectQuery.parse(n.get("query")),text(n,"goal",""),integer(n,"max_wakes",0),integer(n,"max_model_calls",0),integer(n,"pending_limit",4),integer(n,"cooldown_ms",1000),integer(n,"ttl_seconds",3600),null,null,null,null,ScriptEventConsumer.optional(n),StatePushConsumer.optional(n));return new EventToolRequest(tool,request,null,0,"",0);
        }
        if(tool.equals("inspect_subscription")){keys(n,Set.of("subscription_id","offset"),Set.of("subscription_id"));int offset=integer(n,"offset",0);if(offset<0||offset>131072)throw new IllegalArgumentException();return new EventToolRequest(tool,null,UUID.fromString(text(n,"subscription_id","")),0,"",offset);}
        keys(n,Set.of("subscription_id","expected_revision","state"),Set.of("subscription_id","expected_revision","state"));var revision=n.get("expected_revision");String state=text(n,"state","");if(!revision.isIntegralNumber()||!revision.canConvertToLong()||revision.longValue()<1||!Set.of("ACTIVE","PAUSED","CANCELLED").contains(state))throw new IllegalArgumentException();return new EventToolRequest(tool,null,UUID.fromString(text(n,"subscription_id","")),revision.longValue(),state,0);
    }catch(Exception e){throw new IllegalArgumentException("EVENT_TOOL_ARGUMENTS",e);}}
    public String canonical(){try{var data=new LinkedHashMap<String,Object>();if(tool.equals("inspect_state_push_targets")||tool.equals("inspect_event_handlers")){data.put("instance_id",id);data.put("offset",offset);}else if(tool.equals("inspect_score_events")){data.put("objective",objective);data.put("offset",offset);}else if(tool.equals("inspect_object_events")){data.put("instance_id",id);data.put("offset",offset);}else if(tool.equals("subscribe_score_events")||tool.equals("subscribe_object_events")||tool.equals("subscribe_events")||tool.equals("subscribe_shared_state")||tool.equals("subscribe_ui_feedback")){if(request.score()!=null){data.putAll(request.score().wire());data.put("mode",request.mode());}else if(request.object()!=null){data.putAll(request.object().wire());data.put("mode",request.mode());}else if(request.feedback()!=null){data.putAll(request.feedback().wire());data.put("mode",request.mode());}else if(request.shared()==null){data.put("sources",request.sources().stream().sorted().toList());data.put("mode",request.mode());data.put("query",JSON.readTree(request.query().canonical()));}else{data.putAll(request.shared().wire());data.put("mode",request.mode());}if(request.script()!=null)data.put("script",request.script().wire());if(request.push()!=null)data.put("push",request.push().wire());data.put("goal",request.goal());data.put("max_wakes",request.maxWakes());data.put("max_model_calls",request.maxModelCalls());data.put("pending_limit",request.pendingLimit());data.put("cooldown_ms",request.cooldownMillis());data.put("ttl_seconds",request.ttlSeconds());}else{data.put("subscription_id",id);if(tool.equals("inspect_subscription"))data.put("offset",offset);else{data.put("expected_revision",expectedRevision);data.put("state",state);}}return JSON.writeValueAsString(data);}catch(Exception e){throw new IllegalArgumentException("EVENT_TOOL_ENCODING",e);}}
    private static String text(JsonNode n,String field,String fallback){if(!n.has(field))return fallback;if(!n.get(field).isTextual())throw new IllegalArgumentException();return n.get(field).asText();}
    private static int integer(JsonNode n,String field,int fallback){if(!n.has(field))return fallback;var v=n.get(field);if(!v.isIntegralNumber()||!v.canConvertToInt())throw new IllegalArgumentException();return v.intValue();}
    private static void keys(JsonNode n,Set<String> allowed,Set<String> required){if(n==null||!n.isObject())throw new IllegalArgumentException();var keys=new HashSet<String>();n.fieldNames().forEachRemaining(keys::add);if(!allowed.containsAll(keys)||!keys.containsAll(required))throw new IllegalArgumentException();}
}
