package dev.mineagent.runtime.neoforge.client.host;
import dev.mineagent.runtime.neoforge.host.LocalHostCommands;
import dev.mineagent.runtime.core.host.HostCommandRequest;
import dev.mineagent.runtime.client.host.*;
import net.minecraft.client.Minecraft;
import net.minecraft.server.MinecraftServer;
import net.minecraft.network.chat.*;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicBoolean;
import static net.minecraft.commands.Commands.*;
import com.mojang.brigadier.arguments.StringArgumentType;

/** Local-only opaque chat decisions. The approval token is never returned to server tools or the model. */
@EventBusSubscriber(modid="mineagent_runtime",value=Dist.CLIENT)
public final class ClientHostCommands implements LocalHostCommands.Endpoint {
 private static final ClientHostCommands INSTANCE=new ClientHostCommands();
 private static final ExecutorService IO=Executors.newSingleThreadExecutor(r->{var t=new Thread(r,"mineagent-local-python");t.setDaemon(true);return t;});
 private static final ExecutorService OUTPUT=Executors.newVirtualThreadPerTaskExecutor();
 private final Map<UUID,Pending> queue=new LinkedHashMap<>();
 private record OutputScope(MinecraftServer server,UUID owner){}
 private final Map<UUID,OutputScope> outputs=new ConcurrentHashMap<>();
 private volatile MinecraftServer server;private volatile UUID owner;private volatile Pending pending;private boolean installed,dispatching;private int acceptedCount,rejectedCount,invalidTokenCount,duplicateApproveCount;
 private static final class Pending {final HostCommandRequest request;final MinecraftServer server;final UUID owner,token=UUID.randomUUID();final Object connection;final CompletableFuture<Map<String,Object>> result=new CompletableFuture<>();final AtomicBoolean live=new AtomicBoolean(true);final java.util.concurrent.atomic.AtomicReference<String> cancellation=new java.util.concurrent.atomic.AtomicReference<>("");volatile String phase="AWAITING_APPROVAL";final long expires=System.nanoTime()+TimeUnit.MINUTES.toNanos(3);boolean started,approved;int cursor;Pending(HostCommandRequest r,MinecraftServer s,UUID o,Object c){request=r;server=s;owner=o;connection=c;}}
 public boolean matches(MinecraftServer s,UUID id){return server==s&&id.equals(owner);}
 public Map<String,Object> inspect(){var r=new LinkedHashMap<String,Object>();r.put("available",ManagedPythonRuntime.supported());r.put("platform",System.getProperty("os.name","unknown"));r.put("engine","JAVA_MANAGED_PYTHON");r.put("runtime",new ManagedPythonRuntime(Minecraft.getInstance().gameDirectory.toPath()).inspect());r.put("approval","NATIVE_CHAT_CLICK_PER_OPERATION");r.put("scriptMaxChars",8192);r.put("timeoutMaxSeconds",60);r.put("packageInstallTimeoutMaxSeconds",300);r.put("outputPreviewBytesPerStream",LocalPythonExecutor.OUTPUT_BYTES);r.put("workingDirectory","current Minecraft instance/mineagent-host/workspace");r.put("notFilesystemSandbox",true);r.put("remoteServerAccess",false);r.put("systemPythonUsed",false);return r;}
 public CompletableFuture<Map<String,Object>> request(MinecraftServer s,UUID id,HostCommandRequest r){var result=new CompletableFuture<Map<String,Object>>();Minecraft.getInstance().execute(()->{var mc=Minecraft.getInstance();if(!matches(s,id)||mc.getSingleplayerServer()!=s||mc.player==null||!id.equals(mc.player.getUUID())||!ManagedPythonRuntime.supported()){result.complete(Map.of("status","REJECTED","error","HOST_UNAVAILABLE_OR_CONTEXT_CHANGED"));return;}var existing=queue.get(r.operation());if(existing!=null){if(!existing.request.sha256().equals(r.sha256())){result.complete(Map.of("status","REJECTED","error","HOST_OPERATION_REUSED"));return;}existing.result.whenComplete((v,e)->{if(e==null)result.complete(v);else result.completeExceptionally(e);});return;}var p=new Pending(r,s,id,mc.getConnection());queue.put(r.operation(),p);p.result.whenComplete((v,e)->{if(e!=null)result.complete(Map.of("status","UNKNOWN","error","HOST_RESULT_UNAVAILABLE"));else result.complete(v);});prompt(p);});return result;}
 public CompletableFuture<Map<String,Object>> output(MinecraftServer s,UUID id,UUID operation,String stream,int offset){return CompletableFuture.supplyAsync(()->{try{var scope=outputs.get(operation);if(!matches(s,id)||scope==null||scope.server()!=s||!scope.owner().equals(id))throw new SecurityException("HOST_OUTPUT_SCOPE");var result=new LocalPythonExecutor(Minecraft.getInstance().gameDirectory.toPath()).output(operation,stream,offset);if(!matches(s,id))throw new SecurityException("HOST_OUTPUT_CONTEXT_CHANGED");return result;}catch(Exception e){return Map.<String,Object>of("status","REJECTED","error",Objects.toString(e.getMessage(),"HOST_OUTPUT_UNAVAILABLE"));}},OUTPUT);}
 public void cancel(UUID operation){cancel(operation,"HOST_CONVERSATION_CANCELLED");}
 public void cancel(UUID operation,String reason){Minecraft.getInstance().execute(()->{var p=queue.get(operation);if(p!=null)cancel(p,reason);});}
 private static void cancel(Pending p,String reason){if(p.result.isDone())return;p.cancellation.compareAndSet("",reason);p.live.set(false);if(!p.started)finish(p,dev.mineagent.runtime.core.host.HostExecutionOutcome.describe(p.request.operation(),Map.of("status","REJECTED","error",p.cancellation.get()),false,p.phase,p.cancellation.get()));}
 private static String contextError(Pending p){var mc=Minecraft.getInstance();if(p.server!=mc.getSingleplayerServer())return "HOST_WORLD_SESSION_CHANGED";if(p.connection!=mc.getConnection())return "HOST_CONNECTION_CHANGED";if(mc.player==null)return "HOST_PLAYER_UNAVAILABLE";if(!p.owner.equals(mc.player.getUUID()))return "HOST_LOCAL_OWNER_CHANGED";return "";}
 private static String t(String source){return dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t(source);}
 private static void progress(Pending p,String phase){p.phase=phase;String label=switch(phase){case "DOWNLOADING_RUNTIME"->"正在下载专用 Python，尚未执行请求。";case "VERIFYING_RUNTIME","VERIFYING_ARCHIVE"->"正在校验 Python 环境，尚未执行请求。";case "EXTRACTING_RUNTIME"->"正在解压专用 Python，尚未执行请求。";case "CREATING_ENVIRONMENT"->"正在创建专用环境，尚未执行请求。";case "BOOTSTRAPPING_PIP"->"正在初始化 Python 安装工具，尚未执行请求。";case "RUNNING"->"环境已就绪，正在执行已确认的请求。";default->"";};if(!label.isEmpty())Minecraft.getInstance().execute(()->{if(!p.result.isDone()&&p.live.get()&&contextError(p).isEmpty())message(Component.literal(t("[本机 Python] ")+t(label)).append(button(t("停止"),"stop",p)));});}
 private static Component outcomeMessage(Map<String,Object> result){
  String status=Objects.toString(result.get("status"),"UNKNOWN"),error=Objects.toString(result.get("error"),"");
  String label=switch(status){case "EXECUTED"->"已完成";case "REJECTED"->"UNKNOWN".equals(result.get("executionState"))?"执行结果尚未确认":"未执行";case "CANCELLED"->"已停止，可能已有部分结果";case "TIMED_OUT"->"执行超时，可能已有部分结果";case "FAILED"->"执行失败";default->"执行结果尚未确认";};
  String reason=switch(error){case "HOST_CONVERSATION_CANCELLED"->"原对话已结束或不再有效。";case "HOST_PLAYER_SESSION_CHANGED","HOST_PLAYER_UNAVAILABLE"->"玩家会话已变化。";case "HOST_WORLD_SESSION_CHANGED","HOST_SERVER_STOPPED"->"已退出原世界或服务器已关闭。";case "HOST_CONNECTION_CHANGED","HOST_CONTEXT_CHANGED"->"原本机连接已变化。";case "HOST_LOCAL_OWNER_CHANGED","HOST_PERMISSION_CHANGED"->"本机账号或执行权限已变化。";case "HOST_USER_CANCELLED"->"已按你的要求停止。";case "HOST_USER_REJECTED_NOT_EXECUTED"->"你已拒绝本次执行。";case "HOST_APPROVAL_EXPIRED"->"本次确认已过期，请重新发起请求。";default->error.isEmpty()?"":"请查看本次操作的错误详情。";};
  var line=Component.literal(t("[本机 Python] ")+t(label)+(reason.isEmpty()?"":" · "+t(reason)));
  if("NOT_STARTED".equals(result.get("executionState")))line.append(Component.literal(" "+t("请求的脚本或安装命令尚未启动。")));
  if(!error.isEmpty())line.withStyle(style->style.withHoverEvent(new HoverEvent.ShowText(Component.literal(error+" · "+result.getOrDefault("phase","")+" · "+result.getOrDefault("operation","")))));
  return line;
 }
 private static void message(Component value){Minecraft.getInstance().gui.getChat().addClientSystemMessage(value);}
 private static MutableComponent button(String label,String action,Pending p){return Component.literal(" ["+label+"]").withStyle(style->style.withColor(net.minecraft.ChatFormatting.AQUA).withClickEvent(new ClickEvent.RunCommand("/mineagent_host "+action+" "+p.token)));}
 private static void prompt(Pending p){message(Component.literal(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("[本机 Python] ")+p.request.purpose()).append(button(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("查看代码"),"view",p)).append(button(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("确认执行"),"approve",p)).append(button(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("拒绝"),"reject",p)));message(Component.literal(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("仅本机当前账号执行；输出返回 AI。首次需下载约21 MiB Python并校验、创建专用环境；可点停止。")+(p.request.kind()==HostCommandRequest.Kind.INSTALL_PACKAGES?dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("第三方库安装可能运行构建代码：")+String.join(", ",p.request.packages()):"" )).withStyle(net.minecraft.ChatFormatting.GRAY));}
 @SubscribeEvent public static void commands(RegisterClientCommandsEvent e){var root=literal("mineagent_host");for(String action:List.of("approve","reject","stop","view"))root.then(literal(action).then(argument("token",StringArgumentType.word()).executes(c->decide(action,StringArgumentType.getString(c,"token")))));e.getDispatcher().register(root);}
 private static int decide(String action,String token){var p=INSTANCE.queue.values().stream().filter(q->q.token.toString().equals(token)).findFirst().orElse(null);var mc=Minecraft.getInstance();if(p==null){INSTANCE.invalidTokenCount++;message(Component.literal(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("[本机 Python] 此确认已失效。")));return 0;}if(!p.live.get())return 0;String contextFailure=contextError(p);if(!contextFailure.isEmpty()){cancel(p,contextFailure);return 0;}if(!p.started&&!p.approved&&System.nanoTime()>p.expires){cancel(p,"HOST_APPROVAL_EXPIRED");return 0;}
  if(action.equals("view")){String text=p.request.script();int start=p.cursor;if(start>=text.length())start=0;int end=Math.min(text.length(),start+1000);if(end<text.length()&&Character.isHighSurrogate(text.charAt(end-1)))end--;message(Component.literal(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("[本机 Python] SHA-256 ")+p.request.sha256()+" · "+p.request.timeoutSeconds()+dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t(" 秒")));message(Component.literal(text.substring(start,end)).withStyle(net.minecraft.ChatFormatting.WHITE));p.cursor=end;message(button(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("继续查看"),"view",p).append(button(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("确认执行"),"approve",p)).append(button(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("拒绝"),"reject",p)));return 1;}
  if(action.equals("reject")||action.equals("stop")){INSTANCE.rejectedCount++;cancel(p,p.started?"HOST_USER_CANCELLED":"HOST_USER_REJECTED_NOT_EXECUTED");return 1;}
  if(p.started||p.approved){INSTANCE.duplicateApproveCount++;return 0;}p.approved=true;INSTANCE.acceptedCount++;message(Component.literal(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("[本机 Python] 已确认，按当前环境队列执行。")).append(button(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("停止"),"stop",p)));dispatchNext();return 1;

 }
 private static void dispatchNext(){
  if(INSTANCE.dispatching||INSTANCE.pending!=null)return;INSTANCE.dispatching=true;try{while(INSTANCE.pending==null){var mc=Minecraft.getInstance();var p=INSTANCE.queue.values().stream().filter(q->q.approved&&!q.started&&q.live.get()).findFirst().orElse(null);if(p==null)return;
  String contextFailure=contextError(p);if(!contextFailure.isEmpty()){cancel(p,contextFailure);continue;}
  INSTANCE.pending=p;p.started=true;message(Component.literal(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("[本机 Python] 准备环境并执行…")).append(button(dev.mineagent.runtime.neoforge.client.language.ClientLanguage.t("停止"),"stop",p)));
  try{IO.submit(()->{Map<String,Object> result;try{result=new LocalPythonExecutor(mc.gameDirectory.toPath()).execute(p.request,p.request.sha256(),p.live::get,p.cancellation::get,phase->progress(p,phase));}catch(Exception failure){result=Map.of("status","UNKNOWN","error","HOST_EXECUTION_FAILED");}var completed=result;mc.execute(()->finish(p,completed));});}catch(Exception e){finish(p,Map.of("status","REJECTED","error","HOST_EXECUTOR_UNAVAILABLE"));}
  }}finally{INSTANCE.dispatching=false;}
 }
 private static void finish(Pending p,Map<String,Object> result){if(p.result.isDone())return;INSTANCE.queue.remove(p.request.operation(),p);if(INSTANCE.pending==p)INSTANCE.pending=null;if(result.containsKey("pid"))INSTANCE.outputs.put(p.request.operation(),new OutputScope(p.server,p.owner));p.result.complete(result);var mc=Minecraft.getInstance();if(p.server==mc.getSingleplayerServer()&&mc.player!=null&&p.owner.equals(mc.player.getUUID()))message(outcomeMessage(result));dispatchNext();}

 private static boolean smokeEnabled(){return Boolean.getBoolean("mineagent.conversationAgentSmoke")||Boolean.getBoolean("mineagent.skillSmoke")&&System.getProperty("mineagent.skillSmokeMode","").equals("host_context");}
 /** Harness-only local view, never exposed through any game/model tool or server packet. */
 public static Map<String,Object> smokeDecisions(){if(!smokeEnabled())return Map.of();return Map.of("accepted",INSTANCE.acceptedCount,"rejected",INSTANCE.rejectedCount,"invalidToken",INSTANCE.invalidTokenCount,"duplicateApprove",INSTANCE.duplicateApproveCount);}
 public static Map<String,Object> smokePending(){if(!smokeEnabled())return Map.of();var p=INSTANCE.queue.values().stream().filter(q->!q.started).findFirst().orElse(null);if(p==null)return Map.of();return Map.of("operation",p.request.operation().toString(),"script",p.request.script(),"kind",p.request.kind().name(),"hash",p.request.sha256(),"approveCommand","mineagent_host approve "+p.token,"rejectCommand","mineagent_host reject "+p.token,"viewCommand","mineagent_host view "+p.token);}
 @SubscribeEvent public static void tick(ClientTickEvent.Post event){var mc=Minecraft.getInstance();var self=INSTANCE;if(!self.installed){self.installed=true;LocalHostCommands.install(self);Runtime.getRuntime().addShutdownHook(new Thread(()->{var active=self.pending;if(active!=null){active.cancellation.compareAndSet("","HOST_SERVER_STOPPED");active.live.set(false);}IO.shutdownNow();OUTPUT.shutdownNow();try{IO.awaitTermination(3,TimeUnit.SECONDS);}catch(InterruptedException ignored){}},"mineagent-python-stop"));}if(self.server!=mc.getSingleplayerServer())self.outputs.clear();self.server=mc.getSingleplayerServer();self.owner=mc.player==null?null:mc.player.getUUID();for(var p:List.copyOf(self.queue.values())){String contextFailure=contextError(p);if(!contextFailure.isEmpty())cancel(p,contextFailure);else if(!p.started&&!p.approved&&System.nanoTime()>p.expires)cancel(p,"HOST_APPROVAL_EXPIRED");}dispatchNext();}
}
