package dev.mineagent.runtime.neoforge.client.host;
import dev.mineagent.runtime.neoforge.host.LocalHostCommands;
import dev.mineagent.runtime.core.host.HostCommandRequest;
import dev.mineagent.runtime.client.host.*;
import net.minecraft.client.Minecraft;
import net.minecraft.server.MinecraftServer;
import net.minecraft.network.chat.*;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.bus.api.SubscribeEvent;
import net.neoforged.fml.common.EventBusSubscriber;
import net.neoforged.neoforge.client.event.*;
import java.util.*;
import java.util.concurrent.*;
import java.util.concurrent.atomic.AtomicBoolean;
import static net.minecraft.commands.Commands.*;
import com.mojang.brigadier.arguments.StringArgumentType;

/** Local-only opaque chat decisions. The approval token is never returned to server tools or the model. */
@EventBusSubscriber(modid="mineagent_runtime",value=Dist.CLIENT)
public final class ClientHostCommands implements LocalHostCommands.Endpoint {
 private static final ClientHostCommands INSTANCE=new ClientHostCommands();
 private static final ExecutorService IO=Executors.newSingleThreadExecutor(r->{var t=new Thread(r,"mineagent-local-python");t.setDaemon(true);return t;});
 private record OutputScope(MinecraftServer server,UUID owner){}
 private final Map<UUID,OutputScope> outputs=new ConcurrentHashMap<>();
 private volatile MinecraftServer server;private volatile UUID owner;private volatile Pending pending;private boolean installed;private int acceptedCount,rejectedCount,invalidTokenCount,duplicateApproveCount;
 private static final class Pending {final HostCommandRequest request;final MinecraftServer server;final UUID owner,token=UUID.randomUUID();final Object connection;final CompletableFuture<Map<String,Object>> result=new CompletableFuture<>();final AtomicBoolean live=new AtomicBoolean(true);final long expires=System.nanoTime()+TimeUnit.MINUTES.toNanos(3);boolean started;int cursor;Pending(HostCommandRequest r,MinecraftServer s,UUID o,Object c){request=r;server=s;owner=o;connection=c;}}
 public boolean matches(MinecraftServer s,UUID id){return server==s&&id.equals(owner);}
 public Map<String,Object> inspect(){var r=new LinkedHashMap<String,Object>();r.put("available",ManagedPythonRuntime.supported());r.put("platform",System.getProperty("os.name","unknown"));r.put("engine","JAVA_MANAGED_PYTHON");r.put("runtime",new ManagedPythonRuntime(Minecraft.getInstance().gameDirectory.toPath()).inspect());r.put("approval","NATIVE_CHAT_CLICK_PER_OPERATION");r.put("scriptMaxChars",8192);r.put("timeoutMaxSeconds",60);r.put("packageInstallTimeoutMaxSeconds",300);r.put("outputPreviewBytesPerStream",LocalPythonExecutor.OUTPUT_BYTES);r.put("workingDirectory","current Minecraft instance/mineagent-host/workspace");r.put("notFilesystemSandbox",true);r.put("remoteServerAccess",false);r.put("systemPythonUsed",false);return r;}
 public CompletableFuture<Map<String,Object>> request(MinecraftServer s,UUID id,HostCommandRequest r){var result=new CompletableFuture<Map<String,Object>>();Minecraft.getInstance().execute(()->{var mc=Minecraft.getInstance();if(!matches(s,id)||mc.getSingleplayerServer()!=s||mc.player==null||!id.equals(mc.player.getUUID())||!ManagedPythonRuntime.supported()){result.complete(Map.of("status","REJECTED","error","HOST_UNAVAILABLE_OR_CONTEXT_CHANGED"));return;}if(pending!=null){result.complete(Map.of("status","REJECTED","error","HOST_COMMAND_BUSY"));return;}var p=new Pending(r,s,id,mc.getConnection());pending=p;p.result.whenComplete((v,e)->{if(e!=null)result.complete(Map.of("status","UNKNOWN","error","HOST_RESULT_UNAVAILABLE"));else result.complete(v);});prompt(p);});return result;}
 public CompletableFuture<Map<String,Object>> output(MinecraftServer s,UUID id,UUID operation,String stream,int offset){return CompletableFuture.supplyAsync(()->{try{var scope=outputs.get(operation);if(!matches(s,id)||scope==null||scope.server()!=s||!scope.owner().equals(id))throw new SecurityException("HOST_OUTPUT_SCOPE");var result=new LocalPythonExecutor(Minecraft.getInstance().gameDirectory.toPath()).output(operation,stream,offset);if(!matches(s,id))throw new SecurityException("HOST_OUTPUT_CONTEXT_CHANGED");return result;}catch(Exception e){return Map.<String,Object>of("status","REJECTED","error",Objects.toString(e.getMessage(),"HOST_OUTPUT_UNAVAILABLE"));}},IO);}
 public void cancel(UUID operation){Minecraft.getInstance().execute(()->{var p=pending;if(p!=null&&p.request.operation().equals(operation))cancel(p,"HOST_CONVERSATION_CANCELLED");});}
 private static void cancel(Pending p,String reason){p.live.set(false);if(!p.started)finish(p,Map.of("status","REJECTED","error",reason));}
 private static void message(Component value){Minecraft.getInstance().gui.getChat().addClientSystemMessage(value);}
 private static MutableComponent button(String label,String action,Pending p){return Component.literal(" ["+label+"]").withStyle(style->style.withColor(net.minecraft.ChatFormatting.AQUA).withClickEvent(new ClickEvent.RunCommand("/mineagent_host "+action+" "+p.token)));}
 private static void prompt(Pending p){message(Component.literal("[本机 Python] "+p.request.purpose()).append(button("查看代码","view",p)).append(button("确认执行","approve",p)).append(button("拒绝","reject",p)));message(Component.literal("仅本机当前账号执行；输出返回 AI。首次需下载约21 MiB Python并校验、创建专用环境；可点停止。"+(p.request.kind()==HostCommandRequest.Kind.INSTALL_PACKAGES?"第三方库安装可能运行构建代码："+String.join(", ",p.request.packages()):"" )).withStyle(net.minecraft.ChatFormatting.GRAY));}
 @SubscribeEvent public static void commands(RegisterClientCommandsEvent e){var root=literal("mineagent_host");for(String action:List.of("approve","reject","stop","view"))root.then(literal(action).then(argument("token",StringArgumentType.word()).executes(c->decide(action,StringArgumentType.getString(c,"token")))));e.getDispatcher().register(root);}
 private static int decide(String action,String token){var p=INSTANCE.pending;var mc=Minecraft.getInstance();if(p==null||!p.token.toString().equals(token)){INSTANCE.invalidTokenCount++;message(Component.literal("[本机 Python] 此确认已失效。"));return 0;}if(!p.live.get()||p.server!=mc.getSingleplayerServer()||p.connection!=mc.getConnection()||mc.player==null||!p.owner.equals(mc.player.getUUID())){cancel(p,"HOST_CONTEXT_CHANGED");return 0;}if(!p.started&&System.nanoTime()>p.expires){cancel(p,"HOST_APPROVAL_EXPIRED");return 0;}
  if(action.equals("view")){String text=p.request.script();int start=p.cursor;if(start>=text.length())start=0;int end=Math.min(text.length(),start+1000);if(end<text.length()&&Character.isHighSurrogate(text.charAt(end-1)))end--;message(Component.literal("[本机 Python] SHA-256 "+p.request.sha256()+" · "+p.request.timeoutSeconds()+" 秒"));message(Component.literal(text.substring(start,end)).withStyle(net.minecraft.ChatFormatting.WHITE));p.cursor=end;message(button("继续查看","view",p).append(button("确认执行","approve",p)).append(button("拒绝","reject",p)));return 1;}
  if(action.equals("reject")||action.equals("stop")){INSTANCE.rejectedCount++;cancel(p,p.started?"HOST_USER_CANCELLED":"HOST_USER_REJECTED_NOT_EXECUTED");return 1;}
  if(p.started){INSTANCE.duplicateApproveCount++;return 0;}p.started=true;INSTANCE.acceptedCount++;message(Component.literal("[本机 Python] 准备环境并执行…").append(button("停止","stop",p)));try{IO.submit(()->{var result=new LocalPythonExecutor(mc.gameDirectory.toPath()).execute(p.request,p.request.sha256(),p.live::get);mc.execute(()->finish(p,result));});}catch(Exception e){finish(p,Map.of("status","REJECTED","error","HOST_EXECUTOR_UNAVAILABLE"));}return 1;
 }
 private static void finish(Pending p,Map<String,Object> result){if(INSTANCE.pending==p)INSTANCE.pending=null;if(result.containsKey("operation"))INSTANCE.outputs.put(p.request.operation(),new OutputScope(p.server,p.owner));p.result.complete(result);message(Component.literal("[本机 Python] "+result.get("status")+(result.containsKey("error")?" · "+result.get("error"):"")));}
 /** Harness-only local view, never exposed through any game/model tool or server packet. */
 public static Map<String,Object> smokeDecisions(){if(!Boolean.getBoolean("mineagent.conversationAgentSmoke"))return Map.of();return Map.of("accepted",INSTANCE.acceptedCount,"rejected",INSTANCE.rejectedCount,"invalidToken",INSTANCE.invalidTokenCount,"duplicateApprove",INSTANCE.duplicateApproveCount);}
 public static Map<String,Object> smokePending(){if(!Boolean.getBoolean("mineagent.conversationAgentSmoke"))return Map.of();var p=INSTANCE.pending;if(p==null||p.started)return Map.of();return Map.of("operation",p.request.operation().toString(),"script",p.request.script(),"kind",p.request.kind().name(),"hash",p.request.sha256(),"approveCommand","mineagent_host approve "+p.token,"rejectCommand","mineagent_host reject "+p.token,"viewCommand","mineagent_host view "+p.token);}
 @SubscribeEvent public static void tick(ClientTickEvent.Post event){var mc=Minecraft.getInstance();var self=INSTANCE;if(!self.installed){self.installed=true;LocalHostCommands.install(self);Runtime.getRuntime().addShutdownHook(new Thread(()->{var active=self.pending;if(active!=null)active.live.set(false);IO.shutdownNow();try{IO.awaitTermination(3,TimeUnit.SECONDS);}catch(InterruptedException ignored){}},"mineagent-python-stop"));}if(self.server!=mc.getSingleplayerServer())self.outputs.clear();self.server=mc.getSingleplayerServer();self.owner=mc.player==null?null:mc.player.getUUID();var p=self.pending;if(p==null)return;if(p.server!=self.server||!p.owner.equals(self.owner)||p.connection!=mc.getConnection())cancel(p,"HOST_CONTEXT_CHANGED");else if(!p.started&&System.nanoTime()>p.expires)cancel(p,"HOST_APPROVAL_EXPIRED");}
}
