package dev.mineagent.runtime.neoforge.client.objects;

import com.google.common.reflect.TypeToken;import com.google.gson.*;import com.mojang.blaze3d.vertex.PoseStack;import com.mojang.math.Axis;
import dev.mineagent.runtime.core.interaction.*;import dev.mineagent.runtime.core.creature.CreatureAnimation;import dev.mineagent.runtime.neoforge.content.RuntimeCreatureEntity;import dev.mineagent.runtime.neoforge.mixin.client.EntityModelPartsAccess;import dev.mineagent.runtime.neoforge.network.UiPayloads;
import net.minecraft.client.Minecraft;import net.minecraft.client.model.Model;import net.minecraft.client.model.geom.ModelPart;import net.minecraft.client.renderer.entity.EntityRenderer;import net.minecraft.client.renderer.entity.state.EntityRenderState;import net.minecraft.resources.Identifier;import net.minecraft.util.context.ContextKey;import net.minecraft.world.entity.Entity;
import net.neoforged.api.distmarker.Dist;import net.neoforged.bus.api.SubscribeEvent;import net.neoforged.fml.common.EventBusSubscriber;import net.neoforged.neoforge.client.renderstate.RegisterRenderStateModifiersEvent;import net.neoforged.neoforge.client.event.ClientTickEvent;
import java.util.*;

@EventBusSubscriber(modid="mineagent_runtime",value=Dist.CLIENT)
public final class EntityVisualClient {
 public record Meta(UUID entity,String dimension,String type,String species,int part,double age){}
 public static final ContextKey<Meta> KEY=new ContextKey<>(Identifier.fromNamespaceAndPath("mineagent_runtime","entity_visual_context"));
 private record Saved(long revision,EntityAnimationSpec spec,int started){}private record Probe(UUID id,UUID entity,int part,int offset,int expires){}
 private record Pose(float x,float y,float z,float xr,float yr,float zr,float xs,float ys,float zs,boolean visible,boolean skip){Pose(ModelPart p){this(p.x,p.y,p.z,p.xRot,p.yRot,p.zRot,p.xScale,p.yScale,p.zScale,p.visible,p.skipDraw);}void restore(ModelPart p){p.x=x;p.y=y;p.z=z;p.xRot=xr;p.yRot=yr;p.zRot=zr;p.xScale=xs;p.yScale=ys;p.zScale=zs;p.visible=visible;p.skipDraw=skip;}Map<String,Object> view(){return Map.of("positionPixels",List.of(x,y,z),"rotationDegrees",List.of(Math.toDegrees(xr),Math.toDegrees(yr),Math.toDegrees(zr)),"scale",List.of(xs,ys,zs),"visible",visible);}}
 private static final Map<UUID,Saved> RULES=new LinkedHashMap<>();private static final Map<UUID,Probe> PROBES=new LinkedHashMap<>();private static final Map<Model<?>,Map<String,ModelPart>> PARTS=new WeakHashMap<>();private static Object connection;private static int ticks;
 public static final Map<String,Map<String,Object>> observed=new LinkedHashMap<>();
 public static Meta metadata(Entity entity){return metadata(entity,entity.tickCount);}
 public static Meta metadata(Entity entity,double age){var owner=BorrowedCreatureVisuals.owner(entity);if(owner!=null)entity=owner;var root=dev.mineagent.runtime.neoforge.ui.ServerEntityInterop.root(entity);return new Meta(root.getUUID(),root.level().dimension().identifier().toString(),net.minecraft.core.registries.BuiltInRegistries.ENTITY_TYPE.getKey(root.getType()).toString(),root instanceof RuntimeCreatureEntity c&&c.species()!=null?c.species().toString():"",dev.mineagent.runtime.neoforge.ui.ServerEntityInterop.partIndex(entity),age);}
 @SubscribeEvent public static void register(RegisterRenderStateModifiersEvent event){event.registerEntityModifier(new TypeToken<EntityRenderer<Entity,EntityRenderState>>(){},(entity,state)->{state.setRenderData(KEY,metadata(entity,state.ageInTicks));blockNativeState(state);});}
 public static void blockNativeState(EntityRenderState state){Meta meta=state.getRenderData(KEY);if(meta==null||RULES.values().stream().noneMatch(r->r.spec().blockNative()&&matches(r.spec(),meta)))return;
  state.ageInTicks=0;if(state instanceof net.minecraft.client.renderer.entity.state.LivingEntityRenderState s){s.walkAnimationPos=0;s.walkAnimationSpeed=0;s.deathTime=0;s.hasRedOverlay=false;s.isFullyFrozen=false;s.isAutoSpinAttack=false;s.isUpsideDown=false;}
  if(state.getClass().getName().startsWith("twilightforest.client.state.entity.Naga"))for(String name:List.of("isDazed","isCharging","stunlessChargeProgress","xRot"))try{var field=state.getClass().getField(name);if(field.getType()==boolean.class)field.setBoolean(state,false);else if(field.getType()==float.class)field.setFloat(state,0);}catch(ReflectiveOperationException ignored){}
 }
 private static void session(){var current=Minecraft.getInstance().getConnection();if(connection!=current){RULES.clear();PROBES.clear();observed.clear();connection=current;}}
 public static void accept(UiPayloads.Event packet){session();try{var a=JsonParser.parseString(packet.json()).getAsJsonObject();if(packet.channel().equals("entityVisualReset")){RULES.clear();return;}if(packet.channel().equals("entityVisualRule")){var rule=a.getAsJsonObject("rule");long revision=rule.get("revision").getAsLong();var old=RULES.get(packet.requestId());if(old!=null&&old.revision()>revision)return;if(a.get("remove").getAsBoolean())RULES.remove(packet.requestId());else RULES.put(packet.requestId(),new Saved(revision,EntityAnimationSpec.parse(rule.get("source").getAsString()),ticks));return;}if(packet.channel().equals("entityAnimationInspect")){PROBES.put(packet.requestId(),new Probe(packet.requestId(),UUID.fromString(a.get("entity").getAsString()),a.get("part").getAsInt(),a.get("offset").getAsInt(),ticks+80));}}catch(Exception e){reply(packet.requestId(),Map.of("status","UNAVAILABLE","error","ENTITY_ANIMATION_BAD_REQUEST"));}}
 private static boolean matches(EntityAnimationSpec s,Meta m){return s.selector().matches(m.dimension(),m.entity().toString(),m.type(),m.species(),m.part());}
 public static Map<String,ModelPart> modelParts(Model<?> model){return PARTS.computeIfAbsent(model,k->{var values=new LinkedHashMap<String,ModelPart>();collect("root",model.root(),values);return values;});}
 private static void collect(String path,ModelPart p,Map<String,ModelPart> out){out.put(path,p);var children=new TreeMap<>(((EntityModelPartsAccess)(Object)p).mineagent$children());children.forEach((name,child)->collect(path+"/"+name.replace("~","~0").replace("/","~1"),child,out));}
 public static void draw(Model<?> model,Object state,PoseStack poses,Runnable original){
  if(state instanceof EntityPartModels.Draw donor){original.run();EntityPartModels.drawn(donor,poses);return;}
  if(!(state instanceof EntityRenderState render)){original.run();return;}Meta meta=render.getRenderData(KEY);if(meta==null||meta.type().equals("minecraft:player")){original.run();return;}
  var rules=RULES.entrySet().stream().filter(e->matches(e.getValue().spec(),meta)).toList();var probes=PROBES.values().stream().filter(p->p.entity().equals(meta.entity())&&p.part()==meta.part()).toList();if(rules.isEmpty()&&probes.isEmpty()&&!EntityPartModels.hasPlan(render)){original.run();return;}
  var parts=modelParts(model);var before=new IdentityHashMap<ModelPart,Pose>();parts.values().forEach(p->before.put(p,new Pose(p)));var missing=new LinkedHashSet<String>();var nativeMatrix=poses.last().pose().get(new float[16]);poses.pushPose();
  try{
   animate(model,meta,poses,parts,missing);
   var hiddenParts=EntityPartModels.hide(render,parts);
   original.run();
   if(!probes.isEmpty()||(Boolean.getBoolean("mineagent.entityInteropSmoke")||Boolean.getBoolean("mineagent.entityPartsSmoke"))){
    var nodes=new ArrayList<Map<String,Object>>();parts.forEach((path,p)->nodes.add(Map.of("path",path,"nativePose",before.get(p).view(),"renderedPose",new Pose(p).view(),"cubes",((EntityModelPartsAccess)(Object)p).mineagent$cubes().size(),"renderedMatrix",partMatrix(path,parts,poses))));
    var data=new LinkedHashMap<String,Object>();data.put("status","OBSERVED_NATIVE_DRAW");data.put("adapter","MODEL_PART");data.put("entity",meta.entity());data.put("part_index",meta.part());data.put("modelClass",model.getClass().getName());data.put("nativeMatrix",nativeMatrix);data.put("renderedMatrix",poses.last().pose().get(new float[16]));data.put("appliedRules",rules.stream().map(Map.Entry::getKey).toList());data.put("missingParts",missing);data.put("partCount",nodes.size());data.put("ageInTicks",meta.age());data.put("hiddenParts",hiddenParts);data.put("replacementErrors",EntityPartModels.errors(render));data.put("replacementDraws",EntityPartModels.draws(render,meta));
    if((Boolean.getBoolean("mineagent.entityInteropSmoke")||Boolean.getBoolean("mineagent.entityPartsSmoke"))){var all=new LinkedHashMap<String,Object>(data);all.put("parts",nodes);observed.put(meta.entity()+":"+meta.part(),all);}
    for(var probe:probes){var page=new LinkedHashMap<String,Object>(data);page.put("parts",nodes.stream().skip(probe.offset()).limit(24).toList());page.put("nextOffset",probe.offset()+24<nodes.size()?probe.offset()+24:-1);reply(probe.id(),page);PROBES.remove(probe.id());}
   }
  }finally{before.forEach((part,pose)->pose.restore(part));poses.popPose();}
 }
 private static float[] partMatrix(String path,Map<String,ModelPart> parts,PoseStack poses){poses.pushPose();try{String prefix="";for(String segment:path.split("/")){prefix=prefix.isEmpty()?segment:prefix+"/"+segment;parts.get(prefix).translateAndRotate(poses);}return poses.last().pose().get(new float[16]);}finally{poses.popPose();}}
 public static Map<String,EntityPartReplacement> replacements(Meta meta){var result=new LinkedHashMap<String,EntityPartReplacement>();for(var saved:RULES.values())if(matches(saved.spec(),meta))result.putAll(saved.spec().replacements());return result;}
 private static void animate(Model<?> model,Meta meta,PoseStack poses,Map<String,ModelPart> parts,Set<String> missing){var rules=RULES.entrySet().stream().filter(e->matches(e.getValue().spec(),meta)).toList();for(var entry:rules){var rule=entry.getValue().spec();double animationTime=Math.max(0,ticks-entry.getValue().started())+(meta.age()-Math.floor(meta.age()));if(rule.blockNative())model.resetPose();double[] root=CreatureAnimation.sample(rule.root(),animationTime);poses.translate(root[0],root[1],root[2]);poses.mulPose(Axis.XP.rotationDegrees((float)root[3]));poses.mulPose(Axis.YP.rotationDegrees((float)root[4]));poses.mulPose(Axis.ZP.rotationDegrees((float)root[5]));poses.scale((float)root[6],(float)root[7],(float)root[8]);for(var track:rule.parts().entrySet()){var p=parts.get(track.getKey());if(p==null){missing.add(track.getKey());continue;}if(!rule.additive())p.resetPose();var tr=CreatureAnimation.sample(track.getValue(),animationTime);p.x+=tr[0]*16;p.y+=tr[1]*16;p.z+=tr[2]*16;p.xRot+=Math.toRadians(tr[3]);p.yRot+=Math.toRadians(tr[4]);p.zRot+=Math.toRadians(tr[5]);p.xScale*=tr[6];p.yScale*=tr[7];p.zScale*=tr[8];}}}
 public static <S> void attachmentPose(Model<? super S> model,S state,PoseStack poses,Runnable body){var parts=modelParts(model);var before=new IdentityHashMap<ModelPart,Pose>();parts.values().forEach(p->before.put(p,new Pose(p)));poses.pushPose();try{model.setupAnim(state);animate(model,((EntityRenderState)state).getRenderData(KEY),poses,parts,new LinkedHashSet<>());body.run();}finally{before.forEach((p,v)->v.restore(p));poses.popPose();}}
 private static void reply(UUID id,Map<String,Object> data){if(Minecraft.getInstance().getConnection()!=null)net.neoforged.neoforge.client.network.ClientPacketDistributor.sendToServer(new UiPayloads.Command(id,"entityAnimationInspectReply",new Gson().toJson(data)));}
 @SubscribeEvent public static void tick(ClientTickEvent.Post e){session();ticks++;for(var p:List.copyOf(PROBES.values()))if(ticks>p.expires()){PROBES.remove(p.id());reply(p.id(),Map.of("status","UNAVAILABLE","error","ENTITY_ANIMATION_NOT_RENDERED_OR_UNSUPPORTED","hint","Look at the loaded entity/part. Only Model/ModelPart submitted geometry is supported; custom shader or proprietary renderers need an adapter."));}}
 private EntityVisualClient(){}
}
