package dev.mineagent.runtime.neoforge.client.objects;
import dev.mineagent.runtime.neoforge.ui.EntityInteropSmokeServer;import net.minecraft.client.Minecraft;import net.neoforged.api.distmarker.Dist;import net.neoforged.bus.api.SubscribeEvent;import net.neoforged.fml.common.EventBusSubscriber;import net.neoforged.neoforge.client.event.ClientTickEvent;import java.util.*;import java.nio.file.*;
@EventBusSubscriber(modid="mineagent_runtime",value=Dist.CLIENT)
public final class EntityInteropSmokeClient {
 private static boolean done,captured;private static double minRoot=Double.POSITIVE_INFINITY,maxRoot=Double.NEGATIVE_INFINITY;private static int ticks;private static volatile boolean writing;
 @SubscribeEvent public static void tick(ClientTickEvent.Post event){if(!EntityInteropSmokeServer.enabled()||done)return;var mc=Minecraft.getInstance();try{
  var root=Files.createDirectories(mc.gameDirectory.toPath().resolve("entity-interop-smoke"));if(++ticks>20000)throw new IllegalStateException("ENTITY_CLIENT_TIMEOUT");if(mc.player==null||mc.level==null)return;mc.options.pauseOnLostFocus=false;if(mc.screen!=null)mc.setScreen(null);mc.player.setYRot(180);mc.player.setXRot(8);
  var live=EntityVisualClient.observed.get(EntityInteropSmokeServer.nagaId+":-1");if(live!=null&&!((List<?>)live.get("appliedRules")).isEmpty()){var delta=new org.joml.Matrix4f().set((float[])live.get("nativeMatrix")).invert().mul(new org.joml.Matrix4f().set((float[])live.get("renderedMatrix")));minRoot=Math.min(minRoot,delta.m31());maxRoot=Math.max(maxRoot,delta.m31());}
  if(EntityInteropSmokeServer.phase.equals("CLIENT_FINAL")&&!captured){var naga=EntityVisualClient.observed.get(EntityInteropSmokeServer.nagaId+":-1");var part=EntityVisualClient.observed.get(EntityInteropSmokeServer.nagaId+":0");var copy=EntityVisualClient.observed.get(EntityInteropSmokeServer.copyId+":-1");if(naga!=null&&part!=null&&copy!=null){require(angle(naga,30),"NAGA_HEAD_ANGLE");require(maxRoot-minRoot>.02,"WHOLE_MODEL_ANIMATION_NOT_MOVING");require(angle(part,45),"NAGA_SEGMENT_ANGLE");require(angle(copy,-30),"DERIVED_HEAD_ANGLE");long count=java.util.stream.StreamSupport.stream(mc.level.entitiesForRendering().spliterator(),false).filter(e->net.minecraft.core.registries.BuiltInRegistries.ENTITY_TYPE.getKey(e.getType()).toString().equals("twilightforest:naga")).count();require(count==1,"VISUAL_PROXY_ADDED_TO_WORLD");Files.writeString(root.resolve("client.json"),new com.google.gson.Gson().toJson(Map.of("status","PASSED","naga",naga,"part",part,"derived",copy,"realNagaCount",count,"rootMovementRange",maxRoot-minRoot,"osInputInjected",false)));captured=true;writing=true;mc.options.hideGui=true;net.minecraft.client.Screenshot.takeScreenshot(mc.getMainRenderTarget(),image->{try(image){image.writeToFile(root.resolve("naga-and-derived.png"));}catch(Exception e){EntityInteropSmokeServer.failure="SCREENSHOT_FAILED";}finally{writing=false;EntityInteropSmokeServer.clientObserved=true;}});}}
  if(EntityInteropSmokeServer.done&&!writing){done=true;mc.stop();}
 }catch(Exception e){EntityInteropSmokeServer.failure=e.toString();try{Files.writeString(mc.gameDirectory.toPath().resolve("entity-interop-smoke/client-failure.json"),e.toString());}catch(Exception ignored){}done=true;mc.stop();}}
 private static boolean angle(Map<String,Object> value,double expected){for(var entry:(List<?>)value.get("parts")){var row=(Map<?,?>)entry;if(row.get("path").equals("root/head")){var pose=(Map<?,?>)row.get("renderedPose");double actual=((Number)((List<?>)pose.get("rotationDegrees")).get(2)).doubleValue();return Math.abs(actual-expected)<.2;}}return false;}
 private static void require(boolean ok,String error){if(!ok)throw new IllegalStateException(error);}
 private EntityInteropSmokeClient(){}
}
