package dev.mineagent.runtime.worker.smoke;
import com.sun.net.httpserver.HttpServer;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.file.*;
import java.nio.charset.StandardCharsets;
import java.util.*;
import java.util.concurrent.atomic.AtomicInteger;
/** Local transport fixture; not a real-model quality result. */
final class NativeMentionControlledProvider implements AutoCloseable {
    private final HttpServer http;private final Path game;private final AtomicInteger calls=new AtomicInteger();
    NativeMentionControlledProvider(Path game)throws Exception{this.game=game;http=HttpServer.create(new java.net.InetSocketAddress("127.0.0.1",0),0);http.createContext("/v1/chat/completions",e->{try{String request=new String(e.getRequestBody().readNBytes(512*1024),StandardCharsets.UTF_8);calls.incrementAndGet();Files.writeString(game.resolve("native-mention-request.json"),request);if(request.contains("NATIVE_COMMAND_REQUEST")){var plan=Map.of("summary","受控验收：修改游戏规则、计分、给予物品并附魔", "commands",List.of("gamerule keep_inventory true","scoreboard objectives add mention_score dummy","scoreboard players set @s mention_score 11","give @s minecraft:apple 2","item replace entity @s weapon.mainhand with minecraft:diamond_sword","enchant @s minecraft:sharpness 3"));byte[] body=new ObjectMapper().writeValueAsBytes(Map.of("choices",List.of(Map.of("message",Map.of("content",new ObjectMapper().writeValueAsString(plan))))));e.sendResponseHeaders(200,body.length);e.getResponseBody().write(body);return;}if(!request.contains("NATIVE_MENTION_HELLO"))throw new IllegalArgumentException("MENTION_PROMPT_MISSING");e.getResponseHeaders().set("Content-Type","text/event-stream");e.sendResponseHeaders(200,0);for(String part:List.of("NATIVE_","MENTION_REPLY")){e.getResponseBody().write(("data: {\"model\":\"local-mention\",\"choices\":[{\"delta\":{\"content\":\""+part+"\"}}]}\n\n").getBytes(StandardCharsets.UTF_8));e.getResponseBody().flush();Thread.sleep(350);}e.getResponseBody().write("data: [DONE]\n\n".getBytes(StandardCharsets.UTF_8));}catch(Exception failure){Files.writeString(game.resolve("native-mention-provider-failure.txt"),failure.toString());}finally{e.close();}});http.start();try(var cfg=dev.mineagent.runtime.core.config.ServerConfigService.open(game.resolve("mineagent-runtime-data/runtime.db"))){var values=Map.of("provider.openai.enabled","true","provider.openai.baseUrl","http://127.0.0.1:"+http.getAddress().getPort()+"/v1/","provider.openai.model","local-mention","provider.openai.apiKey","fixture-only","runtime.initialized","true","voice.output.enabled","false");if(!cfg.apply(new dev.mineagent.runtime.api.config.ConfigPatch(cfg.snapshot().revision(),values),true).accepted())throw new IllegalStateException("MENTION_CONFIG");}}
    void verify(){if(calls.get()!=2||Files.exists(game.resolve("native-mention-provider-failure.txt")))throw new IllegalStateException("MENTION_PROVIDER_COUNT");}
    public void close()throws Exception{http.stop(0);Files.writeString(game.resolve("native-mention-provider.json"),new ObjectMapper().writeValueAsString(Map.of("providerCalls",calls.get(),"paidCalls",0,"origin","CONTROLLED_LOCAL_SSE")));}
}
