package dev.mineagent.runtime.core.compile;

import com.fasterxml.jackson.databind.*;
import java.util.*;

/** Strict requests for FML transformed bytes and Instrumentation-backed loaded-class inspection. */
public record NativeLiveToolRequest(String tool,String kind,UUID classToken,String snapshot,String module,String className,String query,String method,String descriptor,int offset,int textOffset){
    public static final Set<String> TOOLS=Set.of("inspect_native_live_environment","inspect_native_loaded_classes","inspect_native_live_members","inspect_native_live_method_body","inspect_native_transformed_members","inspect_native_transformed_method_body");
    private static final ObjectMapper JSON=new ObjectMapper().enable(DeserializationFeature.FAIL_ON_READING_DUP_TREE_KEY).enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS);
    public NativeLiveToolRequest{if(!TOOLS.contains(tool)||kind==null||snapshot==null||module==null||className==null||query==null||method==null||descriptor==null||offset<0||offset>300000||textOffset<0||textOffset>4000000||!snapshot.matches("(?:[a-f0-9]{64})?")||module.length()>160||className.length()>512||query.length()>128||method.length()>512||descriptor.length()>2048)throw new IllegalArgumentException("NATIVE_LIVE_ARGUMENTS");if(kind.equals("live_state")&&(classToken!=null||!snapshot.isEmpty()||!module.isEmpty()||!className.isEmpty()||!query.isEmpty()||!method.isEmpty()||!descriptor.isEmpty()||offset!=0||textOffset!=0))throw new IllegalArgumentException("NATIVE_LIVE_ARGUMENTS");if(kind.equals("loaded")&&(classToken!=null||!snapshot.isEmpty()||!module.isEmpty()||!className.isEmpty()||!method.isEmpty()||!descriptor.isEmpty()||textOffset!=0))throw new IllegalArgumentException("NATIVE_LIVE_ARGUMENTS");if(kind.equals("live_members")&&(classToken==null||!snapshot.isEmpty()||!module.isEmpty()||!className.isEmpty()||!method.isEmpty()||!descriptor.isEmpty()))throw new IllegalArgumentException("NATIVE_LIVE_ARGUMENTS");if(kind.equals("live_method_body")&&(classToken==null||!snapshot.isEmpty()||!module.isEmpty()||!className.isEmpty()||!query.isEmpty()||method.isBlank()||descriptor.isBlank()||offset>131070))throw new IllegalArgumentException("NATIVE_LIVE_ARGUMENTS");if(kind.equals("transformed_members")&&(classToken!=null||snapshot.isEmpty()||module.isEmpty()||className.isEmpty()||!method.isEmpty()||!descriptor.isEmpty()))throw new IllegalArgumentException("NATIVE_LIVE_ARGUMENTS");if(kind.equals("transformed_method_body")&&(classToken!=null||snapshot.isEmpty()||module.isEmpty()||className.isEmpty()||!query.isEmpty()||method.isBlank()||descriptor.isBlank()||offset>131070))throw new IllegalArgumentException("NATIVE_LIVE_ARGUMENTS");if(kind.endsWith("method_body"))try{java.lang.constant.MethodTypeDesc.ofDescriptor(descriptor);}catch(IllegalArgumentException invalid){throw new IllegalArgumentException("NATIVE_LIVE_ARGUMENTS",invalid);}}
    public static NativeLiveToolRequest parse(String tool,String source){try{if(source==null||source.length()>8192)throw new IllegalArgumentException();var n=JSON.readTree(source);if(!n.isObject())throw new IllegalArgumentException();var keys=new HashSet<String>();n.fieldNames().forEachRemaining(keys::add);String kind=switch(tool){case "inspect_native_live_environment"->"live_state";case "inspect_native_loaded_classes"->"loaded";case "inspect_native_live_members"->"live_members";case "inspect_native_live_method_body"->"live_method_body";case "inspect_native_transformed_members"->"transformed_members";case "inspect_native_transformed_method_body"->"transformed_method_body";default->throw new IllegalArgumentException();};Set<String> wanted=switch(kind){case "live_state"->Set.of();case "loaded"->n.has("offset")?Set.of("query","offset"):Set.of("query");case "live_members"->{var v=new HashSet<>(Set.of("class_token","query"));optional(v,n);yield Set.copyOf(v);}case "live_method_body"->{var v=new HashSet<>(Set.of("class_token","method","descriptor"));optional(v,n);yield Set.copyOf(v);}case "transformed_members"->{var v=new HashSet<>(Set.of("snapshot","module","class","query"));optional(v,n);yield Set.copyOf(v);}case "transformed_method_body"->{var v=new HashSet<>(Set.of("snapshot","module","class","method","descriptor"));optional(v,n);yield Set.copyOf(v);}default->throw new IllegalArgumentException();};if(!keys.equals(wanted))throw new IllegalArgumentException();for(String key:keys)if(!Set.of("offset","text_offset").contains(key)&&!n.path(key).isTextual())throw new IllegalArgumentException();return new NativeLiveToolRequest(tool,kind,uuid(n,"class_token"),text(n,"snapshot"),text(n,"module"),text(n,"class"),text(n,"query"),text(n,"method"),text(n,"descriptor"),number(n,"offset"),number(n,"text_offset"));}catch(Exception invalid){throw new IllegalArgumentException("NATIVE_LIVE_ARGUMENTS",invalid);}}
    private static void optional(Set<String> values,JsonNode n){if(n.has("offset"))values.add("offset");if(n.has("text_offset"))values.add("text_offset");}
    private static UUID uuid(JsonNode n,String key){return n.has(key)?UUID.fromString(n.path(key).textValue()):null;}
    private static String text(JsonNode n,String key){return n.has(key)?n.path(key).textValue():"";}
    private static int number(JsonNode n,String key){if(!n.has(key))return 0;if(!n.path(key).isIntegralNumber()||!n.path(key).canConvertToInt())throw new IllegalArgumentException();return n.path(key).intValue();}
    public String canonical(){try{var value=new LinkedHashMap<String,Object>();switch(kind){case "live_state"->{}case "loaded"->{value.put("query",query);value.put("offset",offset);}case "live_members"->{value.put("class_token",classToken);value.put("query",query);value.put("offset",offset);value.put("text_offset",textOffset);}case "live_method_body"->{value.put("class_token",classToken);value.put("method",method);value.put("descriptor",descriptor);value.put("offset",offset);value.put("text_offset",textOffset);}case "transformed_members"->{value.put("snapshot",snapshot);value.put("module",module);value.put("class",className);value.put("query",query);value.put("offset",offset);value.put("text_offset",textOffset);}case "transformed_method_body"->{value.put("snapshot",snapshot);value.put("module",module);value.put("class",className);value.put("method",method);value.put("descriptor",descriptor);value.put("offset",offset);value.put("text_offset",textOffset);}}return JSON.writeValueAsString(value);}catch(Exception failure){throw new IllegalStateException("NATIVE_LIVE_ENCODING",failure);}}
}
