package dev.mineagent.runtime.core.compile;

import dev.mineagent.runtime.core.content.ContentAddressedStore;
import dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer;
import java.io.*;
import java.lang.classfile.*;
import java.nio.*;
import java.nio.charset.*;
import java.util.*;
import java.util.zip.*;

/** Exact SourceFile attachment plus optional classfile line-table mapping. No source is compiled or executed. */
public final class NativeSourceView {
    public record Result(String module,String className,String method,String descriptor,String sourcePath,String sourceHash,String sourceArchiveHash,String namespace,String mappingConfidence,int mappedStartLine,int mappedEndLine,int pageStartLine,int pageEndLine,int totalLines,String text,int nextOffset,boolean more){}
    private NativeSourceView(){}
    public static Result inspect(NativeCompilationSnapshot snapshot,ContentAddressedStore content,String moduleName,String className,String method,String descriptor,int lineOffset)throws Exception{return inspect(snapshot,content,moduleName,className,method,descriptor,lineOffset,128,64*1024);}
    public static Result inspectAll(NativeCompilationSnapshot snapshot,ContentAddressedStore content,String moduleName,String className,String method,String descriptor)throws Exception{return inspect(snapshot,content,moduleName,className,method,descriptor,0,200000,256*1024);}
    private static Result inspect(NativeCompilationSnapshot snapshot,ContentAddressedStore content,String moduleName,String className,String method,String descriptor,int lineOffset,int maximumLines,int maximumChars)throws Exception{
        if(snapshot==null||content==null||moduleName==null||className==null||className.isBlank()||method==null||descriptor==null||lineOffset<0||lineOffset>200000)throw new IllegalArgumentException("NATIVE_SOURCE_QUERY");var module=snapshot.module(moduleName);if(module.sourceSha256().isEmpty())throw new IllegalStateException("NATIVE_SOURCE_UNAVAILABLE");byte[] classBytes=snapshot.classBytes(content,moduleName,className);var model=ClassFile.of().parse(classBytes);if(!model.thisClass().asInternalName().replace('/','.').equals(className))throw new IllegalStateException("NATIVE_SOURCE_CLASS_CHANGED");String file=model.findAttribute(Attributes.sourceFile()).map(a->a.sourceFile().stringValue()).orElseThrow(()->new IllegalStateException("NATIVE_SOURCE_FILE_ATTRIBUTE_MISSING"));if(file.contains("/")||file.contains("\\")||file.contains("..")||file.isBlank()||file.length()>256)throw new IllegalStateException("NATIVE_SOURCE_FILE_ATTRIBUTE_INVALID");String internal=model.thisClass().asInternalName();int slash=internal.lastIndexOf('/');String path=(slash<0?"":internal.substring(0,slash+1))+file;String source=readSource(content,module,path);var lines=source.split("\\R",-1);int mappedStart=1,mappedEnd=lines.length;String confidence="HASHED_SIBLING_SOURCE_FILE_ATTRIBUTE";
        if(!method.isEmpty()||!descriptor.isEmpty()){if(method.isEmpty()||descriptor.isEmpty())throw new IllegalArgumentException("NATIVE_SOURCE_METHOD_SELECTOR");var body=ClassFileMethodBody.inspectAll(classBytes,method,descriptor);var mapped=body.instructions().stream().mapToInt(ClassFileMethodBody.Step::line).filter(v->v>0).summaryStatistics();if(mapped.getCount()==0){confidence="SOURCE_FILE_ONLY_METHOD_LINES_UNAVAILABLE";mappedStart=mappedEnd=0;}else{confidence="HASHED_SIBLING_SOURCE_CLASSFILE_LINE_TABLE";mappedStart=Math.max(1,mapped.getMin());mappedEnd=Math.min(lines.length,mapped.getMax());}}
        int range=mappedStart==0?0:mappedEnd-mappedStart+1;if(lineOffset>range)throw new IllegalArgumentException("NATIVE_SOURCE_LINE_OFFSET");int pageStart=mappedStart==0?0:mappedStart+lineOffset,pageEnd=pageStart==0?0:Math.min(mappedEnd,pageStart+maximumLines-1);String text="";if(pageStart>0){text=String.join("\n",Arrays.copyOfRange(lines,pageStart-1,pageEnd));if(text.length()>maximumChars)throw new IllegalStateException("NATIVE_SOURCE_TEXT_LIMIT");}int consumed=pageStart==0?0:pageEnd-mappedStart+1;return new Result(moduleName,className,method,descriptor,path,RuntimePackageCanonicalizer.sha256(source),module.sourceSha256(),snapshot.namespace(),confidence,mappedStart,mappedEnd,pageStart,pageEnd,lines.length,text,consumed,consumed<range);
    }
    private static String readSource(ContentAddressedStore content,NativeCompilationSnapshot.Module module,String wanted)throws Exception{
        byte[] raw=NativeCompilationSnapshot.read(content.pathFor(module.sourceSha256()),(int)module.sourceSize());if(raw.length!=module.sourceSize()||!RuntimePackageCanonicalizer.sha256(raw).equals(module.sourceSha256()))throw new IllegalStateException("NATIVE_SOURCE_ARCHIVE_CHANGED");long total=0,auxiliary=0;int files=0,entries=0;byte[] found=null;var names=new HashSet<String>();try(var zip=new ZipInputStream(new ByteArrayInputStream(raw))){ZipEntry entry;while((entry=zip.getNextEntry())!=null){String name=entry.getName();if(name.startsWith("/")||name.contains("..")||name.contains("\\")||name.length()>1024||!names.add(name)||++entries>module.sourceFiles()+1024)throw new IllegalStateException("NATIVE_SOURCE_ENTRY_INVALID");if(entry.isDirectory())continue;if(!name.endsWith(".java")){byte[] ignored=zip.readNBytes(64*1024+1);auxiliary+=ignored.length;if(ignored.length>64*1024||auxiliary>16L*1024*1024)throw new IllegalStateException("NATIVE_SOURCE_ARCHIVE_LIMIT");continue;}byte[] body=zip.readNBytes(1024*1024+1);total+=body.length;if(body.length>1024*1024||total>module.sourceBytes()||++files>module.sourceFiles())throw new IllegalStateException("NATIVE_SOURCE_ARCHIVE_LIMIT");if(name.equals(wanted)){if(found!=null)throw new IllegalStateException("NATIVE_SOURCE_AMBIGUOUS");found=body;}}}
        if(total!=module.sourceBytes()||files!=module.sourceFiles()||found==null)throw new IllegalStateException(found==null?"NATIVE_SOURCE_FILE_MISSING":"NATIVE_SOURCE_ARCHIVE_CHANGED");try{return StandardCharsets.UTF_8.newDecoder().onMalformedInput(CodingErrorAction.REPORT).onUnmappableCharacter(CodingErrorAction.REPORT).decode(ByteBuffer.wrap(found)).toString();}catch(CharacterCodingException invalid){throw new IllegalStateException("NATIVE_SOURCE_ENCODING",invalid);}
    }
}
