package dev.mineagent.runtime.core.compile;

import dev.mineagent.runtime.core.content.ContentAddressedStore;
import dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer;
import java.io.*;
import java.util.*;
import java.util.function.BooleanSupplier;
import java.util.jar.*;
import java.util.zip.*;

/** Rewrites an immutable raw snapshot with explicit CAS class overlays; never mutates the captured base. */
public final class NativeOverlaySnapshot {
    public record Stored(String hash,NativeCompilationSnapshot snapshot){}
    private NativeOverlaySnapshot(){}
    public static Stored apply(NativeCompilationSnapshot raw,ContentAddressedStore content,List<NativeCoderContext.Overlay> values,BooleanSupplier permit)throws Exception{
        if(raw==null||content==null||values==null||values.isEmpty()||values.size()>NativeCoderContext.MAX_TYPES)throw new IllegalArgumentException("NATIVE_OVERLAY_SELECTION");var overlays=new TreeMap<String,NativeCoderContext.Overlay>();for(var value:values){String path=entry(value.className());var old=overlays.putIfAbsent(path,value);if(old!=null&&!old.classRef().equals(value.classRef()))throw new IllegalArgumentException("NATIVE_OVERLAY_CONFLICT");}var found=new HashSet<String>();var modules=new ArrayList<NativeCompilationSnapshot.Module>();long classBytes=raw.classBytes(),sourceBytes=0;int sourceFiles=0;
        for(var module:raw.modules()){if(!permit.getAsBoolean())throw new IllegalStateException("NATIVE_OVERLAY_AUTHORITY_CHANGED");byte[] image=raw.bytes(content,module);var output=new BoundedOutput();boolean changed=false;long delta=0;int scanned=0;try(var input=new ZipInputStream(new ByteArrayInputStream(image));var jar=new JarOutputStream(output)){ZipEntry entry;while((entry=input.getNextEntry())!=null){if(++scanned%512==0&&!permit.getAsBoolean())throw new IllegalStateException("NATIVE_OVERLAY_AUTHORITY_CHANGED");byte[] bytes=input.readNBytes(8*1024*1024+1);if(bytes.length>8*1024*1024)throw new IllegalStateException("NATIVE_OVERLAY_LIMIT");var overlay=overlays.get(entry.getName());if(overlay!=null){if(!overlay.rawClassHash().isEmpty()&&!RuntimePackageCanonicalizer.sha256(bytes).equals(overlay.rawClassHash()))throw new IllegalStateException("NATIVE_OVERLAY_RAW_CHANGED");byte[] live=classBytes(content,overlay);delta+=live.length-bytes.length;bytes=live;changed=true;found.add(entry.getName());}var item=new JarEntry(entry.getName());item.setTime(0);jar.putNextEntry(item);jar.write(bytes);jar.closeEntry();}}
            if(changed){var stored=content.put(output.toByteArray());modules.add(new NativeCompilationSnapshot.Module(module.name(),module.version(),stored.sha256(),stored.size(),module.classes()));classBytes+=delta;}else{modules.add(module);sourceBytes+=module.sourceBytes();sourceFiles+=module.sourceFiles();}}
        var pending=new TreeMap<String,NativeCoderContext.Overlay>();overlays.forEach((key,value)->{if(!found.contains(key))pending.put(key,value);});if(!pending.isEmpty()){if(modules.size()>=512)throw new IllegalStateException("NATIVE_OVERLAY_MODULE_LIMIT");var output=new BoundedOutput();try(var jar=new JarOutputStream(output)){for(var entry:pending.entrySet()){var overlay=entry.getValue();if(!overlay.rawClassHash().isEmpty())throw new IllegalStateException("NATIVE_OVERLAY_RAW_CLASS_MISSING");byte[] bytes=classBytes(content,overlay);var item=new JarEntry(entry.getKey());item.setTime(0);jar.putNextEntry(item);jar.write(bytes);jar.closeEntry();classBytes+=bytes.length;}}var stored=content.put(output.toByteArray());String suffix=RuntimePackageCanonicalizer.sha256(output.toByteArray()).substring(0,16);modules.add(new NativeCompilationSnapshot.Module("mineagent.live.overlay."+suffix,"1",stored.sha256(),stored.size(),pending.size()));}
        var snapshot=new NativeCompilationSnapshot(1,raw.namespace(),raw.physicalSide(),"RAW_MODULE_RESOURCES_WITH_EXPLICIT_LIVE_OVERLAYS",raw.environment(),modules,classBytes,raw.classCount()+pending.size(),sourceBytes,sourceFiles);var stored=content.put(snapshot.encode());NativeCompilationSnapshot.read(content,stored.sha256());return new Stored(stored.sha256(),snapshot);
    }
    private static byte[] classBytes(ContentAddressedStore content,NativeCoderContext.Overlay value)throws Exception{byte[] bytes=NativeCompilationSnapshot.read(content.pathFor(value.classRef()),8*1024*1024);if(!RuntimePackageCanonicalizer.sha256(bytes).equals(value.classHash())||!value.classRef().equals(value.classHash())||!java.lang.classfile.ClassFile.of().parse(bytes).thisClass().asInternalName().replace('/','.').equals(value.className()))throw new IllegalStateException("NATIVE_OVERLAY_CLASS_CHANGED");return bytes;}
    private static String entry(String className){if(className==null||className.isBlank()||className.length()>512||className.contains("..")||className.contains("/")||className.contains("\\")||className.startsWith("java.")||className.startsWith("jdk."))throw new IllegalArgumentException("NATIVE_OVERLAY_CLASS");return className.replace('.','/')+".class";}
    private static final class BoundedOutput extends ByteArrayOutputStream {private void reserve(int length){if(length<0||(long)count+length>256L*1024*1024)throw new IllegalStateException("NATIVE_OVERLAY_LIMIT");}@Override public synchronized void write(int value){reserve(1);super.write(value);}@Override public synchronized void write(byte[] bytes,int offset,int length){Objects.checkFromIndexSize(offset,length,bytes.length);reserve(length);super.write(bytes,offset,length);}}
}
