package dev.mineagent.runtime.core.compile;

import com.fasterxml.jackson.databind.ObjectMapper;
import java.util.*;

/** Strict planner arguments. Identity and authority are always supplied by Native, never by the model. */
public record NativeApiToolRequest(String tool,String snapshot,String module,String className,String query,String methodName,String descriptor,int offset,int textOffset) {
    public static final Set<String> TOOLS=Set.of("inspect_native_environment","refresh_native_api","inspect_native_modules","inspect_native_classes","inspect_native_members","inspect_native_method_body","inspect_native_source");
    private static final ObjectMapper JSON=new ObjectMapper().enable(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_READING_DUP_TREE_KEY).enable(com.fasterxml.jackson.databind.DeserializationFeature.FAIL_ON_TRAILING_TOKENS);
    public NativeApiToolRequest {
        if(!TOOLS.contains(tool)||snapshot==null||module==null||className==null||query==null||methodName==null||descriptor==null||offset<0||offset>300000||textOffset<0||textOffset>4000000||!snapshot.matches("(?:[a-f0-9]{64})?")||module.length()>160||className.length()>512||query.length()>128||methodName.length()>512||descriptor.length()>2048)throw new IllegalArgumentException("NATIVE_API_TOOL_ARGUMENTS");
        if(Set.of("inspect_native_environment","refresh_native_api").contains(tool)&&(!snapshot.isEmpty()||!module.isEmpty()||!className.isEmpty()||!query.isEmpty()||!methodName.isEmpty()||!descriptor.isEmpty()||offset!=0||textOffset!=0))throw new IllegalArgumentException("NATIVE_API_TOOL_ARGUMENTS");
        if(tool.equals("inspect_native_modules")&&(snapshot.isEmpty()||!module.isEmpty()||!className.isEmpty()||!query.isEmpty()||!methodName.isEmpty()||!descriptor.isEmpty()||textOffset!=0))throw new IllegalArgumentException("NATIVE_API_TOOL_ARGUMENTS");
        if(tool.equals("inspect_native_classes")&&(snapshot.isEmpty()||module.isEmpty()||!className.isEmpty()||!methodName.isEmpty()||!descriptor.isEmpty()||textOffset!=0))throw new IllegalArgumentException("NATIVE_API_TOOL_ARGUMENTS");
        if(tool.equals("inspect_native_members")&&(snapshot.isEmpty()||module.isEmpty()||className.isEmpty()||!methodName.isEmpty()||!descriptor.isEmpty()))throw new IllegalArgumentException("NATIVE_API_TOOL_ARGUMENTS");
        if(tool.equals("inspect_native_method_body")){if(snapshot.isEmpty()||module.isEmpty()||className.isEmpty()||!query.isEmpty()||methodName.isBlank()||descriptor.isBlank()||offset>131070)throw new IllegalArgumentException("NATIVE_API_TOOL_ARGUMENTS");try{java.lang.constant.MethodTypeDesc.ofDescriptor(descriptor);}catch(IllegalArgumentException invalid){throw new IllegalArgumentException("NATIVE_API_TOOL_ARGUMENTS",invalid);}}
        if(tool.equals("inspect_native_source")){if(snapshot.isEmpty()||module.isEmpty()||className.isEmpty()||!query.isEmpty()||methodName.isEmpty()!=descriptor.isEmpty()||offset>200000)throw new IllegalArgumentException("NATIVE_API_TOOL_ARGUMENTS");if(!descriptor.isEmpty())try{java.lang.constant.MethodTypeDesc.ofDescriptor(descriptor);}catch(IllegalArgumentException invalid){throw new IllegalArgumentException("NATIVE_API_TOOL_ARGUMENTS",invalid);}}
    }
    public static NativeApiToolRequest parse(String tool,String source){
        try{
            if(source==null||source.length()>8192)throw new IllegalArgumentException();var n=JSON.readTree(source);if(!n.isObject())throw new IllegalArgumentException();var keys=new HashSet<String>();n.fieldNames().forEachRemaining(keys::add);
            Set<String> wanted=switch(tool){case "inspect_native_environment","refresh_native_api"->Set.of();case "inspect_native_modules"->n.has("offset")?Set.of("snapshot","offset"):Set.of("snapshot");case "inspect_native_classes"->n.has("offset")?Set.of("snapshot","module","query","offset"):Set.of("snapshot","module","query");case "inspect_native_members"->{var v=new HashSet<>(Set.of("snapshot","module","class","query"));if(n.has("offset"))v.add("offset");if(n.has("text_offset"))v.add("text_offset");yield Set.copyOf(v);}case "inspect_native_method_body"->{var v=new HashSet<>(Set.of("snapshot","module","class","method","descriptor"));if(n.has("offset"))v.add("offset");if(n.has("text_offset"))v.add("text_offset");yield Set.copyOf(v);}case "inspect_native_source"->{var v=new HashSet<>(Set.of("snapshot","module","class"));if(n.has("method")||n.has("descriptor")){v.add("method");v.add("descriptor");}if(n.has("offset"))v.add("offset");if(n.has("text_offset"))v.add("text_offset");yield Set.copyOf(v);}default->throw new IllegalArgumentException();};
            if(!keys.equals(wanted))throw new IllegalArgumentException();for(String key:keys)if(!Set.of("offset","text_offset").contains(key)&&!n.path(key).isTextual())throw new IllegalArgumentException();
            int offset=integer(n,"offset"),textOffset=integer(n,"text_offset");return new NativeApiToolRequest(tool,text(n,"snapshot"),text(n,"module"),text(n,"class"),text(n,"query"),text(n,"method"),text(n,"descriptor"),offset,textOffset);
        }catch(Exception invalid){throw new IllegalArgumentException("NATIVE_API_TOOL_ARGUMENTS",invalid);}
    }
    private static int integer(com.fasterxml.jackson.databind.JsonNode n,String key){if(!n.has(key))return 0;var value=n.path(key);if(!value.isIntegralNumber()||!value.canConvertToInt())throw new IllegalArgumentException();return value.intValue();}
    private static String text(com.fasterxml.jackson.databind.JsonNode n,String key){return n.has(key)?n.path(key).textValue():"";}
    public String canonical(){try{var value=new LinkedHashMap<String,Object>();switch(tool){case "inspect_native_environment","refresh_native_api"->{}case "inspect_native_modules"->{value.put("snapshot",snapshot);value.put("offset",offset);}case "inspect_native_classes"->{value.put("snapshot",snapshot);value.put("module",module);value.put("query",query);value.put("offset",offset);}case "inspect_native_members"->{value.put("snapshot",snapshot);value.put("module",module);value.put("class",className);value.put("query",query);value.put("offset",offset);value.put("text_offset",textOffset);}case "inspect_native_method_body"->{value.put("snapshot",snapshot);value.put("module",module);value.put("class",className);value.put("method",methodName);value.put("descriptor",descriptor);value.put("offset",offset);value.put("text_offset",textOffset);}case "inspect_native_source"->{value.put("snapshot",snapshot);value.put("module",module);value.put("class",className);if(!methodName.isEmpty()){value.put("method",methodName);value.put("descriptor",descriptor);}value.put("offset",offset);value.put("text_offset",textOffset);}}return JSON.writeValueAsString(value);}catch(Exception e){throw new IllegalArgumentException("NATIVE_API_TOOL_ENCODING",e);}}
    public Map<String,String> arguments(){var value=new LinkedHashMap<String,String>();value.put("kind",switch(tool){case "inspect_native_environment"->"state";case "refresh_native_api"->"refresh";case "inspect_native_modules"->"modules";case "inspect_native_classes"->"classes";case "inspect_native_members"->"members";case "inspect_native_method_body"->"method_body";case "inspect_native_source"->"source";default->throw new IllegalStateException();});if(!snapshot.isEmpty())value.put("snapshot",snapshot);if(!module.isEmpty())value.put("module",module);if(!className.isEmpty())value.put("class",className);if(!query.isEmpty()||Set.of("classes","members").contains(value.get("kind")))value.put("search",query);if(!methodName.isEmpty())value.put("method",methodName);if(!descriptor.isEmpty())value.put("descriptor",descriptor);if(Set.of("modules","classes","members","method_body").contains(value.get("kind")))value.put("offset",Integer.toString(offset));if(value.get("kind").equals("source"))value.put("lineOffset",Integer.toString(offset));if(Set.of("members","method_body","source").contains(value.get("kind")))value.put("textOffset",Integer.toString(textOffset));return Map.copyOf(value);}
}
