package dev.mineagent.runtime.core.compile;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.databind.*;
import dev.mineagent.runtime.core.packages.RuntimePackageCanonicalizer;
import dev.mineagent.runtime.core.persistence.SqliteRuntimeRepository;
import java.nio.charset.StandardCharsets;
import java.nio.file.Path;
import java.time.Clock;
import java.util.*;

/** Durable Native knowledge heads. CURRENT always means one exact snapshot; callers must also check the live snapshot. */
public final class NativeKnowledgeStore implements AutoCloseable {
    private static final String ENTRIES="native_api_knowledge_v1",OPERATIONS="native_api_knowledge_operations_v1";private static final int MAX_ENTRIES=4096,MAX_OPERATIONS=16384;
    public record Entry(UUID knowledgeId,UUID worldId,UUID owner,UUID agent,String label,NativeCoderContext selection,NativeCoderContext.Snapshot context,String semanticHash,String state,String diagnostic,
            @JsonInclude(JsonInclude.Include.NON_NULL) NativeCoderContext candidateSelection,@JsonInclude(JsonInclude.Include.NON_NULL) NativeCoderContext.Snapshot candidateContext,String candidateSemanticHash,
            UUID sourceTask,UUID sourceOperation,UUID lastOperation,String lastFingerprint,long revision,long updatedAt){
        public Entry{if(knowledgeId==null||worldId==null||owner==null||agent==null||sourceTask==null||sourceOperation==null||lastOperation==null||label==null||label.isBlank()||label.length()>128||selection==null||context==null||!context.selectionHash().equals(selection.fingerprint())||!hash(semanticHash)||!Set.of("CURRENT","CHANGED_REVIEW_REQUIRED","MISSING","FORGOTTEN").contains(state)||diagnostic==null||diagnostic.length()>128||candidateSemanticHash==null||lastFingerprint==null||!hash(lastFingerprint)||revision<1||updatedAt<0)throw new IllegalArgumentException("NATIVE_KNOWLEDGE_ENTRY");if(state.equals("CHANGED_REVIEW_REQUIRED")!=(candidateSelection!=null&&candidateContext!=null&&hash(candidateSemanticHash)))throw new IllegalArgumentException("NATIVE_KNOWLEDGE_CANDIDATE");if(candidateContext!=null&&!candidateContext.selectionHash().equals(candidateSelection.fingerprint()))throw new IllegalArgumentException("NATIVE_KNOWLEDGE_CANDIDATE");}
    }
    private record Operation(UUID operationId,UUID owner,UUID agent,String action,String fingerprint,UUID knowledgeId,String state,long revision,long updatedAt){public Operation{if(operationId==null||owner==null||agent==null||knowledgeId==null||!Set.of("PREPARED","COMPLETE").contains(state)||action==null||!action.matches("[A-Z_]{1,48}")||!hash(fingerprint)||revision<1)throw new IllegalArgumentException("NATIVE_KNOWLEDGE_OPERATION");}}
    public record Mutation(Entry entry,boolean duplicate){}
    public record Page(List<Entry> entries,int offset,int nextOffset,boolean more,int total){public Page{entries=List.copyOf(entries);}}
    private final SqliteRuntimeRepository repo;private final UUID world;private final Clock clock;private final ObjectMapper json=new ObjectMapper();private final Map<UUID,Entry> entries=new LinkedHashMap<>();private final Map<UUID,Operation> operations=new LinkedHashMap<>();private boolean closed;
    private NativeKnowledgeStore(Path database,UUID world,Clock clock)throws Exception{this.repo=new SqliteRuntimeRepository(database);this.world=Objects.requireNonNull(world);this.clock=Objects.requireNonNull(clock);try{for(var row:repo.list(world,ENTRIES)){var value=json.readValue(row.payload(),Entry.class);if(!value.worldId().equals(world)||value.revision()!=row.revision())throw new IllegalStateException("NATIVE_KNOWLEDGE_RECORD");entries.put(value.knowledgeId(),value);}for(var row:repo.list(world,OPERATIONS)){var value=json.readValue(row.payload(),Operation.class);if(value.revision()!=row.revision())throw new IllegalStateException("NATIVE_KNOWLEDGE_OPERATION");operations.put(value.operationId(),value);}}catch(Exception failure){repo.close();throw failure;}}
    public static NativeKnowledgeStore open(Path database,UUID world,Clock clock)throws Exception{return new NativeKnowledgeStore(database,world,clock);}
    public synchronized Mutation remember(UUID operation,UUID owner,UUID agent,UUID task,UUID sourceOperation,String label,NativeCoderContext selection,NativeCoderContext.Snapshot context,String semanticHash)throws Exception{
        requireOpen();if(label==null||label.isBlank()||label.length()>128)throw new IllegalArgumentException("NATIVE_KNOWLEDGE_LABEL");validateSelection(selection,context,semanticHash);String selector=selector(selection),fingerprint=fingerprint(Map.of("action","REMEMBER","owner",owner,"agent",agent,"task",task,"source",sourceOperation,"label",label,"selection",selection,"context",context,"semantic",semanticHash));UUID id=id(owner,agent,selector);var begun=begin(operation,owner,agent,"REMEMBER",fingerprint,id);if(begun.state().equals("COMPLETE"))return new Mutation(owned(owner,agent,id),true);var old=entries.get(id);Entry next;
        if(old!=null&&old.lastOperation().equals(operation)&&old.lastFingerprint().equals(fingerprint))next=old;else{long revision=old==null?1:old.revision()+1;next=new Entry(id,world,owner,agent,label,selection,context,semanticHash,"CURRENT","VERIFIED_CURRENT",null,null,"",task,sourceOperation,operation,fingerprint,revision,clock.millis());save(next,old==null?0:old.revision());}finish(begun);return new Mutation(next,false);
    }
    public synchronized Mutation revalidate(UUID operation,UUID owner,UUID agent,UUID knowledge,NativeCoderContext selection,NativeCoderContext.Snapshot context,String semanticHash)throws Exception{
        requireOpen();validateSelection(selection,context,semanticHash);var old=owned(owner,agent,knowledge);if(old.state().equals("FORGOTTEN"))throw new IllegalStateException("NATIVE_KNOWLEDGE_FORGOTTEN");if(!selector(old.selection()).equals(selector(selection)))throw new IllegalArgumentException("NATIVE_KNOWLEDGE_SELECTOR_CHANGED");String fingerprint=fingerprint(Map.of("action","REVALIDATE","owner",owner,"agent",agent,"knowledge",knowledge,"selection",selection,"context",context,"semantic",semanticHash));var begun=begin(operation,owner,agent,"REVALIDATE",fingerprint,knowledge);if(begun.state().equals("COMPLETE"))return new Mutation(owned(owner,agent,knowledge),true);Entry next;
        boolean provenanceSame=old.selection().snapshot().equals(selection.snapshot())&&old.selection().environment().equals(selection.environment())&&old.selection().types().getFirst().moduleHash().equals(selection.types().getFirst().moduleHash());
        if(old.lastOperation().equals(operation)&&old.lastFingerprint().equals(fingerprint))next=old;else if(old.semanticHash().equals(semanticHash)&&provenanceSame)next=mutate(old,old.label(),selection,context,semanticHash,"CURRENT","UNCHANGED_ON_CURRENT_SNAPSHOT",null,null,"",old.sourceTask(),old.sourceOperation(),operation,fingerprint);else next=mutate(old,old.label(),old.selection(),old.context(),old.semanticHash(),"CHANGED_REVIEW_REQUIRED",old.semanticHash().equals(semanticHash)?"PROVENANCE_CHANGED":"CONTENT_CHANGED",selection,context,semanticHash,old.sourceTask(),old.sourceOperation(),operation,fingerprint);save(next,old.revision());finish(begun);return new Mutation(next,false);
    }
    public synchronized Mutation markMissing(UUID operation,UUID owner,UUID agent,UUID knowledge,String diagnostic)throws Exception{return state(operation,owner,agent,knowledge,"MISSING",diagnostic);}
    public synchronized Mutation forget(UUID operation,UUID owner,UUID agent,UUID knowledge)throws Exception{return state(operation,owner,agent,knowledge,"FORGOTTEN","USER_FORGOT");}
    private Mutation state(UUID operation,UUID owner,UUID agent,UUID knowledge,String state,String diagnostic)throws Exception{
        requireOpen();var old=owned(owner,agent,knowledge);if(old.state().equals("FORGOTTEN")&&!state.equals("FORGOTTEN"))throw new IllegalStateException("NATIVE_KNOWLEDGE_FORGOTTEN");if(diagnostic==null||!diagnostic.matches("[A-Z0-9_]{1,80}"))throw new IllegalArgumentException("NATIVE_KNOWLEDGE_DIAGNOSTIC");String fingerprint=fingerprint(Map.of("action",state,"owner",owner,"agent",agent,"knowledge",knowledge,"diagnostic",diagnostic));var begun=begin(operation,owner,agent,state,fingerprint,knowledge);if(begun.state().equals("COMPLETE"))return new Mutation(owned(owner,agent,knowledge),true);Entry next=old.lastOperation().equals(operation)&&old.lastFingerprint().equals(fingerprint)?old:mutate(old,old.label(),old.selection(),old.context(),old.semanticHash(),state,diagnostic,null,null,"",old.sourceTask(),old.sourceOperation(),operation,fingerprint);if(next!=old)save(next,old.revision());finish(begun);return new Mutation(next,false);
    }
    public synchronized Entry get(UUID owner,UUID agent,UUID knowledge){requireOpen();return owned(owner,agent,knowledge);}
    public synchronized Page search(UUID owner,UUID agent,String query,int offset){requireOpen();if(query==null||query.length()>128||offset<0||offset>4096)throw new IllegalArgumentException("NATIVE_KNOWLEDGE_QUERY");String wanted=query.toLowerCase(Locale.ROOT);var all=entries.values().stream().filter(e->e.owner().equals(owner)&&e.agent().equals(agent)&&!e.state().equals("FORGOTTEN")&&searchText(e).contains(wanted)).sorted(Comparator.comparingLong(Entry::updatedAt).reversed().thenComparing(e->e.knowledgeId().toString())).toList();if(offset>all.size())throw new IllegalArgumentException("NATIVE_KNOWLEDGE_OFFSET");var page=all.stream().skip(offset).limit(16).toList();return new Page(page,offset,offset+page.size(),offset+page.size()<all.size(),all.size());}
    public synchronized List<NativeCoderContext> current(UUID owner,UUID agent,List<UUID> ids,String snapshot,String environment){requireOpen();if(ids==null||ids.isEmpty()||ids.size()>16||ids.stream().distinct().count()!=ids.size()||!hash(snapshot)||!hash(environment))throw new IllegalArgumentException("NATIVE_KNOWLEDGE_SELECTION");var result=new ArrayList<NativeCoderContext>();for(var id:ids){var entry=owned(owner,agent,id);if(!entry.state().equals("CURRENT")||!entry.selection().snapshot().equals(snapshot)||!entry.selection().environment().equals(environment))throw new IllegalStateException("NATIVE_KNOWLEDGE_REVALIDATION_REQUIRED");result.add(entry.selection());}return List.copyOf(result);}
    private Entry mutate(Entry old,String label,NativeCoderContext selection,NativeCoderContext.Snapshot context,String semantic,String state,String diagnostic,NativeCoderContext candidate,NativeCoderContext.Snapshot candidateContext,String candidateSemantic,UUID sourceTask,UUID sourceOperation,UUID operation,String fingerprint){return new Entry(old.knowledgeId(),world,old.owner(),old.agent(),label,selection,context,semantic,state,diagnostic,candidate,candidateContext,candidateSemantic,sourceTask,sourceOperation,operation,fingerprint,old.revision()+1,clock.millis());}
    private void validateSelection(NativeCoderContext selection,NativeCoderContext.Snapshot context,String semantic){if(selection==null||selection.types().size()!=1||selection.methods().size()>1||selection.sources().size()>1||!selection.overlays().isEmpty()||context==null||!context.selectionHash().equals(selection.fingerprint())||!hash(semantic))throw new IllegalArgumentException("NATIVE_KNOWLEDGE_SELECTION");}
    private Operation begin(UUID id,UUID owner,UUID agent,String action,String fingerprint,UUID knowledge)throws Exception{var old=operations.get(id);if(old!=null){if(!old.owner().equals(owner)||!old.agent().equals(agent)||!old.action().equals(action)||!old.fingerprint().equals(fingerprint)||!old.knowledgeId().equals(knowledge))throw new IllegalArgumentException("NATIVE_KNOWLEDGE_OPERATION_REUSED");return old;}if(operations.size()>=MAX_OPERATIONS)throw new IllegalStateException("NATIVE_KNOWLEDGE_OPERATION_BUDGET");var value=new Operation(id,owner,agent,action,fingerprint,knowledge,"PREPARED",1,clock.millis());var saved=repo.compareAndSet(world,OPERATIONS,id.toString(),0,json.writeValueAsString(value),clock.millis());if(!saved.accepted())throw new IllegalStateException("NATIVE_KNOWLEDGE_OPERATION_CAS");operations.put(id,value);return value;}
    private void finish(Operation old)throws Exception{if(old.state().equals("COMPLETE"))return;var value=new Operation(old.operationId(),old.owner(),old.agent(),old.action(),old.fingerprint(),old.knowledgeId(),"COMPLETE",old.revision()+1,clock.millis());if(!repo.compareAndSet(world,OPERATIONS,old.operationId().toString(),old.revision(),json.writeValueAsString(value),clock.millis()).accepted())throw new IllegalStateException("NATIVE_KNOWLEDGE_OPERATION_CAS");operations.put(value.operationId(),value);}
    private void save(Entry value,long expected)throws Exception{if(entries.size()>=MAX_ENTRIES&&expected==0)throw new IllegalStateException("NATIVE_KNOWLEDGE_ENTRY_BUDGET");String payload=json.writeValueAsString(value);if(payload.getBytes(StandardCharsets.UTF_8).length>64*1024)throw new IllegalStateException("NATIVE_KNOWLEDGE_ENTRY_LIMIT");if(!repo.compareAndSet(world,ENTRIES,value.knowledgeId().toString(),expected,payload,clock.millis()).accepted())throw new IllegalStateException("NATIVE_KNOWLEDGE_CAS");entries.put(value.knowledgeId(),value);}
    private Entry owned(UUID owner,UUID agent,UUID id){var value=entries.get(id);if(value==null||!value.owner().equals(owner)||!value.agent().equals(agent))throw new SecurityException("NATIVE_KNOWLEDGE_NOT_OWNED");return value;}
    private UUID id(UUID owner,UUID agent,String selector){return UUID.nameUUIDFromBytes(("native-knowledge|"+world+"|"+owner+"|"+agent+"|"+selector).getBytes(StandardCharsets.UTF_8));}
    private static String selector(NativeCoderContext value){var type=value.types().getFirst();var method=value.methods().isEmpty()?null:value.methods().getFirst();return type.module()+"\n"+type.className()+(method==null?"":"\n"+method.name()+"\n"+method.descriptor());}
    private static String searchText(Entry e){return (e.label()+" "+selector(e.selection())+" "+e.state()+" "+e.diagnostic()).toLowerCase(Locale.ROOT);}
    private static String fingerprint(Map<String,?> value){try{return RuntimePackageCanonicalizer.sha256(new ObjectMapper().enable(SerializationFeature.ORDER_MAP_ENTRIES_BY_KEYS).writeValueAsBytes(value));}catch(Exception failure){throw new IllegalStateException("NATIVE_KNOWLEDGE_FINGERPRINT",failure);}}
    private static boolean hash(String value){return value!=null&&value.matches("[a-f0-9]{64}");}
    private void requireOpen(){if(closed)throw new IllegalStateException("NATIVE_KNOWLEDGE_CLOSED");}
    @Override public synchronized void close()throws Exception{if(!closed){closed=true;repo.close();}}
}
