package dev.mineagent.runtime.core.compile;
import dev.mineagent.runtime.core.task.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.nio.charset.StandardCharsets;
import java.util.*;
/** Rebuilds declarations and explicit method implementations only from verified Native receipts in the same task history. */
public final class NativeGenerationContext {
    private static final ObjectMapper JSON=new ObjectMapper();
    private NativeGenerationContext(){}
    public static NativeCoderContext resolve(List<WorldActionJournal.Batch> history,NativeObservationSelection selected,NativeCompilationSnapshot latest,String snapshot,String environment){
        return resolve(history,selected,latest,snapshot,environment,"");
    }
    public static NativeCoderContext resolve(List<WorldActionJournal.Batch> history,NativeObservationSelection selected,NativeCompilationSnapshot latest,String snapshot,String environment,String liveEpoch){
        var requested=new LinkedHashMap<String,Map<String,String>>();var methods=new LinkedHashMap<String,Map<String,String>>();var sources=new LinkedHashMap<String,Map<String,String>>();var overlays=new LinkedHashMap<String,NativeCoderContext.Overlay>();String pinned="";
        for(var operation:selected.operations()){
            WorldActionJournal.Receipt found=null;WorldActionSpec source=null;
            for(var batch:history)for(var receipt:batch.receipts())if(receipt.operationId().equals(operation)){if(found!=null)throw new IllegalStateException("NATIVE_OBSERVATION_AMBIGUOUS");if(receipt.index()<0||receipt.index()>=batch.actions().size()||!receipt.operationId().equals(UUID.nameUUIDFromBytes((batch.batchId()+"|"+receipt.index()).getBytes(StandardCharsets.UTF_8))))throw new IllegalStateException("NATIVE_OBSERVATION_CHANGED");found=receipt;source=batch.actions().get(receipt.index());}
            if(found==null||!found.verified()||source==null||!source.tool().equals(found.tool()))throw new IllegalStateException("NATIVE_OBSERVATION_REQUIRED");boolean raw=Set.of("inspect_native_members","inspect_native_method_body","inspect_native_source").contains(found.tool()),live=Set.of("inspect_native_live_members","inspect_native_live_method_body","inspect_native_transformed_members","inspect_native_transformed_method_body").contains(found.tool());if(!raw&&!live)throw new IllegalStateException("NATIVE_OBSERVATION_REQUIRED");
            if(raw){var request=NativeApiToolRequest.parse(source.tool(),source.options().get("request"));if(!found.after().getOrDefault("snapshot","").equals(request.snapshot()))throw new IllegalStateException("NATIVE_OBSERVATION_CHANGED");if(pinned.isEmpty())pinned=request.snapshot();else if(!pinned.equals(request.snapshot()))throw new IllegalStateException("NATIVE_OBSERVATION_SNAPSHOT_MIXED");requested.putIfAbsent(request.module()+"\n"+request.className(),Map.of("module",request.module(),"class",request.className()));if(found.tool().equals("inspect_native_method_body")){NativeMethodObservation.require(history,request);methods.putIfAbsent(request.module()+"\n"+request.className()+"\n"+request.methodName()+"\n"+request.descriptor(),Map.of("module",request.module(),"class",request.className(),"method",request.methodName(),"descriptor",request.descriptor()));}if(found.tool().equals("inspect_native_source")){NativeSourceObservation.require(history,request);var selectedSource=Map.of("module",request.module(),"class",request.className(),"method",request.methodName(),"descriptor",request.descriptor());sources.putIfAbsent(request.module()+"\n"+request.className()+"\n"+request.methodName()+"\n"+request.descriptor(),selectedSource);if(!request.methodName().isEmpty())methods.putIfAbsent(request.module()+"\n"+request.className()+"\n"+request.methodName()+"\n"+request.descriptor(),selectedSource);}}
            else{var request=NativeLiveToolRequest.parse(source.tool(),source.options().get("request"));if(Set.of("live_method_body","transformed_method_body").contains(request.kind()))NativeLiveObservation.requireMethod(history,request);String observedSnapshot=found.after().getOrDefault("snapshot","");if(observedSnapshot.isEmpty())throw new IllegalStateException("NATIVE_LIVE_SNAPSHOT_REQUIRED");if(pinned.isEmpty())pinned=observedSnapshot;else if(!pinned.equals(observedSnapshot))throw new IllegalStateException("NATIVE_OBSERVATION_SNAPSHOT_MIXED");try{var result=JSON.readTree(found.after().getOrDefault("result","{}"));String provenance=result.path("provenance").asText(),className=result.path("class").asText(),classRef=result.path("classRef").asText(),classHash=result.path("classHash").asText(),rawHash=result.path("rawClassHash").asText(""),epoch=result.path("processEpoch").asText(),module=result.path("module").asText(""),loader=result.path("loader").asText(""),audit=result.path("audit").asText("");String expected=request.kind().startsWith("live_")?"JVM_RETRANSFORM_LIVE_DEFINITION":"FML_TRANSFORM_PIPELINE_PREDEFINE";if(!provenance.equals(expected)||!classRef.equals(classHash)||!classHash.matches("[a-f0-9]{64}")||!rawHash.matches("(?:[a-f0-9]{64})?")||epoch.isEmpty()||!epoch.equals(liveEpoch)||className.isEmpty()||request.kind().startsWith("transformed_")&&(!request.snapshot().equals(observedSnapshot)||!request.module().equals(module)||!request.className().equals(className)))throw new IllegalStateException("NATIVE_LIVE_OBSERVATION_CHANGED");String method=request.kind().endsWith("method_body")?request.method():"",descriptor=request.kind().endsWith("method_body")?request.descriptor():"";var overlay=new NativeCoderContext.Overlay(module,className,classRef,classHash,rawHash,provenance,epoch,loader,method,descriptor,audit);overlays.putIfAbsent(className+"\n"+method+"\n"+descriptor,overlay);}catch(RuntimeException failure){throw failure;}catch(Exception failure){throw new IllegalStateException("NATIVE_LIVE_OBSERVATION_CHANGED",failure);}}
        }
        if(pinned.isEmpty()||!pinned.equals(snapshot))throw new IllegalStateException("NATIVE_OBSERVATION_SNAPSHOT_CHANGED");
        try{NativeCoderContext raw=requested.isEmpty()?new NativeCoderContext(pinned,environment,latest.physicalSide(),latest.mappingStatus(),List.of(),List.of(),List.of(),List.copyOf(overlays.values())):NativeCoderContext.resolve(latest,pinned,environment,List.copyOf(requested.values()),List.copyOf(methods.values()),List.copyOf(sources.values()),()->true);return overlays.isEmpty()?raw:new NativeCoderContext(raw.snapshot(),raw.environment(),raw.physicalSide(),raw.mappingStatus(),raw.types(),raw.methods(),raw.sources(),List.copyOf(overlays.values()));}catch(RuntimeException failure){throw failure;}catch(Exception failure){throw new IllegalStateException("NATIVE_OBSERVATION_CHANGED",failure);}
    }
}
