package dev.mineagent.runtime.core.scheduling;
import com.fasterxml.jackson.databind.*;
import com.fasterxml.jackson.core.*;
import java.time.*;
import java.util.*;
public record ScheduleToolRequest(String tool,ScheduleSpec spec,UUID id,long revision,String state,int offset){
    public static final Set<String> TOOLS=Set.of("create_schedule","inspect_schedule","set_schedule_state","inspect_clock","inspect_schedule_handlers","inspect_schedule_push_targets");
    private static final ObjectMapper JSON=new ObjectMapper(JsonFactory.builder().enable(StreamReadFeature.STRICT_DUPLICATE_DETECTION).build()).enable(DeserializationFeature.FAIL_ON_TRAILING_TOKENS);
    public static ScheduleToolRequest parse(String tool,String source){try{
        if(!TOOLS.contains(tool)||source==null||source.length()>16384)throw new IllegalArgumentException();var n=JSON.readTree(source);
        if(tool.equals("inspect_clock")){keys(n,Set.of(),Set.of());return new ScheduleToolRequest(tool,null,null,0,"",0);}
        if(tool.equals("inspect_schedule_handlers")||tool.equals("inspect_schedule_push_targets")){keys(n,Set.of("instance_id","offset"),Set.of("instance_id"));int offset=Math.toIntExact(integer(n,"offset",0));if(offset<0||offset>128)throw new IllegalArgumentException();return new ScheduleToolRequest(tool,null,UUID.fromString(text(n,"instance_id","")),0,"",offset);}
        if(tool.equals("create_schedule")){
            String kind=text(n,"kind",""),mode=text(n,"mode","");boolean wall=kind.startsWith("WALL"),tick=kind.startsWith("TICK"),repeat=kind.endsWith("PERIODIC"),condition=kind.equals("EVENT_CONDITION");var allowed=new HashSet<>(Set.of("kind","mode","goal","max_model_calls","ttl_seconds","script","push","delivery"));
            if(wall){allowed.addAll(Set.of("at","delay_ms","timezone"));if(repeat)allowed.addAll(Set.of("period_ms","max_occurrences","missed_policy","max_lateness_ms"));}
            if(tick){allowed.add("delay_ticks");if(repeat)allowed.addAll(Set.of("period_ticks","max_occurrences","missed_policy"));}
            if(condition)allowed.addAll(Set.of("subscription_id","subscription_revision","fire_if_initially_matched"));keys(n,allowed,Set.of("kind","mode"));
            if(mode.equals("AGENT_WAKE")&&(!n.has("goal")||!n.has("max_model_calls")))throw new IllegalArgumentException();if(n.has("at")&&n.has("delay_ms"))throw new IllegalArgumentException();
            Long at=n.has("at")?OffsetDateTime.parse(text(n,"at","")).toInstant().toEpochMilli():null;long delay=integer(n,wall?"delay_ms":"delay_ticks",0),period=repeat?integer(n,wall?"period_ms":"period_ticks",-1):0;int count=repeat?Math.toIntExact(integer(n,"max_occurrences",-1)):1;long ttl=Math.multiplyExact(integer(n,"ttl_seconds",wall?60:604800),1000);
            UUID subscription=condition?UUID.fromString(text(n,"subscription_id","")):null;long subRevision=condition?integer(n,"subscription_revision",-1):0;boolean initial=false;if(condition){if(!n.path("fire_if_initially_matched").isBoolean())throw new IllegalArgumentException();initial=n.get("fire_if_initially_matched").booleanValue();}
            var spec=new ScheduleSpec(kind,mode,text(n,"goal",""),at,delay,period,count,ttl,text(n,"timezone","UTC"),text(n,"missed_policy","SKIP"),wall?integer(n,"max_lateness_ms",250):0,subscription,subRevision,initial,Math.toIntExact(integer(n,"max_model_calls",0)),ScriptScheduleConsumer.optional(n),SchedulePushConsumer.optional(n),ScheduleDeliveryConsumer.optional(n));return new ScheduleToolRequest(tool,spec,null,0,"",0);
        }
        if(tool.equals("inspect_schedule")){keys(n,Set.of("schedule_id","offset"),Set.of("schedule_id"));int offset=Math.toIntExact(integer(n,"offset",0));if(offset<0||offset>8192)throw new IllegalArgumentException();return new ScheduleToolRequest(tool,null,UUID.fromString(text(n,"schedule_id","")),0,"",offset);}
        keys(n,Set.of("schedule_id","expected_revision","state"),Set.of("schedule_id","expected_revision","state"));long revision=integer(n,"expected_revision",-1);String state=text(n,"state","");if(revision<1||!Set.of("ACTIVE","PAUSED","CANCELLED").contains(state))throw new IllegalArgumentException();return new ScheduleToolRequest(tool,null,UUID.fromString(text(n,"schedule_id","")),revision,state,0);
    }catch(Exception e){throw new IllegalArgumentException("SCHEDULE_TOOL_ARGUMENTS",e);}}
    public String canonical(){try{var n=new LinkedHashMap<String,Object>();if(tool.equals("create_schedule")){if(spec.script()!=null)n.put("script",spec.script().wire());if(spec.push()!=null)n.put("push",spec.push().wire());if(spec.delivery()!=null)n.put("delivery",spec.delivery().wire());n.put("kind",spec.kind());n.put("mode",spec.mode());n.put("goal",spec.goal());n.put("max_model_calls",spec.maxModelCalls());n.put("ttl_seconds",spec.ttlMillis()/1000);boolean wall=spec.kind().startsWith("WALL"),tick=spec.kind().startsWith("TICK");if(wall){if(spec.atMillis()!=null)n.put("at",Instant.ofEpochMilli(spec.atMillis()).toString());else n.put("delay_ms",spec.delay());n.put("timezone",spec.zone());}if(tick)n.put("delay_ticks",spec.delay());if(spec.kind().endsWith("PERIODIC")){n.put(wall?"period_ms":"period_ticks",spec.period());n.put("max_occurrences",spec.maxOccurrences());n.put("missed_policy",spec.missedPolicy());if(wall)n.put("max_lateness_ms",spec.lateness());}if(spec.kind().equals("EVENT_CONDITION")){n.put("subscription_id",spec.conditionSubscription());n.put("subscription_revision",spec.conditionRevision());n.put("fire_if_initially_matched",spec.initiallyMatched());}}
            else if(tool.equals("inspect_schedule_handlers")||tool.equals("inspect_schedule_push_targets")){n.put("instance_id",id);n.put("offset",offset);}
            else if(!tool.equals("inspect_clock")){n.put("schedule_id",id);if(tool.equals("inspect_schedule"))n.put("offset",offset);else{n.put("expected_revision",revision);n.put("state",state);}}return JSON.writeValueAsString(n);
        }catch(Exception e){throw new IllegalArgumentException("SCHEDULE_TOOL_ENCODING",e);}}
    private static void keys(JsonNode n,Set<String> allowed,Set<String> required){if(n==null||!n.isObject())throw new IllegalArgumentException();var keys=new HashSet<String>();n.fieldNames().forEachRemaining(keys::add);if(!allowed.containsAll(keys)||!keys.containsAll(required))throw new IllegalArgumentException();}
    private static String text(JsonNode n,String name,String fallback){if(!n.has(name))return fallback;if(!n.get(name).isTextual())throw new IllegalArgumentException();return n.get(name).asText();}
    private static long integer(JsonNode n,String name,long fallback){if(!n.has(name))return fallback;if(!n.get(name).isIntegralNumber()||!n.get(name).canConvertToLong())throw new IllegalArgumentException();return n.get(name).longValue();}
}
