package dev.mineagent.runtime.core.scheduling;
import java.time.ZoneId;
import java.util.*;
public record ScheduleSpec(String kind,String mode,String goal,Long atMillis,long delay,long period,int maxOccurrences,long ttlMillis,String zone,String missedPolicy,long lateness,UUID conditionSubscription,long conditionRevision,boolean initiallyMatched,int maxModelCalls,
                           @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL) ScriptScheduleConsumer script,
                           @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL) SchedulePushConsumer push,
                           @com.fasterxml.jackson.annotation.JsonInclude(com.fasterxml.jackson.annotation.JsonInclude.Include.NON_NULL) ScheduleDeliveryConsumer delivery) {
    public ScheduleSpec(String kind,String mode,String goal,Long atMillis,long delay,long period,int maxOccurrences,long ttlMillis,String zone,String missedPolicy,long lateness,UUID conditionSubscription,long conditionRevision,boolean initiallyMatched,int maxModelCalls,ScriptScheduleConsumer script,SchedulePushConsumer push){this(kind,mode,goal,atMillis,delay,period,maxOccurrences,ttlMillis,zone,missedPolicy,lateness,conditionSubscription,conditionRevision,initiallyMatched,maxModelCalls,script,push,null);}
    public ScheduleSpec(String kind,String mode,String goal,Long atMillis,long delay,long period,int maxOccurrences,long ttlMillis,String zone,String missedPolicy,long lateness,UUID conditionSubscription,long conditionRevision,boolean initiallyMatched,int maxModelCalls,ScriptScheduleConsumer script){this(kind,mode,goal,atMillis,delay,period,maxOccurrences,ttlMillis,zone,missedPolicy,lateness,conditionSubscription,conditionRevision,initiallyMatched,maxModelCalls,script,null);}
    public ScheduleSpec(String kind,String mode,String goal,Long atMillis,long delay,long period,int maxOccurrences,long ttlMillis,String zone,String missedPolicy,long lateness,UUID conditionSubscription,long conditionRevision,boolean initiallyMatched,int maxModelCalls){this(kind,mode,goal,atMillis,delay,period,maxOccurrences,ttlMillis,zone,missedPolicy,lateness,conditionSubscription,conditionRevision,initiallyMatched,maxModelCalls,null);}
    public ScheduleSpec{
        if(!Set.of("WALL_ONCE","WALL_PERIODIC","TICK_ONCE","TICK_PERIODIC","EVENT_CONDITION").contains(kind)||!Set.of("RECORD_ONLY","AGENT_WAKE","SCRIPT","STATE_PUSH","CONTENT_DELIVERY").contains(mode)||goal==null||goal.codePointCount(0,goal.length())>200||!ZoneId.getAvailableZoneIds().contains(zone)||!Set.of("SKIP","COALESCE").contains(missedPolicy)||ttlMillis<1000||ttlMillis>2_592_000_000L||delay<0||period<0||maxOccurrences<1||maxOccurrences>32||lateness<0||lateness>10000)throw new IllegalArgumentException("SCHEDULE_ARGUMENTS");
        if(mode.equals("SCRIPT")!=(script!=null)||mode.equals("STATE_PUSH")!=(push!=null)||mode.equals("CONTENT_DELIVERY")!=(delivery!=null)||(script!=null?1:0)+(push!=null?1:0)+(delivery!=null?1:0)>1)throw new IllegalArgumentException("SCHEDULE_CONSUMER_MODE");
        if(!mode.equals("AGENT_WAKE")?(!goal.isEmpty()||maxModelCalls!=0):(goal.isBlank()||maxModelCalls<1||maxModelCalls>16))throw new IllegalArgumentException("SCHEDULE_MODEL_BUDGET_REQUIRED");
        boolean wall=kind.startsWith("WALL"),ticks=kind.startsWith("TICK"),repeat=kind.endsWith("PERIODIC");
        if(atMillis!=null&&(!wall||atMillis<0||delay!=0)||wall&&delay>2_592_000_000L||ticks&&delay>32_000_000L||repeat&&(period<(wall?1000:1)||period>(wall?604800000L:1_000_000L))||!repeat&&(period!=0||maxOccurrences!=1||!missedPolicy.equals("SKIP")))throw new IllegalArgumentException("SCHEDULE_TIMING");
        if(kind.equals("EVENT_CONDITION")?(conditionSubscription==null||conditionRevision<1||delay!=0||atMillis!=null):(conditionSubscription!=null||conditionRevision!=0||initiallyMatched))throw new IllegalArgumentException("SCHEDULE_CONDITION");
    }
}
