package dev.mineagent.runtime.core.geometry;
import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import java.util.*;
class WorldGeometryTest {
    private WorldGeometry.Plan plan(String part){return WorldGeometry.parse("{\"origin\":[10,80,20],\"parts\":["+part+"]}");}
    private WorldGeometry.Plan shape(String props){return plan("{\"material\":\"minecraft:stone\","+props+"}");}
    private boolean has(WorldGeometry.Plan p,int x,int y,int z){return p.cells().stream().anyMatch(c->c.pos().equals(new WorldGeometry.Pos(10+x,80+y,20+z)));}
    @Test void solidWallsAndShell(){String base="\"kind\":\"box\",\"min\":[0,0,0],\"max\":[4,4,4]";assertEquals(125,shape(base).cells().size());var walls=shape(base+",\"mode\":\"walls\"");assertEquals(80,walls.cells().size());assertFalse(has(walls,2,0,2));var shell=shape(base+",\"mode\":\"shell\"");assertEquals(98,shell.cells().size());assertTrue(has(shell,2,0,2));assertFalse(has(shell,2,2,2));}
    @Test void polylineConnectsEndpoints(){var p=shape("\"kind\":\"line\",\"points\":[[0,0,0],[4,2,1],[7,2,1]]");assertTrue(has(p,0,0,0));assertTrue(has(p,4,2,1));assertTrue(has(p,7,2,1));assertTrue(p.cells().size()>=8);}
    @Test void planeAndTwistedSurface(){var p=shape("\"kind\":\"plane\",\"points\":[[0,0,0],[4,0,0],[0,0,3]]");assertEquals(20,p.cells().size());var s=shape("\"kind\":\"surface\",\"points\":[[0,0,0],[4,0,0],[0,0,4],[4,4,4]]");assertTrue(has(s,4,4,4));assertTrue(has(s,2,1,2));}
    @Test void concavePolygonExtrudesWithoutFillingNotch(){var p=shape("\"kind\":\"polygon\",\"points\":[[0,0,0],[4,0,0],[4,0,1],[1,0,1],[1,0,4],[0,0,4]],\"height\":3");assertTrue(has(p,0,2,4));assertFalse(has(p,3,0,3));assertFalse(has(p,0,3,0));}
    @Test void rejectsInvalidPolygons(){assertThrows(IllegalArgumentException.class,()->shape("\"kind\":\"polygon\",\"points\":[[0,0,0],[4,0,4],[0,0,4],[4,0,0]],\"height\":1"));assertThrows(IllegalArgumentException.class,()->shape("\"kind\":\"polygon\",\"points\":[[0,0,0],[4,1,0],[0,0,4]],\"height\":1"));}
    @Test void slopeAndThinRoof(){var solid=shape("\"kind\":\"slope\",\"min\":[0,0,0],\"max\":[4,4,2]");assertEquals(45,solid.cells().size());var roof=shape("\"kind\":\"slope\",\"min\":[0,0,0],\"max\":[4,4,2],\"thickness\":1");assertEquals(15,roof.cells().size());assertTrue(has(roof,4,4,1));assertFalse(has(roof,4,3,1));}
    @Test void bezierArchIsNotControlPolygon(){var p=shape("\"kind\":\"curve\",\"points\":[[0,0,0],[0,8,0],[8,8,0],[8,0,0]]");assertTrue(has(p,4,6,0));assertFalse(has(p,0,8,0));assertTrue(has(p,8,0,0));}
    @Test void cylinderAndDomeShell(){var c=shape("\"kind\":\"cylinder\",\"center\":[0,0,0],\"radius\":[3,2],\"height\":4,\"thickness\":1");assertFalse(has(c,0,0,0));assertTrue(has(c,3,3,0));var dome=shape("\"kind\":\"dome\",\"center\":[0,0,0],\"radius\":[4,4,4],\"thickness\":1");assertTrue(has(dome,0,4,0));assertFalse(has(dome,0,-4,0));assertFalse(has(dome,0,1,0));}
    @Test void ellipsoidIncludesLowerHalf(){var e=shape("\"kind\":\"ellipsoid\",\"center\":[0,0,0],\"radius\":[2,3,4]");assertTrue(has(e,0,-3,0));assertTrue(has(e,0,3,0));assertFalse(has(e,2,3,4));}
    @Test void orientationOrderIsPreserved(){var p=plan("{\"kind\":\"box\",\"min\":[1,0,2],\"max\":[1,0,2],\"material\":\"minecraft:oak_stairs[facing=north]\",\"transforms\":[{\"op\":\"rotate\",\"turns\":1},{\"op\":\"mirror\",\"axis\":\"x\"},{\"op\":\"translate\",\"offset\":[0,1,0]}]}");assertTrue(has(p,2,1,1));assertEquals(List.of("r1","mx"),p.cells().getFirst().orientation());}
    @Test void arraysAndArcLengthRepeat(){var p=shape("\"kind\":\"box\",\"min\":[0,0,0],\"max\":[0,0,0],\"transforms\":[{\"op\":\"array\",\"count\":[2,3,1],\"step\":[4,5,0]}]");assertEquals(6,p.cells().size());assertTrue(has(p,4,10,0));var path=shape("\"kind\":\"box\",\"min\":[0,0,0],\"max\":[0,0,0],\"transforms\":[{\"op\":\"path\",\"points\":[[0,0,0],[3,0,0],[3,0,5]],\"spacing\":2,\"orient\":true}]");assertEquals(5,path.cells().size());assertTrue(has(path,3,0,1));assertTrue(has(path,3,0,5));}
    @Test void materialsAreDeterministicAndLocal(){String p="{\"kind\":\"box\",\"min\":[-2,0,0],\"max\":[6,2,2],\"material\":{\"mode\":\"weighted\",\"states\":[\"minecraft:stone\",\"minecraft:andesite\"],\"weights\":[1,3],\"seed\":37}}";assertEquals(plan(p),plan(p));assertEquals(2,plan(p).cells().stream().map(WorldGeometry.Cell::state).distinct().count());var c=plan(p.replace("weighted","checker").replace(",\"weights\":[1,3]",""));assertNotEquals(c.cells().get(0).state(),c.cells().get(1).state());}
    @Test void layerAndStripeRules(){String p="{\"kind\":\"line\",\"points\":[[0,-1,0],[0,3,0]],\"material\":{\"mode\":\"layers\",\"axis\":\"y\",\"states\":[\"minecraft:stone\",\"minecraft:andesite\"]}}";assertEquals("minecraft:stone",plan(p).cells().getFirst().state());assertEquals("minecraft:andesite",plan(p).cells().getLast().state());assertEquals("minecraft:stone",plan(p.replace("layers","stripe")).cells().get(3).state());}
    @Test void lastPartWinsAndMaskIsRetained(){String box="{\"kind\":\"box\",\"min\":[0,0,0],\"max\":[0,0,0],\"material\":\"minecraft:stone\"}";var p=WorldGeometry.parse("{\"origin\":[0,0,0],\"parts\":["+box+","+box.replace("stone","gold_block")+"],\"replace\":[\"minecraft:air\"]}");assertEquals(1,p.cells().size());assertEquals("minecraft:gold_block",p.cells().getFirst().state());assertEquals(List.of("minecraft:air"),p.replace());}
    @Test void malformedAndOversizedPlansAreRejectedNeverTruncated(){assertThrows(IllegalArgumentException.class,()->shape("\"kind\":\"box\",\"min\":[0,0,0],\"max\":[100,100,100]"));assertThrows(IllegalArgumentException.class,()->shape("\"kind\":\"box\",\"min\":[0,0,0],\"max\":[0,0,0],\"typo\":0"));assertThrows(IllegalArgumentException.class,()->WorldGeometry.parse("{\"origin\":[0,0,0],\"origin\":[0,0,0],\"parts\":[]}"));assertThrows(IllegalArgumentException.class,()->WorldGeometry.parse("{}{}"));}
    @Test void contractToolsAreActuallyAdmitted(){var tools=dev.mineagent.runtime.core.conversation.ConversationTools.class;assertFalse(dev.mineagent.runtime.core.conversation.ConversationTools.mutation("inspect_world_geometry"));assertFalse(dev.mineagent.runtime.core.conversation.ConversationTools.mutation("plan_world_geometry"));assertTrue(dev.mineagent.runtime.core.conversation.ConversationTools.NAMES.contains("apply_world_geometry"));}
}
